<html>
	<head>
		<title><?php echo $this->escape($this->title);?></title>
		<link href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet" type="text/css">

	<?php
    require_once('views/helpers/ScriptContainer.php');
    print ScriptContainer::$instance->renderCSSHead();
	print ScriptContainer::$instance->renderJSHead();
	?>
    
		<script type="text/javascript" charset="utf-8">
			$(document).ready(function() {
				$( ".calendarbox" ).datepicker({
					changeMonth: true,
					changeYear: true
				});
				/* Add a click handler to the rows - this could be used as a callback */
				$(".tablegrid tbody").click(function(event) {
					$(oTable.fnSettings().aoData).each(function (){
						$(this.nTr).removeClass('row_selected');
					});
					$(event.target.parentNode).addClass('row_selected');
				});
	 
				/* Add a click handler for the delete row */
				$('#delete').click( function() {
					var anSelected = fnGetSelected( oTable );
					oTable.fnDeleteRow( anSelected[0] );
				} );
	 
				/* Init the table */
				oTable = $('.tablegrid').dataTable({
					"bJQueryUI": true,
					"sPaginationType": "full_numbers"
				});
			} );

			/* Get the rows which are currently selected */
			function fnGetSelected( oTableLocal ){
				var aReturn = new Array();
				var aTrs = oTableLocal.fnGetNodes();
				 
				for ( var i=0 ; i<aTrs.length ; i++ ){
					if ( $(aTrs[i]).hasClass('row_selected') ){
						aReturn.push( aTrs[i] );
					}
				}
				return aReturn;
			}
		</script>
	</head>
	<body>
    
     <div id="pageHolder">
			<div id="header"><?php require_once('views/scripts/preheader.phtml');?></div>
            <div id="content">
			<div id="subcontent">
				<div id="contentheader">
					<h2><?php echo t('Exams associated with the cohort'); ?></h2>
					<br>
			
				</div>
				<div class="pad50 clear"></div>
				<form  action="<?php echo $this->escape($this->action); ?>" id="peopleadd" method="post">
				<div class="mainformholder">
                    
 					<label><?php echo t('Name'); ?></label>
					<input type="text" name="name" size="32" maxlength="32">
                    
                    <label><?php echo t('Date'); ?></label>
					<input type="text" name="classdate" size="32" maxlength="32" class="calendarbox">

					<label><?php echo t('Participant Count'); ?></label>
					<input type="text" name="count" size="32" maxlength="32">

                </div>
                
         <div  style="margin:-130px 0 0 400px;">
        <a href="<?php echo Settings::$COUNTRY_BASE_URL.'/cohort/cohortedit' ?>" class="tsbutton green large"><?php echo t('Go back'); ?> &raquo;</a> 
		<input type="submit" name="add" value="<?php echo t('Add'); ?> &raquo;" class="tsbutton green large">
					</div>


                </form>
               
				</div>
            </div>
		</div>
        				

		<div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
        </div>
	</body>
</html>