<html>
	<head>
		<title><?php echo $this->escape($this->title);?></title>
		<link href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet" type="text/css">

<?php
    require_once('views/helpers/ScriptContainer.php');
    print ScriptContainer::$instance->renderCSSHead();
	print ScriptContainer::$instance->renderJSHead();
?>

		<style>
			fieldset input[type=text], fieldset select { margin-bottom:12px; width:95%; padding: .4em; }
			fieldset { padding:0; border:0; margin-top:25px; text-align : left; font-size : .9em }
			h1 { font-size: 1.2em; margin: .6em 0; }
			.ui-dialog .ui-state-error { padding: .3em; }
			.validateTips { border: 1px solid transparent; padding: 0.3em; }
		</style>
		<script>
			$(function() {
				$( "#dialog-form-student" ).dialog({
					autoOpen: false,
					height: 460,
					width: 750,
					modal: true,
					buttons: {
						<?php echo t('Update')?>: function() {
							$('#dialog-form-student select[name="_length"]')
								.append('<option value="1000">1000</option>')
								.val(1000)
								.change();
							document.getElementById('studentform').submit();
						},
						<?php echo t('Cancel')?>: function() {
							$( this ).dialog( "close" );
						}
					},
					close: function() {
						//allFields.val( "" ).removeClass( "ui-state-error" );
					}
				});

				$( "#studentpopupbutton" )
					.button()
					.click(function() {
						$( "#dialog-form-student" ).dialog( "open" );
					});


				$( "#dialog-form-license" ).dialog({
					autoOpen: false,
					height: 300,
					width: 400,
					modal: true,
					buttons: {
						<?php echo t('Save')?>: function() {
							document.getElementById('licenseform').submit();
						},
						<?php echo t('Cancel')?>: function() {
							$( this ).dialog( "close" );
						}
					},
					close: function() {
						//allFields.val( "" ).removeClass( "ui-state-error" );
					}
				});

				$( "#licensepopupbutton" )
					.button()
					.click(function() {
						$('#dialog-form-license').dialog('option', 'title', '<?php echo t('Add a license'); ?>');
						$("#licenseid").val("0");

						$("#licensename").val("");
						$("#licensedate").val("");

						$( "#dialog-form-license" ).dialog( "open" );
				});

				$( "#dialog-form-class" ).dialog({
					autoOpen: false,
					height: 460,
					width: 750,
					modal: true,
					buttons: {
						<?php echo t('Update')?>: function() {
							document.getElementById('classform').submit();
						},
						<?php echo t('Cancel')?>: function() {
							$( this ).dialog( "close" );
						}
					},
					close: function() {
						//allFields.val( "" ).removeClass( "ui-state-error" );
					}
				});

				$( "#classpopupbutton" )
					.button()
					.click(function() {
						$( "#dialog-form-class" ).dialog( "open" );
				});


				$( "#dialog-form-practicum" ).dialog({
					autoOpen: false,
					height: 580,
					width: 400,
					modal: true,
					buttons: {
						<?php echo t('Save')?>: function() {
							document.getElementById('practicumform').submit();
						},
						<?php echo t('Cancel')?>: function() {
							$( this ).dialog( "close" );
						}
					},
					close: function() {
						//allFields.val( "" ).removeClass( "ui-state-error" );
					}
				});

				$( "#practicumpopupbutton" )
					.button()
					.click(function() {
						$('#dialog-form-practicum').dialog('option', 'title', '<?php echo t('Add a practicum'); ?>');
						$("#practicumid").val("0");

						$("#practicumname").val("");
						$("#practicumdate").val("");
						$("#facilityid").val("");
						$("#advisorid").val("");
						$("#hoursrequired").val("");

						$( "#dialog-form-practicum" ).dialog( "open" );
				});


			});
			function licenseedititem(iid,nm,dt){
				$('#dialog-form-license').dialog('option', 'title', '<?php echo t('Update a license'); ?>');
				$("#licenseid").val(iid);

				$("#licensename").val(nm);
				$("#licensedate").val(dt);

				$( "#dialog-form-license" ).dialog( "open" );
			}
			function practicumedititem(iid,nm,dt,fid,aid,hreq,hfin){
				$('#dialog-form-practicum').dialog('option', 'title', '<?php echo t('Update a practicum'); ?>');
				$("#practicumid").val(iid);

				$("#practicumname").val(nm);
				$("#practicumdate").val(dt);
				$("#facilityid").val(fid);
				$("#advisorid").val(aid);
				$("#hoursrequired").val(hreq);

				$( "#dialog-form-practicum" ).dialog( "open" );
			}
		</script>



		<script type="text/javascript" charset="utf-8">
			$(document).ready(function() {
				$( ".calendarbox" ).datepicker({
					changeMonth: true,
					changeYear: true,
					yearRange: "c-50:+50",
				});

				/* Add a click handler to the rows - this could be used as a callback */
				$(".tablegrid tbody").click(function(event) {
					$(oTable.fnSettings().aoData).each(function (){
						$(this.nTr).removeClass('row_selected');
					});
					$(event.target.parentNode).addClass('row_selected');
				});

				/* Add a click handler for the delete row */
/*
				$('#delete').click( function() {
					var anSelected = fnGetSelected( oTable );
					oTable.fnDeleteRow( anSelected[0] );
				} );
*/
				/* Init the table */
				oTable = $('.tablegrid').dataTable({
					"bJQueryUI": true,
					"sPaginationType": "full_numbers"
				});
			} );

			/* Get the rows which are currently selected */
			function fnGetSelected( oTableLocal ){
				var aReturn = new Array();
				var aTrs = oTableLocal.fnGetNodes();

				for ( var i=0 ; i<aTrs.length ; i++ ){
					if ( $(aTrs[i]).hasClass('row_selected') ){
						aReturn.push( aTrs[i] );
					}
				}
				return aReturn;
			}
		</script>
	</head>
	<body>

<div id="dialog-form-student" title="<?php echo t("Update students")?>">
	<form method="post" name="studentform" id="studentform">
		<input type="hidden" name="action" id="action" value="students">
		<input type="hidden" name="id" id="id" value="<?php echo $this->id; ?>">
		<table cellpadding="0" cellspacing="0" border="0" class="display tablegrid" id="" style="width:100%">
			<thead>
				<tr>
					<th><?php echo t('Student Id'); ?></th>
					<th><?php echo t('Name'); ?></th>
					<th><?php echo t('Gender'); ?></th>
					<th><?php echo t('DOB'); ?></th>
				</tr>
			</thead>
			<tbody>
				<?php
				foreach ($this->allStudents as $row){
					$found = false;
					$sid = 0;
					foreach ($this->cohortStudents as $subrow){
						if ($subrow['id'] == $row['id']){
							$sid = $subrow['studentid'];
							$found = true;
						}
					}
					?>
					<tr class="GradeA">
						<td><input type="checkbox" name="students[<?php echo($row['sid']);?>]" id="students[<?php echo($row['sid']);?>]" value="<?php echo $row['sid']; ?>"<?php echo ($found ? " checked" : "") ?>> <?php echo $row['id']; ?></td>
						<td class=""><?php echo $row['first_name'] . " " . $row['last_name']; ?></td>
						<td class=""><?php echo $row['gender']; ?></td>
						<td class=""><?php echo trim($row['birthdate']) != "" ? date("m/d/Y", strtotime($row['birthdate'])) : t("N/A"); ?></td>
					</tr>
					<?php
				}
				?>
			</tbody>
		</table>
	</form>
</div>

<div id="dialog-form-license" title="<?php echo t('Add license')?>">
	<form method="post" name="licenseform" id="licenseform">
		<input type="hidden" name="licenseaction" id="licenseaction" value="license">
		<input type="hidden" name="licenseid" id="licenseid" value="<?php echo $this->id; ?>">
	<p class="validateTips"><?php echo t('All form fields are required'); ?></p>

	<form method="post">
		<fieldset>
			<label for="name"><?php echo t('Name'); ?></label>
			<input type="text" name="licensename" id="licensename" class="text ui-widget-content ui-corner-all" />
			<label for="name"><?php echo t('Date'); ?></label>
			<input type="text" name="licensedate" id="licensedate" class="calendarbox text ui-widget-content ui-corner-all" />
		</fieldset>
	</form>
	</form>
</div>

<div id="dialog-form-class" title="<?php echo t('Update classes')?>">
	<form method="post" name="classform" id="classform">
		<input type="hidden" name="classaction" id="classaction" value="classaction">
		<input type="hidden" name="classid" id="classid" value="<?php echo $this->id; ?>">
		<table cellpadding="0" cellspacing="0" border="0" class="display tablegrid" id="" style="width:100%">
			<thead>
				<tr>
					<th><?php echo t('Class Name'); ?></th>
					<th><?php echo t('Instructor'); ?></th>
					<th><?php echo t('Start date'); ?></th>
					<th><?php echo t('End date'); ?></th>
				</tr>
			</thead>
			<tbody>
				<?php
					foreach ($this->fetchclasses as $classes){
						$found = false;
						foreach ($this->fetchcurrentclasses as $current){
							if ($current['id'] == $classes['id']){
								$found = true;
							}
						}
						?>
						<tr class="GradeA">
							<td><input type="checkbox" name="class[<?php echo $classes['id']; ?>][id]" id="class[<?php echo $classes['id']; ?>][id]" value="<?php echo $classes['id']; ?>"<?php echo ($found ? " checked" : "") ?>> <?php echo $classes['classname']; ?></td>
							<td class=""><?php echo $classes['first_name'] . " " . $classes['last_name']; ?></td>
							<td class=""><?php echo date("m/d/Y", strtotime($classes['startdate'])); ?></td>
							<td class=""><?php echo date("m/d/Y", strtotime($classes['enddate'])); ?></td>
						</tr>
						<?php
					}
				?>
			</tbody>
		</table>
	</form>
</div>

<div id="dialog-form-practicum" title="Add a practicum">
	<form method="post" name="practicumform" id="practicumform">
		<input type="hidden" name="practicumaction" id="practicumaction" value="practicumaction">
		<input type="hidden" name="practicumid" id="practicumid" value="0">
	<p class="validateTips"><?php echo t('All form fields are required'); ?></p>

	<form method="post">
		<fieldset>
			<label for="name"><?php echo t('Name'); ?></label>
			<input type="text" name="practicumname" id="practicumname" class="text ui-widget-content ui-corner-all" />
			<label for="name"><?php echo t('Date'); ?></label>
			<input type="text" name="practicumdate" id="practicumdate" class="calendarbox text ui-widget-content ui-corner-all" />
			<label for="name"><?php echo t('Facility'); ?></label>
			<select name="facilityid" id="facilityid" class="text ui-widget-content ui-corner-all" />
				<option value="0"><?php echo t('Select'); ?></option>
<?php
	foreach ($this->facilities as $facility){
?>
					<option value="<?php echo $facility['id']; ?>"><?php echo $facility['facility_name']; ?></option>
<?php
	}
?>
			</select>
			<label for="name"><?php echo t('Advisor'); ?></label>
			<select name="advisorid" id="advisorid" class="text ui-widget-content ui-corner-all" />
				<option value="0"><?php echo t('Select'); ?></option>
<?php
	foreach ($this->advisors as $advisor){
?>
					<option value="<?php echo $advisor['id']; ?>"><?php echo $advisor['first_name'] . " " . $advisor['last_name']; ?></option>
<?php
	}
?>
			</select>
			<label for="name"><?php echo t('Hours Required'); ?></label>
			<input type="text" name="hoursrequired" id="hoursrequired" class="text ui-widget-content ui-corner-all" />
		</fieldset>
	</form>
	</form>
</div>


		<div id="pageHolder">
			<div id="header"><?php require_once('views/scripts/preheader.phtml');?></div>
			<div id="content">
				<div id="subcontent">
					<div id="contentheader">
						<h2><?php echo t('Edit/View Cohort Record'); ?></h2>
					</div>
					<div class="pad50 clear"></div>
					<form  id="cohortedit" method="post" class="formvalidate">
						<input type="hidden" name="id" value="<?php echo $this->escape($this->id);?>">
						<div class="mainformholder">
							<p style=""><?php echo t('Cohort details'); ?></p><br>

							<label><?php echo t('Cohort ID'); ?></label>
							<input type="text" class="required" name="cohortid" readonly  value="<?php echo $this->escape($this->cohortid);?>">

							<label><?php echo t('Cohort Name'); ?></label>
							<input type="text" class="required" name="cohortname"  value="<?php echo $this->escape($this->cohortname);?>">

							<label><?php echo t('Degree Information'); ?></label>
							<select name="degreeinfo" class="comboeditable">
								<option value="0"><?php echo t('Select...'); ?></option>
								<?php
									foreach ($this->lookupdegrees as $degree){
									?>
										<option value="<?php echo $degree['id']; ?>"<?php echo $degree['id'] == $this->escape($this->degree) ? " selected" : ""; ?>><?php echo $degree['degree']; ?></option>
									<?php
										}
								?>
							</select>

							<label><?php echo t('Institution'); ?></label>
							<select name="institution" id="institution" disabled="true">
								<?php
									foreach ($this->institutions as $institution){
									?>
										<option value="<?php echo $institution['id']; ?>"<?php echo $institution['id'] == $this->institution ? " selected" : ""; ?>><?php echo $institution['institutionname']; ?></option>
									<?php
										}
								?>
							</select>

							<label><?php echo t('Cadre'); ?></label>
							<select name="cadre" id="cadre">
								<?php
								foreach ($this->institution_cadres as $cadre){
									?>
									<option value="<?php echo $cadre['id_cadre']; ?>"<?php echo ($cadre['id_cadre'] == $this->institution_cadre_id) ? " SELECTED" : ""; ?>><?php echo $cadre['cadrename']; ?></option>
									<?php
								}
								?>
							</select>

							<label><?php echo t('Cohort Start Date'); ?></label>
							<input type="text" name="cohortstart" class="calendarbox required" value="<?php echo $this->escape($this->startname);?>">

							<label><?php echo t('Cohort Graduation Date'); ?></label>
							<input type="text" name="cohortgrade" class="calendarbox required" value="<?php echo $this->escape($this->graddate);?>">

							<label><?php echo t('Cohort Participants at Start'); ?></label>
							<input type="text" name="startdate" readonly value="<?php echo $this->escape($this->studentsatstart);?>">

							<label><?php echo t('Cohort Participants Dropped Out'); ?></label>
							<input type="text" name="sepratedate" readonly value="<?php echo $this->escape($this->studentsseparated);?>">

							<label><?php echo t('Cohort Current or Graduating Number'); ?></label>
							<input type="text" name="graddate" readonly value="<?php echo $this->escape($this->studentsgraduating);?>">

							<div class="rightdiv" style="margin-top:10px; margin-right:12px;">
							<!-- TA:44 add button Delete -->
								<input type="submit" name="deletecohort" value="<?php echo t('Delete'); ?>" class="tsbutton green large" 
								onclick="<?php if(sizeof($this->cohortStudents) !=0 ) echo 'alert(\'Please remove all Students associated with the cohort first\'); return false;'; ?>">
								<input type="submit" name="updatecohort" value="<?php echo t('Update'); ?> &raquo;" class="tsbutton green large">
							</div>
						</div>
					</form>

					<div class="clear50"></div>

					<div class="pad20 clear"></div>
					<p style="float:left;font-size:14px; font-weight:bold; margin:40px 0 0 0;"><?php echo t('Students associated with the cohort'); ?></p>

					<div style="width : 100%;">
						<table cellpadding="0" cellspacing="0" border="0" class="display tablegrid" id="" style="width:100%">
							<thead>
								<tr>
									<th><?php echo t('Student ID'); ?></th>
									<th><?php echo t('Name'); ?></th>
									<th><?php echo t('Gender'); ?></th>
									<th><?php echo t('DOB'); ?></th>
									<th><?php echo t('Status'); ?></th>
								</tr>
							</thead>
							<tbody>
<?php
	foreach ($this->cohortStudents as $row){
?>
								<tr class="GradeA" style="cursor : pointer;" onclick="location='<?php echo Settings::$COUNTRY_BASE_URL; ?>/studentedit/personview/id/<?php echo $row['id']; ?>'";>
									<td style=" width : 120px;"><?php echo $row['id']; ?></td>
									<td class="" style=""><?php echo $row['first_name'] . " " . $row['last_name']; ?></td>
									<td class="" style="width : 120px;"><?php echo $row['gender']; ?></td>
									<td class="" style="width : 120px;"><?php echo trim($row['birthdate']) != "" ? date("m/d/Y", strtotime($row['birthdate'])) : t("N/A"); ?></td>
									<td class="" style="width : 120px;"><?php
										if ($row['isgraduated']){
											echo t("Graduated");
										} elseif ($row['dropdate'] != "0000-00-00"){
											echo t("Dropped");
										} else {
											echo t("Active");
										}
									?></td>
								</tr>
<?php
	}
?>
							</tbody>
						</table>
						<div style="text-align : right;">
							<br>
							<input type="submit" name="studentpopupbutton" id="studentpopupbutton" value="<?php echo t('Update associated students'); ?>" class="tsbutton green large">
						</div>
					</div>
<?php
#					<div class="rightdiv" style="">
#						<a href="../cohortadd/cohortstudent" class="tsbutton green large">Add a student &raquo;</a>
#					</div>
?>
					<div class="pad50 clear"></div>
					<p style="float:left;font-size:14px; font-weight:bold;"><?php echo t('License / Registration'); ?></p>

					<div style="width : 100%;">
						<table cellpadding="0" cellspacing="0" border="0" class="display tablegrid" id="" style="width:100%">
							<thead>
								<tr>
									<th><?php echo t('Name'); ?></th>
									<th><?php echo t('Date'); ?></th>
									<th>&nbsp;</th>
								</tr>
							</thead>
							<tbody>
<?php
	foreach ($this->licenses as $license){
?>
								<tr class="GradeA">
									<td style="cursor : pointer;" onclick="licenseedititem('<?php echo $license['id'] . "','" . $license['licensename'] . "','" . $license['licensedate']; ?>');"><?php echo $license['licensename'];?></td>
									<td style="cursor : pointer; width : 120px;" onclick="licenseedititem('<?php echo $license['id'] . "','" . $license['licensename'] . "','" . $license['licensedate']; ?>');"><?php echo date("m/d/Y", strtotime($license['licensedate']));?></td>
									<td style="cursor : pointer; width : 80px;"><form method="post"><input type="submit" value="<?php echo t('Delete'); ?>" style="width : 100%; padding : 3px;"><input type="hidden" name="dellicense" id="dellicense" value="<?php echo $license['id'] ?>"></form></td>
								</tr>
<?php
	}
?>
							</tbody>
						</table>
						<div style="text-align : right;">
							<input type="submit" name="licensepopupbutton" id="licensepopupbutton" value="<?php echo t('Add a license'); ?>" class="tsbutton green large">
						</div>
					</div>
<?php
#					<div class="rightdiv" style="">
#						<a href="../cohort/cohortpracticum/cohortid/< ? php echo $this->escape($this->id);? >" class="tsbutton green large">Add a Requirement &raquo;</a>
#					</div>
?>
					<div class="pad50 clear"></div>
					<p style="float:left;font-size:14px; font-weight:bold;"><?php echo t('Classes associated with the Cohort'); ?></p>

					<div style="width : 100%;">
						<table cellpadding="0" cellspacing="0" border="0" class="display tablegrid" id="" style="width:100%">
							<thead>
								<tr>
									<th><?php echo t('Class Name'); ?></th>
									<th><?php echo t('Tutor'); ?></th>
									<th><?php echo t('Start date'); ?></th>
									<th><?php echo t('End date'); ?></th>
								</tr>
							</thead>
							<tbody>
							<?php
								foreach ($this->fetchcurrentclasses as $classes){
									?>
									<tr class="GradeA">
										<td class=""><?php echo $classes['classname'];?></td>
										<td class="" style=" width : 160px;"><?php echo $classes['first_name'] . " " . $classes['last_name'];?></td>
										<td class="" style=" width : 120px;"><?php echo date("m/d/Y", strtotime($classes['startdate']));?></td>
										<td class="" style=" width : 120px;"><?php echo date("m/d/Y", strtotime($classes['enddate']));?></td>
									</tr>
									<?php
								}
							?>
							</tbody>
						</table>
						<div style="text-align : right;">
							<input type="submit" name="classpopupbutton" id="classpopupbutton" value="<?php echo t('Update associated classes'); ?>" class="tsbutton green large">
						</div>
					</div>
<?php
#					<div class="rightdiv" style="">
#						<a href="../cohort/cohortclass/cohortid/< ? php echo $this->escape($this->id);? >" class="tsbutton green large">Add a Class &raquo;</a>
#					</div>
?>
					<div class="pad50 clear"></div>
					<p style="float:left;font-size:14px; font-weight:bold;"><?php echo t('Clinical Allocation'); ?></p>

					<div style="width : 100%;">
						<table cellpadding="0" cellspacing="0" border="0" class="display tablegrid" id="" style="width:100%">
							<thead>
								<tr>
									<th><?php echo t('Name'); ?></th>
									<th><?php echo t('Date'); ?></th>
									<th><?php echo t('Facility'); ?></th>
									<th><?php echo t('Advisor'); ?></th>
									<th><?php echo t('Hours Required'); ?></th>
									<th>&nbsp;</th>
								</tr>
							</thead>
							<tbody>
<?php
	foreach ($this->practicumfetch as $practicum){
?>
								<tr class="GradeA">
									<td style="cursor : pointer;" onclick="practicumedititem('<?php echo addslashes($practicum['id']) . "','" . addslashes($practicum['practicumname']) . "','" . addslashes($practicum['practicumdate']) . "','" . addslashes($practicum['facilityid']) . "','" . addslashes($practicum['advisorid']) . "','" . addslashes($practicum['hoursrequired']); ?>');"><?php echo $practicum['practicumname'];?></td>
									<td style="cursor : pointer; width : 120px;" onclick="practicumedititem('<?php echo addslashes($practicum['id']) . "','" . addslashes($practicum['practicumname']) . "','" . addslashes($practicum['practicumdate']) . "','" . addslashes($practicum['facilityid']) . "','" . addslashes($practicum['advisorid']) . "','" . addslashes($practicum['hoursrequired']); ?>');"><?php echo $practicum['practicumdate'];?></td>
									<td style="cursor : pointer; width : 120px;" onclick="practicumedititem('<?php echo addslashes($practicum['id']) . "','" . addslashes($practicum['practicumname']) . "','" . addslashes($practicum['practicumdate']) . "','" . addslashes($practicum['facilityid']) . "','" . addslashes($practicum['advisorid']) . "','" . addslashes($practicum['hoursrequired']); ?>');"><?php echo $practicum['facilityid'];?></td>
									<td style="cursor : pointer; width : 120px;" onclick="practicumedititem('<?php echo addslashes($practicum['id']) . "','" . addslashes($practicum['practicumname']) . "','" . addslashes($practicum['practicumdate']) . "','" . addslashes($practicum['facilityid']) . "','" . addslashes($practicum['advisorid']) . "','" . addslashes($practicum['hoursrequired']); ?>');"><?php echo $practicum['advisorid'];?></td>
									<td style="cursor : pointer; width : 120px;" onclick="practicumedititem('<?php echo addslashes($practicum['id']) . "','" . addslashes($practicum['practicumname']) . "','" . addslashes($practicum['practicumdate']) . "','" . addslashes($practicum['facilityid']) . "','" . addslashes($practicum['advisorid']) . "','" . addslashes($practicum['hoursrequired']); ?>');"><?php echo $practicum['hoursrequired'];?></td>
									<td style="cursor : pointer; width : 80px;"><form method="post"><input type="submit" value="<?php echo t('Delete'); ?>" style="width : 100%; padding : 3px;"><input type="hidden" name="delpracticum" id="delpracticum" value="<?php echo $practicum['id'] ?>"></form></td>
								</tr>
<?php
	}
?>
							</tbody>
						</table>
						<div style="text-align : right;">
							<input type="submit" name="practicumpopupbutton" id="practicumpopupbutton" value="<?php echo t('Add a practicum'); ?>" class="tsbutton green large">
						</div>
					</div>
<?php
#					<div class="rightdiv" style="">
#						<a href="../cohort/cohortasspracticum/cohortid/< ? php echo $this->escape($this->id);? >" class="tsbutton green large">   <  ?php echo t('Add a Practicum'); ?  > &raquo;</a>
#					</div>
?>
					<div class="pad50 clear"></div>
<!--
					<p style="float:left;font-size:14px; font-weight:bold;"><?php echo t('Assessment associated with Cohort'); ?></p>

					<div style="width : 100%;">
						<table cellpadding="0" cellspacing="0" border="0" class="display tablegrid" id="" style="width:100%">
							<thead>
								<tr>
									<th>Exam Id</th>
									<th>Exam</th>
									<th>Exam Year</th>
									<th>Grade</th>
									<th>Edit</th>
								</tr>
							</thead>
							<tbody>
<?php
	foreach($this->fetchexams as $fetchexam){
?>
								<tr class="GradeA">
									<td><?php echo $fetchexam[id];?></td>
									<td class=""><?php echo $fetchexam[examname];?></td>
									<td class=""><?php echo $fetchexam[examdate];?></td>
									<td class=""><?php echo $fetchexam[grade];?></td>
									<td class=""><form name="edit" method="post" action="../cohort/cohortexamedit/examid/<?php echo $fetchexam[id];?>">
									<input type="hidden" name="id" value="<?php echo $cohortresult[id]; ?>" />
									<input type="hidden" name="edittable" value="1" />
									<input type="submit" name="update" style="background-image:url(<?php echo Settings::$COUNTRY_BASE_URL.'/images/edit.png'?>); height:25px; width:25px;color:transparent;border:0px;" /></form> </td>
								</tr>
<?php } ?>
							</tbody>
						</table>
					</div>
-->
<?php
#					<div class="rightdiv" style="">
#						<a href="../cohort/cohortexamadd/cohortid/< ? php echo $this->escape($this->id); ? >" class="tsbutton green large">Add a Exams &raquo;</a>
#					</div>
?>
				</div>
			</div>
			<div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
		</div>
	</body>
</html>