
<html>
	<head>
		<title><?php echo $this->escape($this->title);?></title>
		<link href="//fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet" type="text/css">

<?php
    require_once('views/helpers/ScriptContainer.php');
    print ScriptContainer::$instance->renderCSSHead();
	print ScriptContainer::$instance->renderJSHead();
?>

		<style>
			fieldset input[type=text], fieldset select { margin-bottom:12px; width:95%; padding: .4em; }
			fieldset { padding:0; border:0; margin-top:25px; text-align : left; font-size : .9em }
			h1 { font-size: 1.2em; margin: .6em 0; }
			.ui-dialog .ui-state-error { padding: .3em; }
			.validateTips { border: 1px solid transparent; padding: 0.3em; }
            .dataTables_wrapper { min-height: 0; }
		</style>
		<script>
			$(function() {
				$( "#dialog-form-student" ).dialog({
					autoOpen: false,
					height: 460,
					width: 750,
					modal: true,
					buttons: {
						<?php echo t('Update')?>: function() {
							$('#dialog-form-student select[name="_length"]')
								.append('<option value="1000">1000</option>')
								.val(1000)
								.change();
							document.getElementById('studentform').submit();
						},
						<?php echo t('Cancel')?>: function() {
							$( this ).dialog( "close" );
						}
					}
				});

				$( "#studentpopupbutton" )
					.button()
					.click(function() {
						$( "#dialog-form-student" ).dialog( "open" );
					});


				$( "#dialog-form-license" ).dialog({
					autoOpen: false,
					height: 300,
					width: 400,
					modal: true,
					buttons: {
						<?php echo t('Save')?>: function() {
							document.getElementById('licenseform').submit();
						},
						<?php echo t('Cancel')?>: function() {
							$( this ).dialog( "close" );
						}
					}
				});

				$( "#licensepopupbutton" )
					.button()
					.click(function() {
						$('#dialog-form-license').dialog('option', 'title', '<?php echo t('Add a license'); ?>');
						$("#licenseid").val("0");

						$("#licensename").val("");
						$("#licensedate").val("");

						$( "#dialog-form-license" ).dialog( "open" );
				});

                $( "#dialog-form-edit-class" ).dialog({
                    autoOpen: false,
                    width: 550,
                    modal: true,
                    buttons: {
                        "<?php echo t('Save') ?>": function() {

                            if ($("#currentid").val() == 0){
                                $("#_action").val("addnew");
                            } else {
                                $("#_action").val("update");
                            }

                            if ($("#classname").val() == "") {
                                alert('Class Name is required');
                                $("#classname").focus();
                            }
                            //TA:#491
//                             else if ($("#startdate").val() == ""){
//                                 alert ('Please enter a start date');
//                                 $("#startdate").focus();
//                             } else if ($("#enddate").val() == ""){
//                                 alert ('Please enter an end date');
//                                 $("#enddate").focus();
//                             } else if (Date.parse($("#enddate").val()) <= Date.parse($("#startdate").val())){
 //                               alert ('<?php //echo t('The end date cannot be before the start date')?>');
//                                 $("#enddate").focus();
//                             } 
                            else {
                                $( this ).dialog( "close" );
                                document.getElementById("editclass").submit();
                            }
                        },
                        "<?php echo t('Cancel') ?>": function() {
                            $( this ).dialog( "close" );
                        }
                    }
                });

                $( "#addclassbutton" )
                    .button()
                    .click(function() {
                        $('#dialog-form-edit-class').dialog('option', 'title', '<?php echo t('Add class')?>');
                        $("#currentid").val("0");

                        <?php // Note: the form action is being changed here by JavaScript ?>
                        $("#editclassaction").val('addclass');

                        $("#classname").val("");
                        $("#startdate").val("");
                        $("#enddate").val("");
                        $("#coursetopic").val("");

                        $("#dialog-form-edit-class" ).dialog("open");
                    });

            $( "#dialog-form-class" ).dialog({
					autoOpen: false,
					height: 460,
					width: 750,
					modal: true,
					buttons: {
						<?php echo t('Update')?>: function() {
							document.getElementById('classform').submit();
						},
						<?php echo t('Cancel')?>: function() {
							$( this ).dialog( "close" );
						}
					}
				});

				$( "#classpopupbutton" )
					.button()
					.click(function() {
						$( "#dialog-form-class" ).dialog( "open" );
				});


				$( "#dialog-form-practicum" ).dialog({
					autoOpen: false,
					height: 580,
					width: 400,
					modal: true,
					buttons: {
						<?php echo t('Save')?>: function() {
							document.getElementById('practicumform').submit();
						},
						<?php echo t('Cancel')?>: function() {
							$( this ).dialog( "close" );
						}
					}
				});

				$( "#practicumpopupbutton" )
					.button()
					.click(function() {
						$('#dialog-form-practicum').dialog('option', 'title', '<?php echo t('Add a practicum'); ?>');
						$("#practicumid").val("0");

						$("#practicumname").val("");
						$("#practicumdate").val("");
						$("#facilityid").val("");
						$("#advisorid").val("");
						$("#hoursrequired").val("");

						$( "#dialog-form-practicum" ).dialog( "open" );
				});
			});

            function classedititem(d){

                $('#dialog-form-edit-class').dialog('option', 'title', '<?php echo t('Update class')?>');
                $("#currentid").val(d['id']);

                <?php // Note: the form action is being changed here by JavaScript ?>
                $("#editclassaction").val('editclass');

                $("#classname").val(d['classname']);
                $("#startdate").val(d['startdate']);
                $("#enddate").val(d['enddate']);
                $("#instructorid").val(d['instructorid']);
                $("#coursetypeid").val(d['coursetypeid']);
                $("#coursetopic").val(d['coursetopic']);

                $("#class_modules_id").val(d['class_modules_id']);
                $("#custom_1").val(d['custom_1']);
                $("#credits").val(d['maxcredits']);
                $("#custom_2").val(d['custom_2']);

                $( "#dialog-form-edit-class" ).dialog( "open" );
            }

            function licenseedititem(iid,nm,dt){
				$('#dialog-form-license').dialog('option', 'title', '<?php echo t('Update a license'); ?>');
				$("#licenseid").val(iid);

				$("#licensename").val(nm);
				$("#licensedate").val(dt);

				$( "#dialog-form-license" ).dialog( "open" );
			}
			function practicumedititem(iid,nm,dt,fid,aid,hreq,hfin){
				$('#dialog-form-practicum').dialog('option', 'title', '<?php echo t('Update a practicum'); ?>');
				$("#practicumid").val(iid);

				$("#practicumname").val(nm);
				$("#practicumdate").val(dt);
				$("#facilityid").val(fid);
				$("#advisorid").val(aid);
				$("#hoursrequired").val(hreq);

				$( "#dialog-form-practicum" ).dialog( "open" );
			}
		</script>



		<script type="text/javascript" charset="utf-8">
			$(document).ready(function() {
				$( ".calendarbox" ).datepicker({
					changeMonth: true,
					changeYear: true,
					yearRange: "c-50:+50",
				});

				/* Add a click handler to the rows - this could be used as a callback */
				$(".tablegrid tbody").click(function(event) {
					$(oTable.fnSettings().aoData).each(function (){
						$(this.nTr).removeClass('row_selected');
					});
					$(event.target.parentNode).addClass('row_selected');
				});

				/* Init the tables */
				oTable = $('.tablegrid').dataTable({
					"bJQueryUI": true,
					"sPaginationType": "full_numbers"
				});

                /* init non-paging tables - workaround for the checkboxes that are not registering because they
                 are not visible
                 */
                var fullTable = $('.tablegrid_show_all').dataTable({
                    "bJQueryUI": true,
                    "bFilter": false,
                    "iDisplayLength": -1,
                    "bLengthChange": false
                });

			} );

			/* Get the rows which are currently selected */
			function fnGetSelected( oTableLocal ){
				var aReturn = new Array();
				var aTrs = oTableLocal.fnGetNodes();

				for ( var i=0 ; i<aTrs.length ; i++ ){
					if ( $(aTrs[i]).hasClass('row_selected') ){
						aReturn.push( aTrs[i] );
					}
				}
				return aReturn;
			}
		</script>
	</head>
	<body>

<div id="dialog-form-student" title="<?php echo t("Update students")?>">
	<form method="post" name="studentform" id="studentform">
		<input type="hidden" name="formaction" value="students">
		<input type="hidden" name="id" id="id" value="<?php echo $this->id; ?>">
		<table cellpadding="0" cellspacing="0" border="0" class="display tablegrid_show_all" id="" style="width:100%">
			<thead>
				<tr>
					<th><?php echo t('Student Id'); ?></th>
					<th><?php echo t('Name'); ?></th>
					<th><?php echo t('Gender'); ?></th>
					<th><?php echo t('DOB'); ?></th>
				</tr>
			</thead>
			<tbody>
				<?php
				foreach ($this->allStudents as $row){
					$found = false;
					$sid = 0;
					foreach ($this->cohortStudents as $subrow){
						if ($subrow['id'] == $row['id']){
							$sid = $subrow['studentid'];
							$found = true;
						}
					}
					?>
					<tr class="GradeA">
						<td><input type="checkbox" name="students[<?php echo($row['sid']);?>]" id="students[<?php echo($row['sid']);?>]" value="<?php echo $row['sid']; ?>"<?php echo ($found ? " checked" : "") ?>> <?php echo $row['id']; ?></td>
						<td class=""><?php echo $row['first_name'] . " " . $row['last_name']; ?></td>
						<td class=""><?php echo $row['gender']; ?></td>
						<td class=""><?php echo trim($row['birthdate']) != "" ? date("m/d/Y", strtotime($row['birthdate'])) : t("N/A"); ?></td>
					</tr>
					<?php
				}
				?>
			</tbody>
		</table>
	</form>
</div>

<div id="dialog-form-license" title="<?php echo t('Add license')?>">
	<form method="post" name="licenseform" id="licenseform">
		<input type="hidden" name="licenseaction" id="licenseaction" value="license">
		<input type="hidden" name="licenseid" id="licenseid" value="<?php echo $this->id; ?>">
	<p class="validateTips"><?php echo t('All form fields are required'); ?></p>

	<form method="post">
		<fieldset>
			<label for="name"><?php echo t('Name'); ?></label>
			<input type="text" name="licensename" id="licensename" class="text ui-widget-content ui-corner-all" />
			<label for="name"><?php echo t('Date'); ?></label>
			<input type="text" name="licensedate" id="licensedate" class="calendarbox text ui-widget-content ui-corner-all" />
		</fieldset>
	</form>
	</form>
</div>

<div id="dialog-form-edit-class" title="Update class">
    <form method="post" name="editclass" id="editclass">
        <input type="hidden" name="formaction" id="editclassaction">

        <fieldset>
            <label for="classname"><?php echo t('Class name');?></label>
            <input type="text" name="classname" id="classname" class="text ui-widget-content ui-corner-all" />
            <label for="coursetypeid"><?php echo t('Course Type');?></label>
            <?php echo $this->formSelect('coursetypeid', '',
                array('id' => 'coursetypeid', 'class' => 'text ui-widget-content ui-corner-all'),
                $this->coursetypes); ?>
            <label for="coursetopic"><?php echo t('Topic');?></label>
            <input type="text" name="coursetopic" id="coursetopic" class="text ui-widget-content ui-corner-all" />
            <!-- TA:#491 
            <label for="startdate"><?php echo t('Start date');?></label>
            <input type="text" name="startdate" id="startdate" class="calendarbox text ui-widget-content ui-corner-all" />
            <label for="enddate"><?php echo t('End date');?></label>
            <input type="text" name="enddate" id="enddate" class="calendarbox text ui-widget-content ui-corner-all" />
            -->
            <label for="instructorid"><?php echo t('Instructor');?></label>

            <select name="instructorid" id="instructorid" class="text ui-widget-content ui-corner-all">
                <?php
                foreach ($this->advisors as $advisor) {
                    echo "<option value='{$advisor['id']}'>{$advisor['first_name']} {$advisor['last_name']}</option>\n";
                }
                ?>
            </select>
            <?php if ($this->setting['site_style'] == 'skillsmart') { ?>
                <label for="class_modules_id">Module</label>
                <select name="class_modules_id" id="class_modules_id" class="text ui-widget-content ui-corner-all">
                    <?php
                    foreach ($this->modules as $module){
                        echo "<option value=\"" . $module['id'] . "\">" . $module['external_id'] . " - " . $module['title'] . "</option>\n";
                    }
                    ?>
                </select>
                <label for="custom_1">Short Name</label>
                <input type="text" name="custom_1" id="custom_1" class="text ui-widget-content ui-corner_all" />
                <label for="credits">Credits</label>
                <input type="text" name="credits" id="credits" class="text ui-widget-content ui-corner_all" />
                <label for="custom_2">Weight</label>
                <input type="text" name="custom_2" id="custom_2" class="text ui-widget-content ui-corner_all" />
            <?php } ?>

        </fieldset>
        <input type="hidden" name="currentid" id="currentid" class="text ui-widget-content ui-corner-all" />
    </form>
</div>


<div id="dialog-form-class" title="<?php echo t('Update classes')?>">
	<form method="post" name="classform" id="classform">
		<input type="hidden" name="classaction" id="classaction" value="classaction">
		<input type="hidden" name="classid" id="classid" value="<?php echo $this->id; ?>">
		<table cellpadding="0" cellspacing="0" border="0" class="display tablegrid_show_all" id="" style="width:100%">
			<thead>
				<tr>
					<th><?php echo t('Class Name'); ?></th>
					<th><?php echo t('Instructor'); ?></th>
					<!-- TA:#491 <th><?php echo t('Start date'); ?></th>
					<th><?php echo t('End date'); ?></th>-->
				</tr>
			</thead>
			<tbody>
				<?php
					foreach ($this->fetchclasses as $classes){
						$found = false;
						foreach ($this->fetchcurrentclasses as $current){
							if ($current['id'] == $classes['id']){
								$found = true;
							}
						}
						?>
						<tr class="GradeA">
							<?php if ($this->setting['site_style'] == 'skillsmart') { ?>
								<td><input type="checkbox" name="class[<?php echo $classes['id']; ?>][id]" id="class[<?php echo $classes['id']; ?>][id]" value="<?php echo $classes['id']; ?>"<?php echo ($found ? " checked" : "") ?>> <?php echo $classes['custom_1']; ?></td>
							<?php } else { ?>
								<td><input type="checkbox" name="class[<?php echo $classes['id']; ?>][id]" id="class[<?php echo $classes['id']; ?>][id]" value="<?php echo $classes['id']; ?>"<?php echo ($found ? " checked" : "") ?>> <?php echo $classes['classname']; ?></td>
							<?php } ?>
							<td><?php echo $classes['first_name'] . " " . $classes['last_name']; ?></td>
							<!-- TA:#491 <td><?php if (strlen($classes['startdate'])) { echo date("m/d/Y", strtotime($classes['startdate'])); } ?></td>
							<td><?php if (strlen($classes['enddate'])) { echo date("m/d/Y", strtotime($classes['enddate'])); } ?></td>-->
						</tr>
						<?php
					}
				?>
			</tbody>
		</table>
	</form>
</div>

<div id="dialog-form-practicum" title="Add a practicum">
	<form method="post" name="practicumform" id="practicumform">
		<input type="hidden" name="practicumaction" id="practicumaction" value="practicumaction">
		<input type="hidden" name="practicumid" id="practicumid" value="0">
	<p class="validateTips"><?php echo t('All form fields are required'); ?></p>

	<form method="post">
		<fieldset>
			<label for="name"><?php echo t('Name'); ?></label>
			<input type="text" name="practicumname" id="practicumname" class="text ui-widget-content ui-corner-all" />
			<label for="name"><?php echo t('Date'); ?></label>
			<input type="text" name="practicumdate" id="practicumdate" class="calendarbox text ui-widget-content ui-corner-all" />
			<label for="name"><?php echo t('Facility'); ?></label>
			<select name="facilityid" id="facilityid" class="text ui-widget-content ui-corner-all" />
				<option value="0"><?php echo t('Select'); ?></option>
<?php
	foreach ($this->facilities as $facility){
?>
					<option value="<?php echo $facility['id']; ?>"><?php echo $facility['facility_name']; ?></option>
<?php
	}
?>
			</select>
			<label for="name"><?php echo t('Advisor'); ?></label>
			<select name="advisorid" id="advisorid" class="text ui-widget-content ui-corner-all" />
				<option value="0"><?php echo t('Select'); ?></option>
<?php
	foreach ($this->advisors as $advisor){
?>
					<option value="<?php echo $advisor['id']; ?>"><?php echo $advisor['first_name'] . " " . $advisor['last_name']; ?></option>
<?php
	}
?>
			</select>
			<label for="name"><?php echo t('Hours Required'); ?></label>
			<input type="text" name="hoursrequired" id="hoursrequired" class="text ui-widget-content ui-corner-all" />
		</fieldset>
	</form>
	</form>
</div>


		<div id="pageHolder">
			<div id="header"><?php require_once('views/scripts/preheader.phtml');?></div>
			<div id="content">
				<div id="subcontent">
					<div id="contentheader">
						<h2><?php 
						//TA:#380
						if ( $this->hasACL('edit_people')	){
						    echo t('Edit/View Cohort Record');
						}else{
						  echo t('View Cohort Record'); 
						}
						?>
						</h2>
					</div>
					<div class="pad50 clear"></div>
					<form  id="cohortedit" method="post" class="formvalidate">
					
					<!-- TA:97 -->
	<table style="width:100%">
				<tr><td>
				<input type="hidden" name="id" value="<?php echo $this->escape($this->id);?>">
						<div class="mainformholder">
							<p style=""><?php echo t('Cohort details'); ?></p><br>

							<label><?php echo t('Cohort ID'); ?></label>
							<input type="text" class="required" name="cohortid" readonly  value="<?php echo $this->escape($this->cohortid);?>">

							<label><?php echo t('Cohort Name'); ?></label>
							<!-- TA:#380 -->
							<input type="text" class="required" name="cohortname"  <?php echo $this->hasACL('edit_people')?'':'readonly';?> value="<?php echo $this->escape($this->cohortname);?>">

							<label><?php echo t('Degree Information'); ?></label>
							<!-- TA:#380 -->
							<select name="degreeinfo" class="comboeditable" <?php echo $this->hasACL('edit_people')?'':'disabled=disabled';?>>
								<option value="0"><?php echo t('Select...'); ?></option>
								<?php
									foreach ($this->lookupdegrees as $degree){
									?>
										<option value="<?php echo $degree['id']; ?>"<?php echo $degree['id'] == $this->escape($this->degree) ? " selected" : ""; ?>><?php echo $degree['degree']; ?></option>
									<?php
										}
								?>
							</select>

							<label><?php echo t('Institution'); ?></label>
							<!-- TA:#380 -->
							<select name="institution" id="institution" <?php echo $this->hasACL('edit_people')?'':'disabled=disabled';?>>
								<?php
									foreach ($this->institutions as $institution){
									?>
										<option value="<?php echo $institution['id']; ?>"<?php echo $institution['id'] == $this->institution ? " selected" : ""; ?>><?php echo $institution['institutionname']; ?></option>
									<?php
										}
								?>
							</select>

							<label><?php echo t('Cadre'); ?></label>
							<!-- TA:#380 -->
							<select name="cadre" id="cadre" <?php echo $this->hasACL('edit_people')?'':'disabled=disabled';?>>
								<?php
								foreach ($this->institution_cadres as $cadre){
									?>
									<option value="<?php echo $cadre['id_cadre']; ?>"<?php echo ($cadre['id_cadre'] == $this->institution_cadre_id) ? " SELECTED" : ""; ?>><?php echo $cadre['cadrename']; ?></option>
									<?php
								}
								?>
							</select>

							<label><?php echo t('Cohort Start Date'); ?></label>
							<!-- TA:#380 -->
							<input type="text" name="cohortstart" <?php echo $this->hasACL('edit_people')?' class="calendarbox required" ':'readonly';?> value="<?php echo $this->escape($this->startname);?>">

							<label><?php echo t('Cohort Graduation Date'); ?></label>
							<!-- TA:#380 -->
							<input type="text" name="cohortgrade" <?php echo $this->hasACL('edit_people')?' class="calendarbox required" ':'readonly';?> value="<?php echo $this->escape($this->graddate);?>">

							<label><?php echo t('Cohort Participants at Start'); ?></label>
							<input type="text" name="startdate" readonly value="<?php echo $this->escape($this->studentsatstart);?>">

							<label><?php echo t('Cohort Participants Dropped Out'); ?></label>
							<input type="text" name="sepratedate" readonly value="<?php echo $this->escape($this->studentsseparated);?>">

							<label><?php echo t('Cohort Current or Graduating Number'); ?></label>
							<input type="text" name="graddate" readonly value="<?php echo $this->escape($this->studentsgraduating);?>">

							<div class="rightdiv" style="margin-top:10px; margin-right:12px;">
							
							<?php 
						//TA:#380
						if ( $this->hasACL('edit_people')	){?>
						    <!-- TA:44 add button Delete -->
								<input type="submit" name="deletecohort" value="<?php echo t('Delete'); ?>" class="tsbutton green large" 
								onclick="<?php if(sizeof($this->cohortStudents) !=0 ) echo 'alert(\'Please remove all Students associated with the cohort first\'); return false;'; ?>">
								<input type="submit" name="updatecohort" value="<?php echo t('Update'); ?> &raquo;" class="tsbutton green large">
						<?php }else{?>
						   <a href="../../../cohort/cohort"> <input type="button"  value="Back" class="tsbutton green large"></a>
						<?php } ////?>
						
							</div>
						</div>
				</td>
				<td style="width:20%" valign='top' align='left'>
				<div class="historyDiv">
						<b><?php echo t('ID'); ?></b>&nbsp;<?php echo $this->escape($this->id);?><br>
						<b><?php echo t('Date created'); ?></b>&nbsp;<?php echo str_replace(' ','&nbsp;',$this->escape($this->dateCreated));?><br>						
						<b><?php echo t('Created by'); ?></b>&nbsp;<?php echo $this->creator; ?><br>
						<b><?php echo t('Date updated'); ?></b>&nbsp;<?php echo str_replace(' ','&nbsp;',$this->escape($this->dateModified));?><br>
						<b><?php echo t('Updated by'); ?></b>&nbsp;<?php echo $this->updater; ?><br>
						<?php //TA:#380
						if ( $this->hasACL('edit_people')	){?> 
						<!-- TA:#362 -->
						<hr>
						<a href="<?php echo Settings::$COUNTRY_BASE_URL; ?>/cohort/transcript/id/<?php echo $this->escape($this->id); ?>" target="_blank" ><?php echo t('Create a new Official Transcript')?></a> <br/>
                          <?php }?>
						</div>
				</td>
				</td></tr>
				</table>
				
						
					</form>

					<div class="clear50"></div>

					<div class="pad20 clear"></div>
					<p style="float:left;font-size:14px; font-weight:bold; margin:40px 0 0 0;"><?php echo t('Students associated with the cohort'); ?></p>

					<div style="width : 100%;">
						<table cellpadding="0" cellspacing="0" border="0" class="display tablegrid" id="" style="width:100%">
							<thead>
								<tr>
									<th><?php echo t('Student ID'); ?></th>
									<th><?php echo t('Name'); ?></th>
									<th><?php echo t('Gender'); ?></th>
									<th><?php echo t('DOB'); ?></th>
									<th><?php echo t('Status'); ?></th>
								</tr>
							</thead>
							<tbody>
<?php
	foreach ($this->cohortStudents as $row){
?>
								<tr class="GradeA" style="cursor : pointer;" onclick="location='<?php echo Settings::$COUNTRY_BASE_URL; ?>/studentedit/personview/id/<?php echo $row['id']; ?>'";>
									<td style=" width : 120px;"><?php echo $row['id']; ?></td>
									<td class="" style=""><?php echo $row['first_name'] . " " . $row['last_name']; ?></td>
									<td class="" style="width : 120px;"><?php echo $row['gender']; ?></td>
									<td class="" style="width : 120px;"><?php echo trim($row['birthdate']) != "" ? date("m/d/Y", strtotime($row['birthdate'])) : t("N/A"); ?></td>
									<td class="" style="width : 120px;"><?php
										if ($row['isgraduated']){
											echo t("Graduated");
										} elseif ($row['dropdate'] != "0000-00-00"){
											echo t("Dropped");
										} else {
											echo t("Active");
										}
									?></td>
								</tr>
<?php
	}
?>
							</tbody>
						</table>
						<div style="text-align : right;">
							<br>
							<?php 
							//TA:#380
						if ( $this->hasACL('edit_people')	){?>
							<input type="submit" name="studentpopupbutton" id="studentpopupbutton" value="<?php echo t('Update associated students'); ?>" class="tsbutton green large">
							<?php }?>
						</div>
					</div>
<?php
#					<div class="rightdiv" style="">
#						<a href="../cohortadd/cohortstudent" class="tsbutton green large">Add a student &raquo;</a>
#					</div>
?>
					<div class="pad50 clear"></div>
					<p style="float:left;font-size:14px; font-weight:bold;"><?php echo t('License / Registration'); ?></p>

					<div style="width : 100%;">
						<table cellpadding="0" cellspacing="0" border="0" class="display tablegrid" id="" style="width:100%">
							<thead>
								<tr>
									<th><?php echo t('Name'); ?></th>
									<th><?php echo t('Date'); ?></th>
									<th>&nbsp;</th>
								</tr>
							</thead>
							<tbody>
<?php
	foreach ($this->licenses as $license){
?>
								<tr class="GradeA">
									<td style="cursor : pointer;"
                            <?php //TA:#380
						if ( $this->hasACL('edit_people')	){?>  
									onclick="licenseedititem('<?php echo $license['id'] . "','" . $license['licensename'] . "','" . $license['licensedate']; ?>');"
									<?php }?>
									><?php echo $license['licensename'];?></td>
									<td style="cursor : pointer; width : 120px;"><?php echo date("m/d/Y", strtotime($license['licensedate']));?></td>
									<td style="cursor : pointer; width : 80px;">
									<?php //TA:#380
						if ( $this->hasACL('edit_people')	){?>
									<form method="post"><input type="submit" value="<?php echo t('Delete'); ?>" style="width : 100%; padding : 3px;"><input type="hidden" name="dellicense" id="dellicense" value="<?php echo $license['id'] ?>"></form>
									<?php }?>
									</td>
								
								</tr>
<?php
	}
?>
							</tbody>
						</table>
						<div style="text-align : right;">
                            <br>
                            <?php 
							//TA:#380
						if ( $this->hasACL('edit_people')	){?>
							<input type="submit" name="licensepopupbutton" id="licensepopupbutton" value="<?php echo t('Add a license'); ?>" class="tsbutton green large">
							<?php }?>
						</div>
					</div>
<?php
#					<div class="rightdiv" style="">
#						<a href="../cohort/cohortpracticum/cohortid/< ? php echo $this->escape($this->id);? >" class="tsbutton green large">Add a Requirement &raquo;</a>
#					</div>
?>
					<div class="pad50 clear"></div>
					<p style="float:left;font-size:14px; font-weight:bold;"><?php echo t('Classes associated with the Cohort'); ?></p>

					<div style="width : 100%;">
						<table cellpadding="0" cellspacing="0" border="0" class="display tablegrid" id="" style="width:100%">
							<thead>
								<tr>
									<th><?php echo t('Class Name'); ?></th>
									<th><?php echo t('Tutor'); ?></th>
									<!-- TA:#491 <th><?php echo t('Start date'); ?></th>
									<th><?php echo t('End date'); ?></th>-->
								</tr>
							</thead>
							<tbody>
							<?php
								foreach ($this->fetchcurrentclasses as $classes){
									?>
									<tr class="GradeA" style="cursor : pointer;" 
									<?php //TA:#380
						if ( $this->hasACL('edit_people')	){?> 
									onclick='classedititem(<?php echo json_encode($classes, JSON_HEX_QUOT|JSON_HEX_APOS); ?>);'
									<?php }?>
									>
										<td class="">
											<?php if ($this->setting['site_style'] == 'skillsmart') {
												echo $classes['custom_1'];
											} else {
												echo $classes['classname'];
											}?></td>
										<td style="width : 160px;"><?php echo $classes['first_name'] . " " . $classes['last_name'];?></td>
										<!-- TA:#491<td style="width : 120px;"><?php if (strlen($classes['startdate'])) { echo date("m/d/Y", strtotime($classes['startdate'])); }?></td>
										<td style="width : 120px;"><?php if (strlen($classes['enddate'])) { echo date("m/d/Y", strtotime($classes['enddate'])); }?></td>-->
									</tr>
									<?php
								}
							?>
							</tbody>
						</table>
						<div style="text-align : right;">
                            <br>
                            <?php 
							//TA:#380
						if ( $this->hasACL('edit_people')	){?>
                            <input type="button" name="addclassbutton" id="addclassbutton" value="<?php echo t('Add Class'); ?>" class="tsbutton green large">
							<input type="submit" name="classpopupbutton" id="classpopupbutton" value="<?php echo t('Update associated classes'); ?>" class="tsbutton green large">
							<?php }?>
						</div>
					</div>
<?php
#					<div class="rightdiv" style="">
#						<a href="../cohort/cohortclass/cohortid/< ? php echo $this->escape($this->id);? >" class="tsbutton green large">Add a Class &raquo;</a>
#					</div>
?>
					<div class="pad50 clear"></div>
					<p style="float:left;font-size:14px; font-weight:bold;"><?php echo t('Clinical Allocation'); ?></p>

					<div style="width : 100%;">
						<table cellpadding="0" cellspacing="0" border="0" class="display tablegrid" id="" style="width:100%">
							<thead>
								<tr>
									<th><?php echo t('Name'); ?></th>
									<th><?php echo t('Date'); ?></th>
									<th><?php echo t('Facility'); ?></th>
									<th><?php echo t('Advisor'); ?></th>
									<th><?php echo t('Hours Required'); ?></th>
									<th>&nbsp;</th>
								</tr>
							</thead>
							<tbody>
<?php
	foreach ($this->practicumfetch as $practicum){
?>
								<tr class="GradeA">
									<td style="cursor : pointer;"
                                    <?php //TA:#380
						if ( $this->hasACL('edit_people')	){?>  
									onclick="practicumedititem('<?php echo addslashes($practicum['id']) . "','" . addslashes($practicum['practicumname']) . "','" . addslashes($practicum['practicumdate']) . "','" . addslashes($practicum['facilityid']) . "','" . addslashes($practicum['advisorid']) . "','" . addslashes($practicum['hoursrequired']); ?>');"
									<?php }?>
									><?php echo $practicum['practicumname'];?></td>
									<td style="cursor : pointer; width : 120px;"><?php echo $practicum['practicumdate'];?></td>
									<td style="cursor : pointer; width : 120px;"><?php echo $practicum['facilityid'];?></td>
									<td style="cursor : pointer; width : 120px;"><?php echo $practicum['advisorid'];?></td>
									<td style="cursor : pointer; width : 120px;"><?php echo $practicum['hoursrequired'];?></td>
									<td style="cursor : pointer; width : 80px;">
									<?php //TA:#380
						if ( $this->hasACL('edit_people')	){?> 
									<form method="post"><input type="submit" value="<?php echo t('Delete'); ?>" style="width : 100%; padding : 3px;"><input type="hidden" name="delpracticum" id="delpracticum" value="<?php echo $practicum['id'] ?>"></form>
									<?php }?>
									</td>
								</tr>
<?php
	}
?>
							</tbody>
						</table>
						<div style="text-align : right;">
                            <br>
                            <?php 
							//TA:#380
						if ( $this->hasACL('edit_people')	){?>
							<input type="submit" name="practicumpopupbutton" id="practicumpopupbutton" value="<?php echo t('Add a practicum'); ?>" class="tsbutton green large">
							<?php }?>
						</div>
					</div>
<?php
#					<div class="rightdiv" style="">
#						<a href="../cohort/cohortasspracticum/cohortid/< ? php echo $this->escape($this->id);? >" class="tsbutton green large">   <  ?php echo t('Add a Practicum'); ?  > &raquo;</a>
#					</div>
?>
					<div class="pad50 clear"></div>
<!--
					<p style="float:left;font-size:14px; font-weight:bold;"><?php echo t('Assessment associated with Cohort'); ?></p>

					<div style="width : 100%;">
						<table cellpadding="0" cellspacing="0" border="0" class="display tablegrid" id="" style="width:100%">
							<thead>
								<tr>
									<th>Exam Id</th>
									<th>Exam</th>
									<th>Exam Year</th>
									<th>Grade</th>
									<th>Edit</th>
								</tr>
							</thead>
							<tbody>
<?php
	foreach($this->fetchexams as $fetchexam){
?>
								<tr class="GradeA">
									<td><?php echo $fetchexam[id];?></td>
									<td class=""><?php echo $fetchexam[examname];?></td>
									<td class=""><?php echo $fetchexam[examdate];?></td>
									<td class=""><?php echo $fetchexam[grade];?></td>
									<td class=""><form name="edit" method="post" action="../cohort/cohortexamedit/examid/<?php echo $fetchexam[id];?>">
									<input type="hidden" name="id" value="<?php echo $cohortresult[id]; ?>" />
									<input type="hidden" name="edittable" value="1" />
									<input type="submit" name="update" style="background-image:url(<?php echo Settings::$COUNTRY_BASE_URL.'/images/edit.png'?>); height:25px; width:25px;color:transparent;border:0px;" /></form> </td>
								</tr>
<?php } ?>
							</tbody>
						</table>
					</div>
-->
<?php
#					<div class="rightdiv" style="">
#						<a href="../cohort/cohortexamadd/cohortid/< ? php echo $this->escape($this->id); ? >" class="tsbutton green large">Add a Exams &raquo;</a>
#					</div>
?>
				</div>
			</div>
			<div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
		</div>
	</body>
</html>
