<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title><?php echo $this->translation['Application Name'];?> | <?php print(t('Add').space.t('Employee').space.t('Funder'));?></title>
<?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>

</head>
<body class="yui-skin-sam">
<div id="pageHolder">
  <div id="header"><?php require_once('views/scripts/header.phtml');?></div>
  <div id="content">
  
  		<?php require_once 'views/scripts/status.phtml' ?>

		<h1><?php echo t('Add').space.t('Employee').space.t('Funder');?></h1>
		
		
		 <form action="" method="post" class="form_employee">

<?php
// suppress warning in labelAndField
$this->required_fields = array();


// examples:
// labelAndField($this, t('Input 1'), $myDropDown, 'input_1');
// labelAndField($this, t('Input 2'), 'text', 'field2', $values['field2']);
//echo labelAndField ( $this, t ( 'Partner' ), $this->partner, 'partner_id' );

?>
<fieldset>
<div id="funwrapper">
<?php 
  // funder_filter_dropdown is cascading fields 
  //funder_filter_dropdown($this, $this->partners, $this->partnerFunder, $this->mechanism);
  // build_funding_dropdown builds cascading with all options
  
//file_put_contents('c:\wamp\logs\php_debug.log', 'add-funder-to-employee 40>'.PHP_EOL, FILE_APPEND | LOCK_EX);	ob_start();
//var_dump($this->employee[0]);
//$result = ob_get_clean(); file_put_contents('c:\wamp\logs\php_debug.log', $result .PHP_EOL, FILE_APPEND | LOCK_EX);

 $this->viewonly = true;
 echo labelAndField($this, t('Employee').space.t('ID'),  'text', 'id', $this->employee[0]['id']);
 echo labelAndField($this, t('Partner').space.t('ID'),  'text', 'pid', $this->employee[0]['partner_id']);
 $this->viewonly = false;
 employee_psfm_dropdown(0, $this, $this->partner, $this->subPartner, $this->partnerFunder, $this->mechanism, $this->employee[0]['id'], $this->employee[0]['partner_id']);
 echo labelAndField($this, t('Percentage'), 'text','percentage', $this->percentage);
 
?>

</div>
</fieldset>
  	<div class="clear"></div>
    <input type="hidden" name="redirect" id="redirect" value="<?php echo Settings::$COUNTRY_BASE_URL . '/employee/edit/id/' . $this->employee[0]['id'] ?>" />
  	<input type="hidden" name="limit" id="limit" value="1" />
				<input type="submit" class="submitNoArrow" name="go" value="<?php tp('Save');?>" />
			<div class="clear"></div>
</form>			
</div>
</body>
</html>