<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title><?php echo $this->translation['Application Name'];?> | <?php print(t('Add').space.t('Employee').space.t('Funder'));?></title>
<?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>

</head>
<body class="yui-skin-sam">
<div id="pageHolder">
  <div id="header"><?php require_once('views/scripts/header.phtml');?></div>
  <div id="content">
  
  		<?php require_once 'views/scripts/status.phtml' ?>

		<h1><?php echo t('Add').space.t('Employee').space.t('Funder');?></h1>
		
		
		 <form action="" method="post" class="form_employee">

<?php
// suppress warning in labelAndField
$this->required_fields = array();


?>
<fieldset>
<div id="funwrapper">
 <input type="hidden" id="employeeFunding_delete_data" name="employeeFunding_delete_data"/>
 <input type="hidden" id="employeeFunding_new_data" name="employeeFunding_new_data"/>
 <?php 
 echo $this->tableEmployeeFunding;
 ?>
<br />
  <script>
	// fired on "insert" button click
	function addMechanism(oButton) {
	    var oMechanism = YAHOO.util.Dom.get('new_mechanism');
	    var oPercent = YAHOO.util.Dom.get('percentage');

	    if(oMechanism.value == ""){
    	    alert("Mechanism cannot be empty.");
    	    return;
	    }

	    if(oPercent.value == ""){
    	    alert("Percentage cannot be empty.");
    	    return;
	    }
	    else if(isNaN(oPercent.value) || (oPercent.value < 1) || (oPercent.value > 100)) {
		    alert("Percentage must be a number from 1 to 100.");
		    return;
	    }

        var jsonAdd = { }
        jsonAdd.mechanism = oMechanism.selectedOptions[0].label;
        jsonAdd.combined_id = oMechanism.value;
        jsonAdd.percentage = oPercent.value;
        var percent = jsonAdd.percentage / 100.0;
        
        jsonAdd.hours = percent * <?php echo $this->employee[0]['funded_hours_per_week']?>;
        jsonAdd.cost = percent * <?php echo $this->employee[0]['annual_cost']?>;
      	ITECH.employeeFundingTable.addDataRow(jsonAdd, oMechanism.value);
                
        oMechanism.value = "";
        oPercent.value = "";
      }
  </script>
  
<div><label class="label">Mechanism</label>
  <select id="new_mechanism" name="new_mechanism">
  <option value="">--choose--</option>
  <?php 
  foreach ($this->mechanismList as $i => $row)
  {
    echo '<option value='.$row['combined_id'].'>'.$row['mechanism_phrase'].'</option>';
  }
  ?>
  </select>
  <span>
    <label class="label">Percentage</label>
    <input type="text" id="percentage" name="percentage" value="" />
  </span>
  <input type="submit" name="associateMechanism" value="<?php tp("Add");?>" class="insert" id="mechanismInsertButton" onclick="addMechanism(this);return false;"/>
</div>

</div>
</fieldset>
  	<div class="clear"></div>
    <input type="hidden" name="redirect" id="redirect" value="<?php echo Settings::$COUNTRY_BASE_URL . '/employee/edit/id/' . $this->employee[0]['id'] ?>" />
  	<input type="hidden" name="limit" id="limit" value="1" />
				<input type="submit" class="submitNoArrow" name="go" value="<?php tp('Save');?>" />
			<div class="clear"></div>
</form>			
</div>
</body>
</html>