<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title><?php echo $this->translation['Application Name'] . " | " . $this->pageTitle; ?></title>
	<?php
	require_once('views/helpers/Location.php');
	require_once('views/helpers/ScriptContainer.php');
	require_once('views/helpers/FormHelper.php');
	print ScriptContainer::$instance->renderCSSHead();
	print ScriptContainer::$instance->renderJSHead();
	?>

</head>
<body class="yui-skin-sam"  >
<script id="mechanismData" type="application/json">
    <?php echo json_encode($this->mechanismData); ?>
</script>

	<div id="pageHolder">

		<div id="header"><?php require_once('views/scripts/header.phtml');?></div>
		<div id="content">


			<?php require_once 'views/scripts/status.phtml' ?>

			<h1><?php $this->mode == 'add' ? print(t('Add').space.t('Employee')) : print(t('Edit').space.t('Employee')); ?></h1>
			<form action="" method="post" class="form_employee">
				<legend></legend>

					<?php if ($this->employee['id'] && $this->hasACL('edit_employee') && $this->hasACL('delete_employee')): ?>
						<div class="historyDiv">
							<a href="<?php echo $this->base_url; ?>/employee/delete/id/<?php echo $this->employee['id']; ?>"><?php echo t('Delete this').space.t('Employee'); ?></a>
						</div>
					<?php
						endif; // fi historyDiv

						// form fields
						//if (! $this->hasACL('employees_module')) $this->read_only = true; // readonly
						// gnr:Jan.9.14 SA Emergency $this->required_fields = array('first_name', 'last_name','dob','select_lookup_nationalities', 'partner_id', 'subpartner_id', 'based_at', 'select_employee_qualification_option','salary','benefits','additional_expenses','stipend','employee_transition_option_id', 'select_employee_role_option', 'race', 'gender', 'disability_option_id', 'disability_comments', 'funded_hours_per_week', 'agreement_end_date');
						
						$this->required_fields = array('employee_code', 'partner_id', 'based_at', 'select_employee_qualification_option','salary','benefits','additional_expenses','stipend','employee_transition_option_id', 'select_employee_role_option', 'disability_option_id', 'disability_comments', 'funded_hours_per_week', 'agreement_end_date');

						#if ($this->mode != 'add' && $this->employee['id'])
						#echo labelAndField($this, 'Person ID',       'text', 'id', $this->employee['id']);
						if (! $this->hasACL('edit_employee')) 
						{
						    $this->viewonly = true;
						}
						echo labelAndField($this, t('Staff Cadre'),    $this->cadres, 'select_employee_qualification_option');
						if($this->setting['display_employee_primary_role'])
						echo labelAndField($this, t('Primary Role'),   $this->roles,   'select_employee_role_option');
						/*
						echo labelAndField($this, t('Title'),        $this->titles);
						echo labelAndField($this, t('First Name'),   'text', 'first_name',  $this->employee['first_name'] );
						if($this->setting['display_middle_name'])
						echo labelAndField($this, t('Middle Name'),  'text', 'middle_name', $this->employee['middle_name'] );
						echo labelAndField($this, t('Last Name'),    'text', 'last_name',   $this->employee['last_name'] );
						*/
						$this->viewonly = true;
						echo labelAndField($this, t('Employee').space.t('ID'),    'text', 'employee_id',   $this->employee['id'] );
						if ($this->hasACL('edit_employee'))
						{
						    $this->viewonly = false;
						}
						echo labelAndField($this, t('Employee').space.t('Code'),    'text', 'employee_code',   $this->employee['employee_code'] );
						
						if($this->setting['display_employee_dob'])
						echo labelAndField($this, t('Employee Date of Birth').space.('(dd/mm/yyyy)'),'date', 'dob',         $this->employee['dob'] );
						
						// if($this->setting['display_employee_nationality'])
						// echo labelAndField($this, t('Employee Nationality'), $this->nationality, 'select_lookup_nationalities');
						
						// echo labelAndField($this, t('National ID'),  'text', 'national_id', $this->employee['national_id'] );
						
						// if($this->setting['display_employee_other_id'])
						// echo labelAndField($this, t('Other ID'),     'text', 'other_id',    $this->employee['other_id'] );
						
						//if($this->setting['display_employee_race'])
						//echo labelAndField($this, t('Race'),         $this->race, 'race');
						//echo genderDropdown($this,t('Gender'),       'gender', $this->employee['gender']);
						if($this->setting['display_employee_disability']) 
						{
    						$this->viewonly = true;
    						echo confirmDropdown($this, t('Disability'), 'disability_option_id', $this->employee['disability_option_id']);
    						echo labelAndField($this, t('Nature of Disability'), 'text', 'disability_comments', $this->employee['disability_comments']);
    						echo '<div class="clear"></div><br /><br />'.PHP_EOL;
						    if ($this->hasACL('edit_employee'))
						    {
						        $this->viewonly = false;
						    }
						}

						if ($this->mode != 'add' && $this->employee['partner_employee_number'])
						echo labelAndField($this, t('Employee').space.t('Number'),       'text', 'partner_employee_number', $this->employee['partner_employee_number']);
						
						if($this->setting['display_employee_partner'])	
						echo labelAndField($this, t('Employer'),     $this->partners, 'partner_id');

						
						if($this->setting['display_employee_base'])
						echo labelAndField($this, t('Employee Based at'), $this->bases, 'based_at');
						region_filters_dropdown( $this, $this->locations, $this->employee, false, false, '', true );
						if($this->setting['display_employee_site_name']) {
							$facDropDown = renderFacilityDropDown($this->facilities, $this->employee['site_id'], $this->viewonly);
							if ($this->hasACL ( 'edit_facility' )) {
								$facDropDown .= '<a href="'.$this->base_url.'/site/add">'.t('Insert a New').space.t('Site').'</a> ';
								$facDropDown .= '<a href="'.$this->base_url.'/site/search">'.t('View/Edit').space.t('Site').'</a>'; // need to put the links inside of the div so they dont wrap to the next line
							}
							echo labelAndField($this, t('Site').space.t('Name'), $facDropDown, 'site');
						}
						if($this->setting['display_employee_site_type'])
						echo labelAndField($this,t('Site').space.t('Type'),   $this->site_types);

						if($this->setting['display_employee_staff_category'])
						echo labelAndField($this, t('Staff Category'), $this->categories);
						if($this->setting['display_employee_registration_number'])
						echo labelAndField($this, t('Registration Number'),    'text', 'registration_number',    $this->employee['registration_number']);
						
						if($this->setting['display_employee_contract_end_date'])
						    echo labelAndField($this, t('Contract End Date'),      'date', 'agreement_end_date', $this->employee['agreement_end_date']);
						if($this->setting['display_employee_intended_transition'])
						    echo labelAndField($this, t('Intended Transition'), $this->transitions, 'employee_transition_option_id');
						echo labelAndField($this, t('Other Transition'),  'text', 'transition_other',  $this->employee['transition_other']); // hidden field
						if($this->setting['display_employee_transition_confirmed'])
						    echo confirmDropdown($this, t('Transition Confirmed'), 'transition_confirmed', $this->employee['transition_confirmed']);
						echo labelAndField($this, t('Intended Transition Date'), 'date','transition_date', $this->employee['transition_date']);
						if($this->setting['display_employee_complete_transition'])
						    echo labelAndField($this, t('Actual Transition Outcome'), $this->transitions_complete, 'employee_transition_complete_option_id');
						echo labelAndField($this, t('Other Transition'), 'text', 'transition_complete_other', $this->employee['transition_complete_other']); // hidden field
						
						if($this->setting['display_employee_actual_transition_date'])
						    echo labelAndField($this, t('Actual Transition Date'), 'date','transition_complete_date', $this->employee['transition_complete_date']);
						
						
						// fields for only community health workers and community based workers
						echo '<div class="clear"></div><br /><br />';

						echo '<div id="chw"'.($this->expandCHWFields ? '' : ' style="display:none;"') . '>';
							if($this->setting['display_employee_relationship'])
							echo labelAndField($this, t('Relationship between CHW and formal health services'), $this->relationships);
							if($this->setting['display_employee_referral_mechanism'])
							echo labelAndField($this, t('Referral Mechanism'), $this->referrals);
							if($this->setting['display_employee_chw_supervisor'])
							echo labelAndField($this, t('CHW Supervisor'),     $this->supervisors);
							if($this->setting['display_employee_trainings_provided'])
							echo labelAndField($this, t('Trainings provided'), $this->provided);
						echo '</div>';

						// yearly costs of employee
						echo '<div class="clear"></div><br /><br />';
						if($this->setting['display_employee_salary']
							|| $this->setting['display_employee_benefits']
							|| $this->setting['display_employee_additional_expenses']
							|| $this->setting['display_employee_stipend']) {
							echo '<h2>' . t('Annual Cost to Company  (CTC) funded by PEPFAR only Amount') . '</h2>';
							
							if ($this->translation['Employee Local Currency'] && $this->translation['Employee Local Currency'] != 'Employee Local Currency')
								echo "<br>".t('Currency:').space.$this->translation['Employee Local Currency'].'<br clear="all"/>'; #TODO rework
						}
						if($this->setting['display_employee_full_time'])
						    echo labelAndField($this, t('Full Time'),      $this->fulltime);
						echo labelAndField($this, t('Funded hours per week'),  'text', 'funded_hours_per_week',  $this->employee['funded_hours_per_week']);
						
						if($this->setting['display_employee_salary'])
						echo labelAndField($this, t('Salary'),   'text', 'salary',   $this->employee['salary']);
						if($this->setting['display_employee_benefits'])
						echo labelAndField($this, t('Benefits'), 'text', 'benefits', $this->employee['benefits']);
						if($this->setting['display_employee_additional_expenses'])
						echo labelAndField($this, t('Additional Expenses'), 'text', 'additional_expenses', $this->employee['additional_expenses']);
						if($this->setting['display_employee_stipend'])
						echo labelAndField($this, t('Stipend'),  'text', 'stipend',  $this->employee['stipend']);
						if($this->setting['display_employee_annual_cost'])
						echo labelAndField($this, t('(R)Annual Cost'), 'text', 'annual_cost', $this->employee['annual_cost']);
						//if($this->setting['display_employee_external_funding'])
						//echo labelAndField($this, t('Percentage not paid by').space.t('Partner'), 'text', 'external_funding_percent', $this->employee['external_funding_percent']);

						echo '<div class="clear"></div><br /><br />';

						#echo labelAndField($this, t('Employee Comments'), 'textarea', 'comments',       $this->employee['comments']);

						/////////////////////////// data table - course history - and UI javascript ///////////////////////////
					?>
						<div class="clear"></div><br /><br />

					<?php if($this->setting['display_employee_courses_completed']) require_once ('employee_course_table.phtml'); ?>

					<script type="text/javascript">
						validCHWids = [<?php echo implode(',', $this->validCHWids); ?>]; /* watch Cadre field and show/hide CHW divs on CHW fields */
					</script>

					<script type="text/javascript">
						$(document).ready(function () {  /* doc ready */

							itech_save_confirm_on_leave();

							/* Init the table */
							oTable = $('.tablegrid').dataTable({
								"bJQueryUI": true,
								"bPaginate": false,
								"bSort": true,
								"bInfo": false,
								"bFilter": false
							});


							$('#select_employee_qualification_option').change( function () { /* watch Cadre field and show/hide CHW divs on CHW fields */

								if (validCHWids.lastIndexOf( parseInt( $(this).val() ) ) != -1) { // found in the valid list
									$('#chw,#classWrapper').show();
								} else {
									$('#chw,#classWrapper').hide();
								}
							});

							$('#disability_option_id').change( function () { /* watch disability field */
								var objs = $('#disability_comments').parent();
								if ($(this).val() == 1) { // show or hide based on value
									objs.show();
									objs.prev().show();
								} else {
									objs.prev().hide();
									objs.hide();
								}
							}).change(); // fire once

							$('#id').attr({readonly: 'readonly'});
							$('#partner_employee_number').attr({readonly: 'readonly'});
							$('#annual_cost').attr({readonly: 'readonly'});

							$('.datepicker').datepicker({
									changeMonth: true,
									changeYear: true,
									yearRange: "-90:+50",
									dateFormat: "dd/mm/yy"
								});
							$('.calendarbtn').click(openNearestDatePicker);

							$('#salary,#benefits,#additional_expenses,#stipend').change( function () { /* calc amounts */
								$('#annual_cost').calcFieldsMoney('#salary,#benefits,#additional_expenses,#stipend', '#annual_cost');
							});

							$('#select_employee_transition_option').change(function (e) { /* watch the two transition drop downs */
								var selected = $(this).find('option:selected').text();
								if (selected.indexOf("Other") != -1) {
									$('.transition_other,#transition_other').show();
								} else {
									$('.transition_other,#transition_other').hide();
								}
							}).change(); // fire once

							$('select[name=employee_transition_complete_option_id]').change(function (e) { /* watch the two transition drop downs */
								var selected = $(this).find('option:selected').text();
								if (selected.indexOf("Other") != -1) {
									$('.transition_complete_other,#transition_complete_other').show();
								} else {
									$('.transition_complete_other,#transition_complete_other').hide();
								}
							}).change(); // fire once
						});

						(function( $ ){

							$.fn.calcFieldsMoney = function(selector,errField) {
								var flds = $(selector);
								if (! flds.length )
									return;

								var total = 0;
								$('.dec_warning').remove();
								flds.each( function (i, val) {
									new_val = $(this).val().match(/^\D*([\d\.,]+)\s*$/); //optionally $, then 1234 w/ optional decimal, optional space then end
									new_val = (new_val && new_val[1]) ? parseInt(new_val[1]) : 0;
									total += new_val;

									var using_punc_val = $(this).val().match(/[.,]/);
									if (using_punc_val && using_punc_val[0]) { // display warning if using puncuation (!! is force compare bool)
										$('.dec_warning').remove();
										$(errField).after('<span class="errorText dec_warning"> <br> <?php tp('Please do not use decimal places or change, please round the amount up to the next dollar'); ?></span>')
									}
								});

								if ( isNaN (total) )
									total = '?';

								$(this).val(total);
								return this;

						};})( jQuery );

						$(function (e) { /* docready */
							// we dont want to capture national id data if not southafrica, only their site.
							var select   = $('#select_lookup_nationalities');
							var id_fld   = $('#national_id');
							var passport = $('#other_id');
							if (! select.length)
								return;
                            if (location.hostname.indexOf("pepfarskillsmart.trainingdata.org") !== -1) /*south africa*/
								return;
							select.change(function (e) {
								if (id_fld.length) {
									if (select.val() != 1) /*south africa - these values are hardcoded. */
										id_fld.attr('disabled','disabled');
									else
										id_fld.attr('disabled', null);
								}
								if (passport.length) {
									if (select.val() == 2) /*foreign*/
										passport.attr('disabled', null);
									else
										passport.attr('disabled','disabled');
								}
							}).change();

							$('#select_employee_base_option').change( function () { /* watch based at field */
								var val = $(this).val();
								var real_val = $(this).find('option:selected').text();
								$('#facilityInput,#province_id,#district_id,#region_c_id,#region_d_id,#region_e_id,#region_f_id,#region_g_id,#region_h_id,#region_i_id').attr('disabled', ((real_val == "Non South African based office") ? 'disabled' : null)); // enable/disable site by value of base field
							}).change(); // fire once

							rgnsels = $('#province_id,#district_id,#region_c_id,#region_d_id,#region_e_id,#region_f_id,#region_g_id,#region_h_id,#region_i_id');
							rgnsels.change(function (e) { /* southafrica, hardcoded, they dont want site_enabled if multiple regions selected */
								var off = false;
								rgnsels.each(function (i, val) {
									var chosen = $(this).find('option:selected').html();
									if (!off && (chosen.indexOf('*Multiple') != -1 || chosen.indexOf('*Not In') != -1))
										off = true;
								});
								if (off)
									$('#facilityInput').attr('disabled', 'disabled');
								else
									$('#facilityInput').removeAttr('disabled');
							});


						});
					</script>



				<h1><?php tp('Mechanisms'); ?>:</h1>
				<div style="width:100%;">

					<table cellpadding="0" cellspacing="0" border="0" class="display tablegrid" id=""
						   style="width:100%">
						<thead>
						<tr>
							<th><?php tp('Mechanism'); ?></th>
							<th><?php tp('Percent'); ?></th>
							<?php if ($this->setting['display_hours_per_mechanism']){ ?>
								<th><?php tp('Hours'); ?></th>
							<?php }
							if ($this->setting['display_annual_cost_to_mechanism'])	{ ?>
								<th><?php tp('Annual Cost'); ?></th>
							<?php } ?>
							<th><?php tp("Delete?"); ?></th>
						</tr>
						</thead>
						<tbody id="employee_mechanism_table">
						<?php foreach ($this->employeeMechanisms as $mech) { ?>
							<tr id="<?php echo $mech['id']; ?>">
								<td><?php echo $mech['mechanism_phrase']; ?></td>
								<td><?php echo $mech['percentage']; ?></td>
							<?php if ($this->setting['display_hours_per_mechanism']){ ?>
								<td><?php echo ($mech['percentage']/100.0 * $this->employee['funded_hours_per_week']) ; ?></td>
							<?php }
							if ($this->setting['display_annual_cost_to_mechanism'])	{ ?>
								<td><?php echo sprintf('%0.2f', $mech['percentage']/100.0 * $this->employee['annual_cost']); ?></td>
							<?php } ?>
								<td><input type="checkbox" onclick="deleteToggle(this);"/></td>
							</tr>
						<?php } ?>
						</tbody>
					</table>
				</div>

                <script>
                    function deleteToggle(element) {
                        // get jQuery version of the element
                        var el = $(element);
                        var siblings = el.parent().siblings('td');
                        var idList = $("#disassociateMechanisms").data("ids");

                        // get the mechanism association id in the tr element
                        var id = el.parent().parent().attr("id");

                        var mechID = el.parent().siblings().first().data('mechID');

                        if (element.checked) {
                            siblings.css({"text-decoration" : "line-through", "color" : "red", "font-style" : "italic"});
                            if (typeof id != 'undefined') {
                                idList.push(id);
                            }
                            else {
                                // since there's no tr id,
                                // this should be a new mechanism that's been deleted before it was saved

                                $("#associateMechanisms").removeData(mechID);

                                var mechIndex = $.inArray(mechID, $("#associateMechanisms").data('ids'));
                                // TODO: remove debug
                                var d = $("#associateMechanisms").data();
                                $("#associateMechanisms").data('ids', $("#associateMechanisms").data('ids').splice(mechIndex, 1));
                                $("#mechanismPercentages").data('ids', $("#mechanismPercentages").data('ids').splice(mechIndex, 1));


                            }
                            window.mechData['employee_mechanism_ids'].splice($.inArray(mechID, window.mechData['employee_mechanism_ids']), 1);

                        }
                        else {

                            if (typeof id != 'undefined') {
                                siblings.css({"text-decoration" : "", "color" : "", "font-style" : ""});
                                // use jQuery's inArray because IE <9 doesn't support indexOf in arrays
                                idList.splice($.inArray(id, idList), 1);
                            }
                            else {
                                // since there's no tr id,
                                // this should be a new mechanism that's been deleted and now un-checked again
                                // before it was saved
                                siblings.css({"text-decoration" : "", "color" : "green", "font-style" : ""});

                                var percent = el.parent().siblings().first().next().text();

                                // TODO: remove debug
                                d = $("#associateMechanisms").data();
                                $("#associateMechanisms").data("ids").push(mechID);
                                d = $("#mechanismPercentages").data();
                                $("#mechanismPercentages").data("percents").push(percent);

                            }
                            window.mechData['employee_mechanism_ids'].push(mechID);
                        }
                        availableMechanisms();
                        return true;
                    }
                    function addMechanism() {
                        var tbody = $("#employee_mechanism_table");
                        var percent = $("#percentage").val();
                        var fpercent = percent / 100.0;
                        var selectedMechanism = $("#new_mechanism option:selected");
                        var mechID = selectedMechanism.val();

                        var newRow = $("<tr><td>" + selectedMechanism.text() + "</td><td>" + percent +
                            "</td><td>" + (fpercent * <?php echo $this->employee['funded_hours_per_week']?>).toFixed(2) +
                            "</td><td>" + (fpercent * <?php echo $this->employee['annual_cost']?>).toFixed(2) +
                            '</td><td><input type="checkbox" onclick="deleteToggle(this);"/></td></tr>');
                        newRow.children().css({"color": "green", "font-weight": "bold"});

                        var d = newRow.children().first();
                        d = d.data();
                        newRow.children().first().data("mechID", mechID);
                        d = newRow.children().first().data();
                        tbody.append(newRow);

                        $("#associateMechanisms").data("ids").push(mechID);
                        $("#mechanismPercentages").data("percents").push(percent);
                        window.mechData['employee_mechanism_ids'].push(mechID);

                        availableMechanisms();

                        return true;
                    }
                    function processMechanismAssociations() {
                        $("#associateMechanisms").val($("#associateMechanisms").data("ids").join(','));
                        $("#mechanismPercentages").val($("#mechanismPercentages").data("percents").join(','));
                        $("#disassociateMechanisms").val($("#disassociateMechanisms").data("ids").join(','));
                        return true;
                    }
                </script>

                <input type="hidden" id="disassociateMechanisms" name="disassociateMechanisms"/>
                <input type="hidden" id="associateMechanisms" name="associateMechanisms"/>
                <input type="hidden" id="mechanismPercentages" name="mechanismPercentages"/>

                     <input type="hidden" id="employeeFunding_delete_data" name="employeeFunding_delete_data"/>
                     <input type="hidden" id="employeeFunding_new_data" name="employeeFunding_new_data"/>
                     <?php 
                     echo $this->tableEmployeeFunding;
                     ?>
                    <br />
                      <script>
                    	// fired on "insert" button click
                    	function addMechanism2(oButton) {
                    	    var oMechanism = YAHOO.util.Dom.get('new_mechanism');
                    	    var oPercent = YAHOO.util.Dom.get('percentage');
                    
                    	    if(oMechanism.value == ""){
                        	    alert("Mechanism cannot be empty.");
                        	    return;
                    	    }
                    
                    	    if(oPercent.value == ""){
                        	    alert("Percentage cannot be empty.");
                        	    return;
                    	    }
                    	    else if(isNaN(oPercent.value) || (oPercent.value < 1) || (oPercent.value > 100)) {
                    		    alert("Percentage must be a number from 1 to 100.");
                    		    return;
                    	    }
                    
                            var jsonAdd = { }
                            jsonAdd.mechanism_phrase = oMechanism.selectedOptions[0].label;
                            jsonAdd.id = oMechanism.value;
                            jsonAdd.percentage = oPercent.value;
                            var percent = jsonAdd.percentage / 100.0;
                            
                            jsonAdd.hours = (percent * <?php echo $this->employee['funded_hours_per_week']?>).toFixed(2);
                            jsonAdd.cost = (percent * <?php echo $this->employee['annual_cost']?>).toFixed(2);
                          	ITECH.employeeFundingTable.addDataRow(jsonAdd, oMechanism.value);
                                    
                            oMechanism.value = "";
                            oPercent.value = "";
                            window.mechData['employee_mechanism_ids'].push(jsonAdd.id);
                            availableMechanisms();
                          }
                      </script>
                      
                    <div><label class="label">Mechanism</label>
                      <select id="new_mechanism" name="new_mechanism"></select>
                      <span>
                        <label class="label">Percentage</label>
                        <input type="text" id="percentage" name="percentage" value="" />
                      </span>
                      <input type="button" name="associateMechanism" value="<?php tp("Add");?>" class="insert" id="mechanismInsertButton" onclick="addMechanism();"/>
                    </div>

					<div class="clear"></div>
					<input type="hidden" name="limit" id="limit" value="1" />

					<input type="submit" class="submitNoArrow" name="saveonly" onclick="processMechanismAssociations();" value="<?php tp('Save');?>" />


            </form>
			<div class="clear"></div>
            <script type="application/javascript">
                $(document).ready(function() {
                    window.mechData = JSON.parse($("#mechanismData").html());
                    $('#select_partner').on('change', availableMechanisms);
                    availableMechanisms();
                    $("#disassociateMechanisms").data("ids", []);
                    $("#associateMechanisms").data("ids", []);
                    $("#mechanismPercentages").data("percents", []);

                });
            </script>

            <script type="application/javascript">
                var availableMechanisms = function() {
                    var optList = '<option value="">--choose--</option>';
                    var partnerID = $('#select_partner').val();
                    var mechData = window.mechData;
                    var numMechs = mechData['available'].length;
                    var mech;
                    for (var i = 0; i < numMechs; i++) {
                        mech = mechData['available'][i];
                        if ((mech['partners'].indexOf(partnerID) > -1) && (mechData['employee_mechanism_ids'].indexOf(mech['id']) < 0)) {
                            optList += '<option value="' + mech['id'] + '">' + mech['mechanism_phrase'] + '</option>';
                        }
                    }
                    $('#new_mechanism').html(optList);
                }
            </script>

			<div class="clear"></div>
		</div>
	</body>
</html>
