<!DOCTYPE html>
<html>
<head>
    <title><?php echo $this->translation['Application Name'] . " | " . $this->pageTitle; ?></title>
    <?php
    require_once('views/helpers/Location.php');
    require_once('views/helpers/ScriptContainer.php');
    print ScriptContainer::$instance->renderCSSHead();
    print ScriptContainer::$instance->renderJSHead();
    ?>
    <script type="text/javascript" charset="utf-8">
        $(document).ready(function () {
            var oTable = $('.tablegrid').dataTable({
                "bJQueryUI": true,
                "bSort": true,
                "sPaginationType": "full_numbers",
                "aaData" : <?php echo json_encode($this->output, JSON_HEX_APOS|JSON_HEX_QUOT); ?>,
                "aoColumns" : <?php echo json_encode(array_map(function ($header) { return array('sTitle' => $header); }, $this->headers), JSON_HEX_APOS|JSON_HEX_QUOT);?>
            });
            $('.tablegrid tbody').on('click', 'tr', function() {
                window.location = '/employee/edit/id/' + this.children[0].innerText;
            });
            $('.tablegrid tbody').css('cursor', 'pointer');
        });

        function fnGetSelected( oTableLocal ){
            var aReturn = new Array();
            var aTrs = oTableLocal.fnGetNodes();

            for ( var i=0 ; i<aTrs.length ; i++ ){
                if ( $(aTrs[i]).hasClass('row_selected') ){
                    aReturn.push( aTrs[i] );
                }
            }
            return aReturn;
        }

        function goToEmployee(id) {
            window.location = '/employee/edit/id/' + id;
        }

    </script>

</head>
<body>

<div id="pageHolder">

    <div id="header"><?php require_once('views/scripts/header.phtml');?></div>
    <div id="content">

        <h1><?php print(t('Search').space.t('Employees'));?></h1>
        <form action="" method="get" class="form_employee">
            <fieldset><legend><?php tp('Select Criteria');?></legend>


                <?php
                $this->required_fields = array();

                echo labelAndField($this, t('Employee Code'), 'text', 'employee_code', $this->criteria['employee_code']);

                //TA:#293 multiple location selection
                //TA:#293.1
                region_filters_dropdown( $this, $this->locations, $this->criteria, true, false );

                if ( $this->setting['display_employee_partner'] ) {
                    echo labelAndField($this, t('Partner'), $this->partners);

                }
                if ( $this->setting['display_employee_site_name'] )
                    echo labelAndField($this, t('Site'), renderFacilityDropDown($this->sites, $this->criteria['facilityInput'], $this->viewonly));

                echo labelAndField($this, t('Staff Cadre'),    $this->cadres);

                if ( $this->setting['display_employee_staff_category'] )
                    echo labelAndField($this, t('Staff Category'), $this->categories);

                ?>
                <div class="clear"></div>
                <input type="hidden" name="limit" id="limit" value="1" />
                <input type="submit" class="submitNoArrow" name="go" value="<?php tp('Preview');?>" />
            </fieldset>
        </form>

        <?php if ( $this->criteria['go'] ) {
            // datatables fills in the table, no need for inner tags
            ?>
            <table cellpadding="0" cellspacing="0" border="0" class="display tablegrid" id="" style="width:100%"></table>
        <?php } ?>
    </div>
</body>
</html>