<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
  <title><?php echo $this->translation['Application Name'];?></title>
		<?php
		require_once('views/helpers/ScriptContainer.php');
		print ScriptContainer::$instance->renderCSSHead();
		print ScriptContainer::$instance->renderJSHead();
		?>

	</head>
	<body class="yui-skin-sam">

		<div id="pageHolder">

  <div id="header"><?php require_once('views/scripts/header.phtml');?></div>
  <div id="content">

    <h1><?php print t('Welcome to').' '.$this->translation['Application Name'];?></h1>
	<h2><?php tp('Training System Monitoring and Reporting Tool');?></h2><br/>
  	<?php if ($this->isLoggedIn()) { ?>
				<?php if (isset($this->unique_participants)) { ?>
 <div class="fieldIndentNoMargin"><?php tp('Data Summary');?></div>
	<div class="fieldIndent2">
		<div id="trainingStats"></div>
	</div>

	<script type="text/javascript">
 var statsData = [
		['<?php tp('Participants');?>&nbsp;(<?php echo $this->unique_participants.' '.t('unique');?>)','<?php echo $this->attendees;?>','<?php echo $this->attendees_ytd;?>'],
		['<?php tp('Trainers');?>&nbsp;(<?php echo $this->unique_trainers.' '.t('unique');?>)','<?php echo $this->trainers;?>','<?php echo $this->trainers_ytd;?>'],
		['<?php tp('Trainings');?>','<?php echo $this->trainings;?>','<?php echo $this->trainings_ytd;?>']

   ];

		var statsColumnDefs = [
		    {key:"name", label: "<?php echo $this->min_date;?>&nbsp;to&nbsp;<?php echo $this->max_date;?>", sortable:false, resizeable:true},
		    {key:"total", label: "<?php tp('Total');?>", sortable:false, resizeable:true},
			{key:"ytd", label: "<?php tp('Fiscal Year');?> (since&nbsp;<?php echo $this->ytdStart;?>)", sortable:false, resizeable:true}
		];

		makeDataTable("trainingStats", null, statsData, statsColumnDefs);
	</script>
				<?php } ?>
				<div class="clear"></div>

<?php
	if (isset($this->setting['display_mod_skillsmart']) && ($this->setting['display_mod_skillsmart'] == 1)){
?>
				<div class="fieldIndent2">
					<div id="workerStats"></div>
				</div>
				<script type="text/javascript">
					var workerData = [
					<?php
					foreach ($this->rowy as $row) {
						if($row['qualification_phrase'] == "Nurse") {
							echo '[\''.$row['qualification_phrase'].' (Nurse Initiating ART: '.$this->NIMART.')\',\''.$row['CNT'].'\'],';
						}
						else {
							echo '[\''.$row['qualification_phrase'].'\',\''.$row['CNT'].'\'],';
						}
					}
					?>
					];

					var workerColumnDefs = [
					{key:"qualification_phrase", label: "Occupational category", sortable:false, resizeable:true},
					{key:"CNT", label: "Count", sortable:false, resizeable:true}
					];

					makeDataTable("workerStats", null, workerData, workerColumnDefs);
				</script>
				<div class="clear"></div>
<?php
	}
?>


			<div class="fieldIndentNoMargin"><?php echo t('Future').' '.t('Trainings');?>: <span class="total"><?php tp('Total');?>: <span id="trainingfuture_total">0</span></span>      </div>

			<div class="fieldIndent2">

			<a href="<?php print Settings::$COUNTRY_BASE_URL;?>/calendar"><?php tp('View Printable Calendar');?></a><br /><br />

			<?php if($this->tableTrainingFuture) : ?>
				<div id="trainingfutureTable"></div>
				  <?php echo $this->tableTrainingFuture; ?>
			<?php endif; ?>
			</div>


			<!-- show incomplete trainings -->
			<?php if($this->tableTrainingPast) : ?>

			<div class="fieldIndentNoMargin"><?php echo t('Incomplete').' '.t('Trainings').' '.t('that already occurred');?>: <span class="total"><?php tp('Total');?>: <span id="trainingpast_total">0</span></span></div>
			<div class="fieldIndent2">
			<div id="trainingpastTable"></div>
			  <?php echo $this->tableTrainingPast; ?>
			</div>
			<?php endif; ?>

			<!-- show unapproved trainings -->
			<?php if($this->tableUnapproved) : ?>

			<div class="fieldIndentNoMargin"><?php tp('To be Approved');?></div>
			<div class="fieldIndent2">
			<div id="unapprovedTable"></div>
			  <?php echo $this->tableUnapproved; ?>
			</div>
			<?php endif; ?>

			<div class="clear"></div>

			<!-- TA:17: 09/09/2014 -->
    <?php if ( $this->hasACL ( 'admin_files' ) ) {?>
			    <div class="hrGrey"></div>
			    <div class="clear"></div>
			    <div class="fieldIndentNoMargin"><?php tp('Attached Documents'); ?></div>
			    <div class="fieldIndent2">
			      <?php echo $this->editTableFiles; ?>
			      <span class="caption"><?php tp('Right-click and select "Save Target As..." to download.');?></span>
			    </div>
			    <?php if($this->filesForm) : ?>
			    <div class="fieldIndentNoMargin"><?php tp('Document Upload'); ?></div>
			    <div class="fieldIndent2">
			      <?php echo $this->filesForm; ?>
			    </div>
			<script type="text/javascript">
			YAHOO.util.Event.on(window, 'load', initUploadButton);
			</script>
			    <?php endif; ?>
			    <?php } ?>


	<?php } else { ?>
	<div style="height: 300px;"><br/><br/>
	<div class="fieldLabel" for="spacer"></div>
		<div class="fieldInput"><?php tp('Please login below');?>:</div>

    <form action="<?php echo $this->base_url;?>/user/login" id="userForm" method="post">
   		<div class="fieldLabel" id="username_lbl"><?php tp('User name');?></div>
	  <div class="fieldInput"><input type="text" name="username" size="32" maxlength="32"  tabindex=1  value=""/></div>
   		<div class="fieldLabel" id="password_lbl"><?php tp('Password');?></div>
	  <div class="fieldInput"><input type="password" name="password" size="32" maxlength="32" tabindex=2  value=""/></div>
		<div class="fieldLabel" for="spacer"></div>
		<div class="fieldInput"><a href="<?php echo $this->base_url;?>/user/forgotPassword" tabindex=4 ><?php tp('Forgot your password?');?></a></div>
      <input type="submit" value="Sign In" tabindex=3  title="log in now" class="submitArrow"/>

  	</form>
  	</div>
	<?php } ?>

  </div>
  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>


		</div>

	</body>
</html>