<?php

// Aggregate all our JS files into one file

// it would be better to build this aggregate just once when the javascript code is updated
// (perhaps when updates are deployed) instead of generating it dynamically each time.
// this would also allow web browsers to cache the file instead of downloading it every request.

require_once('views/helpers/ScriptContainer.php');

foreach (ScriptContainer::$jsfiles as $file) {
    $didRead = readfile(Globals::$BASE_PATH . Globals::$WEB_FOLDER . $file);
    echo "\n\n";
    if (!$didRead) {
        throw new Exception("Problem loading JavaScript file $file");
    }
}

ob_flush();
