<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<title><?php echo $this->translation['Application Name'];?> | <?php tp('Assessments');?></title>
		
		<style>
		</style>
		<?php
		require_once('views/helpers/Location.php');
		require_once('views/helpers/ScriptContainer.php');
		print ScriptContainer::$instance->renderCSSHead();
		print ScriptContainer::$instance->renderJSHead();
		?>
		<script type="text/javascript">
			var vwvls=new Array();
			function SetAll() {
				<?php
				if(isset($this->vwvls[0]))
				{
					$lscntr=0;
					foreach ( $this->vwvls as $ys => $ls ) {
						echo 'vwvls['.$lscntr.']="'.$ls.'";';
						$lscntr++;
					}
				}
				?>
				var i;
				for(i=0;i<vwvls.length;i++){
					if(vwvls[i].indexOf("240")==0){
						document.getElementById('grp240').value=vwvls[i].substr(3);
					} else {
						document.getElementById('grp'+vwvls[i].toLowerCase()).checked=true;
					}
				}
			}
		</script>
	</head>
	<body  class="yui-skin-sam" onload="SetAll()">
		<div id="pageHolder">
			<div id="header"><?php require_once('views/scripts/header.phtml');?></div>
			<div id="content">
				<h1><?php echo t('Edit Assessment'); ?></h1>
				<div style="height:54px">
					<div style="width:486px;text-align:left;float:right">
						<div><b></b>  <?php echo t(''); ?></div>
						<div><b></b>  <?php echo t(''); ?></div>
						<div><b></b>  <?php echo t(''); ?></div>
						<div><b></b>  <?php echo t(''); ?></div>
						<div><b></b>  <?php echo t(''); ?></div>
					</div>
				</div>
				<form action="" id="personCompForm" method="post">

					<?php
					foreach ($this->assessments as $assessment){
						$counter = 0;
						?>
						<h2><?php echo $assessment['assessment_name']; ?></h2>
						<div style="height:12px"></div>
						<div class="nwtxthead"><?php echo 
										$assessment['first_name'] . ' ' .
										$assessment['last_name'] . ', ' .
										$assessment['facility_name'] . ', ' .
						                $assessment['date_created'] ; ?></div>
						
						<table cellpadding="0" cellspacing="0" border="0" style="width:100%;border:solid 1px #AAA">
                    <?php
							$lasttype = "";
							$first_calender = "true";
							foreach ($assessment['questions'] as $question){
								switch ($question['itemtype']){
									case "text":
									echo "						<tr>\n";
									echo '							<td style="width:68%">';
									echo "								<div class=\"nwtxtbig\">" . $question['question'] . "</div>\n";
									echo "							</td>\n";
									echo "						</tr>\n";
									break;
									case "questiondate":
									    $counter++;
									    
									    $answer = "";
									    
									    foreach ($assessment['answers'] as $a){
									        if ($a['question'] == $question['id']){
									            $answer = $a['option'];
									        }
									    }
									    
									    $date_array = explode('-', $answer);
									    $vday = $date_array[0];
									    $vmonth = $date_array[1];
									    $vyear = $date_array[2];
									    
                                        $date_id = $question['id'] . '"';
                                        $adate = '"answer' . $date_id;
                                        $adate_sub = 'questions[' . $question['id'] . ']';
                                        $aday = '"answer_day' . $date_id;
                                        $amonth = '"answer_month' . $date_id;
                                        $ayear = '"answer_year' . $date_id;
                                        
									    
									    echo "						<tr>\n";
									    echo "							<td colspan=\"7\">";
									    echo '								<div class="nwtxt">'; echo $question['question']; echo '</div>';
									    echo '							</td>';
									    echo '							<td colspan="6" style="text-align:center">';
									    echo "						<tr>";
									    echo '							<td colspan="6" style="text-align:right">';
									    echo "<div class='input' id=" . $adate . ' name="answer' . $question['id'] . '" >';
									    tp('Day'); 
									    echo "  <input id=" . $aday . " class='dayfield' type='text' name=" . $aday . " maxlength='2' value=" . $vday;
									    echo $this->criteria['answer-day']; echo "  > ";
									    tp('Month'); 
									    echo "  <input id=" . $amonth . " class='monthfield' type='text' name=" . $amonth . " maxlength='2' value=" . $vmonth;
									    echo $this->criteria['answer-month']; echo "  > ";
									    tp('Year');  
									    echo "  <input id=" . $ayear . " class='yearfield' type='text' name=" . $ayear . " maxlength='4' value=" . $vyear;
									    echo $this->criteria['answer-year']; echo " > ";
									    echo "						</td></tr>";
									    echo "<script  type='text/javascript'>";
									    echo "YAHOO.util.Event.onDOMReady(function () {";
									    if ($first_calender == 'true'){
									        echo "makeCalendar($adate,$aday,$amonth,$ayear);";
									        $first_calender = "false";
									    } else {
									        echo "makeAdditionalCalendar($adate,$aday,$amonth,$ayear);";
									    }
									    echo "});";
									    echo "</script>";
									    echo "							</td>";
									    echo "						</tr>";
									    
									    echo '						<tr>';
									    echo '							<td style="width:68%">';
									    echo '								<div class="nwtxtbig">&nbsp;</div>';
									    echo '							</td>';
									    echo '						</tr>';
									    
									break;
									
									case "questiondropdown":
									    $counter++;
									    
									    $answer = "";
									    foreach ($assessment['answers'] as $a){
									        if ($a['question'] == $question['id']){
									            $answer = $a['option'];
									        }
									    }
									    
									    echo '						<tr>';
									    echo '							<td style="width:68%">';
									    //echo '								<div class="nwtxt">' . $counter . ')&nbsp;' . $question['question'] . '</div>';
									    echo '								<div class="nwtxt">' . $question['question'] . '</div>';
									    echo '							</td>';
									    echo '							<td colspan="6" style="text-align:right">';
									    ?>

									    <div class="fieldLabel" id="type_id_lbl"><?php echo t('');?></div>
									    		<div class="fieldInput">
									    		<?php echo '<select id="dropdown' . $question['id'] . '" name="dropdown' . $question['id'] . '" >' ?>
									    		<option value="--N/A--">--N/A--</option>
									    		<?php
									    		foreach ( $this->dropdowns as $k=>$vals ) {
									    		    if($question['id'] == $vals['id']) {

echo '<option value="'.$vals['dropdown_phrase'].'" '.(($answer) == $vals['dropdown_phrase']? 'SELECTED':'').' >'.$vals['dropdown_phrase'].'</option>';
									    		    }
									    		}
									    		?>
									    		</select></div>
									    
									    
									    <?php 
									    
									    echo '							</td>';
									    echo '						</tr>';
									break;
									
									
									
									
									
									
									
									case "questionyesno":
										$counter++;
										if ($lasttype != $question['itemtype']){
											echo '						<tr>';
											echo '							<td style="width:68%">';
											echo '								<div class="nwtxtbig">&nbsp;</div>';
											echo '							</td>';
											echo '							<td style="width:5%;text-align:center">';
											echo '								<div class="nwtxtbig">'.t('Yes').'</div>';
											echo '							</td>';
											echo '							<td style="width:5%;text-align:center">';
											echo '								<div class="nwtxtbig">'.t('No').'</div>';
											echo '							</td>';
											echo '							<td style="width:5%;text-align:center">';
											echo '								<div class="nwtxtbig">&nbsp;</div>';
											echo '							</td>';
											echo '							<td style="width:5%;text-align:center">';
											echo '								<div class="nwtxtbig">&nbsp;</div>';
											echo '							</td>';
											echo '							<td style="width:5%;text-align:center">';
											echo '								<div class="nwtxtbig">&nbsp;</div>';
											echo '							</td>';
											echo '							<td style="width:7%;text-align:center">';
											echo '								<div class="nwtxtbig">'.t('No Answer').'</div>';
											echo '							</td>';
											echo '						</tr>';
										}

$answer = "F";
foreach ($assessment['answers'] as $a){
	if ($a['question'] == $question['id']){
		$answer = $a['option'];
	}
}
										echo '						<tr>';
										echo '							<td style="width:68%">';
										//echo '								<div class="nwtxt">' . $counter . ')&nbsp;' . $question['question'] . '</div>';
										echo '								<div class="nwtxt">' . $question['question'] . '</div>';
										echo '							</td>';
										echo '							<td style="width:5%;text-align:center">';
										echo '								<input type="radio" id="question' . $question['id'] . '" value="A"' . ($answer == "A" ? " checked" : "") . ' name="question[' . $question['id'] . ']" />';
										echo '							</td>';
										echo '							<td style="width:5%;text-align:center">';
										echo '								<input type="radio" id="question' . $question['id'] . '" value="B"' . ($answer == "B" ? " checked" : "") . ' name="question[' . $question['id'] . ']" />';
										echo '							</td>';
										echo '							<td style="width:5%;text-align:center">&nbsp;</td>';
										echo '							<td style="width:5%;text-align:center">&nbsp;</td>';
										echo '							<td style="width:5%;text-align:center">&nbsp;</td>';
										echo '							<td style="width:7%;text-align:center">';
										echo '								<input type="radio" id="question' . $question['id'] . '" value="F"' . ($answer == "F" ? " checked" : "") . ' name="question[' . $question['id'] . ']" />';
										echo '							</td>';
										echo '						</tr>';
									break;
									case "questiontext":
										$counter++;

										$answer = "";
										foreach ($assessment['answers'] as $a){
											if ($a['question'] == $question['id']){
												$answer = $a['option'];
											}
										}

										echo '						<tr>';
										echo '							<td style="width:68%">';
										//echo '								<div class="nwtxt">' . $counter . ')&nbsp;' . $question['question'] . '</div>';
										echo '								<div class="nwtxt">' . $question['question'] . '</div>';
										echo '							</td>';
										echo '							<td colspan="6" style="text-align:center">';
										echo '								<input type="text" id="question' . $question['id'] . '" name="question[' . $question['id'] . ']" maxlength="128" style="width : 99%;" value="' . substr($answer,0,128) . '" />';
										echo '							</td>';
										echo '						</tr>';
									break;
									case "questiontextarea":
									    $counter++;
									
									    $answer = "";
									    foreach ($assessment['answers'] as $a){
									        if ($a['question'] == $question['id']){
									            $answer = $a['option'];
									        }
									    }
									
									    echo '						<tr>';
									    echo '							<td style="width:68%">';
									    //echo '								<div class="nwtxt">' . $counter . ')&nbsp;' . $question['question'] . '</div>';
									    echo '								<div class="nwtxt">' . $question['question'] . '</div>';
									    echo '							</td>';
									    echo '							<td colspan="6" >';
echo '<textarea id="question' . $question['id'] . '" name="question[' . $question['id'] . ']" cols="48" rows="1"  . ">'. substr($answer,0,2048) .'</textarea>';
										echo '							</td>';
									   
									    echo '						</tr>';
									    
									    echo '						<tr>';
									    echo '							<td style="width:68%">';
									    echo '								<div class="nwtxt">&nbsp;</div>';
									    echo '							</td>';
									    echo '						</tr>';
									    
									    break;
									case "question110":
									    // question 1 to 10
									    $counter++;
									    if ($lasttype != $question['itemtype']){
									        echo '						<tr>';
									        echo '							<td style="width:68%">';
									        echo '								<div class="nwtxtbig">&nbsp;</div>';
									        echo '							</td>';
									        echo '							<td style="width:5%;text-align:center">';
									        echo '								<div class="nwtxtbig">1</div>';
									        echo '							</td>';
									        echo '							<td style="width:5%;text-align:center">';
									        echo '								<div class="nwtxtbig">2</div>';
									        echo '							</td>';
									        echo '							<td style="width:5%;text-align:center">';
									        echo '								<div class="nwtxtbig">3</div>';
									        echo '							</td>';
									        echo '							<td style="width:5%;text-align:center">';
									        echo '								<div class="nwtxtbig">4</div>';
									        echo '							</td>';
									        echo '							<td style="width:5%;text-align:center">';
									        echo '								<div class="nwtxtbig">5</div>';
									        echo '							</td>';
									        	
									        echo '							<td style="width:7%;text-align:center">';
									        echo '								<div class="nwtxtbig">'.t('No Answer').'</div>';
									        echo '							</td>';
									        echo '						</tr>';
									    }
									
									    $answer = "F";
									    foreach ($assessment['answers'] as $a){
									        if ($a['question'] == strtoupper($question['id'])){
									            $answer = $a['option'];
									        }
									    }
									
									    echo '						<tr>';
									    echo '							<td style="width:68%">';
									    //echo '								<div class="nwtxt">' . $counter . ')&nbsp;' . $question['question'] . '</div>';
									    echo '								<div class="nwtxt">' . $question['question'] . '</div>';
									    echo '							</td>';
									    echo '							<td style="width:5%;text-align:center">';
									    echo '								<input type="radio" id="question' . $question['id'] . '" value="A"' . ($answer == "A" ? " checked" : "") . ' name="question[' . $question['id'] . ']" />';
									    echo '							</td>';
									    echo '							<td style="width:5%;text-align:center">';
									    echo '								<input type="radio" id="question' . $question['id'] . '" value="B"' . ($answer == "B" ? " checked" : "") . ' name="question[' . $question['id'] . ']" />';
									    echo '							</td>';
									    echo '							<td style="width:5%;text-align:center">';
									    echo '								<input type="radio" id="question' . $question['id'] . '" value="C"' . ($answer == "C" ? " checked" : "") . ' name="question[' . $question['id'] . ']" />';
									    echo '							</td>';
									    echo '							<td style="width:5%;text-align:center">';
									    echo '								<input type="radio" id="question' . $question['id'] . '" value="D"' . ($answer == "D" ? " checked" : "") . ' name="question[' . $question['id'] . ']" />';
									    echo '							</td>';
									    echo '							<td style="width:5%;text-align:center">';
									    echo '								<input type="radio" id="question' . $question['id'] . '" value="E"' . ($answer == "E" ? " checked" : "") . ' name="question[' . $question['id'] . ']" />';
									    echo '							</td>';
									    echo '							<td style="width:7%;text-align:center">';
									    echo '								<input type="radio" id="question' . $question['id'] . '" value="F"' . ($answer == "F" ? " checked" : "") . ' name="question[' . $question['id'] . ']" />';
									    echo '							</td>';
									    echo '						</tr>';
									
									    break;
									case "questionmulti":
									    // default:
										// questionmulti
										$counter++;
										if ($lasttype != $question['itemtype']){
											echo '						<tr>';
											echo '							<td style="width:68%">';
											echo '								<div class="nwtxtbig">&nbsp;</div>';
											echo '							</td>';
											echo '							<td style="width:5%;text-align:center">';
											echo '								<div class="nwtxtbig">A</div>';
											echo '							</td>';
											echo '							<td style="width:5%;text-align:center">';
											echo '								<div class="nwtxtbig">B</div>';
											echo '							</td>';
											echo '							<td style="width:5%;text-align:center">';
											echo '								<div class="nwtxtbig">C</div>';
											echo '							</td>';
											echo '							<td style="width:5%;text-align:center">';
											echo '								<div class="nwtxtbig">D</div>';
											echo '							</td>';
											echo '							<td style="width:5%;text-align:center">';
											echo '								<div class="nwtxtbig">E</div>';
											echo '							</td>';
											echo '							<td style="width:7%;text-align:center">';
											echo '								<div class="nwtxtbig">'.t('No Answer').'</div>';
											echo '							</td>';
											echo '						</tr>';
										}
	
										$answer = "F";
										foreach ($assessment['answers'] as $a){
											if ($a['question'] == strtoupper($question['id'])){
												$answer = $a['option'];
											}
										}

										echo '						<tr>';
										echo '							<td style="width:68%">';
										//echo '								<div class="nwtxt">' . $counter . ')&nbsp;' . $question['question'] . '</div>';
										echo '								<div class="nwtxt">' . $question['question'] . '</div>';
										echo '							</td>';
										echo '							<td style="width:5%;text-align:center">';
										echo '								<input type="radio" id="question' . $question['id'] . '" value="A"' . ($answer == "A" ? " checked" : "") . ' name="question[' . $question['id'] . ']" />';
										echo '							</td>';
										echo '							<td style="width:5%;text-align:center">';
										echo '								<input type="radio" id="question' . $question['id'] . '" value="B"' . ($answer == "B" ? " checked" : "") . ' name="question[' . $question['id'] . ']" />';
										echo '							</td>';
										echo '							<td style="width:5%;text-align:center">';
										echo '								<input type="radio" id="question' . $question['id'] . '" value="C"' . ($answer == "C" ? " checked" : "") . ' name="question[' . $question['id'] . ']" />';
										echo '							</td>';
										echo '							<td style="width:5%;text-align:center">';
										echo '								<input type="radio" id="question' . $question['id'] . '" value="D"' . ($answer == "D" ? " checked" : "") . ' name="question[' . $question['id'] . ']" />';
										echo '							</td>';
										echo '							<td style="width:5%;text-align:center">';
										echo '								<input type="radio" id="question' . $question['id'] . '" value="E"' . ($answer == "E" ? " checked" : "") . ' name="question[' . $question['id'] . ']" />';
										echo '							</td>';
										echo '							<td style="width:7%;text-align:center">';
										echo '								<input type="radio" id="question' . $question['id'] . '" value="F"' . ($answer == "F" ? " checked" : "") . ' name="question[' . $question['id'] . ']" />';
										echo '							</td>';
										echo '						</tr>';
	
									break;
								}
								$lasttype = $question['itemtype'];
							}
							echo "						<tr>\n";
							echo "							<td colspan=\"7\">\n";
							echo "								<div class=\"nwtxtbig\">&nbsp;</div>\n";
							echo "							</td>\n";
							echo "						</tr>\n";

?>
						</table>
						<div style="height:16px"></div>
						<?php
					}

					?>
					<div class="actionBtn">
						<input type="submit" class="submitNoArrow" name="go" value="<?php echo t('Save'); ?>" />
					</div>
					<div class="clear"></div>
				</form>
			</div>
		</div>
		<div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
	</body>
</html>
