<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <title><?php echo t($this->translation['Application Name']); ?> | <?php echo t($this->pageTitle); ?></title>
    <?php
    require_once('views/helpers/ScriptContainer.php');
    print ScriptContainer::$instance->renderCSSHead();
    print ScriptContainer::$instance->renderJSHead();

    require_once('views/helpers/TrainingViewHelper.php');

    ?>
    <style>

        <?php if($this->viewonly) : ?>
        .required {
            display: none;
        }

        <?php endif; ?>

    </style>

</head>
<body class="yui-skin-sam">
<div id="pageHolder">
    <div id="header"><?php require_once('views/scripts/header.phtml'); ?></div>
    <div id="content" class="<?php if ($this->mode != 'add') print 'edit-training' ?>">

        <h1><?php echo $this->pageTitle; ?></h1>

        <?php if ($this->mode != 'add') : ?>
            <?php if (!$this->viewonly) : ?>
                <div class="actionBtn">
                    <div class="clear yui-push-button">
                        <button type="button"
                                onclick="submitForm();"><?php echo t('Save') . ' ' . t('Training'); ?></button>
                    </div>
                </div>
            <?php endif; ?>

        <?php endif; ?>

        <?php if ($this->msg) echo '<div class="errorText">' . $this->msg . '</div>'; ?>


        <!-- "add new" training location pop-up modal -->

        <div id="addLocation">
            <div class="hd"><?php echo t('Add new') . ' ' . t('Training Location'); ?></div>
            <div class="bd">

                <h1><?php echo t('Please enter') . ' ' . t('Training') . ' ' . t('location') . ' ' . t('information' . ':'); ?></h1>
                <?php require_once('views/scripts/training/_template_locationform.phtml'); ?>

            </div>
        </div>

        <script>
            YAHOO.namespace("example.container");

            //add end date handler
            function dateCalc() {
                var elSD = YAHOO.util.Dom.get("start-day").value;
                var elSM = YAHOO.util.Dom.get("start-month").value;
                var elSY = YAHOO.util.Dom.get("start-year").value;
                var elED = YAHOO.util.Dom.get("end-day").value;
                var elEM = YAHOO.util.Dom.get("end-month").value;
                var elEY = YAHOO.util.Dom.get("end-year").value;
                if (elSM > 0) elSM--;
                if (elEM > 0) elEM--;
                var startTime = new Date(elSY, elSM, elSD, 1).getTime();
                var endTime = new Date(elEY, elEM, elED, 1).getTime();
                var day = 1000 * 60 * 60 * 24;
                var duration = (endTime - startTime) / day;
                if (duration >= 0 && duration < 1200) {
                    YAHOO.util.Dom.get("training_length_value").value = Math.round(duration) + 1;
                    YAHOO.util.Dom.get("interval2").checked = 'checked';

                }
            }

            function dateConfirm() {
                var elSD = YAHOO.util.Dom.get("start-day").value;
                var elSM = YAHOO.util.Dom.get("start-month").value;
                var elSY = YAHOO.util.Dom.get("start-year").value;
                var elED = YAHOO.util.Dom.get("end-day").value;
                var elEM = YAHOO.util.Dom.get("end-month").value;
                var elEY = YAHOO.util.Dom.get("end-year").value;
                if (elSM > 0) elSM--;
                if (elEM > 0) elEM--;
                var startTime = new Date(elSY, elSM, elSD, 1).getTime();
                var endTime = new Date(elEY, elEM, elED, 1).getTime();
                var day = 1000 * 60 * 60 * 24;
                var duration = (endTime - startTime) / day;
                if (YAHOO.util.Dom.get("training_length_value").value != (Math.round(duration) + 1))
                    alert("<?php echo t('It looks like the').' '.t('training').' '.t('dates do not match the length. Please double check these fields.');?>");

            }

            function init() {

                // Define various event handlers for Dialog
                var handleSubmit = function () {
                    //clear error text
                    var els = YAHOO.util.Dom.getElementsByClassName('errorText');
                    if (els.length)
                        YAHOO.util.Dom.setStyle(els, 'display', 'none');
                    this.submit();
                };
                var handleCancel = function () {
                    this.cancel();
                };
                var handleSuccess = function (o) {
                    var response = o.responseText;
                    var responseObj = YAHOO.lang.JSON.parse(response);
                    displayStatus(responseObj.status);
                    var allGood = true;
                    if (responseObj.messages) {
                        for (var key in responseObj.messages) {
                            YAHOO.example.container.addLocation.show();
                            displayErrorMessage(key, responseObj.messages[key]);
                            allGood = false;
                        }
                    }

                    if (allGood) {
                        var locationNameEl = YAHOO.util.Dom.get('locationName');
                        var oSelect = YAHOO.util.Dom.get('select_training_location');

                        var addIndex = oSelect.options.length;
                        oSelect.options[addIndex] = new Option(locationNameEl.value, responseObj.location_id);
                        oSelect.selectedIndex = addIndex;
                    }

                };
                var handleFailure = function (o) {
                    alert("Submission failed: " + o.status);
                };

                // Instantiate the Dialog
                YAHOO.example.container.addLocation = new YAHOO.widget.Dialog("addLocation",
                    {
                        width: "650px",
                        fixedcenter: true,
                        visible: false,
                        constraintoviewport: true,
                        modal: true,
                        zIndex: 9100,
                        context: ["trainingForm", "tl", "bl"],
                        buttons: [{text: "<?php tp('Submit');?>", handler: handleSubmit, isDefault: true},
                            {text: "<?php tp('Cancel');?>", handler: handleCancel}]
                    });

                // Validate the entries in the form to require that both first and last name are entered
                YAHOO.example.container.addLocation.validate = function () {
                    return true;//do all validation server side
                };

                // Wire up the success and failure handlers
                YAHOO.example.container.addLocation.callback = {
                    success: handleSuccess,
                    failure: handleFailure
                };

                // Render the Dialog
                YAHOO.example.container.addLocation.render();

                YAHOO.util.Event.addListener("show", "click", YAHOO.example.container.addLocation.show, YAHOO.example.container.addLocation, true);


                YAHOO.util.Event.addListener("end-day", "change", dateCalc);
                YAHOO.util.Event.addListener("end-month", "change", dateCalc);
                YAHOO.util.Event.addListener("end-year", "change", dateCalc);

                YAHOO.util.Event.addListener("training_length_value", "change", dateConfirm);
            }
            YAHOO.util.Event.onDOMReady(init);


        </script>

        <div>
            <form name="trainingForm" id="trainingForm" method="post">
                <?php if ($this->mode != 'add') : ?>

                    <!-- history + links -->
                    <div class="historyDiv">
                        <b><?php tp('ID'); ?></b> <?php echo $this->row['id']; ?>
                        <br/><b><?php tp('Date created:'); ?></b> <?php echo $this->row['timestamp_created']; ?><br>
                        <b><?php tp('Created by:'); ?></b> <?php echo $this->row['creator']; ?><br>
                        <b><?php tp('Date modified:'); ?></b> <?php echo $this->row['timestamp_updated']; ?><br>
                        <b><?php tp('Modified by:'); ?></b> <?php echo $this->row['updater']; ?><br>
                        <hr size="1">
                        <a href="javascript:submitThenRedirect('<?php echo $this->base_url; ?>/training/roster/id/<?php echo $this->row['id']; ?>');"
                           onclick=""><?php echo t('View/Print Training Roster'); ?></a><br>
                        <?php if ($this->setting['module_evaluation_enabled']) { ?>
                            <?php if (!@$this->evaluation_id) { ?><a
                                href="javascript:submitThenRedirect('<?php echo $this->base_url; ?>/evaluation/assign-training/id/<?php echo $this->row['id']; ?>');"
                                onclick=""><?php echo t('Assign Evaluation to Training'); ?></a>&nbsp;&nbsp;&nbsp;<?php } ?>
                            <?php if (@$this->evaluation_id) : ?><a
                                href="javascript:submitThenRedirect('<?php echo $this->base_url; ?>/evaluation/data/id/<?php echo $this->evaluation_to_training_id; ?>');"
                                onclick=""><?php tp('Enter Evaluation Data'); ?></a>&nbsp;&nbsp;&nbsp;<a
                                    href="javascript:submitThenRedirect('<?php echo $this->base_url; ?>/reports/evaluations/training_id/<?php echo $this->row['id']; ?>');"
                                    onclick=""><?php tp('View Data'); ?></a>&nbsp;&nbsp;&nbsp;<a
                                href="javascript:submitThenRedirect('<?php echo $this->base_url; ?>/reports/evaluations/training_id/<?php echo $this->row['id']; ?>/outputType/csv');"
                                onclick=""><?php tp('Export'); ?></a><?php else : ?><?php tp('unassigned') ?><?php endif; ?>
                            <br>
                        <?php } ?>
                        <?php if (!$this->viewonly) : ?>
                            <?php if ($this->hasACL('duplicate_training')) {
                                echo '  <a href="" onclick="duplicateTraining(); return false;">' . t('Duplicate this Training') . '</a><br>';
                            } ?>
                            <a href="#"
                               onclick="deleteTraining(); return false;"><?php echo t('Delete this Training'); ?></a>
                        <?php endif; ?>

                    </div>
                <?php endif; ?>
                <!-- TA:17: 8/27/2014 START-->
                <?php if ($this->setting['display_training_category']) {
                    echo "<div class='fieldIndentNoMargin'>&nbsp;</div><br/>";
                    echo "<div class='fieldLabel' id='training_category_id_lbl'>" . $this->translation['Training Category'] . "</div>";
                    echo "<div class='fieldInput'  >";
                    echo @$this->dropDownCategory;
                    echo "</div>";
                } else {
                    echo "<br clear='top'/><br clear='left'/><br clear='top'/>";
                } ?>
                <!-- TA:17: 8/27/2014 END -->

                <div class="fieldLabel" id="training_title_lbl"><span
                        class="required">*</span><?php echo $this->translation['Training Name']; ?></div>
                <div class="fieldInput">

                    <select id="select_training_title_option" name="training_category_and_title_option_id">
                        <option value="">&mdash; <?php tp('select'); ?> &mdash;</option>
                        <?php
                        $lastId = NULL;
                        foreach ($this->categoryTitle as $vals) {
                            $isSelected = ($vals['id'] && $vals['id'] === $this->row['training_title_option_id']) ? ' selected="selected"' : '';

                            // Also list empty prefix to allow all titles to be displayed
                            if ($vals['training_category_option_id'] && $vals['id'] != $lastId) {
                                echo '<option value="_' . $vals['id'] . '">' . $vals['training_title_phrase'] . '</option>';
                            }

                            echo '<option value="' . $vals['training_category_option_id'] . '_' . $vals['id'] . '"' . $isSelected . '>' . $vals['training_title_phrase'] . '</option>';
                            $lastId = $vals['id'];
                        }
                        ?>
                    </select><?php print $this->titleInsertLink; ?>    <?php echo hasACLEdit('acl_editor_training_title', 'admin/training-title', $this); ?>

                </div>

                <script>
                    // Set correct title
                    elCategory = YAHOO.util.Dom.get("select_training_category_option");
                    elTitle = YAHOO.util.Dom.get("select_training_title_option");
                    elCategory.onchange = function () {
                        setTrainingTitle(this.selectedIndex, 'select_training_category_option', 'select_training_title_option');
                    }
                    setTrainingTitle(elCategory.selectedIndex, 'select_training_category_option', 'select_training_title_option');

                    // Select title if editing
                    training_title_id = "<?php print $this->row['training_title_option_id'];?>";
                    if (training_title_id) {
                        for (var i = 0; i < elTitle.options.length; i++) {
                            if (elTitle.options[i].value == elCategory.options[elCategory.selectedIndex].value + "_" + training_title_id) {
                                elTitle.options[i].selected = true;
                            }
                        }
                    }
                    <?php if($this->viewonly) print 'elTitle.disabled = true'; ?>

                    <?php if(!$this->row['id']) { ?>
                    elTitle.selectedIndex = 0; //  do not default to "unknown" title
                    <?php } ?>

                </script>

                <!-- TA:17: 09/02/2014  -->
                <?php if ($this->setting['display_training_start_date']) { ?>
                    <div class="fieldLabel"><?php echo t('Training start date'); ?></div>
                    <div class="fieldInput" id="startdate">
                        <!-- TA:34 fixing bug, allow two digit eneter (remove extra white space for text field) -->
                        <?php tp('Day'); ?> <input id="start-day" class="dayfield" type="text" name="start-day"
                                                   maxlength="2"
                                                   value="<?php echo $this->row['start-day']; ?>" <?php echo $this->viewonly; ?>>
                        / <?php tp('Month'); ?> <input id="start-month" class="monthfield" type="text"
                                                       name="start-month" maxlength="2"
                                                       value="<?php echo $this->row['start-month']; ?>" <?php echo $this->viewonly; ?>>
                        / <?php tp('Year'); ?> <input id="start-year" class="yearfield" type="text" name="start-year"
                                                      maxlength="4"
                                                      value="<?php if ($this->row['start-year']) echo $this->row['start-year']; else echo date('Y'); ?>" <?php echo $this->viewonly; ?>>

                        <?php if (!$this->viewonly) : ?>
                            <script type="text/javascript">
                                YAHOO.util.Event.onDOMReady(function () {
                                    makeCalendar("startdate", "start-day", "start-month", "start-year", dateCalc);
                                });
                            </script>
                        <?php endif; ?>
                    </div><br/>
                <?php } ?>

                <?php if ($this->setting['display_end_date']) { ?>
                    <div class="fieldLabel"><?php echo t('Training end date'); ?></div>
                    <div class="fieldInput" id="enddate">
                        <?php tp('Day'); ?> <input id="end-day" class="dayfield" type="text" name="end-day"
                                                   maxlength="2"
                                                   value="<?php echo $this->row['end-day']; ?>" <?php echo $this->viewonly; ?>>
                        / <?php tp('Month'); ?> <input id="end-month" class="monthfield" type="text" name="end-month"
                                                       maxlength="2"
                                                       value="<?php echo $this->row['end-month']; ?>" <?php echo $this->viewonly; ?>>
                        / <?php tp('Year'); ?> <input id="end-year" class="yearfield" type="text" name="end-year"
                                                      maxlength="4"
                                                      value="<?php if (!empty($this->row['end-year']) && $this->row['end-year'] != '0000') echo $this->row['end-year']; else echo date('Y'); ?>" <?php echo $this->viewonly; ?>>

                        <?php if (!$this->viewonly) : ?>
                            <script type="text/javascript">
                                YAHOO.util.Event.onDOMReady(function () {
                                    makeAdditionalCalendar("enddate", "end-day", "end-month", "end-year", dateCalc);
                                });
                            </script>
                        <?php endif; ?>
                    </div><br/>
                <?php } ?>

                <!-- TA:17: 09/03/2014 START-->
                <?php if ($this->setting['display_training_length']) { ?>
                    <div class="fieldLabel" id="training_length_value_lbl"><?php echo t('Training length'); ?></div>
                    <div class="fieldInput">
                        <input type="text" id="training_length_value" name="training_length_value" size="6"
                               value="<?php echo $this->row['training_length_value']; ?>" <?php echo $this->viewonly; ?>>
                        &nbsp;
                        <input type="radio" name="training_length_interval" value="hour"
                               id="interval1" <?php if ($this->row['training_length_interval'] == 'hour') echo 'checked'; ?> <?php echo $this->viewonly; ?>>
                        <label for="interval1"><?php tp('hours'); ?></label>
                        &nbsp;
                        <input type="radio" name="training_length_interval" value="day"
                               id="interval2" <?php if ($this->row['training_length_interval'] == 'day') echo 'checked'; ?> <?php echo $this->viewonly; ?>>
                        <label for="interval2"><?php tp('days'); ?></label>
                        &nbsp;
                        <input type="radio" name="training_length_interval" value="week"
                               id="interval3" <?php if ($this->row['training_length_interval'] == 'week') echo 'checked'; ?> <?php echo $this->viewonly; ?>>
                        <label for="interval3"><?php tp('weeks'); ?></label>
                        <span id="training_length_interval_lbl"></span>
                    </div><br/>
                <?php } ?>

                <div class="fieldLabel"
                     id="training_organizer_option_id_lbl"><?php echo $this->translation['Training Organizer']; ?></div>
                <div class="fieldInput">
                    <?php echo $this->dropDownOrg; ?>
                    <?php echo hasACLEdit('acl_editor_training_organizer', 'admin/training-organizer', $this); ?>
                </div>
                <br/>

                <!-- TA:17:14: -->
                <?php if ($this->setting['display_training_location']) { ?>
                    <div class="fieldLabel"><?php echo t('Training location'); ?></div>
                    <div class="fieldInput">
                        <?php
                        training_location_dropdown($this->tlocations, $this->row['training_location_id'], 'name="training_location_id" id="select_training_location" ' . $this->viewonly); 
                        if ($this->hasACL ( 'edit_training_location' )){//TA:114
                            echo $this->insertLocationLink;
                        }
                        ?>
                    </div><br/>
                <?php } ?>

                <!-- TA:17: 09/03/2014 -->
                <?php if ($this->setting['display_training_level']) { ?>
                    <div class="fieldLabel"
                         id="training_level_option_id_lbl"><?php echo $this->translation['Training Level']; ?></div>
                    <div class="fieldInput">
                        <?php echo $this->dropDownLevel; ?>
                        <?php

                        #if(!@$this->setting['desktop_disable_insert_level']) {    // desktop_disable_ prefix is only in tanzania databases, but anyone can add this option to their _system
                        echo hasACLEdit('acl_editor_training_level', 'admin/training-level', $this);
                        # }
                        ?>
                    </div><br/>
                <?php } ?>

                <?php if ($this->mode == 'add' && $this->setting['module_unknown_participants_enabled']) : ?>
                    <div class="fieldLabel"
                         id="training_has_known_participants"><?php tp('Participants are known'); ?></div>
                    <div class="fieldInput">
                        <input type="checkbox" name="has_known_participants" value="1" id="has_known_participants"
                               checked/>
                    </div>
                <?php endif; ?>


                <?php
                /*** ADD TRAINING ends here ***************************************************************************/
                if ($this->mode == 'add') : ?>
                <div class="clear"></div>
                <?php if ($this->hasACL('import_training')) : ?>
                    <!-- import training button -->
                    <span id="importTraining" class="yui-button yui-push-button" style="float:left;">
      <span class="first-child">
        <button onclick="location.href='<?php echo $this->base_url; ?>/training/import';return false;" type="button"
                tabindex=1 id="trainingImportBtn"
                class="yui-button yui-push-button"><?php tp('Import trainings from Excel'); ?></button>
      </span>
    </span>
                <?php endif; ?>
                <button type="button" id="submitTraining"><?php tp('Save and Continue'); ?></button>
                <br>

                <script>
                    addAjaxSubmit('submitTraining', 'trainingForm', '<?php echo $this->base_url;?>/training/add/outputType/json');
                </script>
            </form>
        </div>

    </div>
    <div id="footer"><?php require_once('views/scripts/footer.phtml'); ?></div>
</body>
</html>

<?php return;
endif; ?>
<?php if ($this->setting['display_training_pepfar']) : ?>
    <div class="fieldLabel"
         id="training_pepfar_categories_option_lbl"><?php echo $this->translation['PEPFAR Category']; ?></div>
    <div class="fieldInput">
        <div style="margin-left: 250px;">
            <?php for ($j = 0; $j < $this->NUM_PEPFAR; $j++) { ?>

                <?php echo $this->dropDownPepfars[$j]; ?>

                <?php if ($this->NUM_PEPFAR != 1) : ?>
                    <input name="pepfar_days[]" type="text" size="3"
                           value="<?php if (isset($this->pepfarDurations[$j]) && $this->pepfarDurations[$j]) echo $this->pepfarDurations[$j] . ''; ?>" <?php echo $this->viewonly; ?>> <?php tp('days'); ?>
                <?php endif; ?>

                <?php if ($j != $this->NUM_PEPFAR - 1) echo '<br/><br/>'; ?>

            <?php } ?>

        </div>
    </div><br/>
<?php endif; ?>
<?php if ($this->setting['display_training_method']) { ?>
    <div class="fieldLabel"
         id="training_method_option_id_lbl"><?php echo $this->translation['Training Method']; ?></div>
    <div class="fieldInput">
        <?php echo $this->dropDownMethod; ?>
        <?php echo hasACLEdit('acl_editor_method', 'admin/training-method', $this); ?>
    </div>
<?php } ?>

<?php if ($this->setting['display_training_topic']) : ?>
    <div class="fieldLabel"
         id="training_topic_option_id_lbl"><?php echo(@$this->translation['Training Topic']); ?></div>
    <div class="fieldInput" id="topicContainer">
        <?php if(isset($this->dropDownTopic)) : ?>
      <?php echo $this->dropDownTopic; ?>
    <?php elseif($this->topicArray) : ?>
      <div style="line-height:1.5em;margin-bottom:0.5em;">
       <?php if(!$this->viewonly) : ?>
          <?php tp('Check all that apply below');?>
          <?php echo $this->insertTopicLink; ?>
          <?php echo hasACLEdit('acl_editor_training_topic', 'admin/training-topic', $this); ?>
        <?php endif; ?>
      </div>
      <?php
        // table used to align checkboxes w/labels
        $topicChunked = array_chunk($this->topicArray, count($this->topicArray) / 2);

        foreach($topicChunked as $i => $topicRay) {
          if ( $i%2 == 0) echo '<div class="fieldLabel" >&nbsp;</div>';
          echo '<div class="float50" style="width: 33%;"><table width="100%" class="tableChoices">';
          foreach($topicRay as $item) {
            $isChecked = (isset($item['training_id']) && $item['training_id']) ? ' checked' : '';
            echo '<tr><td valign="top" width="30px;">';
            echo '<input type="checkbox" name="topic_id[]" value="'.$item['id'].'" id="topic_id_'.$item['id'].'"'.$isChecked.' '.$this->viewonly.'> ';
            echo '</td><td valign="top">';
            echo '<label for="topic_id_'.$item['id'].'">'.$item['training_topic_phrase'].'</label>';
            echo '</td></tr>';
          }
          echo '</table></div>';
        }

      ?>
      </tr>
      </table>
    <?php endif; ?>
    </div><br/><br clear="all"/>
<?php endif; ?>

<?php if ($this->setting['display_training_trainers']) : ?>
    <div class="fieldLabel"><?php echo $this->translation['Training of Trainers']; ?></div>
    <div class="fieldInput" id="totContainer">
        <input type="checkbox" name="is_tot" value="1" id="is_tot" <?php if ($this->row['is_tot']) print 'checked'; ?>/><label
            for="is_tot"></label>
    </div><br/>
<?php endif; ?>

<?php if ($this->setting['display_training_refresher']) : ?>
    <div class="fieldLabel"><?php echo $this->translation['Refresher Course']; ?></div>
    <div class="fieldInput" id="refresherContainer">
        <?php

        if (@$this->setting['multi_opt_refresher_course']) {
            echo '<div style="line-height:1.5em;margin-bottom:0.5em;">';
            if (!$this->viewonly) {
                tp('Check all that apply below');
                echo $this->refresherInsertLink;
                echo hasACLEdit('acl_editor_refresher_course', 'admin/training-refreshercourse', $this);
            }
            echo '</div>';
            if ($this->refresherArray) {
                // table used to align checkboxes w/labels
                $chunked = array_chunk($this->refresherArray, count($this->refresherArray) / 2);

                foreach ($chunked as $i => $topicRay) {
                    if ($i % 2 == 0) echo '<div class="fieldLabel" >&nbsp;</div>';
                    echo '<div id="refresherTableContainer" class="float50" style="width: 33%;"><table width="100%" class="tableChoices">';
                    foreach ($topicRay as $item) {
                        $isChecked = (isset($item['training_id']) && $item['training_id']) ? ' checked' : '';
                        echo '<tr><td valign="top" width="30px;">';
                        echo '<input type="checkbox" name="training_refresher_option_id[]" value="' . $item['id'] . '" id="training_refresher_option_id_' . $item['id'] . '"' . $isChecked . ' ' . $this->viewonly . '> ';
                        echo '</td><td valign="top">';
                        echo '<label for="refresher_id_' . $item['id'] . '">' . $item['refresher_phrase_option'] . '</label>';
                        echo '</td></tr>';
                    }
                    echo '</table></div>';
                }
                echo '</tr>';
                echo '</table>';
            }

        } else {
            echo '  <input type="checkbox" name="is_refresher" value="1" id="is_refresher" ';
            if ($this->row['is_refresher']) {
                echo 'checked';
            }
            echo '><label for="is_refresher"></label>';
        }
        ?>
    </div><br/><br clear="all"/>

<?php endif; ?>

<script type="text/javascript">
    function updateTrainingCheck(parent_check, funding_amount) {
        if (YAHOO.util.Dom.get(funding_amount).value) {
            YAHOO.util.Dom.get(parent_check).checked = "checked";
        }
    }
</script>

<?php if ($this->setting['display_funding_options']) : ?>

    <div class="fieldLabel"><?php tp('Funding'); ?></div>
    <div class="fieldInput" id="fundingContainer">
        <div style="line-height:1.5em;margin-bottom:0.5em;">
            <?php if (!$this->viewonly) : ?>
                <?php tp('Check all that apply below'); ?>
                <?php echo $this->fundingInsertLink; ?>
                <?php echo hasACLEdit('acl_editor_funding', 'admin/training-funding', $this); ?>
            <?php endif; ?>
        </div>
        <?php
        // table used to align checkboxes w/labels
        $fundingChunked = array($this->fundingArray);
        foreach ($fundingChunked as $fundingRay) {
            echo '<div class="fieldLabel">&nbsp;</div><div class="float50"><table class="tableChoices">';
            foreach ($fundingRay as $item) {
                $isChecked = ((isset($item['training_id']) && $item['training_id']) || ($this->is_new && $item['is_default'])) ? ' checked' : '';
                echo '<tr><td valign="top">';
                echo '<input type="checkbox" name="funding_id[]" value="' . $item['id'] . '" id="funding_id_' . $item['id'] . '"' . $isChecked . ' ' . $this->viewonly . '> ';
                echo '</td><td valign="top">';
                echo '<label for="funding_id_' . $item['id'] . '">' . $item['funding_phrase'] . '</label>';
                echo '</td>';
                if ($this->setting['display_funding_amounts']) {
                    echo '<td valign="top" nowrap="nowrap">';
                    echo '&nbsp;&nbsp;$&nbsp;<input type="text" onkeyup="updateTrainingCheck(\'funding_id_' . $item['id'] . '\', \'funding_id_amount_' . $item['id'] . '\')" size="6" name="funding_id_amount_' . $item['id'] . '" value="' . (@$item['funding_amount']) . '" id="funding_id_amount_' . $item['id'] . '" ' . $this->viewonly . ' />';
                    echo '</td>';
                }
                echo '</tr>';
            }
            echo '</table></div>';
        }

        ?>

    </div><br/><br clear="both"/>

<?php endif; ?>

<?php if ($this->setting['display_training_got_curric']) : ?>
    <div class="fieldLabel"
         id="training_got_cirriculum_option_id_lbl"><?php echo $this->translation['GOT Curriculum']; ?></div>
    <div class="fieldInput">
        <?php echo $this->dropDownGotCir; ?>
        <?php echo hasACLEdit('acl_editor_funding', 'admin/training-funding', $this); ?>
    </div><br/>
<?php endif; ?>

<?php if ($this->setting['display_training_got_comment']) : ?>
    <div class="fieldLabel"><?php echo(@$this->translation['GOT Comment']); ?></div>
    <div class="fieldInput">
        <textarea name="got_comments"><?php echo $this->row['got_comments']; ?></textarea>
    </div><br/>
<?php endif; ?>


<?php if ($this->setting['display_training_comments']) { ?>
    <div class="fieldLabel"><?php echo(@$this->translation['Training Comments']); ?></div>
    <div class="fieldInput">
        <textarea name="comments"><?php echo $this->row['comments']; ?></textarea>
    </div><br/>
<?php } ?>

<?php if ($this->setting['display_course_objectives']) : ?>
    <div class="fieldLabel"><?php echo $this->translation['Course Objectives']; ?></div>
    <div class="fieldInput">
        <textarea name="objectives"><?php echo $this->row['objectives']; ?></textarea>
    </div><br/>
<?php endif; ?>

<?php if ($this->setting['display_primary_language']) { ?>
    <div class="fieldLabel"
         id="training_primary_language_option_id_lbl"><?php echo $this->translation['Primary Language']; ?></div>
    <div class="fieldInput">
        <?php echo $this->dropDownPrimaryLanguage; ?>
    </div>
<?php } ?>
<?php if ($this->setting['display_secondary_language']) { ?>
    <div class="fieldLabel"
         id="training_secondary_language_option_id_lbl"><?php echo $this->translation['Secondary Language']; ?></div>
    <div class="fieldInput">
        <?php echo $this->dropDownSecondaryLanguage; ?>
    </div>
<?php } ?>

<?php if (!$this->viewonly && !$this->isIncomplete) : ?>
    <div class="actionBtn">
        <div class="clear yui-push-button">
            <button type="button" onclick="submitForm();"><?php echo t('Save') . ' ' . t('Training'); ?></button>
            <br>
        </div>
    </div>
<?php endif; ?>




<?php /************ TRAINERS ******************************************************************************/
if ($this->row['has_known_participants']) :
?>


    <!-- TA:17: 09/03/2014 -->
<?php if ($this->setting['display_facilitator_info']) { ?>

    <div class="clear"></div>
    <div class="hrGrey"></div>
    <div class="clear"></div>

    <div class="fieldIndentNoMargin"><span class="required">*</span><?php echo t('Trainer Information'); ?> <span
            class="total"><?php echo t('Total Trainers') . ':'; ?> <span id="trainer_total">0</span></span></div>
    <div class="fieldIndent2">

        <div id="trainerTable"></div>
        <?php echo $this->tableTrainers; ?>

        <?php if (!$this->viewonly) : ?>
            <br>
            <div>
                <script>
                    function lastNameOnBlur(objRef) {
                        if (objRef.value == '')
                            objRef.value = "<?php echo $this->translation['Last Name'];?>";
                    }
                    function lastNameOnFocus(objRef) {
                        if (objRef.value == "<?php echo $this->translation['Last Name'];?>")
                            objRef.value = '';
                    }
                    function firstNameOnBlur(objRef) {
                        if (objRef.value == '')
                            objRef.value = "<?php echo $this->translation['First Name'];?>";
                    }
                    function firstNameOnFocus(objRef) {
                        if (objRef.value == "<?php echo $this->translation['First Name'];?>")
                            objRef.value = '';
                    }
                    function middleNameOnBlur(objRef) {
                        if (objRef.value == '')
                            objRef.value = "<?php echo $this->translation['Middle Name'];?>";
                    }
                    function middleNameOnFocus(objRef) {
                        if (objRef.value == "<?php echo $this->translation['Middle Name'];?>")
                            objRef.value = '';
                    }
                </script>
                <input type="text" id="trainer_first_name" size="15"
                       value="<?php echo $this->translation['First Name']; ?>" onfocus="firstNameOnFocus(this)"
                       onblur="firstNameOnBlur(this)">
                <?php if ($this->setting['display_middle_name'] && !$this->setting['display_middle_name_last']) { ?>
                    <input type="text" id="trainer_middle_name" size="15"
                           value="<?php echo $this->translation['Middle Name']; ?>" onfocus="middleNameOnFocus(this)"
                           onblur="middleNameOnBlur(this)">
                <?php } ?>
                <input type="text" id="trainer_last_name" size="15"
                       value="<?php echo $this->translation['Last Name']; ?>" onfocus="lastNameOnFocus(this)"
                       onblur="lastNameOnBlur(this)">
                <?php if ($this->setting['display_middle_name'] && $this->setting['display_middle_name_last']) { ?>
                    <input type="text" id="trainer_middle_name" size="15"
                           value="<?php echo $this->translation['Middle Name']; ?>" onfocus="middleNameOnFocus(this)"
                           onblur="middleNameOnBlur(this)">
                <?php } ?>
                <!-- TA:113 add birthday, facility, distyrict fields as well -->
                <input type="text" id="trainer_birthdate" size="9" disabled="true" value="<?php tp('Birthdate'); ?>" alt="Birthdate">
<input type="text" id="trainer_facility" size="15" disabled="true" value="<?php tp('Facility'); ?>" alt="Facility">
<?php
if ($this->setting ['display_region_c']) {
    $location_title = $this->translation['Region C (Local Region)'];
    $location_idx = 10;
} else if ($this->setting ['display_region_b']) {
    $location_title = $this->translation['Region B (Health District)'];
    $location_idx = 9;
} else {
    $location_title = $this->translation['Region A (Province)'];
    $location_idx = 8;
}
?>
<input type="text" id="trainer_health" size="15" disabled="true" value="<?php echo $location_title; ?>" alt="Location">
                <input type="hidden" id="trainer_days" value="0">
                <!--<input type="text" id="trainer_days" size="3" value="" >&nbsp;<?php tp('days'); ?>-->
                &nbsp;&nbsp;&nbsp;
                <input type="hidden" id="trainer_id" value="0">
                <input type="hidden" id="is_trainer" value="0">
                <input type="button" value="<?php tp('Insert'); ?>" class="insert"
                       onclick="addTrainer(this);return false;">
                &nbsp;&nbsp;&nbsp;
                <a href="javascript:submitThenRedirect('<?php echo $this->base_url; ?>/person/add/trainingredirect/<?php echo $this->row['id']; ?>/maketrainer/1');"><?php tp('New Person Form'); ?></a>
            </div>

            <div style="z-index:9001;">
                <div id="trainerContainerFirst" class="autocomplete" style="z-index:9001;"></div>
                <?php if ($this->setting['display_middle_name'] && !$this->setting['display_middle_name_last']) { ?>
                    <div id="trainerContainerMiddle" class="autocomplete" style="margin-left:135px;z-index:9001;"></div>
                <?php } ?>
                <div id="trainerContainer" class="autocomplete" style="margin-left:135px;z-index:9001;"></div>
                <?php if ($this->setting['display_middle_name'] && $this->setting['display_middle_name_last']) { ?>
                    <div id="trainerContainerMiddle" class="autocomplete" style="margin-left:135px;z-index:9001;"></div>
                <?php } ?>
            </div>

            <script type="text/javascript">
                YAHOO.util.Event.onDOMReady(function () {
                    // last name
                    var autoComp = makeAutocomplete('trainer_last_name', 'trainerContainer', '<?php echo $this->base_url;?>/training/trainer-last-list/outputType/text/');
                    formatNameAutocomplete(autoComp);
                    YAHOO.util.Dom.get('trainerContainer').style.position = "absolute"; // fix position
                    YAHOO.util.Dom.get('trainerContainer').style.top = '0px';

                    // first name
                    var autoCompFirst = makeAutocomplete('trainer_first_name', 'trainerContainerFirst', '<?php echo $this->base_url;?>/training/trainer-first-list/outputType/text/');
                    formatNameAutocomplete(autoCompFirst);
                    YAHOO.util.Dom.get('trainerContainerFirst').style.position = "absolute";
                    YAHOO.util.Dom.get('trainerContainerFirst').style.top = '0px';

                    // middle name
                    <?php if ( $this->setting['display_middle_name'] ) {?>
                    var autoCompMiddle = makeAutocomplete('trainer_middle_name', 'trainerContainerMiddle', '<?php echo $this->base_url;?>/training/trainer-middle-list/outputType/text/');
                    formatNameAutocomplete(autoCompMiddle);
                    YAHOO.util.Dom.get('trainerContainerMiddle').style.position = "absolute";
                    YAHOO.util.Dom.get('trainerContainerMiddle').style.top = '0px';
                    <?php } ?>

                    var oTrainerFirst = YAHOO.util.Dom.get('trainer_first_name');
                    var oTrainerLast = YAHOO.util.Dom.get('trainer_last_name');
                    var oTrainerMiddle = YAHOO.util.Dom.get('trainer_middle_name');
                    var oTrainerId = YAHOO.util.Dom.get('trainer_id');
                    var oIsTrainer = YAHOO.util.Dom.get('is_trainer');
                    var oTrainerBday = YAHOO.util.Dom.get('trainer_birthdate');
                    var oTrainerFacility = YAHOO.util.Dom.get('trainer_facility');
                    var OTrainerHealth = YAHOO.util.Dom.get('trainer_health');

                    // array can contain object references, element ids, or both
                    function suggestTrainerName(oSelf, elItem, oData) {
             
                        //TA:113
                        oTrainerId.value = elItem[2][4];
                        oIsTrainer.value = elItem[2][8];
                        oTrainerBday.value = elItem[2][7];
                         oTrainerFacility.value = elItem[2][5];
                         OTrainerHealth.value = elItem[2][<?php echo $location_idx;?>];

                        //TA:113
//                         var midNameIdx = 2;
//                         var lastNameIdx = 3;
                        var midNameIdx = 1;
                        var lastNameIdx = 2;
                        <?php if ( $this->setting['display_middle_name'] ) { ?>
                        midNameIdx =    <?php echo ( $this->setting['display_middle_name_last'] ? 3:2);?>;
                        lastNameIdx =    <?php echo ( $this->setting['display_middle_name_last'] ? 2:3);?>;
                        <?php }?>
                        if (elItem[0]._elTextbox == oTrainerLast) {
                            oTrainerFirst.value = elItem[2][1];
                            <?php if ( $this->setting['display_middle_name'] ) {?>
                            oTrainerMiddle.value = elItem[2][midNameIdx];
                            <?php }?>
                            oTrainerLast.value = elItem[2][lastNameIdx];
                        } else if (elItem[0]._elTextbox == oTrainerFirst) {
                            oTrainerFirst.value = elItem[2][1];
                            <?php if ( $this->setting['display_middle_name'] ) {?>
                            oTrainerMiddle.value = elItem[2][midNameIdx];
                            <?php }?>
                            oTrainerLast.value = elItem[2][lastNameIdx];
                        } else if (elItem[0]._elTextbox == oTrainerMiddle) {
                            oTrainerFirst.value = elItem[2][1];
                            <?php if ( $this->setting['display_middle_name'] ) {?>
                            oTrainerMiddle.value = elItem[2][midNameIdx];
                            <?php } ?>
                            oTrainerLast.value = elItem[2][lastNameIdx];
                        }

                        //YAHOO.util.Dom.get('trainer_days').focus();
                    };

                    autoComp.itemSelectEvent.subscribe(suggestTrainerName);
                    autoCompFirst.itemSelectEvent.subscribe(suggestTrainerName);
                    <?php if ( $this->setting['display_middle_name'] ) {?>
                    autoCompMiddle.itemSelectEvent.subscribe(suggestTrainerName);
                    <?php } ?>
                });
                // fired on "insert" button click
                function addTrainer(oButton) {

                    var oTrainerFirst = YAHOO.util.Dom.get('trainer_first_name');
                    var oTrainerLast = YAHOO.util.Dom.get('trainer_last_name');
                    var oTrainerMiddle = YAHOO.util.Dom.get('trainer_middle_name');
                    var oTrainerDays = YAHOO.util.Dom.get('trainer_days');
                    var oTrainerId = YAHOO.util.Dom.get('trainer_id');
                    var oIsTrainer = YAHOO.util.Dom.get('is_trainer');
                    var oTrainerBday = YAHOO.util.Dom.get('trainer_birthdate');
                    var oTrainerFacility = YAHOO.util.Dom.get('trainer_facility');
                    var OTrainerHealth = YAHOO.util.Dom.get('trainer_health');

                    if (oTrainerId.value == 0) {
                        alert("<?php echo t('The entered trainer name could not be found.') . '\n' . t('Please select one from the list or add a new person.');?>");
                        return;
                    }

                    //  if(oTrainerDays.value == "Days" || !oTrainerDays.value) {
                    //      alert('<?php echo t('Please enter the number of days for this').' '.t('trainer').'.';?>');
                    //   return;
                    //    }
                    <?php if (@$this->setting['require_trainer_skill']) : ?>
                    if (oIsTrainer.value == 0) {
                        if (confirm("<?php echo t('You must edit this person\'s').' '.t('trainer').' '.t('profile before adding them to this session.\n\nWould you like to do this now?');?>")) {
                            submitThenRedirect('<?php echo $this->base_url;?>/person/edit/id/' + oTrainerId.value + '/trainingredirect/<?php echo $this->row['id']; ?>/maketrainer/1/days/1' + '#training');
                        }
                        return;
                    }
                    <?php endif; ?>

                    //oButton.disabled = true;

                    var jsonAdd = {}
                    jsonAdd.id = oTrainerId.value;
                    jsonAdd.trainer_id = oTrainerId.value;
                    jsonAdd.first_name = oTrainerFirst.value;
                    <?php if ( $this->setting['display_middle_name'] ) {?>
                    jsonAdd.middle_name = oTrainerMiddle.value;
                    <?php } ?>
                    jsonAdd.last_name = oTrainerLast.value;
                    jsonAdd.duration_days = oTrainerDays.value;
                    //TA:113
                    jsonAdd.birthdate = oTrainerBday.value;
                    jsonAdd.facility_name = oTrainerFacility.value;
                    jsonAdd.district_name = OTrainerHealth.value;

                    var successCallback = function () {
                        oTrainerId.value = "0";
                        oTrainerFirst.value = "";
                        oTrainerFirst.focus();
                        oTrainerFirst.blur();
                        <?php if ($this->setting['display_middle_name'] ) { ?>
                        oTrainerMiddle.value = "";
                        oTrainerMiddle.focus();
                        oTrainerMiddle.blur();
                        <?php } ?>
                        oTrainerLast.value = "";
                        oTrainerLast.focus();
                        oTrainerLast.blur();
                        oTrainerDays.value = "";
                        oTrainerDays.focus();
                        oTrainerDays.blur();
                        //oButton.disabled = false;
                        //TA:113
                        oTrainerBday.value = oTrainerBday.alt;
                        oTrainerFacility.value = oTrainerFacility.alt;
                        OTrainerHealth.value = OTrainerHealth.alt;

         

                    }

                    ITECH.trainerTable.addRow(jsonAdd, successCallback);

                }


            </script>

        <?php endif; ?>

    </div>

<?php } ?>


<?php /************ PARTICIPANTS TA:113 ******************************************************************************/ ?>

    <div class="clear"></div>
    <div class="hrGrey"></div>
    <div class="clear"></div>
    <div class="fieldIndentNoMargin"><span class="required">*</span><?php tp('Participant Information'); ?> <span
            class="total"><?php tp('Total Participants:'); ?> <span id="persons_total">0</span></span></div>
<div class="fieldIndent2">
    <div id="personsTable"></div>
    <?php echo $this->tablePersons; ?>

    <?php if (!$this->viewonly) : ?>
<br/>
<input type="text" id="person_first_name" size="15" placeholder="<?php echo $this->translation['First Name']; ?>"
       onfocus="firstNameOnFocus(this)" onblur="firstNameOnBlur(this)">
<?php if ($this->setting['display_middle_name'] && !$this->setting['display_middle_name_last']) { ?>
<input type="text" id="person_middle_name" size="15" placeholder="<?php echo $this->translation['Middle Name']; ?>"
       onfocus="middleNameOnFocus(this)" onblur="middleNameOnBlur(this)">
<?php } ?>
<input type="text" id="person_last_name" size="15" placeholder="<?php echo $this->translation['Last Name']; ?>"
       onfocus="lastNameOnFocus(this)" onblur="lastNameOnBlur(this)">
<?php if ($this->setting['display_middle_name'] && $this->setting['display_middle_name_last']) { ?>
<input type="text" id="person_middle_name" size="15" value="<?php echo $this->translation['Middle Name']; ?>"
       onfocus="middleNameOnFocus(this)" onblur="middleNameOnBlur(this)">
<?php } ?>
<input type="text" id="person_birthdate" size="9" disabled="true" value="<?php tp('Birthdate'); ?>" alt="Birthdate">
<input type="text" id="person_facility" size="15" disabled="true" value="<?php tp('Facility'); ?>" alt="Facility">
<?php
if ($this->setting ['display_region_c']) {
    $location_title = $this->translation['Region C (Local Region)'];
    $location_idx = 10;
} else if ($this->setting ['display_region_b']) {
    $location_title = $this->translation['Region B (Health District)'];
    $location_idx = 9;
} else {
    $location_title = $this->translation['Region A (Province)'];
    $location_idx = 8;
}
?>
<input type="text" id="person_health" size="15" disabled="true" value="<?php echo $location_title; ?>" alt="Location">
<input type="hidden" id="person_id" value="0"/>

    <div>
        <div id="personContainerFirst" class="autoComplete" style="z-index: 9001;"></div>
        <?php if ($this->setting['display_middle_name'] && !$this->setting['display_middle_name_last']) { ?>
            <div id="personContainerMiddle" class="autoComplete" style="margin-left:135px;z-index: 9001;"></div>
        <?php } ?>
        <div id="personContainer" class="autoComplete" style="margin-left:135px;z-index: 9001;"></div>
        <?php if ($this->setting['display_middle_name'] && $this->setting['display_middle_name_last']) { ?>
            <div id="personContainerMiddle" class="autoComplete" style="margin-left:135px;z-index: 9001;"></div>
        <?php } ?>


        <div class="actionBtn" style="float:right; margin-top: -18px;">
            <input type="button" name="Insert" value="<?php tp("Insert"); ?>" class="insert" id="personInsertButton"
                   onclick="addPerson(this);return false;">
            &nbsp;&nbsp;&nbsp;
            <a href="javascript:submitThenRedirect('<?php echo $this->base_url; ?>/person/add/trainingredirect/<?php echo $this->row['id']; ?>');"><?php tp('New Person Form'); ?></a>
        </div>


        <script type="text/javascript">
            YAHOO.util.Event.onDOMReady(function () {
                // last name
                var autoCompPerson = makeAutocomplete('person_last_name', 'personContainer', '<?php echo $this->base_url;?>/training/person-last-list/outputType/text/');
                formatNameAutocomplete(autoCompPerson);
                YAHOO.util.Dom.get('personContainer').style.position = "absolute"; // fix position
                YAHOO.util.Dom.get('personContainer').style.top = '0px';

                // first name
                var autoCompPersonFirst = makeAutocomplete('person_first_name', 'personContainerFirst', '<?php echo $this->base_url;?>/training/person-first-list/outputType/text/');
                formatNameAutocomplete(autoCompPersonFirst);
                YAHOO.util.Dom.get('personContainerFirst').style.position = "absolute"; // fix position
                YAHOO.util.Dom.get('personContainerFirst').style.top = '0px';

                // middle name
                <?php if ( $this->setting['display_middle_name'] ) { ?>
                var autoCompPersonMiddle = makeAutocomplete('person_middle_name', 'personContainerMiddle', '<?php echo $this->base_url;?>/training/person-middle-list/outputType/text/');
                formatNameAutocomplete(autoCompPersonMiddle);
                YAHOO.util.Dom.get('personContainerMiddle').style.position = "absolute"; // fix position
                YAHOO.util.Dom.get('personContainerMiddle').style.top = '0px';
                <?php } ?>

                var oPFirst = YAHOO.util.Dom.get('person_first_name');
                var oPLast = YAHOO.util.Dom.get('person_last_name');
                var oPMiddle = YAHOO.util.Dom.get('person_middle_name');
                var oPBday = YAHOO.util.Dom.get('person_birthdate');
                var oPFacility = YAHOO.util.Dom.get('person_facility');
                var OPHealth = YAHOO.util.Dom.get('person_health');
                var oPId = YAHOO.util.Dom.get('person_id');

                // array can contain object references, element ids, or both
                function suggestPersonName(oSelf, elItem, oData) {

                    oPBday.value = elItem[2][7];
                    oPFacility.value = elItem[2][5];
                    OPHealth.value = elItem[2][<?php echo $location_idx;?>];
                    oPId.value = elItem[2][4];

                    var midNameIdx =    <?php echo ( $this->setting['display_middle_name_last'] ? 3:2);?>;
                    var lastNameIdx =    <?php echo ( $this->setting['display_middle_name_last'] ? 2:3);?>;

                    if (elItem[0]._elTextbox == oPLast) {
                        oPFirst.value = elItem[2][1];
                        <?php if ( $this->setting['display_middle_name'] ) {?>
                        oPMiddle.value = elItem[2][midNameIdx];
                        <?php } ?>
                        oPLast.value = elItem[2][lastNameIdx];
                    } else if (elItem[0]._elTextbox == oPFirst) {
                        oPFirst.value = elItem[2][1];
                        <?php if ( $this->setting['display_middle_name'] ) {?>
                        oPMiddle.value = elItem[2][midNameIdx];
                        <?php }?>
                        oPLast.value = elItem[2][lastNameIdx];
                    } else if (elItem[0]._elTextbox == oPMiddle) {
                        oPFirst.value = elItem[2][1];
                        <?php if ( $this->setting['display_middle_name'] ) {?>
                        oPMiddle.value = elItem[2][midNameIdx];
                        <?php }?>
                        oPLast.value = elItem[2][lastNameIdx];
                    }

                    //addPerson(YAHOO.util.Dom.get('personInsertButton'));

                };

                autoCompPerson.itemSelectEvent.subscribe(suggestPersonName);
                autoCompPersonFirst.itemSelectEvent.subscribe(suggestPersonName);
                <?php if ( $this->setting['display_middle_name'] ) { ?>
                autoCompPersonMiddle.itemSelectEvent.subscribe(suggestPersonName);
                <?php } ?>

            });

            // fired on "insert" button click
            function addPerson(oButton) {
                var oPFirst = YAHOO.util.Dom.get('person_first_name');
                var oPLast = YAHOO.util.Dom.get('person_last_name');
                var oPMiddle = YAHOO.util.Dom.get('person_middle_name');
                var oPBday = YAHOO.util.Dom.get('person_birthdate');
                var oPFacility = YAHOO.util.Dom.get('person_facility');
                var OPHealth = YAHOO.util.Dom.get('person_health');
                var oPId = YAHOO.util.Dom.get('person_id');

                if (oPId.value == 0) {
                    alert("<?php echo t('The entered person could not be found.') . '\n'. t('Please select one from the list or add a new person.'); ?>");
                    return;
                }

                var jsonAdd = {}
                jsonAdd.id = oPId.value;
                jsonAdd.person_id = oPId.value;
                jsonAdd.last_name = oPLast.value;
                jsonAdd.first_name = oPFirst.value;
                <?php if ( $this->setting['display_middle_name'] ) {?>
                jsonAdd.middle_name = oPMiddle.value;
                <?php } ?>
                jsonAdd.birthdate = oPBday.value;
                jsonAdd.facility_name = oPFacility.value;
                jsonAdd.district_name = OPHealth.value;


                var successCallback = function () {
                    oPId.value = "0";
                    oPFirst.value = "";
                    oPFirst.focus();
                    oPFirst.blur();
                    oPLast.value = "";
                    oPLast.focus();
                    oPLast.blur();
                    <?php if ( $this->setting['display_middle_name'] ) { ?>
                    oPMiddle.value = "";
                    oPMiddle.focus();
                    oPMiddle.blur();
                    <?php } ?>
                    oPBday.value = oPBday.alt;
                    oPFacility.value = oPFacility.alt;
                    OPHealth.value = OPHealth.alt;
                }

                ITECH.personsTable.addRow(jsonAdd, successCallback);

            }


        </script>

        <?php endif; ?>

    </div>
    <!-- TA:17: 09/03/2014  -->
    <?php if (!$this->viewonly && $this->setting['display_training_score']) { ?>
        <div class="fieldLabel"><label><?php tp('Participant Test Scores'); ?></label></div>
        <div class="fieldInput"><a
                href="<?php echo $this->base_url; ?>/training/scores-import/training/<?php echo $this->row['id']; ?>"><?php tp('Import Scores'); ?></a>
        </div>
    <?php } ?>
    <?php if ($this->setting['display_training_pre_test'] || $this->setting['display_training_post_test']) : ?>
        <!-- test scores -->
        <div class="clear"></div>
        <div class="hrGrey"></div>
        <div class="clear"></div>
        <div class="fieldIndentNoMargin"><?php tp('Course Average Test Scores'); ?></div>
        <div class="fieldIndent2">

            <?php if ($this->setting['display_training_pre_test']) : ?>
                <?php echo $this->translation['Pre Test Score']; ?>
                <input type="text" size="8" name="pre"
                       value="<?php echo $this->row['pre']; ?>" <?php echo $this->viewonly; ?>>
                &nbsp;
            <?php endif; ?>
            <?php if ($this->setting['display_training_post_test']) : ?>
                <?php echo $this->translation['Post Test Score']; ?>
                <input type="text" size="8" name="post"
                       value="<?php echo $this->row['post']; ?>" <?php echo $this->viewonly; ?>>
            <?php endif; ?>

        </div>

    <?php endif; ?>
    
    <!-- TA:#271 -->
    <?php if ($this->setting['display_training_pt_pass']) : ?>
        <!-- test scores pass/fail -->
        <div class="clear"></div>
        <div class="hrGrey"></div>
        <div class="clear"></div>
        <div class="fieldIndentNoMargin"><?php tp('Post-Test Pass'); ?></div>
        <div class="fieldIndent2">
           <?php echo $this->pass;?>
        </div>
    <?php endif; ?>

    <?php endif; //$this->has_known_participants  ?>
    <?php if (!$this->row['has_known_participants']) : ?>
        <script type="text/javascript">

            <?php $num_qual_quantities = 1;
                foreach ($this->unknownQualDropDowns as $dd) {
                    if ( $dd['quantity_na'] ) $num_qual_quantities++;
             else if ( $dd['quantity_male'] ) $num_qual_quantities++;
                 else if ( $dd['quantity_female'] ) $num_qual_quantities++;
                }

            ?>
            var qual_cnt = <?php print $num_qual_quantities;?>;

            function showQualCallback() {
                var qualElement = YAHOO.util.Dom.get('training_qualification_item_' + qual_cnt);
                if (qualElement) {
                    qualElement.style.display = 'block';
                    qual_cnt++;
                }
                return false;
            }

            function calculate_quantity() {
                var num = 0;
                var qualElement;
                var elementNum;
                for (var n = 0; n < qual_cnt; n++) {
                    elementNum = num;
                    qualElement = YAHOO.util.Dom.get('qualification_quantity_na_' + n);
                    if (parseInt(qualElement.value) > 0) {
                        num = num + parseInt(qualElement.value);
                    }
                    qualElement = YAHOO.util.Dom.get('qualification_quantity_male_' + n);
                    if (parseInt(qualElement.value) > 0) {
                        num = num + parseInt(qualElement.value);
                    }
                    qualElement = YAHOO.util.Dom.get('qualification_quantity_female_' + n);
                    if (parseInt(qualElement.value) > 0) {
                        num = num + parseInt(qualElement.value);
                    }

                    qualType = YAHOO.util.Dom.get('select_person_qualification_option_' + n);
                    if ((elementNum != num) && (qualType.selectedIndex == 0)) {
                        alert('<?php tp('You need to choose a qualification for all recorded participants.');?>');
                    }
                }

               // var totalElement = YAHOO.util.Dom.get('total');
                var totalElement = YAHOO.util.Dom.get('persons_total');
                totalElement.innerHTML = num;

            }

            YAHOO.util.Event.onDOMReady(calculate_quantity);
        </script>

        <div class="fieldIndentNoMargin"><?php tp('Participant Qualifications'); ?></div>
    <?php
    $i = 0;
    foreach ($this->unknownQualDropDowns as $dd) { ?>
        <div class="fieldIndent2" style="display: <?php print (($i < $num_qual_quantities) ? 'block;' : 'none;') ?>;"
             id="training_qualification_item_<?php echo $i; ?>">
            <?php echo ($dd['select']) . '&nbsp;';
            echo t('Age Range') . ':<select name="age_range_option_id[]" id="age_range_option_id_' . $i . '" >';
            foreach ($this->age_options as $ao) {
                echo "<option value='{$ao['id']}' " . ($dd['age_range_option_id'] == $ao['id'] ? "selected='selected'" : "") . ">{$ao['age_range_phrase']}</option>";
            }
            echo '</select>&nbsp;';
            echo t('Male') . ':<input type="text" size="6" name="qualification_quantity_male[]" id="qualification_quantity_male_' . $i . '" onfocus="this.select();" onchange="calculate_quantity();" value="' . ($dd['quantity_male'] ? $dd['quantity_male'] : '') . '" />&nbsp;';
            echo t('Female') . ':<input type="text" size="6" name="qualification_quantity_female[]" id="qualification_quantity_female_' . $i . '" onfocus="this.select();" onchange="calculate_quantity();" value="' . ($dd['quantity_female'] ? $dd['quantity_female'] : '') . '" />&nbsp;';
            echo t('Unknown') . ':<input type="text" size="6" name="qualification_quantity_na[]" id="qualification_quantity_na_' . $i . '" onfocus="this.select();" onchange="calculate_quantity();" value="' . ($dd['quantity_na'] ? $dd['quantity_na'] : '') . '" />';
            echo '<br/>'; ?>
        </div>
        <?php
        $i++;
    } ?><br/>
        <div class="fieldIndent2"><a href="#" onclick="return showQualCallback();" id="add_qual">Add another
                qualification</a>&nbsp;&nbsp;
            <div style="display: inline;"><label>Total</label>&nbsp;<label id="total">0</label></div>
        </div>
    <?php endif; //$this->has_known_participants  ?>

    <?php if ($this->setting['display_training_custom1']) : ?>
        <!-- custom field 1 -->

        <div class="clear"></div>
        <div class="hrGrey"></div>
        <div class="clear"></div>

        <div class="fieldIndentNoMargin"><?php echo $this->translation['Training Custom 1']; ?></div>
        <div class="fieldIndent2">
            <input type="text" name="custom1_phrase" size="60" value="<?php echo $this->row['custom1_phrase']; ?>">
        </div>
    <?php endif; ?>

    <?php if ($this->setting['display_training_custom2']) : ?>
        <!-- custom field 2 -->

        <div class="clear"></div>
        <div class="hrGrey"></div>
        <div class="clear"></div>

        <div class="fieldIndentNoMargin"><?php echo $this->translation['Training Custom 2']; ?></div>
        <div class="fieldIndent2">
            <input type="text" name="custom2_phrase" size="60" value="<?php echo $this->row['custom2_phrase']; ?>">
        </div>
    <?php endif; ?>

    <?php if ($this->setting['display_training_custom3']) : ?>
        <!-- custom field 3 -->

        <div class="clear"></div>
        <div class="hrGrey"></div>
        <div class="clear"></div>

        <div class="fieldIndentNoMargin"><?php echo $this->translation['Training Custom 3']; ?></div>
        <div class="fieldIndent2">
            <input type="text" name="custom3_phrase" size="60" value="<?php echo $this->row['custom_3']; ?>">
        </div>
    <?php endif; ?>

    <?php if ($this->setting['display_training_custom4']) : ?>
        <!-- custom field 4 -->

        <div class="clear"></div>
        <div class="hrGrey"></div>
        <div class="clear"></div>

        <div class="fieldIndentNoMargin"><?php echo $this->translation['Training Custom 4']; ?></div>
        <div class="fieldIndent2">
            <input type="text" name="custom4_phrase" size="60" value="<?php echo $this->row['custom_4']; ?>">
        </div>
    <?php endif; ?>


    <?php if ($this->setting['module_approvals_enabled']) : ?>
        <div class="clear"></div>
        <div class="hrGrey"></div>
        <div class="clear"></div>
        <div class="fieldIndentNoMargin"><?php tp('Approval Status'); ?></div>
        <div class="fieldIndentNoMargin">
            <div class="fieldLabel"><?php tp('Approved'); ?></div>
            <input type="radio" name="approval_status" value="approved" <?php if ($this->approve_val) {
                echo 'checked';
            } ?> <?php echo $this->approve_disable_str; ?> />
        </div>
        <div class="fieldIndentNoMargin">
            <div class="fieldLabel"><?php tp('Rejected'); ?></div>
            <input type="radio" name="approval_status" value="rejected" <?php if (!$this->row['is_approved']) {
                echo 'checked';
            } ?> <?php echo $this->approve_disable_str; ?> />
        </div>
        <?php if (!$this->row['is_approved'] and (array_search('approve_trainings', $this->identity->acls) !== false)) { ?>
            <div class="clear"></div>
            <label><?php tp('Comments'); ?></label>
            <textarea name="approval_comments" cols="80"></textarea>
        <?php } ?>
    <?php endif; ?>


    <input type="hidden" name="redirectUrl" id="redirectUrl" value="">
    <input type="hidden" name="specialAction" id="specialAction" value="">

    <?php if (!$this->viewonly) : ?>
        <div class="actionBtn">
            <button type="button" id="submitTraining"><?php echo t('Save') . ' ' . t('Training'); ?></button>
            <br>
        </div>
    <?php endif; ?>

    </form></div> <!-- table ends -->

<div class="clear"></div>

<!-- TA:17: 09/09/2014 -->
<?php if ($this->hasACL('admin_files')) { ?>
    <div class="hrGrey"></div>
    <div class="clear"></div>
    <div class="fieldIndentNoMargin"><?php tp('Attached Documents'); ?></div>
    <div class="fieldIndent2">
        <?php echo $this->editTableFiles; ?>
        <span class="caption"><?php tp('Right-click and select "Save Target As..." to download.'); ?></span>
    </div>

    <?php if ($this->filesForm) : ?>
        <div class="fieldIndentNoMargin"><?php tp('Document Upload'); ?></div>
        <div class="fieldIndent2">
            <?php echo $this->filesForm; ?>
        </div>
        <script type="text/javascript">
            YAHOO.util.Event.on(window, 'load', initUploadButton);
        </script>
    <?php endif; ?>
<?php } ?>


</div>

<script type="text/javascript">
    <?php
    // onready - add ajax submit
        if(!$this->viewonly) {
            if ( $this->mode != 'add') {
                echo "addAjaxSubmit('submitTraining','trainingForm','".$this->base_url."/training/edit/id/".$this->row['id'].">/outputType/json');".PHP_EOL;
            } else {
                echo "addAjaxSubmit('submitTraining','trainingForm','".$this->base_url."/training/add/outputType/json/');".PHP_EOL;
            }
        }

    ?>

    documentHasChanged = false;

    function monitorChanges(e) {
        documentHasChanged = true;
    }

    $(document).ready(function () {
        $('#trainingForm select').click(monitorChanges);
        $('#trainingForm input').change(monitorChanges);
    });

    // submitThenRedirect()
    function submitThenRedirect(url) {
        var fld = document.getElementById('redirectUrl');
        fld.value = url;

        if (!documentHasChanged)
            return window.location = url;

        if (confirm("<?php tp('You are moving to a new page, do you wish to save the changes you\'ve made?');?>"))
            submitForm();
        else
            window.location = url;
    }

    function deleteTraining() {
        var personsTable = ITECH.personsTable;
        var trainerTable = ITECH.trainerTable;

        if (<?php echo ($this->row['has_known_participants'] ? '(trainerTable != undefined &&  (trainerTable.myDataTable.getRecordSet().getLength() != 0)) || (personsTable != undefined && (personsTable.myDataTable.getRecordSet().getLength() != 0))': ' (YAHOO.util.Dom.get("qualification_quantity_na_0").value > 0) || (YAHOO.util.Dom.get("qualification_quantity_female_0").value > 0) || (YAHOO.util.Dom.get("qualification_quantity_male_0").value > 0) ');  ?>) {
            alert('<?php echo t('All trainers and participants must be removed before deleting a training session.'); ?>');
        } else if (confirm("<?php tp("Are you sure you wish to delete this training session?"); ?>")) {
            YAHOO.util.Dom.get('specialAction').value = "delete";
            YAHOO.util.Dom.get('redirectUrl').value = "<?php echo $this->base_url;?>/training/deleted";
            submitForm();
        }
    }

    // duplicate training confirm
    function duplicateTraining() {
        if (confirm("<?php echo t('Duplicate this').' '.t('Training').'?'; ?>")) {
            YAHOO.util.Dom.get('specialAction').value = "duplicate";
            submitForm();
        }
    }

    // submit form via ajax
    function submitForm() {
        <?php if ( $this->mode != 'add') {
              echo 'var postUrl = "'. $this->base_url . '/training/edit/id/'.$this->row['id'].'/outputType/json"';
        } else {
              echo 'var postUrl = "' . $this->base_url . '/training/add/outputType/json"';
        } ?>

        var buttonId = 'submitTraining';
        var formId = 'trainingForm';
        (function () {
            //var _button = new YAHOO.widget.Button(buttonId);
            var handleSuccess = function (o) {
                try {
                    var response = o.responseText;

                    var responseObj = YAHOO.lang.JSON.parse(response);
                    displayStatus(responseObj.status);
                    var allGood = true;
                    if (responseObj.messages) {
                        for (var key in responseObj.messages) {
                            displayErrorMessage(key, responseObj.messages[key]);
                            allGood = false;
                        }
                    }
                    if (!allGood) {
                        setStatusBoxError();
                    }

                    if (responseObj.obj_id) {
                        var new_obj_field = YAHOO.util.Dom.get('obj_id');
                        if (new_obj_field) {
                            new_obj_field.value = responseObj.obj_id;
                        }
                    }

                    var redir = document.getElementById('redirectUrl');
                    if (redir.value != '' && allGood) {
                        window.location = redir.value;
                    } else if (responseObj.redirect) {
                        window.location = responseObj.redirect;
                    }
                }
                catch (x) {
                    alert("ITech script error: " + x);
                    alert(response);
                    return;
                }

                document.body.style.cursor = "auto";

            }
            var handleFailure = function (o) {
                alert("Submission failed with code: " + o.status + ". The error text is: " + o.statusText);
                document.body.style.cursor = "auto";
            }

            var callback = {
                success: handleSuccess,
                failure: handleFailure
            };

            window.setTimeout(function () {

                //document.body.style.cursor = "wait";

                //clear error text
                var els = YAHOO.util.Dom.getElementsByClassName('errorText');
                if (els.length)
                    YAHOO.util.Dom.setStyle(els, 'display', 'none');
                var formObject = document.getElementById(formId);
                YAHOO.util.Connect.setForm(formObject);
                var request = YAHOO.util.Connect.asyncRequest('POST', postUrl, callback);
            }, 200);

        })();
    }


</script>

</div>

<div id="footer"><?php require_once('views/scripts/footer.phtml'); ?></div>
</body>
</html>
