<?php

if ( isset($this->results) ) { require_once('evaluations-results.phtml'); }

require_once('views/helpers/Location.php');

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title><?php echo $this->translation['Application Name'];?> | <?php tp('Evaluation Reports');?></title>
<?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>
</head>
<body class="yui-skin-sam" >
<div id="pageHolder">
  <div id="header"><?php require_once('views/scripts/header.phtml');?></div>
  <div id="content">

    <h1><?php tp('T Evaluation Reports');?></h1>

    <form action="" method="get">

  <div class="fieldLabel" id="evaluation_id_lbl"><?php echo tp('Evaluation'); ?></div>
  <div class="fieldInput">
   <select name="evaluation_id[]" multiple="multiple">
    <option value="">&mdash;<?php tp('choose');?>&mdash;</option>
    <?php
      foreach ( $this->evaluations as $vals ) {
        echo '<option value="'.$vals['id'].'" '.((@$this->criteria['evaluation_id']) == $vals['id']? 'SELECTED="selected"':'').' >'.($vals['title']).'</option>';
    }
    ?>
  </select>
  </div>


  <div class="fieldLabel" id="evaluation_id_lbl"><?php echo t('Partcipant').space.t('or').space.t('Trainer'); ?></div>
  <div class="fieldInput">
    <select name="person_id" id="person_id">
      <option value="">&mdash;<?php tp('select'); ?>&mdash;</option>
      <?php
        $middleNameLast = $this->setting['display_middle_name_last'];
        foreach ($this->people as $i => $row) {
          $selected = $row['id'] == $criteria['person_id'] ? " selected" : "";
          $pName = $middleNameLast ? $row['middle'] . ', ' . $row['first_name'] . space . $row['last_name'] : $row['last_name'] . ', ' . $row['first_name'] . space . $row['middle_name'] ;
          if ($row['id'])
            echo "<option value=\"{$row['id']}\"$selected>$pName</option>";
        }
      ?>
    </select>
  </div>

  <div class="fieldLabel" id="evaluation_id_lbl"><?php echo @$this->translation['Training Name']; ?></div>
  <div class="fieldInput">
    <?php echo $this->titles; ?>
  </div>
<?php region_filters_dropdown($this, $this->locations, $this->criteria, true); ?>

  <div class="clear"></div>
<div class="fieldLabel"><?php tp('Start date');?></div>
<div class="fieldInput" id="startdate">
    <?php tp("Day");?> <input id="start-day" class="dayfield" type="text" name="start-day" maxlength="2" value="<?php echo $this->criteria['start-day']; ?>"  >
    / <?php tp("Month");?> <input id="start-month" class="monthfield" type="text" name="start-month" maxlength="2" value="<?php echo $this->criteria['start-month']; ?>"  >
    / <?php tp("Year");?> <input id="start-year" class="yearfield" type="text" name="start-year" maxlength="4" value="<?php echo $this->criteria['start-year'];  ?>" >
    <script  type="text/javascript">
        YAHOO.util.Event.onDOMReady(function () {
          makeCalendar("startdate","start-day", "start-month", "start-year");
        });
    </script>
  </div>
<div class="fieldLabel" style="padding-top:1em;"><?php tp('End date');?></div>
<div class="fieldInput" id="enddate" style="margin-top:1em;">
    <?php tp("Day");?> <input id="end-day" class="dayfield" type="text" name="end-day" maxlength="2" value="<?php echo $this->criteria['end-day']; ?>"  >
    / <?php tp("Month");?> <input id="end-month" class="monthfield" type="text" name="end-month" maxlength="2" value="<?php echo $this->criteria['end-month']; ?>"  >
    / <?php tp("Year");?> <input id="end-year" class="yearfield" type="text" name="end-year" maxlength="4" value="<?php echo $this->criteria['end-year'];  ?>" >
    <script  type="text/javascript">
        YAHOO.util.Event.onDOMReady(function () {
          makeAdditionalCalendar("enddate","end-day", "end-month", "end-year");
        });
    </script>
  </div>

<div class="fieldLabel" style="padding-top:1em;"></div>
<div class="fieldInput" id="enddate" style="margin-top:1em;">
</div>


  <div class="clear"></div>
    <input type="submit" class="submitNoArrow" name="go" value="<?php tp("Generate Report");?>" />
   </form>

  <div class="clear"></div>
  </div>

  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
  </div></div>
</body>
</html>
