<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title><?php echo $this->translation['Application Name'];?></title>
<?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>

</head>
<body class="yui-skin-sam">

<div id="pageHolder">

  <div id="header"><?php require_once('views/scripts/header.phtml');?></div>
  <div id="content">

    <h1><?php echo t('Test scores')?></h1> <!-- TA:66 translation -->

    <div class="simpleLabel"><?php tp('Course');?></div>
    <div class="simpleValue"><?php echo $this->courseName; ?></div>

    <div class="simpleLabel"><?php tp('Score Import');?></div>
    <div class="simpleValue">
    <form id="upload" method="post" enctype="multipart/form-data">
    <?php tp('Enter scores by importing a CSV file.'); ?> <br/><br/>
      <input type="file" name="import" /> <input type="submit" value="<?php tp('Import');?>" class="importBtn"/>
      <br clear="all"/><br clear="all"/>
      <a href="<?php echo $this->base_url; ?>/training/scores-template/training/<?php echo $this->training_id; ?>/outputType/csv"><?php tp('Get sample Excel template'); ?></a>
    </form>
    <hr/>
    </div>

    <div class="simpleLabel"><?php tp('Scores');?></div>
    <div class="simpleValue"><?php echo $this->editTable; ?></div>

    <br clear="all">

    <form method="get" action="<?php echo $this->base_url;?>/training/edit/id/<?php echo $this->training_id; ?>">
    <input type="hidden">
    <input type="submit" value="<?php echo t('Return to Training');?>" class="submitArrow">
    </form>

    <div class="clear"></div>



  </div>
  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>


</div>

</body>
</html>