<html>
	<head>
		<title><?php echo $this->escape($this->title);?></title>
		<link href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet" type="text/css">

	<?php
	require_once('views/helpers/Location.php');
	require_once('views/helpers/ScriptContainer.php');
	print ScriptContainer::$instance->renderCSSHead();
	print ScriptContainer::$instance->renderJSHead();	 ?>
	



		<script type="text/javascript" charset="utf-8">
			$(document).ready(function() {
				$( ".calendarbox" ).datepicker({
					changeMonth: true,
					changeYear: true
				});
				/* Add a click handler to the rows - this could be used as a callback */
				$(".tablegrid tbody").click(function(event) {
					$(oTable.fnSettings().aoData).each(function (){
						$(this.nTr).removeClass('row_selected');
					});
					$(event.target.parentNode).addClass('row_selected');
				});
	
				/* Add a click handler for the delete row */
				$('#delete').click( function() {
					var anSelected = fnGetSelected( oTable );
					oTable.fnDeleteRow( anSelected[0] );
				} );
	
				/* Init the table */
				oTable = $('.tablegrid').dataTable({
					"bJQueryUI": true,
					"sPaginationType": "full_numbers"
				});
			} );

			/* Get the rows which are currently selected */
			function fnGetSelected( oTableLocal ){
				var aReturn = new Array();
				var aTrs = oTableLocal.fnGetNodes();
				
				for ( var i=0 ; i<aTrs.length ; i++ ){
					if ( $(aTrs[i]).hasClass('row_selected') ){
						aReturn.push( aTrs[i] );
					}
				}
				return aReturn;
			}
		</script>
	</head>
	<body>
	<div id="pageHolder">
			<div id="header"><?php require_once('views/scripts/preheader.phtml');?></div>
			<div id="content">
			<div id="subcontent">
				<div id="contentheader">
					<h2>Institution Search</h2><br>
			
				</div>
				<div class="pad50 clear"></div>
				<form  action="" id="peopleadd" method="post">
				<div class="mainformholder">
					
			  <p style="">Select Criteria</p><br>
 					<label>Institution Name</label>
					<input type="text" name="name" size="32" maxlength="32" value="<?php echo $this->escape($_POST['name']);?>">

							<!-- geographical area-->
							<label id="province_id_lbl"><span class="required">*</span> <?php echo (@$this->translation['Region A (Province)']); ?></label>
<?php
	renderFilter($this->locations, 1, 'geo1', $_POST['geo1'], 'geo2');
	if ( $this->setting['display_region_b'] ) {
?>
							<label id="district_id_lbl"><span class="required">*</span> <?php echo (@$this->translation['Region B (Health District)']); ?></label>
<?php
		renderFilter($this->locations, 2, 'geo2', $_POST['geo2'], ($this->setting['geo3']?'region_c_id':false));
?>
<?php
	}
?>
<?php
	if ( $this->setting['display_region_c'] ) {
?>
							<label id="region_c_id_lbl"><span class="required">*</span> <?php echo (@$this->translation['Region C (Local Region)']); ?></label>
<?php
		renderFilter($this->locations, 3, 'geo3', $_POST['geo3'], false);
?>
<?php
	}
?>

                     <label>Institution Sponsor</label>
					<select name="sponsor">
<?php
	echo "<option value=\"0\">Any</option>\n";
	foreach ($this->sponsors as $sponsor){
		echo "<option value=\"" . $sponsor['id'] . "\"" . ($sponsor['id'] == $_POST['sponsor'] ? " selected" : "") . ">" . $sponsor['sponsorname'] . "</option>\n";
	}
?>
					</select>
					
					<label>Institution Type</label>
					<select name="instype" id="instype">
						<option value="0">Select...</option>
<?php
	foreach ($this->institutiontypes as $instype){
?>
						<option value="<?php echo $instype['id']; ?>"<?php echo $this->escape($_POST['instype']) == $instype['id'] ? " selected" : ""; ?>> <?php echo $instype['typename']; ?></option>
<?php
	}
?>
					</select>
					
					<div class="rightdiv">
					<input type="submit" name="submit" value="Search &raquo;" class="tsbutton green large"></div>

					<div class="pad50 clear"></div>
					<?php /*?><a href="<?php  echo Settings::$COUNTRY_BASE_URL.'/institution/institutionadd'; ?>" style="float:left;font-size:14px;">Add New Institution</a><?php */?>
					</div></form>
					<div class="pad50 clear"></div>
					
					
<div style="width :100%;">
<table cellpadding="0" cellspacing="0" border="0" class="display tablegrid" id="" style="width:100%">
	<thead>
		<tr>
			<th>ID</th>
			<th>Name</th>
			<th><?php echo (@$this->translation['Region A (Province)']); ?> </th>
			<th><?php echo (@$this->translation['Region B (Health District)']); ?></th>
			<th><?php echo (@$this->translation['Region C (Local Region)']); ?></th>
			<th>Type</th>
		</tr>
	</thead>
	<tbody>
	<?php foreach ($this->institute as $fetchins){ ?>
		<tr style="cursor : pointer;" class="GradeA" onClick="window.location.href='<?php echo Settings::$COUNTRY_BASE_URL; ?>/institution/institutionedit/id/<?php echo $fetchins[id]; ?>' ">
			<td><?php echo $fetchins['id'];?></td>
			<td class=""><?php echo $fetchins['institutionname'];?></td>
			<td class=""><?php echo !is_null($fetchins['geo1']) ? $fetchins['geo1'] : "N/A";?></td>
			<td class=""><?php echo !is_null($fetchins['geo2']) ? $fetchins['geo2'] : "N/A";?></td>
			<td class=""><?php echo !is_null($fetchins['geo3']) ? $fetchins['geo3'] : "N/A";?></td>
			<td class=""><?php echo $fetchins['typename'];?></td>
		</tr>
	<?php } ?>
	
		<!--<tr class="GradeA">
			<td>2</td>
			<td class="">John Doe</td>
			<td class="">12315</td>
			<td class="">316</td>
			<td class="">545</td>
			<td class="">Cohort</td>
		</tr>-->
	
		
	</tbody>
</table>
					<div class="pad50 clear"></div>
 <a href="../institution/institutionadd" style="">
				 <input type="submit" name="institution" value="Add New Institution" class="tsbutton green large"></a>
</div>
			

			  
				</div>
				 
			  
			</div>
		</div>
						
  
		<div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
		</div>
	</body>
</html>