<?php
/*
 * Created on Mar 7, 2008
 *
 *  Built for itechweb
 *  Fuse IQ -- todd@fuseiq.com
 *
 */
function no_soft_space_str($v){
	return str_replace(' ', '&nbsp;', $v);
}

$navMain = array( // directory => array of nav items
  'index' => array(
    'index' => t('Home'), // file => label (use "index" for root)
  ));

if ( $this->isLoggedIn() ) {

	if ( $this->hasACL('in_service')) {
		if ( $this->hasACL('edit_course')  ){
			$navMain['training'] = array(
			'index' => t('Trainings'),
	    'view'  => t('View/Edit Training'),
	    'add' => t('Add New Training')
			);
		} else {
			$navMain['training'] = array(
			'index' => t('Trainings'),
	    'view'  => t('View Training')
			);
		}

		if ( $this->hasACL('edit_people')  ){
			$navMain['person'] = array(
			'index' => t('People'),
			'search'  => t('View/Edit Person'),
			'add' =>  t('Add New Person')
			);
		} else {
			$navMain['person'] = array(
			'index' => t('People'),
			'search'  => t('View person'),
			);
		}

		if ( $this->hasACL('edit_course') or $this->hasACL('edit_people') or $this->hasACL('view_people') ) {
			$navMain['facility'] = array('index' => t('Places'));

			if (   $this->hasACL('edit_people')  ) {
				$navMain['facility']['search']  = t('View/Edit Facility');
			} else if ($this->hasACL('view_people')) {
				$navMain['facility']['search']  = t('View facility');
			}
			if (   $this->hasACL('edit_people') && $this->hasACL('add_new_facility')) { //TA:17:12: 10/04/2014
				$navMain['facility']['add']  = t('Add Facility');
			}

			if (   $this->hasACL('edit_course')  && $this->setting['display_training_location']) { //TA:17:14:
     	$navMain['facility']['search-location']  = t('View/Edit').' '.t('Training Location');
			} else if ($this->hasACL('view_course')) {
     	$navMain['facility']['search-location']  = t('View').' '.t('Training Location');
			}
			if (   $this->hasACL('edit_course') && $this->setting['display_training_location']) { //TA:17:14:)
      	$navMain['facility']['add-location']  = t('Add').' '.t('Training Location');
			}
		}

		if ( $this->hasACL('view_create_reports') && $this->setting['display_country_reports']) { //TA:17: 09/11/2014
			$navMain['reports'] = array('index' => t('Reports'));

			if ( $this->setting['display_mod_skillsmart'] ) {

				$navMain['reports']['person->reports']               = t('Individual Report');
				$navMain['reports']['comp']                          = t('Competence Overview Report');
				$navMain['reports']['prof']                          = t('Professional Reports');
				$navMain['reports']['compcomp']                      = t('Competence Compare Reports');
				$navMain['reports']['quescomp']                      = t('Question Compare Reports');
				$navMain['reports']['../']                           = '---------------';
			}

			$navMain['reports']['training-by-participants']            = t('Training Reports');
			//TA:#253
// 			$navMain['reports']['participants-by-category/cat/pepfar'] = t('Participant Reports');
			$navMain['reports']['participants-by-training'] = t('Participant Reports');
			if ($this->setting['display_budget_code']) {
				$navMain['reports']['budget-code']                    = t('Budget Code Reports');
			}
			$navMain['reports']['trainers']                          = t('Trainer Reports');
			$navMain['reports']['training-by-facility-count']           = t('Facility Reports');
			$navMain['reports']['needs-by-person-name']                 = t('Assessment Reports');
			$navMain['reports']['roster']                            = t('Roster Reports');
			$navMain['reports']['evaluations']                       = t('Evaluations Reports');
			$navMain['reports']['data']                              = t('Data Downloads');
			//  '' =>

			if ( !$this->setting['display_training_recommend'] ) {
				unset($navMain['reports']['needs-by-person-name']);
			}

			if ( $this->hasACL('pre_service')) {
				$navMain['reports']['..//']                          = '---------------';
				$navMain['reports']['ps-students-trained']			= t('Student Reports');
				$navMain['reports']['ps-course-by-name']				= t('Course Reports');
				$navMain['reports']['ps-cohort-by-participant-count']	= t('Cohort Reports');
				$navMain['reports']['ps-institution-information']		= t('Institution Reports');
				$navMain['reports']['ps-tutor-by-name']				= t('Tutor Reports');
				$navMain['reports']['ps-facility-report']				= t('Facility Report');
			}
		}

		if ( $this->setting['module_evaluation_enabled']) {
			$navMain['evaluation'] = array(
			'index' => t('Evaluations')
			);
		}
	}

	// PRE-SERVICE LINK
	if ( $this->hasACL('pre_service') or $this->hasACL('admin_preservice') ) {
		$navMain['dash'] = array(
		'index' => t('Pre-service')
		);
	}

  // employee mod link
  if ($this->setting['module_employee_enabled'])
    $navMain['employee'] = array('index' => t('Employees') );


  // employee header (override other menus)
  $controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
  if ($controller == 'employee' || strstr($_SERVER['REQUEST_URI'] , 'reports/employee') || strstr($_SERVER['REQUEST_URI'] , 'reports/partners') || $controller == 'site' || $controller == 'partner')
  {
    $navMain = array( // directory => array of nav items
    'index' => array(
    'index' => t('Home'), // file => label (use "index" for root)
    ));
    $navMain['partner'] = array( 'index' => t('Partners') );
    $navMain['partner']['add']     = t('Add Partner');
    $navMain['partner']['search']  = t('View/Edit Partner');
    $navMain['employee'] = array( 'index' => t('Employees') );// BS:1:10/06/2014 translate employee/employees
    $navMain['employee']['add']    = t('Add Employee'); 
    $navMain['employee']['search'] = t('View/Edit Employee');
    #$navMain['site'] = array( 'index' => t('Sites') );
    #$navMain['site']['search']     = t('View/Edit').space.('Site');
    #$navMain['site']['add']        = t('Add').space.('Site');
    $navMain['reports'] = array( 'index' => t('Reports') );
    $navMain['reports']['employees'] = t('Employees');
    $navMain['reports']['partners'] = t('Partners');
  }

	$navMain['user'] = array(
	'index' => t('My Account'),
	);

	if ( $this->hasACL('edit_country_options')) {
		$navMain['user']['../admin/country-settings'] = t('Country Setup');
		$navMain['user']['../admin/training-settings'] = t('Training Settings');
		$navMain['user']['../admin/people-settings'] = t('People Settings');
		$navMain['user']['../admin/facilities-settings'] = t('Facility Settings');
	}
	if ( isset($this->setting['display_training_partner']) && $this->setting['display_training_partner'] == 1 ) {
		if ( $this->hasACL('edit_country_options') ) {
      $navMain['user']['../training-partner/search']  = no_soft_space_str( t('Training Partners') );
		}
	}
  if ( isset($this->setting['module_employee_enabled']) && $this->setting['module_employee_enabled'] == 1 ) {
    if ( $this->hasACL('edit_country_options') ) {
      $navMain['user']['../admin/employee-settings']  = no_soft_space_str( t('Employees Settings') );
    }
  }
	if ( $this->hasACL('add_edit_users')) {
		$navMain['user']['add'] = t('Add New User');
		$navMain['user']['search'] = t('Edit User');
	}
	//TA:50:1 display use offline app only for some sites
// 	if ( $this->setting['display_use_offline_app'] && ($this->hasACL('edit_country_options') || $this->hasACL('use_offline_app'))) {
	//TA:95 remove offline access from in-service, show only for pre-service 
	if ( $this->setting['display_use_offline_app'] && $this->hasACL('use_offline_app') && $this->hasACL('pre_service')) {
		$navMain['user'][''] = '---------------';
		//$navMain['user']['../desktop/create'] = no_soft_space_str( t('Create App Now') );
		$navMain['user']['../desktop/download'] = no_soft_space_str( t('Download PS Application') );
		//$navMain['user']['../desktop/download-dotnet'] = no_soft_space_str( t('Get Required .NET') );
		//TA:1000 $navMain['user']['../sync/upload'] = t('Upload PS Application');
	}
}


$firstName = 'guest';
$loginoutLink =  '<a href="'.(Settings::$COUNTRY_BASE_URL).'/user/login">'.t("login").'</a>';
if ( $this->isLoggedIn() ) $firstName = $this->identity->first_name;
if ( $this->isLoggedIn() ) $loginoutLink = '<a href="'.(Settings::$COUNTRY_BASE_URL).'/user/logout">'.t("logout").'</a>';

// custom inline CSS
if(isset(Settings::$CSS)) {
	echo '<style>' . Settings::$CSS . '</style>';
}

?>


<!-- login links -->
<a href="<?php echo Settings::$COUNTRY_BASE_URL;?>"><img src="<?php
	$engender = false;

	if ($this->setting['site_style'] === 'eventsmart') {
		echo Settings::$COUNTRY_BASE_URL.'/images/engenderhealth-logo-v2.gif';
		$engender = true;
	}
	else if ( isset($this->setting['logo_id']) ) {
		echo Settings::$COUNTRY_BASE_URL.'/file/download/id/'.$this->setting['logo_id'];
	}
	else {
		switch ( strtolower(Settings::$COUNTRY_NAME) ) {
			case 'haiti':
			echo Settings::$COUNTRY_BASE_URL.'/images/haiti_flag.jpg';
			break;
			case 'tanzaniapartners':
			echo Settings::$COUNTRY_BASE_URL.'/images/tanzanian_flag.png';
			break;
			case 'tanzanianacp':
			echo Settings::$COUNTRY_BASE_URL.'/images/tanzanian_flag.png';
			break;
			default:
			echo Settings::$COUNTRY_BASE_URL.'/images/header.gif';
			break;
		}
	}

?>" id="headerImg" alt="banner" /></a>
<div style="color:#99CC7E; float:left; padding-top:20px; vertical-align:middle;"><span style="font-size:4em;"><?php echo $this->translation['Application Name'];?></span><br/><span style="margin-left:120px;"><?php echo $this->setting['country'];?></span></div>
<div style="float:right;">
	<div id="headerLinks">
		<?php print t('Welcome');?>, <?php echo $firstName;?> <span class="pipe">|</span> <?php echo  $loginoutLink;?>&nbsp;

		<!-- switch language -->
		<div style="margin-top:70px; text-align:right; ">
			<?php
			if(count($this->languages_enabled) > 1) {
				foreach( $this->languages_enabled as $lang_opt) {
					$opts []= '<a href="'.Settings::$COUNTRY_BASE_URL.'/index/language?opt='.urlencode($lang_opt).'">'.t($this->languages[$lang_opt]).'</a>';
				}
				print implode ('&nbsp;|&nbsp;', $opts);
			}
			?>
		</div>

	</div>

</div><div class="clear"></div>

	<!-- main navigation -->
	<div id="navMain">
		<?php
		// Detect page
		$parsed_url = parse_url(Settings::$COUNTRY_BASE_URL);
		$pathFront = @$parsed_url['path'];
		if ( $pathFront )
		$path = str_replace($pathFront,'',$_SERVER['REQUEST_URI']);
		else
		$path = $_SERVER['REQUEST_URI'];
		// Sean Smith: Added filter out double slashes (handles improper config in globals.php, and other unforseeables)
		$path = str_replace("//",'/',$path);
		$path = str_replace("\\",'/',$path);
		$path = explode('/',$path);

		foreach($navMain as $dir => $navRay) {
			$class = array();
			if($dir == 'index') { $class[] = 'first'; /*$dir = '' ;*/  } // special CSS // uncomment to apply active class (always on) the ohome link

			// add "active" class
			if(empty($path[1]) || /*empty($dir) ||*/ $path[1] == $dir) { $class[] = 'active'; } /* commenting out always-on for home link */

			echo '
			<div class="flydown" '.($dir == 'user'? 'style="float:right;"':'').' onmouseover="fadeShow(this,\''.$dir.'\');" onmouseout="fadeOut(this,\''.$dir.'\');">
			';
			echo '<a href="'.Settings::$COUNTRY_BASE_URL.'/'.$dir.'"'.(!empty($class) ? ' class="'.implode(' ', $class).'"' : '').' id="nav'.$dir.'">' . $navRay['index'] . '</a>';

			// Fly-down menu items
			if(count($navRay) > 1) {
				echo '<div class="flydownItems">';
				foreach($navRay as $file => $label) {
					if( strstr($file, '->') ){
						$fragments = explode('->', $file);
						echo '<a '.(strlen($file)?'href="'.Settings::$COUNTRY_BASE_URL.'/'.$fragments[0].'/'.$fragments[1].'"':'').' >'.$label.'</a>';
					} else {
						if($file != 'index') {
							echo '<a '.(strlen($file)?'href="'.Settings::$COUNTRY_BASE_URL.'/'.$dir.'/'.$file.'"':'').' >'.$label.'</a>';
						}
					}
				}
				echo '</div>';
			}

			echo '</div>';

		}

		?>


	</div>

