<?php
//include in the page if you are using a old style form POST to display the status messages
?>
<div id="status"></div>
<script type="text/javascript">
    <?php
    if (isset($this->status)) {
        if ($this->status->redirect) {
            echo "window.location = {$this->status->redirect};";
        } else {
            echo "$(document).ready(function () {\n";
            if (isset($this->status->status) and $this->status->status) {
                echo "displayStatus('{$this->status->status}');\n";
            }
            foreach ($this->status->messages as $field => $msg) {
                echo "displayErrorMessage('$field', '$msg');\n";
            }
            echo "});\n";
        }
    }
    ?>
</script>