<html>
<head>
    <title><?php echo $this->escape($this->title); ?></title>
    <link href="//fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet" type="text/css">
    <?php
    require_once('views/helpers/Location.php');
    require_once('views/helpers/ScriptContainer.php');
    require_once('views/helpers/DropDown.php'); 
    
    print ScriptContainer::$instance->renderCSSHead();
    print ScriptContainer::$instance->renderJSHead();
    ?>
    <script type="text/javascript" charset="utf-8">
        $(document).ready(function () {
            $(".calendarbox").datepicker({
                changeMonth: true,
                changeYear: true,
                yearRange: '1900:2099(new Date).getFullYear()'
            });
            /* Add a click handler to the rows - this could be used as a callback */
            $(".tablegrid tbody").click(function (event) {
                $(oTable.fnSettings().aoData).each(function () {
                    $(this.nTr).removeClass('row_selected');
                });
                $(event.target.parentNode).addClass('row_selected');
            });

            /* Add a click handler for the delete row */
            $('#delete').click(function () {
                var anSelected = fnGetSelected(oTable);
                oTable.fnDeleteRow(anSelected[0]);
            });

            /* Init the table */
            oTable = $('.tablegrid').dataTable({
                "bJQueryUI": true,
                "sPaginationType": "full_numbers"
            });
        });

        /* Get the rows which are currently selected */
        function fnGetSelected(oTableLocal) {
            var aReturn = new Array();
            var aTrs = oTableLocal.fnGetNodes();

            for (var i = 0; i < aTrs.length; i++) {
                if ($(aTrs[i]).hasClass('row_selected')) {
                    aReturn.push(aTrs[i]);
                }
            }
            return aReturn;
        }

        $(document).ready(function () {
            $("#second").validate();
        });
        <?php
            // TODO: This hack is a bad solution, but will work better and be more obvious than what was here before.
            // TODO: Redirecting the form action set by the controller in the view javascript is not consistent with
            // TODO: our MVC tools and more difficult to maintain.
            // TODO: Ideally we'd use the controller to insert the data and redirect to the proper edit
            // TODO: page after, but refactoring parts of preservice is a bigger chunk of time.
        ?>
        function clickform() {
            var getthing = $("#type_id option:selected").val();
            if (getthing == "tutor" || getthing == "key") {
                document.forms['second'].action = "../peopleadd/peopleadd/";
            } else {
                document.forms['second'].action = "../studentedit/studentedit/";
            }
        }

        //TA:87 people duplicate check
        <?php //if($this->mode == 'add') : ?>
        var formatViewUrl = function(elCell, oRecord, oColumn, sData) {
            var tredirect = '';
            <?php if($this->trainingredirect) { ?>
            tredirect = "/trainingredirect/<?php echo $this->trainingredirect; ?>";
            <?php } ?>
            <?php if($this->maketrainer) { ?>
            tredirect = tredirect + "/maketrainer/1";
            <?php } ?>
            if ( (sData == null) || (sData.length == 0) )
                sData = '&nbsp;&nbsp;&nbsp;';
            elCell.innerHTML = "<a href='<?php echo $this->base_url;?>/person/edit/id/" + oRecord.getData("person_id") + tredirect + "' >" + sData + "</a>";
        }
        
        //{key:"input", width:0, resizeable:true , label:"", hidden:"true", width:"0", className:"hidden"},
        var dupeColDefs =
            [{key:"input", width:15, resizeable:true , label:""}, //TA:57 10/08/2015 
             {key:"person_id", label: "<?php tp('ID')?>", sortable:false, resizable:false, formatter: formatViewUrl},
                {key:"first_name", width:60, sortable:true, resizeable:true , label:"<?php tp("First Name"); ?>"},
                <?php if ( !$this->setting['display_middle_name_last'] ) { ?>
                {key:"middle_name", width:66, sortable:true, resizeable:true , label:"<?php echo (@$this->translation['Middle Name']); ?>"},
                <?php } ?>
                {key:"last_name", width:54, sortable:true, resizeable:true , label:"<?php echo (@$this->translation['Last Name']); ?>"},
                {key:"birthdate", width:78, sortable:true, resizeable:true , label:"<?php tp("Date of Birth"); ?>"},
                {key:"gender", width:40, sortable:true, resizeable:true , label:"<?php tp("Gender"); ?>"},
                {key:"facility_name", width:120, sortable:true, resizeable:true , label:"<?php tp("Facility");?>"},
                {key:"qualification_phrase", width:100, sortable:true, resizeable:true, label:"<?php tp("Qualification"); ?>"},
                {key:"national_id", width:60, sortable:true, resizeable:true , label:"<?php tp("National ID"); ?>"}
                <?php if ( $this->setting['display_people_file_num'] ) { ?>
                ,{key:"file_number", width:60, sortable:true, resizeable:true, label:"<?php tp("File Number"); ?>"}
                <?php } ?>
            ];

        var dupeDataSource = { } // filled via ajaxDupeSuccess callback

        var ajaxDupeSuccess = function(o) {
            if(o.responseText !== undefined){
                if(!o.responseText) {
                    YAHOO.util.Dom.get('dupecheck').innerHTML = "<em><?php tp('No duplicates found.'); ?></em>";
                } else {
                    dupeDataSource = eval(o.responseText);
                    makeDynamicDataTable("dupecheck", "<?php tp("If the person already exists, please select their name below."); ?>", dupeDataSource, dupeColDefs);
                    YAHOO.util.Dom.removeClass(YAHOO.util.Dom.get('submitAddContinue'), "hidden");
                    do_dupe_highlight();
                }
            }
        }

        function do_dupe_highlight(){
            var checkval1 = $('#file_number').val() || -1;
            var checkval2 = $('#national_id').val() || -1;
            var style = {'border': '1px dotted pink','background': '#CAD'};
            $('#dupecheck div.yui-dt-bd table td div').each(function(){
                var val = $(this).html();
                if (val == checkval1) $(this).parents('tr:first').css(style);
                if (val == checkval2) $(this).parents('tr:first').css(style);
            });
        }

        var ajaxDupeFailure = function(o){
            if(o.responseText !== undefined){
                YAHOO.util.Dom.get('dupecheck').innerHTML = o.status + "<br />" + o.statusText;
            }
        }

        var callback = {
            success:ajaxDupeSuccess,
            failure: ajaxDupeFailure
        };

        var isTimeout = false;

        function buildDupeTable(e) {
            if(!isTimeout) {
                var last_name   = $('#last_name').val()   || '';
                var first_name  = $('#first_name').val()  || '';
                var file_number = $('#file_number').val() || '';
                var national_id = $('#national_id').val() || '';
                var qualification = $('#primary_qualification_option_id').val() || '';

                if(last_name || first_name || national_id || file_number) {
                    YAHOO.util.Dom.removeClass(YAHOO.util.Dom.get('duplicateCheckLabel'), "hidden");

                    var sUrl = "<?php echo $this->base_url;?>/person/dupe-list/outputType/json?";
                    sUrl += "last_name=" + last_name + "&";
                    sUrl += "first_name=" + first_name + "&";
                    sUrl += "file_number=" + file_number + "&";
                    sUrl += "national_id=" + national_id + "&";
                    sUrl += "primary_qualification_option_id=" + qualification + "&";
                    var request = YAHOO.util.Connect.asyncRequest('GET', sUrl, callback);

                    isTimeout = true;
                    setTimeout(function() {
                        isTimeout = false;
                        if(e) {
                            buildDupeTable(false);
                        }
                    }, 300);
                } else {
                    YAHOO.util.Dom.get('dupecheck').innerHTML = "";
                }
            }
        }

        function continueClick() {

            // find checked radio
            var elChecked = YAHOO.util.Dom.getElementsBy( function(el) {
                return el.checked;
            }, 'input',YAHOO.util.Dom.get('dupecheck'));

            if(elChecked && elChecked.length) {
                elChecked.form.submit();
            } else {
                last_name = YAHOO.util.Dom.get('last_name').value;
                first_name = YAHOO.util.Dom.get('first_name').value;

                if(!last_name || !first_name) {
                    alert("<?php tp("Please enter a first and last name."); ?>");
                } else {
                    YAHOO.util.Dom.removeClass(YAHOO.util.Dom.get('personAddHide'), "hidden");
                    YAHOO.util.Dom.addClass(YAHOO.util.Dom.get('submitAddContinue'), "hidden");
                    $('#dupecheck,#duplicateCheckLabel').hide();
                }
            }

            return false;
        }

        YAHOO.util.Event.onDOMReady(function() {
            YAHOO.util.Event.addListener(YAHOO.util.Dom.get('last_name'), "keyup", buildDupeTable);
            YAHOO.util.Event.addListener(YAHOO.util.Dom.get('first_name'), "keyup", buildDupeTable);
            YAHOO.util.Event.addListener(YAHOO.util.Dom.get('primary_qualification_option_id'), "change", buildDupeTable);
            YAHOO.util.Event.addListener(YAHOO.util.Dom.get('national_id'), "keyup", buildDupeTable);
            YAHOO.util.Event.addListener(YAHOO.util.Dom.get('file_number'), "keyup", buildDupeTable);
        });

        <?php //endif; //add only dupe check ?>

        YAHOO.util.Event.onDOMReady(function() {
            <?php if ( $this->mode == 'edit' ) { ?>
            addAjaxSubmit('submitPerson','personForm','<?php echo $this->base_url;?>/person/edit/id/<?php echo $this->person['id'];?>/outputType/json');
            <?php } else { ?>
            addAjaxSubmit('submitPerson','personForm','<?php echo $this->base_url;?>/person/add/outputType/json');
            <?php } ?>
            <?php if ( $this->mode == 'edit' ) { ?>
            addAjaxSubmit('submitPersonTop','personForm','<?php echo $this->base_url;?>/person/edit/id/<?php echo $this->person['id'];?>/outputType/json');
            <?php } else { ?>
            //addAjaxSubmit('submitPersonTop','personForm','<?php echo $this->base_url;?>/person/add/outputType/json');
            <?php } ?>
            <?php if ( $this->mode == 'edit' && $this->maketrainer) { ?>
            displayStatus("<?php echo t('Please add or verify the').' '.t('trainer').' '.t('information below.'); ?>");
            <?php } ?>
        });
    </script>

    <!--<input type="radio' name="student" value="student" onclick=click(this.value);>
    <input type="radio' name="tutor" value="tutor" onclick=click(this.value);>-->
</head>
<body class="yui-skin-sam">
<div id="pageHolder">
    <div id="header"><?php require_once('views/scripts/preheader.phtml'); ?></div>
    <div id="content">
        <div id="subcontent">
            <div id="contentheader">
                <h2><?php echo t('Add a New Student or Tutor Record'); ?></h2><br>
                <p style="float:left;font-size:13px;"><?php echo t('Enter details'); ?></p>
            </div>

            <div class="pad50 clear"></div>

            <div class="mainformholder" style="">
            <!-- TA:92 add validation to select Type -->
                <form action="<?php echo $this->escape($this->action); ?>" method="post" name="second" id="second" onsubmit="if($('#type_id option:selected').val() == ''){alert('Please select Type');return false;}">
                    <label><?php echo t('Title'); ?></label>
                    <select name="title">
                        <option value="0"><?php echo t('Select...'); ?></option>
                        <?php
                        foreach ($this->fetchtitle as $fetchtitle) {
                            ?>
                            <option
                                value="<?php echo $fetchtitle[id]; ?>"><?php echo $fetchtitle[title_phrase]; ?></option>
                            <?php
                        }
                        ?>
                    </select>

                    <label><span class="required">*</span> <?php echo t('First name'); ?></label>
                    <input type="text" name="first_name" id="first_name" value="" class="required">

                    <label><?php echo t('Middle name'); ?></label>
                    <input type="text" name="middlename" value="" class="">

                    <label><span class="required">*</span> <?php echo t('Last name'); ?></label>
                    <input type="text" name="last_name" id="last_name" value="" class="required">

                    <label><?php echo t('Gender'); ?></label>
                    <select name="gender" id="gender">
                        <option value="male"><?php echo t('Male'); ?></option>
                        <option value="female"><?php echo t('Female'); ?></option>
                        <option value="unknown"><?php echo t('Unknown'); ?></option>
                    </select>

                    <label><?php echo t('Date of birth'); ?></label>
                    <input type="text" class="calendarbox" name="dob" value=""><br>

                    <label><?php echo t('Institution'); ?></label>
                    <select name="institutionid" id="institutionid">
                        <?php
                        foreach ($this->institutions as $institution) {
                            ?>
                            <option
                                value="<?php echo $institution['id']; ?>"><?php echo $institution['institutionname']; ?></option>
                            <?php
                        }
                        ?>
                    </select>

                    <div class="pad50 clear"></div>
                    <p style="float:left;font-size:14px;"><?php echo t('Local address'); ?></p>

                    <div class="pad20 clear"></div>

                    <!-- geographical area-->
                    <label id="province_id_lbl"><span
                            class="required">*</span> <?php echo(@$this->translation['Region A (Province)']); ?></label>
                    <?php
                    renderFilter($this->locations, 1, 'province_id', 0, 'district_id');
                    if ($this->setting['display_region_b']) {
                        ?>
                        <label id="district_id_lbl"><span
                                class="required">*</span> <?php echo(@$this->translation['Region B (Health District)']); ?>
                        </label>
                        <?php
                        renderFilter($this->locations, 2, 'district_id', 0, ($this->setting['display_region_c'] ? 'region_c_id' : false));
                        ?>
                        <?php
                    }
                    ?>
                    <?php
                    if ($this->setting['display_region_c']) {
                        ?>
                        <label id="region_c_id_lbl"><span
                                class="required">*</span> <?php echo(@$this->translation['Region C (Local Region)']); ?>
                        </label>
                        <?php
                        renderFilter($this->locations, 3, 'region_c_id', 0, false);
                        ?>
                        <?php
                    }
                    ?>
                    <!-- geographical area-->

                    <label><?php echo t('Facility'); ?></label>
                    <select name="facility" id="facility">
                        <option value="0"><?php echo t('Select...'); ?></option>
                        <?php
                        foreach ($this->fetchfacility as $facility) {
                            ?>
                            <option
                                value="<?php echo $facility[id]; ?>"><?php echo $facility[facility_name]; ?></option>
                            <?php
                        }
                        ?>
                    </select>

                    <label><?php echo t('Address 1'); ?></label>
                    <input type="text" name="address1" value="">

                    <label><?php echo t('Address 2'); ?></label>
                    <input type="text" name="address2">

                    <label><?php echo t('City'); ?></label>
                    <select name="city">
                        <option value="0"><?php echo t('Select...'); ?></option>
                        <?php
                        foreach ($this->fetchcity as $city) {
                            ?>
                            <option value="<?php echo $city[id]; ?>"><?php echo $city[city_name]; ?></option>
                            <?php
                        }
                        ?>
                    </select>
                    <!--<input type="text" name="city" value="">-->

                    <label style="display : none;"><?php echo t('Postal code / ZIP'); ?></label>
                    <input type="text" name="zip" value="" style="display : none;">

                    <!-- TA:92 -->
                    <label><span class="required">*</span><?php echo t('Type'); ?></label>
                    <select name="type" id="type_id" class="required">
                        <?php if ($this->setting['site_style'] == 'skillsmart') { ?>
                            <option value="tutor"><?php echo t('Tutor'); ?></option>
                        <?php } else { ?>
                            <option value=""><?php echo t('Select'); ?></option>
                            <option value="student"><?php echo t('Student'); ?></option>
                            <option value="tutor"><?php echo t('Tutor'); ?></option>
                            <option value="key"><?php echo t('Personal'); ?></option>
                        <?php } ?>
                    </select>
                    
                    <!-- TA:87 -->
                     <?php //if($this->mode == 'add') { ?>

            <div class="clear"></div>
            <div class="fieldIndentNoMargin hidden" id="duplicateCheckLabel"><?php tp('Duplicate Check');?></div>
            <div id="dupecheck"></div>
            
            <?php //endif; ?>

                    <div class="rightdiv" style="padding-top:50px;margin-left:25px;;">
                        <input type="submit" border="0" class="tsbutton green large" onclick="clickform();"
                               name="addpeople" value="<?php echo t('Add person'); ?> &raquo;">
                    </div>
                </form>
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
        </div>
        <div class="clear"></div>
    </div>
    <div id="footer"><?php require_once('views/scripts/footer.phtml'); ?></div>
</div>
</body>
</html>