<script language="javascript">

function adminChecks(val) {
	chked = null;
	if( val==1 )
		chked = 'checked';
	$('#admin_box input[type="checkbox"]').attr('checked', chked);
	event.preventDefault();
	return false;
}

function showAdminLevels() {
	$('#admin_box').toggle();
	if(!$('#toggle').is(':checked')){
		$('#admin_box input').removeAttr('checked');
	}
}

//TA:#415
function setOrgAccessStatus() { /* organizer logic (restrict access), show hide, uncheck and check */
	if ($('#acl_org_restrict').attr('checked') == 'checked') {
		$('#orgs').slideDown();	
		if ($('#acl_mechanism_restrict').attr('checked') == 'checked') {
			 var mechFields = YAHOO.util.Dom.get("mechanisms").getElementsByTagName('input');
			 for(var i = 0; i < mechFields.length; i++) {
				 $(mechFields[i]).parent().parent().parent().hide();
				 orginizer_selected(mechFields[i]);
			 }
		}
	}else {
		$('#orgs').slideUp();
		if ($('#acl_mechanism_restrict').attr('checked') == 'checked') {
		 var mechFields = YAHOO.util.Dom.get("mechanisms").getElementsByTagName('input');
		 for(var i = 0; i < mechFields.length; i++) {
			    $(mechFields[i]).parent().parent().parent().show();
		 }
		 var orgFields = YAHOO.util.Dom.get("orgs").getElementsByTagName('input');
			for(var i = 0; i < orgFields.length; i++) {
				$(orgFields[i]).attr('checked', false);
			}
		}
	}

	var edCourseRB = YAHOO.util.Dom.get("edit_course");
	var orgFields = YAHOO.util.Dom.get("orgs").getElementsByTagName('input');
	for(var i = 0; i < orgFields.length; i++) {
		var isDisabled = false;
		if (edCourseRB.checked == false) isDisabled = true;
		orgFields[i].disabled = isDisabled;
		orginizer_selected(orgFields[i]);//TA:#415.2
	}
	
}

//TA:#415
function setMechanismAccessStatus(){
	if ($('#acl_mechanism_restrict').attr('checked') == 'checked') {
		$('#mechanisms').slideDown();
	}
	else {
		$('#mechanisms').slideUp();
	}

	var edCourseRB = YAHOO.util.Dom.get("edit_course");
	var orgFields = YAHOO.util.Dom.get("mechanisms").getElementsByTagName('input');
	for(var i = 0; i < orgFields.length; i++) {
		var isDisabled = false;
		if (edCourseRB.checked == false) isDisabled = true;
		orgFields[i].disabled = isDisabled;
	}
// 	var allOrgsRB = YAHOO.util.Dom.get("mechanism_option_all");
// 	if ( allOrgsRB.checked &&  edCourseRB.checked ) {
// 		for(var i = 0; i < orgFields.length; i++) {
// 			orgFields[i].checked = true;
// 			orgFields[i].disabled = true;
// 		}
// 		allOrgsRB.disabled = false;
// 	} else if ( edCourseRB.checked ) {
// 		for(var i = 0; i < orgFields.length; i++) {
// 			orgFields[i].disabled = false;
// 		}
// 	}
}

//TA:#415.2
var orginizer_selected = function (elem) {
	var org_id = $(elem).attr('id').replace("training_organizer_option_", "");    
	var mech_fields = YAHOO.util.Dom.get("mechanisms_box").getElementsByTagName('input');
	for(var i = 0; i < mech_fields.length; i++) {
		if($(mech_fields[i]).parent().parent().parent().attr('id') == org_id){
			if($(elem).attr('checked')){
			  $(mech_fields[i]).parent().parent().parent().show();
			}else{
				$(mech_fields[i]).parent().parent().parent().hide();
				$(mech_fields[i]).attr('checked', false);
			}
		}
	}				
}

YAHOO.util.Event.onDOMReady(setOrgAccessStatus);
YAHOO.util.Event.onDOMReady(setMechanismAccessStatus);//TA:#415

</script>

<form action="" id="userForm" method="POST">
<?php if($this->setting['display_last_name_first']){ //TA:UK:1712:23 shaw different names order for  PHC and UCFM?>
<div class="fieldLabel" id="last_name_lbl"><span class="required">*</span><?php echo $this->translation['Last Name'];?></div>
	<div class="fieldInput"><input type="text" name="last_name" size="32" maxlength="32" value="<?php echo $this->user['last_name'];?>"/></div>
<?php }?>
	<div class="fieldLabel" id="first_name_lbl"><span class="required">*</span><?php echo $this->translation['First Name'];?></div>
	<div class="fieldInput"><input type="text" name="first_name" size="32" maxlength="32" value="<?php echo $this->user['first_name'];?>"/></div>
	<?php if(!$this->setting['display_last_name_first']){ //TA:UK:1712:23 shaw different names order for  PHC and UCFM?>
	<div class="fieldLabel" id="last_name_lbl"><span class="required">*</span><?php echo $this->translation['Last Name'];?></div>
	<div class="fieldInput"><input type="text" name="last_name" size="32" maxlength="32" value="<?php echo $this->user['last_name'];?>"/></div>
	<?php }?>
	<div class="fieldLabel"  id="username_lbl"><span class="required">*</span><?php tp('Login');?></div>
	<div class="fieldInput"><input type="text" name="username" size="32" maxlength="32" value="<?php echo $this->user['username'];?>"/></div>
	<div class="fieldLabel"  id="password_lbl"><span class="required">*</span><?php tp('Password');?></div>
	<div class="fieldInput"><input type="text" name="password" size="32" maxlength="32" value="<?php echo $this->user['password'];?>"/></div>
	<div class="fieldLabel"  id="email_lbl"><span class="required">*</span><?php tp('E-mail');?></div>
	<div class="fieldInput"><input type="text" name="email" size="32" maxlength="256" value="<?php echo $this->user['email'];?>"/></div>
	<div class="clear"></div>

	<fieldset><legend><?php tp('Access Level');?></legend>
		<div class="fieldLabelThin"> <?php tp('In-Service');?></div><div class="fieldInput width100"><div class="float50"><input type="checkbox" name="in_service" id="in_service" CHECKED /><label for="in_service"> <?php tp('In-service access');?></label></div></div>
		<div class="fieldLabelThin"> <?php tp('Pre-Service');?></div><div class="fieldInput width100"><div class="float50"><input type="checkbox" name="pre_service" id="pre_service"/><label for="pre_service"> <?php tp('Pre-service access');?></label></div></div>
		<?php if ($this->setting['module_employee_enabled']): ?>
		<div class="fieldLabelThin"> <?php print(t('Employee Module'));?></div><div class="fieldInput width100"><div class="float50"><input type="checkbox" name="employees_module" id="employees_module" /><label for="employees_module"> <?php print(t('Access Employees'));?></label></div></div>
		<!-- TA:#421 START -->
					<div class="fieldLabelThin"> <?php print(t('Positions'));?></div>
					<div class="fieldInput width100">
						<div class="float50">
							<input type="checkbox" name="position_access" id="position_access"
								<?php if ( array_search('position_access', $this->user['acls']) !== false) echo 'CHECKED'; ?> /><label
								for=position_access> <?php print(t('View/add positions'));?></label>
						</div>
					</div>
					<!-- TA:#421 END -->
		<?php endif; ?>
		<br/><br/>

        <?php
            // don't allow users access to all training organizers for pepfarskillsmart
            $default_all_orgs = true;
            $default_all_mechanisms = true;//TA:#415
            if (strpos(strtolower($_SERVER['HTTP_HOST']), "pepfarskillsmart.trainingdata.org") > -1) {
                $default_all_orgs = false;
                $default_all_mechanisms = false;//TA:#415
            }
        ?>
		<div class="fieldLabelThin"> <?php tp('Restrict Access');?></div>
		<div class="fieldInput">
		<div class="float50">
		<label for="acl_orgAll"><input type="radio" id="acl_orgAll"
								name="training_organizer_option_all" value="training_organizer_option_all" onchange="setOrgAccessStatus();" CHECKED /> <?php tp('All organizations data');?></label>
						</div>
						<label for="acl_org_restrict"><input type="radio" id="acl_org_restrict"
							name="training_organizer_option_all" value="" onchange="setOrgAccessStatus();"/> <?php tp('Only selected organizations');?></label>
					</div>
					<!-- TA:#415 START -->
					<div class="fieldLabelThin"> </div>
					<div class="fieldInput">
						<div class="float50">
							<label for="acl_mechanismAll"><input type="radio" id="acl_mechanismAll"
								name="mechanism_option_all" value="mechanism_option_all" onchange="setMechanismAccessStatus();" CHECKED /> <?php tp('All mechanism data');?></label>
						</div>
						<label for="acl_mechanism_restrict"><input type="radio" id="acl_mechanism_restrict"
							name="mechanism_option_all" value=""
							onchange="setMechanismAccessStatus();"> <?php tp('Only selected mechanisms');?></label>
					</div>
					<!-- TA:#415 END -->
		<br/><br/>
		<div class="fieldLabelThin"> <?php tp('Reports');?></div><div class="fieldInput width100"><div class=""><input type="checkbox" id="view_create_reports" name="view_create_reports" CHECKED /><label for="view_create_reports"> <?php tp('View/create reports');?></label></div></div>
		<div class="fieldLabelThin"> <?php tp('Trainings');?></div>
		<div class="fieldInput"><div class="float50"><label for="edit_course"><input type="radio" id="edit_course" name="edit_course" value="edit_course" CHECKED onchange="setOrgAccessStatus();"> <?php tp('Add/Edit/Delete');?></label></div><label for="view_course"><input type="radio" id="edit_course" name="edit_course" value="view_course"  onchange="setOrgAccessStatus();"> <?php tp('View only');?></label></div>
		<div class="fieldLabelThin"></div><div class="fieldInput float50"><input type="checkbox" id="duplicate_training" name="duplicate_training" CHECKED /><label for="duplicate_training"> <?php tp('Ability to duplicate Training');?></label></div>
		<div class="fieldLabelThin"></div><div class="fieldInput float50"><input type="checkbox" id="use_offline_app" name="use_offline_app" CHECKED /><label for="use_offline_app"> <?php tp('Use Offline Application')?></label></div>
		<div class="fieldLabelThin"> <?php tp('People');?></div><div class="fieldInput"><div class="float50"><label for="edit_people"><input type="radio" id="edit_people" name="edit_people" value="edit_people" CHECKED> <?php tp('Add/Edit/Delete');?></label></div><label for="view_people"><input type="radio" id="view_people" name="edit_people" value="view_people"> <?php tp('View only');?></label></div>
		<div class="fieldLabelThin"> <?php tp('Facilities');?></div><div class="fieldInput"><div class="float50"><label for="edit_facility"><input type="radio" id="edit_facility" name="edit_facility" value="edit_facility" CHECKED> <?php tp('Add/Edit/Delete');?></label></div><label for="view_facility"><input type="radio" id="view_facility" name="edit_facility" value="view_facility"> <?php tp('View only');?></label></div>
		<div class="fieldLabelThin"> <?php tp('Training Location');?></div><div class="fieldInput"><div class="float50"><label for="edit_training_location"><input type="checkbox" id="edit_training_location" name="edit_training_location" value="edit_training_location" CHECKED> <?php tp('Add/Edit');?></label></div></div>
		<div><div class="fieldLabelThin"> <?php tp('Files');?></div><div class="fieldInput width100"><div class="float50"><input type="checkbox" id="admin_files" name="admin_files" CHECKED /><label for="admin_files"> <?php tp('Upload and delete');?></label></div></div></div>
		<div style="width:100%;height:auto;display:block;;">
		<div class="fieldLabelThin"> <?php tp('Approval');?></div><div class="fieldInput width100"><div class="float50"><input type="checkbox" id="approve_trainings" name="approve_trainings" /><label for="approve_trainings"> <?php tp('Approve trainings');?></label></div></div>

		<div class="fieldLabelThin"> <?php tp('Evaluations');?></div><div class="fieldInput width100"><div class="float50"><input type="checkbox" id="edit_evaluations" name="edit_evaluations" /><label for="edit_evaluations"> <?php echo t('Edit').' '.t('Evaluations');?></label></div></div>

		<div class="fieldLabelThin"> <?php tp('Approver');?></div><div class="fieldInput width100"><div class="float50"><input type="checkbox" id="acl_editor_training_category" name="acl_editor_training_category" /><label for="acl_editor_training_category"> <?php tp('Approve people and facilities');?></label></div></div>

		<div class="fieldLabelThin"> <?php tp('Admin'); ?></div><div class="fieldInput width100"><label for="toggle"><input type="checkbox" id="toggle" onchange="showAdminLevels();" /><label for=""> <?php tp('User is Administrator or can edit drop down lists, titles, and data, or import excel records');?></label></div>

	<fieldset id="orgs">
					<legend><?php tp('Organizer access');?></legend>
					<div>
						<div class="fieldLabelThin"></div>
						<div class="fieldInput"><div class="float50"></div></div>
						<div class="fieldLabelThin"></div>
						<div class="fieldInput">
							<a href="#" id="orgcheckall"> <?php tp('check all'); ?></a> <a
								href="#" id="orguncheckall"> <?php tp('uncheck all'); ?></a>
						</div>
							<?php
							foreach( $this->training_organizer as $org ) {
								echo '<div><div class="fieldLabelThin"></div><div class="fieldInput"><div class="float50">
    <input type="checkbox" name="training_organizer_option_id[]" id="training_organizer_option_'.$org['id'].'" value="'.$org['id'].'" onclick="orginizer_selected(this);"/><label for="training_organizer_option_'.$org['id'].'">'.$org['training_organizer_phrase'].'</label></div></div></div>';
							}
							?>	
				</fieldset>
	
	<!-- TA:#415 START -->
				<fieldset id="mechanisms">
					<legend><?php tp('Mechanism access');?></legend>
					<div>
						<div class="fieldLabelThin"></div>
						<div class="fieldInput">
							<div class="float50">
							</div>
						</div>
						<div class="fieldLabelThin"></div>
						<div class="fieldInput">
							<a href="#" id="mechanismcheckall"> <?php tp('check all'); ?></a> <a
								href="#" id="mechanismuncheckall"> <?php tp('uncheck all'); ?></a>
						</div>
						<div id="mechanisms_box">
							<?php
							foreach( $this->mechanism as $org ) {
							    $display = 'style="display:none;"';
								echo '<div id="' . $org['owner_id'] . '" ' . $display . '><div class="fieldLabelThin"></div><div class="fieldInput"><div class="float50">
    <input type="checkbox" name="mechanism_option_id[]" id="mechanism_option_'.$org['id'].'" value="'.$org['id'].'" />
			    <label for="mechanism_option_'.$org['id'].'">'.$org['mechanism_phrase'].'</label></div></div></div>';
							}
							?>
							</div>
				</fieldset>
				<!-- TA:#415 END -->

	<?php
	if ($this->showinstitutions){
		echo "      <fieldset id=\"institutions\" ><legend>" . t('Institution access') . "</legend>\n";
		echo "        <div>\n";
		echo "          <div class=\"fieldLabel\">\n";
		echo "          </div>\n";
		echo "          <div class=\"fieldInput\">\n";
		echo "            <div class=\"float50\">\n";
		echo "              <input type=\"checkbox\" name=\"institutions_all\" id=\"institutions_all\" value=\"institutions_all\"" . (count($this->userinstitutions) == 0 ? " checked" : "") . " onchange=\"toggleinstitution(this);\" /><label for=\"institutions_all\">" . tp('All Institutions') . "</label>\n";
		echo "            </div>\n";
		echo "          </div>\n";

		$disable = false;
		if (count($this->userinstitutions) == 0){
			$disable = true;
		}
		foreach( $this->institutions as $ins ) {
			echo "          <div>\n";
			echo "            <div class=\"fieldLabel\">\n";
			echo "            </div>\n";
			echo "            <div class=\"fieldInput\">\n";
			echo "              <div class=\"float50\">\n";
			echo "                <input class=\"institutioncheck\" type=\"checkbox\" name=\"institutionselect[]\" id=\"institutionselect[]\" value=\"" . $ins['id'] . "\"" . ($disable ? " disabled checked" : (in_array($ins['id'],$this->userinstitutions) ? " checked" : "")) . " /><label for=\"training_organizer_" . $ins['id'] . "\">" . $ins['institutionname'] . "</label>\n";
			echo "              </div>\n";
			echo "            </div>\n";
			echo "          </div>\n";
		}
		echo "        </div>\n";
		echo "      </fieldset>\n";
	}
	?>

	<fieldset id="admin_box" class="width100" style="display:none;"><legend><?php tp('Admin access');?></legend>
			<div class="fieldLabelThin"><?php tp('Admin'); ?></div><div class="fieldInput"><label><a href="#" id="admin_select_all"><button>select all admin capabilities</button></a><a href="#" id="admin_select_none"><button>de-select all</button></a></label></div>
		<div class="fieldLabelThin"> <?php tp('Restricted Settings'); ?></div><div class="fieldInput"><div class="width100"><input type="checkbox" id="edit_country_options" name="edit_country_options" /><label for="edit_country_options"> <?php tp('Edit country options');?></label></div></div>
		<div class="fieldLabelThin"></div><div class="fieldInput"><input type="checkbox" id="add_edit_users" name="add_edit_users" /><label for="add_edit_users"> <?php tp('Add/Edit users');?></label></div>

		<div class="fieldLabelThin"> <?php tp('Fields on/off and Labels'); ?></div><div class="fieldInput"><label for="acl_admin_training"><input type="checkbox" id="acl_admin_training" name="acl_admin_training" /><label for="acl_admin_training"> <?php tp('Training Settings');?></label></div>
		<div class="fieldLabelThin"></div><div class="fieldInput"><label for="acl_admin_people"><input type="checkbox" id="acl_admin_people" name="acl_admin_people" /><label for="acl_admin_people"> <?php tp('People Settings');?></label></div>
		<div class="fieldLabelThin"></div><div class="fieldInput"><label for="acl_admin_facilities"><input type="checkbox" id="acl_admin_facilities" name="acl_admin_facilities" /><label for="acl_admin_facilities"> <?php tp('Facility Settings');?></label></div>

		<div class="fieldLabelThin"> <?php echo t('Training').' '.t('and').' '.t('People'); ?></div><div class="fieldInput"><div class="float50"><label for="acl_editor_training_category"><input type="checkbox" id="acl_editor_training_category" name="acl_editor_training_category" /><label for="acl_editor_training_category"> <?php echo t('Edit').' '.t('Training category').' '.t('and').' '.t('Assignment');?></label></div><label for="acl_editor_people_qualifications"><input type="checkbox" id="acl_editor_people_qualifications" name="acl_editor_people_qualifications"> <?php echo t('Edit').' '.t('Professional Qualification');?></label></div>
		<div class="fieldLabelThin"></div><div class="fieldInput"><div class="float50"><label for="training_title_option_all"><input type="checkbox" id="training_title_option_all" name="training_title_option_all" onchange="setOrgAccessStatus();" /><label for="training_title_option_all"> <?php tp('Add Training Titles');?></label></div><label for="acl_editor_people_responsibility"><input type="checkbox" id="acl_editor_people_responsibility" name="acl_editor_people_responsibility"> <?php echo t('Edit').' '.t('Responsibility');?></label></div>
		<div class="fieldLabelThin"></div><div class="fieldInput"><div class="float50"><label for="acl_editor_training_organizer"><input type="checkbox" id="acl_editor_training_organizer" name="acl_editor_training_organizer" /><label for="acl_editor_training_organizer"> <?php echo t('Edit').' '.t('Training Organizer');?></label></div><label for="acl_editor_people_trainer"><input type="checkbox" id="acl_editor_people_trainer" name="acl_editor_people_trainer"> <?php echo t('Edit').' '.t('Trainer Types');?></label></div>
		<div class="fieldLabelThin"></div><div class="fieldInput"><div class="float50"><label for="acl_editor_training_topic"><input type="checkbox" id="acl_editor_training_topic" name="acl_editor_training_topic" /><label for="acl_editor_training_topic"> <?php echo t('Edit').' '.t('Training Topic');?></label></div><label for="acl_editor_people_titles"><input type="checkbox" id="acl_editor_people_titles" name="acl_editor_people_titles"> <?php echo t('Edit').' '.t('Titles');?></label></div>
		<div class="fieldLabelThin"></div><div class="fieldInput"><div class="float50"><label for="acl_editor_training_level"><input type="checkbox" id="acl_editor_training_level" name="acl_editor_training_level" /><label for="acl_editor_training_level"> <?php echo t('Edit').' '.t('Training level');?></label></div><label for="acl_editor_people_trainer_skills"><input type="checkbox" id="acl_editor_people_trainer_skills" name="acl_editor_people_trainer_skills"> <?php echo t('Edit').' '.t('Trainer Skills');?></label></div>
		<div class="fieldLabelThin"></div><div class="fieldInput"><div class="float50"><label for="acl_editor_pepfar_category"><input type="checkbox" id="acl_editor_pepfar_category" name="acl_editor_pepfar_category" /><label for="acl_editor_pepfar_category"> <?php echo t('Edit').' '.t('PEPFAR category');?></label></div><label for="acl_editor_people_languages"><input type="checkbox" id="acl_editor_people_languages" name="acl_editor_people_languages"> <?php echo t('Edit').' '.t('Languages');?></label></div>
		<div class="fieldLabelThin"></div><div class="fieldInput"><div class="float50"><label for="acl_editor_funding"><input type="checkbox" id="acl_editor_funding" name="acl_editor_funding" /><label for="acl_editor_funding"> <?php echo t('Edit').' '.t('Funding');?></label></div><label for="acl_editor_people_affiliations"><input type="checkbox" id="acl_editor_people_affiliations" name="acl_editor_people_affiliations"> <?php echo t('Edit').' '.t('Affiliations');?></label></div>
		<div class="fieldLabelThin"></div><div class="fieldInput"><div class="float50"><label for="acl_editor_recommended_topic"><input type="checkbox" id="acl_editor_recommended_topic" name="acl_editor_recommended_topic" /><label for="acl_editor_recommended_topic"> <?php echo t('Edit').' '.t('Recommended topic');?></label></div><label for="acl_editor_people_titles"><input type="checkbox" id="acl_editor_people_titles" name="acl_editor_people_titles"> <?php echo t('Edit').' '.t('Titles');?></label></div>
		<div class="fieldLabelThin"></div><div class="fieldInput"><div class="float50"><label for="acl_editor_nationalcurriculum"><input type="checkbox" id="acl_editor_nationalcurriculum" name="acl_editor_nationalcurriculum" /><label for="acl_editor_nationalcurriculum"> <?php echo t('Edit').' '.t('Nat. Curriculum');?></label></div><label for="acl_editor_people_suffix"><input type="checkbox" id="acl_editor_people_suffix" name="acl_editor_people_suffix"> <?php echo t('Edit').' '.t('Suffix');?></label></div>
		<div class="fieldLabelThin"></div><div class="fieldInput"><div class="float50"><label for="acl_editor_method"><input type="checkbox" id="acl_editor_method" name="acl_editor_method" /><label for="acl_editor_method"> <?php echo t('Edit').' '.t('Training Method');?></label></div><label for="acl_editor_people_active_trainer"><input type="checkbox" id="acl_editor_people_active_trainer" name="acl_editor_people_active_trainer"> <?php echo t('Edit').' '.t('Active Trainer');?></label></div>
		<div class="fieldLabelThin"></div><div class="fieldInput"><div class="float50"><label for="acl_editor_refresher_course"><input type="checkbox" id="acl_editor_refresher_course" name="acl_editor_refresher_course" /><label for="acl_editor_refresher_course"> <?php echo t('Edit').' '.t('Refresher Course');?></label></div></div>
		<div class="fieldLabelThin"></div><div class="fieldInput"><div class="float50"><label for="import_training"><input type="checkbox" id="import_training" name="import_training" /><label for="import_training"> <?php echo t('Import').' '.t('Training');?></label></div><label for="import_person"><input type="checkbox" id="import_person" name="import_person"> <?php echo t('Import').' '.t('Person');?></label></div>

		
		<br clear="all"/>
		<div class="fieldLabelThin"> <?php echo t('Facilities').'&nbsp;'.t('and').'&nbsp;'.t('Preservice'); ?></div><div class="fieldInput"><div class="float50"><label for="acl_editor_facility_types"><input type="checkbox" id="acl_editor_facility_types" name="acl_editor_facility_types" /><label for="acl_editor_facility_types"> <?php echo t('Edit').' '.t('Facility Types');?></label></div><label for="acl_editor_ps_classes"><input type="checkbox" id="acl_editor_ps_classes" name="acl_editor_ps_classes"> <?php echo t('Edit').' '.t('Classes');?></label></div>
		<div class="fieldLabelThin"></div><div class="fieldInput"><div class="float50"><label for="acl_editor_facility_sponsors"><input type="checkbox" id="acl_editor_facility_sponsors" name="acl_editor_facility_sponsors" /><label for="acl_editor_facility_sponsors"> <?php echo t('Edit').' '.t('Facility Sponsors');?></label></div><label for="acl_editor_ps_cadres"><input type="checkbox" id="acl_editor_ps_cadres" name="acl_editor_ps_cadres"> <?php echo t('Edit').' '.t('Cadres');?></label></div>
		<div class="fieldLabelThin"></div><div class="fieldInput"><div class="float50"><label for="import_facility"><input type="checkbox" id="import_facility" name="import_facility"> <?php echo t('Import').' '.t('Facility');?></label></div>	<label for="acl_editor_ps_degrees"><input type="checkbox" id="acl_editor_ps_degrees" name="acl_editor_ps_degrees"> <?php echo t('Edit').' '.t('Degrees');?></label></div>
		<div class="fieldLabelThin"></div><div class="fieldInput"><div class="float50"><label for="import_training_location"><input type="checkbox" id="import_training_location" name="import_training_location"> <?php echo t('Import').' '.t('Training Location');?></label></div>	<label for="acl_editor_ps_funding"><input type="checkbox" id="acl_editor_ps_funding" name="acl_editor_ps_funding"> <?php echo t('Edit').' '.t('Funding');?></label></div>
		<div class="fieldLabelThin"></div><div class="fieldInput"><div class="float50">&nbsp;</div>	<label for="acl_editor_ps_institutions"><input type="checkbox" id="acl_editor_ps_institutions" name="acl_editor_ps_institutions"> <?php echo t('Edit').' '.t('Institution Types');?></label></div>
		<div class="fieldLabelThin"></div><div class="fieldInput"><div class="float50">&nbsp;</div>	<label for="acl_editor_ps_languages"><input type="checkbox" id="acl_editor_ps_languages" name="acl_editor_ps_languages"> <?php echo t('Edit').' '.t('Languages');?></label></div>
		<div class="fieldLabelThin"></div><div class="fieldInput"><div class="float50">&nbsp;</div>	<label for="acl_editor_ps_nationalities"><input type="checkbox" id="acl_editor_ps_nationalities" name="acl_editor_ps_nationalities"> <?php echo t('Edit').' '.t('Nationalities');?></label></div>
		<div class="fieldLabelThin"></div><div class="fieldInput"><div class="float50">&nbsp;</div>	<label for="acl_editor_ps_joindropreasons"><input type="checkbox" id="acl_editor_ps_joindropreasons" name="acl_editor_ps_joindropreasons"> <?php echo t('Edit').' '.t('Join & drop reasons');?></label></div>
		<div class="fieldLabelThin"></div><div class="fieldInput"><div class="float50">&nbsp;</div>	<label for="acl_editor_ps_sponsors"><input type="checkbox" id="acl_editor_ps_sponsors" name="acl_editor_ps_sponsors"> <?php echo t('Edit').' '.t('Sponsors');?></label></div>
		<div class="fieldLabelThin"></div><div class="fieldInput"><div class="float50">&nbsp;</div>	<label for="acl_editor_ps_tutortypes"><input type="checkbox" id="acl_editor_ps_tutortypes" name="acl_editor_ps_tutortypes"> <?php echo t('Edit').' '.t('Tutor Types');?></label></div>
		<div class="fieldLabelThin"></div><div class="fieldInput"><div class="float50">&nbsp;</div>	<label for="acl_editor_ps_coursetypes"><input type="checkbox" id="acl_editor_ps_coursetypes" name="acl_editor_ps_coursetypes"> <?php echo t('Edit').' '.t('Course Types');?></label></div>
		<div class="fieldLabelThin"></div><div class="fieldInput"><div class="float50">&nbsp;</div>	<label for="acl_editor_ps_religions"><input type="checkbox" id="acl_editor_ps_religions" name="acl_editor_ps_religions"> <?php echo t('Edit').' '.t('Religious denominations');?></label></div>

		<br clear="all"/>

	</fieldset>

	<div class="fieldLabelThin" for="spacer"></div>
	<div class="fieldInput"><input type="checkbox" id="send_email" name="send_email"  CHECKED /><label for="send_email"> <?php tp('Send email with login information');?></label></div>
	<div class="fieldLabelThin" for="spacer"></div>
	<input type="submit" value="<?php tp('Next User');?>" title="save and continue" class="submitArrow"/>
	<div style="float:right;">&nbsp;</div>
	<button type="button" id="Finished" title="save this record" class="submitNoArrow" /><?php tp('Finished');?></button>
	<div class="clear"></div>

</form>
<script type="text/javascript">
addAjaxSubmit('Finished','userForm','<?php echo $this->base_url;?>/user/add/outputType/json');

$(document).ready(function () {
	$('#orgcheckall').click(function (e) {   /* check all btn  */
		e.preventDefault();
		$('#orgs input[name="training_organizer_option_id[]"]').attr('checked', 'checked');
		//TA:#415
		var mech_fields = YAHOO.util.Dom.get("mechanisms_box").getElementsByTagName('input');
		for(var i = 0; i < mech_fields.length; i++) {
			$(mech_fields[i]).parent().parent().parent().show();
		}			
	});
	$('#orguncheckall').click(function (e) { /* check none btn */
		e.preventDefault();
		$('#training_organizer_option_all,#orgs input[name="training_organizer_option_id[]"]').removeAttr('checked').removeAttr('readonly').removeAttr('disabled');
		//TA:#415
		var mech_fields = YAHOO.util.Dom.get("mechanisms_box").getElementsByTagName('input');
		for(var i = 0; i < mech_fields.length; i++) {
				$(mech_fields[i]).parent().parent().parent().hide();
				$(mech_fields[i]).attr('checked', false);
		}
	});

	//TA:#415
	$('#mechanismcheckall').click(function (e) {   /* check all btn  */
		e.preventDefault();
		var mech_fields = YAHOO.util.Dom.get("mechanisms_box").getElementsByTagName('input');
		for(var i = 0; i < mech_fields.length; i++) {
			if($(mech_fields[i]).is(':hidden')){
				mech_fields[i].checked = false;
			}else{
				mech_fields[i].checked = true;
			}
		}
	});
	$('#mechanismuncheckall').click(function (e) { /* check none btn */
		e.preventDefault();
		$('#mechanism_option_all,#mechanisms input[name="mechanism_option_id[]"]').removeAttr('checked').removeAttr('readonly').removeAttr('disabled');
	});
	///

	$('#edit_country_options').click(function (e) { /* edit country options checkbox (this is master admin) */
		$('#admin_box input[type="checkbox"]').attr('checked', $(this).is(':checked'));
	});

	$('#admin_select_all').click(function (e) {
		e.preventDefault();
		adminChecks(1);
	});
	$('#admin_select_none').click(function (e) {
		e.preventDefault();
		adminChecks(0);
	});

	//TA:#421
	if($('#employees_module').attr('checked')){
		$("#position_access").prop('disabled',false);
	}else{
		 $("#position_access").prop('disabled',true);
	}
	$('#employees_module').click(function (e) {
		if($('#employees_module').attr('checked')){
			$("#position_access").prop('disabled',false);
		}else{
			 $("#position_access").prop('disabled',true);
			 $("#position_access").prop('checked',false);
		}
	})	
	///
});

function toggleinstitution(sender){
	if (sender.checked){
		$(".institutioncheck").prop('checked',true);
		$(".institutioncheck").prop('disabled',true);
	} else {
		$(".institutioncheck").prop('disabled',false);
	}
}
</script>
<div class="clear"></div>