<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title><?php echo $this->translation['Application Name'];?> | <?php tp('Login');?></title>
<?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>

</head>
<body class="yui-skin-sam">

<div id="pageHolder">

  <div id="header"><?php require_once('views/scripts/header.phtml');?></div>
  <div id="content">
  <?php if ( !$this->complete ) { ?>
     <h1><?php tp('Forgot Password');?></h1>
    <div class="clear"></div>
    <form action=""  method="POST">
    	<?php tp('Enter your email address, and a new temporary password will be sent to you.');?><br/><br/>
 	  <div class="fieldLabel"  id="email_lbl"><?php tp('E-mail');?></div>
	  <div class="fieldInput"><input type="text" name="email" size="32" maxlength="32" value="<?php echo $this->user['email'];?>"/></div>
		<div class="fieldLabel" for="spacer"></div>
      <input type="submit" name="send" value="<?php tp('Send Password');?>" title="get new password" class="submitArrow"/>
  	</form>
  <?php } ?>
<div class="clear"></div>
  </div>
  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>

</div>

</body>
</html>