<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title><?php echo $this->translation['Application Name'];?> | <?php tp('Add Facility');?></title>
<?php
require_once('views/helpers/ScriptContainer.php');

require_once('views/helpers/Location.php');
require_once('views/helpers/TrainingViewHelper.php');
require_once('views/helpers/FormHelper.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>

</head>
<body class="yui-skin-sam">
<div id="pageHolder">
  <div id="header"><?php require_once('views/scripts/preheader.phtml');?></div>
  <div id="content">

		<h1><?php tp('Add new Facility');?></h1>

		<form id="edit" action="" method="post">

		<?php require_once('addfacility-form.phtml');?>
		<div class="clear" ></div>
		<button type="button" id="submitFacility"><?php tp('Add Facility');?></button><br>
		<script type="text/javascript">
			addAjaxSubmit('submitFacility','edit','<?php echo $this->base_url;?>/facility/add/outputType/json');
		</script>
		</form>
		<div class="clear" ></div>

  </div>
  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
</div>

</body>
</html>