<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title><?php echo $this->translation['Application Name'];?></title>
<?php
require_once('views/helpers/Location.php');
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>
     
</head>
<body class="yui-skin-sam"  >

<div id="pageHolder">

  <div id="header"><?php require_once('views/scripts/preheader.phtml');?></div>
  <div id="content">

    <h1><?php tp('Search Facilities');?></h1>
	   <form action="" method="get">
   <fieldset><legend><?php tp('Select Criteria');?></legend>

	<div class="fieldLabel"><?php tp('Facility Name');?></div>
	<div class="fieldInput"><select id="facility_name" name="facility_name">
		<option value="">--<?php tp('All');?>--</option>
		<?php
			foreach ( $this->facility_names as $vals ) {
				echo '<option value="'.htmlspecialchars($vals['facility_name']).'" '.((@$this->criteria['facility_name']) == $vals['facility_name']? 'SELECTED':'').' >'.$vals['facility_name'].'</option>';
		}
		?>
	</select></div>

	<div class="fieldLabel" id="province_id_lbl"><?php echo (@$this->translation['Region A (Province)']); ?></div>
	<div class="fieldInput"><?php renderFilter($this->locations, 1, 'province_id', $this->criteria['province_id'], 'district_id');?></div>
  <?php if ( $this->setting['display_region_b'] ) { ?>
	<div class="fieldLabel" id="district_id_lbl"><?php echo (@$this->translation['Region B (Health District)']); ?></div>
	<div class="fieldInput"><?php renderFilter($this->locations, 2, 'district_id', $this->criteria['district_id'], ($this->setting['display_region_c']?'region_c_id':false));?></div>
	<?php } ?>
  <?php if ( $this->setting['display_region_c'] ) { ?>
  <div class="fieldLabel" id="region_c_id_lbl"><?php echo (@$this->translation['Region C (Local Region)']); ?></div>
  <div class="fieldInput"><?php renderFilter($this->locations, 3, 'region_c_id', $this->criteria['region_c_id'], false);?></div>
  <?php } ?>
  
  <!-- TA:17: 09/04/2014 START-->
<?php if($this->setting['display_facility_type']){?>
	<div class="fieldLabel" id="type_id_lbl"><?php tp('Facility Type');?></div>
	<div class="fieldInput">
	<select id="type_id" name="type_id" >
		<option value="">--<?php tp('All');?>--</option>
		<?php
			foreach ( $this->facility_types as $vals ) {
				echo '<option value="'.$vals['id'].'" '.((@$this->criteria['type_id']) == $vals['id']? 'SELECTED':'').' >'.$vals['facility_type_phrase'].'</option>';
		}
		?>
	</select></div>
	<?php }?>
	
	<div class="fieldLabel" id="sponsor_id_lbl"><?php tp('Facility Sponsor');?></div>
	<div class="fieldInput">
	<select id="sponsor_id" name="sponsor_id" >
		<option value="">--<?php tp('All');?>--</option>
		<?php
			foreach ( $this->facility_sponsors as $vals ) {
				echo '<option value="'.$vals['id'].'" '.((@$this->criteria['sponsor_id']) == $vals['id']? 'SELECTED':'').' >'.$vals['facility_sponsor_phrase'].'</option>';
		}
		?>
	</select></div>

	<div class="clear"></div>
	<input type="hidden" name="limit" id="limit" value="1" />
    <input type="submit" class="submitNoArrow" name="go" value="<?php tp('Preview');?>" />
   </fieldset>
   </form>
<?php if ( $this->criteria['go'] ) { ?>
		    <div class="hrGrey"></div>
		    <div class="fieldIndentNoMargin"><?php tp('Facilities');?> <span class="total"><?php echo $this->count;?>  <?php tp('Results');?></span><?php echo $this->printAndExport();?></div>
			<a href="<?php echo $this->base_url;?>/facility/add"><?php tp('Add New Facility');?></a><br/><br/>
		    <div id="facilities"></div>
		    <script type="text/javascript">
		var facilitiesData = [
		<?php
		$cnt = 0;
		 	$isFirstRow = true;
			foreach($this->results as $row) {
				if ( (isset($_REQUEST['limit']) AND !$_REQUEST['limit'])  or ($cnt < 100) ) {
				if (!$isFirstRow )
					echo ',';
				$isFirstRow = false;
				echo '['.'"'.$row['id'].'","'.str_replace('\\','',$row['facility_name']).'","'.$row['province_name'].'","'.($this->setting['display_region_b']?$row['district_name'].'","':'').($this->setting['display_region_c']?$row['region_c_name'].'","':'').$row['facility_type_phrase'].'","'.$row['facility_sponsor_phrase'].'"]';
				$cnt++;
			}
			}
		   ?>];

		   var formatViewUrl = function(elCell, oRecord, oColumn, sData) {
			if ( (sData == null) || (sData.length == 0) )
				sData = '&nbsp;&nbsp;&nbsp;';
		    elCell.innerHTML = "<a href='<?php echo $this->base_url;?>/facility/view/id/" + oRecord.getData("id") + "' >" + sData + "</a>";
		}

		var facilitiesColumnDefs = [
			{key:"id", label: "<?php tp("ID");?>", sortable:false, resizable:false,
			                formatter: formatViewUrl},
		    {key:"facility_name", label: "<?php tp('Facility Name');?>", sortable:true, resizeable:true},
		    {key:"province_name", label: "<?php echo (@$this->translation['Region A (Province)']); ?>", sortable:true, resizeable:true},
<?php if ( $this->setting['display_region_b'] ) { ?>
		    {key:"district_name", label: "<?php echo (@$this->translation['Region B (Health District)']); ?>", sortable:true, resizeable:true},
<?php } ?>
<?php if ( $this->setting['display_region_c'] ) { ?>
        {key:"region_c_name", label: "<?php echo (@$this->translation['Region C (Local Region)']); ?>", sortable:true, resizeable:true},
<?php } ?>
<?php if($this->setting['display_facility_type']){?> //TA:17: 09/04/2014
		    {key:"facility_type_phrase", label: "<?php tp('Type');?>", sortable:true, resizeable:true},
		    <?php }?>
		    {key:"facility_sponsor_phrase", label: "<?php tp('Sponsor');?>", sortable:true, resizeable:true}
		];

			makeDataTable("facilities", null, facilitiesData, facilitiesColumnDefs);
		</script>
		<?php if ($cnt < count($this->results)) { ?>
		[<?php tp('Limited to 100 rows');?>]  <a href="<?php echo str_replace('limit=1','limit=0',$_SERVER['REQUEST_URI']);?>"><?php tp('Full Results');?></a>
		<?php } ?>
<?php } ?>
  </div>
  </div>
  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>


</div>

</body>
</html>