<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title><?php echo $this->translation['Application Name'];?> | <?php tp('View Facility');?></title>
<?php
require_once('views/helpers/ScriptContainer.php');
require_once('views/helpers/TrainingViewHelper.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>

</head>
<body class="yui-skin-sam">
<div id="pageHolder">
  <div id="header"><?php require_once('views/scripts/preheader.phtml');?></div>
  <div id="content">

<h1><?php tp('View Facility');?></h1>

<div style="height: 600px;">
	<form id="change" action="<?php echo $this->base_url;?>/facility/view" method="GET">
	<div class="fieldInput"><select name="id"  id="id" onchange="this.form.submit();">
	<option value="">-- <?php tp('choose');?> --</option>
	<?php foreach ( $this->facilities as $facility) {
		echo '<option value="'.($facility['id']).'" '.((@$this->facility['id']) == $facility['id']? 'SELECTED':'').' >'.($facility['facility_name']).'</option>';
	}
	?>
	}
	</select><?php if ($this->facility['id'] and $this->hasACL('edit_people')) { ?><a href="<?php echo $this->base_url;?>/facility/edit/id/<?php echo $this->facility['id'];?>" >Edit</a><?php } ?>
	</div>
	</form>

<?php if ($this->facility['id']) { ?>
	<input type="hidden" name="id" value="<?php echo $this->facility['id'];?>"></input>
	<div class="fieldLabel" id="facility_address1_lbl"><?php tp('Address 1');?></div>
	  <div class="fieldInput"><input type="text" name="facility_address1" id="facility_address1" readonly="readonly"  value="<?php echo $this->facility['address_1'];?>" size="40" maxlength="40"/></div>
	<div class="fieldLabel" id="facility_address2_lbl"><?php tp('Address 2');?></div>
	  <div class="fieldInput"><input type="text" name="facility_address2" id="facility_address2" readonly="readonly"  value="<?php echo $this->facility['address_2'];?>" size="40" maxlength="40"/></div>
	<div class="fieldLabel" id="facility_city_lbl"><?php echo (@$this->translation['City or Town']); ?></div>
	    <div class="fieldInput"><input name="facility_city" id="facility_city" type="text" size="40" readonly="readonly"  maxlength="128" value="<?php echo $this->facility['facility_city'];?>" />
	</div>
	<div class="fieldLabel" id="facility_district_id_lbl"><?php echo (@$this->translation['Region B (Health District)']); ?></div>
	<div class="fieldInput"><input type="text" readonly="readonly" id="facility_district_id" name="facility_district_id" value="<?php
		foreach ( $this->districts as $vals ) {
			if ((@$this->facility['district_id']) == $vals['id']) echo $vals['district_name'];
		}
		?>" />
	</select></div>
	<div class="fieldLabel" id="facility_province_id_lbl"><?php echo (@$this->translation['Region A (Province)']); ?></div>
	<div class="fieldInput"><input type="text" readonly="readonly" id="facility_province_id" name="facility_province_id" value="<?php
		foreach ( $this->provinces as $vals ) {
			if ((@$this->facility['province_id']) == $vals['id']) echo $vals['province_name'];
		}
		?>" /></div>
	<div class="fieldLabel" id="facility_postal_code_lbl"><?php tp('Postal Code');?></div>
	  <div class="fieldInput"><input type="text" name="facility_postal_code" readonly="readonly"  id="facility_postal_code" value="<?php echo $this->facility['postal_code'];?>" size="40" maxlength="40"/></div>
	<div class="fieldLabel" id="facility_phone_lbl"><?php tp('Phone');?></div>
	  <div class="fieldInput"><input type="text" name="facility_phone" readonly="readonly"  id="facility_phone" value="<?php echo $this->facility['phone'];?>" size="40" maxlength="40"/></div>
	<div class="fieldLabel" id="facility_fax_lbl"><?php tp('Fax');?></div>
	  <div class="fieldInput"><input type="text" name="facility_fax"  readonly="readonly" id="facility_fax" value="<?php echo $this->facility['fax'];?>" size="40" maxlength="40"/></div>
	<div class="fieldLabel" id="facility_type_id_lbl"><?php tp('Facility type');?></div>
	<div class="fieldInput"><input type="text" readonly="readonly" id="facility_type_id" name="facility_type_id" value="<?php
		foreach ( $this->facility_types as $vals ) {
			if ((@$this->facility['type_option_id']) == $vals['id']) echo $vals['facility_type_phrase'];
		}
		?>" /></div>
	<div class="fieldLabel" id="facility_sponsor_id_lbl"><?php tp('Facility sponsor');?></div>
	<div class="fieldInput">
	<input type="text" readonly="readonly" id="facility_sponsor_id" name="facility_sponsor_id" value="<?php
		foreach ( $this->facility_sponsors as $vals ) {
			if ((@$this->facility['sponsor_option_id']) == $vals['id']) echo $vals['facility_sponsor_phrase'];
		}
		?>" /></div>
	<div class="fieldLabel" id="facility_comments_lbl"><?php tp('Comments');?></div>
	<div class="fieldInput"><textarea name="facility_comments" readonly="readonly"  id="facility_comments" size="40" maxlength="40" ><?php echo $this->facility['facility_comments'];?></textarea></div>
<?php } ?>

</div>
  </div>
  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
</div>

</body>
</html>
