<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title><?php echo $this->translation['Application Name'];?> | <?php tp('Competencies');?></title>


<?php
require_once('views/helpers/Location.php');
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>
<script type="text/javascript">
var vwvls=new Array();
function SetAll() {
<?php
if(isset($this->vwvls[0]))
{
	$lscntr=0;
	foreach ( $this->vwvls as $ys => $ls ) {
	 echo 'vwvls['.$lscntr.']="'.$ls.'";';
	 $lscntr++;
	}
}
?>
var i;
for(i=0;i<vwvls.length;i++)
{
if(vwvls[i].indexOf("240")==0)
{
document.getElementById('grp240').value=vwvls[i].substr(3);
}
else
{
document.getElementById('grp'+vwvls[i].toLowerCase()).checked=true;
}
}
}
</script>
</head>
<body  class="yui-skin-sam" onload="SetAll()">
<div id="pageHolder">
<div id="header"><?php require_once('views/scripts/header.phtml');?></div>
<div id="content">
<h1><?php echo t('Add/Edit Competency'); ?></h1>
<div style="height:54px">
<div style="width:486px;text-align:left;float:right">
<div><b>A</b> - <?php echo t('fully competent and confident; able to teach others (mentor'); ?>)</div>
<div><b>B</b> - <?php echo t('fully competent; not able to teach others (not able to be a mentor'); ?>)</div>
<div><b>C</b> - <?php echo t('capable'); ?></div>
<div><b>D</b> - <?php echo t('not capable'); ?></div>
<div><b>E</b> - <?php echo t('not currently in my job description/duties'); ?></div>
</div>
</div>
<form action="" id="personCompForm" method="post">
<div style="height:12px"></div>
<div class="nwtxthead"><?php echo t('Adult HIV Care'); ?></div>
<table cellpadding="0" cellspacing="0" border="0" style="width:100%;border:solid 1px #AAA">
<tr>
<td colspan="7">
 <div class="nwtxtbig"><?php echo t('Clinical competency tasks'); ?></div>
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxtbig"><?php echo t('Do you feel competent and confident to ...'); ?></div>
</td>
<td style="width:5%;text-align:center">
 <div class="nwtxtbig">A</div>
</td>
<td style="width:5%;text-align:center">
 <div class="nwtxtbig">B</div>
</td>
<td style="width:5%;text-align:center">
 <div class="nwtxtbig">C</div>
</td>
<td style="width:5%;text-align:center">
 <div class="nwtxtbig">D</div>
</td>
<td style="width:5%;text-align:center">
 <div class="nwtxtbig">E</div>
</td>
<td style="width:7%;text-align:center">
 <div class="nwtxtbig"><?php echo t('No Answer'); ?></div>
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">1)&nbsp;&nbsp;&nbsp;Take an appropriate history of all patients?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp1a" value="A" name="grp1" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp1b" value="B" name="grp1" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp1c" value="C" name="grp1" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp1d" value="D" name="grp1" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp1e" value="E" name="grp1" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp1f" value="F" name="grp1" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">2)&nbsp;&nbsp;&nbsp;Provide patients with HIV counseling and screening tests?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp2a" value="A" name="grp2" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp2b" value="B" name="grp2" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp2c" value="C" name="grp2" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp2d" value="D" name="grp2" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp2e" value="E" name="grp2" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp2f" value="F" name="grp2" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">3)&nbsp;&nbsp;&nbsp;Provide patients with opt-out HIV testing?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp3a" value="A" name="grp3" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp3b" value="B" name="grp3" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp3c" value="C" name="grp3" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp3d" value="D" name="grp3" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp3e" value="E" name="grp3" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp3f" value="F" name="grp3" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">4)&nbsp;&nbsp;&nbsp;Advise HIV positive patients to encourage partners and children to test?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp4a" value="A" name="grp4" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp4b" value="B" name="grp4" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp4c" value="C" name="grp4" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp4d" value="D" name="grp4" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp4e" value="E" name="grp4" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp4f" value="F" name="grp4" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">5)&nbsp;&nbsp;&nbsp;Screen for and manage HIV and AIDS opportunistic infections?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp5a" value="A" name="grp5" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp5b" value="B" name="grp5" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp5c" value="C" name="grp5" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp5d" value="D" name="grp5" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp5e" value="E" name="grp5" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp5f" value="F" name="grp5" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">6)&nbsp;&nbsp;&nbsp;Identify patients eligible for treatment using SA criteria for eligibility?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp6a" value="A" name="grp6" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp6b" value="B" name="grp6" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp6c" value="C" name="grp6" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp6d" value="D" name="grp6" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp6e" value="E" name="grp6" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp6f" value="F" name="grp6" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">7)&nbsp;&nbsp;&nbsp;Discuss chronic or other medication including possible drug interactions?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp7a" value="A" name="grp7" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp7b" value="B" name="grp7" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp7c" value="C" name="grp7" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp7d" value="D" name="grp7" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp7e" value="E" name="grp7" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp7f" value="F" name="grp7" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">8)&nbsp;&nbsp;&nbsp;Prescribe ARVs to HIV positive patients?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp8a" value="A" name="grp8" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp8b" value="B" name="grp8" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp8c" value="C" name="grp8" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp8d" value="D" name="grp8" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp8e" value="E" name="grp8" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp8f" value="F" name="grp8" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">9)&nbsp;&nbsp;&nbsp;Provide follow up for patients on ART?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp9a" value="A" name="grp9" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp9b" value="B" name="grp9" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp9c" value="C" name="grp9" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp9d" value="D" name="grp9" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp9e" value="E" name="grp9" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp9f" value="F" name="grp9" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">10)&nbsp;&nbsp;Provide family planning for HIV positive patients?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp10a" value="A" name="grp10" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp10b" value="B" name="grp10" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp10c" value="C" name="grp10" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp10d" value="D" name="grp10" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp10e" value="E" name="grp10" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp10f" value="F" name="grp10" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">11)&nbsp;&nbsp;Discuss rights and access for HIV positive patients?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp11a" value="A" name="grp11" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp11b" value="B" name="grp11" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp11c" value="C" name="grp11" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp11d" value="D" name="grp11" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp11e" value="E" name="grp11" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp11f" value="F" name="grp11" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">12)&nbsp;&nbsp;Initiate and manage support groups?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp12a" value="A" name="grp12" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp12b" value="B" name="grp12" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp12c" value="C" name="grp12" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp12d" value="D" name="grp12" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp12e" value="E" name="grp12" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp12f" value="F" name="grp12" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">13)&nbsp;&nbsp;Treat the common ART side effects in patients?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp13a" value="A" name="grp13" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp13b" value="B" name="grp13" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp13c" value="C" name="grp13" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp13d" value="D" name="grp13" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp13e" value="E" name="grp13" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp13f" value="F" name="grp13" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">14)&nbsp;&nbsp;Screen for and treat HIV positive patients with TB and HBV co-infection?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp14a" value="A" name="grp14" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp14b" value="B" name="grp14" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp14c" value="C" name="grp14" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp14d" value="D" name="grp14" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp14e" value="E" name="grp14" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp14f" value="F" name="grp14" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">15)&nbsp;&nbsp;Identify and treat patients with clinical depression?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp15a" value="A" name="grp15" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp15b" value="B" name="grp15" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp15c" value="C" name="grp15" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp15d" value="D" name="grp15" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp15e" value="E" name="grp15" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp15f" value="F" name="grp15" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">16)&nbsp;&nbsp;Provide mentorship support for lay counselors?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp16a" value="A" name="grp16" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp16b" value="B" name="grp16" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp16c" value="C" name="grp16" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp16d" value="D" name="grp16" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp16e" value="E" name="grp16" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp16f" value="F" name="grp16" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">17)&nbsp;&nbsp;Provide mentorship support for nursing staff?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp17a" value="A" name="grp17" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp17b" value="B" name="grp17" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp17c" value="C" name="grp17" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp17d" value="D" name="grp17" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp17e" value="E" name="grp17" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp17f" value="F" name="grp17" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">18)&nbsp;&nbsp;Provide the correct level of referral for treatment when required?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp18a" value="A" name="grp18" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp18b" value="B" name="grp18" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp18c" value="C" name="grp18" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp18d" value="D" name="grp18" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp18e" value="E" name="grp18" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp18f" value="F" name="grp18" />
</td>
</tr>
</table>
<div style="height:20px"></div>
<div class="nwtxthead"><?php echo t('Pediatric HIV Care'); ?></div>
<table cellpadding="0" cellspacing="0" border="0" style="width:100%;border:solid 1px #AAA">
<tr>
<td colspan="7">
 <div class="nwtxtbig"><?php echo t('Clinical competency tasks'); ?></div>
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxtbig"><?php echo t('Do you feel competent and confident to ...'); ?></div>
</td>
<td style="width:5%;text-align:center">
 <div class="nwtxtbig">A</div>
</td>
<td style="width:5%;text-align:center">
 <div class="nwtxtbig">B</div>
</td>
<td style="width:5%;text-align:center">
 <div class="nwtxtbig">C</div>
</td>
<td style="width:5%;text-align:center">
 <div class="nwtxtbig">D</div>
</td>
<td style="width:5%;text-align:center">
 <div class="nwtxtbig">E</div>
</td>
<td style="width:7%;text-align:center">
 <div class="nwtxtbig"><?php echo t('No Answer'); ?></div>
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">1)&nbsp;&nbsp;&nbsp;Correctly diagnose, classify, and treat HIV positive infants and children?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp01a" value="A" name="grp01" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp01b" value="B" name="grp01" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp01c" value="C" name="grp01" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp01d" value="D" name="grp01" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp01e" value="E" name="grp01" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp01f" value="F" name="grp01" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">2)&nbsp;&nbsp;&nbsp;Treat ARV side effects in children?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp02a" value="A" name="grp02" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp02b" value="B" name="grp02" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp02c" value="C" name="grp02" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp02d" value="D" name="grp02" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp02e" value="E" name="grp02" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp02f" value="F" name="grp02" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">3)&nbsp;&nbsp;&nbsp;Correctly treat an HIV positive child with TB and on ARV therapy?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp03a" value="A" name="grp03" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp03b" value="B" name="grp03" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp03c" value="C" name="grp03" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp03d" value="D" name="grp03" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp03e" value="E" name="grp03" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp03f" value="F" name="grp03" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">4)&nbsp;&nbsp;&nbsp;Provide counseling for HIV positive children and their caregivers?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp04a" value="A" name="grp04" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp04b" value="B" name="grp04" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp04c" value="C" name="grp04" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp04d" value="D" name="grp04" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp04e" value="E" name="grp04" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp04f" value="F" name="grp04" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">5)&nbsp;&nbsp;&nbsp;Monitor the nutritional status of HIV positive children?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp05a" value="A" name="grp05" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp05b" value="B" name="grp05" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp05c" value="C" name="grp05" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp05d" value="D" name="grp05" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp05e" value="E" name="grp05" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp05f" value="F" name="grp05" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">6)&nbsp;&nbsp;&nbsp;Explain the importance of ARV adherence to HIV positive children and their caregivers?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp06a" value="A" name="grp06" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp06b" value="B" name="grp06" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp06c" value="C" name="grp06" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp06d" value="D" name="grp06" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp06e" value="E" name="grp06" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp06f" value="F" name="grp06" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">7)&nbsp;&nbsp;&nbsp;Follow up with HIV positive children who miss their appointments?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp08a" value="A" name="grp08" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp08b" value="B" name="grp08" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp08c" value="C" name="grp08" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp08d" value="D" name="grp08" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp08e" value="E" name="grp08" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp08f" value="F" name="grp08" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">8)&nbsp;&nbsp;&nbsp;Provide the correct level of referral for treatment when required?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp09a" value="A" name="grp09" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp09b" value="B" name="grp09" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp09c" value="C" name="grp09" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp09d" value="D" name="grp09" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp09e" value="E" name="grp09" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp09f" value="F" name="grp09" />
</td>
</tr>
</table>
<div style="height:20px"></div>
<div class="nwtxthead"><?php echo t('Tuberculosis'); ?></div>
<table cellpadding="0" cellspacing="0" border="0" style="width:100%;border:solid 1px #AAA">
<tr>
<td colspan="7">
 <div class="nwtxtbig"><?php echo t('Clinical competency tasks'); ?></div>
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxtbig"><?php echo t('Do you feel competent and confident to ...'); ?></div>
</td>
<td style="width:5%;text-align:center">
 <div class="nwtxtbig">A</div>
</td>
<td style="width:5%;text-align:center">
 <div class="nwtxtbig">B</div>
</td>
<td style="width:5%;text-align:center">
 <div class="nwtxtbig">C</div>
</td>
<td style="width:5%;text-align:center">
 <div class="nwtxtbig">D</div>
</td>
<td style="width:5%;text-align:center">
 <div class="nwtxtbig">E</div>
</td>
<td style="width:7%;text-align:center">
 <div class="nwtxtbig"><?php echo t('No Answer'); ?></div>
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">1)&nbsp;&nbsp;&nbsp;Recognise and correctly diagnose TB in patients?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp31a" value="A" name="grp31" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp31b" value="B" name="grp31" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp31c" value="C" name="grp31" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp31d" value="D" name="grp31" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp31e" value="E" name="grp31" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp31f" value="F" name="grp31" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">2)&nbsp;&nbsp;&nbsp;Screen for HIV in TB infected patients?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp32a" value="A" name="grp32" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp32b" value="B" name="grp32" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp32c" value="C" name="grp32" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp32d" value="D" name="grp32" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp32e" value="E" name="grp32" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp32f" value="F" name="grp32" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">3)&nbsp;&nbsp;&nbsp;Initiate and manage all patients with TB?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp33a" value="A" name="grp33" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp33b" value="B" name="grp33" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp33c" value="C" name="grp33" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp33d" value="D" name="grp33" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp33e" value="E" name="grp33" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp33f" value="F" name="grp33" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">4)&nbsp;&nbsp;&nbsp;Follow up with smear negative patients?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp34a" value="A" name="grp34" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp34b" value="B" name="grp34" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp34c" value="C" name="grp34" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp34d" value="D" name="grp34" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp34e" value="E" name="grp34" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp34f" value="F" name="grp34" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">5)&nbsp;&nbsp;&nbsp;Manage MDR and XDR in co-infected patients?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp35a" value="A" name="grp35" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp35b" value="B" name="grp35" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp35c" value="C" name="grp35" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp35d" value="D" name="grp35" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp35e" value="E" name="grp35" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp35f" value="F" name="grp35" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">6)&nbsp;&nbsp;&nbsp;Manage common ART side effects in TB patients?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp36a" value="A" name="grp36" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp36b" value="B" name="grp36" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp36c" value="C" name="grp36" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp36d" value="D" name="grp36" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp36e" value="E" name="grp36" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp36f" value="F" name="grp36" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">7)&nbsp;&nbsp;&nbsp;Provide the correct level of referral for treatment when required?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp37a" value="A" name="grp37" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp37b" value="B" name="grp37" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp37c" value="C" name="grp37" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp37d" value="D" name="grp37" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp37e" value="E" name="grp37" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp37f" value="F" name="grp37" />
</td>
</tr>
</table>
<div style="height:20px"></div>
<div class="nwtxthead"><?php echo t('STIs'); ?></div>
<table cellpadding="0" cellspacing="0" border="0" style="width:100%;border:solid 1px #AAA">
<tr>
<td colspan="7">
 <div class="nwtxtbig"><?php echo t('Clinical competency tasks'); ?></div>
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxtbig"><?php echo t('Do you feel competent and confident to ...'); ?></div>
</td>
<td style="width:5%;text-align:center">
 <div class="nwtxtbig">A</div>
</td>
<td style="width:5%;text-align:center">
 <div class="nwtxtbig">B</div>
</td>
<td style="width:5%;text-align:center">
 <div class="nwtxtbig">C</div>
</td>
<td style="width:5%;text-align:center">
 <div class="nwtxtbig">D</div>
</td>
<td style="width:5%;text-align:center">
 <div class="nwtxtbig">E</div>
</td>
<td style="width:7%;text-align:center">
 <div class="nwtxtbig"><?php echo t('No Answer'); ?></div>
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">1)&nbsp;&nbsp;&nbsp;Recognise and correctly diagnose and manage STIs in patients syndromically?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp41a" value="A" name="grp41" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp41b" value="B" name="grp41" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp41c" value="C" name="grp41" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp41d" value="D" name="grp41" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp41e" value="E" name="grp41" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp41f" value="F" name="grp41" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">2)&nbsp;&nbsp;&nbsp;Manage patients with positive syphilis results?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp42a" value="A" name="grp42" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp42b" value="B" name="grp42" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp42c" value="C" name="grp42" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp42d" value="D" name="grp42" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp42e" value="E" name="grp42" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp42f" value="F" name="grp42" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">3)&nbsp;&nbsp;&nbsp;Follow up with patients who do not show up for appointments?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp43a" value="A" name="grp43" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp43b" value="B" name="grp43" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp43c" value="C" name="grp43" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp43d" value="D" name="grp43" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp43e" value="E" name="grp43" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp43f" value="F" name="grp43" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">4)&nbsp;&nbsp;&nbsp;Provide the correct level of referral for treatment when required?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp44a" value="A" name="grp44" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp44b" value="B" name="grp44" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp44c" value="C" name="grp44" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp44d" value="D" name="grp44" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp44e" value="E" name="grp44" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp44f" value="F" name="grp44" />
</td>
</tr>
</table>
<div style="height:20px"></div>
<div class="nwtxthead"><?php echo t('PMTCT'); ?></div>
<table cellpadding="0" cellspacing="0" border="0" style="width:100%;border:solid 1px #AAA">
<tr>
<td colspan="7">
 <div class="nwtxtbig"><?php echo t('Clinical competency tasks'); ?></div>
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxtbig"><?php echo t('Do you feel competent and confident to ...'); ?></div>
</td>
<td style="width:5%;text-align:center">
 <div class="nwtxtbig">A</div>
</td>
<td style="width:5%;text-align:center">
 <div class="nwtxtbig">B</div>
</td>
<td style="width:5%;text-align:center">
 <div class="nwtxtbig">C</div>
</td>
<td style="width:5%;text-align:center">
 <div class="nwtxtbig">D</div>
</td>
<td style="width:5%;text-align:center">
 <div class="nwtxtbig">E</div>
</td>
<td style="width:7%;text-align:center">
 <div class="nwtxtbig"><?php echo t('No Answer'); ?></div>
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">1)&nbsp;&nbsp;&nbsp;Treat HIV positive pregnant women?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp51a" value="A" name="grp51" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp51b" value="B" name="grp51" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp51c" value="C" name="grp51" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp51d" value="D" name="grp51" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp51e" value="E" name="grp51" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp51f" value="F" name="grp51" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">2)&nbsp;&nbsp;&nbsp;Initiate ART prophylaxis and treatment for HIV positive women during pregnancy, labour and postnatal periods using the 2010 protocols?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp52a" value="A" name="grp52" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp52b" value="B" name="grp52" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp52c" value="C" name="grp52" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp52d" value="D" name="grp52" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp52e" value="E" name="grp52" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp52f" value="F" name="grp52" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">3)&nbsp;&nbsp;&nbsp;Recognise and treat common ART side effects in HIV positive pregnant women?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp53a" value="A" name="grp53" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp53b" value="B" name="grp53" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp53c" value="C" name="grp53" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp53d" value="D" name="grp53" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp53e" value="E" name="grp53" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp53f" value="F" name="grp53" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">4)&nbsp;&nbsp;&nbsp;Provide counseling on contraceptives, emergency pill and dual protection information for HIV positive women?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp54a" value="A" name="grp54" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp54b" value="B" name="grp54" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp54c" value="C" name="grp54" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp54d" value="D" name="grp54" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp54e" value="E" name="grp54" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp54f" value="F" name="grp54" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">5)&nbsp;&nbsp;&nbsp;Provide counseling on and termination of unwanted pregnancies according to guidelines?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp55a" value="A" name="grp55" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp55b" value="B" name="grp55" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp55c" value="C" name="grp55" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp55d" value="D" name="grp55" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp55e" value="E" name="grp55" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp55f" value="F" name="grp55" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">6)&nbsp;&nbsp;&nbsp;Correctly treat HIV positive pregnant and lactating women with TB/HBV infection who are also on ART?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp56a" value="A" name="grp56" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp56b" value="B" name="grp56" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp56c" value="C" name="grp56" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp56d" value="D" name="grp56" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp56e" value="E" name="grp56" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp56f" value="F" name="grp56" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">7)&nbsp;&nbsp;&nbsp;Follow up with HIV positive pregnant women who miss their appointments?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp57a" value="A" name="grp57" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp57b" value="B" name="grp57" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp57c" value="C" name="grp57" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp57d" value="D" name="grp57" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp57e" value="E" name="grp57" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp57f" value="F" name="grp57" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">8)&nbsp;&nbsp;&nbsp;Provide the correct level of referral for treatment when required?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp58a" value="A" name="grp58" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp58b" value="B" name="grp58" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp58c" value="C" name="grp58" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp58d" value="D" name="grp58" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp58e" value="E" name="grp58" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp58f" value="F" name="grp58" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">9)&nbsp;&nbsp;&nbsp;Promote, monitor and support safe infant feeding?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp59a" value="A" name="grp59" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp59b" value="B" name="grp59" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp59c" value="C" name="grp59" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp59d" value="D" name="grp59" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp59e" value="E" name="grp59" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp59f" value="F" name="grp59" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">10)&nbsp;&nbsp;Promote childhood immunisation?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp510a" value="A" name="grp510" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp510b" value="B" name="grp510" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp510c" value="C" name="grp510" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp510d" value="D" name="grp510" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp510e" value="E" name="grp510" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp510f" value="F" name="grp510" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">11)&nbsp;&nbsp;Provide Basic Antenatal Care (BANC) using integrated BANC/HIV checklists?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp511a" value="A" name="grp511" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp511b" value="B" name="grp511" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp511c" value="C" name="grp511" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp511d" value="D" name="grp511" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp511e" value="E" name="grp511" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp511f" value="F" name="grp511" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">12)&nbsp;&nbsp;Manage labour according to the modified obstetrical practices?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp512a" value="A" name="grp512" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp512b" value="B" name="grp512" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp512c" value="C" name="grp512" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp512d" value="D" name="grp512" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp512e" value="E" name="grp512" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp512f" value="F" name="grp512" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">13)&nbsp;&nbsp;Collect DBS -PCR specimen from exposed infants?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp513a" value="A" name="grp513" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp513b" value="B" name="grp513" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp513c" value="C" name="grp513" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp513d" value="D" name="grp513" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp513e" value="E" name="grp513" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp513f" value="F" name="grp513" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">14)&nbsp;&nbsp;Initiate infants eligible for ART?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp514a" value="A" name="grp514" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp514b" value="B" name="grp514" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp514c" value="C" name="grp514" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp514d" value="D" name="grp514" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp514e" value="E" name="grp514" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp514f" value="F" name="grp514" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">15)&nbsp;&nbsp;Provide maternal nutritional counseling and support?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp515a" value="A" name="grp515" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp515b" value="B" name="grp515" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp515c" value="C" name="grp515" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp515d" value="D" name="grp515" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp515e" value="E" name="grp515" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp515f" value="F" name="grp515" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">16)&nbsp;&nbsp;Counsel women and partners/family on postnatal care?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp516a" value="A" name="grp516" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp516b" value="B" name="grp516" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp516c" value="C" name="grp516" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp516d" value="D" name="grp516" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp516e" value="E" name="grp516" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp516f" value="F" name="grp516" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">17)&nbsp;&nbsp;Provide Cotrimoxazole prophylaxis?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp517a" value="A" name="grp517" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp517b" value="B" name="grp517" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp517c" value="C" name="grp517" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp517d" value="D" name="grp517" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp517e" value="E" name="grp517" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp517f" value="F" name="grp517" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">18)&nbsp;&nbsp;Promote partner or spouse involvement?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp518a" value="A" name="grp518" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp518b" value="B" name="grp518" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp518c" value="C" name="grp518" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp518d" value="D" name="grp518" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp518e" value="E" name="grp518" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp518f" value="F" name="grp518" />
</td>
</tr>
</table>
<div style="height:20px"></div>
<div class="nwtxthead"><?php echo t('Post Exposure Prophylaxis'); ?></div>
<table cellpadding="0" cellspacing="0" border="0" style="width:100%;border:solid 1px #AAA">
<tr>
<td colspan="7">
 <div class="nwtxtbig"><?php echo t('Clinical competency tasks'); ?></div>
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxtbig"><?php echo t('Do you feel competent and confident to ...'); ?></div>
</td>
<td style="width:5%;text-align:center">
 <div class="nwtxtbig">A</div>
</td>
<td style="width:5%;text-align:center">
 <div class="nwtxtbig">B</div>
</td>
<td style="width:5%;text-align:center">
 <div class="nwtxtbig">C</div>
</td>
<td style="width:5%;text-align:center">
 <div class="nwtxtbig">D</div>
</td>
<td style="width:5%;text-align:center">
 <div class="nwtxtbig">E</div>
</td>
<td style="width:7%;text-align:center">
 <div class="nwtxtbig"><?php echo t('No Answer'); ?></div>
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">1)&nbsp;&nbsp;&nbsp;Provide counseling to persons who have experienced sexual or occupational exposure to HIV?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp61a" value="A" name="grp61" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp61b" value="B" name="grp61" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp61c" value="C" name="grp61" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp61d" value="D" name="grp61" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp61e" value="E" name="grp61" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp61f" value="F" name="grp61" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">2)&nbsp;&nbsp;&nbsp;Provide prophylactic treatment to exposed patients and health care workers?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp62a" value="A" name="grp62" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp62b" value="B" name="grp62" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp62c" value="C" name="grp62" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp62d" value="D" name="grp62" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp62e" value="E" name="grp62" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp62f" value="F" name="grp62" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">3)&nbsp;&nbsp;<?php echo t('Perform physical examination for a victim of sexual assault (and complete Form J88)'); ?>?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp63a" value="A" name="grp63" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp63b" value="B" name="grp63" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp63c" value="C" name="grp63" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp63d" value="D" name="grp63" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp63e" value="E" name="grp63" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp63f" value="F" name="grp63" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">4)&nbsp;&nbsp;<?php echo t('Protect yourself from HIV exposure (e.g. needle stick injury)'); ?>?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp64a" value="A" name="grp64" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp64b" value="B" name="grp64" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp64c" value="C" name="grp64" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp64d" value="D" name="grp64" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp64e" value="E" name="grp64" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp64f" value="F" name="grp64" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">5)&nbsp;&nbsp;&nbsp;Provide care for sexually assaulted adults and children?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp65a" value="A" name="grp65" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp65b" value="B" name="grp65" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp65c" value="C" name="grp65" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp65d" value="D" name="grp65" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp65e" value="E" name="grp65" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp65f" value="F" name="grp65" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">6)&nbsp;&nbsp;&nbsp;Provide the correct level of referral for treatment when required?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp66a" value="A" name="grp66" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp66b" value="B" name="grp66" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp66c" value="C" name="grp66" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp66d" value="D" name="grp66" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp66e" value="E" name="grp66" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp66f" value="F" name="grp66" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">7)&nbsp;&nbsp;&nbsp;Provide follow up care, management and support?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp67a" value="A" name="grp67" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp67b" value="B" name="grp67" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp67c" value="C" name="grp67" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp67d" value="D" name="grp67" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp67e" value="E" name="grp67" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp67f" value="F" name="grp67" />
</td>
</tr>
</table>
<div style="height:20px"></div>
<div class="nwtxthead"><?php echo t('Guidelines:'); ?> <span style="font-weight:normal"><i><?php echo t('(Answer those relevant to you)'); ?></i></span></div>
<table cellpadding="0" cellspacing="0" border="0" style="width:100%;border:solid 1px #AAA">
<tr>
<td colspan="7">
 <div class="nwtxtbig"><?php echo t('Clinical competency tasks'); ?></div>
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxtbig"><?php echo t('Do you feel competent and confident to ...'); ?></div>
</td>
<td style="width:5%;text-align:center">
 <div class="nwtxtbig">A</div>
</td>
<td style="width:5%;text-align:center">
 <div class="nwtxtbig">B</div>
</td>
<td style="width:5%;text-align:center">
 <div class="nwtxtbig">C</div>
</td>
<td style="width:5%;text-align:center">
 <div class="nwtxtbig">D</div>
</td>
<td style="width:5%;text-align:center">
 <div class="nwtxtbig">E</div>
</td>
<td style="width:7%;text-align:center">
 <div class="nwtxtbig"><?php echo t('No Answer'); ?></div>
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">1)&nbsp;&nbsp;&nbsp;Understand and use the 2007 guidelines on nutrition for people living with HIV, AIDS, TB and other chronic debilitating conditions?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp71a" value="A" name="grp71" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp71b" value="B" name="grp71" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp71c" value="C" name="grp71" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp71d" value="D" name="grp71" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp71e" value="E" name="grp71" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp71f" value="F" name="grp71" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">2)&nbsp;&nbsp;&nbsp;Understand and use the CCMT/ART guidelines for adults and children?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp72a" value="A" name="grp72" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp72b" value="B" name="grp72" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp72c" value="C" name="grp72" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp72d" value="D" name="grp72" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp72e" value="E" name="grp72" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp72f" value="F" name="grp72" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">3)&nbsp;&nbsp;&nbsp;Understand and use the Sexual Assault Management guidelines?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp73a" value="A" name="grp73" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp73b" value="B" name="grp73" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp73c" value="C" name="grp73" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp73d" value="D" name="grp73" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp73e" value="E" name="grp73" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp73f" value="F" name="grp73" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">4)&nbsp;&nbsp;&nbsp;Understand and use the Contraceptive Management guidelines?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp74a" value="A" name="grp74" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp74b" value="B" name="grp74" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp74c" value="C" name="grp74" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp74d" value="D" name="grp74" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp74e" value="E" name="grp74" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp74f" value="F" name="grp74" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">5)&nbsp;&nbsp;<?php echo t('Understand and use the Choice on Termination of Pregnancy Act (No. 92 of 1996)'); ?>?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp75a" value="A" name="grp75" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp75b" value="B" name="grp75" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp75c" value="C" name="grp75" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp75d" value="D" name="grp75" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp75e" value="E" name="grp75" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp75f" value="F" name="grp75" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">6)&nbsp;&nbsp;&nbsp;Understand and use the National STI syndromic management guidelines?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp76a" value="A" name="grp76" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp76b" value="B" name="grp76" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp76c" value="C" name="grp76" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp76d" value="D" name="grp76" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp76e" value="E" name="grp76" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp76f" value="F" name="grp76" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">7)&nbsp;&nbsp;&nbsp;Understand and use the Prevention of Mother to Child Transmission guidelines?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp77a" value="A" name="grp77" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp77b" value="B" name="grp77" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp77c" value="C" name="grp77" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp77d" value="D" name="grp77" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp77e" value="E" name="grp77" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp77f" value="F" name="grp77" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">8)&nbsp;&nbsp;&nbsp;Understand and use the Maternity guidelines?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp78a" value="A" name="grp78" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp78b" value="B" name="grp78" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp78c" value="C" name="grp78" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp78d" value="D" name="grp78" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp78e" value="E" name="grp78" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp78f" value="F" name="grp78" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">9)&nbsp;&nbsp;&nbsp;Understand and use the National TB Control guidelines?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp79a" value="A" name="grp79" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp79b" value="B" name="grp79" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp79c" value="C" name="grp79" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp79d" value="D" name="grp79" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp79e" value="E" name="grp79" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp79f" value="F" name="grp79" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">10)&nbsp;Understand and use the IMCI booklet?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp710a" value="A" name="grp710" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp710b" value="B" name="grp710" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp710c" value="C" name="grp710" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp710d" value="D" name="grp710" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp710e" value="E" name="grp710" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp710f" value="F" name="grp710" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">11)&nbsp;Understand and use the National HIV Counselor Mentorship guidelines?</div>
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp711a" value="A" name="grp711" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp711b" value="B" name="grp711" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp711c" value="C" name="grp711" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp711d" value="D" name="grp711" />
</td>
<td style="width:5%;text-align:center">
 <input type="radio" id="grp711e" value="E" name="grp711" />
</td>
<td style="width:7%;text-align:center">
 <input type="radio" id="grp711f" value="F" name="grp711" />
</td>
</tr>
</table>
<div style="height:20px"></div>
<div class="nwtxthead"><?php echo t('Other'); ?></div>
<table cellpadding="0" cellspacing="0" border="0" style="width:100%;border:solid 1px #AAA">
<tr>
<td style="width:68%">
 <div class="nwtxtbig"><?php echo t('Clinical competency tasks'); ?></div>
</td>
<td style="text-align:center;width:10%">
 <div class="nwtxtbig"><?php echo t('Yes'); ?></div>
</td>
<td style="text-align:center;width:15%">
 <div class="nwtxtbig"><?php echo t('No'); ?></div>
</td>
<td style="width:7%;text-align:center">
 <div class="nwtxtbig"><?php echo t('No Answer'); ?></div>
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">1)&nbsp;&nbsp;&nbsp;Do you require additional training to perform your tasks?</div>
</td>
<td style="text-align:center;width:10%">
 <input type="radio" id="grp21a" value="A" name="grp21" />
</td>
<td style="text-align:center;width:15%">
 <input type="radio" id="grp21b" value="B" name="grp21" />
</td>
<td style="text-align:center;width:7%">
 <input type="radio" id="grp21f" value="F" name="grp21" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">2)&nbsp;&nbsp;&nbsp;Would you like to become a mentor?</div>
</td>
<td style="text-align:center;width:10%">
 <input type="radio" id="grp22a" value="A" name="grp22" />
</td>
<td style="text-align:center;width:15%">
 <input type="radio" id="grp22b" value="B" name="grp22" />
</td>
<td style="text-align:center;width:7%">
 <input type="radio" id="grp22f" value="F" name="grp22" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">3)&nbsp;&nbsp;&nbsp;Do you feel prepared to become a mentor?</div>
</td>
<td style="text-align:center;width:10%">
 <input type="radio" id="grp23a" value="A" name="grp23" />
</td>
<td style="text-align:center;width:15%">
 <input type="radio" id="grp23b" value="B" name="grp23" />
</td>
<td style="text-align:center;width:7%">
 <input type="radio" id="grp23f" value="F" name="grp23" />
</td>
</tr>
<tr>
<td style="width:68%">
 <div class="nwtxt">4)&nbsp;&nbsp;&nbsp;If yes to question 1, what additional training needs do you have?</div>
</td>
<td style="text-align:center;width:10%">
</td>
<td style="text-align:center;width:15%">
 <input type="text" id="grp240" name="grp240" maxlength="128" />
</td>
<td style="text-align:center;width:7%">
</td>
</tr>
</table>
<input type="hidden" name="ids1" id="ids1" value="1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,01,02,03,04,05,06,08,09,31,32,33,34,35,36,37,41,42,43,44,51,52,53,54,55,56,57,58,59,510,511,512,513,514,515,516,517,518,61,62,63,64,65,66,67" />
<input type="hidden" name="ids2" id="ids2" value="21,22,23" />
<input type="hidden" name="ids3" id="ids3" value="71,72,73,74,75,76,77,78,79,710,711" />
<input type="hidden" name="ids4" id="ids4" value="240" />
<div style="height:16px"></div>
<div class="actionBtn">
<?php
if($this->mode=='ok')
{
 echo '<input type="submit" class="submitNoArrow" name="go" value="<?php echo t('Save'); ?>" />';
}
?>
</div>
<div class="clear"></div>
</form>
</div>
</div>
<div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
<script type="text/javascript">
var c = 0;
var d = 'a';
function taby(event)
{
  var a = document.getElementById("ids1").value+','+document.getElementById("ids3").value+','+document.getElementById("ids2").value;
  var b = a.split(',');
  if(event.keyCode == 9)
  {
	if(d=='f')
	{
		d='a';
		if(c==(b.length-1))
		{
			c=0;
		}
		else
		{
			c=c+1;
		}
	}
	else
	{
		d=String.fromCharCode(d.charCodeAt(0)+1);
	}
	if(document.getElementById('grp'+b[c]+d) != null)
	{
		$('#grp'+b[c]+'a').focus();
		document.getElementById('grp'+b[c]+d).checked = true;
	}
	else
	{
		taby(event);
	}
  }
}
if ($.browser.mozilla) {
    $(document).keypress (taby);
} else {
    $(document).keydown (taby);
}
</script>
</body>
</html>