<div class="fieldIndentNoMargin"><?php tp('Current Contact Information');?></div>
<fieldset>

<div id="facwrapper">

<legend><?php tp('Facility');?></legend>

<?php region_filters_dropdown ($this, $this->locations, $this->person, false, false, 'person_facility'); ?>

  <!-- filter the facility drop down by region -->
<script type="text/javascript">
	$(document).ready(function () {
		var sels = $('#facwrapper select').not('#facilityInput'); // all selects

<?php
if ( $this->setting['num_location_tiers'] > 2 ) {
    $selectFunction = 'filterByText';
} else { 
    $selectFunction = 'filterFacilityByText';
}
?>

$('#facilityInput').<?php echo $selectFunction; ?>(sels, true);
	});
</script>


  <!-- facility dropdown -->
<div class="fieldLabel"  id="facilityInput_lbl"><span class="required">*</span><?php tp('Facility');?></div>
<div class="fieldInput">
<?php

if ($this->setting['display_mod_skillsmart']) {
   $multi_fac_ids = json_decode(html_entity_decode($this->person['multi_facility_ids']));
		if(count($multi_fac_ids) >= 2){ ?>
     <select id="facilityInput" name="facilityInput[]" multiple="multiple">
			  <option value="">--<?php tp('choose');?>--</option>
			  <?php
				foreach ( $this->facilities as $vals ) {
								$non_city_parent = $vals['location_id'];
								if ($this->locations[$non_city_parent]['tier'] == $this->setting['num_location_tiers']) $non_city_parent = $this->locations[$vals['location_id']]['parent_id'];
								$value = buildId($this->setting['num_location_tiers'] - 1, $this->locations, $non_city_parent).'_'.$vals['id'];
								//$value = $vals['province_id'].'_'.$vals['id'];
					echo '<option value="'.$value.'" '.( in_array($vals['id'], $multi_fac_ids) ? 'selected="selected"' : '' ).'>' . $vals['facility_name'] . '</option>';
				}
			  ?>
			</select>
		<?php } else { ?>
			<select id="facilityInput" name="facilityInput[]" multiple="multiple">
			  <option value="">--<?php tp('choose');?>--</option>
			  <?php
			    foreach ( $this->facilities as $vals ) {
					$non_city_parent = $vals['location_id'];
					if ($this->locations[$non_city_parent]['tier'] == $this->setting['num_location_tiers']) $non_city_parent = $this->locations[$vals['location_id']]['parent_id'];
					$value = buildId($this->setting['num_location_tiers'] - 1, $this->locations, $non_city_parent).'_'.$vals['id'];
					//$value = $vals['province_id'].'_'.$vals['id'];
					echo '<option value="'.$value.'" '.($this->person['facility']['id'] == $vals['id']?'selected="selected"':'').'>' . $vals['facility_name'] . '</option>';
				}
			  ?>
			</select>
<?php
		}
} else {

	// ! skillsmart

?>
  <select id="facilityInput" name="facilityInput">
  <option value="">--<?php tp('choose');?>--</option>
<?php
    foreach ( $this->facilities as $vals ) {
      $non_city_parent = $vals['location_id'];
      if ($this->locations[$non_city_parent]['tier'] == $this->setting['num_location_tiers']) $non_city_parent = $this->locations[$vals['location_id']]['parent_id'];
      $value = buildId($this->setting['num_location_tiers'] - 1, $this->locations, $non_city_parent).'_'.$vals['id'];
      //$value = $vals['province_id'].'_'.$vals['id'];
      echo '<option value="'.$value.'" '.($this->person['facility']['id'] == $vals['id']?'selected="selected"':'').'>'.$vals['facility_name'].'</option>';
  }
?>
</select>
<?php
}
  if (! @$this->setting['desktop_disable_people_insert_facility'])   // tanzania request - only their DB's will have this, but anyone could add this setting to _system
    #echo $this->insertFacilityLink;
    echo '<a href="#" id="show">' . str_replace(' ','&nbsp;',t('Insert new facility')) . '</a>';
?>
</div>


	</div>

	<?php if ($this->setting['display_mod_skillsmart']) { ?>
		<div class="fieldLabel" id="facilitydepartment_id_lbl"><?php tp('If facility is a hospital, please click specific department');?></div>
		<div class="fieldInput">
			<select id="facilitydepartment_id" name="facilitydepartment_id">
				<option value="">--<?php tp('choose');?>--</option>
				<?php
					if (isset ($this->skillsmart['facilitydepartment'])){
						foreach ($this->skillsmart['facilitydepartment'] as $ss){
							echo "<option value=\"" . $ss['id'] . "\"" . (($this->person['facilitydepartment_id'] == $ss['id']) ? " selected=\"selected\"" : "") . ">" . $ss['label'] . "</option>\n";
						}
					}
				?>
			</select>
		</div>
	<?php } ?>

</fieldset>

<fieldset>
<legend><?php tp('Address and Phone');?></legend>
<?php if ( $this->setting['display_people_home_address'] ) {
  require_once('edit-home-address.phtml');
  } ?>
  <?php if ( $this->setting['display_people_home_phone'] ) { ?>
  <div class="fieldLabel"  id="phone_home_lbl"><?php tp('Home phone');?></div>
  <div class="fieldInput"><input type="text" id="phone_home" name="phone_home" size="32" maxlength="32" value="<?php echo $this->person['phone_home'];?>"/></div>
  <?php } ?>
  <div class="fieldLabel" ><?php tp('Work phone');?></div>
  <div class="fieldInput"><input type="text" id="phone_work" name="phone_work" size="32" maxlength="32" value="<?php echo $this->person['phone_work'];?>"/></div>
  <div class="fieldLabel" ><?php tp('Mobile phone');?></div>
  <div class="fieldInput"><input type="text" id="phone_mobile" name="phone_mobile" size="32" maxlength="32" value="<?php echo $this->person['phone_mobile'];?>"/></div>
  <div class="fieldLabel"  id="email_lbl"><?php tp('Email');?></div>
  <div class="fieldInput"><input type="text" id="email" name="email" size="32" maxlength="64" value="<?php echo $this->person['email'];?>"/><br/><span style="color: #696969;">johndoe@example.net</span></div>
  <?php if ( $this->setting['display_people_second_email'] ) { ?>
  <div class="fieldLabel"  id="email_secondary_lbl"><?php tp('Email Secondary');?></div>
  <div class="fieldInput"><input type="text" id="email_secondary" name="email_secondary" size="32" maxlength="64" value="<?php echo $this->person['email_secondary'];?>"/></div>
  <?php } ?>
  <?php if ( $this->setting['display_people_fax'] ) { ?>
  <div class="fieldLabel" ><?php tp('Fax');?></div>
  <div class="fieldInput"><input type="text" id="fax" name="fax" size="32" maxlength="32" value="<?php echo $this->person['fax'];?>"/></div>
  <?php } ?>
</fieldset>
 <div class="clear"></div>
  <div class="hrGrey"></div>
  <div class="clear"></div>
<div class="fieldIndentNoMargin"><?php tp('Qualifications');?></div>
<div class="fieldLabel" id="primary_qualification_option_id_lbl"><span class="required">*</span><?php tp('Professional qualification');?></div><div class="fieldInput"><select id="primary_qualification_option_id" name="primary_qualification_option_id">
  <option value="">--<?php tp('choose');?>--</option>
  <?php
    $lastParent = null;
    foreach ( $this->qualifications as $vals ) {
    if ( !$vals['id'] ) {
      $lastParent = ($vals['parent_phrase']);
      echo '<option value="'.$vals['parent_id'].'" '.($this->person['primary_qualification_option_id'] == $vals['parent_id'] || (!$this->id && $vals['is_default']  ) ?'selected="selected"':'').'>'.htmlspecialchars($vals['parent_phrase']).'</option>';
    } else {
      echo '<option value="'.$vals['id'].'" '.($this->person['primary_qualification_option_id'] == $vals['id'] || (!$this->id && $vals['is_default']  ) ?'selected="selected"':'').'>&nbsp;&nbsp;'. htmlspecialchars($vals['qualification_phrase']).'</option>';
    }
  }
    ?>
</select></div><br/>

<?php if ( $this->setting['display_responsibility_me']  ) { ?>
<div class="fieldLabel" ><?php echo (@$this->translation['M&E Responsibility']); ?></div><div class="fieldInput"><textarea name="me_responsibility" rows="3" cols="100"><?php echo $this->person['me_responsibility'];?></textarea></div><br/>
<?php }?>

<?php if ( $this->setting['display_primary_responsibility']  ) { ?>
<?php echo DropDown::render('primary_responsibility_option_id', $this->translation['Primary Responsibility'], $this->primaryResponsibilities, 'responsibility_phrase', 'id', $this->person['primary_responsibility_option_id'], $onchange = 'makeUniqueOptions("primary_responsibility_option_id","secondary_responsibility_option_id");' ); ?><br/>
<?php }?>

<?php if ( $this->setting['display_secondary_responsibility']  ) { ?>
<?php echo DropDown::render('secondary_responsibility_option_id', $this->translation['Secondary Responsibility'], $this->secondaryResponsibilities, 'responsibility_phrase', 'id', $this->person['secondary_responsibility_option_id'], $onchange = 'makeUniqueOptions("secondary_responsibility_option_id","primary_responsibility_option_id");' ); ?><br/>
<?php }?>


<script type="text/javascript">
  function makeUniqueOptions(updatedSelect,alternateSelect) {
    var updatedObj = YAHOO.util.Dom.get(updatedSelect);
    var alternateObj = YAHOO.util.Dom.get(alternateSelect);
    if ( updatedObj.selectedIndex == alternateObj.selectedIndex )
      alternateObj.selectedIndex = 0;
  }
</script>

  <?php if ( $this->setting['display_attend_reason']  ) { ?>
		<?php echo DropDown::render('attend_reason_option_id', $this->translation['Reason Attending'], $this->attendreasons, 'attend_reason_phrase', 'id', $this->person['attend_reason_option_id'], $onchange = 'initReasonOtherField();', false); ?><br/>
	  <div class="fieldLabel" ><?php tp('Reason (if Other selected above)');?></div>
	  <div class="fieldInput"><input type="text" id="attend_reason_other" name="attend_reason_other" size="32" maxlength="100" onfocus="initReasonOtherField();" value="<?php echo $this->person['attend_reason_other'];?>"/> </div>

<script type="text/javascript">
  function initReasonOtherField(init) {
    var selectField = YAHOO.util.Dom.get("attend_reason_option_id");
    var inputField = YAHOO.util.Dom.get("attend_reason_other");
    if (selectField.value == <?php echo $this->other_reason_option_id; ?>) {
    	inputField.diabled = false;
    } else {
      //if (!init) alert(selectField.value);
    	inputField.value = "";
    	inputField.diabled = true;
    	if (!init) selectField.focus();
   	}
  }
  initReasonOtherField(true);
</script>
  <?php }?>

  <?php if ( $this->setting['display_people_custom1'] ) { ?>
  <div id="custom1AutoComplete" >
      <div class="fieldLabel" id="custom1Input_lbl"><?php echo (@$this->translation['People Custom 1']); ?> </div><div class="fieldInput"><input id="custom1Input" name="custom1Input" type="text" size="40" maxlength="128" value="<?php echo @$this->person['custom1'];?>" /><div class="clear"></div><div id="custom1Container" class="autoComplete"></div></div>
  </div><br/>
  <?php } ?>
    <?php if ( $this->setting['display_people_custom2'] ) { ?>
  <div id="custom2AutoComplete" >
      <div class="fieldLabel" id="custom2Input_lbl"><?php echo (@$this->translation['People Custom 2']); ?> </div><div class="fieldInput"><input id="custom2Input" name="custom2Input" type="text" size="40" maxlength="128" value="<?php echo @$this->person['custom2'];?>" /><div class="clear"></div><div id="custom2Container" class="autoComplete"></div></div>
  </div><br/>
  <?php } ?>

  <?php if ( $this->setting['display_people_custom3'] ) { ?>
  <div id="custom3AutoComplete" >
      <div class="fieldLabel" id="custom3Input_lbl"><?php echo (@$this->translation['People Custom 3']); ?> </div><div class="fieldInput"><input id="custom_3" name="custom_3" type="text" size="40" maxlength="128" value="<?php echo @$this->person['custom_3'];?>" /><div class="clear"></div><div id="custom3Container" class="autoComplete"></div></div>
  </div><br/>
  <?php } ?>

  <?php if ( $this->setting['display_people_custom4'] ) { ?>
  <div id="custom4AutoComplete" >
      <div class="fieldLabel" id="custom2Input_lbl"><?php echo (@$this->translation['People Custom 4']); ?> </div>
      <div class="fieldInput"><input id="custom_4" name="custom_4" type="text" size="40" maxlength="128" value="<?php echo @$this->person['custom_4'];?>" />
      <div class="clear"></div>
      <div id="custom4Container" class="autoComplete"></div></div>
  </div><br/>
  <?php } ?>

    <?php if ( $this->setting['display_people_custom5'] ) { ?>
  <div id="custom5AutoComplete" >
      <div class="fieldLabel" id="custom5Input_lbl"><?php echo (@$this->translation['People Custom 5']); ?> </div>
      <div class="fieldInput"><input id="custom_5" name="custom_5" type="text" size="40" maxlength="128" value="<?php echo @$this->person['custom_5'];?>" />
      <div class="clear"></div>
      <div id="custom5Container" class="autoComplete"></div></div>
  </div><br/>
  <?php } ?>

  <?php if ( $this->setting['display_highest_ed_level']  ) { ?>
		<?php echo DropDown::render('highest_edu_level_option_id', $this->translation['Highest Education Level'], $this->educationlevels, 'education_level_phrase', 'id', $this->person['highest_edu_level_option_id']); ?><br/>
  <?php }?>

  <!-- TA:17: 09/09/2014 -->
<?php if($this->setting['display_people_comments']){?>
<div class="fieldLabel" ><?php tp('Qualification Comments');?></div><div class="fieldInput"><textarea name="comments" rows="5" cols="100"><?php echo $this->person['comments'];?></textarea></div><br/>
<?php }?>

<script type="text/javascript">
  function toggleDiv(divId,placeholderId) {
    var divObj = YAHOO.util.Dom.get(divId);
    var placeObj = YAHOO.util.Dom.get(placeholderId);
    if ( divObj.style.display == 'none' ) {
      divObj.style.display = 'block';
      if ( placeObj != null )
        placeObj.style.display = 'none';
    } else {
      divObj.style.display = 'none';
      if ( placeObj != null)
        placeObj.style.display = 'block';
    }
  }
</script>

      
      <!-- TA:17: 09/10/2014 -->
      <?php if($this->setting['display_people_facilitator']) {?>
 <div class="clear"></div>
  <div class="hrGrey"></div>
  <div class="clear"></div>
  <a name="training"></a>
 <div class="fieldIndentNoMargin"><?php tp('Trainer').' '.t('Information');?> <a href="javascript:toggleDiv('trainingInfo','placeholderTraining');"><?php tp('Show/Hide');?></a></div>

<div id="trainingInfo" style="<?php echo (($this->person['active_trainer_option_id'] || $this->maketrainer) ? 'display:block;' : 'display:none;');?>"><br/>
  <div class="fieldInput"> <input type="hidden" id="is_trainer" name="is_trainer" <?php if (@$this->person['trainer_is_active']) echo 'checked="checked" ';?>/><label for="is_trainer"><?php echo t('Is person an').' '.t('active').' '.t('trainer?');?></label></div>
  <?php
  print DropDown::render('active_trainer_option_id', t('Active trainer'), $this->active_trainer,'active_trainer_phrase','id', $this->person['active_trainer_option_id']  );
  ?>
  <div class="fieldLabel" id="trainer_type_option_id_lbl"><span class="required">*</span><?php echo t('Trainer').' '.t('type');?></div>
  <div class="fieldInput">
  <select id="trainer_type_option_id" name="trainer_type_option_id" >
    <option value="">--<?php tp('choose');?>--</option>
    <?php
      foreach ( $this->trainer_types as $vals ) {
        echo '<option value="'.$vals['id'].'" '.($this->person['trainer_type_option_id'] == $vals['id']?'selected="selected"':'').'>'.$vals['trainer_type_phrase'].'</option>';
    }
    ?>
  </select>
  </div>

  <?php if ($this->setting['display_trainer_affiliations'] ) { ?>
  <div class="fieldLabel"  id="trainer_affiliation_option_id_lbl"><?php echo t('Trainer').' '.t('Affiliation');?></div>
  <div class="fieldInput"><select id="trainer_affiliation_option_id" name="trainer_affiliation_option_id" >
    <option value="">--<?php tp('choose');?>--</option>
    <?php
      foreach ( $this->trainer_affiliations as $vals ) {
        echo '<option value="'.$vals['id'].'" '.($this->person['trainer_affiliation_option_id'] == $vals['id']?'selected="selected"':'').'>'.$vals['trainer_affiliation_phrase'].'</option>';
    }
    ?>
  </select>
  </div>
  <?php } ?>
  
     

<div class="clear" ></div>

  <div class="fieldLabel"  id="trainer_skill_id_lbl">
    <?php
      if($this->setting['require_trainer_skill']) {
        echo '<span class="required">*</span>';
      }
      echo t('Trainer').' '.t('skills');?>
    </div>
  <div class="fieldInput">
        (<?php tp('check all that apply');?>)<br/><br/>
         <div class="checkBoxes">
   <?php
    foreach( $this->trainer_skills as $skill ) {
      echo '<div class="float50"><input type="checkbox" name="trainer_skill_id[]" id="trainer_skill_'.$skill['id'].'" value="'.$skill['id'].'" '.(@$skill['trainer_id']? 'CHECKED':'').' /><label for="trainer_skill_'.$skill['id'].'">'.$skill['trainer_skill_phrase'].'</label></div>';
    }
  ?>      </div></div>

<div class="clear" ></div>
<?php echo DropDown::render('primary_language_id', t('Primary language'), $this->trainer_languages, 'language_phrase', 'id', @$this->person['primary_language_id']); ?>
<div class="fieldLabel" ><?php tp('Secondary languages');?></div>
    <div class="fieldInput">
        (<?php tp('check all that apply');?>)<br/><br/>
        <div class="checkBoxes">
    <?php
      foreach( $this->trainer_languages as $lang ) {
        echo '<div class="float50"><input type="checkbox" name="trainer_language_id[]" id="trainer_language_'.$lang['id'].'"  value="'.$lang['id'].'" '.(@$lang['trainer_id']? 'CHECKED':'').' /><label for="trainer_language_'.$lang['id'].'">'.$lang['language_phrase'].'</label></div>';
      }
    ?></div></div>
    

<?php if ($this->hasTrainerHistory) { ?>
  <div class="clear" ></div>

  <?php if ( $this->mode != 'add' ) { ?>
  <div id="trainerInfo" class="itechTable"></div>
  <script type="text/javascript">

  var formatTrainingViewUrl = function(elCell, oRecord, oColumn, sData) {
    if ( oRecord.getData("training_id") == null )
      return;

    if ( (sData == null) || (sData.length == 0) )
      sData = '&nbsp;&nbsp;&nbsp;';
    elCell.innerHTML = "<a href='<?php echo $this->base_url;?>/training/view/id/" + oRecord.getData("training_id") + "' >" + sData + "</a>";
  };


    var trainerColumnDefs = [
        {key:"training_id", label: "<?php tp('ID')?>", sortable:false, resizeable:true, formatter: formatTrainingViewUrl},
        {key:"training_start_date", label: "<?php tp('Start Date');?>", sortable:true, resizeable:true},
        {key:"training_title", label: "<?php tp('Name');?>", sortable:true, resizeable:true},
        {key:"training_location_name", label: "<?php tp('Location');?>", sortable:true, resizeable:true}
    ];

    var traction = '<?php echo $this->base_url;?>/training/list-by-trainer/id/<?php echo $this->person['id'];?>/outputType/json';
    makeJSONDataTable("trainerInfo", null, traction, trainerColumnDefs);
  </script>
  <?php }?>

<?php }?>


  <div class="clear"></div>
    <div class="hrGrey"></div>
    <div class="clear"></div>
</div>
<?php }?><!-- TA:17: 09/10/2014 END -->


