<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<title><?php echo $this->translation['Application Name'];?> | <?php tp('Person Search');?></title>
		<?php
		require_once('views/helpers/Location.php');
		require_once('views/helpers/ScriptContainer.php');
		print ScriptContainer::$instance->renderCSSHead();
		print ScriptContainer::$instance->renderJSHead();

		?>

	</head>
	<body class="yui-skin-sam" >

		<div id="pageHolder">

			<div id="header"><?php require_once('views/scripts/header.phtml');?></div>
			<div id="content">

				<h1><?php tp('People Search');?></h1>
				<form action="" method="get">
					<fieldset><legend><?php tp('Select Criteria');?></legend>


					<?php region_filters_dropdown($this, $this->locations, $this->criteria, false, false); ?>

					<div class="fieldLabel"  id="facilityInput_lbl"><?php tp('Facility');?></div><div class="fieldInput">

					<?php echo renderFacilityDropDown($this->facilities, $this->criteria['facilityInput'], $this->viewonly); ?></div>

					<div class="clear"></div>

					<!-- course taken -->
					<div class="fieldLabel" id="training_title_option_id_lbl"><?php echo (@$this->translation['Training Name']); ?></div>
					<div class="fieldInput">
						<select id="training_title_option_id" name="training_title_option_id" >
							<option value="">--<?php tp('All');?>--</option>
							<?php
							foreach ( $this->courses as $vals ) {
							    //TA: do not use $this->truncate($vals['training_title_phrase'])
								echo '<option value="'.$vals['id'].'" '.((@$this->criteria['training_title_option_id']) == $vals['id']? 'SELECTED':'').' >'. $vals['training_title_phrase'].'</option>';
							}
							?>
						</select></div>
						<div class="clear"></div>

						<div class="fieldLabel" id="qualification_id_lbl"><?php tp('Qualification');?></div>
						<div class="fieldInput"><select id="qualification_id" name="qualification_id">
							<option value="">--<?php tp('All');?>--</option>
							<?php
							$lastParent = null;
							foreach ( $this->qualifications as $vals ) {
								if ( !$vals['id'] ) {
									$lastParent = $vals['parent_phrase'];
									echo '<option value="'.$vals['parent_id'].'" '.((@$this->criteria['qualification_id']) == $vals['parent_id']?'SELECTED':'').'>'.htmlspecialchars($vals['parent_phrase']).'</option>';
								} else {
									echo '<option value="'.$vals['id'].'" '.((@$this->criteria['qualification_id']) == $vals['id']?'SELECTED':'').'>&nbsp;&nbsp;'. htmlspecialchars($vals['qualification_phrase']).'</option>';
								}
							}
							?>
						</select></div>
						
						<?php if($this->setting['display_last_name_first']){ //TA:UK:1712:23 shaw different names order for  PHC and UCFM?>
						<div id="lastAutoComplete">
							<div class="fieldLabel"><?php echo (@$this->translation['Last Name']); ?></div><div class="fieldInput"><input id="last_name" type="text" name="last_name" value="<?php echo $this->criteria['last_name'];?>" /><div class="clear"></div><div id="lastContainer" class="autoComplete"></div></div>
						</div>
						<?php }?>
						<div  id="firstAutoComplete">
							<div class="fieldLabel"><?php echo (@$this->translation['First Name']); ?></div><div class="fieldInput"><input id="first_name" type="text" name="first_name" value="<?php echo $this->criteria['first_name'];?>" /><div class="clear"></div><div id="firstContainer" class="autoComplete"></div></div>
						</div>
						<script type="text/javascript">
							var firstAuto = makeAutocomplete('first_name', 'firstContainer', '<?php echo $this->base_url;?>/person/first-list/outputType/text/' );
						</script>
						<?php if(!$this->setting['display_last_name_first']){ //TA:UK:1712:23 shaw different names order for  PHC and UCFM?>
						<div id="lastAutoComplete">
							<div class="fieldLabel"><?php echo (@$this->translation['Last Name']); ?></div><div class="fieldInput"><input id="last_name" type="text" name="last_name" value="<?php echo $this->criteria['last_name'];?>" /><div class="clear"></div><div id="lastContainer" class="autoComplete"></div></div>
						</div>
						<?php }?>
						<script type="text/javascript">
							var lastAuto = makeAutocomplete('last_name', 'lastContainer', '<?php echo $this->base_url;?>/person/last-list/outputType/text/' );
						</script>
						<div class="clear"></div>
      <div class="fieldLabel"></div><div class="fieldInput" style="font-size:11px; font-weight:bold; color: #696969;"><input type="radio" id="is_trainer" value="is_trainer" name="person_type" <?php if ( $this->criteria['person_type'] == 'is_trainer') echo 'CHECKED'; ?> /><?php echo t('Trainers');?></div>
      <div class="fieldLabel"></div><div class="fieldInput" style="font-size:11px; font-weight:bold; color: #696969;"><input type="radio" id="is_participant" value="is_participant" name="person_type" <?php if ( $this->criteria['person_type'] == 'is_participant' ) echo 'CHECKED'; ?> /><?php echo t('Participants');?></div>
						<div class="fieldLabel"></div><div class="fieldInput" style="font-size:11px; font-weight:bold; color: #696969;"><input type="radio" id="is_unattached_person" value="is_unattached_person" name="person_type" <?php if ( $this->criteria['person_type'] == 'is_unattached_person' ) echo 'CHECKED'; ?> /><?php tp('Unattached only');?></div>
						<div class="fieldLabel"></div><div class="fieldInput" style="font-size:11px; font-weight:bold; color: #696969;"><input type="radio" id="is_everyone" value="is_everyone" name="person_type" <?php if ( $this->criteria['person_type'] == 'is_everyone' ) echo 'CHECKED'; ?> /><?php tp('Everyone');?></div>
<?php
	if (isset($this->setting['display_mod_skillsmart']) && ($this->setting['display_mod_skillsmart'] == 1)){
?>
						<div class="fieldLabel"></div><div class="fieldInput" style="font-size:11px; font-weight:bold; color: #696969;"><input type="checkbox" id="is_complete" value="is_complete" name="is_complete" <?php if ( $this->criteria['is_complete'] == 'is_complete' ) echo 'CHECKED'; ?> /><?php tp('Incomplete competence');?></div>
<?php
	}
?>
						<input type="hidden" name="limit" id="limit" value="1" />
						<input type="submit" class="submitNoArrow" name="go" value="<?php tp('Preview');?>" />
					</fieldset>
				</form>
				<?php if ( $this->criteria['go'] ) { ?>

<?php
#	foreach($this->results as $row) {
#		var_dump ($row);
#	}
?>

				<div class="hrGrey"></div>
				<!-- TA:80 print only people report part-->
				<div class="fieldIndentNoMargin"><?php tp('People');?> <span class="total"><?php echo $this->count;?>  <?php tp('Results');?></span><?php echo $this->printAndExport("people");?></div>
					<a href="<?php echo $this->base_url;?>/person/add"><?php tp('Add New Person');?></a><br/><br/>
					<div id="people"></div>
					<script type="text/javascript">
						var peopleData = [
						<?php
						$cnt = 0;
						$isFirstRow = true;
						foreach($this->results as $row) {
							$showperson = true;

							$required = isset ($row['comps']['required']) ? $row['comps']['required'] : 0;
							$answered = count($row['comps']['answers']);

							if ($this->criteria['is_complete'] == 'is_complete'){
								if ($required <= $answered){
									$showperson = false;
								}
							}

							if ($showperson){
								if ( (isset($_REQUEST['limit']) AND !$_REQUEST['limit'])  or ($cnt < 100) ) {
									if (!$isFirstRow )
									echo ',';
									$isFirstRow = false;

									$thisrow = array();
									$thisrow[] = $row['id'];
									$thisrow[] = addslashes($row['first_name']);


									if ( $this->setting['display_middle_name'] &&  !$this->setting['display_middle_name_last'] ) {
										$thisrow[] = addslashes($row['middle_name']);
									}
									$thisrow[] = addslashes($row['last_name']);
									if ( $this->setting['display_middle_name'] && $this->setting['display_middle_name_last'] ) {
										$thisrow[] = addslashes($row['middle_name']);
									}
									// Some results do not contain province_name
									if (! array_key_exists('province_name', $row)) {
										$row['province_name'] = '(no region)';
									}
									if (isset($this->setting['display_mod_skillsmart']) && ($this->setting['display_mod_skillsmart'] == 1)){
										// ALSO DISPLAY SKILLSMART SPECIFIC COLUMNS
										if($this->setting['display_gender']){//TA:17: 09/09/2014
										$thisrow[] = addslashes($row['gender']);
										}
										$thisrow[] = addslashes($row['birthdate']);
										$thisrow[] = addslashes($row['qualification_phrase']);
										$thisrow[] = addslashes($row['province_name']);


										if($row['res']=="0"){
											$showred=' style=\"color:Red\"';
										} else {
											$showred="";
										}

										// New database driven
										if (count ($row['comps']) > 0){
											if ($required > $answered){
												// INCOMPLETE
												$thisrow[] = '<a href=\\\''.$this->base_url.'/person/editcompetency/id/'.$row['id'].'\\\'>Enter data</a>';
												$thisrow[] = "";
											} else {
												// COMPLETE
												$thisrow[] = '<a href=\\\''.$this->base_url.'/person/editcompetency/id/'.$row['id'].'\\\'>Enter data</a>';
												$thisrow[] = '<a href=\\\'' . $this->base_url . '/person/viewcompetency/id/' . $row['id'] . '\\\'>View</a>';
											}
										} else {
											$thisrow[] = '';
											$thisrow[] = '';
										}
									} else {
										// ONLY DISPLAY NON-SKILLSMART COLUMNS
										if($this->setting['display_gender']){//TA:17: 09/09/2014
										$thisrow[] = addslashes($row['gender']);
										}
										$thisrow[] = addslashes($row['birthdate']);
										$thisrow[] = trim(addslashes($row['qualification_phrase'])); // bugfix.
										$thisrow[] = addslashes($row['province_name']);
									}
									echo "['" . implode("','", $thisrow) . "']\n";
									$cnt++;
								}
							}
						}
						?>];

						var formatViewUrl = function(elCell, oRecord, oColumn, sData) {
							if ( (sData == null) || (sData.length == 0) )
							sData = '&nbsp;&nbsp;&nbsp;';
							elCell.innerHTML = "<a href='<?php echo $this->base_url;?>/person/view/id/" + oRecord.getData("id") + "' >" + sData + "</a>";
						}

						var peopleColumnDefs = [
						{key:"id", label: "<?php tp('ID')?>", sortable:false, resizable:false,
						formatter: formatViewUrl},
						<?php if($this->setting['display_last_name_first']){ //TA:UK:1712:23 shaw different names order for  PHC and UCFM?>
							{key:"last_name", label: "<?php echo addslashes((@$this->translation['Last Name'])); ?>", sortable:true, resizeable:true},
							<?php }?>
						{key:"first_name", label: "<?php echo addslashes((@$this->translation['First Name'])); ?>", sortable:true, resizeable:true},
						<?php if ( $this->setting['display_middle_name'] && !$this->setting['display_middle_name_last'] ) { ?>
							{key:"middle_name", label: "<?php echo addslashes((@$this->translation['Middle Name'])); ?>", sortable:true, resizeable:true},
						<?php }?>
						<?php if(!$this->setting['display_last_name_first']){ //TA:UK:1712:23 shaw different names order for  PHC and UCFM?>
						{key:"last_name", label: "<?php echo addslashes((@$this->translation['Last Name'])); ?>", sortable:true, resizeable:true},
						<?php }?>
						<?php if ( $this->setting['display_middle_name'] && $this->setting['display_middle_name_last'] ) { ?>
							{key:"middle_name", label: "<?php echo (@$this->translation['Middle Name']); ?>", sortable:true, resizeable:true},
						<?php }?>
						<?php if($this->setting['display_gender']){?> //TA:17: 09/09/2014
						{key:"gender", label: "<?php tp('Gender');?>", sortable:true, resizeable:true},
						<?php }?>
						{key:"birthdate", label: "<?php tp('Birthdate');?>", sortable:true, resizeable:true},
						{key:"qualification_phrase", label: "<?php tp('Qualification');?>", sortable:true, resizeable:true},
						{key:"province_name", label: "<?php echo (@$this->translation['Region A (Province)']); ?>", sortable:true, resizeable:true}
<?php 	if (isset($this->setting['display_mod_skillsmart']) && ($this->setting['display_mod_skillsmart'] == 1)){
?>
						,{key:"comp", label: "<?php tp('Competence');?>", sortable:false, resizeable:false},
			{key:"rpt", label: "<?php tp('Report');?>", sortable:false, resizeable:false}
<?php	} 	?>
						];

						makeDataTable("people", null, peopleData, peopleColumnDefs);
					</script>
					<?php if ($cnt < count($this->results)) { ?>
					[<?php tp('Limited to 100 rows');?>]  <a href="<?php echo str_replace('limit=1','limit=0',$_SERVER['REQUEST_URI']);?>"><?php tp('Full Results');?></a>
					<?php } ?>
					<?php } ?>
				</div>
				<div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>


			</div>

		</body>
	</html>
