<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title><?php echo $this->translation['Application Name'];?> | <?php tp('Competence Detail Reports');?></title>
	<?php
	require_once('views/helpers/Location.php');
	require_once('views/helpers/ScriptContainer.php');
	print ScriptContainer::$instance->renderCSSHead();
	print ScriptContainer::$instance->renderJSHead();
	?>

<script language="JavaScript">
	var all = false;
	function allcompetence(){
		if ($('#complist').is(":disabled")){
			alert("<?php tp('Please select an occupational category first')?>");
			$("#qualification_id").focus();
		} else {
			if (!all){
				$("#complist > option").attr("selected", true);
				all = true;
			} else {
				$("#complist > option").removeAttr("selected");
				all = false;
			}
			$('#complist').change();
//			ShwHid(document.getElementById("complist"));
		}
	}
</script>

</head>
<!--<body class="yui-skin-sam" onload="SwHd(document.getElementById('qualification_id'));Sel();"> -->
<body class="yui-skin-sam" onload="Sel();">
	<div id="pageHolder">

		<div id="header"><?php require_once('views/scripts/header.phtml');?></div>
		<div id="content">

			<h1><?php tp('Competence Detail Reports');?></h1>
			<form action="" method="get">
				<fieldset><legend><?php tp('Select Criteria');?></legend>
					<div class="fieldLabel" id="province_id_lbl"><?php echo (@$this->translation['Region A (Province)']); ?></div>
					<div class="fieldInput"><?php renderFilter($this->locations, 1, 'province_id', $this->criteria['province_id'], 'district_id');?></div>
					<?php if ( $this->setting['display_region_b'] ) { ?>
					<div class="fieldLabel" id="district_id_lbl"><?php echo (@$this->translation['Region B (Health District)']); ?></div>
					<div class="fieldInput"><?php renderFilter($this->locations, 2, 'district_id', $this->criteria['district_id'], ($this->setting['display_region_c']?'region_c_id':false));?></div>
					<?php } ?>
					<?php if ( $this->setting['display_region_c'] ) { ?>
					<div class="fieldLabel" id="region_c_id_lbl"><?php echo (@$this->translation['Region C (Local Region)']); ?></div>
					<div class="fieldInput"><?php renderFilter($this->locations, 3, 'region_c_id', $this->criteria['region_c_id'], false);?></div>
					<?php } ?>

					<div class="fieldLabel"  id="facilityInput_lbl"><?php tp('Facility');?></div><div class="fieldInput"><select id="facilityInput" name="facilityInput" >
					<option value="">--<?php tp('choose');?>--</option>
					<?php
					foreach ( $this->facilities as $vals ) {
						echo '<option value="'.$vals['id'].'" '.($this->criteria['facilityInput'] == $vals['id']?'SELECTED':'').'>'.$vals['facility_name'].'</option>';
					}
					?>
				</select></div>
				<div class="clear"></div>

				<div class="fieldLabel" id="training_title_option_id_lbl"><?php echo (@$this->translation['Training Name']); ?></div>
				<div class="fieldInput">
					<select id="training_title_option_id" name="training_title_option_id" >
						<option value="">--<?php tp('All');?>--</option>
						<?php
						foreach ( $this->courses as $vals ) {
							echo '<option value="'.$vals['id'].'" '.((@$this->criteria['training_title_option_id']) == $vals['id']? 'SELECTED':'').' >'.$this->truncate($vals['training_title_phrase']).'</option>';
						}
						?>
					</select></div>

					<div class="clear"></div>

					<div class="fieldLabel" id="qualification_id_lbl"><?php echo t('Occupational category'); ?></div>
					<div class="fieldInput"><select id="qualification_id" name="qualification_id" onchange="showCompetencies()">
						<option value="">--<?php tp('choose');?>--</option>
						<?php
						$lastParent = null;
						foreach ( $this->qualifications as $vals ) {
							if ( !$vals['id'] ) {
								$lastParent = $vals['parent_phrase'];
								echo '<option value="'.$vals['parent_id'].'" '.((@$this->criteria['qualification_id']) == $vals['parent_id']?'SELECTED':'').'>'.htmlspecialchars($vals['parent_phrase']).'</option>';
							}
						}
						?>
					</select></div>
					<div class="clear"></div>
					<script type="text/javascript">
/*
					var i;
					for(i=0;i<document.getElementById("qualification_id").options.length;i++){
						if(document.getElementById("qualification_id").options[i].text.indexOf("ther (Please")>0)
							document.getElementById("qualification_id").options[i].text=document.getElementById("qualification_id").options[i].text.substr(0,document.getElementById("qualification_id").options[i].text.length-2).replace("Z_","");
					}
*/
						</script>
						<div class="fieldLabel" id="qualification_id_lbl"><?php echo t('Competence'); ?><br><a href="#" onclick="allcompetence()"><span style="font-size : 9px;">Select all / none</span></a></div>
						<div class="fieldInput">
							<select name="complist[]" id="complist" style="width : 350px;" size="5" multiple="multiple" disabled onchange="ShwHid(this)">
								<option>Select an occupational category first</option>
							</select>
<?php

	# HARDCODED COMPETENCIES ARE BAD M'KAY
	#require_once('listcomn.phtml');
	#require_once('listcomd.phtml');
	#require_once('listcomp.phtml');
	#require_once('listcomc.phtml');

?>
						</div>
						<div class="clear"></div>
						<script type="text/javascript">

<?php

	echo "var comptrans = new Array();\n";
	foreach ($this->complist as $cl){
		$comp = array();
		if (count($cl['competencies']) > 0){
			foreach ($cl['competencies'] as $c_arr){
				$comp[] = "[" . $c_arr['id'] . ",'" . addslashes($c_arr['name']) . "']";
			}
		}
		echo "comptrans['c" . $cl['id'] . "'] = [" . implode(",", $comp) . "];\n";
	}

?>

						// document.getElementById("listc").setAttribute("multiple","multiple");
						// document.getElementById("listd").setAttribute("multiple","multiple");
						// document.getElementById("listn").setAttribute("multiple","multiple");
						// document.getElementById("listp").setAttribute("multiple","multiple");
						// document.getElementById("listc").options.remove(0);
						// document.getElementById("listd").options.remove(0);
						// document.getElementById("listn").options.remove(0);
						// document.getElementById("listp").options.remove(0);
						function myExport()
						{
							var v1;
							var v2;
							v1="";
							v2=""
							if(document.getElementById('dv0')!=null)
							{
								v1=v1+document.getElementById('dv0').innerHTML+"~";
								v2=v2+document.getElementById('pr0').innerHTML.replace("%","")+"~";
							}
							if(document.getElementById('dv1')!=null)
							{
								v1=v1+document.getElementById('dv1').innerHTML+"~";
								v2=v2+document.getElementById('pr1').innerHTML.replace("%","")+"~";
							}
							if(document.getElementById('dv2')!=null)
							{
								v1=v1+document.getElementById('dv2').innerHTML+"~";
								v2=v2+document.getElementById('pr2').innerHTML.replace("%","")+"~";
							}
							if(document.getElementById('dv3')!=null)
							{
								v1=v1+document.getElementById('dv3').innerHTML+"~";
								v2=v2+document.getElementById('pr3').innerHTML.replace("%","")+"~";
							}
							if(document.getElementById('dv4')!=null)
							{
								v1=v1+document.getElementById('dv4').innerHTML+"~";
								v2=v2+document.getElementById('pr4').innerHTML.replace("%","")+"~";
							}
							if(document.getElementById('dv5')!=null)
							{
								v1=v1+document.getElementById('dv5').innerHTML+"~";
								v2=v2+document.getElementById('pr5').innerHTML.replace("%","")+"~";
							}
							v1=v1.substring(0,v1.length-1);
							v2=v2.substring(0,v2.length-1);
							var loc=window.location.href;
							window.location=loc.substr(0,loc.indexOf("?"))+"csv?v1="+v1+"&v2="+v2;
						}
						function Sel()
						{
							if(document.getElementById("ques").value!="")
							{
								var Vls=document.getElementById("ques").value.split(",");
								for(var i=0;i<Vls.length;i++)
								{
									if(document.getElementById('qualification_id').value=="6")
									{
										document.getElementById('listc').options[Vls[i]].selected=true;
										document.getElementById('dv'+i).innerHTML=document.getElementById('listc').options[Vls[i]].text;
									}
									if(document.getElementById('qualification_id').value=="7")
									{
										document.getElementById('listd').options[Vls[i]].selected=true;
										document.getElementById('dv'+i).innerHTML=document.getElementById('listd').options[Vls[i]].text;
									}
									if(document.getElementById('qualification_id').value=="8")
									{
										document.getElementById('listn').options[Vls[i]].selected=true;
										document.getElementById('dv'+i).innerHTML=document.getElementById('listn').options[Vls[i]].text;
									}
									if(document.getElementById('qualification_id').value=="9")
									{
										document.getElementById('listp').options[Vls[i]].selected=true;
										document.getElementById('dv'+i).innerHTML=document.getElementById('listp').options[Vls[i]].text;
									}
								}
							}
						}

						function is_array(input){
							return typeof(input)=='object'&&(input instanceof Array);
						}

						function showCompetencies(selected){
							all = false;
							if ($("#qualification_id").val() != ""){
								var items = comptrans['c'+$("#qualification_id").val()];
								$("#complist").empty();
								var ctr = 0;
								if (items[ctr]){
									while (items[ctr]){
										$('#complist')
											.append($("<option></option>")
											.attr("value",items[ctr][0])
											.text(items[ctr][1])); 
										ctr++;
									}
									$("#complist").removeAttr("disabled");

									if (is_array(selected)){
										// highlighting selected elements
										var ctr = 0;
										while(selected[ctr]){
											$("#complist option[value='" + selected[ctr] + "']").attr("selected", true);
											ctr++;
										}
									}

								} else {
									$('#complist')
										.append($("<option></option>")
										.attr("value","")
										.text("Category has no competencies")); 
									$("#complist").attr("disabled",true);
								}
							} else {
								$("#complist").empty();
								$('#complist')
									.append($("<option></option>")
									.attr("value","")
									.text("Select an occupational category first")); 
								$("#complist").attr("disabled",true);
								ctr++;
							}
						}

/*
						function SwHd(obj)
						{
							document.getElementById("listc").style.display="none";
							document.getElementById("listd").style.display="none";
							document.getElementById("listn").style.display="none";
							document.getElementById("listp").style.display="none";
							document.getElementById("listc").selectedIndex=0;
							document.getElementById("listd").selectedIndex=0;
							document.getElementById("listn").selectedIndex=0;
							document.getElementById("listp").selectedIndex=0;
							document.getElementById("listc").options[0].selected=false;
							document.getElementById("listd").options[0].selected=false;
							document.getElementById("listn").options[0].selected=false;
							document.getElementById("listp").options[0].selected=false;
							if(obj.value=="6")
							{
								document.getElementById("listc").style.display="inline";
							}
							if(obj.value=="7")
							{
								document.getElementById("listd").style.display="inline";
							}
							if(obj.value=="8")
							{
								document.getElementById("listn").style.display="inline";
								document.getElementById("NurseOptions").style.display="block";
							}
							else
							{
								document.getElementById("trainer_type_option_id1").selectedIndex=0;
								document.getElementById("grp1a").checked=false;
								document.getElementById("grp1b").checked=false;
								document.getElementById("grp2a").checked=false;
								document.getElementById("grp2b").checked=false;
								document.getElementById("grp3a").checked=false;
								document.getElementById("grp3b").checked=false;
							}
							if(obj.value=="9")
							{
								document.getElementById("listp").style.display="inline";
							}
						}
*/
						function ShwHid(obj)
						{
							document.getElementById("ques").value="";
							for(var i=0;i<obj.options.length;i++)
							{
								if(obj.options[i].selected)
								{
									// document.getElementById("ques").value=document.getElementById("ques").value+i+",";
									document.getElementById("ques").value=document.getElementById("ques").value + obj.options[i].value + ",";
								}
							}
							document.getElementById("ques").value=document.getElementById("ques").value.replace(/,+$/,'');
						}
						</script>
						<div class="fieldLabel"><?php echo t('Score'); ?></div><div class="fieldInput">
						<select id="score_id" name="score_id">
							<option value="">--<?php echo t('choose'); ?>--</option>
							<option value="100" <?php if ($this->criteria['score_id']=="100") echo 'selected="selected"';?>>90 - 100%</option>
							<option value="89" <?php if ($this->criteria['score_id']=="89") echo 'selected="selected"';?>>75 - 89%</option>
							<option value="74" <?php if ($this->criteria['score_id']=="74") echo 'selected="selected"';?>>60 - 74%</option>
							<option value="0" <?php if ($this->criteria['score_id']=="0") echo 'selected="selected"';?>><?php echo t('Less than 60%'); ?></option>
						</select></div>
						<div class="fieldLabel"><?php echo t('Primary patients'); ?></div><div class="fieldInput">
						<select id="primarypatients" name="primarypatients">
							<option value="">--<?php echo t('choose'); ?>--</option>
							<option value="1" <?php if ($this->criteria['primarypatients']=="1") echo 'selected="selected"';?>><?php echo t('Pregnant women'); ?></option>
							<option value="2" <?php if ($this->criteria['primarypatients']=="2") echo 'selected="selected"';?>><?php echo t('Adults'); ?></option>
							<option value="3" <?php if ($this->criteria['primarypatients']=="3") echo 'selected="selected"';?>><?php echo t('Children'); ?></option>
						</select>
					</div>
					<div class="fieldLabel"><?php echo t('Years of experience'); ?></div><div class="fieldInput">
					<select id="hivInput" name="hivInput">
						<option value="">--<?php echo t('choose'); ?>--</option>
						<option value="1" <?php if ($this->criteria['hivInput']=="1") echo 'selected="selected"';?>><?php echo t('Less than 1 year'); ?></option>
						<option value="5" <?php if ($this->criteria['hivInput']=="5") echo 'selected="selected"';?>><?php echo t('1 - 5 years'); ?></option>
						<option value="10" <?php if ($this->criteria['hivInput']=="10") echo 'selected="selected"';?>><?php echo t('More than 5 years'); ?></option>
					</select>
				</div>
				<div id="NurseOptions" style="display : none;">
					<div class="fieldLabel"><?php echo t('Nurse trainer type'); ?></div><div class="fieldInput">
					<select id="trainer_type_option_id1" name="trainer_type_option_id1">
						<option value="">--<?php echo t('choose'); ?>--</option>
						<option value="Master Trainer"<?php if ($this->criteria['trainer_type_option_id1']=="Master Trainer"){echo ' selected="selected"';}?>><?php echo t('Master Trainer'); ?></option>
						<option value="Facility Trainer"<?php if ($this->criteria['trainer_type_option_id1']=="Facility Trainer"){echo ' selected="selected"';}?>><?php echo t('Facility Trainer'); ?></option>
						<option value="N/A or None"<?php if ($this->criteria['trainer_type_option_id1']=="N/A or None"){echo ' selected="selected"';}?>><?php echo t('N/A or None'); ?></option>
					</select>
				</div>
				<div class="fieldLabel"><?php echo t('Nurse initiating ART'); ?></div><div class="fieldInput">
				<input <?php if ($this->criteria['grp1']=="Y") echo 'checked="checked"';?> type="radio" id="grp1a" value="Y" name="grp1" /><?php echo t('Yes'); ?>
				<input <?php if ($this->criteria['grp1']=="N") echo 'checked="checked"';?> type="radio" id="grp1b" value="N" name="grp1" /><?php echo t('No'); ?>
			</div>
			<div class="fieldLabel"><?php echo t('Would like to become a nurse mentor'); ?></div><div class="fieldInput" style="margin-top:20px">
			<input <?php if ($this->criteria['grp2']=="Y") echo 'checked="checked"';?> type="radio" id="grp2a" value="Y" name="grp2" /><?php echo t('Yes'); ?>
			<input <?php if ($this->criteria['grp2']=="N") echo 'checked="checked"';?> type="radio" id="grp2b" value="N" name="grp2" /><?php echo t('No'); ?>
		</div>
		<div class="fieldLabel"><?php echo t('Feels prepared to become a nurse mentor'); ?></div><div class="fieldInput" style="margin-top:20px">
		<input <?php if ($this->criteria['grp3']=="Y") echo 'checked="checked"';?> type="radio" id="grp3a" value="Y" name="grp3" /><?php echo t('Yes'); ?>
		<input <?php if ($this->criteria['grp3']=="N") echo 'checked="checked"';?> type="radio" id="grp3b" value="N" name="grp3" /><?php echo t('No'); ?>
	</div>
</div>
<input type="hidden" name="listcq" id="listcq" value="1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20" />
<input type="hidden" name="listdq" id="listdq" value="1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18~01,02,03,04,05,06,08,09~31,32,33,34,35,36,37~41,42,43,44~51,52,53,54,55,56,57,58,59,510,511,512,513,514,515,516,517,518~61,62,63,64,65,66,67" />
<input type="hidden" name="listnq" id="listnq" value="1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,200~01,02,03,04,05,06,07,08,09~31,32,33,34,35,36,37,38~41,42,43,44,45~51,52,53,54,55,56,57,58,59,510,511,512,513~61,62,63,64,65" />
<input type="hidden" name="listpq" id="listpq" value="1,2,3,4,5,6,7" />
<input type="hidden" name="ques" id="ques" value="<?php echo $this->criteria['ques'] ?>" />
<input type="hidden" name="limit" id="limit" value="1" />
<input type="submit" onclick="if(document.getElementById('ques').value==''){alert('Please select a competence');return false;}" class="submitNoArrow" name="go" value="<?php tp('Preview');?>" />
</fieldset>
</form>
<?php if ( $this->criteria['go'] ) { ?>
<div class="hrGrey"></div>
<div class="fieldIndentNoMargin"><?php tp('Results');?></span><span class="printAndExport"><a href="javascript:window.print()"><?php echo t('Print'); ?></a>&nbsp;&nbsp;<a href="javascript:myExport()"><?php echo t('Export'); ?></a>&nbsp;&nbsp;<a href="javascript:myExport()"><img src="<?php echo (Settings::$COUNTRY_BASE_URL).'/images/excel.jpg'; ?>" /></a></span></div>

<script language="JavaScript">
$(function(){
	document.getElementById("NurseOptions").style.display="none";
<?php
	if (isset ($_GET['qualification_id'])){
		echo "showCompetencies([" . implode(",", $_GET['complist']) . "]);\n";
//		echo "alert('" . implode(",", $_GET['complist']) . "');\n";
	}
?>
})
</script>

<?php

if (isset ($this->reportoutput)){
	echo "<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:40%;border:solid 1px #AAA\">\n";
	echo "	<tr>\n";
	echo "		<td><div class=\"nwtxtbig\">".t("Competence")."</div></td>\n";
	echo "		<td><div class=\"nwtxtbig\">".t("Result")."</div></td>\n";
	echo "	</tr>\n";
	foreach ( $this->reportoutput as $k => $v ) {
		echo "	<tr>\n";
		echo "		<td><div class=\"nwtxt\" id=\"dv".$cntr."\">" . $k . "</div></td>\n";
		echo "		<td><div class=\"nwtxt\" id=\"pr".$cntr."\">" . $v . "%</div></td>\n";
		echo "	</tr>\n";
		$cntr=$cntr+1;;
	}
	echo "</table>\n";
}

/*
if(isset($this->rss[0])){
	$cntr;
	$cntr=0;
	echo "<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:40%;border:solid 1px #AAA\">\n";
	echo "	<tr>\n";
	echo "		<td><div class=\"nwtxtbig\">".t("Competence")."</div></td>\n";
	echo "		<td><div class=\"nwtxtbig\">".t("Result")."</div></td>\n";
	echo "	</tr>\n";
	foreach ( $this->rss as $ys => $ls ) {
		echo "	<tr>\n";
		echo "		<td><div class=\"nwtxt\" id=\"dv".$cntr."\">" . $ys . "</div></td>\n";
		echo "		<td><div class=\"nwtxt\" id=\"pr".$cntr."\">" . $ls . "%</div></td>\n";
		echo "	</tr>\n";
		$cntr=$cntr+1;;
	}
	echo "</table>\n";
} else {

	if ( $this->criteria['go'] ){
		echo "<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style=\"width:40%;border:solid 1px #AAA\">\n";
		echo "	<tr>\n";
		echo "		<td><div class=\"nwtxtbig\">".t("Competence")."</div></td>\n";
		echo "		<td><div class=\"nwtxtbig\">".t("Result")."</div></td>\n";
		echo "	</tr>\n";
		foreach ($this->complist as $cl){
			echo "	<tr>\n";
			echo "		<td><div class=\"nwtxt\" id=\"dv".$cntr."\">" . $ys . "</div></td>\n";
			echo "		<td><div class=\"nwtxt\" id=\"pr".$cntr."\">" . $ls . "%</div></td>\n";
			echo "	</tr>\n";
		}
		echo "</table>\n";
	}
}
*/
?>
<?php } ?>
</div>
<div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>

</div>

</body>
</html>