<!DOCTYPE html>
<html>
<head>
    <title><?php echo $this->translation['Application Name']; ?>
        | <?php echo t('Employee') . " " . t('Reports'); ?></title>
    <?php
    require_once('views/helpers/ScriptContainer.php');
    require_once('views/helpers/FormHelper.php');
    require_once('views/helpers/DropDown.php');
    require_once('views/helpers/Location.php');
    require_once('views/helpers/CheckBoxes.php');

    print ScriptContainer::$instance->renderCSSHead();
    print ScriptContainer::$instance->renderJSHead();
    echo $this->partial('reports/employee-reports-common-javascript-header-partial.phtml');
    ?>

</head>
<body class="yui-skin-sam">
<div id="pageHolder">
    <div id="header"><?php require_once('views/scripts/header.phtml'); ?></div>
    <div id="content">
        <?php require_once 'views/scripts/status.phtml' ?>
        <div id="subcontent">
            <?php
            echo $this->partial('reports/employee-reports-report-types-partial.phtml', array('site_style' => $this->site_style, 'base_url' => $this->base_url));
            ?>

            <div class="clear"></div>
            <div id="contentheader">
                <h2><?php echo t("Employee") . " " . t("Reports"); ?></h2><br/>
            </div>
            <div class="pad50 clear"></div>
            <form action="" method="get" class="form_employee">
                <fieldset id="criteria">
                    <legend><?php tp('Select Criteria'); ?></legend>
                    <div class="fieldLabel"></div>
                    <div class="fieldInput criteria-header">
                        <div class="criteria-label"><?php tp('show'); ?></div>
                        <div class="criteria-label" style="padding-left: 20px;"><?php tp('filter'); ?></div>
                    </div>
                    <div class="clear"></div>
                    <div id="dividers">

                        <?php
                        $this->required_fields = array();
                        $this->calendar_fields = array('transition_start_date', 'transition_end_date');
                        $this->is_report = true;


                        echo labelAndField($this, t('Partner'),
                            $this->formSelect('partner', isset($this->criteria['partner']) ? $this->criteria['partner'] : null, array(), $this->partners), 'partner');

                        //TA:#293 multiple locations
                       // echo region_filters_dropdown($this, $this->locations, $this->criteria, false, true);
                       //TA:#293.1
                        region_filters_dropdown( $this, $this->locations, $this->criteria, true, true );
                       
                        echo labelAndField($this, t('Based at'),
                            $this->formSelect('based_at', isset($this->criteria['based_at']) ? $this->criteria['based_at'] : null, array(), $this->bases), 'based_at');

                        //TA:#293.1
//                         echo labelAndField($this, t('Site') . space . t('Name'),
//                             $this->formSelect('site', isset($this->criteria['site']) ? $this->criteria['site'] : null, array(), $this->facilities), 'site');   
                        echo labelAndField($this, t('Site Name'), renderFacilityDropDown($this->sites, $this->criteria['site'], $this->viewonly), 'facilityInput');

                        echo labelAndField($this, t('Facility Type'),
                            $this->formSelect('facility_type', isset($this->criteria['facility_type']) ? $this->criteria['facility_type'] : null, array(), $this->facilityTypes), 'facility_type');

                        echo labelAndField($this, t('Staff Cadre'),
                            $this->formSelect('classification', isset($this->criteria['classification']) ? $this->criteria['classification'] : null, array(), $this->classifications), 'classification');

                        echo labelTwoFields($this, t('Funded hours per week'), t('to'), 'hours_min', 'hours_max',
                            isset($this->criteria['hours_min']) ? $this->criteria['hours_min'] : '',
                            isset($this->criteria['hours_max']) ? $this->criteria['hours_max'] : '');

                        echo labelTwoFields($this, t('Annual Cost'), t('to'), 'cost_min', 'cost_max',
                            isset($this->criteria['cost_min']) ? $this->criteria['cost_min'] : '',
                            isset($this->criteria['cost_max']) ? $this->criteria['cost_max'] : '');

                        echo labelAndField($this, t('Primary Role'),
                            $this->formSelect('primary_role', isset($this->criteria['primary_role']) ? $this->criteria['primary_role'] : null, array(), $this->roles), 'primary_role');

                        echo labelAndField($this, t('Intended Transition'),
                            $this->formSelect('intended_transition', isset($this->criteria['intended_transition']) ? $this->criteria['intended_transition'] : null, array(), $this->transitions), 'intended_transition');

                        echo labelAndField($this, t('Actual Transition Outcome'),
                            $this->formSelect('actual_transition', isset($this->criteria['actual_transition']) ? $this->criteria['actual_transition'] : null, array(), $this->transitions), 'actual_transition');

                        echo labelTwoFields($this, t('Actual Transition Date'), t('to'), 'transition_start_date', 'transition_end_date',
                            isset($this->criteria['transition_start_date']) ? $this->criteria['transition_start_date'] : '',
                            isset($this->criteria['transition_end_date']) ? $this->criteria['transition_end_date'] : '');

                        echo labelTwoFields($this, t('Salary'), t('to'), 'salary_min', 'salary_max',
                            isset($this->criteria['salary_min']) ? $this->criteria['salary_min'] : '',
                            isset($this->criteria['salary_max']) ? $this->criteria['salary_max'] : '');

                        echo labelTwoFields($this, t('Benefits'), t('to'), 'benefits_min', 'benefits_max',
                            isset($this->criteria['benefits_min']) ? $this->criteria['benefits_min'] : '',
                            isset($this->criteria['benefits_max']) ? $this->criteria['benefits_max'] : '');

                        echo labelTwoFields($this, t('Additional Expenses'), t('to'), 'expenses_min', 'expenses_max',
                            isset($this->criteria['expenses_min']) ? $this->criteria['expenses_min'] : '',
                            isset($this->criteria['expenses_max']) ? $this->criteria['expenses_max'] : '');

                        echo labelTwoFields($this, t('Stipend'), t('to'), 'stipend_min', 'stipend_max',
                            isset($this->criteria['stipend_min']) ? $this->criteria['stipend_min'] : '',
                            isset($this->criteria['stipend_max']) ? $this->criteria['stipend_max'] : '');

                        echo $this->partial('reports/ps-search-preview-button-partial.phtml', array());
                        ?>
                    </div>
                    <div class="clear"></div>

            </form>
            <?php if (isset($this->output)) {
                echo $this->partial('reports/ps-jquery-table-search-results-preview-partial.phtml',
                    array('output' => $this->output, 'headers' => $this->headers));
                ?>
                <input type="button" name="go" value="<?php tp('Download'); ?> &raquo;" class="tsbutton green large"
                       onclick="window.open('<?php echo $_SERVER['REQUEST_URI'] . "&format=csv" ?>')">
            <?php } ?>
        </div>
    </div>
</div>

</body>
</html>
