<div class="fieldLabel" id="training_lbl">
<?php echo t('Employee') . ' ' . t('Reports');?>
</div>

<?php
$options = array(
    "" => "--" . t('choose') . "--",
    "/reports/employees" => t('Custom'),
    "/reports/employee-report-occupational-category" => t('Occupational Category'),
    "/reports/employee-report-primary-role" => t('Primary Role'),
    "/reports/employee-report-mechanism-transition-description" => t('Mechanism Transition By Description'),
    "/reports/employee-report-mechanism-transition" => t('Mechanism Transition'),
);

$r = Zend_Controller_Front::getInstance()->getRequest();
$selected = "/" . $r->getControllerName() . "/" .$r->getActionName();
echo $this->formSelect('employees', $selected, array('id' => 'employee-reports', 'onchange' => "window.location = '$this->base_url' + $(this).val();"), $options);
echo "<br/><br>";