<!DOCTYPE html>
<html>
<head>
    <title><?php echo $this->translation['Application Name'];?> | <?php echo t('Employee') . " " . t('Reports'); ?></title>
<?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>
    <script type="text/javascript" charset="utf-8">
        $(document).ready(function () {
            $('.datepicker').datepicker( {dateFormat: "dd/mm/yy"} );
            $('#employee-reports').change(function(){
                <?php // #employee-reports is part of employee-report-types-partial template ?>

                window.location = '<?php echo $this->base_url;?>' + $(this).val();
            });

        });
        $(document).ready(function() {
            /* Init the table */
            var oTable = $('.tablegrid').dataTable({
                "bJQueryUI": true,
                "bSort": false,
                "sPaginationType": "full_numbers"
            });
        } );


    </script>

</head>
<body class="yui-skin-sam">
<div id="pageHolder">
    <div id="header"><?php require_once('views/scripts/header.phtml');?></div>
    <div id="content">
        <div id="subcontent">
            <?php
            echo $this->partial('reports/employee-report-types-partial.phtml', array('site_style' => $this->site_style));
            ?>

            <div class="clear"></div>
            <div id="contentheader">
                <h2><?php echo t("Employee") . " " . t("Reports"); ?></h2><br/>
            </div>
            <div class="pad50 clear"></div>
            <form action="" method="get" class="form_employee">
                <?php
                    echo $this->partial('reports/employee-reports-common.phtml',
                        array('mechanisms' => $this->mechanisms, 'funders' => $this->funders,
                            'transitions' => $this->transitions, 'transition_types' => $this->transition_types));
                    echo $this->partial('reports/ps-search-preview-button-partial.phtml', array());
                ?>

            </form>
            <?php if (isset($this->output)) {
                echo $this->partial('reports/ps-jquery-table-search-results-preview-partial.phtml',
                    array('output' => $this->output, 'headers' => $this->headers));
                ?>
                <input type="button" name="go" value="<?php tp('Download');?> &raquo;" class="tsbutton green large"
                       onclick="window.open('<?php echo $_SERVER['REQUEST_URI'] . "&format=csv"?>')">
            <?php } ?>
        </div>
    </div>
</div>

</body>
</html>
