<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<title><?php echo $this->translation['Application Name'];?></title>
		<?php
		require_once('views/helpers/ScriptContainer.php');
		print ScriptContainer::$instance->renderCSSHead();
		print ScriptContainer::$instance->renderJSHead();
		?>

	</head>
	<body class="yui-skin-sam">


		<script language="javascript">
			function gotoPage(objId) {
				var reportSelector = YAHOO.util.Dom.get(objId);
				if ( reportSelector[reportSelector.selectedIndex].value ) {
					window.location = '<?php echo $this->base_url;?>' + reportSelector[reportSelector.selectedIndex].value + '?<?php echo $_SERVER['QUERY_STRING'];?>';
				}
			}
		</script>
		<div id="pageHolder">

			<div id="header"><?php require_once('views/scripts/header.phtml');?></div>
			<div id="content" class="form_styled">
<?php
	if ($this->hasACL('in_service')){ 
?>
				<h1><?php tp("Report");?></h1>
				<p></p>
				<?php require_once('peopleReportsPicker.phtml'); ?><br/><br/>
				<div class="clear"></div>
				<div class="fieldLabel" id="trainer_lbl"><?php echo t('Select').' '.t('trainer').' '.t('report');?></div>
				<select id="trainer" name="trainer" onchange="gotoPage('trainer');">
					<option value="">--<?php tp('choose');?>--</option>
					<option value="/reports/trainers"><?php echo t('Trainers').' '.t('by').space.t('Skill, Language, and PEPFAR');?></option>
					<option value="/reports/trainersByName"><?php echo t('Trainers').' '.t('by').space.t('Name');?></option>
				</select><br/><br/>
				<div class="clear"></div>
				<div class="fieldLabel" id="training_lbl"><?php echo t('Select').' '.t('Training').' '.t('report');?></div>
				<select id="training" name="training" onchange="gotoPage('training');">
					<option value="">--<?php tp('choose');?>--</option>
					<option value="/reports/trainings"><?php echo t('Trainings').space.t('by').space.t('Name'); ?></option>
					<option value="/reports/trainingByTitle"><?php echo t('Trainings').space.t('by').space.t('Multiple Names'); ?></option>
					<?php if ($this->setting['display_budget_code']) { ?>
					<option value="/reports/budgetcode"><?php echo t('Trainings').space.t('by').space.t('Budget Code').space.t('Viewing Location'); ?></option>
					<?php } ?>
					<option value="/reports/trainingUnknown"><?php echo t('Trainings').space.t('with').space.t('Unknown Participants'); ?></option>
					<option value="/reports/trainingsMissingInformation"><?php echo t('Trainings').space.t('with').space.t('missing information'); ?></option>
				</select><br/><br/>
<?php
	}
	if ($this->hasACL('pre_service')){
/*
				<div class="clear"></div>
				<div class="fieldLabel" id="training_lbl"><?php tp('Pre-service reports');?></div>
				<select id="pstraining" name="pstraining" onchange="gotoPage('pstraining');">
					<option value="">--<?php tp('choose');?>--</option>
					<option value="/reports/psTrainingsByName"><?php tp('Trainings by Name');?></option>
					<option value="/reports/psTrainingByParticipants"><?php tp('Trainings by Participant Count');?></option>

					<option value="/reports/psMissingStudentsTrained"><?php tp('Missing students trained');?></option>
					<option value="/reports/psMissingStudentsByName"><?php tp('Missing students by name');?></option>
					<option value="/reports/psMissingGraduatedStudents"><?php tp('Missing graduated students');?></option>
					<option value="/reports/psMissingCourseByStudentCount"><?php tp('Missing course by student count');?></option>
					<option value="/reports/psMissingCourseByName"><?php tp('Missing course by name');?></option>
					<option value="/reports/psMissingCohortByParticipantCount"><?php tp('Missing cohort by participant count');?></option>
					<option value="/reports/psMissingInstitutionInformation"><?php tp('Missing instituiton information');?></option>
					<option value="/reports/psMissingTutorByName"><?php tp('Missing tutor by name');?></option>
					<option value="/reports/psMissingFacilityReport"><?php tp('Missing facility report');?></option>
				</select>
*/
?>
				<h2><?php echo t('Pre-Service'); ?></h2>

				<div class="clear"></div>
				<div class="fieldLabel" id="training_lbl"><?php tp('Select student report');?></div>
				<select id="pstraining" name="pstraining" onchange="gotoPage('pstraining');">
					<option value="">--<?php tp('choose');?>--</option>
					<option value="/reports/psStudentsTrained"			><?php tp('Students Trained');?></option>
					<option value="/reports/psStudentsByName"			><?php tp('Students By Name');?></option>
					<option value="/reports/psGraduatedStudents"		><?php tp('Graduated Students');?></option>
				</select><br/><br/>

				<div class="clear"></div>
				<div class="fieldLabel" id="training_lbl"><?php tp('Select course report');?></div>
				<select id="pscrs" name="pscrs" onchange="gotoPage('pscrs');">
					<option value="">--<?php tp('choose');?>--</option>
					<option value="/reports/psCourseByStudentCount"		><?php tp('Course By Student Count');?></option>
					<option value="/reports/psCourseByName"				><?php tp('Course By Name');?></option>
				</select><br/><br/>

				<div class="clear"></div>
				<div class="fieldLabel" id="training_lbl"><?php tp('Select cohort report');?></div>
				<select id="pscoh" name="pscoh" onchange="gotoPage('pscoh');">
					<option value="">--<?php tp('choose');?>--</option>
					<option value="/reports/psCohortByParticipantCount"	><?php tp('Cohort By Participant Count');?></option>
				</select><br/><br/>

				<div class="clear"></div>
				<div class="fieldLabel" id="training_lbl"><?php tp('Select institution report');?></div>
				<select id="psins" name="psins" onchange="gotoPage('psins');">
					<option value="">--<?php tp('choose');?>--</option>
					<option value="/reports/psInstitutionInformation"	><?php tp('Institution Information');?></option>
				</select><br/><br/>

				<div class="clear"></div>
				<div class="fieldLabel" id="training_lbl"><?php tp('Select tutor report');?></div>
				<select id="pstut" name="pstut" onchange="gotoPage('pstut');">
					<option value="">--<?php tp('choose');?>--</option>
					<option value="/reports/psTutorByName"				><?php tp('Tutor By Name');?></option>
				</select><br/><br/>

				<div class="clear"></div>
				<div class="fieldLabel" id="training_lbl"><?php tp('Select facility report');?></div>
				<select id="psfac" name="psfac" onchange="gotoPage('psfac');">
					<option value="">--<?php tp('choose');?>--</option>
					<option value="/reports/psFacilityReport"			><?php tp('Facility Report');?></option>
				</select><br/><br/>

<?php
	}

	if ($this->hasACL('employees_module') && $this->setting['module_employee_enabled']) {
?>
				<h2><?php echo t('Employee'), space, t('Tracking Module'); ?></h2>
				<div class="clear"></div>
				<div class="fieldLabel" id="training_lbl"><?php print(t('Employee').space.t('Tracking Reports'));?></div>
				<select id="employee_reports" name="employee_reports" onchange="gotoPage('employee_reports');">
					<option value="">--<?php tp('choose');?>--</option>
					<option value="/reports/employees"			><?php tp('Employees');?></option>
					<option value="/reports/partners"			><?php tp('Partners');?></option>
					<option value="/reports/mechanisms"			><?php tp('Mechanisms');?></option>
				</select><br/><br/>
<?php
	}
?>
			</div>
			<div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
		</div>
	</body>
</html>