<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<title><?php echo $this->translation['Application Name'];?> | <?php echo ($this->identity->locale == 'nl_NL.UTF-8' ? t('Training Search') : ($this->mode != 'search'? t('Training').' '.t('Reports'):t('Training').' '.t('Search') )); ?></title>
		<?php
		require_once('views/helpers/Location.php');
		require_once('views/helpers/DropDown.php');
		require_once('views/helpers/TrainingViewHelper.php');
		require_once('views/helpers/ScriptContainer.php');
		print ScriptContainer::$instance->renderCSSHead();
		print ScriptContainer::$instance->renderJSHead();

		$checkLabel = ( $this->mode == 'count' ) ? t('group') : t('show');

		?>
		
			</head>
	<body class="yui-skin-sam">
		<div id="pageHolder">
			<div id="header"><?php require_once('views/scripts/header.phtml');?></div>


<?php

// require_once __DIR__ . "/vendor/autoload.php";
require_once "autoload.php";

header('Content-Type: text/html');

use Jaspersoft\Client\Client;

$c = new Client(
        "http://jasperadmin:jasperadmin@140.142.66.229:8080/jasperserver",
        "jasperadmin",
        "jasperadmin"
    //,        "organization_1"
      );  

$report = $c->reportService()->runReport("/reports/samples/AllAccounts", 'html');

echo $report;
  
?>


											<div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>


													</div>

												</body>
											</html>
