<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title><?php echo $this->translation['Application Name'] . " | " . $this->pageTitle; ?></title>
	<?php
	require_once('views/helpers/Location.php');
	require_once('views/helpers/ScriptContainer.php');
	print ScriptContainer::$instance->renderCSSHead();
	print ScriptContainer::$instance->renderJSHead();
	
	$report = 'defined';
	?>

</head>
<body class="yui-skin-sam"  >

	<div id="pageHolder">

		<div id="header"><?php require_once('views/scripts/header.phtml');?></div>
		<div id="content">

			<h1><?php tp('Mechanism Reports');?></h1>

			<form action="" method="get" class="form_employee">
			
			<div id="content">
				<div id="subcontent">
					<div class="fieldLabel" id="report_lbl">Select Mechanism Report</div>
					<select id="report" name="report" >
						<option value="defined" <?php if ( @$this->report == 'defined' ) echo 'SELECTED';?> >Mechanisms Defined</option>
						<option value="definedByPartner" <?php if ( @$this->report == 'definedByPartner' ) echo 'SELECTED';?> >Mechanisms Defined by Partner</option>
						<option value="definedByEmployee" <?php if ( @$this->report == 'definedByEmployee' ) echo 'SELECTED';?> >Mechanisms Defined by <?php tp('Employee');?></option>
					</select><br/><br/>
			
			
				<fieldset id=""><legend><?php tp('Select Criteria');?></legend>

					<?php
						$cal = '<a class="calendarbtn" href="#"><img src="'.$this->base_url.'/js/yui/assets/calbtn.gif"></a>';
						$this->required_fields = array();
						$this->calendar_fields = array('start_date','end_date');

						if($this->setting['display_employee_partner'])
							echo labelAndField($this, t('Partner'), $this->partners, 'partner');
						if($this->setting['display_employee_sub_partner'])
							echo labelAndField($this, t('Sub Partner'), $this->subpartners, 'sub_partner');
						
					?>
					<div class="clear"></div>
					<input type="hidden" name="limit" id="limit" value="1" />
					<input type="submit" class="submitNoArrow" name="go" value="<?php tp('Preview');?>" />
				</fieldset>
			</form>

			<script type="text/javascript">
				$(function () { //docready
					$('#start_date,#end_date').datepicker({
						changeMonth: true, changeYear: true
					});
					$('.calendarbtn').click(openNearestDatePicker);
				});
			</script>

			<?php if ( $this->criteria['go'] ) { ?>
			<div class="hrGrey"></div>
			<div class="fieldIndentNoMargin"><?php tp('Partners');?> <span class="total"><?php echo $this->count;?>  <?php tp('Results');?></span><?php echo $this->printAndExport();?></div><br/>
			<div id="partners"></div>
			<script type="text/javascript">
			var partnersData = [
			<?php
			$cnt = 0;
			$isFirstRow = true;
			foreach($this->results as $row) {

				if ( ( $cnt < 100 ) or ( isset($_REQUEST['limit']) AND !$_REQUEST['limit'] ) ) {
					if ( !$isFirstRow ) {
						echo ',';
					}
					$isFirstRow = false;

					echo '[';
						echo $row['id'].',';
						$data = array();
						$data[] = $row['employee_code'];
						$data[] = $row['partner'];
						$data[] = $row['subpartner'];
						$data[] = $row['funder_phrase'];
						$data[] = $row['mechanism_phrase'];
						$data[] = $row['funding_end_date'];
						$data[] = $row['percentage'];
						echo '"'.implode('","', $data).'"';
					echo ']';
					$cnt++;
				}
			}
			?>];

			var formatViewUrl = function(elCell, oRecord, oColumn, sData) {
				if ( (sData == null) || (sData.length == 0) )
					sData = '&nbsp;&nbsp;&nbsp;';
				elCell.innerHTML = "<a href='<?php echo $this->base_url;?>/mechanism/edit/id/" + oRecord.getData("id") + "' >" + sData + "</a>";
			}

			var partnersColumnDefs = [
				{key:"id", label: "<?php tp("ID");?>", sortable:true, resizable:false <?php if ( @$this->report == 'defined' ) echo ', formatter: formatViewUrl';?>}
				,{key:"employee_code",       label: "<?php tp('Employee');?>",         sortable:true, resizeable:true}
				,{key:"partner",       label: "<?php tp('Partner');?>",         sortable:true, resizeable:true}
				,{key:"subpartner",       label: "<?php tp('Subpartner');?>",         sortable:true, resizeable:true}
				,{key:"funder_phrase",          label: "<?php tp('Funder');?>",  sortable:true, resizeable:true}
				,{key:"mechanism_phrase",    label: "<?php tp('Mechanism');?>",           sortable:true, resizeable:true}
				,{key:"funding_end_date",    label: "<?php tp('Funding End Date');?>",           sortable:true, resizeable:true}
				,{key:"percentage",    label: "<?php tp('Percentage');?>",           sortable:true, resizeable:true}
			];

			makeDataTable("partners", null, partnersData, partnersColumnDefs);
		</script>
			<?php if ($cnt < count($this->results)) { ?>
			[<?php tp('Limited to 100 rows');?>]  <a href="<?php echo str_replace('limit=1','limit=0',$_SERVER['REQUEST_URI']);?>"><?php tp('Full Results');?></a>
			<?php } ?>
			<?php } ?>
		</div>
	</body>
</html>