<script language="javascript">
	function gotoPeoplePage(objId) {
		var reportSelector = YAHOO.util.Dom.get(objId);
		if ( reportSelector[reportSelector.selectedIndex].value ) {
			window.location = '<?php echo $this->base_url;?>' + reportSelector[reportSelector.selectedIndex].value + '?<?php echo $_SERVER['QUERY_STRING'];?>';
		}
	}
</script>
    	<div class="fieldLabel" id="peopleSelect_lbl" style="width: auto;"><?php print str_replace(' ','&nbsp;', t('Select person report'));?></div>
    	<select id="peopleSelect" name="peopleSelect" onchange="gotoPeoplePage('peopleSelect');">
    		<option value="">--<?php tp('choose');?>--</option>
    		<option value="/reports/needs-by-person-name" <?php if ( strstr($path[2], 'needs-by-person-name') !== FALSE) echo 'SELECTED';?> ><?php tp('Needs by Person\'s Name');?></option>
     		<option value="/reports/needs-by-person-count" <?php if ( strstr($path[2], 'needs-by-person-count') !== FALSE ) echo 'SELECTED';?> ><?php tp('Needs by Person Count');?></option>
 	</select>
