<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title><?php echo $this->translation['Application Name'];?> | <?php tp('Assessment Reports');?></title>
<?php
require_once('views/helpers/Location.php');
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();

$checkLabel = t('show');
if ( $this->mode == 'count' )
	$checkLabel = t('group');

?>



</head>
<body class="yui-skin-sam" >
<div id="pageHolder">

  <div id="header"><?php require_once('views/scripts/header.phtml');?></div>
  <div id="content">

    <h1><?php tp('Assessment Reports');?></h1>
    	<?php require_once('needsReportsPicker.phtml'); ?>
	   <form action="" method="get">
   <fieldset id="criteria"><legend><?php tp('Select Criteria');?></legend>
<div id="dividers">
      	<div class="fieldLabel" ></div>
      <div class="fieldInput criteria-header"><div  class="criteria-label" ><?php echo $checkLabel;?></div><div  class="criteria-label" style="padding-left: 20px;"><?php tp('filter');?></div></div>


      <?php region_filters_dropdown($this, $this->locations, $this->criteria, false, true); ?>

	<div id="facilityAutoComplete">
	    <div class="fieldLabel" id="facilityInput_lbl"><?php tp('Facility');?></div>
	    <div class="fieldInput">
	    <div  class="leftBorderPad"><input type="checkbox" name="showFacility" <?php  if ($this->criteria['showFacility']) echo 'CHECKED';?> /></div>
	    <div  class="leftBorder"><select id="facilityInput" name="facilityInput" >
	<option value="">--<?php tp('choose');?>--</option>
	<?php
		foreach ( $this->facilities as $vals ) {
			echo '<option value="'.$vals['id'].'" '.($this->criteria['facilityInput'] == $vals['id']?'SELECTED':'').'>'.$vals['facility_name'].'</option>';
	}
	?>
</select>
	    </div></div>
	</div>
	
	<div class="fieldLabel" id="district_id_lbl"><?php tp('Qualification'); ?> (<?php tp('primary');?>)</div><div class="fieldInput">
	<div  class="leftBorderPad"><input type="checkbox" name="showQualPrim" <?php  if ($this->criteria['showQualPrim']) echo 'CHECKED';?> /></div>
  	<div  class="leftBorder"><select id="qualification_id" name="qualification_id">
		<option value="">--<?php tp('All');?>--</option>
		<?php
			foreach ( $this->qualifications_primary as $vals ) {
				echo '<option value="'.$vals['id'].'" '.((@$this->criteria['qualification_id']) == $vals['id'] ? 'SELECTED':'').' >'.$vals['qualification_phrase'].'</option>';
		}
		?>
	</select></div></div>

	<div class="fieldLabel" id="district_id_lbl"><?php tp('Qualification'); ?> (<?php tp('secondary');?>)</div><div class="fieldInput">
	<div  class="leftBorderPad"><input type="checkbox" name="showQualSecond" <?php  if ($this->criteria['showQualSecond']) echo 'CHECKED';?> /></div>
  	<div  class="leftBorder"><select id="qualification_secondary_id" name="qualification_secondary_id">
		<option value="">--<?php tp('All');?>--</option>
		<?php
			foreach ( $this->qualifications_secondary as $vals ) {
				echo '<option value="'.$vals['id'].'" '.((@$this->criteria['qualification_secondary_id']) == $vals['id'] ? 'SELECTED':'').' >'.$vals['qualification_phrase'].'</option>';
		}
		?>
	</select></div></div>

<?php if ( $this->mode != 'count' ) { ?>
  	<div  id="firstAutoComplete">
  	    <div class="fieldLabel"><?php echo (@$this->translation['First Name']); ?></div>
        <div class="fieldInput">
        <div  class="leftBorderPad"><input type="checkbox" name="showFirstName" checked disabled <?php  if ($this->criteria['showFirstName']) echo 'CHECKED';?> /></div>
        <div  class="leftBorder"><input id="first_name" type="text" name="first_name" value="<?php echo $this->criteria['first_name'];?>" /><div class="clear"></div><div id="firstContainer" class="autoComplete"></div></div></div>
  	</div>
  <script type="text/javascript">
  	var firstAuto = makeAutocomplete('first_name', 'firstContainer', '<?php echo $this->base_url;?>/person/firstList/outputType/text/' );
  </script>
  	<div id="lastAutoComplete">
  	    <div class="fieldLabel"><?php echo (@$this->translation['Last Name']); ?></div>
        <div class="fieldInput">
        <div  class="leftBorderPad"><input type="checkbox" name="showLastName" checked disabled <?php  if ($this->criteria['showLastName']) echo 'CHECKED';?> /></div>
        <div  class="leftBorder"><input id="last_name" type="text" name="last_name" value="<?php echo $this->criteria['last_name'];?>" /><div class="clear"></div><div id="lastContainer" class="autoComplete"></div></div></div>
  	</div>
  <script type="text/javascript">
  	var lastAuto = makeAutocomplete('last_name', 'lastContainer', '<?php echo $this->base_url;?>/person/lastList/outputType/text/' );
  </script>
<?php } ?>

<?php if ( $this->mode != 'count' ) { ?>
	<div class="fieldLabel" id="training_title_option_id_lbl"><?php tp('Classes taken'); ?></div>
	<div class="fieldInput"><div  class="leftBorderPad"><input type="checkbox" name="showTrainingTitle" <?php  if ($this->criteria['showTrainingTitle']) echo 'CHECKED';?> /></div>
  	<div  class="leftBorder">
	<select id="training_title_id" name="training_title_id" >
		<option value="">--<?php tp('All');?>--</option>
		<?php
			foreach ( $this->courses as $vals ) {
				echo '<option value="'.$vals['id'].'" '.((@$this->criteria['training_title_id']) == $vals['id']? 'SELECTED':'').' >'.$this->truncate($vals['training_title_phrase']).'</option>';
		}
		?>
	</select></div></div>
	<div class="fieldLabel" id="upcoming_id_lbl"><?php tp('Upcoming classes'); ?></div>
	<div class="fieldInput"><div  class="leftBorderPad"><input type="checkbox" name="showUpcoming" <?php  if ($this->criteria['showUpcoming']) echo 'CHECKED';?> /></div>
  	<div  class="leftBorder">
	<select id="upcoming_id" name="upcoming_id" >
		<option value="">--<?php tp('All');?>--</option>
		<?php
			foreach ( $this->upcoming as $vals ) {
				echo '<option value="'.$vals['id'].'" '.((@$this->criteria['upcoming_id']) == $vals['id']? 'SELECTED':'').' >'.$this->truncate($vals['training_title']).'</option>';
		}
		?>
	</select></div></div>
<?php } ?>

<!--
	<div class="fieldLabel" id="training_topic_id_lbl"><?php tp('Training topic');?></div>
	<div class="fieldInput">
	<div  class="leftBorderPad"><input type="checkbox" name="showTopic" <?php  if ($this->criteria['showTopic']) echo 'CHECKED';?> /></div>
  	<div  class="leftBorder">
	<select id="training_topic_id" name="training_topic_id" >
		<option value="">--<?php tp('All');?>--</option>
		<?php
			foreach ( $this->topics as $vals ) {
				echo '<option value="'.$vals['id'].'" '.((@$this->criteria['training_topic_id']) == $vals['id']? 'SELECTED':'').' >'.($vals['training_topic_phrase']).'</option>';
		}
		?>
	</select></div></div>
-->

<!--
	<div class="fieldLabel" id="training_topic_recommend_id_lbl"><?php tp('Recommended classes');?></div>
	<div class="fieldInput">
	<div  class="leftBorderPad"><input type="checkbox" name="showCourseRecommend" <?php  if ($this->criteria['showCourseRecommend']) echo 'CHECKED';?> /></div>
  	<div  class="leftBorder">
	<select id="course_recommend_id" name="course_recommend_id" >
		<option value="">--<?php tp('All');?>--</option>
		<?php
			foreach ( $this->courses as $vals ) {
				echo '<option value="'.$vals['id'].'" '.((@$this->criteria['course_recommend_id']) == $vals['id']? 'SELECTED':'').' >'.$this->truncate($vals['training_title_phrase']).'</option>';
		}
		?>
	</select></div></div>
-->


	<div class="fieldLabel" id="training_topic_recommend_id_lbl"><?php tp('Recommended topics');?></div>
	<div class="fieldInput">
	<div  class="leftBorderPad"><input type="checkbox" name="showTopicRecommend" <?php  if ($this->criteria['showTopicRecommend']) echo 'CHECKED';?> /></div>
  	<div  class="leftBorder">
	<select id="training_topic_recommend_id" name="training_topic_recommend_id" >
		<option value="">--<?php tp('All');?>--</option>
		<?php
			foreach ( $this->topicsRecommend as $vals ) {
				echo '<option value="'.$vals['id'].'" '.((@$this->criteria['training_topic_recommend_id']) == $vals['id']? 'SELECTED':'').' >'.($vals['training_topic_phrase']).'</option>';
		}
		?>
	</select></div></div>



	<!--
	<div class="fieldLabel" id="training_pepfar_id_lbl"><?php print $this->translation['PEPFAR Category'];?></div>
	<div class="fieldInput">
	<div  class="leftBorderPad"><input type="checkbox" name="showPepfar" <?php  if ($this->criteria['showPepfar']) echo 'CHECKED';?> /></div>
  	<div  class="leftBorder">
	<select id="training_pepfar_id" name="training_pepfar_id" >
		<option value="">--<?php tp('All');?>--</option>
		<?php
			foreach ( $this->pepfars as $vals ) {
				echo '<option value="'.$vals['id'].'" '.((@$this->criteria['training_pepfar_id']) == $vals['id']? 'SELECTED':'').' >'.($this->truncate($vals['pepfar_category_phrase'],45)).'</option>';
		}
		?>
	</select></div></div>
	<div class="fieldLabel" id="training_gender_lbl">Gender</div>
	<div class="fieldInput">
	<div  class="leftBorderPad"><input type="checkbox" name="showGender" <?php  if ($this->criteria['showGender']) echo 'CHECKED';?> /></div>
  	<div  class="leftBorder">
	<select id="training_gender" name="training_gender" >
		<option value="">--<?php tp('All');?>--</option>
		<option value="male" <?php echo (@$this->criteria['training_gender'] == 'male'? 'SELECTED':''); ?> ><?php echo t('Male') ?></option>
		<option value="female"  <?php echo (@$this->criteria['training_gender'] == 'female'? 'SELECTED':''); ?> ><?php echo t('Female') ?></option>
		<option value="na"  <?php echo (@$this->criteria['training_gender'] == 'na'? 'SELECTED':''); ?> ><?php echo t('N/A') ?></option>
	</select></div></div>
 <?php if ($this->setting['display_people_active']) { ?>
	<div class="fieldLabel" id="training_active_lbl"><?php echo (@$this->translation['Is Active']); ?></div>
	<div class="fieldInput">
	<div  class="leftBorderPad"><input type="checkbox" name="showActive" <?php  if ($this->criteria['showActive']) echo 'CHECKED';?> /></div>
  	<div  class="leftBorder">
	<select id="training_active" name="training_active" >
		<option value="">--<?php tp('All');?>--</option>
		<option value="active" <?php echo (@$this->criteria['training_active'] == 'active'? 'SELECTED':''); ?> >active</option>
		<option value="inactive"  <?php echo (@$this->criteria['training_active'] == 'inactive'? 'SELECTED':''); ?> >inactive</option>
	</select></div></div>
<?php } ?>
-->


<?php if ( $this->mode != 'count' ) { ?>
	<div class="fieldLabel" id="training_phone_lbl"><?php tp('Email');?></div>
	<div class="fieldInput">
	<div  class="leftBorderPad"><input type="checkbox" name="showEmail" <?php  if ($this->criteria['showEmail']) echo 'CHECKED';?> /></div>
  	<div  class="leftBorder">
	</div></div>
	<div class="fieldLabel" id="training_phone_lbl"><?php tp('Phone');?></div>
	<div class="fieldInput">
	<div  class="leftBorderPad"><input type="checkbox" name="showPhone" <?php  if ($this->criteria['showPhone']) echo 'CHECKED';?> /></div>
  	<div  class="leftBorder">
	</div></div>
<?php } ?>

</div>

<?php if ( $this->mode != 'count' ) { ?>
	<div class="fieldLabel">&nbsp;</div>
   	<div class="fieldInput" style="margin-top:1em;"><input type="checkbox" name="concatNames"  <?php  if ($this->criteria['concatNames']) echo 'CHECKED';?> /><label for="concatNames" ><?php tp("Combine First and Last Names");?></label></div>
<?php } ?>
	<div class="clear"></div>
	<input type="hidden" name="limit" id="limit" value="1" />
   	<input type="submit" class="submitNoArrow" name="go" value="Preview" />
   </fieldset>
   </form>
<?php if ( $this->criteria['go'] ) { ?>
<div class="hrGrey"></div>
    <div class="fieldIndentNoMargin"><?php tp('People');?> <span class="total"><?php echo $this->count;?> <?php //tp('Trainings Attended');?></span><?php echo $this->printAndExport();?></div>

    <div id="trainings"  class="itechTable"></div>
    <script type="text/javascript">

    	        var formatViewUrl = function(elCell, oRecord, oColumn, sData) {
	            elCell.innerHTML = "<a href='<?php echo $this->base_url;?>/person/view/id/" + oRecord.getData("id") + "'>" + sData + "</a>";
	        };


var trainingData = [
<?php $isFirstRow = true;
$cnt = 0;
foreach($this->results as $row) {
	if ( (!@$_REQUEST['limit'])  or ($cnt < 100) ) {
	if (!$isFirstRow )
		echo ',';
	$isFirstRow = false;
	echo '['.(isset($row['cnt'])?$row['cnt']:$row['id']);
	if ( isset($row['id']) and !$this->criteria['concatNames'])
		echo ',"'.$row['first_name'].'"';
	if ( isset($row['id']) and !$this->criteria['concatNames'] && $this->setting['display_middle_name'] && !$this->setting['display_middle_name_last'])
		echo ',"'.$row['middle_name'].'"';
	if ( isset($row['id']) and !$this->criteria['concatNames'])
		echo ',"'.$row['last_name'].'"';
	if ( isset($row['id']) and !$this->criteria['concatNames'] && $this->setting['display_middle_name'] && $this->setting['display_middle_name_last'])
		echo ',"'.$row['middle_name'].'"';
	if ( isset($row['id']) and $this->criteria['concatNames'])
		echo ',"'.$row['name'].'"';
	if ( isset($row['id']) and $this->criteria['showEmail'])
		echo ',"'.$row['email'].'"';
	if ( isset($row['id']) and $this->criteria['showPhone'])
		echo ',"'.$row['phone'].'"';
	if ( $this->criteria['showGender'] )
		echo ',"'.$row['gender'].'"';
	if ( $this->criteria['showActive'] )
		echo ',"'.$row['active'].'"';
	if ( $this->criteria['showProvince'] )
		echo ',"'.$row['province_name'].'"';
	if ( $this->criteria['showDistrict'] )
		echo ',"'.$row['district_name'].'"';
  if ( $this->criteria['showRegionC'] )
    echo ',"'.$row['region_c_name'].'"';
	if ( $this->criteria['showFacility'] )
		echo ',"'.$row['facility_name'].'"';
	if ( $this->criteria['showTrainingTitle'] )
		echo ',"'.$row['training_title'].'"';
	if ( $this->criteria['showQualPrim'] )
		echo ',"'.$row['qualification_phrase'].'"';
	if ( $this->criteria['showQualSecond'] )
		echo ',"'.$row['qualification_secondary_phrase'].'"';
	if ( $this->criteria['showTopic'] )
		echo ',"'.$row['training_topic_phrase'].'"';
	if ( (!$this->criteria['doCount']) AND $this->criteria['showUpcoming'] )
		echo ',"'.$row['upcoming'].'"';
	if ( $this->criteria['showTopicRecommend'] )
		echo ',"'.$row['recommended'].'"';
	if ( $this->criteria['showPepfar'] )
		echo ',"'.$row['pepfar_category_phrase'].'"';
	echo "]";
	$cnt++;
	}
	}
   ?>];

var trainingColumnDefs = [
<?php if (isset($this->results[0]['cnt'])) { ?>
{key:"cnt", label: "<?php tp('Person Count');?>", sortable:true, resizeable:true}
<?php } else { ?>
	{key:"id", label: "ID", sortable:true, resizeable:true, formatter: formatViewUrl}

	<?php if ( !$this->criteria['concatNames'] ) { ?>
		,{key:"first_name", label: "<?php echo (@$this->translation['First Name']); ?>", sortable:true, resizeable:true}
   <?php if ( $this->setting['display_middle_name'] && !$this->setting['display_middle_name_last'] ) { ?>
		    ,{key:"middle_name", label: "<?php echo (@$this->translation['Middle Name']); ?>", sortable:true, resizeable:true}
	<?php }?>

		,{key:"last_name", label: "<?php echo (@$this->translation['Last Name']); ?>", sortable:true, resizeable:true}

   <?php if ( $this->setting['display_middle_name'] && $this->setting['display_middle_name_last'] ) { ?>
		    ,{key:"middle_name", label: "<?php echo (@$this->translation['Middle Name']); ?>", sortable:true, resizeable:true}
	<?php }?>
	<?php } else { ?>
		,{key:"name", label: "<?php tp('Name');?>", sortable:true, resizeable:true}
	<?php } ?>
<?php if ( $this->criteria['showEmail'] ) { ?>
   ,{key:"email", label: "<?php tp('Email');?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showPhone'] ) { ?>
   ,{key:"phone", label: "<?php tp('Phone');?>", sortable:true, resizeable:true}
 <?php } ?>

<?php } ?>
<?php if ( $this->criteria['showGender'] ) { ?>
   ,{key:"gender", label: "<?php tp('Gender');?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showActive'] ) { ?>
   ,{key:"active", label: "<?php echo (@$this->translation['Is Active']); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showProvince'] ) { ?>
    ,{key:"province_name", label: "<?php echo (@$this->translation['Region A (Province)']); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showDistrict'] ) { ?>
   ,{key:"district_name", label: "<?php echo (@$this->translation['Region B (Health District)']); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showRegionC'] ) { ?>
   ,{key:"region_c_name", label: "<?php echo (@$this->translation['Region C (Local Region)']); ?>", sortable:true, resizeable:true}
 <?php } ?>
 <?php if ( $this->criteria['showFacility'] ) { ?>
   ,{key:"facility_name", label: "<?php tp('Facility');?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showTrainingTitle'] ) { ?>
   ,{key:"training_title", label: "<?php tp('Classes taken'); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showQualPrim'] ) { ?>
   ,{key:"qualification_phrase", label: "<?php tp('Qualification') . ' ' . tp('(primary)');?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showQualSecond'] ) { ?>
   ,{key:"qualification_secondary_phrase", label: "<?php tp('Qualification') . ' ' . tp('(secondary)');?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showTopic'] ) { ?>
   ,{key:"training_topic_phrase", label: "<?php tp('Training Topic');?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( (!$this->criteria['doCount']) AND $this->criteria['showUpcoming'] ) { ?>
   ,{key:"upcoming", label: "<?php tp('Upcoming classes');?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showTopicRecommend'] ) { ?>
   ,{key:"recommended", label: "<?php tp('Recommended');?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showPepfar'] ) { ?>
   ,{key:"pepfar_category_phrase", label: "<?php tp('PEPFAR');?>", sortable:true, resizeable:true}
 <?php } ?>
];

	makeDataTable("trainings", null, trainingData, trainingColumnDefs);
</script>
<?php if ($cnt < count($this->results)) { ?>
[<?php tp('Limited to 100 rows');?>]  <a href="<?php echo str_replace('limit=1','limit=0',$_SERVER['REQUEST_URI']);?>"><?php tp('Full Results');?></a>
<?php } ?>
<?php } ?>
  </div>
  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>


</div>

</body>
</html>
