<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title><?php echo $this->translation['Application Name'];?> | <?php tp('Participants Report');?></title>
<?php
require_once('views/helpers/Location.php');
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();

$checkLabel = t('show');
if ( $this->mode == 'count' )
	$checkLabel = 'group';

?>

<script language="javascript">
function setDistrictStatus(selectedIndex)  {
	<?php if ( $this->setting['display_region_b'] ) { ?>
	var districtObj = YAHOO.util.Dom.get('district_id');
	if ( districtObj ) {
		if ( selectedIndex ) {
			districtObj.disabled = false;
			filterSubTypeOptions('province_id','district_id');
		} else {
			districtObj.selectedIndex = 0;
			districtObj.disabled = true;
		}
	}
 <?php } ?>
}
</script>

</head>
<body class="yui-skin-sam" onload="filterSubTypeOptions('province_id','district_id');">
<div id="pageHolder">

  <div id="header"><?php require_once('views/scripts/header.phtml');?></div>
  <div id="content">

    <h1><?php tp('Participant Reports');?></h1>
    	<?php require_once('peopleReportsPicker.phtml'); ?>
	   <form action="" method="get">
   <fieldset id="criteria" ><legend><?php tp('Select Criteria');?></legend>
 <div id="dividers">

      	<div class="fieldLabel" ></div>
    	<div class="fieldInput  criteria-header"><div   class="criteria-label"><?php echo $checkLabel;?></div><div  class="criteria-label" style="padding-left: 20px;"><?php tp('filter');?></div></div>

	<!--TA:38 change for multiple selection region_filters_dropdown($this, $this->locations, $this->criteria, false, true); -->
	<?php region_filters_dropdown($this, $this->locations, $this->criteria, true, true); ?>

	<div id="facilityAutoComplete">
	    <div class="fieldLabel" id="facilityInput_lbl"><?php tp('Facility');?></div>
	    <div class="fieldInput">
	    <div  class="leftBorderPad"><input type="checkbox" name="showFacility" <?php  if ($this->criteria['showFacility']) echo 'CHECKED';?> /></div>
	    <div  class="leftBorder">
	    <select id="facilityInput" name="facilityInput" >
	<option value="">--<?php tp('choose');?>--</option>
	<?php
		foreach ( $this->facilities as $vals ) {
			echo '<option value="'.$vals['id'].'" '.($this->criteria['facilityInput'] == $vals['id']?'SELECTED':'').'>'.$vals['facility_name'].'</option>';
	}
	?>
</select>
	    </div></div>
	</div>
	<div class="fieldLabel" id="type_id_lbl"><?php tp('Facility Type');?></div>
    <div class="fieldInput"><div  class="leftBorderPad"><input type="checkbox" name="showType"   <?php  if ($this->criteria['showType'] or ($this->mode == 'search' )) echo 'CHECKED';?> /></div><label for="showType" ></label>
	<div  class="leftBorder">
	<select id="facility_type_id" name="facility_type_id" >
		<option value="">--<?php tp('All');?>--</option>
		<?php
			foreach ( $this->facility_types as $vals ) {
				echo '<option value="'.$vals['id'].'" '.((@$this->criteria['facility_type_id']) == $vals['id']? 'SELECTED':'').' >'.$vals['facility_type_phrase'].'</option>';
		}
		?>
	</select></div></div>
	<div class="fieldLabel" id="sponsor_id_lbl"><?php tp('Facility Sponsor');?></div>
    <div class="fieldInput"><div  class="leftBorderPad"><input type="checkbox" name="showSponsor"  <?php  if ($this->criteria['showSponsor'] or ($this->mode == 'search' )) echo 'CHECKED';?> /></div><label for="showSponsor" ></label>
	<div  class="leftBorder">
	<select id="facility_sponsor_id" name="facility_sponsor_id" >
		<option value="">--<?php tp('All');?>--</option>
		<?php
			foreach ( $this->facility_sponsors as $vals ) {
				echo '<option value="'.$vals['id'].'" '.((@$this->criteria['facility_sponsor_id']) == $vals['id']? 'SELECTED':'').' >'.$vals['facility_sponsor_phrase'].'</option>';
		}
		?>
	</select></div></div>
	<div class="fieldLabel" id="training_title_option_id_lbl"><?php echo (@$this->translation['Training Name']); ?></div>
	<div class="fieldInput">
	<div  class="leftBorderPad"><input type="checkbox" name="showTrainingTitle" <?php  if ($this->criteria['showTrainingTitle']) echo 'CHECKED';?> /></div>
  	<div class="leftBorder autoHeight autoWidth">
  	<!-- TA:69 expend to ??? style="min-width:780px;" -->
	<select id="training_title_id" name="training_title_id[]" multiple="multiple" size="10" style="min-width:600px;">
		<option value="" <?php if (is_array($this->criteria['training_title_id']) && in_array("", $this->criteria['training_title_id'])) echo "selected"; ?>>--<?php tp('All');?>--</option>
		<?php
		//TA:69 remove trancate values, show whole values, display titles=item value as mouse over
			foreach ( $this->courses as $vals ) {
				echo '<option title="'.$vals['training_title_phrase'].'" value="'.$vals['id'].'"
				     '.((@$this->criteria['training_title_id']) == $vals['id'] || @in_array($vals['id'], $this->criteria['training_title_id'])? 'SELECTED':'').' >'
				     .$vals['training_title_phrase'].'</option>';

		}
		?>
	</select></div></div>


	<div class="fieldLabel" id="training_organizer_id_lbl"><?php echo (@$this->translation['Training Organizer']); ?></div>
	<div class="fieldInput">
	<div  class="leftBorderPad"><input type="checkbox" name="showOrganizer" <?php  if ($this->criteria['showOrganizer']) echo 'CHECKED';?> /></div>
  	<div  class="leftBorder autoHeight">
  	

<?php echo $this->organizers_dropdown; ?><br />
	
	
	</div>
	</div>
	
  <?php if ( $this->setting['display_training_topic'] ) { ?>
	<div class="fieldLabel" id="training_topic_id_lbl"><?php echo (@$this->translation['Training Topic']); ?></div>
	<div class="fieldInput">
	<div  class="leftBorderPad"><input type="checkbox" name="showTopic" <?php  if ($this->criteria['showTopic']) echo 'CHECKED';?> /></div>
  	<div  class="leftBorder">
	<select id="training_topic_id" name="training_topic_id" >
		<option value="">--<?php tp('All');?>--</option>
		<?php
			foreach ( $this->topics as $vals ) {
				echo '<option value="'.$vals['id'].'" '.((@$this->criteria['training_topic_id']) == $vals['id']? 'SELECTED':'').' >'.($vals['training_topic_phrase']).'</option>';
		}
		?>
	</select></div></div>
	<?php } ?>

	<div class="fieldLabel" id="training_pepfar_id_lbl"><?php print $this->translation['PEPFAR Category'];?></div>
	<div class="fieldInput">
	<div  class="leftBorderPad"><input type="checkbox" name="showPepfar" <?php  if ($this->criteria['showPepfar']) echo 'CHECKED';?> /></div>
  	<div  class="leftBorder">
	<select id="training_pepfar_id" name="training_pepfar_id" >
		<option value="">--<?php tp('All');?>--</option>
		<?php
			foreach ( $this->pepfars as $vals ) {
				echo '<option value="'.$vals['id'].'" '.((@$this->criteria['training_pepfar_id']) == $vals['id']? 'SELECTED':'').' >'.($this->truncate($vals['pepfar_category_phrase'],45)).'</option>';
		}
		?>
	</select></div></div>


 	<?php if ( $this->setting['display_funding_options']) { ?>
	<div class="fieldLabel" id="training_funding_id_lbl"><?php tp('Funding'); ?></div>
	<div class="fieldInput"><div  class="leftBorderPad" ><input type="checkbox" name="showFunding"   <?php  if ($this->criteria['showFunding']) echo 'CHECKED';?> /></div><label for="showFunding" ></label>

	<div  class="leftBorder"><select id="funding_id" name="funding_id" >
		<option value="">--<?php tp('All');?>--</option>
		<?php
			foreach ( $this->funding as $vals ) {
				echo '<option value="'.$vals['id'].'" '.((@$this->criteria['funding_id']) == $vals['id']? 'SELECTED="selected"':'').' >'.($this->truncate($vals['funding_phrase'],45)).'</option>';
		}
		?>
	</select></div></div>
	<?php } ?>

	<?php if ( $this->setting['display_people_custom1'] ) { ?>
	<div class="fieldLabel" id="person_custom1_lbl"><?php print $this->translation['People Custom 1']; ?></div>
	<div class="fieldInput"><div  class="leftBorderPad" ><input type="checkbox" name="showCustom1"   <?php  if ($this->criteria['showCustom1']) echo 'CHECKED';?> /></div><label for="showCustom1" ></label>

	<div  class="leftBorder"><select id="custom_1_id" name="custom_1_id" >
		<option value="">--<?php tp('All');?>--</option>
		<?php
			foreach ( $this->custom1 as $vals ) {
				echo '<option value="'.$vals['id'].'" '.((@$this->criteria['custom_1_id']) == $vals['id']? 'SELECTED="selected"':'').' >'.($this->truncate($vals['custom1_phrase'],45)).'</option>';
		}
		?>
	</select></div></div>
	<?php } ?>

	<?php if ( $this->setting['display_people_custom2'] ) { ?>
	<div class="fieldLabel" id="person_custom2_lbl"><?php print $this->translation['People Custom 2']; ?></div>
	<div class="fieldInput"><div  class="leftBorderPad" ><input type="checkbox" name="showCustom2"   <?php  if ($this->criteria['showCustom2']) echo 'CHECKED';?> /></div><label for="showCustom2" ></label>
	<div  class="leftBorder"><select id="custom_2_id" name="custom_2_id" >
		<option value="">--<?php tp('All');?>--</option>
		<?php
			foreach ( $this->custom2 as $vals ) {
				echo '<option value="'.$vals['id'].'" '.((@$this->criteria['custom_2_id']) == $vals['id']? 'SELECTED="selected"':'').' >'.($this->truncate($vals['custom2_phrase'],45)).'</option>';
		}
		?>
	</select></div></div>
	<?php } ?>

	<?php if ( $this->setting['display_people_custom3'] ) { ?>
	<div class="fieldLabel" id="person_custom3_lbl"><?php print $this->translation['People Custom 3']; ?></div>
	<div class="fieldInput"><div  class="leftBorderPad" ><input type="checkbox" name="showCustom3"   <?php  if ($this->criteria['showCustom3']) echo 'CHECKED';?> /></div><label for="showCustom3" ></label>
	<div  class="leftBorder"><select id="custom_3_id" name="custom_3_id" >
		<option value="">--<?php tp('All');?>--</option>
		<?php
			foreach ( $this->custom3 as $vals ) {
				if(! trim($vals['custom_3']))
					continue;
				echo '<option value="'.$vals['custom_3'].'" '.((@$this->criteria['custom_3_id']) == $vals['custom_3']? 'SELECTED="selected"':'').' >'.($this->truncate($vals['custom_3'],45)).'</option>';
		}
		?>
	</select></div></div>
	<?php } ?>

	<?php if ( $this->setting['display_people_custom4'] ) { ?>
	<div class="fieldLabel" id="person_custom4_lbl"><?php print $this->translation['People Custom 4']; ?></div>
	<div class="fieldInput"><div  class="leftBorderPad" ><input type="checkbox" name="showCustom4"   <?php  if ($this->criteria['showCustom4']) echo 'CHECKED';?> /></div><label for="showCustom4" ></label>
	<div  class="leftBorder"><select id="custom_4_id" name="custom_4_id" >
		<option value="">--<?php tp('All');?>--</option>
		<?php
			foreach ( $this->custom4 as $vals ) {
				if(! trim($vals['custom_4']))
					continue;
				echo '<option value="'.$vals['custom_4'].'" '.((@$this->criteria['custom_4_id']) == $vals['custom_4']? 'SELECTED="selected"':'').' >'.($this->truncate($vals['custom_4'],45)).'</option>';
		}
		?>
	</select></div></div>
	<?php } ?>

	<?php if ( $this->setting['display_people_custom5'] ) { ?>
	<div class="fieldLabel" id="person_custom5_lbl"><?php print $this->translation['People Custom 5']; ?></div>
	<div class="fieldInput"><div  class="leftBorderPad" ><input type="checkbox" name="showCustom5"   <?php  if ($this->criteria['showCustom5']) echo 'CHECKED';?> /></div><label for="showCustom5" ></label>
	<div  class="leftBorder"><select id="custom_5_id" name="custom_5_id" >
		<option value="">--<?php tp('All');?>--</option>
		<?php
			foreach ( $this->custom5 as $vals ) {
				if(! trim($vals['custom_5']))
					continue;
				echo '<option value="'.$vals['custom_5'].'" '.((@$this->criteria['custom_5_id']) == $vals['custom_5']? 'SELECTED="selected"':'').' >'.($this->truncate($vals['custom_5'],45)).'</option>';
		}
		?>
	</select></div></div>
	<?php } ?>

	<div class="fieldLabel" id="training_gender_lbl"><?php tp('Gender');?></div>
	<div class="fieldInput">
	<div  class="leftBorderPad"><input type="checkbox" name="showGender" <?php  if ($this->criteria['showGender']) echo 'CHECKED';?> /></div>
  	<div  class="leftBorder">
	<select id="training_gender" name="training_gender" >
		<option value="">--<?php tp('All');?>--</option>
		<option value="male" <?php echo (@$this->criteria['training_gender'] == 'male'? 'SELECTED':''); ?> ><?php tp('male');?></option>
		<option value="female"  <?php echo (@$this->criteria['training_gender'] == 'female'? 'SELECTED':''); ?> ><?php tp('female');?></option>
		<option value="na"  <?php echo (@$this->criteria['training_gender'] == 'na'? 'SELECTED':''); ?> ><?php tp('na');?></option>
	</select></div></div>
<div class="fieldLabel" id="qualification_option_id_lbl"><?php tp('Qualification');?></div>
  <div class="fieldInput"><div  class="leftBorderPad"><input type="checkbox" name="showQualification"  <?php  if ($this->criteria['showQualification']) echo 'checked="checked"';?> /></div><label for="showQualification" ></label>  <div  class="leftBorder">    <select id="qualification_option_id" name="qualification_option_id">
  <option value="">--<?php tp('choose');?>--</option>
  <?php
    $lastParent = null;
    foreach ( $this->qualifications as $vals ) {
    if ( !$vals['id'] ) {
      $lastParent = ($vals['parent_phrase']);
      echo '<option value="'.$vals['parent_id'].'" '.($this->criteria['qualification_option_id'] == $vals['parent_id'] ?'selected="selected"':'').'>'.htmlspecialchars($vals['parent_phrase']).'</option>';
    } else {
      echo '<option value="'.$vals['id'].'" '.($this->criteria['qualification_option_id'] == $vals['id'] ?'selected="selected"':'').'>&nbsp;&nbsp;'. htmlspecialchars($vals['qualification_phrase']).'</option>';
    }
  }
    ?>
</select></div></div>

<?php if ( $this->setting['display_people_age'] ) { ?>
  <div class="fieldLabel" id="training_age_lbl"><?php tp('Age');?></div>
  <div class="fieldInput">
  <div  class="leftBorderPad"><input type="checkbox" name="showAge" <?php  if ($this->criteria['showAge']) echo 'CHECKED';?> /></div>
    <div  class="leftBorder">
    <?php tp('min');?> <input type="text" id="age_min" name="age_min" size="4" value="<?php echo ( $this->criteria['age_min'] ? $this->criteria['age_min'] : '0');?>" /> <?php tp('max');?> <input type="text"  size="4" name="age_max" id="age_max" value="<?php echo ( $this->criteria['age_max'] ? $this->criteria['age_max'] : '');?>" /> <a href="#" id="clear_age" onclick="return clearAge();" ><?php tp('clear');?></a>
    </div></div>
<?php } ?>

 <?php if ($this->setting['display_people_active']) { ?>
	<div class="fieldLabel" id="training_active_lbl"><?php echo (@$this->translation['Is Active']); ?></div>
	<div class="fieldInput">
	<div  class="leftBorderPad"><input type="checkbox" name="showActive" <?php  if ($this->criteria['showActive']) echo 'CHECKED';?> /></div>
  	<div  class="leftBorder">
	<select id="training_active" name="training_active" >
		<option value="">--<?php tp('All');?>--</option>
		<option value="active" <?php echo (@$this->criteria['training_active'] == 'active'? 'SELECTED':''); ?> ><?php tp('active');?></option>
		<option value="inactive"  <?php echo (@$this->criteria['training_active'] == 'inactive'? 'SELECTED':''); ?> ><?php tp('inactive');?></option>
	</select></div></div>
<?php } ?>
<?php if ( strstr($path[2], 'participantsByName') !== FALSE  OR ( strstr($path[2], 'participants-by-name') !== FALSE )) { //TA:63?>
	<div class="fieldLabel" id="training_phone_lbl"><?php tp('Email');?></div>
	<div class="fieldInput">
	<div  class="leftBorderPad"><input type="checkbox" name="showEmail" <?php  if ($this->criteria['showEmail']) echo 'CHECKED';?> /></div>
  	<div  class="leftBorder">
	</div></div>
	<div class="fieldLabel" id="training_phone_lbl"><?php tp('Phone');?></div>
	<div class="fieldInput">
	<div  class="leftBorderPad"><input type="checkbox" name="showPhone" <?php  if ($this->criteria['showPhone']) echo 'CHECKED';?> /></div>
  	<div  class="leftBorder">
	</div></div>
<?php } ?>


 	<?php if ( $this->setting['display_training_trainers']) { ?>
	<div class="fieldLabel" id="is_tot_lbl"><?php echo (@$this->translation['Training of Trainers']); ?></div>
	<div class="fieldInput"><div  class="leftBorderPad"><input type="checkbox" name="showTot" <?php  if ($this->criteria['showTot']) echo 'CHECKED';?> /></div><label for="showTot" ></label>

	<div  class="leftBorder">
  <!--
  <select id="is_tot" name="is_tot">
		<option value="">--<?php tp('All');?>--</option>
		<?php
			foreach ( array(1 => 'Yes', 0 => 'No') as $val => $label ) {
				echo '<option value="'.$val.'" '.((is_numeric(@$this->criteria['is_tot']) && $this->criteria['is_tot'] == $val) ? 'SELECTED="selected"':'').' >'.t($label).'</option>';
		}
		?>
	</select>
  -->
  </div></div>
	<?php } ?>

</div>
	<div class="clear"></div><br /><br />
<div class="fieldLabel"><?php tp('Start date');?></div>
<div class="fieldInput" id="startdate">
    <?php tp('Day');?> <input id="start-day" class="dayfield" type="text" name="start-day" maxlength="2" value="<?php echo $this->criteria['start-day']; ?>"  >
    / <?php tp('Month');?> <input id="start-month" class="monthfield" type="text" name="start-month" maxlength="2" value="<?php echo $this->criteria['start-month']; ?>"  >
    / <?php tp('Year');?> <input id="start-year" class="yearfield" type="text" name="start-year" maxlength="4" value="<?php echo $this->criteria['start-year'];  ?>" >
		            <script  type="text/javascript">
		    YAHOO.util.Event.onDOMReady(function () {
		    	makeCalendar("startdate","start-day", "start-month", "start-year");
		    });
		</script>
	</div>
<div class="fieldLabel" style="padding-top:1em;"><?php tp('End date');?></div>
<div class="fieldInput" id="enddate" style="margin-top:1em;">
    <?php tp('Day');?> <input id="end-day" class="dayfield" type="text" name="end-day" maxlength="2" value="<?php echo $this->criteria['end-day']; ?>"  >
    / <?php tp('Month');?> <input id="end-month" class="monthfield" type="text" name="end-month" maxlength="2" value="<?php echo $this->criteria['end-month']; ?>"  >
    / <?php tp('Year');?> <input id="end-year" class="yearfield" type="text" name="end-year" maxlength="4" value="<?php echo $this->criteria['end-year'];  ?>" >
		            <script  type="text/javascript">
		    YAHOO.util.Event.onDOMReady(function () {
		    	makeAdditionalCalendar("enddate","end-day", "end-month", "end-year");
		    });
		</script>
	</div>
<?php if ( $this->mode != 'count' ) { ?>
	<div class="fieldLabel">&nbsp;</div>
   	<div class="fieldInput" style="margin-top:1em;"><input type="checkbox" name="concatNames"  <?php  if ($this->criteria['concatNames']) echo 'CHECKED';?> /><label for="concatNames" ><?php tp('Combine First and Last Names');?></label></div>
<?php } ?>
	<div class="clear"></div>
	<input type="hidden" name="limit" id="limit" value="1" />
   	<input type="submit" class="submitNoArrow" name="go" value="<?php tp('Preview');?>" />
   </fieldset>
   </form>
<?php if ( $this->criteria['go'] ) {

$hasTrainingInfo = false;
if ( $this->criteria['showTrainingTitle'] or $this->criteria['showTopic'] or $this->criteria['showTrainingTitle'] or $this->criteria['showPepfar'] )
	$hasTrainingInfo = true;

?>
<div class="hrGrey"></div>
<!-- TA:80 -->
    <div class="fieldIndentNoMargin"><?php tp('Participants');?> <span class="total"><?php echo $this->count;?> <?php tp('Participants');?> </span>
    <?php echo $this->printAndExport("trainings");?>
    <?php echo ($hasTrainingInfo? '<br/><span class="total">*'.t('Note: This report may contain multiple rows for participants who attended multiple').' '.t('trainings').'.</span>':''); ?>
    </div>

    <div id="trainings"  class="itechTable"></div>
    <script type="text/javascript">

    	        var formatViewUrl = function(elCell, oRecord, oColumn, sData) {
	            elCell.innerHTML = "<a href='<?php echo $this->base_url;?>/person/view/id/" + oRecord.getData("id") + "'>" + sData + "</a>";
	        };


var trainingData = [
<?php $isFirstRow = true;
$cnt = 0;
foreach($this->results as $row) {
	if ( (!@$_REQUEST['limit'])  or ($cnt < 100) ) {
	if (!$isFirstRow )
		echo ',';
	$isFirstRow = false;
	echo '['.(isset($row['cnt'])?$row['cnt']:$row['id']);
	if ( isset($row['id']) and !$this->criteria['concatNames'])
		echo ',"'.$row['first_name'].'"';
	if ( isset($row['id']) and !$this->criteria['concatNames'] && $this->setting['display_middle_name'] && !$this->setting['display_middle_name_last'])
		echo ',"'.$row['middle_name'].'"';
	if ( isset($row['id']) and !$this->criteria['concatNames'])
		echo ',"'.$row['last_name'].'"';
	if ( isset($row['id']) and !$this->criteria['concatNames'] && $this->setting['display_middle_name'] &&  $this->setting['display_middle_name_last'])
		echo ',"'.$row['middle_name'].'"';
	if ( isset($row['id']) and $this->criteria['concatNames'])
		echo ',"'.$row['name'].'"';
	if ( isset($row['id']) and $this->criteria['showEmail'])
		echo ',"'.$row['email'].'"';
	if ( isset($row['id']) and $this->criteria['showPhone'])
		echo ',"'.$row['phone'].'"';
	if ( $this->criteria['showGender'] )
		echo ',"'.$row['gender'].'"';
  if ( $this->criteria['showAge'] )
    echo ','.$row['age']    ;
		if ( $this->criteria['showActive'] )
		echo ',"'.$row['active'].'"';
	if ( $this->criteria['showProvince'] )
		echo ',"'.$row['province_name'].'"';
	if ( $this->criteria['showDistrict'] )
		echo ',"'.$row['district_name'].'"';
  if ( $this->criteria['showRegionC'] )
    echo ',"'.$row['region_c_name'].'"';
		if ( $this->criteria['showFacility'] )
		echo ',"'.$row['facility_name'].'"';
	if ( $this->criteria['showType'] )
		echo ',"'.$row['facility_type_phrase'].'"';
	if ( $this->criteria['showSponsor'] )
		echo ',"'.$row['facility_sponsor_phrase'].'"';
	if ( $this->criteria['showTrainingTitle'] )
		echo ',"'.$row['training_title'].'","'.$row['training_start_date'].'"';
	if ( $this->criteria['showQualification'] )
		echo ',"'.$row['qualification_phrase'].'"';
	if ( $this->criteria['showOrganizer'] )
		echo ',"'.$row['training_organizer_phrase'].'"';
	if ( $this->criteria['showTopic'] )
		echo ',"'.$row['training_topic_phrase'].'"';
    if ( $this->criteria['showPepfar'] )
        echo ',"'.$row['pepfar_category_phrase'].'"';
    if ( $this->criteria['showFunding'] )
        echo ',"'.$row['funding_phrase'].'"';
    if ( $this->criteria['showCustom1'] )
		echo ',"'.$row['custom1_phrase'].'"';
	if ( $this->criteria['showCustom2'] )
		echo ',"'.$row['custom2_phrase'].'"';
	if ( $this->criteria['showCustom3'] )
		echo ',"'.$row['custom3_phrase'].'"';
	if ( $this->criteria['showCustom4'] )
		echo ',"'.$row['custom4_phrase'].'"';
	if ( $this->criteria['showCustom5'] )
		echo ',"'.$row['custom5_phrase'].'"';
	if ( $this->criteria['showTot'] )
		echo ',"'.$row['is_tot'].'"';
	echo "]";
	$cnt++;
	}
	}
   ?>];

var trainingColumnDefs = [
<?php if (isset($this->results[0]['cnt'])) { ?>
{key:"cnt", label: "<?php tp('Participant Count');?>", sortable:false, resizeable:true}
<?php } else { ?>
	{key:"id", label: "<?php tp('ID')?>", sortable:false, resizeable:true, formatter: formatViewUrl}
	<?php if ( !$this->criteria['concatNames'] ) { ?>
		,{key:"first_name", label: "<?php echo (@$this->translation['First Name']); ?>", sortable:true, resizeable:true}
   <?php if ( $this->setting['display_middle_name'] && !$this->setting['display_middle_name_last'] ) { ?>
		    ,{key:"middle_name", label: "<?php echo (@$this->translation['Middle Name']); ?>", sortable:true, resizeable:true}
	<?php }?>
		,{key:"last_name", label: "<?php echo (@$this->translation['Last Name']); ?>", sortable:true, resizeable:true}
   <?php if ( $this->setting['display_middle_name'] && $this->setting['display_middle_name_last'] ) { ?>
		    ,{key:"middle_name", label: "<?php echo (@$this->translation['Middle Name']); ?>", sortable:true, resizeable:true}
	<?php }?>

	<?php } else { ?>
		,{key:"name", label: "<?php tp('Name');?>", sortable:true, resizeable:true}
	<?php } ?>
<?php if ( $this->criteria['showEmail'] ) { ?>
   ,{key:"email", label: "<?php tp('Email');?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showPhone'] ) { ?>
   ,{key:"phone", label: "<?php tp('Phone');?>", sortable:true, resizeable:true}
 <?php } ?>
<?php } ?>
<?php if ( $this->criteria['showGender'] ) { ?>
   ,{key:"gender", label: "<?php tp('Gender');?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showAge'] ) { ?>
   ,{key:"age", label: "<?php tp('Age');?>", sortable:true, resizeable:true}
 <?php } ?>
 <?php if ( $this->criteria['showActive'] ) { ?>
  ,{key:"active", label: "<?php echo (@$this->translation['Is Active']); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showProvince'] ) { ?>
    ,{key:"province_name", label: "<?php echo (@$this->translation['Region A (Province)']); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showDistrict'] ) { ?>
   ,{key:"district_name", label: "<?php echo (@$this->translation['Region B (Health District)']); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showRegionC'] ) { ?>
   ,{key:"region_c_name", label: "<?php echo (@$this->translation['Region C (Local Region)']); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showFacility'] ) { ?>
   ,{key:"facility_name", label: "<?php tp('Facility');?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showType'] ) { ?>
   ,{key:"facility_type_phrase", label: "<?php tp('Type');?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showSponsor'] ) { ?>
   ,{key:"facility_sponsor_phrase", label: "<?php tp('Sponsor');?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showTrainingTitle'] ) { ?>
   ,{key:"training_title", label: "<?php echo (@$this->translation['Training Name']); ?>", sortable:true, resizeable:true}
   ,{key:"training_start_date", label: "<?php tp('Date'); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php  if ( $this->criteria['showQualification'] ) { ?>
   ,{key:"qualification_phrase", label: "<?php tp('Qualification');?>", sortable:true, resizeable:true}
 <?php } ?>
 <?php if ( $this->criteria['showOrganizer'] ) { ?>
   ,{key:"training_organizer_phrase", label: "<?php echo (@$this->translation['Training Organizer']); ?>", sortable:true, resizeable:true}
 <?php } ?>

<?php if ( $this->criteria['showTopic'] ) { ?>
   ,{key:"training_topic_phrase", label: "<?php echo (@$this->translation['Training Topic']); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showPepfar'] ) { ?>
   ,{key:"pepfar_category_phrase", label: "<?php tp('PEPFAR');?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showFunding'] ) { ?>
   ,{key:"funding_phrase", label: "<?php tp('Funding');?>", sortable:true, resizeable:true}
 <?php } ?>
 <?php 	if ( $this->criteria['showCustom1'] ) { ?>
  ,{key:"custom1_phrase", label: "<?php echo (@$this->translation['People Custom 1']); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php 	if ( $this->criteria['showCustom2'] ) { ?>
  ,{key:"custom2_phrase", label: "<?php echo (@$this->translation['People Custom 2']); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php 	if ( $this->criteria['showCustom3'] ) { ?>
  ,{key:"custom3_phrase", label: "<?php echo (@$this->translation['People Custom 3']); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php 	if ( $this->criteria['showCustom4'] ) { ?>
  ,{key:"custom4_phrase", label: "<?php echo (@$this->translation['People Custom 4']); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php 	if ( $this->criteria['showCustom5'] ) { ?>
  ,{key:"custom5_phrase", label: "<?php echo (@$this->translation['People Custom 5']); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showTot'] ) { ?>
   ,{key:"is_tot", label: "<?php echo tp('TOT'); ?>", sortable:true, resizeable:true}
 <?php } ?>

];

	makeDataTable("trainings", null, trainingData, trainingColumnDefs);
</script>
<?php if ($cnt < count($this->results)) { ?>
[<?php tp('Limited to 100 rows');?>]  <a href="<?php echo str_replace('limit=1','limit=0',$_SERVER['REQUEST_URI']);?>"><?php tp('Full Results');?></a>
<?php } ?>
<?php } ?>
  </div>
  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>

</div>

</body>
</html>
