<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title><?php echo $this->translation['Application Name'] . " | " . $this->pageTitle; ?></title>
	<?php
	require_once('views/helpers/Location.php');
	require_once('views/helpers/ScriptContainer.php');
	print ScriptContainer::$instance->renderCSSHead();
	print ScriptContainer::$instance->renderJSHead();
	?>

</head>
<body class="yui-skin-sam"  >

	<div id="pageHolder">

		<div id="header"><?php require_once('views/scripts/header.phtml');?></div>
		<div id="content">

			<h1><?php tp('Partner Report');?></h1>
			<form action="" method="GET" class="form_employee">
				<fieldset id=""><legend><?php tp('Select Criteria');?></legend>

					<?php
						$cal = '<a class="calendarbtn" href="#"><img src="'.$this->base_url.'/js/yui/assets/calbtn.gif"></a>';
						$this->required_fields = array();
						$this->calendar_fields = array('start_date','end_date');

						if($this->setting['display_employee_partner'])
							echo labelAndField($this, t('Partner'), $this->partners, 'partner');
						if($this->setting['display_employee_sub_partner'])
							echo labelAndField($this, t('Sub Partner'), $this->subpartners, 'sub_partner');
						echo region_filters_dropdown( $this, $this->locations, $this->criteria, false, false );
						if ( $this->setting['display_employee_site_name'] )
							echo labelAndField($this, t('Site').space.t('Name'), renderFacilityDropDown($this->facilities, $this->criteria['facilityInput']), 'site');
						if ( $this->setting['display_employee_site_name'] )
							echo labelAndField($this, t('Facility Type'), $this->facilitytypes, 'facility_type');
						echo labelAndField($this, t('Staff Cadre'), $this->cadres, 'staff_cadre');
						if ( $this->setting['display_employee_staff_category'] )
							echo labelAndField($this, t('Staff Category'), $this->categories, 'staff_category');
						#if($this->setting['display_employee_funded_hours_per_week'])
						#	echo labelTwoFields($this, t('Funded Hours per week'), t('to'), 'hours_min', 'hours_max', $this->#criteria['hours_min'], $this->criteria['hours_max']);
						#if($this->setting['display_employee_annual_cost'])
						#	echo labelTwoFields($this, t('Annual Cost'), t('to'), 'cost_min', 'cost_max', $this->criteria['#hours_min'], $this->criteria['hours_max']);
						#if($this->setting['display_employee_primary_role'])
						#	echo labelAndField($this, t('Primary Role'), $this->roles, 'primary_role');
						if ($this->setting['display_employee_importance'])
							echo labelAndField($this, t('Importance'), $this->importance, 'importance');
						if($this->setting['display_employee_funder'])
							echo labelTwoFields($this, t('Funding End Date Between'), t('to'), 'start_date', 'end_date', $this->criteria['start_date'], $this->criteria['end_date']);
						#if($this->setting['display_employee_intended_transition'])
						#	echo labelAndField($this, t('Intended Transition'), $this->transitions, 'intended_transition');
						#if($this->setting['display_employee_transition_confirmed'])
						#	echo confirmDropdown($this, t('Transition Confirmed'), 'transition_confirmed', $this->criteria['transition_confirmed']);
						#echo labelAndCheckBox($this, t('Partner Comments'), 'show_comments', $this->criteria['show_comments']);
						echo labelAndCheckBox($this, t('Show all').space.t('Staff Cadre'), 'show_cadres', $this->criteria['show_cadres']);

					?>
					<div class="clear"></div>
					<input type="hidden" name="limit" id="limit" value="1" />
					<input type="submit" class="submitNoArrow" name="go" value="<?php tp('Preview');?>" />
				</fieldset>
			</form>

			<script type="text/javascript">
				$(function () { //docready
					$('#start_date,#end_date').datepicker({
						changeMonth: true, changeYear: true
					});
					$('.calendarbtn').click(openNearestDatePicker);
				});
			</script>

			<?php if ( $this->criteria['go'] ) { ?>
			<div class="hrGrey"></div>
			<div class="fieldIndentNoMargin"><?php tp('Partners');?> <span class="total"><?php echo $this->count;?>  <?php tp('Results');?></span><?php echo $this->printAndExport();?></div><br/>
			<div id="partners"></div>
			<script type="text/javascript">
			var partnersData = [
			<?php
			$cnt = 0;
			$isFirstRow = true;
			foreach($this->results as $row) {

				if ( ( $cnt < 100 ) or ( isset($_REQUEST['limit']) AND !$_REQUEST['limit'] ) ) {
					if ( !$isFirstRow ) {
						echo ',';
					}
					$isFirstRow = false;

					echo '[';
						echo $row['id'].',';
						$data = array();
						$data[] = $row['partner'];
						$data[] = $row['pcnt'];
						$data[] = $row['facilities'];
						if($this->criteria['show_comments'])
							$data[] = $row['comments'];
						if($this->criteria['show_cadres'])
							$data[] = $row['cadres'];
						echo '"'.implode('","', $data).'"';
					echo ']';
					$cnt++;
				}
			}
			?>];

			var formatViewUrl = function(elCell, oRecord, oColumn, sData) {
				if ( (sData == null) || (sData.length == 0) )
					sData = '&nbsp;&nbsp;&nbsp;';
				elCell.innerHTML = "<a href='<?php echo $this->base_url;?>/partner/edit/id/" + oRecord.getData("id") + "' >" + sData + "</a>";
			}

			var partnersColumnDefs = [
				{key:"id", label: "<?php tp("ID");?>", sortable:true, resizable:false,formatter: formatViewUrl}
				,{key:"partner",       label: "<?php tp('Partner');?>",         sortable:true, resizeable:true}
				,{key:"pcnt",          label: "<?php tp('Employee Count');?>",  sortable:true, resizeable:true}
				,{key:"facilities",    label: "<?php tp('Sites');?>",           sortable:true, resizeable:true}
				<?php if($this->criteria['show_comments']) { ?>
				,{key:"comments",      label: "<?php tp('Partner Comments');?>",sortable:true, resizeable:true}
				<?php } ?>
				<?php if($this->criteria['show_cadres']) { ?>
				,{key:"comments",      label: "<?php tp('Staff Cadre');?>",sortable:true, resizeable:true}
				<?php } ?>

			];

			makeDataTable("partners", null, partnersData, partnersColumnDefs);
		</script>
			<?php if ($cnt < count($this->results)) { ?>
			[<?php tp('Limited to 100 rows');?>]  <a href="<?php echo str_replace('limit=1','limit=0',$_SERVER['REQUEST_URI']);?>"><?php tp('Full Results');?></a>
			<?php } ?>
			<?php } ?>
		</div>
	</body>
</html>