<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title><?php echo $this->translation['Application Name'];?> | <?php tp('Participants Report');?></title>
<?php
require_once('views/helpers/Location.php');
require_once('views/helpers/ScriptContainer.php');
require_once('views/helpers/DropDown.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();

$checkLabel = t('show');
if ( $this->mode == 'count' )
	$checkLabel = t('group');

?>

</head>
<body class="yui-skin-sam" >

<div id="pageHolder">

  <div id="header"><?php require_once('views/scripts/header.phtml');?></div>
  <div id="content">

<?php if( strstr($path[2], 'trainersByName') === FALSE ):?>
    <h1><?php tp('Participant Reports');?></h1>
    	<?php require_once('peopleReportsPicker.phtml'); ?>
<?php else :?>
    <h1><?php tp('Trainers by Name');?></h1>
      <?php require_once('trainerReportsPicker.phtml'); ?>
<?php endif;?>
	   <form action="" method="get">
   <fieldset id="criteria"><legend><?php tp('Select Criteria');?></legend>
<div id="dividers">
      	<div class="fieldLabel" ></div>
    	<div class="fieldInput  criteria-header"><div   class="criteria-label" ><?php echo $checkLabel;?></div><div  class="criteria-label" style="padding-left: 20px;"><?php tp('filter');?></div></div>

	<?php region_filters_dropdown($this, $this->locations, $this->criteria, true, true); ?>

	<div id="facilityAutoComplete">
	    <div class="fieldLabel" id="facilityInput_lbl"><?php tp('Facility');?></div>
	    <div class="fieldInput">
	    <div  class="leftBorderPad"><input type="checkbox" name="showFacility" <?php  if ($this->criteria['showFacility']) echo 'CHECKED';?> /></div>
	    <div  class="leftBorder"><select id="facilityInput" name="facilityInput" >
	<option value="">--<?php tp('choose');?>--</option>
	<?php
		foreach ( $this->facilities as $vals ) {
			echo '<option value="'.$vals['id'].'" '.($this->criteria['facilityInput'] == $vals['id']?'SELECTED':'').'>'.$vals['facility_name'].'</option>';
	}
	?>
</select>
	    </div></div>
	</div>


	<div class="fieldLabel" id="training_title_option_id_lbl"><?php echo (@$this->translation['Training Name']); ?></div>
	<div class="fieldInput"><div  class="leftBorderPad"><input type="checkbox" name="showTrainingTitle" <?php  if ($this->criteria['showTrainingTitle']) echo 'CHECKED';?> /></div>
  	<div  class="leftBorder autoHeight">
	<select id="training_title_id" name="training_title_id[]" multiple="multiple" size="10">
		<option value="" <?php if (is_array($this->criteria['training_title_id']) && in_array("", $this->criteria['training_title_id'])) echo "selected"; ?>>--<?php tp('All');?>--</option>
		<?php
			foreach ( $this->courses as $vals ) {
				echo '<option value="'.$vals['id'].'" '.(@$this->criteria['training_title_id'] == $vals['id'] || @in_array($vals['id'], $this->criteria['training_title_id'])? 'SELECTED':'').' >'.$this->truncate($vals['training_title_phrase']).'</option>';
		}
		?>
	</select></div></div>

<!--
	<div class="fieldLabel" id="qualification_id_lbl"><?php tp('Qualification');?></div>
	<div class="fieldInput"><div  class="leftBorderPad"><input type="checkbox" name="showQualification" <?php  if ($this->criteria['showQualification']) echo 'CHECKED';?> /></div>

	<div  class="leftBorder"><select id="qualification_id" name="qualification_id" >
		<option value="">--<?php tp('All');?>--</option>
		<?php
			foreach ( $this->qualifications as $vals ) {
				echo '<option value="'.$vals['id'].'" '.((@$this->criteria['qualification_id']) == $vals['id']? 'SELECTED':'').' >'.($vals['qualification_phrase']).'</option>';
		}
		?>
	</select></div></div>
-->

	<div class="fieldLabel" id="district_id_lbl"><?php tp('Qualification'); ?> (<?php tp('primary');?>)</div><div class="fieldInput">
	<div  class="leftBorderPad"><input type="checkbox" name="showQualPrim" <?php  if ($this->criteria['showQualPrim']) echo 'CHECKED';?> /></div>
  	<div  class="leftBorder"><select id="qualification_id" name="qualification_id">
		<option value="">--<?php tp('All');?>--</option>
		<?php
			foreach ( $this->qualifications_primary as $vals ) {
				echo '<option value="'.$vals['id'].'" '.((@$this->criteria['qualification_id']) == $vals['id'] ? 'SELECTED':'').' >'.$vals['qualification_phrase'].'</option>';
		}
		?>
	</select></div></div>

	<div class="fieldLabel" id="district_id_lbl"><?php tp('Qualification'); ?> (<?php tp('secondary');?>)</div><div class="fieldInput">
	<div  class="leftBorderPad"><input type="checkbox" name="showQualSecond" <?php  if ($this->criteria['showQualSecond']) echo 'CHECKED';?> /></div>
  	<div  class="leftBorder"><select id="qualification_secondary_id" name="qualification_secondary_id">
		<option value="">--<?php tp('All');?>--</option>
		<?php
			foreach ( $this->qualifications_secondary as $vals ) {
				echo '<option value="'.$vals['id'].'" '.((@$this->criteria['qualification_secondary_id']) == $vals['id'] ? 'SELECTED':'').' >'.$vals['qualification_phrase'].'</option>';
		}
		?>
	</select></div></div>

	<!-- Primary Responsibility -->
	<?php if ($this->setting['display_primary_responsibility']) { ?>
	<div class="fieldLabel" id="resppri_lbl"><?php echo (@$this->translation['Primary Responsibility']); ?> </div><div class="fieldInput">
	<div  class="leftBorderPad"><input type="checkbox" name="showRespPrim" <?php  if ($this->criteria['showRespPrim']) echo 'CHECKED';?> /></div>
  	<div  class="leftBorder"><select id="primary_responsibility_option_id" name="primary_responsibility_option_id">
		<option value="">--<?php tp('All');?>--</option>
		<?php
			foreach ( $this->responsibility_primary as $vals ) {
				echo '<option value="'.$vals['id'].'" '.((@$this->criteria['primary_responsibility_option_id']) == $vals['id'] ? 'SELECTED':'').' >'.$vals['responsibility_phrase'].'</option>';
		}
		?>
	</select></div></div>
	<?php }	?>

	<!-- Secondary Responsibility -->
	<?php if ($this->setting['display_secondary_responsibility']) { ?>
	<div class="fieldLabel" id="respsec_lbl"><?php echo (@$this->translation['Secondary Responsibility']); ?> </div><div class="fieldInput">
	<div  class="leftBorderPad"><input type="checkbox" name="showRespSecond" <?php  if ($this->criteria['showRespSecond']) echo 'CHECKED';?> /></div>
  	<div  class="leftBorder"><select id="secondary_responsibility_option_id" name="secondary_responsibility_option_id">
		<option value="">--<?php tp('All');?>--</option>
		<?php
			foreach ( $this->responsibility_secondary as $vals ) {
				echo '<option value="'.$vals['id'].'" '.((@$this->criteria['secondary_responsibility_option_id']) == $vals['id'] ? 'SELECTED':'').' >'.$vals['responsibility_phrase'].'</option>';
		}
		?>
	</select></div></div>
	<?php }	?>



	<?php

	if (( strstr($path[2], 'trainersByName') !== FALSE ) OR ( strstr($path[2], 'participantsByName') !== FALSE )) { ?>

		<!-- Highest Education Level -->
		<?php if ($this->setting['display_highest_ed_level']) { ?>
			<div class="fieldLabel" id="person_highest_edu_level_lbl">
				<?php echo (@$this->translation['Highest Education Level']); ?>
			</div><div class="fieldInput">
			<div  class="leftBorderPad"><input type="checkbox" name="showHighestEd" <?php  if ($this->criteria['showHighestEd']) echo 'CHECKED';?> /></div>
	  	<div  class="leftBorder"><select id="highest_edu_level_option_id" name="highest_edu_level_option_id">
			<option value="">--<?php tp('All');?>--</option>
			<?php
				foreach ( $this->highest_education_level as $vals ) {
					echo '<option value="'.$vals['id'].'" '.((@$this->criteria['highest_edu_level_option_id']) == $vals['id'] ? 'SELECTED':'').' >'.$vals['education_level_phrase'].'</option>';
				}
			?>
			</select></div></div>
		<?php } ?>
  <?php } ?>

	<?php
	if ( strstr($path[2], 'participantsByName') !== FALSE ) { ?>

		<!-- Attend Reason -->
		<?php if ($this->setting['display_attend_reason']) { ?>
			<div class="fieldLabel" id="person_attend_reason_lbl"><?php echo (@$this->translation['Reason Attending']); ?> </div><div class="fieldInput">
			<div  class="leftBorderPad"><input type="checkbox" name="showReason" <?php  if ($this->criteria['showReason']) echo 'CHECKED';?> /></div>
	  	<div class="leftBorder"><select id="attend_reason_option_id" name="attend_reason_option_id">
			<option value="">--<?php tp('All');?>--</option>
			<?php
				foreach ( $this->attend_reason as $vals ) {
					echo '<option value="'.$vals['id'].'" '.((@$this->criteria['attend_reason_option_id']) == $vals['id'] ? 'SELECTED':'').' >'.$vals['attend_reason_phrase'].'</option>';
				}
			?>
			</select></div></div>
		<?php } ?>

		<!-- Training Name -->
  <?php } ?>

	<div class="fieldLabel" id="training_organizer_id_lbl"><?php echo (@$this->translation['Training Organizer']); ?></div>
	<div class="fieldInput">
		 <div  class="leftBorderPad"><input type="checkbox" name="showOrganizer" <?php  if ($this->criteria['showOrganizer']) echo 'CHECKED';?> /></div>
  	<div  class="leftBorder autoHeight">
  	

<?php echo $this->organizers_dropdown; ?><br />
	
	
	</div>
	</div>



  <?php if ( $this->setting['display_training_topic'] ) { ?>
	<div class="fieldLabel" id="training_topic_id_lbl"><?php echo (@$this->translation['Training Topic']); ?></div>
	<div class="fieldInput">
	<div  class="leftBorderPad"><input type="checkbox" name="showTopic" <?php  if ($this->criteria['showTopic']) echo 'CHECKED';?> /></div>
  	<div  class="leftBorder">
	<select id="training_topic_id" name="training_topic_id" >
		<option value="">--<?php tp('All');?>--</option>
		<?php
			foreach ( $this->topics as $vals ) {
				echo '<option value="'.$vals['id'].'" '.((@$this->criteria['training_topic_id']) == $vals['id']? 'SELECTED':'').' >'.($vals['training_topic_phrase']).'</option>';
		}
		?>
	</select></div></div>
	<?php } ?>

	<div class="fieldLabel" id="training_pepfar_id_lbl"><?php print $this->translation['PEPFAR Category'];?></div>
	<div class="fieldInput">
	<div  class="leftBorderPad"><input type="checkbox" name="showPepfar" <?php  if ($this->criteria['showPepfar']) echo 'CHECKED';?> /></div>
  	<div  class="leftBorder">
	<select id="training_pepfar_id" name="training_pepfar_id" >
		<option value="">--<?php tp('All');?>--</option>
		<?php
			foreach ( $this->pepfars as $vals ) {
				echo '<option value="'.$vals['id'].'" '.((@$this->criteria['training_pepfar_id']) == $vals['id']? 'SELECTED':'').' >'.($this->truncate($vals['pepfar_category_phrase'],45)).'</option>';
		}
		?>
	</select></div></div>

 	<?php if ( $this->setting['display_funding_options'] && strstr($path[2], 'participantsByTraining') !== FALSE) { ?>
	<div class="fieldLabel" id="training_funding_id_lbl"><?php tp('Funding'); ?></div>
	<div class="fieldInput"><div  class="leftBorderPad" ><input type="checkbox" name="showFunding"   <?php  if ($this->criteria['showFunding']) echo 'CHECKED';?> /></div><label for="showFunding" ></label>

	<div  class="leftBorder"><select id="funding_id" name="funding_id" >
		<option value="">--<?php tp('All');?>--</option>
		<?php
			foreach ( $this->funding as $vals ) {
				echo '<option value="'.$vals['id'].'" '.((@$this->criteria['funding_id']) == $vals['id']? 'SELECTED="selected"':'').' >'.($this->truncate($vals['funding_phrase'],45)).'</option>';
		}
		?>
	</select></div></div>
	<?php } ?>

	<?php if ( $this->setting['display_people_custom1'] ) { ?>
	<div class="fieldLabel" id="person_custom1_lbl"><?php print $this->translation['People Custom 1']; ?></div>
	<div class="fieldInput"><div  class="leftBorderPad" ><input type="checkbox" name="showCustom1"   <?php  if ($this->criteria['showCustom1']) echo 'CHECKED';?> /></div><label for="showCustom1" ></label>

	<div  class="leftBorder"><select id="custom_1_id" name="custom_1_id" >
		<option value="">--<?php tp('All');?>--</option>
		<?php
			foreach ( $this->custom1 as $vals ) {
				echo '<option value="'.$vals['id'].'" '.((@$this->criteria['custom_1_id']) == $vals['id']? 'SELECTED="selected"':'').' >'.($this->truncate($vals['custom1_phrase'],45)).'</option>';
		}
		?>
	</select></div></div>
	<?php } ?>

	<?php if ( $this->setting['display_people_custom2'] ) { ?>
	<div class="fieldLabel" id="person_custom2_lbl"><?php print $this->translation['People Custom 2']; ?></div>
	<div class="fieldInput"><div  class="leftBorderPad" ><input type="checkbox" name="showCustom2"   <?php  if ($this->criteria['showCustom2']) echo 'CHECKED';?> /></div><label for="showCustom2" ></label>
	<div  class="leftBorder"><select id="custom_2_id" name="custom_2_id" >
		<option value="">--<?php tp('All');?>--</option>
		<?php
			foreach ( $this->custom2 as $vals ) {
				echo '<option value="'.$vals['id'].'" '.((@$this->criteria['custom_2_id']) == $vals['id']? 'SELECTED="selected"':'').' >'.($this->truncate($vals['custom2_phrase'],45)).'</option>';
		}
		?>
	</select></div></div>
	<?php } ?>

	<?php if ( $this->setting['display_people_custom3'] ) { ?>
	<div class="fieldLabel" id="person_custom3_lbl"><?php print $this->translation['People Custom 3']; ?></div>
	<div class="fieldInput"><div  class="leftBorderPad" ><input type="checkbox" name="showCustom3"   <?php  if ($this->criteria['showCustom3']) echo 'CHECKED';?> /></div><label for="showCustom3" ></label>
	<div  class="leftBorder"><select id="custom_3_id" name="custom_3_id" >
		<option value="">--<?php tp('All');?>--</option>
		<?php
			foreach ( $this->custom3 as $vals ) {
				if(! trim($vals['custom_3']))
					continue;
				echo '<option value="'.$vals['custom_3'].'" '.((@$this->criteria['custom_3_id']) == $vals['custom_3']? 'SELECTED="selected"':'').' >'.($this->truncate($vals['custom_3'],45)).'</option>';
		}
		?>
	</select></div></div>
	<?php } ?>

	<?php if ( $this->setting['display_people_custom4'] ) { ?>
	<div class="fieldLabel" id="person_custom4_lbl"><?php print $this->translation['People Custom 4']; ?></div>
	<div class="fieldInput"><div  class="leftBorderPad" ><input type="checkbox" name="showCustom4"   <?php  if ($this->criteria['showCustom4']) echo 'CHECKED';?> /></div><label for="showCustom4" ></label>
	<div  class="leftBorder"><select id="custom_4_id" name="custom_4_id" >
		<option value="">--<?php tp('All');?>--</option>
		<?php
			foreach ( $this->custom4 as $vals ) {
				if(! trim($vals['custom_4']))
					continue;
				echo '<option value="'.$vals['custom_4'].'" '.((@$this->criteria['custom_4_id']) == $vals['custom_4']? 'SELECTED="selected"':'').' >'.($this->truncate($vals['custom_4'],45)).'</option>';
		}
		?>
	</select></div></div>
	<?php } ?>

	<?php if ( $this->setting['display_people_custom5'] ) { ?>
	<div class="fieldLabel" id="person_custom5_lbl"><?php print $this->translation['People Custom 5']; ?></div>
	<div class="fieldInput"><div  class="leftBorderPad" ><input type="checkbox" name="showCustom5"   <?php  if ($this->criteria['showCustom5']) echo 'CHECKED';?> /></div><label for="showCustom5" ></label>
	<div  class="leftBorder"><select id="custom_5_id" name="custom_5_id" >
		<option value="">--<?php tp('All');?>--</option>
		<?php
			foreach ( $this->custom5 as $vals ) {
				if(! trim($vals['custom_5']))
					continue;
				echo '<option value="'.$vals['custom_5'].'" '.((@$this->criteria['custom_5_id']) == $vals['custom_5']? 'SELECTED="selected"':'').' >'.($this->truncate($vals['custom_5'],45)).'</option>';
		}
		?>
	</select></div></div>
	<?php } ?>

	<div class="fieldLabel" id="training_gender_lbl"><?php tp('Gender');?></div>
	<div class="fieldInput">
	<div  class="leftBorderPad"><input type="checkbox" name="showGender" <?php  if ($this->criteria['showGender']) echo 'CHECKED';?> /></div>
  	<div  class="leftBorder">
	<select id="training_gender" name="training_gender" >
		<option value="">--<?php tp('All');?>--</option>
		<option value="male" <?php echo (@$this->criteria['training_gender'] == 'male'? 'SELECTED':''); ?> ><?php tp('male');?></option>
		<option value="female"  <?php echo (@$this->criteria['training_gender'] == 'female'? 'SELECTED':''); ?> ><?php tp('female');?></option>
		<option value="na"  <?php echo (@$this->criteria['training_gender'] == 'na'? 'SELECTED':''); ?> ><?php tp('na');?></option>
	</select></div></div>
<?php if ( $this->setting['display_people_age'] ) { ?>
  <div class="fieldLabel" id="training_age_lbl"><?php tp('Age');?></div>
  <div class="fieldInput">
  <div  class="leftBorderPad"><input type="checkbox" name="showAge" <?php  if ($this->criteria['showAge']) echo 'CHECKED';?> /></div>
    <div  class="leftBorder">
    <?php tp('min');?> <input type="text" id="age_min" name="age_min" size="4" value="<?php echo ( $this->criteria['age_min'] ? $this->criteria['age_min'] : '0');?>" /> <?php tp('max');?> <input type="text"  size="4" name="age_max" id="age_max" value="<?php echo ( $this->criteria['age_max'] ? $this->criteria['age_max'] : '');?>" /> <a href="#" id="clear_age" onclick="return clearAge();" ><?php tp('clear');?></a>
    </div></div>
<?php } ?>

<?php
if ( $this->setting['display_viewing_location'] && $this->mode != 'search' && ! $this->is_trainers ) {
	echo DropDown::render_report_filter('person_to_training_viewing_loc_option', 'showViewingLoc', @$this->translation['Viewing Location'], $this->viewing_loc, 'location_phrase', @$this->criteria['person_to_training_viewing_loc_option_id'], $this->criteria['showViewingLoc']);
} ?>

<?php if ($this->setting['display_people_active']) { ?>
	<div class="fieldLabel" id="training_active_lbl"><?php echo (@$this->translation['Is Active']); ?></div>
	<div class="fieldInput">
	<div  class="leftBorderPad"><input type="checkbox" name="showActive" <?php  if ($this->criteria['showActive']) echo 'CHECKED';?> /></div>
  	<div  class="leftBorder">
	<select id="training_active" name="training_active" >
		<option value="">--<?php tp('All');?>--</option>
		<option value="active" <?php echo (@$this->criteria['training_active'] == 'active'? 'SELECTED':''); ?> ><?php tp('active');?></option>
		<option value="inactive"  <?php echo (@$this->criteria['training_active'] == 'inactive'? 'SELECTED':''); ?> ><?php tp('inactive');?></option>
	</select></div></div>
<?php } ?>

<?php if (( strstr($path[2], 'trainersByName') !== FALSE ) OR ( strstr($path[2], 'participantsByName') !== FALSE )) { ?>

	<?php if ($this->setting['display_people_suffix']) { ?>
		<div class="fieldLabel" id="person_suffix_lbl"><?php echo (@$this->translation['Suffix']); ?></div>
		<div class="fieldInput">
			<div  class="leftBorderPad"><input type="checkbox" name="showSuffix" <?php  if ($this->criteria['showSuffix']) echo 'CHECKED';?> /></div>
		  <div  class="leftBorder"></div>
		</div>
  <?php } ?>

	<div class="fieldLabel" id="training_phone_lbl"><?php tp('Email');?></div>
	<div class="fieldInput">
		<div  class="leftBorderPad"><input type="checkbox" name="showEmail" <?php  if ($this->criteria['showEmail']) echo 'CHECKED';?> /></div>
  	<div  class="leftBorder"></div>
  </div>
	<div class="fieldLabel" id="training_phone_lbl"><?php tp('Phone');?></div>
	<div class="fieldInput">
		<div  class="leftBorderPad"><input type="checkbox" name="showPhone" <?php  if ($this->criteria['showPhone']) echo 'CHECKED';?> /></div>
  	<div  class="leftBorder"></div>
  </div>
<?php } ?>


 	<?php if ( $this->setting['display_training_trainers']) { ?>
	<div class="fieldLabel" id="is_tot_lbl"><?php echo (@$this->translation['Training of Trainers']); ?></div>
	<div class="fieldInput"><div  class="leftBorderPad"><input type="checkbox" name="showTot" <?php  if ($this->criteria['showTot']) echo 'CHECKED';?> /></div><label for="showTot" ></label>

	<div  class="leftBorder">
  <!--
  <select id="is_tot" name="is_tot">
		<option value="">--<?php tp('All');?>--</option>
		<?php
			foreach ( array(1 => 'Yes', 0 => 'No') as $val => $label ) {
				echo '<option value="'.$val.'" '.((is_numeric(@$this->criteria['is_tot']) && $this->criteria['is_tot'] == $val) ? 'SELECTED="selected"':'').' >'.t($label).'</option>';
		}
		?>
	</select>
  -->
  </div></div>
	<?php } ?>

<?php if($this->isScoreReport) { ?>
	<div class="fieldLabel" id="is_tot_lbl"><?php tp('Show post-test scores above') ?></div>
	<div class="fieldInput"><div  class="leftBorderPad"><input type="checkbox" style="visibility:hidden;"></div>

	<div  class="leftBorder">
  <input type="text" name="score_min" value="<?php echo @$this->criteria['score_min']; ?>" size="5" />
  </div></div>

	<div class="fieldLabel" id="is_tot_lbl"><?php tp('Show score increase above') ?></div>
	<div class="fieldInput"><div  class="leftBorderPad"><input type="checkbox" style="visibility:hidden;"></div>

	<div  class="leftBorder">
  <input type="text" name="score_percent_min" value="<?php echo @$this->criteria['score_percent_min']; ?>" size="5" />%
  </div></div>


<?php } ?>

</div>

<?php if(strstr($path[2], 'participantsByTraining') == TRUE or strstr($path[2], 'participantsByName') == TRUE) { ?>
  <div class="clear"></div>
	<div class="fieldLabel">&nbsp;</div>
   	<div class="fieldInput" style="margin-top:1em;"><input type="checkbox" name="distinctCount" id="distinctCount" 
   	<?php  if ($this->criteria['distinctCount']) echo 'checked="checked"';?> /><label for="distinctCount" > 
   	<?php if(strstr($path[2], 'participantsByTraining') == TRUE) tp('Return Unique Participants');?>
   	<?php if(strstr($path[2], 'participantsByName') == TRUE) tp('Return Unique Participants By Training Names');?>
   	
   	</label></div><?php }; ?>


	<div class="clear"></div><br /><br />
<div class="fieldLabel"><?php tp('Start date');?></div>
<div class="fieldInput" id="startdate">
    <?php tp("Day");?> <input id="start-day" class="dayfield" type="text" name="start-day" maxlength="2" value="<?php echo $this->criteria['start-day']; ?>"  >
    / <?php tp("Month");?> <input id="start-month" class="monthfield" type="text" name="start-month" maxlength="2" value="<?php echo $this->criteria['start-month']; ?>"  >
    / <?php tp("Year");?> <input id="start-year" class="yearfield" type="text" name="start-year" maxlength="4" value="<?php echo $this->criteria['start-year'];  ?>" >
		            <script  type="text/javascript">
		    YAHOO.util.Event.onDOMReady(function () {
		    	makeCalendar("startdate","start-day", "start-month", "start-year");
		    });
		</script>
	</div>
<div class="fieldLabel" style="padding-top:1em;"><?php tp('End date');?></div>
<div class="fieldInput" id="enddate" style="margin-top:1em;">
    <?php tp("Day");?> <input id="end-day" class="dayfield" type="text" name="end-day" maxlength="2" value="<?php echo $this->criteria['end-day']; ?>"  >
    / <?php tp("Month");?> <input id="end-month" class="monthfield" type="text" name="end-month" maxlength="2" value="<?php echo $this->criteria['end-month']; ?>"  >
    / <?php tp("Year");?> <input id="end-year" class="yearfield" type="text" name="end-year" maxlength="4" value="<?php echo $this->criteria['end-year'];  ?>" >
		            <script  type="text/javascript">
		    YAHOO.util.Event.onDOMReady(function () {
		    	makeAdditionalCalendar("enddate","end-day", "end-month", "end-year");
		    });
		</script>
	</div>
<?php if ( $this->mode != 'count' ) { ?>
	<div class="fieldLabel">&nbsp;</div>
   	<div class="fieldInput" style="margin-top:1em;"><input type="checkbox" name="concatNames" id="concatNames" <?php  if ($this->criteria['concatNames']) echo 'CHECKED';?> /><label for="concatNames" ><?php tp('Combine First and Last Names');?></label></div>
<?php } ?>

	<div class="clear"></div>
	<input type="hidden" name="limit" id="limit" value="1" />
   	<input type="submit" class="submitNoArrow" name="go" value="<?php tp('Preview')?>" />
   </fieldset>
   </form>
<?php if ( $this->criteria['go'] ) { ?>
<div class="hrGrey"></div>
    <div class="fieldIndentNoMargin"><?php tp('Participants')?> <span class="total"><?php echo $this->count;?> <?php echo t('Trainings Attended');?></span><?php echo $this->printAndExport();?></div>

    <div id="trainings"  class="itechTable"></div>
    <script type="text/javascript">

    	        var formatViewUrl = function(elCell, oRecord, oColumn, sData) {
	            elCell.innerHTML = "<a href='<?php echo $this->base_url;?>/person/view/id/" + oRecord.getData("id") + "'>" + sData + "</a>";
	        };


var trainingData = [
<?php $isFirstRow = true;
$cnt = 0;
foreach($this->results as $row) {
	if ( (!@$_REQUEST['limit'])  or ($cnt < 100) ) {
	if (!$isFirstRow )
		echo ',';
	$isFirstRow = false;
	echo '['.(isset($row['cnt'])?$row['cnt']:$row['id']);
	if ( isset($row['id']) and !$this->criteria['concatNames'])
		echo ',"'.$row['first_name'].'"';
	if ( isset($row['id']) and !$this->criteria['concatNames'] && $this->setting['display_middle_name'] &&  !$this->setting['display_middle_name_last'])
		echo ',"'.$row['middle_name'].'"';
	if ( isset($row['id']) and !$this->criteria['concatNames'])
		echo ',"'.$row['last_name'].'"';
	if ( isset($row['id']) and !$this->criteria['concatNames'] && $this->setting['display_people_suffix'] && $this->criteria['showSuffix'])
		echo ',"'.$row['suffix_phrase'].'"';
	if ( isset($row['id']) and !$this->criteria['concatNames'] && $this->setting['display_middle_name'] &&  $this->setting['display_middle_name_last'])
		echo ',"'.$row['middle_name'].'"';
	if ( isset($row['id']) and $this->criteria['concatNames'])
		echo ',"'.$row['name'].'"';
	if ( isset($row['id']) and $this->criteria['showEmail'])
		echo ',"'.$row['email'].'"';
	if ( isset($row['id']) and $this->criteria['showPhone']){
		if (! array_key_exists('phone', $row))
			$row['phone'] = t('(no phone)');
			echo ',"'. (isset ($row['phone']) ? $row['phone'] : t("N/A")) .'"';
		}
	if ( isset($row['id']) )
		echo ',"'.$row['training_start_date'].'"';
	if ( $this->criteria['showGender'] )
		echo ',"'.$row['gender'].'"';
	if ( $this->criteria['showAge'] )
		echo ','.$row['age'];
	if ( $this->criteria['showViewingLoc'] )
		echo ',"'.($row['location_phrase'] ? $row['location_phrase'] : '-').'"';
	if ( $this->criteria['showActive'] )
		echo ',"'.$row['active'].'"';
	if ( $this->criteria['showProvince'] )
		echo ',"'.$row['province_name'].'"';
	if ( $this->criteria['showDistrict'] )
		echo ',"'.$row['district_name'].'"';
	if ( $this->criteria['showRegionC'] )
	echo ',"'.$row['region_c_name'].'"';
	if ( $this->criteria['showRegionD'] )
		echo ',"'.$row['region_d_name'].'"';
	if ( $this->criteria['showRegionD'] )
		echo ',"'.$row['region_e_name'].'"';
	if ( $this->criteria['showRegionE'] )
		echo ',"'.$row['region_f_name'].'"';
	if ( $this->criteria['showRegionF'] )
		echo ',"'.$row['region_g_name'].'"';
	if ( $this->criteria['showRegionH'] )
		echo ',"'.$row['region_h_name'].'"';
	if ( $this->criteria['showRegionI'] )
		echo ',"'.$row['region_i_name'].'"';
	if ( $this->criteria['showFacility'] )
		echo ',"'.$row['facility_name'].'"';
	if ( $this->criteria['showTrainingTitle'] )
		echo ',"'.$row['training_title'].'"';
	if ( $this->criteria['showQualification'] )
		echo ',"'.$row['qualification_phrase'].'"';
	if ( $this->criteria['showQualPrim'] )
		echo ',"'.$row['qualification_phrase'].'"';
	if ( $this->criteria['showQualSecond'] )
		echo ',"'.$row['qualification_secondary_phrase'].'"';
	if ($this->criteria ['showRespPrim'])
		echo ',"'.$row['primaryResponsibility'].'"';
	if ($this->criteria ['showRespSecond'])
		echo ',"'.$row['secondaryResponsibility'].'"';
	if ($this->criteria ['showHighestEd'])
		echo ',"'.$row['education_level_phrase'].'"';
	if ($this->criteria ['showReason'])
		echo ',"'.$row['attend_reason_phrase'].'"';
	if ( $this->criteria['showOrganizer'] )
		echo ',"'.$row['training_organizer_phrase'].'"';
	if ( $this->criteria['showTopic'] )
		echo ',"'.$row['training_topic_phrase'].'"';
	if ( $this->criteria['showPepfar'] )
		echo ',"'.$row['pepfar_category_phrase'].'"';
	if ( $this->criteria['showFunding'] )
		echo ',"'.$row['funding_phrase'].'"';
	if ( $this->criteria['showCustom1'] )
		echo ',"'.$row['custom1_phrase'].'"';
	if ( $this->criteria['showCustom2'] )
		echo ',"'.$row['custom2_phrase'].'"';
	if ( $this->criteria['showCustom3'] )
		echo ',"'.$row['custom3_phrase'].'"';
	if ( $this->criteria['showCustom4'] )
		echo ',"'.$row['custom4_phrase'].'"';
	if ( $this->criteria['showCustom5'] )
		echo ',"'.$row['custom5_phrase'].'"';
	if ( $this->criteria['showTot'] )
		echo ',"'.$row['is_tot'].'"';
  if ( $this->isScoreReport) {
    if($row['score_percent_change'] > 0) {
      $row['score_percent_change'] = "+" . $row['score_percent_change'];
    }
    if(is_numeric($row['score_percent_change'])) {
      $row['score_percent_change'] = "{$row['score_percent_change']}%";
    }
    echo ',"'.$row['score_pre'].'"';
    echo ',"'.$row['score_post'].'"';
    echo ',"'.$row['score_percent_change'].'"';
    echo ',"'.$row['labels'].'"';
    echo ',"'.$row['scores'].'"';
  }
	echo "]";
	$cnt++;
	}
}
   ?>
   ];

var myNumberSort = function(a,b,desc,fieldname) {

       var astr = new String(a.getData(fieldname));
       var bstr = new String(b.getData(fieldname));

       if ( astr == bstr)
           return 0;

       var anum  = parseInt(astr.replace('%','').replace('+',''));
       var bnum  = parseInt(bstr.replace('%','').replace('+',''));

       if ( astr == '' )
         return -1;
       if ( bstr == '' )
         return 1;
       return ( anum < bnum  ? -1: 1);

}
var myScorePercentSortFunction = function(a, b, desc) {
    return myNumberSort(a,b,desc,'score_percent_change');
};
var myScorePostSortFunction = function(a, b, desc) {
    return myNumberSort(a,b,desc,'score_post');
};
var myScorePreSortFunction = function(a, b, desc) {
    return myNumberSort(a,b,desc,'score_pre');
};


var trainingColumnDefs = [
<?php if (isset($this->results[0]['cnt'])) { ?>
{key:"cnt", label: "<?php tp('Participant Count');?>", sortable:false, resizeable:true}
<?php } else { ?>
	{key:"id", label: "<?php tp('ID')?>", sortable:false, resizeable:true, formatter: formatViewUrl},
	<?php if ( !$this->criteria['concatNames'] ) { ?>
		{key:"first_name", label: "<?php echo (@$this->translation['First Name']); ?>", sortable:true, resizeable:true},
   <?php if ( $this->setting['display_middle_name'] && !$this->setting['display_middle_name_last'] ) { ?>
		    {key:"middle_name", label: "<?php echo (@$this->translation['Middle Name']); ?>", sortable:true, resizeable:true},
	<?php }?>
		{key:"last_name", label: "<?php echo (@$this->translation['Last Name']); ?>", sortable:true, resizeable:true},

	<?php if ( $this->setting['display_people_suffix'] && $this->criteria['showSuffix']) {?>
		{key:"suffix_phrase", label: "<?php echo (@$this->translation['Suffix']); ?>", sortable:true, resizeable:true},
	<?php } ?>
   <?php if ( $this->setting['display_middle_name'] && $this->setting['display_middle_name_last'] ) { ?>
		    {key:"middle_name", label: "<?php echo (@$this->translation['Middle Name']); ?>", sortable:true, resizeable:true},
	<?php }?>
	<?php } else { ?>
		{key:"name", label: "<?php tp('Name');?>", sortable:true, resizeable:true},
	<?php } ?>
<?php if ( $this->criteria['showEmail'] ) { ?>
   {key:"email", label: "<?php tp('Email');?>", sortable:true, resizeable:true},
 <?php } ?>
<?php if ( $this->criteria['showPhone'] ) { ?>
   {key:"phone", label: "<?php tp('Phone');?>", sortable:true, resizeable:true},
 <?php } ?>
	{key:"training_start_date", label: "<?php tp('Date');?>", sortable:true, resizeable:true}
<?php } ?>
<?php if ( $this->criteria['showGender'] ) { ?>
   ,{key:"gender", label: "<?php tp('Gender');?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showAge'] ) { ?>
   ,{key:"age", label: "<?php tp('Age');?>", sortable:true, resizeable:true}
 <?php } ?>
 <?php if ( $this->criteria['showViewingLoc'] ) { ?>
   ,{key:"viewing_loc", label: "<?php echo (@$this->translation['Viewing Location']);?>", sortable:true, resizeable:true}
 <?php } ?>
 <?php if ( $this->criteria['showActive'] ) { ?>
   ,{key:"active", label: "<?php echo (@$this->translation['Is Active']); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showProvince'] ) { ?>
    ,{key:"province_name", label: "<?php echo (@$this->translation['Region A (Province)']); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showDistrict'] ) { ?>
   ,{key:"district_name", label: "<?php echo (@$this->translation['Region B (Health District)']); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showRegionC'] ) { ?>
   ,{key:"region_c_name", label: "<?php echo (@$this->translation['Region C (Local Region)']); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showRegionD'] ) { ?>
   ,{key:"region_D_name", label: "<?php echo (@$this->translation['Region D']); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showRegionE'] ) { ?>
   ,{key:"region_e_name", label: "<?php echo (@$this->translation['Region E']); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showRegionF'] ) { ?>
   ,{key:"region_f_name", label: "<?php echo (@$this->translation['Region F']); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showRegionG'] ) { ?>
   ,{key:"region_g_name", label: "<?php echo (@$this->translation['Region G']); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showRegionH'] ) { ?>
   ,{key:"region_h_name", label: "<?php echo (@$this->translation['Region H']); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showRegionI'] ) { ?>
   ,{key:"region_i_name", label: "<?php echo (@$this->translation['Region I']); ?>", sortable:true, resizeable:true}
 <?php } ?>
 <?php if ( $this->criteria['showFacility'] ) { ?>
   ,{key:"facility_name", label: "<?php tp('Facility');?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showTrainingTitle'] ) { ?>
   ,{key:"training_title", label: "<?php echo (@$this->translation['Training Name']); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showQualification'] ) { ?>
   ,{key:"qualification_phrase", label: "<?php tp('Qualification');?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showQualPrim'] ) { ?>
   ,{key:"qualification_phrase", label: "<?php tp('Qualification') . ' ' . tp('(primary)');?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showQualSecond'] ) { ?>
   ,{key:"qualification_secondary_phrase", label: "<?php tp('Qualification') . ' ' . tp('(secondary)');?>", sortable:true, resizeable:true}
 <?php } ?>

<?php if ( $this->criteria['showRespPrim'] ) { ?>
   ,{key:"primaryResponsibility", label: "<?php echo (@$this->translation['Primary Responsibility']);?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showRespSecond'] ) { ?>
   ,{key:"secondaryResponsibility", label: "<?php echo (@$this->translation['Secondary Responsibility']);?>", sortable:true, resizeable:true}
 <?php } ?>


<?php if ( $this->criteria['showHighestEd'] ) { ?>
   ,{key:"education_level_phrase", label: "<?php echo (@$this->translation['Highest Education Level']);?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showReason'] ) { ?>
   ,{key:"attend_reason_phrase", label: "<?php echo (@$this->translation['Reason Attending']);?>", sortable:true, resizeable:true}
 <?php } ?>


 <?php if ( $this->criteria['showOrganizer'] ) { ?>
   ,{key:"training_organizer_phrase", label: "<?php echo (@$this->translation['Training Organizer']); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showTopic'] ) { ?>
   ,{key:"training_topic_phrase", label: "<?php echo (@$this->translation['Training Topic']); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showPepfar'] ) { ?>
   ,{key:"pepfar_category_phrase", label: "<?php tp('PEPFAR');?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showFunding'] ) { ?>
   ,{key:"funding_phrase", label: "<?php tp('Funding');?>", sortable:true, resizeable:true}
 <?php } ?>
<?php 	if ( $this->criteria['showCustom1'] ) { ?>
  ,{key:"custom1_phrase", label: "<?php echo (@$this->translation['People Custom 1']); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php 	if ( $this->criteria['showCustom2'] ) { ?>
  ,{key:"custom2_phrase", label: "<?php echo (@$this->translation['People Custom 2']); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php 	if ( $this->criteria['showCustom3'] ) { ?>
  ,{key:"custom3_phrase", label: "<?php echo (@$this->translation['People Custom 3']); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php 	if ( $this->criteria['showCustom4'] ) { ?>
  ,{key:"custom4_phrase", label: "<?php echo (@$this->translation['People Custom 4']); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php 	if ( $this->criteria['showCustom5'] ) { ?>
  ,{key:"custom5_phrase", label: "<?php echo (@$this->translation['People Custom 5']); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showTot'] ) { ?>
   ,{key:"is_tot", label: "<?php echo tp('TOT'); ?>", sortable:true, resizeable:true}
 <?php } ?>
  <?php if ( $this->isScoreReport) { ?>
  ,{key:"score_pre", label: "<?php echo tp('Pre-Test'); ?>", sortable:true, sortOptions: { sortFunction: myScorePreSortFunction }, resizeable:true}
  ,{key:"score_post", label: "<?php echo tp('Post-Test'); ?>", sortable:true, sortOptions: { sortFunction: myScorePostSortFunction }, resizeable:true}
  ,{key:"score_percent_change", label: "<?php echo tp('% Change'); ?>", sortable:true, sortOptions: { sortFunction: myScorePercentSortFunction }, resizeable:true}
  ,{key:"labels", label: "<?php echo tp('Other Scores'); ?>", sortable:true, resizeable:true}
  ,{key:"scores", label: "<?php echo tp('Other Scores'); ?>", sortable:true, resizeable:true}
  <?php } ?>


];



	makeDataTable("trainings", null, trainingData, trainingColumnDefs);
</script>
<?php if ($cnt < count($this->results)) { ?>
[<?php tp('Limited to 100 rows');?>]  <a href="<?php echo str_replace('limit=1','limit=0',$_SERVER['REQUEST_URI']);?>"><?php tp('Full Results');?></a>
<?php } ?>
<?php } ?>
  </div>
  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>


</div>

<script type="text/javascript">

// uncheck return unique if training_title is used, they are not companitable
$('document').ready(function () {
	//if ($('#training_title_id').val() != "") {
		//$('#distinctCount').removeAttr('checked');
	//}
	//$('#training_title_id').change(function () {
		//if ($('#training_title_id').val() != "") {
			//$('#distinctCount').removeAttr('checked');
		//}
	//})
	//$('#distinctCount').change(function (e) {
		//if ($(this).is(':checked') && $('#training_title_id').val() != "") {
			//alert('<?php echo @$this->translation["Training Name"].space.t("cannot be used with".space.t("Return Unique Participants")); ?>');
			//e.preventDefault();
			//$('#distinctCount').removeAttr('checked');
		}
	})
})

</script>

</body>
</html>
