<script language="javascript">
	function gotoPeoplePage(objId) {
		var reportSelector = YAHOO.util.Dom.get(objId);
		if ( reportSelector[reportSelector.selectedIndex].value ) {
			window.location = '<?php echo $this->base_url;?>' + reportSelector[reportSelector.selectedIndex].value + '?<?php echo $_SERVER['QUERY_STRING'];?>';
		}
	}
</script>
    	<div class="fieldLabel" id="peopleSelect_lbl" ><?php print str_replace(' ','&nbsp;', t('Select participant report'));?></div>
    	<select id="peopleSelect" name="peopleSelect" onchange="gotoPeoplePage('peopleSelect');">
    		<option value="">--<?php tp('choose');?>--</option>
    		<option value="/reports/participantsByCategory/cat/pepfar" <?php if ( @$this->criteria['cat'] == 'pepfar' ) echo 'SELECTED';?> ><?php tp('Unique Participants by ');?> <?php echo (@$this->translation['PEPFAR Category']); ?></option>
     		<option value="/reports/participantsByCategory/cat/level" <?php if ( @$this->criteria['cat'] == 'level' ) echo 'SELECTED';?> ><?php tp('Unique Participants by');?> <?php echo (@$this->translation['Training Level']); ?></option>
    		<option value="/reports/participantsByCategory/cat/qualification" <?php if ( @$this->criteria['cat'] == 'qualification' ) echo 'SELECTED';?> ><?php tp('Unique Participants by Qualification');?></option>
     		<option value="/reports/participantsByTraining" <?php if ( strstr($_SERVER['REQUEST_URI'],'participantsByTraining')) echo 'SELECTED';?>><?php tp('Participants Trained');?></option>
     		<option value="/reports/participantsByFacilityType" <?php if ( strstr($_SERVER['REQUEST_URI'],'participantsByFacilityType')) echo 'SELECTED';?>><?php tp('Participants by Facility');?></option>
     		<option value="/reports/participantsByName" <?php if ( strstr($_SERVER['REQUEST_URI'],'participantsByName')) echo 'SELECTED';?>><?php tp('Participants by Name');?></option>
     		<option value="/reports/participantsScores" <?php if ( strstr($_SERVER['REQUEST_URI'],'participantsScores')) echo 'SELECTED';?>><?php tp('Participants with Scores');?></option>
 	</select>
