<div class="fieldquestion"><?php echo t('ps nationality'); ?></div>
<div class="fieldshow"><input type="checkbox" name="shownationality" id="shownationality" value="1"<?php if (isset($this->criteria['shownationality']) && $this->criteria['shownationality']) { echo " checked"; } ?>></div>
<div class="fieldselect"><select name="nationality" id="nationality" style="" size="10">
        <?php
        foreach ($this->nationalities as $item){
            echo "<option value=\"" . $item['id'] . "\">" . $item['nationality'] . "</option>\n";
        }
        ?>
    </select></div>
<div class="clear pad20">&nbsp;</div>
