<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title><?php echo $this->translation['Application Name'];?> | <?php tp('Competence Overview Reports');?></title>
<?php
require_once('views/helpers/Location.php');
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>
<style>

</style>
</head>
<body class="yui-skin-sam" onload="SwHd(document.getElementById('qualification_id'));Sel();">
<div id="pageHolder">

  <div id="header"><?php require_once('views/scripts/header.phtml');?></div>
  <div id="content">

    <h1><?php tp('Competence Overview Reports');?></h1>
	   <form action="" method="GET">
   <fieldset><legend><?php tp('Select Criteria');?></legend>
	 <div class="fieldLabel" id="province_id_lbl"><?php echo (@$this->translation['Region A (Province)']); ?></div>
  <div class="fieldInput"><?php renderFilter($this->locations, 1, 'province_id', $this->criteria['province_id'], 'district_id');?></div>
  <?php if ( $this->setting['display_region_b'] ) { ?>
  <div class="fieldLabel" id="district_id_lbl"><?php echo (@$this->translation['Region B (Health District)']); ?></div>
  <div class="fieldInput"><?php renderFilter($this->locations, 2, 'district_id', $this->criteria['district_id'], ($this->setting['display_region_c']?'region_c_id':false));?></div>
  <?php } ?>
  <?php if ( $this->setting['display_region_c'] ) { ?>
  <div class="fieldLabel" id="region_c_id_lbl"><?php echo (@$this->translation['Region C (Local Region)']); ?></div>
  <div class="fieldInput"><?php renderFilter($this->locations, 3, 'region_c_id', $this->criteria['region_c_id'], false);?></div>
  <?php } ?>

<div class="fieldLabel"  id="facilityInput_lbl"><?php tp('Facility');?></div><div class="fieldInput"><select id="facilityInput" name="facilityInput" >
	<option value="">--<?php tp('choose');?>--</option>
	<?php
		foreach ( $this->facilities as $vals ) {
			echo '<option value="'.$vals['id'].'" '.($this->criteria['facilityInput'] == $vals['id']?'SELECTED':'').'>'.$vals['facility_name'].'</option>';
	}
	?>
</select></div>
	<div class="clear"></div>

	<div class="fieldLabel" id="qualification_id_lbl"><?php echo t('Occupational category'); ?></div>
	<div class="fieldInput"><select id="qualification_id" name="qualification_id" onchange="SwHd(this)">
		<option value="">--<?php tp('choose');?>--</option>
   <?php
    $lastParent = null;
    foreach ( $this->qualifications as $vals ) {
     if ( !$vals['id'] ) {
      $lastParent = $vals['parent_phrase'];
echo '<option value="'.$vals['parent_id'].'" '.((@$this->criteria['qualification_id']) == $vals['parent_id']?'SELECTED':'').'>'.htmlspecialchars($vals['parent_phrase']).'</option>';
}
    }
   ?>
	</select></div>
 <script type="text/javascript">
  var i;
  for(i=0;i<document.getElementById("qualification_id").options.length;i++)
  {
   if(document.getElementById("qualification_id").options[i].text.indexOf("ther (Please")>0)
    document.getElementById("qualification_id").options[i].text=document.getElementById("qualification_id").options[i].text.substr(0,document.getElementById("qualification_id").options[i].text.length-2).replace("Z_","");
  }
 </script>
	<div class="fieldLabel" id="qualification_id_lbl"><?php echo t('Competence'); ?><br /><a href="javascript:void(0)" onclick="SelAll()"><?php echo t('Select All'); ?></a></div>
	<div class="fieldInput">
	<?php require_once('listcomn.phtml');?>
	<?php require_once('listcomd.phtml');?>
	<?php require_once('listcomp.phtml');?>
	<?php require_once('listcomc.phtml');?>
	</div>
	<script type="text/javascript">
		document.getElementById("listc").setAttribute("multiple","multiple");
		document.getElementById("listd").setAttribute("multiple","multiple");
		document.getElementById("listn").setAttribute("multiple","multiple");
		document.getElementById("listp").setAttribute("multiple","multiple");
		document.getElementById("listc").options.remove(0);
		document.getElementById("listd").options.remove(0);
		document.getElementById("listn").options.remove(0);
		document.getElementById("listp").options.remove(0);
        function SelAll()
        {
            if(document.getElementById("listc").style.display!="none" ||
                document.getElementById("listd").style.display!="none" ||
                document.getElementById("listn").style.display!="none" ||
                document.getElementById("listp").style.display!="none")
            {
                var List;
                if(document.getElementById("listc").style.display!="none")
                {
                    List=document.getElementById("listc");
                }
                if(document.getElementById("listd").style.display!="none")
                {
                    List=document.getElementById("listd");
                }
                if(document.getElementById("listn").style.display!="none")
                {
                    List=document.getElementById("listn");
                }
                if(document.getElementById("listp").style.display!="none")
                {
                    List=document.getElementById("listp");
                }
                for(var i=0;i<List.options.length;i++)
                {
                    List.options[i].selected=true;
                }
                ShwHid(List);
            }

        }
		function myExport()
		{
			var v1;
			var v2;
			v1="";
			v2=""
			if(document.getElementById('dv0')!=null)
			{
				v1=v1+document.getElementById('dv0').innerHTML+"~";
				v2=v2+document.getElementById('pr0').innerHTML.replace("%","")+"~";
			}
			if(document.getElementById('dv1')!=null)
			{
				v1=v1+document.getElementById('dv1').innerHTML+"~";
				v2=v2+document.getElementById('pr1').innerHTML.replace("%","")+"~";
			}
			if(document.getElementById('dv2')!=null)
			{
				v1=v1+document.getElementById('dv2').innerHTML+"~";
				v2=v2+document.getElementById('pr2').innerHTML.replace("%","")+"~";
			}
			if(document.getElementById('dv3')!=null)
			{
				v1=v1+document.getElementById('dv3').innerHTML+"~";
				v2=v2+document.getElementById('pr3').innerHTML.replace("%","")+"~";
			}
			if(document.getElementById('dv4')!=null)
			{
				v1=v1+document.getElementById('dv4').innerHTML+"~";
				v2=v2+document.getElementById('pr4').innerHTML.replace("%","")+"~";
			}
			if(document.getElementById('dv5')!=null)
			{
				v1=v1+document.getElementById('dv5').innerHTML+"~";
				v2=v2+document.getElementById('pr5').innerHTML.replace("%","")+"~";
			}
			if(document.getElementById('dv6')!=null)
			{
				v1=v1+document.getElementById('dv6').innerHTML+"~";
				v2=v2+document.getElementById('pr6').innerHTML.replace("%","")+"~";
			}
			if(document.getElementById('dv7')!=null)
			{
				v1=v1+document.getElementById('dv7').innerHTML+"~";
				v2=v2+document.getElementById('pr7').innerHTML.replace("%","")+"~";
			}
			v1=v1.substring(0,v1.length-1);
			v2=v2.substring(0,v2.length-1);
			var loc=window.location.href;
            var loc1;
            var loc2;
            var loc3;
            var loc4;
            loc1="&p=";
            loc2="&d=";
            loc3="&s=";
            loc4="&f=";
            if(document.getElementById("province_id").value != "")
            {
                loc1=loc1+document.getElementById("province_id").options[document.getElementById("province_id").selectedIndex].text;
            }
            if(document.getElementById("district_id").value != "")
            {
                loc2=loc2+document.getElementById("district_id").options[document.getElementById("district_id").selectedIndex].text;
            }
            if(document.getElementById("region_c_id").value != "")
            {
                loc3=loc3+document.getElementById("region_c_id").options[document.getElementById("region_c_id").selectedIndex].text;
            }
            if(document.getElementById("facilityInput").value != "")
            {
                loc4=loc4+document.getElementById("facilityInput").options[document.getElementById("facilityInput").selectedIndex].text;
            }
			window.location=loc.substr(0,loc.indexOf("?"))+"csv?v1="+v1+"&v2="+v2+loc1+loc2+loc3+loc4;
		}
		function Sel()
		{
			if(document.getElementById("ques").value!="")
			{
			 var Vls=document.getElementById("ques").value.split(",");
			 for(var i=0;i<Vls.length;i++)
			 {
				if(document.getElementById('qualification_id').value=="6")
				{
					document.getElementById('listc').options[Vls[i]].selected=true;
					document.getElementById('dv'+i).innerHTML=document.getElementById('listc').options[Vls[i]].text;
				}
				if(document.getElementById('qualification_id').value=="7")
				{
					document.getElementById('listd').options[Vls[i]].selected=true;
					document.getElementById('dv'+i).innerHTML=document.getElementById('listd').options[Vls[i]].text;
				}
				if(document.getElementById('qualification_id').value=="8")
				{
					document.getElementById('listn').options[Vls[i]].selected=true;
					document.getElementById('dv'+i).innerHTML=document.getElementById('listn').options[Vls[i]].text;
				}
				if(document.getElementById('qualification_id').value=="9")
				{
					document.getElementById('listp').options[Vls[i]].selected=true;
					document.getElementById('dv'+i).innerHTML=document.getElementById('listp').options[Vls[i]].text;
				}
			 }
			}
		}
		function SwHd(obj)
		{
			document.getElementById("listc").style.display="none";
			document.getElementById("listd").style.display="none";
			document.getElementById("listn").style.display="none";
			document.getElementById("listp").style.display="none";
			document.getElementById("listc").selectedIndex=0;
			document.getElementById("listd").selectedIndex=0;
			document.getElementById("listn").selectedIndex=0;
			document.getElementById("listp").selectedIndex=0;
			document.getElementById("listc").options[0].selected=false;
			document.getElementById("listd").options[0].selected=false;
			document.getElementById("listn").options[0].selected=false;
			document.getElementById("listp").options[0].selected=false;
			if(obj.value=="6")
			{
				document.getElementById("listc").style.display="inline";
			}
			if(obj.value=="7")
			{
				document.getElementById("listd").style.display="inline";
			}
			if(obj.value=="8")
			{
				document.getElementById("listn").style.display="inline";
			}
			if(obj.value=="9")
			{
				document.getElementById("listp").style.display="inline";
			}
		}
		function ShwHid(obj)
		{
			document.getElementById("ques").value="";
			for(var i=0;i<obj.options.length;i++)
			{
				if(obj.options[i].selected)
				{
					document.getElementById("ques").value=document.getElementById("ques").value+i+",";
				}
			}
			document.getElementById("ques").value=document.getElementById("ques").value.replace(/,+$/,'');
		}
        function PrintProvince()
        {
            if(document.getElementById("province_id").value != "")
            {
                document.write(document.getElementById("province_id").options[document.getElementById("province_id").selectedIndex].text);
            }
        }
        function PrintDistrict()
        {
            if(document.getElementById("district_id").value != "")
            {
                document.write(document.getElementById("district_id").options[document.getElementById("district_id").selectedIndex].text);
            }
        }
        function PrintSubdistrict()
        {
            if(document.getElementById("region_c_id").value != "")
            {
                document.write(document.getElementById("region_c_id").options[document.getElementById("region_c_id").selectedIndex].text);
            }
        }
        function PrintFacility()
        {
            if(document.getElementById("facilityInput").value != "")
            {
                document.write(document.getElementById("facilityInput").options[document.getElementById("facilityInput").selectedIndex].text);
            }
        }
	</script>
	<input type="hidden" name="listcq" id="listcq" value="1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20~21,22,23" />
	<input type="hidden" name="listdq" id="listdq" value="1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18~01,02,03,04,05,06,08,09~31,32,33,34,35,36,37~41,42,43,44~51,52,53,54,55,56,57,58,59,510,511,512,513,514,515,516,517,518~61,62,63,64,65,66,67~71,72,73,74,75,76,77,78,79,710,711~21,22,23" />
	<input type="hidden" name="listnq" id="listnq" value="1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,200~01,02,03,04,05,06,07,08,09~31,32,33,34,35,36,37,38~41,42,43,44,45~51,52,53,54,55,56,57,58,59,510,511,512,513~61,62,63,64,65~71,72,73,74,75,76,77,78,79,710,711~21,22,23" />
	<input type="hidden" name="listpq" id="listpq" value="1,2,3,4,5,6,7~8,9,10" />
	<input type="hidden" name="ques" id="ques" value="<?php echo $this->criteria['ques'] ?>" />
	<input type="hidden" name="limit" id="limit" value="1" />
    <input type="submit" onclick="if(document.getElementById('ques').value==''){alert('<?php echo t('Please select a competence'); ?>');return false;}" class="submitNoArrow" name="go" value="<?php tp('Preview');?>" />
   </fieldset>
   </form>
<?php if ( $this->criteria['go'] ) { ?>
		    <div class="hrGrey"></div>
		    <div class="fieldIndentNoMargin"><?php tp('Results');?></span><span class="printAndExport"><a href="javascript:window.print()"><?php echo t('Print'); ?></a>&nbsp;&nbsp;<a href="javascript:myExport()">Export</a>&nbsp;&nbsp;<a href="javascript:myExport()"><img src="<?php echo (Settings::$COUNTRY_BASE_URL).'/images/excel.jpg'; ?>" /></a></span></div>
<?php
if(isset($this->rss[0]))
{
	$cntr;
	$cntr=0;
	echo '<table cellpadding="0" cellspacing="0" border="0" style="width:40%;border:solid 1px #AAA">';
	echo '<tr><td><div class="nwtxtbig"><?php echo t('Competence'); ?></div></td><td><div class="nwtxtbig"><?php echo t('Province'); ?></div></td><td><div class="nwtxtbig"><?php echo t('District'); ?></div></td><td><div class="nwtxtbig"><?php echo t('Sub-district'); ?></div></td><td><div class="nwtxtbig"><?php echo t('Facility'); ?></div></td><td><div class="nwtxtbig"><?php echo t('Result'); ?></div></td></tr>';
	foreach ( $this->rss as $ys => $ls ) {
	 echo '<tr><td><div class="nwtxt" id="dv'.$cntr.'"></div></td>';
	 echo '<td><div class="nwtxt" id="lcc1'.$cntr.'">';
     echo '<script type="text/javascript">PrintProvince()</script>';
	 echo '</div></td>';
	 echo '<td><div class="nwtxt" id="lcc2'.$cntr.'">';
     echo '<script type="text/javascript">PrintDistrict()</script>';
	 echo '</div></td>';
	 echo '<td><div class="nwtxt" id="lcc3'.$cntr.'">';
     echo '<script type="text/javascript">PrintSubdistrict()</script>';
	 echo '</div></td>';
	 echo '<td><div class="nwtxt" id="lcc4'.$cntr.'">';
     echo '<script type="text/javascript">PrintFacility()</script>';
	 echo '</div></td>';
	 echo '<td><div class="nwtxt" id="pr'.$cntr.'">';
	 echo $ls.'%';
	 echo '</div></td>';
	 echo '</tr>';
	 $cntr=$cntr+1;;
	}
	echo '</table>';
}
?>
<?php } ?>
  </div>
  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>


</div>

</body>
</html>