<select id="listd1" style="display:none" multiple="multiple">
<option value="1">Take an appropriate history of all patients?</option>
<option value="2">Provide patients with HIV counseling and screening tests?</option>
<option value="3">Provide patients with opt-out HIV testing?</option>
<option value="4">Advise HIV positive patients to encourage partners and children to test?</option>
<option value="5">Screen for and manage HIV and AIDS opportunistic infections?</option>
<option value="6">Identify patients eligible for treatment using SA criteria for eligibility?</option>
<option value="7">Discuss chronic or other medication including possible drug interactions?</option>
<option value="8">Prescribe ARVs to HIV positive patients?</option>
<option value="9">Provide follow up for patients on ART?</option>
<option value="10">Provide family planning for HIV positive patients?</option>
<option value="11">Discuss rights and access for HIV positive patients?</option>
<option value="12">Initiate and manage support groups?</option>
<option value="13">Treat the common ART side effects in patients?</option>
<option value="14">Screen for and treat HIV positive patients with TB and HBV co-infection?</option>
<option value="15">Identify and treat patients with clinical depression?</option>
<option value="16">Provide mentorship support for lay counselors?</option>
<option value="17">Provide mentorship support for nursing staff?</option>
<option value="18">Provide the correct level of referral for treatment when required?</option>
</select>
<select id="listd2" style="display:none" multiple="multiple">
<option value="01">Correctly diagnose, classify, and treat HIV positive infants and children?</option>
<option value="02">Treat ARV side effects in children?</option>
<option value="03">Correctly treat an HIV positive child with TB and on ARV therapy?</option>
<option value="04">Provide counseling for HIV positive children and their caregivers?</option>
<option value="05">Monitor the nutritional status of HIV positive children?</option>
<option value="06">Explain the importance of ARV adherence to HIV positive children and their caregivers?</option>
<option value="08">Follow up with HIV positive children who miss their appointments?</option>
<option value="09">Provide the correct level of referral for treatment when required?</option>
</select>
<select id="listd3" style="display:none" multiple="multiple">
<option value="31">Recognise and correctly diagnose TB in patients?</option>
<option value="32">Screen for HIV in TB infected patients?</option>
<option value="33">Initiate and manage all patients with TB?</option>
<option value="34">Follow up with smear negative patients?</option>
<option value="35">Manage MDR and XDR in co-infected patients?</option>
<option value="36">Manage common ART side effects in TB patients?</option>
<option value="37">Provide the correct level of referral for treatment when required?</option>
</select>
<select id="listd4" style="display:none" multiple="multiple">
<option value="41">Recognise and correctly diagnose and manage STIs in patients syndromically?</option>
<option value="42">Manage patients with positive syphilis results?</option>
<option value="43">Follow up with patients who do not show up for appointments?</option>
<option value="44">Provide the correct level of referral for treatment when required?</option>
</select>
<select id="listd5" style="display:none" multiple="multiple">
<option value="51">Treat HIV positive pregnant women?</option>
<option value="52">Initiate ART prophylaxis and treatment for HIV positive women during pregnancy, labour and postnatal periods using the 2010 protocols?</option>
<option value="53">Recognise and treat common ART side effects in HIV positive pregnant women?</option>
<option value="54">Provide counseling on contraceptives, emergency pill and dual protection information for HIV positive women?</option>
<option value="55">Provide counseling on and termination of unwanted pregnancies according to guidelines?</option>
<option value="56">Correctly treat HIV positive pregnant and lactating women with TB/HBV infection who are also on ART?</option>
<option value="57">Follow up with HIV positive pregnant women who miss their appointments?</option>
<option value="58">Provide the correct level of referral for treatment when required?</option>
<option value="59">Promote, monitor and support safe infant feeding?</option>
<option value="510">Promote childhood immunisation?</option>
<option value="511">Provide Basic Antenatal Care (BANC) using integrated BANC/HIV checklists?</option>
<option value="512">Manage labour according to the modified obstetrical practices?</option>
<option value="513">Collect DBS -PCR specimen from exposed infants?</option>
<option value="514">Initiate infants eligible for ART?</option>
<option value="515">Provide maternal nutritional counseling and support?</option>
<option value="516">Counsel women and partners/family on postnatal care?</option>
<option value="517">Provide Cotrimoxazole prophylaxis?</option>
<option value="518">Promote partner or spouse involvement?</option>
</select>
<select id="listd6" style="display:none" multiple="multiple">
<option value="61">Provide counseling to persons who have experienced sexual or occupational exposure to HIV?</option>
<option value="62">Provide prophylactic treatment to exposed patients and health care workers?</option>
<option value="63">Perform physical examination for a victim of sexual assault (and complete Form J88)?</option>
<option value="64">Protect yourself from HIV exposure (e.g. needle stick injury)?</option>
<option value="65">Provide care for sexually assaulted adults and children?</option>
<option value="66">Provide the correct level of referral for treatment when required?</option>
<option value="67">Provide follow up care, management and support?</option>
</select>
<select id="listd7" style="display:none" multiple="multiple">
<option value="71">Understand and use the 2007 guidelines on nutrition for people living with HIV, AIDS, TB and other chronic debilitating conditions?</option>
<option value="72">Understand and use the CCMT/ART guidelines for adults and children?</option>
<option value="73">Understand and use the Sexual Assault Management guidelines?</option>
<option value="74">Understand and use the Contraceptive Management guidelines?</option>
<option value="75">Understand and use the Choice on Termination of Pregnancy Act (No. 92 of 1996)?</option>
<option value="76">Understand and use the National STI syndromic management guidelines?</option>
<option value="77">Understand and use the Prevention of Mother to Child Transmission guidelines?</option>
<option value="78">Understand and use the Maternity guidelines?</option>
<option value="79">Understand and use the National TB Control guidelines?</option>
<option value="710">Understand and use the IMCI booklet?</option>
<option value="711">Understand and use the National HIV Counselor Mentorship guidelines?</option>
</select>
<select id="listd8" style="display:none" multiple="multiple">
<option value="21">Do you require additional training to perform your tasks?</option>
<option value="22">Would you like to become a mentor?</option>
<option value="23">Do you feel prepared to become a mentor?</option>
</select>