<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title><?php echo $this->translation['Application Name'];?> | <?php tp('Trainings'); echo ' '.t('with').space.t('Unknown Participants');?> </title>
<?php
require_once('views/helpers/Location.php');
require_once('views/helpers/DropDown.php');
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();

$checkLabel = t('show');

if ( $this->mode == 'count' ) {
  $checkLabel = t('group');
}


?>

<script type="text/javascript">
	function gotoPage(objId) {
		var reportSelector = YAHOO.util.Dom.get(objId);
		if ( reportSelector[reportSelector.selectedIndex].value ) {
			window.location = '<?php echo $this->base_url;?>' + reportSelector[reportSelector.selectedIndex].value + '?<?php echo $_SERVER['QUERY_STRING'];?>';
		}
	}
</script>

</head>
<body class="yui-skin-sam">
<div id="pageHolder">

  <div id="header"><?php require_once('views/scripts/header.phtml');?></div>
  <div id="content">

    <h1><?php tp('Training');?> <?php echo ($this->mode != 'search'? t('Reports'):t('Search') );  ?></h1>
 <?php if ($this->mode != 'search' ) { ?>
    	<div class="fieldLabel" style="width: auto;"><?php echo t('Select').' '.t('Training').' '.t('report');?></div>
    	<select id="training" name="training" onchange="gotoPage('training');">
    		<option value="">--<?php tp('choose');?>--</option>
        <option value="/reports/trainings" <?php if ($this->mode == 'id') echo 'selected="selected"';?>><?php echo t('Trainings').' '.t('by').' '.t('Name');?></option>
        <option value="/reports/trainingByTitle" <?php if ($this->expand_lists) echo 'selected="selected"';?>><?php echo t('Trainings').' '.t('by').' '.t('Multiple Names');?></option>
        <option value="/reports/training-by-participants" <?php if ($this->mode == 'count') echo 'selected="selected"';?>><?php echo t('Trainings').' '.t('by').' '.t('Participant Count');?></option>
        <?php if ($this->setting['display_viewing_location']) { ?>
        <option value="/reports/budget-code"><?php echo t('Trainings').space.t('by').space.t('Participants').space.t('Viewing Location'); ?></option>
        <?php } ?>
        <?php if ($this->setting['module_unknown_participants_enabled']) { ?>
        <option value="/reports/training-unknown" <?php if ($this->mode == 'unknown') echo 'selected="selected"';?>><?php echo t('Trainings').' '.t('with').' '.t('Unknown Participants');?></option>
         <?php } ?>
        <option value="/reports/trainings-missing-information" <?php if ($this->missing_info) echo 'selected="selected"';?>><?php echo t('Trainings').' '.t('with').' '.t('Missing Information');?></option>
   	</select>
   <?php } ?>
	   <form action="" method="get">
   <fieldset <?php if( $checkLabel) echo 'id="criteria"'; ?> ><legend><?php tp('Select Criteria');?></legend>
<div id="dividers" >
<?php if ($checkLabel) { ?>
     	<div class="fieldLabel" ></div>
    	<div class="fieldInput criteria-header"><div  class="criteria-label" ><?php echo $checkLabel;?></div><div  class="criteria-label" style="padding-left: 20px;"><?php tp('filter');?></div></div>
<?php } ?>

<?php region_filters_dropdown($this, $this->locations, $this->criteria, true, true);  ?>

<!-- TA:17: 09/02/2014-->
<?php 
if($this->setting['display_training_category']){
   echo DropDown::render_report_filter('training_category', 'showCategory', @$this->translation['Training Category'], $this->category, 'training_category_phrase', @$this->criteria['training_category_id'], $this->criteria['showCategory']);
}
?>

	<div class="fieldLabel" id="training_title_option_id_lbl"><?php echo (@$this->translation['Training Name']); ?></div>
	<div class="fieldInput"><div class="leftBorderPad" ><input type="checkbox" name="showTrainingTitle"  <?php  if ($this->criteria['showTrainingTitle']) echo 'checked="checked"';?> /></div><label for="showTrainingTitle" ></label>
	<div  class="leftBorder"><select class="fixed" id="select_training_title_option" name="training_category_and_title_id" >
		<option value="">--<?php tp('All');?>--</option>
		<?php
      $lastId = NULL;
      foreach ( $this->categoryTitle as $vals ) {
        $isselected = ($vals['id'] === @$this->criteria['training_title_option_id']) ? ' selected="selected"' : '';

        // Also list empty prefix to allow all titles to be displayed
        if($vals['training_category_option_id'] && $vals['id'] != $lastId) {
          echo '<option value="_'.$vals['id'].'"'.$isselected.'>'.$vals['training_title_phrase'].'</option>';
        }

        echo '<option value="'. $vals['training_category_option_id'].'_'.$vals['id'].'"'.$isselected.'>'.$vals['training_title_phrase'].'</option>';
        $lastId = $vals['id'];
      }
		?>
  </select></div></div>

    <script type="text/javascript">
    // Set correct title
    elCategory = YAHOO.util.Dom.get("training_category_id");
    elTitle = YAHOO.util.Dom.get("select_training_title_option");
    elCategory.onchange = function() { setTrainingTitle(this.selectedIndex,'training_category_id','select_training_title_option'); }
    setTrainingTitle(elCategory.selectedIndex,'training_category_id','select_training_title_option');

	</script>


	<div class="fieldLabel" id="training_location_id_lbl"><?php echo t('Training').' '.t('location');?></div>
	<div class="fieldInput"><div  class="leftBorderPad"><input type="checkbox" name="showLocation"  <?php  if ($this->criteria['showLocation']) echo 'checked="checked"';?> /></div><label for="showLocation" ></label>

	<div  class="leftBorder">

	<?php
		training_location_dropdown( $this->tlocations, @$this->criteria['training_location_id'], 'name="training_location_id" id="select_training_location"');
	?>

</div></div>
  <?php
      //echo DropDown::render_report_filter('qualification_option', 'showQualification', t('Qualification'), $this->qualifications, 'qualification_phrase', @$this->criteria['qualification_option_id'], $this->criteria['showQualification']);
  ?>
<div class="fieldLabel" id="qualification_option_id_lbl"><?php tp('Qualification');?></div>
  <div class="fieldInput"><div  class="leftBorderPad"><input type="checkbox" name="showQualification"  <?php  if ($this->criteria['showQualification']) echo 'checked="checked"';?> /></div><label for="showQualification" ></label>  <div  class="leftBorder">    <select id="qualification_option_id" name="qualification_option_id">
  <option value="">--<?php tp('choose');?>--</option>
  <?php
    $lastParent = null;
    foreach ( $this->qualifications as $vals ) {
    if ( !$vals['id'] ) {
      $lastParent = ($vals['parent_phrase']);
      echo '<option value="'.$vals['parent_id'].'" '.($this->criteria['qualification_option_id'] == $vals['parent_id'] ?'selected="selected"':'').'>'.htmlspecialchars($vals['parent_phrase']).'</option>';
    } else {
      echo '<option value="'.$vals['id'].'" '.($this->criteria['qualification_option_id'] == $vals['id'] ?'selected="selected"':'').'>&nbsp;&nbsp;'. htmlspecialchars($vals['qualification_phrase']).'</option>';
    }
  }
    ?>
</select></div></div>
  <?php
      echo DropDown::render_report_filter('age_range_option', 'showAgeRange', t('Age Range'), $this->age_range, 'age_range_phrase', @$this->criteria['age_range_option_id'], $this->criteria['showAgeRange']);
  ?>
<div class="fieldLabel" id="is_tot_lbl"><?php tp('Gender'); ?></div>
  <div class="fieldInput"><div  class="leftBorderPad"><input type="checkbox" name="showGender"   <?php  if ($this->criteria['showGender']) echo 'checked="checked"';?> /></div><label for="showGender" ></label>

  <div  class="leftBorder">
   </div></div>
    <?php


  echo DropDown::render_report_filter('training_organizer','showOrganizer',(@$this->translation['Training Organizer']),$this->organizers,'training_organizer_phrase',$this->criteria['training_organizer_id'],$this->criteria['showOrganizer']);
  if ( $this->setting['display_training_topic'] ) {
      echo DropDown::render_report_filter('training_topic', 'showTopic', @$this->translation['Training Topic'], $this->topics, 'training_topic_phrase', @$this->criteria['training_topic_id'], $this->criteria['showTopic'],false, true);
   }

   //TA:17: 09/02/2014
   if($this->setting['display_training_start_date']){
   echo DropDown::render_report_filter('training_level', 'showLevel', @$this->translation['Training Level'], $this->levels, 'training_level_phrase', @$this->criteria['training_level_id'], $this->criteria['showLevel']);
   }
   echo DropDown::render_report_filter('training_pepfar', 'showPepfar', @$this->translation['PEPFAR Category'], $this->pepfars, 'pepfar_category_phrase', @$this->criteria['training_pepfar_id'], $this->criteria['showPepfar']);

   if ( $this->setting['display_training_method'] && $this->mode != 'search') {
    echo DropDown::render_report_filter('training_method', 'showMethod', @$this->translation['Training Method'], $this->methods, 'training_method_phrase', @$this->criteria['funding_id'], $this->criteria['showMethod']);
   }

   if ( $this->setting['display_funding_options'] && $this->mode != 'search') {
    echo DropDown::render_report_filter('training_funding', 'showFunding', t('Funding'), $this->funding, 'funding_phrase', @$this->criteria['funding_id'], $this->criteria['showFunding']);
   }
    if ( $this->setting['display_funding_amount'] && $this->mode != 'search') { ?>
      <div class="fieldLabel" ></div><div class="fieldInput"><div  class="leftBorderPad"></div>
      <div class="leftBorder" >
		  <div id="funding_min_lbl" style="float:left;  margin-top: .5em; padding-left:2em;"><?php tp('Min'); ?> $</div>
      <input type="text" value=""  style="float:left;" size="6" maxlength="10" name="funding_min" />
      <div id="funding_max_lbl"  style="float:left; margin-top: .5em;"><?php tp('Max'); ?> $</div>
      <input type="text" value=""  style="float:left;" size="6" maxlength="10" name="funding_max" />
      </div>

   </div>
  <?php }?>

 	<?php if ( $this->setting['display_training_trainers'] && $this->mode != 'search') { ?>
	<div class="fieldLabel" id="is_tot_lbl"><?php echo (@$this->translation['Training of Trainers']); ?></div>
	<div class="fieldInput"><div  class="leftBorderPad"><input type="checkbox" name="showTot"   <?php  if ($this->criteria['showTot']) echo 'checked="checked"';?> /></div><label for="showTot" ></label>

	<div  class="leftBorder">
   </div></div>
	<?php } ?>

 	<?php if ( $this->setting['display_training_refresher'] && $this->mode != 'search') { ?>
	<div class="fieldLabel" id="is_refresher_lbl"><?php echo (@$this->translation['Refresher Course']); ?></div>
	<div class="fieldInput"><div  class="leftBorderPad"><input type="checkbox" name="showRefresher"   <?php  if ($this->criteria['showRefresher']) echo 'checked="checked"';?> /></div><label for="showRefresher" ></label>
	<div class="leftBorder"></div></div>
	<?php } ?>

 	<?php if ( $this->setting['display_training_got_curric'] && $this->mode != 'search') {
 	  echo DropDown::render_report_filter('training_got_curric', 'showGotCurric', @$this->translation['GOT Curriculum'], $this->gotcurric, 'training_got_curriculum_phrase', @$this->criteria['training_got_curric_id'], $this->criteria['showGotCurric']);
  } ?>

 	<?php if ( $this->setting['display_training_got_comment'] && $this->mode != 'search') { ?>
	<div class="fieldLabel" id="got_comment_lbl"><?php echo (@$this->translation['GOT Comment']); ?></div>
	<div class="fieldInput"><div  class="leftBorderPad"><input type="checkbox" name="showGotComment"   <?php  if ($this->criteria['showGotComment']) echo 'checked="checked"';?> /></div><label for="showGotComment" ></label>
	<div class="leftBorder"></div></div>
	<?php } ?>
  <?php
   if ( $this->setting['display_primary_language'] && $this->mode != 'search') {
    echo DropDown::render_report_filter('training_primary_language_option', 'showPrimaryLanguage', @$this->translation['Primary Language'], $this->language, 'language_phrase', @$this->criteria['training_primary_language_option_id'], $this->criteria['showPrimaryLanguage']);
   }

   if ( $this->setting['display_secondary_language'] && $this->mode != 'search') {
    echo DropDown::render_report_filter('training_secondary_language_option', 'showSecondaryLanguage', @$this->translation['Secondary Language'], $this->language, 'language_phrase', @$this->criteria['training_secondary_language_option_id'], $this->criteria['showSecondaryLanguage']);
   }
   ?>
  <?php if ( $this->setting['display_training_custom1'] ) { ?>
  <div class="fieldLabel" id="person_custom1_lbl"><?php print $this->translation['Training Custom 1']; ?></div>
  <div class="fieldInput"><div  class="leftBorderPad" ><input type="checkbox" name="showCustom1"   <?php  if ($this->criteria['showCustom1']) echo 'CHECKED';?> /></div><label for="showCustom1" ></label>

  <div  class="leftBorder"><select id="custom_1_id" name="custom_1_id" >
    <option value="">--<?php tp('All');?>--</option>
    <?php
      foreach ( $this->custom1 as $vals ) {
        echo '<option value="'.$vals['id'].'" '.((@$this->criteria['custom_1_id']) == $vals['id']? 'SELECTED="selected"':'').' >'.($this->truncate($vals['custom1_phrase'],45)).'</option>';
    }
    ?>
  </select></div></div>
  <?php } ?>
  <?php if ( $this->setting['display_training_custom2'] ) { ?>
  <div class="fieldLabel" id="person_custom2_lbl"><?php print $this->translation['Training Custom 2']; ?></div>
  <div class="fieldInput"><div  class="leftBorderPad" ><input type="checkbox" name="showCustom2"   <?php  if ($this->criteria['showCustom2']) echo 'CHECKED';?> /></div><label for="showCustom2" ></label>

  <div  class="leftBorder"><select id="custom_2_id" name="custom_2_id" >
    <option value="">--<?php tp('All');?>--</option>
    <?php
      foreach ( $this->custom2 as $vals ) {
        echo '<option value="'.$vals['id'].'" '.((@$this->criteria['custom_2_id']) == $vals['id']? 'SELECTED="selected"':'').' >'.($this->truncate($vals['custom2_phrase'],45)).'</option>';
    }
    ?>
  </select></div></div>
  <?php } ?>
  <?php if ( $this->setting['display_training_custom3'] ) { ?>
  <div class="fieldLabel" id="person_custom3_lbl"><?php print $this->translation['Training Custom 3']; ?></div>
  <div class="fieldInput"><div  class="leftBorderPad" ><input type="checkbox" name="showCustom3"   <?php  if ($this->criteria['showCustom3']) echo 'CHECKED';?> /></div><label for="showCustom3" ></label>

  <div  class="leftBorder"><select id="custom_3_id" name="custom_3_id" >
    <?php print_r($this->custom3); ?>
    <option value="">--<?php tp('All');?>--</option>
    <?php
      foreach ( $this->custom3 as $vals ) {
        if(! trim($vals['custom_3']))
          continue;
        echo '<option value="'.$vals['id'].'" '.((@$this->criteria['custom_3_id']) == $vals['id']? 'SELECTED="selected"':'').' >'.($this->truncate($vals['custom_3'],45)).'</option>';
    }
    ?>
  </select></div></div>
  <?php } ?>
  <?php if ( $this->setting['display_training_custom4'] ) { ?>
  <div class="fieldLabel" id="person_custom4_lbl"><?php print $this->translation['Training Custom 4']; ?></div>
  <div class="fieldInput"><div  class="leftBorderPad" ><input type="checkbox" name="showCustom4"   <?php  if ($this->criteria['showCustom4']) echo 'CHECKED';?> /></div><label for="showCustom4" ></label>

  <div  class="leftBorder"><select id="custom_4_id" name="custom_4_id" >
    <option value="">--<?php tp('All');?>--</option>
    <?php
      foreach ( $this->custom4 as $vals ) {
        if(! trim($vals['custom_4']))
          continue;
        echo '<option value="'.$vals['id'].'" '.((@$this->criteria['custom_4_id']) == $vals['id']? 'SELECTED="selected"':'').' >'.($this->truncate($vals['custom_4'],45)).'</option>';
    }
    ?>
  </select></div></div>
  <?php } ?>
  <?php if ( $this->setting['display_end_date'] && $this->mode != 'search' && $this->mode != 'count') { ?>
  <div class="fieldLabel" id="show_end_lbl"><?php tp('End date'); ?></div>
  <div class="fieldInput"><div  class="leftBorderPad"><input type="checkbox" name="showEndDate"   <?php  if ($this->criteria['showEndDate']) echo 'checked="checked"';?> /></div><label for="showEndDate" ></label>

  <div  class="leftBorder">
   </div></div>
  <?php } ?>
  </div>
  
  <!-- TA:17: 09/03/2014-->
<?php if($this->setting['display_training_start_date']){ ?>
	<div class="clear"></div><br/><br/>
<div class="fieldLabel"><?php tp('Start date');?></div>
<div class="fieldInput" id="startdate">
    <?php tp('Day');?> <input id="start-day" class="dayfield" type="text" name="start-day" maxlength="2" value="<?php echo $this->criteria['start-day']; ?>"  />
    / <?php tp('Month');?> <input id="start-month" class="monthfield" type="text" name="start-month" maxlength="2" value="<?php echo $this->criteria['start-month']; ?>"  />
    / <?php tp('Year');?> <input id="start-year" class="yearfield" type="text" name="start-year" maxlength="4" value="<?php echo $this->criteria['start-year'];  ?>" />
		            <script  type="text/javascript">
		    YAHOO.util.Event.onDOMReady(function () {
		    	makeCalendar("startdate","start-day", "start-month", "start-year");
		    });
		</script>
	</div>
	<?php }?>
<div class="fieldLabel" style="padding-top:1em;"><?php tp('End date');?></div>
<div class="fieldInput" id="enddate" style="margin-top:1em;">
    <?php tp('Day');?> <input id="end-day" class="dayfield" type="text" name="end-day" maxlength="2" value="<?php echo $this->criteria['end-day']; ?>"  />
    / <?php tp('Month');?> <input id="end-month" class="monthfield" type="text" name="end-month" maxlength="2" value="<?php echo $this->criteria['end-month']; ?>"  />
    / <?php tp('Year');?> <input id="end-year" class="yearfield" type="text" name="end-year" maxlength="4" value="<?php echo $this->criteria['end-year'];  ?>" />
		            <script  type="text/javascript">
		    YAHOO.util.Event.onDOMReady(function () {
		    	makeAdditionalCalendar("enddate","end-day", "end-month", "end-year");
		    });
		</script>
	</div>

<?php if ( $this->mode == 'search') {?>
  <div class="clear"></div>
  <br/>
      <div class="fieldLabel"></div><div class="fieldInput" ><input type="radio" id="has_known_participants" value="has_known_participants" name="training_participants_type" <?php if ( $this->criteria['training_participants_type'] == 'has_known_participants') echo 'CHECKED'; ?> />&nbsp;<?php tp('Trainings with known participants only');?></div>
      <div class="fieldLabel"></div><div class="fieldInput" ><input type="radio" id="has_unknown_participants" value="has_unknown_participants" name="training_participants_type" <?php if ( $this->criteria['training_participants_type'] == 'has_unknown_participants' ) echo 'CHECKED'; ?> />&nbsp;<?php tp('Trainings with unknown participants only');?></div>
      <div class="fieldLabel"></div><div class="fieldInput" ><input type="radio" id="has_known_participants" value="has_everyone" name="training_participants_type" <?php if ( $this->criteria['training_participants_type'] == 'has_everyone' ) echo 'CHECKED'; ?> />&nbsp;<?php tp('All trainings');?></div>
<?php }?>
	<div class="clear"></div>
	<input type="hidden" name="limit" id="limit" value="1" />
   	<input type="submit" class="submitNoArrow" name="go" value="<?php tp('Preview');?>" />
   </fieldset>
   </form>
<?php if ( $this->criteria['go'] ) { ?>
<div class="hrGrey"></div>
    <div class="fieldIndentNoMargin"><?php tp('Trainings');?> <span class="total"><?php echo $this->count;?> <?php if ( $this->mode == 'count' ) echo t('Participants'); else echo '';?></span><?php echo $this->printAndExport();?></div>
<?php if ($this->mode == 'search' ) { ?>
	<a href="<?php echo $this->base_url;?>/training/add"><?php echo t('Add').' '.t('New').' '.t('Training');?></a><br/><br/>
<?php } ?>
    <div id="trainings" class="itechTable"></div>
    <script type="text/javascript">
    	        var formatViewUrl = function(elCell, oRecord, oColumn, sData) {
	            elCell.innerHTML = "<a href='<?php echo $this->base_url;?>/training/view/id/" + oRecord.getData("id") + "'>" + sData + "</a>";
	        };

	        var trainingData = [
<?php $isFirstRow = true;
$cnt = 0;
foreach($this->results as $row) {
	if ( (!$_REQUEST['limit'])  or ($cnt < 100) ) {
		if (!$isFirstRow )
			echo ',';
		$isFirstRow = false;
		echo '[';
		if (array_key_exists('cnt', $row) !== false )
		  echo ( $row['cnt'] ? $row['cnt'] : 0 ) ;
    if (isset($row['id'] ) )
      echo ((array_key_exists('cnt', $row) !== false )? ','.$row['id']: $row['id']);
		if ( isset($row['id']) )
			echo ',"'.$row['training_start_date'].'"';
    if ( $this->criteria['showEndDate'] )
      echo ',"'.$row['training_end_date'].'"';
		if ( $this->criteria['showProvince'] )
			echo ',"'.$row['province_name'].'"';
		if ( $this->criteria['showDistrict'] )
			echo ',"'.$row['district_name'].'"';
    if ( $this->criteria['showRegionC'] )
      echo ',"'.$row['region_c_name'].'"';
		if ( $this->criteria['showCategory'])
			echo ',"'.$row['training_category_phrase'].'"';
		if ( $this->criteria['showTrainingTitle'])
			echo ',"'.$row['training_title'].'"';
		if ( $this->criteria['showLocation'] )
			echo ',"'.$row['training_location_name'].'"';
    if ( $this->criteria['showGender'] ) {
      echo ',"'.$row['female_pcnt'].'"';
      echo ',"'.$row['male_pcnt'].'"';
      echo ',"'.$row['na_pcnt'].'"';
    }
    if ( $this->criteria['showQualification'] ) {
      echo ',"'.($row['parent_qualification_phrase']?$row['parent_qualification_phrase']:$row['qualification_phrase']).'"';
      echo ',"'.($row['parent_qualification_phrase']?$row['qualification_phrase']:'').'"';
    }
    if ( $this->criteria['showAgeRange'] )
      echo ',"'.$row['age_range_phrase'].'"';
			if ( $this->criteria['showOrganizer'] )
			echo ',"'.$row['training_organizer_phrase'].'"';
		if ( $this->criteria['showLevel'] )
			echo ',"'.$row['training_level_phrase'].'"';
		if ( $this->criteria['showTopic'] )
			echo ',"'.$row['training_topic_phrase'].'"';
		if ( $this->criteria['showPepfar'] )
			echo ',"'.$row['pepfar_category_phrase'].'"';
    if ( $this->criteria['showMethod'] )
      echo ',"'.$row['training_method_phrase'].'"';
		if ( $this->criteria['showFunding'] )
			echo ',"'.$row['funding_phrase'].'"';
      if ( $this->criteria['showTot'] )
			echo ',"'.$row['is_tot'].'"';
		if ( $this->criteria['showRefresher'] )
			echo ',"'.$row['is_refresher'].'"';
		if ( $this->criteria['showGotComment'] )
			echo ',"'.str_replace(array("\r\n", "\n","\r"), '<br />',htmlspecialchars($row['got_comments'])).'"';
    if ( $this->criteria['showPrimaryLanguage'] )
      echo ',"'.$row['primary_language_phrase'].'"';
    if ( $this->criteria['showSecondaryLanguage'] )
      echo ',"'.$row['secondary_language_phrase'].'"';
		if ( $this->criteria['showGotCurric'] )
			echo ',"'.$row['training_got_curriculum_phrase'].'"';
    if ( $this->criteria['showCustom1'] )
      echo ',"'.$row['custom1_phrase'].'"';
		if (array_key_exists('pcnt', $row) !== false )
      echo ','.( $row['pcnt'] );
		echo "]";
		$cnt++;
}}
   ?>];

var trainingColumnDefs = [
<?php if (isset($this->results[0]['cnt'])) { ?>
{key:"cnt", label: "<?php tp('Count');?>", sortable:true, resizeable:true}
<?php } ?>
<?php if (isset($this->results[0]['id'])) { ?>
<?php if (isset($this->results[0]['cnt'])) echo ',';?>
{key:"id", label: "ID", sortable:true, resizeable:true, formatter: formatViewUrl},
{key:"training_start_date", label: "<?php tp('Start Date');?>", sortable:true, resizeable:true}
<?php } ?>
<?php if ( $this->criteria['showEndDate'] ) { ?>
,{key:"training_end_date", label: "<?php tp('End Date');?>", sortable:true, resizeable:true}
<?php } ?>
<?php if ( $this->criteria['showProvince'] ) { ?>
   ,{key:"province_name", label: "<?php echo (@$this->translation['Region A (Province)']); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showDistrict'] ) { ?>
   ,{key:"district_name", label: "<?php echo (@$this->translation['Region B (Health District)']); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showRegionC'] ) { ?>
   ,{key:"region_c_name", label: "<?php echo (@$this->translation['Region C (Local Region)']); ?>", sortable:true, resizeable:true}
 <?php } ?>
 <?php if ( $this->criteria['showCategory']) { ?>
   ,{key:"training_category_phrase", label: "<?php echo (@$this->translation['Training Category']); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showTrainingTitle']) { ?>
   ,{key:"training_title", label: "<?php echo (@$this->translation['Training Name']); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showLocation'] ) { ?>
   ,{key:"training_location_name", label: "<?php tp('Location');?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showGender'] ) { ?>
   ,{key:"female_pcnt", label: "<?php tp('Female');?>", sortable:true, resizeable:true}
   ,{key:"male_pcnt", label: "<?php tp('Male');?>", sortable:true, resizeable:true}
   ,{key:"na_pcnt", label: "<?php tp('Unknown');?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showQualification'] ) { ?>
   ,{key:"primary_qualification_phrase", label: "<?php tp('Primary Qualification'); ?>", sortable:true, resizeable:true}
   ,{key:"qualification_phrase", label: "<?php tp('Qualification'); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showAgeRange'] ) { ?>
   ,{key:"age_range_phrase", label: "<?php tp('Age Range');?>", sortable:true, resizeable:true}
 <?php } ?>
 <?php if ( $this->criteria['showOrganizer'] ) { ?>
   ,{key:"training_organizer_phrase", label: "<?php echo (@$this->translation['Training Organizer']); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showLevel'] ) { ?>
   ,{key:"training_level_phrase", label: "<?php echo (@$this->translation['Training Level']); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showTopic'] ) { ?>
   ,{key:"training_topic_phrase", label: "<?php echo @$this->translation['Training Topic'];?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showPepfar'] ) { ?>
   ,{key:"pepfar_category_phrase", label: "<?php  echo @$this->translation['PEPFAR Category'];?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showMethod'] ) { ?>
   ,{key:"training_method_phrase", label: "<?php  echo @$this->translation['Training Method'];?>", sortable:true, resizeable:true}
 <?php } ?>
 <?php if ( $this->criteria['showFunding'] ) { ?>
   ,{key:"funding_phrase", label: "<?php tp('Funding');?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showTot'] ) { ?>
   ,{key:"is_tot", label: "<?php echo tp('TOT'); ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showRefresher'] ) { ?>
   ,{key:"is_refresher", label: "<?php echo tp('Refresher'); ?>", sortable:true, resizeable:true}
<?php } ?>
<?php if ( $this->criteria['showGotComment'] ) { ?>
   ,{key:"got_comments", label: "<?php echo @$this->translation['GOT Comment']; ?>", sortable:true, resizeable:true}
 <?php } ?>
<?php if ( $this->criteria['showPrimaryLanguage'] ) { ?>
   ,{key:"primary_language_phrase", label: "<?php echo @$this->translation['Primary Language']; ?>", sortable:true, resizeable:true}
 <?php } ?>
 <?php if ( $this->criteria['showSecondaryLanguage'] ) { ?>
   ,{key:"secondary_language_phrase", label: "<?php echo @$this->translation['Secondary Language']; ?>", sortable:true, resizeable:true}
 <?php } ?>
 <?php if ( $this->criteria['showGotCurric'] ) { ?>
   ,{key:"training_got_curriculum_phrase", label: "<?php echo @$this->translation['GOT Curriculum']; ?>", sortable:true, resizeable:true}
 <?php } ?>
 <?php   if ( $this->criteria['showCustom1'] ) { ?>
 ,{key:"custom1_phrase", label: "<?php echo (@$this->translation['Training Custom 1']); ?>", sortable:true, resizeable:true}
<?php } ?>
 <?php if (array_key_exists('pcnt', $this->results[0]) !== false) { ?>
 ,{key:"pcnt", label: "<?php tp('Participants');?>", sortable:true, resizeable:true}
 <?php } ?>
];

<?php if  ( $this->results ) { ?>
	makeDataTable("trainings", null, trainingData, trainingColumnDefs);
<?php } ?>
</script>
<?php if ($cnt < count($this->results)) { ?>
<div  class="fieldIndentNoMargin">[<?php tp('Limited to 100 rows');?>]  <a href="<?php echo str_replace('limit=1','limit=0',$_SERVER['REQUEST_URI']);?>"><?php tp('Full Results');?></a></div>
<?php } ?>
<?php } ?>
  </div>
   <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>


</div>

</body>
</html>