<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<title><?php echo $this->translation['Application Name'];?> | <?php echo ($this->identity->locale == 'nl_NL.UTF-8' ? t('Training Search') : ($this->mode != 'search'? t('Training Reports'):t('Training Search') )); ?></title>
		<?php
		require_once('views/helpers/Location.php');
		require_once('views/helpers/DropDown.php');
		require_once('views/helpers/TrainingViewHelper.php');
		require_once('views/helpers/ScriptContainer.php');
		print ScriptContainer::$instance->renderCSSHead();
		print ScriptContainer::$instance->renderJSHead();

		$checkLabel = ( $this->mode == 'count' ) ? t('group') : t('show');

		?>

		<script type="text/javascript">
			function gotoPage(objId) {
				var reportSelector = YAHOO.util.Dom.get(objId);
				if ( reportSelector[reportSelector.selectedIndex].value ) {
					window.location = '<?php echo $this->base_url;?>' + reportSelector[reportSelector.selectedIndex].value + '?<?php echo $_SERVER['QUERY_STRING'];?>';
				}
			}
		</script>

	</head>
	<body class="yui-skin-sam">
		<div id="pageHolder">
			<div id="header"><?php require_once('views/scripts/header.phtml');?></div>

			<div id="content">
				<h1><?php echo ($this->identity->locale == 'nl_NL.UTF-8' ? t('Training Search') : ($this->mode != 'search'? t('Training Reports Training Search') : ''));  ?></h1>

				<?php if ($this->mode != 'search' ) { ?>
				<div class="fieldLabel" style="width: auto;"><?php echo t('Select training report');?></div>
				<select id="training" name="training" onchange="gotoPage('training');">
					<option value="">--<?php tp('choose');?>--</option>
					<option value="/reports/trainings" <?php if ($this->mode == 'name') echo 'selected="selected"';?>><?php echo t('Trainings by Name');?></option>
					<option value="/reports/trainingByTitle" <?php if ($this->expand_lists) echo 'selected="selected"';?>><?php echo t('Trainings by Multiple Names');?></option>
					<option value="/reports/trainingByParticipants" <?php if ($this->mode == 'count') echo 'selected="selected"';?>><?php echo t('Trainings by Participant Count');?></option>
					<?php if ($this->setting['display_viewing_location']) { ?>
					<option value="/reports/budgetcode"><?php echo t('Trainings by Participants Viewing Location'); ?></option>
					<?php } ?>
					<?php if ($this->setting['module_unknown_participants_enabled']) { ?>
					<option value="/reports/trainingUnknown" <?php if ($this->mode == 'unknown') echo 'selected="selected"';?>><?php echo t('Trainings with Unknown Participants');?></option>
					<?php } ?>
					<option value="/reports/trainingsMissingInformation" <?php if ($this->missing_info) echo 'selected="selected"';?>><?php echo t('Trainings with missing information');?></option>
				</select>
				<?php } ?>
				<form id="trainingreport" action="" method="get">
					<?php if( $this->missing_info == '1') { ?>
					<fieldset ><legend><?php tp('Return trainings with NULL values in these fields');?></legend>
						<div class="fieldLabel" id="searchflds_lbl"><?php echo t('Report on Missing Data Fields'); ?></div>
						<div class="leftBorder autoHeight">
							<select id="searchflds" name="searchflds[]" class="fixed" multiple="multiple" size="20">
							<?php
								foreach ($this->flds as $tr => $value) {
									$sel = ( is_array($this->criteria['searchflds']) && array_search($value, $this->criteria['searchflds']) !== false ) ? ' selected' : '';
									echo '<option value="'.$value.'"'.$sel.'>'.t( $tr ).'</option>'.PHP_EOL;
								}
							?>
							</select>
						<p>&nbsp;</p>
					</div>
					</fieldset>
					<?php } ?>
					<fieldset <?php if( $checkLabel) echo 'id="criteria"'; if ($this->expand_lists) echo ' class="multiselect_report"'; ?> ><legend><?php tp('Select Criteria');?></legend>
						<div id="dividers" >
							<?php if ($checkLabel) { ?>
							<div class="fieldLabel" ></div>
							<div class="fieldInput criteria-header"><div  class="criteria-label" ><?php echo $checkLabel;?></div><div  class="criteria-label" style="padding-left: 20px;"><?php tp('filter');?></div></div>
							<?php } ?>

											<?php region_filters_dropdown($this, $this->locations, $this->criteria, true, true); ?>
											
											<!-- TA:17: 8/27/2014  START -->
											<?php if($this->setting['display_training_category']){
											echo DropDown::render_report_filter('training_category', 'showCategory', @$this->translation['Training Category'], $this->category, 'training_category_phrase', @$this->criteria['training_category_id'], $this->criteria['showCategory']);
											} ?>
											<!-- TA:17: 8/27/2014  END -->
											
											<div class="fieldLabel" id="training_title_option_id_lbl"><?php echo (@$this->translation['Training Name']); ?></div>
											<div class="fieldInput"><div class="leftBorderPad" ><input type="checkbox" name="showTrainingTitle"  <?php  if ($this->criteria['showTrainingTitle']) echo 'checked="checked"';?> /></div><label for="showTrainingTitle" ></label>
												<div  class="leftBorder"><select <?php echo ($this->expand_lists?'multiple="multiple" size="10"':'class="fixed"'); ?> id="select_training_title_option" name="training_category_and_title_id<?php if ($this->expand_lists) echo '[]'; ?>" >
													<option value="">--<?php tp('All');?>--</option>
													<?php
													$lastId = NULL;
													foreach ( $this->categoryTitle as $vals ) {
														$isselected = ($vals['id'] === @$this->criteria['training_title_option_id']) ? ' selected="selected"' : '';
														if ('_'.$vals['id'] == $this->criteria['training_title_option_id']) $isselected = 'selected="selected"'; // bugfix

														// Also list empty prefix to allow all titles to be displayed
														if($vals['training_category_option_id'] && $vals['id'] != $lastId) {
															echo '<option value="_'.$vals['id'].'"'.$isselected.'>'.$vals['training_title_phrase'].'</option>';
														}

														echo '<option value="'. $vals['training_category_option_id'].'_'.$vals['id'].'"'.$isselected.'>'.$vals['training_title_phrase'].'</option>';
														$lastId = $vals['id'];
													}
													?>
												</select></div></div>

												<script type="text/javascript">
													// Set correct title
													elCategory = YAHOO.util.Dom.get("training_category_id");
													elTitle = YAHOO.util.Dom.get("select_training_title_option");
													elCategory.onchange = function() { setTrainingTitle(this.selectedIndex,'training_category_id','select_training_title_option'); }
													setTrainingTitle(elCategory.selectedIndex,'training_category_id','select_training_title_option');

												</script>

												<!-- TA:17:14 -->
												<?php if($this->setting['display_training_location']){?>
												<div class="fieldLabel" id="training_location_id_lbl"><?php echo t('Training').' '.t('location');?></div>
												<div class="fieldInput"><div  class="leftBorderPad"><input type="checkbox" name="showLocation"  <?php  if ($this->criteria['showLocation']) echo 'checked="checked"';?> /></div><label for="showLocation" ></label>

													<div  class="leftBorder">
														<?php
			training_location_dropdown( $this->tlocations, @$this->criteria['training_location_id'], 'name="training_location_id" id="select_training_location"');
		?>
											</div></div>
											<?php }?>
											
											<?php
											echo DropDown::render_report_filter('training_organizer','showOrganizer',(@$this->translation['Training Organizer']),$this->organizers,'training_organizer_phrase',$this->criteria['training_organizer_id'],$this->criteria['showOrganizer'],false,false,($this->expand_lists?true:false));
											?>
											<?php if ( ! isset($this->setting['display_training_partner']) ) { $this->setting['display_training_partner'] = false; } ?>
											<?php if ($this->setting['display_training_partner'] ) { ?>
												<div class="fieldLabel" id="mechanism_id_lbl"><?php tp('Mechanism ID');?></div>
												<div class="fieldInput"><div  class="leftBorderPad"><input type="checkbox" name="showMechanism" <?php  if ($this->criteria['showMechanism']) echo 'checked="checked"';?> /></div><label for="showMechanism"></label>

												<div  class="leftBorder">    <select name="mechanism_id" id="select_mechanism" >
											    <option value="">--<?php tp('All');?> --</option>
											    <?php
												foreach($this->mechanisms as $vals) {
													echo '<option value="'.$vals['mechanism_id'].'" '.((@$this->criteria['mechanism_id']) == $vals['mechanism_id']? 'selected="selected"':'').' >'.($vals['mechanism_id']).'</option>';
												}
											    ?>
											    </select>
											</div></div>
											<?php } ?>

											<?php
											if ( $this->setting['display_training_topic'] ) {
												echo DropDown::render_report_filter('training_topic', 'showTopic', @$this->translation['Training Topic'], $this->topics, 'training_topic_phrase', @$this->criteria['training_topic_id'], $this->criteria['showTopic'],false, true,($this->expand_lists?true:false));
											}

											//TA:17: 09/03/2014 
											if($this->setting['display_training_level']){
												echo DropDown::render_report_filter('training_level', 'showLevel', @$this->translation['Training Level'], $this->levels, 'training_level_phrase', @$this->criteria['training_level_id'], $this->criteria['showLevel']);
											}
											//TA:17: 09/12/2014  
											if($this->setting['display_training_pepfar']){
												echo DropDown::render_report_filter('training_pepfar', 'showPepfar', @$this->translation['PEPFAR Category'], $this->pepfars, 'pepfar_category_phrase', @$this->criteria['training_pepfar_id'], $this->criteria['showPepfar']);
											}
											
											if ( $this->setting['display_training_method'] && $this->mode != 'search') {
												echo DropDown::render_report_filter('training_method', 'showMethod', @$this->translation['Training Method'], $this->methods, 'training_method_phrase', @$this->criteria['funding_id'], $this->criteria['showMethod']);
											}

											if ( $this->setting['display_funding_options'] && $this->mode != 'search') {
												echo DropDown::render_report_filter('training_funding', 'showFunding', t('Funding'), $this->funding, 'funding_phrase', @$this->criteria['funding_id'], $this->criteria['showFunding']);
												if ( $this->setting['display_funding_amount'] && $this->mode != 'search') { ?>
													<div class="fieldLabel" ></div><div class="fieldInput"><div  class="leftBorderPad"></div>
														<div class="leftBorder" >
															<div id="funding_min_lbl" style="float:left;  margin-top: .5em; padding-left:2em;"><?php tp('Min'); ?> $</div>
															<input type="text" value=""  style="float:left;" size="6" maxlength="10" name="funding_min" />
															<div id="funding_max_lbl"  style="float:left; margin-top: .5em;"><?php tp('Max'); ?> $</div>
															<input type="text" value=""  style="float:left;" size="6" maxlength="10" name="funding_max" />
														</div>

													</div>

													<?php
												}
											}
											?>

											<?php if ( $this->setting['display_training_trainers'] && $this->mode != 'search') { ?>
											<div class="fieldLabel" id="is_tot_lbl"><?php echo (@$this->translation['Training of Trainers']); ?></div>
											<div class="fieldInput"><div  class="leftBorderPad"><input type="checkbox" name="showTot"   <?php  if ($this->criteria['showTot']) echo 'checked="checked"';?> /></div><label for="showTot" ></label>

												<div  class="leftBorder">
												</div></div>
												<?php } ?>

												<?php if ( $this->setting['display_training_refresher'] && $this->mode != 'search') { ?>
											<?php if ( $this->setting['multi_opt_refresher_course'] && $this->refresherArray ) { ?>
											<?php echo DropDown::render_report_filter('training_refresher', 'showRefresher', @$this->translation['Refresher Course'], $this->refresherArray, 'refresher_phrase_option', @$this->criteria['refresher_id'], $this->criteria['showRefresher']); ?>
											<?php } else { ?>
												<div class="fieldLabel" id="is_refresher_lbl"><?php echo (@$this->translation['Refresher Course']); ?></div>
												<div class="fieldInput"><div  class="leftBorderPad"><input type="checkbox" name="showRefresher"   <?php  if ($this->criteria['showRefresher']) echo 'checked="checked"';?> /></div><label for="showRefresher" ></label>
												<div class="leftBorder"></div></div>
													<?php } ?>
											<?php } ?>

													<?php if ( $this->setting['display_training_got_curric'] && $this->mode != 'search') {
														echo DropDown::render_report_filter('training_got_curric', 'showGotCurric', @$this->translation['GOT Curriculum'], $this->gotcurric, 'training_got_curriculum_phrase', @$this->criteria['training_got_curric_id'], $this->criteria['showGotCurric']);
													} ?>

													<?php if ( $this->setting['display_training_got_comment'] && $this->mode != 'search') { ?>
													<div class="fieldLabel" id="got_comment_lbl"><?php echo (@$this->translation['GOT Comment']); ?></div>
													<div class="fieldInput"><div  class="leftBorderPad"><input type="checkbox" name="showGotComment"   <?php  if ($this->criteria['showGotComment']) echo 'checked="checked"';?> /></div><label for="showGotComment" ></label>
													<div class="leftBorder"></div></div>
														<?php } ?>
														<?php
if ( $this->setting['display_primary_language'] && $this->mode != 'search') {
echo DropDown::render_report_filter('training_primary_language_option', 'showPrimaryLanguage', @$this->translation['Primary Language'], $this->language, 
'language_phrase', @$this->criteria['training_primary_language_option_id'], $this->criteria['showPrimaryLanguage']);
														}

														if ( $this->setting['display_secondary_language'] && $this->mode != 'search') {
															echo DropDown::render_report_filter('training_secondary_language_option', 'showSecondaryLanguage', @$this->translation['Secondary Language'], $this->language, 'language_phrase', @$this->criteria['training_secondary_language_option_id'], $this->criteria['showSecondaryLanguage']);
														}

														if ( $this->setting['display_viewing_location'] && $this->mode != 'search') {
															echo DropDown::render_report_filter('person_to_training_viewing_loc_option', 'showViewingLoc', @$this->translation['Viewing Location'], $this->viewing_loc, 'location_phrase', @$this->criteria['person_to_training_viewing_loc_option_id'], $this->criteria['showViewingLoc']);
														}

														?>
														<?php if ( $this->setting['display_training_custom1'] ) { ?>
														<div class="fieldLabel" id="person_custom1_lbl"><?php print $this->translation['Training Custom 1']; ?></div>
														<div class="fieldInput"><div  class="leftBorderPad" ><input type="checkbox" name="showCustom1"   <?php  if ($this->criteria['showCustom1']) echo 'CHECKED';?> /></div><label for="showCustom1" ></label>

															<div  class="leftBorder"><select id="custom_1_id" name="custom_1_id" >
																<option value="">--<?php tp('All');?>--</option>
																<?php
																foreach ( $this->custom1 as $vals ) {
																	echo '<option value="'.$vals['id'].'" '.((@$this->criteria['custom_1_id']) == $vals['id']? 'SELECTED="selected"':'').' >'.($this->truncate($vals['custom1_phrase'],45)).'</option>';
																}
																?>
															</select></div></div>
															<?php } ?>
														<?php if ( $this->setting['display_training_custom2'] ) { ?>
														<div class="fieldLabel" id="training_custom2_lbl"><?php print $this->translation['Training Custom 2']; ?></div>
														<div class="fieldInput"><div  class="leftBorderPad" ><input type="checkbox" name="showCustom2"   <?php  if ($this->criteria['showCustom2']) echo 'CHECKED';?> /></div><label for="showCustom2" ></label>
															<div  class="leftBorder">
																<select id="custom_2_id" name="custom_2_id" >
																	<option value="">--<?php tp('All');?>--</option>
																	<?php
																	foreach ( $this->custom2 as $vals ) {
																		echo '<option value="'.$vals['id'].'" '.((@$this->criteria['custom_2_id']) == $vals['id']? 'SELECTED="selected"':'').' >'.($this->truncate($vals['custom2_phrase'],45)).'</option>';
																	} ?>
																</select>
															</div></div>
														<?php } ?>
														<?php if ( $this->setting['display_training_custom3'] ) { ?>
														<div class="fieldLabel" id="training_custom3_lbl"><?php print $this->translation['Training Custom 3']; ?></div>
														<div class="fieldInput"><div  class="leftBorderPad" ><input type="checkbox" name="showCustom3"   <?php  if ($this->criteria['showCustom3']) echo 'CHECKED';?> /></div><label for="showCustom3" ></label>
															<div  class="leftBorder">
																<select id="custom_3_id" name="custom_3_id" >
																	<option value="">--<?php tp('All');?>--</option>
																	<?php
																	foreach ( $this->custom3 as $vals ) {
																		if(!trim($vals['custom_3'])){ continue; }
																		echo '<option value="'.$vals['custom_3'].'" '.((@$this->criteria['custom_3_id']) == $vals['custom_3']? 'SELECTED="selected"':'').' >'.($this->truncate($vals['custom_3'],45)).'</option>';
																	} ?>
																</select>
															</div></div>
														<?php } ?>
														<?php if ( $this->setting['display_training_custom4'] ) { ?>
														<div class="fieldLabel" id="training_custom4_lbl"><?php print $this->translation['Training Custom 4']; ?></div>
														<div class="fieldInput"><div  class="leftBorderPad" ><input type="checkbox" name="showCustom4"   <?php  if ($this->criteria['showCustom4']) echo 'CHECKED';?> /></div><label for="showCustom4" ></label>
															<div  class="leftBorder">
																<select id="custom_4_id" name="custom_4_id" >
																	<option value="">--<?php tp('All');?>--</option>
																	<?php
																	foreach ( $this->custom4 as $vals ) {
																		if(!trim($vals['custom_4'])){ continue; }
																		echo '<option value="'.$vals['custom_4'].'" '.((@$this->criteria['custom_4_id']) == $vals['custom_4']? 'SELECTED="selected"':'').' >'.($this->truncate($vals['custom_4'],45)).'</option>';
																	} ?>
																</select>
															</div></div>
														<?php } ?>
														<?php if ($this->mode != 'search' ) { ?>
														<div class="fieldLabel" id="training_created_by_lbl"><?php tp('Created By'); ?></div>
														<div class="fieldInput"><div  class="leftBorderPad" ><input type="checkbox" name="showCreatedBy" <?php  if ($this->criteria['showCreatedBy']) echo 'CHECKED';?> /></div><label for="showCreatedBy" ></label>
															<div  class="leftBorder">
																<select id="created_by" name="created_by<?php if($this->expand_lists) echo '[]'; ?>"  <?php echo ($this->expand_lists?'multiple="multiple" size="10"':'class="fixed"'); ?> >
																	<option value="">--<?php tp('All');?>--</option>
																	<?php
																	foreach ( $this->createdBy as $vals ) {
																		if(!trim($vals['name'])){ continue; }
																		echo '<option value="'.$vals['id'].'" '.((@$this->criteria['created_by']) == $vals['id']? 'SELECTED="selected"':'').' >'.$vals['name'].'</option>';
																	} ?>
																</select>
															</div></div>
														<div class="fieldLabel" id="training_creation_dates_lbl"><?php tp('Date Added'); ?></div>
														<div class="fieldInput"><div  class="leftBorderPad" ><input type="checkbox" name="showCreationDate"   <?php  if ($this->criteria['showCreationDate']) echo 'CHECKED';?> /></div><label for="showCreationDate" ></label>
															<div  class="leftBorder">
																<span><input type="text" id="creation_dates1" name="creation_dates[]" class="trainingReportCreationDate datepicker" value="<?php echo (isset($this->criteria['creation_dates']) && is_array($this->criteria['creation_dates'])) ? $this->criteria['creation_dates'][0] : '' ?>"><a class="calendarbtn" href="#"><img src="<?php echo $this->base_url; ?>/js/yui/assets/calbtn.gif"></a></span>&nbsp;&nbsp;<label class="label"><?php tp('to'); ?></label>&nbsp;&nbsp;
																<span><input type="text" id="creation_dates2" name="creation_dates[]" class="trainingReportCreationDate datepicker" value="<?php echo (isset($this->criteria['creation_dates']) && is_array($this->criteria['creation_dates'])) ? @$this->criteria['creation_dates'][1] : '' ?>"><a class="calendarbtn" href="#"><img src="<?php echo $this->base_url; ?>/js/yui/assets/calbtn.gif"></a></span>
															</div>
															<input type="hidden" name="date_localtime" id="date_localtime">
															<script type="text/javascript">
																$('#trainingreport').submit(function (e) {
																	d = new Date();
																	$('#date_localtime').val(d.toLocaleDateString() + ' ' + d.toLocaleTimeString());
																});
															</script>
														</div>
														<?php } ?>
							<?php if ( $this->setting['display_end_date'] && $this->mode != 'search' && $this->mode != 'count') { ?>
															<div class="fieldLabel" id="show_end_lbl"><?php tp('End date'); ?></div>
															<div class="fieldInput">
															<div  class="leftBorderPad"><input type="checkbox" name="showEndDate"   
															<?php  if ($this->criteria['showEndDate']) echo 'checked="checked"';?> />
															</div>
															<label for="showEndDate" ></label>

																<div  class="leftBorder">
																</div>
															</div>
																<?php } ?>
															<?php if($this->mode == 'count' || $this->mode == 'name') { ?>
															<div class="fieldLabel" id="training_gender_lbl"><?php tp('Gender');?></div>
															<div class="fieldInput">
															<div  class="leftBorderPad"><input type="checkbox" name="showGender" <?php  if ($this->criteria['showGender']) echo 'CHECKED';?> /></div>
														  	<div  class="leftBorder">
															<select id="training_gender" name="training_gender" >
																<option value="">--<?php tp('All');?>--</option>
																<option value="male" <?php echo (@$this->criteria['training_gender'] == 'male'? 'SELECTED':''); ?> ><?php tp('male');?></option>
																<option value="female"  <?php echo (@$this->criteria['training_gender'] == 'female'? 'SELECTED':''); ?> ><?php tp('female');?></option>
																<option value="na"  <?php echo (@$this->criteria['training_gender'] == 'na'? 'SELECTED':''); ?> ><?php tp('na');?></option>
															</select></div></div>
															<?php if ( $this->setting['display_people_age'] ) { ?>
															<div class="fieldLabel" id="training_age_lbl"><?php tp('Age');?></div>
															<div class="fieldInput">
															<div  class="leftBorderPad"><input type="checkbox" name="showAge" <?php  if ($this->criteria['showAge']) echo 'CHECKED';?> /></div>
															<div  class="leftBorder">
															<?php tp('min');?> <input type="text" id="age_min" name="age_min" size="4" value="<?php echo ( $this->criteria['age_min'] ? $this->criteria['age_min'] : '0');?>" /> <?php tp('max');?> <input type="text"  size="4" name="age_max" id="age_max" value="<?php echo ( $this->criteria['age_max'] ? $this->criteria['age_max'] : '');?>" /> <a href="#" id="clear_age" onclick="return clearAge();" ><?php tp('clear');?></a>
															</div></div>
															<?php } ?>
																<div class="fieldLabel" id="district_id_lbl"><?php tp('Qualification'); ?> (<?php tp('primary');?>)</div><div class="fieldInput">
																<div  class="leftBorderPad"><input type="checkbox" name="showQualPrim" <?php  if ($this->criteria['showQualPrim']) echo 'CHECKED';?> /></div>
														  		<div  class="leftBorder"><select id="qualification_id" name="qualification_id">
																	<option value="">--<?php tp('All');?>--</option>
																	<?php
																		foreach ( $this->qualifications_primary as $vals ) {
																			echo '<option value="'.$vals['id'].'" '.((@$this->criteria['qualification_id']) == $vals['id'] ? 'SELECTED':'').' >'.$vals['qualification_phrase'].'</option>';
																	}
																	?>
																</select></div></div>
															<div class="fieldLabel" id="district_id_lbl"><?php tp('Qualification'); ?> (<?php tp('secondary');?>)</div><div class="fieldInput">
															<div  class="leftBorderPad"><input type="checkbox" name="showQualSecond" <?php  if ($this->criteria['showQualSecond']) echo 'CHECKED';?> /></div>
														  	<div  class="leftBorder"><select id="qualification_secondary_id" name="qualification_secondary_id">
																<option value="">--<?php tp('All');?>--</option>
																<?php
																	foreach ( $this->qualifications_secondary as $vals ) {
																		echo '<option value="'.$vals['id'].'" '.((@$this->criteria['qualification_secondary_id']) == $vals['id'] ? 'SELECTED':'').' >'.$vals['qualification_phrase'].'</option>';
																}
																?>
															</select></div></div>
															<?php } ?>

															</div>
												
			
															<!-- TA:17: 9/3/2014  START -->
															<?php if($this->setting['display_training_start_date']){?>
															<div class="clear"></div><br/><br/>
															<div class="fieldLabel"><?php tp('Start date');?></div>
															<div class="fieldInput" id="startdate">
																<?php tp('Day');?> <input id="start-day" class="dayfield" type="text" name="start-day" maxlength="2" value="<?php echo $this->criteria['start-day']; ?>"  />
																/ <?php tp('Month');?> <input id="start-month" class="monthfield" type="text" name="start-month" maxlength="2" value="<?php echo $this->criteria['start-month']; ?>"  />
																/ <?php tp('Year');?> <input id="start-year" class="yearfield" type="text" name="start-year" maxlength="4" value="<?php echo $this->criteria['start-year'];  ?>" />
																<script  type="text/javascript">
																	YAHOO.util.Event.onDOMReady(function () {
																		makeCalendar("startdate","start-day", "start-month", "start-year");
																	});
																</script>
															</div>
															<?php }?>
															<!-- TA:17: 9/3/2014  END -->
															
															<!-- TA:17: 09/09/2014 fixed bug to on/off end date -->
			
															<?php if ( $this->setting['display_end_date']){?>
															<div class="fieldLabel" style="padding-top:1em;"><?php tp('End date');?></div>
															<div class="fieldInput" id="enddate" style="margin-top:1em;">
																<?php tp('Day');?> <input id="end-day" class="dayfield" type="text" name="end-day" maxlength="2" value="<?php echo $this->criteria['end-day']; ?>"  />
																/ <?php tp('Month');?> <input id="end-month" class="monthfield" type="text" name="end-month" maxlength="2" value="<?php echo $this->criteria['end-month']; ?>"  />
																/ <?php tp('Year');?> <input id="end-year" class="yearfield" type="text" name="end-year" maxlength="4" value="<?php echo $this->criteria['end-year'];  ?>" />
																<script  type="text/javascript">
																	YAHOO.util.Event.onDOMReady(function () {
																		makeAdditionalCalendar("enddate","end-day", "end-month", "end-year");
																	});
																</script>
															</div>
															<?php }?>
															<!-- TA:17: 09/12/2014 -->
															<?php if ( $this->mode == 'search' && $this->setting['module_unknown_participants_enabled']) {?>
															<div class="clear"></div>
															<br/>
															<div class="fieldLabel"></div><div class="fieldInput" ><input type="radio" id="has_known_participants" value="has_known_participants" name="training_participants_type" <?php if ( $this->criteria['training_participants_type'] == 'has_known_participants') echo 'CHECKED'; ?> />&nbsp;<label for="has_known_participants"><?php tp('Trainings with known participants only');?></label></div>
															<div class="fieldLabel"></div><div class="fieldInput" ><input type="radio" id="has_unknown_participants" value="has_unknown_participants" name="training_participants_type" <?php if ( $this->criteria['training_participants_type'] == 'has_unknown_participants' ) echo 'CHECKED'; ?> />&nbsp;<label for="has_unknown_participants"><?php tp('Trainings with unknown participants only');?></label></div>
															<div class="fieldLabel"></div><div class="fieldInput" ><input type="radio" id="has_known_participants2" value="has_everyone" name="training_participants_type" <?php if ( $this->criteria['training_participants_type'] == 'has_everyone' ) echo 'CHECKED'; ?> />&nbsp;<label for="has_known_participants2"><?php tp('All trainings');?></label></div>
															<?php }?>
															<div class="clear"></div>
															<input type="hidden" name="limit" id="limit" value="1" />
															<input type="submit" class="submitNoArrow" name="go" value="<?php tp('Preview');?>" />
														</fieldset>
													</form>
													<?php if ( $this->criteria['go'] ) { ?>
													<div class="hrGrey"></div>
													<div class="fieldIndentNoMargin"><?php tp('Trainings');?> <span class="total"><?php echo $this->count;?> <?php if ( $this->mode == 'count' ) echo t('Participants'); else echo '';?></span><?php echo $this->printAndExport();?><span class="datadownload" style="float:right;"><?php if(count($this->results)) { ?><a href="<?php echo $this->base_url; ?>/data/trainings/outputType/csv/<?php echo implode_ids($this->results); ?>"><?php tp('Download Complete Excel Data for these trainings'); ?></a><?php } ?></span></div>
														<?php if ($this->mode == 'search' ) { ?>
														<a href="<?php echo $this->base_url;?>/training/add"><?php echo t('Add').' '.t('New').' '.t('Training');?></a><br/><br/>
														<?php } ?>
														<div id="trainings" class="itechTable"></div>
														<script type="text/javascript">
															var formatViewUrl = function(elCell, oRecord, oColumn, sData) {
																elCell.innerHTML = "<a href='<?php echo $this->base_url;?>/training/view/id/" + oRecord.getData("id") + "'>" + sData + "</a>";
															};

															var trainingData = [
															<?php $isFirstRow = true;
															$cnt = 0;
															foreach($this->results as $row) {
																if ( (!$_REQUEST['limit'])  or ($cnt < 100) ) {
																	if (!$isFirstRow )
																	echo ',';
																	$isFirstRow = false;
																	echo '[';
																	if (array_key_exists('cnt', $row) !== false )
																	echo ( $row['cnt'] ? $row['cnt'] : 0 ) ;
																	if (isset($row['id'] ) )
																	echo ((array_key_exists('cnt', $row) !== false )? ','.$row['id']: $row['id']);
																	if ( isset($row['id']) && $this->setting['display_training_start_date']) //TA:17: 09/09/2014
																	echo ',"'.@$row['training_start_date'].'"';
																	if ( $this->criteria['showEndDate'] )
																	echo ',"'.$row['training_end_date'].'"';
																	if ( $this->criteria['showProvince'] )
																	echo ',"'.$row['province_name'].'"';
																	if ( $this->criteria['showDistrict'] )
																	echo ',"'.$row['district_name'].'"';
																	if ( $this->criteria['showRegionC'] )
																	echo ',"'.$row['region_c_name'].'"';
																	if ( $this->criteria['showRegionD'] )
																	echo ',"'.$row['region_d_name'].'"';
																	if ( $this->criteria['showRegionE'] )
																	echo ',"'.$row['region_e_name'].'"';
																	if ( $this->criteria['showRegionF'] )
																	echo ',"'.$row['region_f_name'].'"';
																	if ( $this->criteria['showRegionG'] )
																	echo ',"'.$row['region_g_name'].'"';
																	if ( $this->criteria['showRegionH'] )
																	echo ',"'.$row['region_h_name'].'"';
																	if ( $this->criteria['showRegionI'] )
																	echo ',"'.$row['region_i_name'].'"';
																	if ( $this->criteria['showCategory'])
																	echo ',"'.$row['training_category_phrase'].'"';
																	if ( $this->criteria['showTrainingTitle'])
																	echo ',"'.$row['training_title'].'"';
																	if ( $this->criteria['showLocation'] )
																	echo ',"'.$row['training_location_name'].'"';
																	if ( $this->criteria['showOrganizer'] )
																	echo ',"'.$row['training_organizer_phrase'].'"';
																	if ( $this->criteria['showMechanism'] )
																	echo ',"'.$row['mechanism_id'].'"';
																	if ( $this->criteria['showLevel'] )
																	echo ',"'.$row['training_level_phrase'].'"';
																	if ( $this->criteria['showTopic'] )
																	echo ',"'.$row['training_topic_phrase'].'"';
																	if ( $this->criteria['showPepfar'] )
																	echo ',"'.$row['pepfar_category_phrase'].'"';
																	if ( $this->criteria['showMethod'] )
																	echo ',"'.$row['training_method_phrase'].'"';
																	if ( $this->criteria['showFunding'] )
																	echo ',"'.$row['funding_phrase'].'"';
																	if ( $this->criteria['showTot'] )
																	echo ',"'.$row['is_tot'].'"';
																	if ( $this->criteria['showRefresher'] )
																	echo ',"'.$row['is_refresher'].'"';
																	if ( $this->criteria['showGotComment'] )
																	echo ',"'.$row['got_comments'].'"';
																	if ( $this->criteria['showPrimaryLanguage'] )
																	echo ',"'.$row['primary_language_phrase'].'"';
																	if ( $this->criteria['showSecondaryLanguage'] )
																	echo ',"'.$row['secondary_language_phrase'].'"';
																	if ( $this->criteria['showGotCurric'] )
																	echo ',"'.$row['training_got_curriculum_phrase'].'"';
																	if ( $this->criteria['showCustom1'] )
																	echo ',"'.$row['custom1_phrase'].'"';
																	if ( $this->criteria['showCustom2'] )
																	echo ',"'.$row['custom2_phrase'].'"';
																	if ( $this->criteria['showCustom3'] )
																	echo ',"'.$row['custom_3'].'"';
																	if ( $this->criteria['showCustom4'] )
																	echo ',"'.$row['custom_4'].'"';
																	if (array_key_exists('pcnt', $row) !== false )
																	echo ','.( ($row['has_known_participants']? ($row['pcnt'] ? $row['pcnt'] :0):'"-"') );
																	if ( $this->criteria['showCreatedBy'] )
																	echo ',"'.$row['created_by_user'].'"';
																	if ( $this->criteria['showCreationDate'] )
																	echo ',"'.$row['created_date'].'"';
																	if ( $this->criteria ['showAge'] )
																	echo ','.($row['age'] ? $row['age'] : '"-"');
																	if ( $this->criteria ['showGender'] )
																	echo ',"'.$row['gender'].'"';
																	if ( $this->criteria ['showViewingLoc'] )
																	echo ',"'.($row['location_phrases'] ? $row['location_phrases'] : '-').'"';
																	if ( $this->criteria ['showQualPrim'] )
																	echo ',"'.$row['qualification_phrase'].'"';
																	if ( $this->criteria ['showQualSecond'] )
																	echo ',"'.$row['qualification_secondary_phrase'].'"';
																	echo "]";
																	$cnt++;
																}}
																?>];

																var trainingColumnDefs = [
																<?php if (isset($this->results[0]['cnt'])) { ?>
																	{key:"cnt", label: "<?php tp('Count');?>", sortable:true, resizeable:true}
																<?php } ?>
																//TA:17: 9/3/2014
																<?php if (isset($this->results[0]['id'])) { ?> 
																	<?php  if (isset($this->results[0]['cnt'])) echo ',';?>		
																	{key:"id", label: "<?php tp('ID')?>", sortable:true, resizeable:true, formatter: formatViewUrl}
																	<?php if($this->setting['display_training_start_date'] == 1){?> //TA:17; 9/3/2014
																	,{key:"training_start_date", label: "<?php tp('Start Date');?>", sortable:true, resizeable:true}
																	<?php }?>
																<?php } ?>
																<?php if ( $this->criteria['showEndDate'] ) { ?>
																	,{key:"training_end_date", label: "<?php tp('End Date');?>", sortable:true, resizeable:true}
																<?php } ?>
																<?php if ( $this->criteria['showProvince'] ) { ?>
																	,{key:"province_name", label: "<?php echo (@$this->translation['Region A (Province)']); ?>", sortable:true, resizeable:true}
																<?php } ?>
																<?php if ( $this->criteria['showDistrict'] ) { ?>
																	,{key:"district_name", label: "<?php echo (@$this->translation['Region B (Health District)']); ?>", sortable:true, resizeable:true}
																<?php } ?>
																<?php if ( $this->criteria['showRegionC'] ) { ?>
																	,{key:"region_c_name", label: "<?php echo (@$this->translation['Region C (Local Region)']); ?>", sortable:true, resizeable:true}
																<?php } ?>
																<?php if ( $this->criteria['showRegionD'] ) { ?>
																	,{key:"region_d_name", label: "<?php echo t('Region D'); ?>", sortable:true, resizeable:true}
																<?php } ?>
																<?php if ( $this->criteria['showRegionE'] ) { ?>
																	,{key:"region_e_name", label: "<?php echo t('Region E'); ?>", sortable:true, resizeable:true}
																<?php } ?>
																<?php if ( $this->criteria['showRegionF'] ) { ?>
																	,{key:"region_f_name", label: "<?php echo t('Region F'); ?>", sortable:true, resizeable:true}
																<?php } ?>
																<?php if ( $this->criteria['showRegionG'] ) { ?>
																	,{key:"region_g_name", label: "<?php echo t('Region G'); ?>", sortable:true, resizeable:true}
																<?php } ?>
																<?php if ( $this->criteria['showRegionH'] ) { ?>
																	,{key:"region_h_name", label: "<?php echo t('Region H'); ?>", sortable:true, resizeable:true}
																<?php } ?>
																<?php if ( $this->criteria['showRegionI'] ) { ?>
																	,{key:"region_i_name", label: "<?php echo t('Region I'); ?>", sortable:true, resizeable:true}
																<?php } ?>
																<?php if ( $this->criteria['showCategory']) { ?>
																	,{key:"training_category_phrase", label: "<?php echo (@$this->translation['Training Category']); ?>", sortable:true, resizeable:true}
																<?php } ?>
																<?php if ( $this->criteria['showTrainingTitle']) { ?>
																	,{key:"training_title", label: "<?php echo (@$this->translation['Training Name']); ?>", sortable:true, resizeable:true}
																<?php } ?>
																<?php if ( $this->criteria['showLocation'] ) { ?>
																	,{key:"training_location_name", label: "<?php tp('Location');?>", sortable:true, resizeable:true}
																<?php } ?>
																<?php if ( $this->criteria['showOrganizer'] ) { ?>
																	,{key:"training_organizer_phrase", label: "<?php echo (@$this->translation['Training Organizer']); ?>", sortable:true, resizeable:true}
																<?php } ?>
																<?php if ( $this->criteria['showMechanism'] ) { ?>
																	,{key:"mechanism_id", label: "<?php tp('Mechanism ID'); ?>", sortable:true, resizeable:true}
																<?php } ?>
																<?php if ( $this->criteria['showLevel'] ) { ?>
																	,{key:"training_level_phrase", label: "<?php echo (@$this->translation['Training Level']); ?>", sortable:true, resizeable:true}
																<?php } ?>
																<?php if ( $this->criteria['showTopic'] ) { ?>
																	,{key:"training_topic_phrase", label: "<?php echo @$this->translation['Training Topic'];?>", sortable:true, resizeable:true}
																<?php } ?>
																<?php if ( $this->criteria['showPepfar'] ) { ?>
																	,{key:"pepfar_category_phrase", label: "<?php  echo @$this->translation['PEPFAR Category'];?>", sortable:true, resizeable:true}
																<?php } ?>
																<?php if ( $this->criteria['showMethod'] ) { ?>
																	,{key:"training_method_phrase", label: "<?php  echo @$this->translation['Training Method'];?>", sortable:true, resizeable:true}
																<?php } ?>
																<?php if ( $this->criteria['showFunding'] ) { ?>
																	,{key:"funding_phrase", label: "<?php tp('Funding');?>", sortable:true, resizeable:true}
																<?php } ?>
																<?php if ( $this->criteria['showTot'] ) { ?>
																	,{key:"is_tot", label: "<?php echo tp('TOT'); ?>", sortable:true, resizeable:true}
																<?php } ?>
																<?php if ( $this->criteria['showRefresher'] ) { ?>
																	,{key:"is_refresher", label: "<?php echo tp('Refresher'); ?>", sortable:true, resizeable:true}
																<?php } ?>
																<?php if ( $this->criteria['showGotComment'] ) { ?>
																	,{key:"got_comments", label: "<?php echo @$this->translation['GOT Comment']; ?>", sortable:true, resizeable:true}
																<?php } ?>
																<?php if ( $this->criteria['showPrimaryLanguage'] ) { ?>
																	,{key:"primary_language_phrase", label: "<?php echo @$this->translation['Primary Language']; ?>", sortable:true, resizeable:true}
																<?php } ?>
																<?php if ( $this->criteria['showSecondaryLanguage'] ) { ?>
																	,{key:"secondary_language_phrase", label: "<?php echo @$this->translation['Secondary Languages']; ?>", sortable:true, resizeable:true}
																<?php } ?>
																<?php if ( $this->criteria['showGotCurric'] ) { ?>
																	,{key:"training_got_curriculum_phrase", label: "<?php echo @$this->translation['GOT Curriculum']; ?>", sortable:true, resizeable:true}
																<?php } ?>
																<?php   if ( $this->criteria['showCustom1'] ) { ?>
																	,{key:"custom1_phrase", label: "<?php echo (@$this->translation['Training Custom 1']); ?>", sortable:true, resizeable:true}
																<?php } ?>
																<?php   if ( $this->criteria['showCustom2'] ) { ?>
																	,{key:"custom2_phrase", label: "<?php echo (@$this->translation['Training Custom 2']); ?>", sortable:true, resizeable:true}
																<?php } ?>
																<?php   if ( $this->criteria['showCustom3'] ) { ?>
																	,{key:"custom3_phrase", label: "<?php echo (@$this->translation['Training Custom 3']); ?>", sortable:true, resizeable:true}
																<?php } ?>
																<?php   if ( $this->criteria['showCustom4'] ) { ?>
																	,{key:"custom4_phrase", label: "<?php echo (@$this->translation['Training Custom 4']); ?>", sortable:true, resizeable:true}
																<?php } ?>
																//TA:17: 09/09/2014  
																<?php if ($this->results[0] && array_key_exists('pcnt', $this->results[0]) !== false && $this->setting['display_training_pepfar']) { ?>
																	,{key:"pcnt", label: "<?php tp('Participants');?>", sortable:true, resizeable:true}
																<?php } ?>
																<?php   if ( $this->criteria['showCreatedBy'] ) { ?>
																	,{key:"created_by", label: "<?php tp('Created By'); ?>", sortable:true, resizeable:true}
																<?php } ?>
																<?php   if ( $this->criteria['showCreationDate'] ) { ?>
																	,{key:"created_date", label: "<?php tp('Created'); ?>", sortable:true, resizeable:true}
																<?php } ?>
																<?php   if ( $this->criteria['showAge'] ) { ?>
																	,{key:"age", label: "<?php tp('Age'); ?>", sortable:true, resizeable:true}
																<?php } ?>
																<?php   if ( $this->criteria['showGender'] ) { ?>
																	,{key:"gender", label: "<?php tp('Gender'); ?>", sortable:true, resizeable:true}
																<?php } ?>
																<?php   if ( $this->criteria['showViewingLoc'] ) { ?>
																	,{key:"viewingloc", label: "<?php tp('Viewing Location'); ?>", sortable:true, resizeable:true}
																<?php } ?>
																<?php   if (($this->criteria['doCount'] || $this->criteria['doName']) &&  $this->criteria['showQualPrim'] ) { ?>
																	,{key:"qualification_phrase", label: "<?php echo t('Qualification').space.t('primary'); ?>", sortable:true, resizeable:true}
																<?php } ?>
																<?php   if (($this->criteria['doCount'] || $this->criteria['doName']) &&  $this->criteria['showQualSecond'] ) { ?>
																	,{key:"qualification_secondary_phrase", label: "<?php echo t('Qualification').space.t('secondary');?>", sortable:true, resizeable:true}
																<?php } ?>
																];


																<?php if  ( $this->results ) { ?>
																	makeDataTable("trainings", null, trainingData, trainingColumnDefs);
																<?php } ?>
															</script>
															<?php if ($cnt < count($this->results)) { ?>
															<div  class="fieldIndentNoMargin">[<?php tp('Limited to 100 rows');?>]  <a href="<?php echo str_replace('limit=1','limit=0',$_SERVER['REQUEST_URI']);?>"><?php tp('Full Results');?></a></div>
															<?php } ?>
															<?php } ?>
														</div>
<script type="text/javascript">
$(document).ready( function	() {
	$('.trainingReportCreationDate').datepicker({dateFormat: 'mm/dd/yy'});
	$('.calendarbtn').click(openNearestDatePicker);
});
</script>

														<div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>


													</div>

												</body>
											</html>
