<html>
	<head>
		<title><?php echo $this->escape($this->title);?></title>
		<link href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet" type="text/css">

	<?php
	require_once('views/helpers/Location.php');
	require_once('views/helpers/ScriptContainer.php');
	print ScriptContainer::$instance->renderCSSHead();
	print ScriptContainer::$instance->renderJSHead();	?>

		<script type="text/javascript" charset="utf-8">
			$(document).ready(function() {
				/* Funding - set checkbox if not empty*/
				$("input[name^=fundingamount]").keyup(function (e) {
					var id = $(this).attr('id');
					$('input[name="' + id + '"]').attr('checked', ( ( $(this).val() == "") ? null : 'checked'));
				});
				$( ".calendarbox" ).datepicker({
					changeMonth: true,
					changeYear: true,
					yearRange:"-100:+0"
				});
				/* Add a click handler to the rows - this could be used as a callback */
				$(".tablegrid tbody").click(function(event) {
					$(oTable.fnSettings().aoData).each(function (){
						$(this.nTr).removeClass('row_selected');
					});
					$(event.target.parentNode).addClass('row_selected');
				});

				/* Add a click handler for the delete row */
				$('#delete').click( function() {
					var anSelected = fnGetSelected( oTable );
					oTable.fnDeleteRow( anSelected[0] );
				} );

				/* Init the table */
				oTable = $('.tablegrid').dataTable({
					"bJQueryUI": true,
					"sPaginationType": "full_numbers"
				});

				$( "#dialog-form-license" ).dialog({
					autoOpen: false,
					height: 460,
					width: 750,
					modal: true,
					buttons: {
						"Update": function() {
							document.getElementById('licenseform').submit();
						},
						Cancel: function() {
							$( this ).dialog( "close" );
						}
					},
					close: function() {
						//allFields.val( "" ).removeClass( "ui-state-error" );
					}
				});

				$( "#licensepopupbutton" )
					.button()
					.click(function() {
						$( "#dialog-form-license" ).dialog( "open" );
				});

				$( "#dialog-form-class" ).dialog({
					autoOpen: false,
					height: 460,
					width: 750,
					modal: true,
					buttons: {
						"Update": function() {
							document.getElementById('classform').submit();
						},
						Cancel: function() {
							$( this ).dialog( "close" );
						}
					},
					close: function() {
						//allFields.val( "" ).removeClass( "ui-state-error" );
					}
				});

				$( "#classpopupbutton" )
					.button()
					.click(function() {
						$( "#dialog-form-class" ).dialog( "open" );
				});

				$( "#dialog-form-practicum" ).dialog({
					autoOpen: false,
					height: 460,
					width: 750,
					modal: true,
					buttons: {
						"Update": function() {
							document.getElementById('practicumform').submit();
						},
						Cancel: function() {
							$( this ).dialog( "close" );
						}
					},
					close: function() {
						//allFields.val( "" ).removeClass( "ui-state-error" );
					}
				});

				$( "#practicumpopupbutton" )
					.button()
					.click(function() {
						$( "#dialog-form-practicum" ).dialog( "open" );
				});



			});

			/* Get the rows which are currently selected */
			function fnGetSelected( oTableLocal ){
				var aReturn = new Array();
				var aTrs = oTableLocal.fnGetNodes();

				for ( var i=0 ; i<aTrs.length ; i++ ){
					if ( $(aTrs[i]).hasClass('row_selected') ){
						aReturn.push( aTrs[i] );
					}
				}
				return aReturn;
			}

			function checkcohort(){
				if ($("#cohortid").val() == 0){
					$("#studentid").attr('disabled','disabled');
					$("#studentid").val('');
					$("#studenttype").attr('disabled','disabled');
					$("#studenttype").val(0);
				} else {
					$("#studentid").removeAttr('disabled');
					$("#studenttype").removeAttr('disabled');
				}
			}
		</script>
	</head>
	<body>

<!--
######################################
#                                    #
#  POPUP DIALOG FOR LICENSE DETAILS  #
#                                    #
######################################
-->


<div id="dialog-form-license" title="Update exams">
	<form method="post" name="licenseform" id="licenseform">
		<input type="hidden" name="licenseaction" id="licenseaction" value="license">
		<input type="hidden" name="licenseid" id="licenseid" value="<?php echo $this->id; ?>">
		<input type="hidden" name="cohortid" id="cohortid" value="<?php echo $this->cohortid ?>">
		<table cellpadding="0" cellspacing="0" border="0" class="display tablegrid" id="" style="width:100%">
			<thead>
				<tr>
					<th><?php echo t('License name'); ?></th>
					<th><?php echo t('Date'); ?></th>
					<th><?php echo t('Grade'); ?></th>
				</tr>
			</thead>
			<tbody>
<?php
	foreach ($this->currentlicenses as $classes){
?>
				<tr class="GradeA">
					<td><?php echo $classes['licensename']; ?></td>
					<td class="" style="width : 120px;"><?php echo date("m/d/Y", strtotime($classes['licensedate'])); ?></td>
					<td class="" style="width : 120px;"><input type="text" name="grade[<?php echo $classes['id'] ?>]" id="grade[<?php echo $classes['id'] ?>]" value="<?php echo trim(strtolower($classes['grade'])) != "n/a" ? $classes['grade'] : ""; ?>" style="width : 100%;"></td>
				</tr>
<?php
	}
?>
			</tbody>
		</table>
	</form>
</div>

<!--
####################################
#                                  #
#  POPUP DIALOG FOR CLASS DETAILS  #
#                                  #
####################################
-->


<div id="dialog-form-class" title="Update classes">
	<form method="post" name="classform" id="classform">
		<input type="hidden" name="classaction" id="classaction" value="classaction">
		<input type="hidden" name="classid" id="classid" value="<?php echo $this->id; ?>">
		<input type="hidden" name="cohortid" id="cohortid" value="<?php echo $this->cohortid ?>">
		<table cellpadding="0" cellspacing="0" border="0" class="display tablegrid" id="" style="width:100%">
			<thead>
				<tr>
					<th><?php echo t('Class name'); ?></th>
					<th><?php echo t('Instructor'); ?></th>
					<th><?php echo t('Start date'); ?></th>
					<th><?php echo t('End date'); ?></th>
					<th><?php echo t('Grade'); ?></th>
				</tr>
			</thead>
			<tbody>
<?php
	foreach ($this->currentclasses as $classes){
?>
				<tr class="GradeA">
					<td><?php echo $classes['classname']; ?></td>
					<td class="" style="width : 200px;"><?php echo $classes['first_name'] . " " . $classes['last_name']; ?></td>
					<td class="" style="width : 120px;"><?php echo date("m/d/Y", strtotime($classes['startdate'])); ?></td>
					<td class="" style="width : 120px;"><?php echo date("m/d/Y", strtotime($classes['enddate'])); ?></td>
					<td class="" style="width : 120px;"><input type="text" name="grade[<?php echo $classes['id'] ?>]" id="grade[<?php echo $classes['id'] ?>]" value="<?php echo trim(strtolower($classes['grade'])) != "n/a" ? $classes['grade'] : ""; ?>" style="width : 100%;"></td>
				</tr>
<?php
	}
?>
			</tbody>
		</table>
	</form>
</div>

<!--
########################################
#                                      #
#  POPUP DIALOG FOR practicum DETAILS  #
#                                      #
########################################
-->

<div id="dialog-form-practicum" title="Update clinical allocation">
	<form method="post" name="practicumform" id="practicumform">
		<input type="hidden" name="practicumaction" id="practicumaction" value="practicumaction">
		<input type="hidden" name="practicumid" id="practicumid" value="0">
		<input type="hidden" name="cohortid" id="cohortid" value="<?php echo $this->cohortid ?>">
		<table cellpadding="0" cellspacing="0" border="0" class="display tablegrid" id="" style="width:100%">
			<thead>
				<tr>
					<th><?php echo t('Practicum name'); ?></th>
					<th><?php echo t('Practicum date'); ?></th>
					<th><?php echo t('Hours required'); ?></th>
					<th><?php echo t('Hours completed'); ?></th>
					<th><?php echo t('Grade'); ?></th>
				</tr>
			</thead>
			<tbody>
<?php
	foreach ($this->allpracticum as $classes){
?>
				<tr class="GradeA">
					<td><?php echo $classes['practicumname']; ?></td>
					<td class="" style="width : 120px;"><?php echo date("m/d/Y", strtotime($classes['practicumdate'])); ?></td>
					<td class="" style="width : 120px;"><?php echo $classes['hoursrequired']; ?></td>
					<td class="" style="width : 150px;"><input type="text" name="practicum[<?php echo $classes['id'] ?>][completed]" id="practicum[<?php echo $classes['id'] ?>][completed]" value="<?php echo is_numeric($classes['hourscompleted']) ? $classes['hourscompleted'] : "0"; ?>" style="width : 100%;"></td>
					<td class="" style="width : 120px;"><input type="text" name="practicum[<?php echo $classes['id'] ?>][grade]" id="practicum[<?php echo $classes['id'] ?>][grade]" value="<?php echo trim(strtolower($classes['grade'])) != "n/a" ? $classes['grade'] : ""; ?>" style="width : 100%;"></td>
				</tr>
<?php
	}
?>
			</tbody>
		</table>
	</form>
</div>



		<div id="pageHolder">
			<div id="header"><?php require_once('views/scripts/preheader.phtml');?></div>
			<div id="content">
				<?php require_once 'views/scripts/status.phtml'; ?>

				<div id="subcontent">

						<div class="historyDiv">

						<a href="<?php echo Settings::$COUNTRY_BASE_URL; ?>/studentedit/transcript/id/<?php echo $this->escape($this->id); ?>" target="_blank" >Student Transcript Report</a> <br/>

							<a href="#" onclick="doDelete(); return false;"><?php tp('Delete this Person');?></a>
							<script language="JavaScript">
								function doDelete() {
									if(confirm("<?php tp('Are you sure you wish to delete this person?');?>")) {
										window.location = '<?php echo $this->base_url;?>/person/delete/id/<?php echo $this->id;?>';
										return false;
									}
								}
							</script>

						</div>

					<div id="contentheader">
						<h2><?php echo t('Edit Student Record'); ?></h2><br>
					</div>
					<div class="pad50 clear"></div>
					<form  action="#" id="peopleadd" method="post">
						<input type="hidden" name="id" value="<?php echo $this->escape($this->id); ?>">
						<div class="mainformholder" style="height:100%;">
							<label><?php echo t('Graduated?'); ?></label>
							<select name="graduated">
								<option value="0"<?php echo ($this->escape($this->graduated) == 0 ? " selected" : "") ?>>No</option>
								<option value="1"<?php echo ($this->escape($this->graduated) == 1 ? " selected" : "") ?>>Yes</option>
							</select>

							<label><?php echo t('Cohort') ?></label>
							<input type="hidden" name="cohortid" value="<?php echo $this->cohortid; ?>" />
							<select name="cohortid" id="cohortid" onchange="checkcohort()" <?php if (!empty($this->cohortid)) echo 'disabled' ?>>
								<option value="0"><?php echo t('Select...'); ?></option>
<?php
	foreach ($this->getcohorts as $cohort){
		if (trim($cohort[cohortname]) != ""){
?>
								<option value="<?php echo $cohort[id]; ?>"<?php echo ($this->escape($this->cohortid) == $cohort[id] ? " selected" : "") ?>><?php echo $cohort[cohortname] . (trim($cohort[cohortid]) != "" ? " [" . trim($cohort[cohortid]) . "]" : ""); ?></option>
<?php
		}
	}
?>
							</select>

							<div class="clear pad20"></div>
							<p style=""><?php echo t('Personal Information'); ?></p><br>
							<div class="clear pad20"></div>

		 					<label><?php echo t('Title'); ?></label>
							<select name="title" >
								<option value="0"><?php echo t('Select...'); ?></option>
							<?php foreach ($this->gettitle as $fetchtitle){ ?>
								<option value="<?php echo $fetchtitle[id]; ?>"<?php echo ($this->escape($this->selid) == $fetchtitle[id] ? " selected" : "") ?>><?php echo $fetchtitle[title_phrase]; ?></option>
							<?php } ?>
							</select>

							<label><?php echo t('First name'); ?></label>
							<input type="text" name="firstname" value="<?php echo $this->escape($this->firstname);?>">

							<label><?php echo t('Middle name'); ?></label>
							 <input type="text" name="middlename" value="<?php echo $this->escape($this->middlename);?>">

							<label><?php echo t('Last name'); ?></label>
							<input type="text" name="lastname" value="<?php echo $this->escape($this->lastname);?>">

							<label><?php echo t('School ID'); ?></label>
							<input type="text" name="nationalid" value="<?php echo $this->escape($this->nationalid);?>">

							<label><?php echo t('Nationality'); ?></label>
							<select name="nationality">
								<option value="0"><?php echo t('Select...'); ?></option>
<?php
	foreach ($this->lookupnationalities as $nationality){
?>
								<option value="<?php echo $nationality['id']; ?>"<?php echo $nationality['id'] == $this->escape($this->nationalityid) ? " selected" : ""; ?>><?php echo $nationality['nationality']; ?></option>
<?php
	}
?>
							</select>

							<label><?php echo t('Gender'); ?></label>
							<select name="gender">
								<option value="na"><?php echo t('Select...'); ?></option>
								<option value="male"<?php echo ($this->escape($this->gender) == "male" ? " selected" : "");?>>Male</option>
								<option value="female"<?php echo ($this->escape($this->gender) == "female" ? " selected" : "");?>>Female</option>
							</select>

							<label><?php echo t('Date of birth'); ?></label>
							<input type="text" class="calendarbox" name="dob" id="dob" value="<?php echo ($this->escape($this->dob) != "31-12-1969" ? $this->escape($this->dob) : "");?>">

							<label><?php echo t('Age'); ?></label>
<?php
	if ($this->escape($this->dob) != "31-12-1969"){

		$birthDate = date("m/d/Y", strtotime($this->dob));
		//explode the date to get month, day and year
		$birthDate = explode("/", $birthDate);
		//get age from date or birthdate
		$age = (date("md", date("U", mktime(0, 0, 0, $birthDate[0], $birthDate[1], $birthDate[2]))) > date("md") ? ((date("Y")-$birthDate[2])-1):(date("Y")-$birthDate[2]));
	} else {
		$age = "";
	}
?>
							<input type="text" readonly value="<?php echo $age;?>"><br>

							<div class="pad20 clear"></div>
							<p style="float:left;font-size:14px;"><?php echo t('Local Address'); ?></p>

							<div class="pad20 clear"></div><br>

							<label id="province_id_lbl"><?php echo (@$this->translation['Region A (Province)']); ?></label>
<?php
	renderFilter($this->locations, 1, 'local-geo1', $this->escape($this->localgeo1), 'local-geo2');
	if ( $this->setting['display_region_b'] ) {
?>
							<label id="district_id_lbl"><?php echo (@$this->translation['Region B (Health District)']); ?></label>
<?php
	renderFilter($this->locations, 2, 'local-geo2', $this->escape($this->localgeo2), ($this->setting['display_region_c']?'local-geo3':false));
	}
	if ( $this->setting['display_region_c'] ) {
?>
							<label id="region_c_id_lbl"><?php echo (@$this->translation['Region C (Local Region)']); ?></label>
<?php
	renderFilter($this->locations, 3, 'local-geo3', $this->escape($this->localgeo3), false);
	}
?>

							<label><?php echo t('Address 1'); ?></label>
							<input type="text" name="localaddress1" value="<?php echo $this->escape($this->address1);?>">

							<label><?php echo t('Address 2'); ?></label>
							<input type="text" name="localaddress2" value="<?php echo $this->escape($this->address2);?>" >

							<label><?php echo t('City'); ?></label>
							<input type="text" name="localcity" value="<?php echo $this->escape($this->city);?>">

							<label><?php echo t('Postal code / ZIP'); ?></label>
							<input type="text" name="localpostalcode" value="<?php echo ($this->escape($this->zip) != "0" ? $this->escape($this->zip) : "");?>">

							<div class="pad20 clear"></div>
							<p style="float:left;font-size:14px;"><?php echo t('Next of Kin Address'); ?></p>
							<div class="pad20 clear"></div><br>

							<label id="province_id_lbl"><?php echo (@$this->translation['Region A (Province)']); ?></label>
						<?php
							renderFilter($this->locations, 1, 'permanent-geo1', $this->escape($this->permanentgeo1), 'permanent-geo2');
							if ( $this->setting['display_region_b'] ) {
							?>
							<label id="district_id_lbl"><?php echo (@$this->translation['Region B (Health District)']); ?></label>
							<?php
							renderFilter($this->locations, 2, 'permanent-geo2', $this->escape($this->permanentgeo2), ($this->setting['display_region_c']?'permanent-geo3':false));
							}

							if ( $this->setting['display_region_c'] ) {
							?>
							<label id="region_c_id_lbl"><?php echo (@$this->translation['Region C (Local Region)']); ?></label>
							<?php
							renderFilter($this->locations, 3, 'permanent-geo3', $this->escape($this->permanentgeo3), false);
							}
						?>

							<label><?php echo t('Address 1'); ?></label>
							<input type="text" name="permanent-address1" value="<?php echo $this->escape($this->permanentaddress1);?>">

							<label><?php echo t('Address 2'); ?></label>
							<input type="text" name="permanent-address2" value="<?php echo $this->escape($this->permanentaddress2);?>" >

							<label><?php echo t('City'); ?></label>
							<input type="text" name="permanent-city" value="<?php echo $this->escape($this->permanentcity);?>" >

							<label><?php echo t('Postal code / ZIP'); ?></label>
							<input type="text" name="permanent-postalcode" value="<?php echo $this->escape($this->permanentzip);?>">

							<div class="pad20 clear"></div><br>

							<label><?php echo t('Phone'); ?></label>
							<input type="text" name="localphone" value="<?php echo $this->escape($this->phone);?>">

							<label><?php echo t('Cellphone'); ?></label>
							<input type="text" name="localcell" value="<?php echo $this->escape($this->cell);?>" >

							<label><?php echo t('Cellphone 2'); ?></label>
							<input type="text" name="localcell2" value="<?php echo $this->escape($this->cell2);?>" >

							<label><?php echo t('Email'); ?></label>
							<input type="text" name="email" value="<?php echo $this->escape($this->email);?>">

							<label><?php echo t('Email 2'); ?></label>
							<input type="text" name="email_secondary" value="<?php echo $this->escape($this->email2);?>">

							<div class="pad20 clear"></div>
							<p style="float:left;font-size:14px;"><?php echo t('Student Information'); ?></p>
							<div class="pad20 clear"></div><br>

							<label><?php echo t('Student ID'); ?></label>
							<input readonly type="text" name="studentid" id="studentid" value="<?php echo $this->escape($this->id);?>">

							<label><?php echo t('Religious Denomination'); ?></label>
							<select name="studenttype" id="studenttype" class="comboeditable"<?php echo !$this->hascohort ? " disabled" : "";?>>
								<option value="0"><?php echo t('Select...'); ?></option>
<?php
	foreach ($this->lookupstudenttypes as $studenttype){
?>
								<option value="<?php echo $studenttype['id']; ?>"<?php echo $this->studenttype == $studenttype['id'] ? " selected" : ""; ?>> <?php echo $studenttype['studenttype']; ?></option>
<?php
	}
?>
							</select>

							<label><?php echo t('Date of Enrollment'); ?></label>
							<input type="text" name="enrollmentdate" readonly value="<?php echo $this->escape($this->enrollmentdate);?>"<?php echo !$this->hascohort ? " disabled" : "";?>>

							<label><?php echo t('Reason for Enrollment'); ?></label>
<!--							<input type="text" name="enrollmentreason" value="<?php echo $this->escape($this->enrollmentreason);?>"> -->
							<select name="enrollmentreason" id="enrollmentreason" class="comboeditable"<?php echo !$this->hascohort ? " disabled" : "";?>>
								<option value="0"><?php echo t('Select...'); ?></option>
<?php
	foreach ($this->joinreasons as $joinreason){
?>
								<option value="<?php echo $joinreason['id']; ?>"<?php echo $this->enrollmentreason == $joinreason['id'] ? " selected" : ""; ?>> <?php echo $joinreason['reason']; ?></option>
<?php
	}
?>
							</select>

							<label><?php echo t('Date of Separation'); ?></label>
							<input type="text" name="separationdate" id="separationdate" class="calendarbox" value="<?php echo $this->escape($this->separationdate);?>"<?php echo (($this->separationdate != "") && ($this->separationdate != "0000-00-00") ? " READONLY" : "");?><?php echo !$this->hascohort ? " disabled" : "";?>>
							<label><?php echo t('Clear date'); ?></label>
							<input type="button" value="Remove separation date" style="padding : 2px; position : relative; left : 24px; margin-bottom : 10px;" onclick="document.getElementById('separationdate').value = '';document.getElementById('separationreason').selectedIndex = 0;">

							<label><?php echo t('Reason for Separation'); ?></label>
<!--							<input type="text" name="separationreason"
							value="<?php echo $this->escape($this->separationreason);?>"> -->
							<select name="separationreason" id="separationreason" class="comboeditable"<?php echo !$this->hascohort ? " disabled" : "";?>>
								<option value="0"><?php echo t('Select...'); ?></option>
<?php
	foreach ($this->dropreasons as $dropreason){
?>
								<option value="<?php echo $dropreason['id']; ?>"<?php echo $this->separationreason == $dropreason['id'] ? " selected" : ""; ?>> <?php echo $dropreason['reason']; ?></option>
<?php
	}
?>
							</select>

							<label><?php echo t('Program Enrolled in'); ?></label>
							<select name="cadre" id="cadre" disabled>
								<option value="0"><?php echo t('Select...'); ?></option>
<?php
	foreach ($this->getcadres as $cadre){
		if (trim($cadre[cadrename]) != ""){
?>
								<option value="<?php echo $cohort[id]; ?>"<?php echo ($this->escape($this->cadre) == $cadre[id] ? " selected" : "") ?>><?php echo $cadre[cadrename]; ?></option>
<?php
		}
	}
?>
							</select>

							<label><?php echo t('Years of Study'); ?></label>
							<input type="text" name="yearofstudy" value="<?php echo $this->escape($this->yearofstudy);?>"<?php echo !$this->hascohort ? " disabled" : "";?> readonly>

							<div class="pad20 clear"></div>
							<p style="float:left;font-size:14px;"><?php echo t('Funding'); ?></p>
							<div class="pad20 clear"></div>

							<div style="float : right; width : 350px;">
<?php
	foreach ($this->lookupfunding as $funding){
		$checked = false;
		$amount = "";
		foreach ($this->studentfunding as $sf){
			if ($sf['fundingsource'] == $funding['id']){
				$checked = true;
				$amount = $sf['fundingamount'];
			}
		}
?>
	<div style="width : 100%; height : 25px; position : relative; top : 0px; left : 0px; margin-bottom : 5px;">
		<div style="position : absolute; top : 0px; left : 0px; width : 45px;">
			<input type="checkbox" name="funding[<?php echo $funding['id']; ?>]" id="funding[<?php echo $funding['id']; ?>]" value="<?php echo $funding['id']; ?>" style="position : relative; top : 3px;"<?php echo $checked ? " checked" : ""; ?>>
		</div>
		<div style="position : absolute; top : 0px; left : 50px; width : 190px; padding-top : 3px;">
			<?php echo $funding['fundingname']; ?>
		</div>
		<div style="position : absolute; top : 0px; left : 240px; width : 95px;">
			<input type="text" name="fundingamount[<?php echo $funding['id']; ?>]" id="funding[<?php echo $funding['id']; ?>]" value="<?php echo $amount; ?>" style="text-align : right; width : 95px; float : right; margin : 0px;">
		</div>
	</div>
<?php
}
?>
							</div>
							<div class="clear pad20"></div>

							<div class="pad20 clear"></div>
							<p style="float:left;"><?php echo t('Tutor advisor'); ?></p>
							<div class="pad20 clear"></div>

							<label><?php echo t('Tutor Advisor'); ?></label>
							<select id="tutoradvisor" name="tutoradvisor">
								<option value="0"><?php echo t('Select...'); ?></option>
<?php
	foreach ($this->gettutors as $tutor){
?>
								<option value="<?php echo $tutor[id]; ?>"<?php echo ($this->escape($this->advisor) == $tutor[id] ? " selected" : "") ?>><?php echo $tutor[first_name] . " " . $tutor[last_name]; ?></option>
<?php
	}
?>
							</select>


							<div class="clear pad20"></div>
						 	<p style="float : left;"><?php echo t('Facility After Graduation'); ?></p>
							<div class="clear pad20"></div>

<?php region_filters_dropdown_ps($this, 'post'); ?>

							<label id="province_id_lbl"><?php echo (@$this->translation['Region A (Province)']); ?></label>
<?php renderFilter($this->locations, 1, 'postgeo1', $this->postgeo1, 'postgeo2');?>
<?php if ( $this->setting['display_region_b'] ) { ?>
							<label id="district_id_lbl"><?php echo (@$this->translation['Region B (Health District)']); ?></label>
<?php renderFilter($this->locations, 2, 'postgeo2', $this->postgeo2, ($this->setting['display_region_c']?'postgeo3':false));?>
<?php } ?>
<?php if ( $this->setting['display_region_c'] ) { ?>
							<label id="region_c_id_lbl"><?php echo (@$this->translation['Region C (Local Region)']); ?></label>
<?php renderFilter($this->locations, 3, 'postgeo3', $this->postgeo3, false);?>
<?php } ?>

							<label>Facility Name</label>
			<select name="postfacilityname" id="postfacilityname" class="text ui-widget-content ui-corner-all" />
				<option value="0"><?php echo t('Select'); ?></option>
<?php
	foreach ($this->facilities as $facility){
?>
					<option value="<?php echo $facility['id']; ?>"<?php echo $facility['id'] == $this->postfacilityname ? " selected" : ""; ?>><?php echo $facility['facility_name']; ?></option>
<?php
	}
?>
			</select>

							<div class="pad20 clear"></div>
							<p style="float:left;font-size:14px;"><?php echo t('Comments'); ?></p>
							<div class="pad20 clear"></div>

							<div class="clear"></div>
							<textarea name="comments" id="comments" style="float:right; height:80px; margin-right:12px;" class="mainformholdertextarea"><?php echo $this->escape($this->comments);?></textarea>
							<div class="clear"></div>
						</div>
						<div></div>
						<div class="pad20 clear"></div>
						<div class="mainformholder" style="height : 100px; margin-top:30px;">
							<div  style="float : right; margin-right:12px;" >
								<input type="submit" name="personupdate" value="Update &raquo;" class="tsbutton green large">
								<a href="../../../people/people"> <input type="button"  value="Back" class="tsbutton green large"></a>
							</div>
							<div class="clear pad20"></div>

						</div>
						<div class="clear"></div>
					</form>


					<div class="clear"></div>
					<div style="width :100%;">
						<p style="font-weight:bold;"><?php echo t('Class History'); ?></p>
						<table cellpadding="0" cellspacing="0" border="0" class="display tablegrid" id="" style="width:100%">
							<thead>
								<tr>
									<th><?php echo t('Class Name'); ?></th>
									<th><?php echo t('Topic'); ?></th>
									<th><?php echo t('Start date'); ?></th>
									<th><?php echo t('End date'); ?></th>
									<th><?php echo t('Instructor'); ?></th>
									<th><?php echo t('Course type'); ?></th>
									<th><?php echo t('Grade'); ?></th>
								</tr>
							</thead>
							<tbody>
<?php
	foreach ($this->currentclasses as $row){
?>
								<tr class="GradeA" style="">
									<td class="" style="width : 250px;"><?php echo $row['classname']; ?></td>
									<td class="" style=""><?php echo $row['coursetopic']; ?></td>
									<td class="" style="width : 120px;"><?php echo date("m/d/Y", strtotime($row['startdate'])); ?></td>
									<td class="" style="width : 120px;"><?php echo date("m/d/Y", strtotime($row['enddate'])); ?></td>
									<td class="" style="width : 120px;"><?php echo $row['first_name'] . " " . $row['last_name']; ?></td>
									<td class="" style="width : 120px;"><?php echo $row['coursetype']; ?></td>
									<td class="" style="width : 120px;"><?php echo $row['grade']; ?></td>
								</tr>
<?php
	}
?>
							</tbody>
						</table>
						<div style="text-align : right;">
							<br>
							<input type="submit" name="classpopupbutton" id="classpopupbutton" value="Update classes" class="tsbutton green large">
						</div>
					</div>
					<div style="width :100%; ">
						<p style="margin:15px 0 15px 0;font-weight:bold;"><?php echo t('Clinical Allocation'); ?></p>
						<table cellpadding="0" cellspacing="0" border="0" class="display tablegrid" id="" style="width:100%">
							<thead>
								<tr>
									<th class=""><?php echo t('Practicum name'); ?></th>
									<th class=""><?php echo t('Date'); ?></th>
									<th class=""><?php echo t('Facility'); ?></th>
									<th class=""><?php echo t('Advisor'); ?></th>
									<th class=""><?php echo t('Hours required'); ?></th>
									<th class=""><?php echo t('Hours completed'); ?></th>
									<th class=""><?php echo t('Grade'); ?></th>
								</tr>
							</thead>
							<tbody>
<?php
	foreach ($this->currentpracticum as $row){
?>
								<tr class="GradeA" style="">
									<td class="" style=""><?php echo $row['practicumname']; ?></td>
									<td class="" style="width : 120px;"><?php echo date("m/d/Y", strtotime($row['practicumdate'])); ?></td>
									<td class="" style="width : 200px;"><?php echo $row['facility_name']; ?></td>
									<td class="" style="width : 200px;"><?php echo $row['first_name'] . " " . $row['last_name']; ?></td>
									<td class="" style="width : 120px;"><?php echo $row['hoursrequired']; ?></td>
									<td class="" style="width : 150px;"><?php echo $row['hourscompleted']; ?></td>
									<td class="" style="width : 120px;"><?php echo $row['grade']; ?></td>
								</tr>
<?php
	}
?>
							</tbody>
						</table>
						<div style="text-align : right;">
							<br>
							<input type="submit" name="practicumpopupbutton" id="practicumpopupbutton" value="Update clinical allocation" class="tsbutton green large">
						</div>
					</div>
					<div style="width :100%; ">
						<p style="margin:15px 0 15px 0;font-weight:bold;"><?php echo t('Exams (licensure/registration)'); ?></p>
						<table cellpadding="0" cellspacing="0" border="0" class="display tablegrid" id="" style="width:100%">
							<thead>
								<tr>
									<th class=""><?php echo t('License name'); ?></th>
									<th class=""><?php echo t('Date'); ?></th>
									<th class=""><?php echo t('Grade'); ?></th>
								</tr>
							</thead>
							<tbody>
<?php
	foreach ($this->currentlicenses as $row){
?>
								<tr class="GradeA" style="">
									<td class="" style=""><?php echo $row['licensename']; ?></td>
									<td class="" style="width : 120px;"><?php echo date("m/d/Y", strtotime($row['licensedate'])); ?></td>
									<td class="" style="width : 120px;"><?php echo $row['grade']; ?></td>
								</tr>
<?php
	}
?>
							</tbody>
						</table>
						<div style="text-align : right;">
							<br>
							<input type="submit" name="licensepopupbutton" id="licensepopupbutton" value="<?php echo t('Update exams'); ?>" class="tsbutton green large">
						</div>
					</div>
					<div class="clear" style=""></div>
				</div>
				<div class="clear" style=""></div>
			</div>
			<div class="clear" style="height : 100px;"></div>
			<div class="clear" style=""></div>


			<div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
			</div>
		</div>
	</body>
</html>