<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title><?php echo $this->translation['Application Name'] . " | " . $this->pageTitle; ?></title>
	<?php
	require_once('views/helpers/Location.php');
	require_once('views/helpers/ScriptContainer.php');
	require_once('views/helpers/TrainingViewHelper.php');
	print ScriptContainer::$instance->renderCSSHead();
	print ScriptContainer::$instance->renderJSHead();
	?>

</head>
<body class="yui-skin-sam">

	<div id="pageHolder">

		<div id="header"><?php require_once('views/scripts/header.phtml');?></div>
		<div id="content">

			<?php require_once 'views/scripts/status.phtml' ?>

			<h1><?php $this->mode == 'add' ? tp('Add Partner') : tp('Edit Partner'); ?></h1>
			<form action="" method="post" id="employeePartnerEdit" class="form_employee">
				<?php if ($this->partner['id']): ?>
				<div class="historyDiv">
					<a href="<?php echo $this->base_url; ?>/partner/delete/id/<?php echo $this->partner['id']; ?>"><?php echo t('Delete this').space.t('Partner'); ?></a>
					<a href="<?php echo $this->base_url; ?>/partner/add_funder_to_partner/id/<?php echo $this->partner['id']; ?>"><?php echo t('Add Funder'); ?></a>
				</div>
				<?php
					endif; // fi historyDiv

					require_once ('views/helpers/DropDown.php');
					$this->required_fields = array('partner', 'address1', 'city', 'province_id', 'phone', 'fax', 'funder', 'mechanism', 'funding_end_date[]', 'employee_transition_option_id', 'agreement_end_date', 'partner_importance_option_id', 'incoming_partner', 'comments', 'subpartner_id[]', 'hr_contact_name','hr_contact_phone','hr_contact_email');
					$this->partner['agreement_end_date'] = formhelperdate( $this->partner['agreement_end_date'] );
					//$this->viewonly = true;
					if ($this->mode != 'add') {
					  echo labelAndField($this, t('Partner').space.t('ID'),  'text', 'id',      $this->partner['id']);
					}
					echo labelAndField($this, t('Partner').space.t('Name'),'text', 'partner', $this->partner['partner']);
					
					
					
					/*
					if ($this->setting['display_partner_type'])
					echo labelAndField($this, t('Type of Partner'), $this->types, 'partner_type_option_id');
					if ($this->setting['display_employee_sub_partner']){
						echo '<div class="clear"></div>';                              // clear
						echo '<div class="fieldLabel subpartner_label">'.t('Prime Partners').'</div>';    // a label
						echo '<div class="fieldInput subpartners_wrapper">';           // the normal fieldInput
						echo '<table id="subpartners_table">';                         // a table to line everything up nicely
						if ($this->partner['subpartners'])
							foreach($this->partner['subpartners'] as $i => $value){
								$subPartners = DropDown::generateHtml ( 'partner', 'partner', $value, false, $this->viewonly, false, true, array('name' => 'subpartner_id[]'), true );
								echo   '<tr>
											<td><label class="label">'.t('ID').' </label></td>
											<td><input type="text" class="subpartner_id_display" name="subpartner_id_display[]" value="'.$value.'" readonly="readonly" /></td>
											<td><label class="label"> '.t('Prime Partner\'s Name').' </label></td>
											<td>'.$subPartners.'</td>
										</tr>';
							}
						echo '</table></div>';
						echo '<div class="clear"></div>';
						echo '<button id="add_sub_partner">'.t('Add a new').space.t('Prime Partner').'</button><br/><br/>'; // button to interact with dynamic section
					}
					*/
					
					//file_put_contents('c:\wamp\logs\php_debug.log', 'partEdit 63>'.PHP_EOL, FILE_APPEND | LOCK_EX);	ob_start();
					//var_dump($this->partner['funder']);
					//var_dump($this->subPartner);
					//$result = ob_get_clean(); file_put_contents('c:\wamp\logs\php_debug.log', $result .PHP_EOL, FILE_APPEND | LOCK_EX);
					
					if ($this->setting['display_employee_funder']) {


						foreach ($this->partner['funder'] as $i => $row) {
							
							partner_sfm_dropdown($i, $this, $this->subPartner, $this->partnerFunder, $this->mechanism, '', $row['partner_id'], $row['subpartner_id'], $row['partner_funder_option_id'], $row['mechanism_option_id'], false,  false, ' disabled ');
							
							if ($this->setting['display_employee_funding_end_date'])
								echo labelAndField($this, t('Funding End Date'), 'date','funding_end_date[]', formhelperdate($row['funding_end_date']));
						}
						
						//echo '<button id="funder_add">'.t('Add a new').space.t('Funder').'</button><br />';
					}

					//$this->viewonly = false;
					$organizers = $this->organizers;
				    $organizers .= hasACLEdit('acl_editor_training_organizer', 'admin/training-organizer', $this); // give them an insert and edit link if they have rights to this stuff
				    $organizers .= $this->hasACL('acl_editor_training_organizer') ? "<a href=\"#\" onclick=\"addToSelect('" . str_replace ( "'", "\\" . "'", t ( 'Please enter your new' ) ) . " " . strtolower ( t('Organizer') ) . ":', 'select_training_organizer_option', '" . Settings::$COUNTRY_BASE_URL . "/training/insert-table/table/training_organizer_option/column/training_organizer_phrase/outputType/json'); return false;\">" . t ( 'Insert new' ) . "</a>" : ""; // copied from training edit form
					echo labelAndField($this, t('Organizer'), $organizers,   'organizer');

					echo labelAndField($this, t('Address 1'), 'text', 'address1',  $this->partner['address1']);
					echo labelAndField($this, t('Address 2'), 'text', 'address2',  $this->partner['address2']);
					echo labelAndField($this, t('City'),      'text', 'city',      $this->partner['city']);
					echo region_filters_dropdown( $this, $this->locations, $this->partner, false, false, '', true);
					echo labelAndField($this, t('HR Contact Person Name'), 'text', 'hr_contact_name',  $this->partner['hr_contact_name']);
					echo labelAndField($this, t('HR Contact Office Phone'),             'text', 'hr_contact_phone', $this->partner['hr_contact_phone']);
					echo labelAndField($this, t('HR Contact Office Fax'),               'text', 'hr_contact_fax',   $this->partner['hr_contact_fax']);
					echo labelAndField($this, t('HR Contact Email'),                    'text', 'hr_contact_email', $this->partner['hr_contact_email']);
					#echo labelAndField($this, t('Phone'),     'text', 'phone',     $this->partner['phone']);
					#echo labelAndField($this, t('Fax'),       'text', 'fax',       $this->partner['fax']);



					#if ($this->setting['display_employee_intended_transition'])
					#	echo labelAndField($this, t('Intended Transition'), $this->transitions, 'employee_transition_option_id');
					if ($this->setting['display_employee_agreement_end_date'])
						echo labelAndField($this, t('Agreement End Date'), 'date', 'agreement_end_date', $this->partner['agreement_end_date']);
					if ($this->setting['display_employee_importance'])
						echo labelAndField($this, t('Importance'), $this->importance, 'partner_importance_option_id');
					if ($this->setting['display_employee_incoming_partner'])
						echo labelAndField($this, t('Incoming Partner(s)'), $this->incomingPartners, 'incoming_partner');
					if ($this->setting['display_employee_transition_confirmed'])
					echo labelAndCheckBox($this, t('Transition Confirmed'), 'transition_confirmed', $this->partner['transition_confirmed'], false, $this->viewonly);
#					echo labelAndField($this, t('Partner Comments'), 'textarea', 'comments', $this->partner['comments']);

				?>

				<script type="text/javascript">

					$(document).ready(function () {

						itech_save_confirm_on_leave();

						var subselectchange = function (e) { /* subpartner - <select> 'change' logic */
							// update id box on change
							var $idbox = $(this).parents('tr').find('input.subpartner_id_display:first');
							$idbox.val( (($(this).val()) ? $(this).val() : null));
						};
						$('select[name=subpartner_id\\[\\]]').click(subselectchange);

						$('#add_sub_partner').click( function (e) { /* button - add a new sub partner */
							var template = $('#subpartners_table tr:first').clone();
							template.find('select,input').val(null);
							$('#subpartners_table').append(template);
							$('select[name=subpartner_id\\[\\]]').unbind('click').click(subselectchange); // same functionaility
							e.preventDefault();
						});

						$('#select_partner_type_option').change(function (e) { /* type of partner dropdown */
							var elems  = $('.subpartners_wrapper,.subpartner_label,#add_sub_partner');
							if ($(this).find('option:selected:first').text() == '<?php tp('Sub Partner'); ?>'){
								elems.show();
							} else {
								$('#subpartners_table select').val(0);
								elems.hide();
							}
						}).change(); // fire once

						$('.datepicker').each(function () {
							$(this).removeAttr('id').datepicker({ //bugfix, datepicker doesnt work with multiple id="" field, these are cloned so remove id attribute
								changeMonth: true,
								changeYear: true,
								dateFormat: "dd/mm/yy"
							})
						});
						$('.calendarbtn').click(openNearestDatePicker);

						$('#id').attr({readonly: 'readonly'});

						$('#funder_add').click( function (e) { /* button - add a new funder */
							e.preventDefault();
							var btn = $(this);
							var target = null;
							
							$(".subPartner_lbl:first").add(".partnerFunder_lbl:first").add(".mechanism_lbl:first").add(".funding_end_date\\[\\]:first").each(function () { // class="fieldlabel funder[]", then 'funding_end_date[]' (we'll use these as a template)
								btn.before( $(this).clone() );
								var template = $(this).next().clone();
								template.find('input,select').val('');							
								if ( template.find('input.datepicker') )
									target = template.find('input.datepicker');
								btn.before( template );
							});

							$(target).removeClass('hasDatepicker').removeAttr('id').datepicker({ // rebind datepicker and calender
								changeMonth: true,
								changeYear: true
							});
							$('.calendarbtn').unbind('click').click(openNearestDatePicker);
							return false;
						});
					});
				</script>

				<div class="clear"></div>
				<input type="hidden" name="limit" id="limit" value="1" />
				<input type="submit" class="submitNoArrow" name="go" value="<?php tp('Save');?>" />
			</form>
			<div class="clear"></div>
		</div>
	</body>
</html>