<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title><?php echo $this->translation['Application Name'] . " | " . $this->pageTitle; ?></title>
	<?php
	require_once('views/helpers/Location.php');
	require_once('views/helpers/ScriptContainer.php');
	require_once('views/helpers/TrainingViewHelper.php');
	print ScriptContainer::$instance->renderCSSHead();
	print ScriptContainer::$instance->renderJSHead();
	?>

</head>
<body class="yui-skin-sam">

	<div id="pageHolder">
        <script type="text/javascript">

            var formatEuroDate = function(elCell, oRecord, oColumn, sData) {
                var end = oRecord.getData("end_date");
                if (!end) {
                    end = "0000-00-00";
                }
                var end_date = end.split("-");
                elCell.innerHTML = end_date[2] + "/" + end_date[1] + "/" + end_date[0];
            };
        </script>

		<div id="header"><?php require_once('views/scripts/header.phtml');?></div>
		<div id="content">

			<?php require_once 'views/scripts/status.phtml' ?>

			<h1><?php $this->mode == 'add' ? tp('Add Partner') : tp('Edit Partner'); ?></h1>
			<form action="" method="post" id="employeePartnerEdit" class="form_employee">
				<?php if (($this->partner['id']) && ($this->hasACL("edit_partners")) && ($this->hasACL("delete_partners"))): ?>
				<div class="historyDiv">
					<a href="<?php echo $this->base_url; ?>/partner/delete/id/<?php echo $this->partner['id']; ?>"><?php echo t('Delete this').space.t('Partner'); ?></a>
				</div>
				<?php
					endif; // fi historyDiv

					require_once ('views/helpers/DropDown.php');
					$this->required_fields = array('partner', 'address1', 'city', 'province_id', 'phone', 'fax', 'funder', 'mechanism', 'funding_end_date[]', 'employee_transition_option_id', 'agreement_end_date', 'partner_importance_option_id', 'incoming_partner', 'comments', 'subpartner_id[]', 'hr_contact_name','hr_contact_phone','hr_contact_email');
					$this->partner['agreement_end_date'] = formhelperdate( $this->partner['agreement_end_date'] );
					if ($this->mode != 'add') {
					  echo labelAndField($this, t('Partner').space.t('ID'),  'text', 'id',      $this->partner['id']);
					}
					echo labelAndField($this, t('Partner').space.t('Name'),'text', 'partner', $this->partner['partner']);
					
                    $organizers = $this->organizers;
				    $organizers .= hasACLEdit('acl_editor_training_organizer', 'admin/training-organizer', $this); // give them an insert and edit link if they have rights to this stuff
				    $organizers .= $this->hasACL('acl_editor_training_organizer') ? "<a href=\"#\" onclick=\"addToSelect('" . str_replace ( "'", "\\" . "'", t ( 'Please enter your new' ) ) . " " . strtolower ( t('Organizer') ) . ":', 'select_training_organizer_option', '" . Settings::$COUNTRY_BASE_URL . "/training/insert-table/table/training_organizer_option/column/training_organizer_phrase/outputType/json'); return false;\">" . t ( 'Insert new' ) . "</a>" : ""; // copied from training edit form
					echo labelAndField($this, t('Organizer'), $organizers,   'organizer');

					echo labelAndField($this, t('Address 1'), 'text', 'address1',  $this->partner['address1']);
					echo labelAndField($this, t('Address 2'), 'text', 'address2',  $this->partner['address2']);
					echo labelAndField($this, t('City'),      'text', 'city',      $this->partner['city']);
					echo region_filters_dropdown( $this, $this->locations, $this->partner, false, false, '', true);
					echo labelAndField($this, t('HR Contact Person Name'), 'text', 'hr_contact_name',  $this->partner['hr_contact_name']);
					echo labelAndField($this, t('HR Contact Office Phone'),             'text', 'hr_contact_phone', $this->partner['hr_contact_phone']);
					echo labelAndField($this, t('HR Contact Office Fax'),               'text', 'hr_contact_fax',   $this->partner['hr_contact_fax']);
					echo labelAndField($this, t('HR Contact Email'),                    'text', 'hr_contact_email', $this->partner['hr_contact_email']);
					#echo labelAndField($this, t('Phone'),     'text', 'phone',     $this->partner['phone']);
					#echo labelAndField($this, t('Fax'),       'text', 'fax',       $this->partner['fax']);



					#if ($this->setting['display_employee_intended_transition'])
					#	echo labelAndField($this, t('Intended Transition'), $this->transitions, 'employee_transition_option_id');
					if ($this->setting['display_employee_agreement_end_date'])
						echo labelAndField($this, t('Agreement End Date'), 'date', 'agreement_end_date', $this->partner['agreement_end_date']);
					if ($this->setting['display_employee_importance'])
						echo labelAndField($this, t('Importance'), $this->importance, 'partner_importance_option_id');
					if ($this->setting['display_employee_incoming_partner'])
						echo labelAndField($this, t('Incoming Partner(s)'), $this->incomingPartners, 'incoming_partner');
					if ($this->setting['display_employee_transition_confirmed'])
					echo labelAndCheckBox($this, t('Transition Confirmed'), 'transition_confirmed', $this->partner['transition_confirmed'], false, $this->viewonly);
#					echo labelAndField($this, t('Partner Comments'), 'textarea', 'comments', $this->partner['comments']);

				?>

				<script type="text/javascript">

					$(document).ready(function () {

						itech_save_confirm_on_leave();

					});
				</script>
                <br/>

                <?php
                if ($this->setting['display_employee_funder']) {
                    if ($this->primeMechanisms) {
                        echo "<h1>Prime" . space . t('Mechanisms') . ":</h1>";
                        echo $this->primeMechanisms;
                        echo "<br/>";
                    }

                    if ($this->secondaryMechanisms) {
                        echo "<h1>Subpartner on" . space . t('Mechanisms') . ":</h1>";
                        echo $this->secondaryMechanisms;
                    }
                }
                ?>
				<div class="clear"></div>
				<input type="hidden" name="limit" id="limit" value="1" />
				<input type="submit" class="submitNoArrow" name="go" value="<?php tp('Save');?>" />
			</form>
			<div class="clear"></div>
		</div>
	</body>
</html>