<!DOCTYPE html>
<html>
<head>
	<title><?php echo $this->translation['Application Name'] . " | " . $this->pageTitle; ?></title>
	<?php
	require_once('views/helpers/Location.php');
	require_once('views/helpers/ScriptContainer.php');
	print ScriptContainer::$instance->renderCSSHead();
	print ScriptContainer::$instance->renderJSHead();
	echo $this->partial('reports/employee-reports-common-javascript-header-partial.phtml');
	?>

    <script type="text/javascript">
        function toggle_date_requirement() {
            $('#capture_complete_required').toggle($('#show_complete_captures').val() === '1');
            return true;
        }
        $(document).ready(function () { toggle_date_requirement(); });

    </script>
</head>
<body class="yui-skin-sam">

	<div id="pageHolder">

		<div id="header"><?php require_once('views/scripts/header.phtml');?></div>
		<div id="content">
            <?php require_once 'views/scripts/status.phtml' ?>

			<h1><?php tp('Search Partners');?></h1>
			<form action="" method="get" class="form_employee">
				<fieldset><legend><?php tp('Select Criteria');?></legend>
					<?php
						$this->required_fields = array();
						echo '<input type="text" width="0" style="width: 0; height: 0; top: -100px; position: absolute;"/>'; // bugfix so jquery datepicker doesnt open on dom ready (first element in chrome thats a textbox will focus and trigger..=[)
						if($this->setting['display_employee_partner']) {
							echo labelAndField($this, t('Partner') . space . t('Name'), $this->partners);
						}
						echo region_filters_dropdown( $this, $this->locations, $this->criteria, false, false );
						$cal = '<a class="calendarbtn" href="#"><img src="'.$this->base_url.'/js/yui/assets/calbtn.gif"></a>';
						if ($this->setting['display_employee_funder']) {
							echo $this->partial('/reports/date-range-partial.phtml',
								array('label' => t('Funding End Date Between'),
									'prefix' => 'funding_',
									'start_date' => $this->criteria['funding_start_date'],
									'end_date' => $this->criteria['funding_end_date'],
									'show_value' => false)
							);
						}

                        echo '<div class="fieldLabel">';
                        echo $this->formLabel("", t('Show Only Complete Data Captures'));
                        echo '</div>';
                        echo '<div class="fieldInput">';
                        echo $this->formCheckbox("show_complete_captures", $this->criteria['show_complete_captures'],
                            array('onClick' => 'toggle_date_requirement();', 'style' => 'margin-top: .25em;', 'checked' => $this->criteria['show_complete_captures']));
                        echo '</div><div class="clear"></div>';

						echo $this->partial('/reports/date-range-partial.phtml',
							array('label' => t('Data Capture Completion Date'),
								'prefix' => 'capture_complete_',
								'start_date' => $this->criteria['capture_complete_start_date'],
								'end_date' => $this->criteria['capture_complete_end_date'],
                                'required' => $this->criteria['show_complete_captures'],
								'show_value' => false)
						);
					?>
					<div class="clear"></div>
					<input type="hidden" name="limit" id="limit" value="1" />
                    <?php
                    echo $this->partial('reports/ps-search-preview-button-partial.phtml', array());
                    ?>

				</fieldset>
			</form>
            <?php if (isset($this->output)) {
                echo $this->partial('reports/ps-jquery-table-search-results-preview-partial.phtml',
                    array('output' => $this->output, 'headers' => $this->headers));
                ?>
                <input type="button" name="go" value="<?php tp('Download');?> &raquo;" class="tsbutton green large"
                       onclick="window.open('<?php echo $_SERVER['REQUEST_URI'] . "&format=csv"?>')">
            <?php } ?>

		</div>
	</body>
</html>