<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<style>
#homecontent {
	background: url("images/content-bg.png") repeat-x scroll 0 0 #FAFAFA;
	position: relative;
}

#homecontent-mid {
	background: url("images/bg-stage.png") repeat-y scroll right top #FFFFFF;
	border: 1px solid #BDBCBD;
	min-height: 100%;
	outline: medium none;
	top: -40px;
}

#homebanner {
	background: url("images/bg-stage-shade.png") repeat-x scroll 0 0
		transparent;
	padding-right: 20px;
	position: relative;
}

.rounded {
	border-radius: 10px 10px 10px 10px;
}

.sliderdiv {
	background: none repeat scroll 0 0 FFFFFF;
	float: left;
}

.main-search {
	background: none repeat scroll 0 0 #FFFFFF;
	float: left;
	overflow: hidden;
}

.nav-buttons {
	background: none repeat scroll 0 0 #FFFFFF;
	float: left;
	overflow: hidden;
}

</style>

<link href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700"
	rel="stylesheet" type="text/css">

<?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>


      <link rel="stylesheet" type="text/css"
	href="https://google-developers.appspot.---com/_static/f7a896e076/css/screen-docs.css" />
<link rel="stylesheet"
	href="//www.google.com/cse/style/look/default.css" type="text/css" />
<link rel="stylesheet"
	href="//fonts.googleapis.com/css?family=Open+Sans:300,400"
	type="text/css">
<script
	src="https://google-developers.appspot.com/_static/f7a896e076/js/prettify-bundle.js"></script>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
<script id="jqueryui"
	src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js"
	defer async></script>
<script
	src="//www.google.com/jsapi?key=AIzaSyCZfHRnq7tigC-COeQRmoa9Cxr0vbrK6xw"></script>
<!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
<script
	src="https://google-developers.appspot.com/_static/f7a896e076/js/framebox.js"></script>

</head>
<body class="yui-skin-sam">

	<div id="pageHolder">

		<div id="header"><?php require_once('views/scripts/header.phtml');?></div>
		<div id="content">

			<!-------   /////////////////////////// get data ////////////////////// -->
			<div> <?php  //require_once('views/scripts/dashboard/load_data.phtml');?>
			
			<!-------   /////////////////////////// make top buttons ////////////////////// -->
			<div class="rightdiv" style="float: right;">
				<?php  require_once('views/scripts/dashboard/top_buttons.phtml');?>
			</div>
			<div class="clear"></div>
			<div class="hrGrey"></div>
			<!-------   /////////////////////////// make left buttons ////////////////////// -->
			<div class="nav-buttons">
				<?php  require_once('views/scripts/dashboard/left_buttons.phtml');?>
			</div>
			<!-------   /////////////////////////// charts ////////////////////// -->
			<body">
				<div id="allCharts" class="container">
				
				
				<div id="chart11_div" style="width: 800px; height: 1400px;"></div>
				
				</div>
				</body>
			</div>	
		<div class="clear"></div>
		<div class="hrGrey"></div>
		<div class="clear"></div>
		
		<script type="text/javascript" src="https://www.google.com/jsapi"></script>

		<!-------   /////////////////////////// main ////////////////////// -->

		<script type="text/javascript">
		
  google.load('visualization', '1.1', {'packages':['corechart', 'table', 'gauge', 'controls']});
  google.load('visualization', '1.1', {'packages':['bar']});
  google.setOnLoadCallback(apiLoaded);
  function apiLoaded() {
	  document.getElementById("allCharts").style.marginLeft="130px";

	drawChart11();
	var currentLevel;
	currentLevel = <?php echo '\'' . $this->location_data[0][name] . '\''; ?>;

  }

  <!-------   /////////////////////////// script 1,1 ////////////////////// -->

  function drawChart11() {
      var chart11_data = google.visualization.arrayToDataTable([
        [' ', 'Implanon', 'Jadelle', 'Condoms'],

        <?php
    	  		foreach ($this->latest_consumption_data as $row){
    	  	?>
    	  	[<?php echo  " '$row[location_name]',$row[implanon_consumption],$row[jadelle_consumption],$row[condom_consumption] "; ?>],
    	  	<?php
    	  		}
    	  	?>
        
      ]);

      var calc_height = 500;
      
      if (chart11_data.Nf.length * 22 > 500){
          calc_height =  chart11_data.Nf.length * 22;
      }

    
    <?php echo  " var title_data = 'Consumption as of $this->title_data ' " ?>;
      
      var chart11_options = {
    		  title: title_data,
    		  bar: {groupWidth: "90%"},
    		  width: 800,
    		  height: calc_height,
      };

      //var chart11 = new google.charts.Bar(document.getElementById('chart11_div'));
      var chart11 = new google.visualization.BarChart(document.getElementById('chart11_div'));

      chart11.draw(chart11_data, chart11_options);
    }
  

  function drawChart12() {
	  // Create and populate the data table.
	  var chart11Data = google.visualization.arrayToDataTable([

['State', 'Percentage', { role: 'style' }],
	                                                           
	['Ogun', 0.0006, 'red'],
		['Katsina', 0.0007, 'red'],
		['Kaduna', 0.0007, 'red'],
		['Benue', 0.0007, 'red'],
		['Kano', 0.0008, 'red'],
		['Taraba', 0.0010, 'blue'],
		['Niger', 0.0011, 'blue'],
		['Rivers', 0.0012, 'blue'],
		['Abia', 0.0013, 'blue'],
		['Borno', 0.0015, 'blue'],
		['National', 0.0004, 'black'],
	
]);

	  var chart11Options = {
		      title: '% of Facilities that are stocked out FP commodities',
		      vAxis: {title: 'State'},
		      hAxis: {title: 'Percentage'},
		      is3D:true
		};


	            var chart11 = new google.visualization.ColumnChart(document.getElementById('chart11_div'));
	            
	  chart11.draw(chart11Data, chart11Options);
	}

 
  <!-------   /////////////////////////// 2,1 script gnr  ////////////////////// -->

	

  <!-------   /////////////////////////// 2,1 end script ////////////////////// -->


  <!-------   /////////////////////////// 2,2 script ////////////////////// -->

	


  <!-------   /////////////////////////// 2,2 end script ////////////////////// -->
  

  

</script>


<script>
  devsite.github.Link.convertAnchors();
  window.prettyPrint();
</script>	

  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>



</body>

</html>

