<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<style>
#homecontent {
	background: url("images/content-bg.png") repeat-x scroll 0 0 #FAFAFA;
	position: relative;
}

#homecontent-mid {
	background: url("images/bg-stage.png") repeat-y scroll right top #FFFFFF;
	border: 1px solid #BDBCBD;
	min-height: 100%;
	outline: medium none;
	top: -40px;
}

#homebanner {
	background: url("images/bg-stage-shade.png") repeat-x scroll 0 0
		transparent;
	padding-right: 20px;
	position: relative;
}

.rounded {
	border-radius: 10px 10px 10px 10px;
}

.sliderdiv {
	background: none repeat scroll 0 0 FFFFFF;
	float: left;
}

.main-search {
	background: none repeat scroll 0 0 #FFFFFF;
	float: left;
	overflow: hidden;
}

.nav-buttons {
	background: none repeat scroll 0 0 #FFFFFF;
	float: left;
	overflow: hidden;
}

</style>

<link href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700"
	rel="stylesheet" type="text/css">

<?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>


      <link rel="stylesheet" type="text/css"
	href="https://google-developers.appspot.---com/_static/f7a896e076/css/screen-docs.css" />
<link rel="stylesheet"
	href="//www.google.com/cse/style/look/default.css" type="text/css" />
<link rel="stylesheet"
	href="//fonts.googleapis.com/css?family=Open+Sans:300,400"
	type="text/css">
<script
	src="https://google-developers.appspot.com/_static/f7a896e076/js/prettify-bundle.js"></script>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
<script id="jqueryui"
	src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js"
	defer async></script>
<script
	src="//www.google.com/jsapi?key=AIzaSyCZfHRnq7tigC-COeQRmoa9Cxr0vbrK6xw"></script>
<!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
<script
	src="https://google-developers.appspot.com/_static/f7a896e076/js/framebox.js"></script>

</head>
<body class="yui-skin-sam">

	<div id="pageHolder">

		<div id="header"><?php require_once('views/scripts/header.phtml');?></div>
		<div id="content">

			<!-------   /////////////////////////// get data ////////////////////// -->

			<div>
				<?php  // require_once('views/scripts/dashboard/load_data.phtml');?>

			<!-------   /////////////////////////// make top buttons ////////////////////// -->

			<div class="rightdiv" style="float: right;">
				<?php //require_once('views/scripts/dashboard/top_buttons.phtml');?>
			</div>

			<!-------   /////////////////////////// make left buttons ////////////////////// -->

			<div class="nav-buttons">
				<?php  require_once('views/scripts/dashboard/left_buttons.phtml');?>
				<?php  //require_once('views/scripts/dashboard/geo_button.phtml');?>
				
			</div>
			
			<!-------   /////////////////////////// load scripts ////////////////////// -->
            <div class="nav-buttons">
				<?php require_once('views/scripts/dashboard/displayScripts.phtml');?>
			</div>

			<!-------   /////////////////////////// charts ////////////////////// -->


			<body class="docs slim framebox_body">

				<div id="allCharts" class="container">

				<div id="toprow" class="container">
						<div id="homecontent" class="container">
							<div id="homecontent-mid" class="row rounded">
								<div id="homebanner" class="rounded">
								<div class="sliderdiv">
									<div id="chart_div" style="width: 500px; height: 300px;"></div>
									</div>
									<div class="main-search">
										<div id="chart12_div" style="width: 500px; height: 300px;"></div>
									</div>
								</div>
							</div>
						</div>			
					</div>
					
					</div>

								<!-------   /////////////////////////// chart 2,1 ////////////////////// -->
								
					<div id="bottomrow" class="container">
						<div id="homecontent" class="container">
							<div id="homecontent-mid" class="row rounded">
								<div id="homebanner" class="rounded">
								<div class="sliderdiv">
									<div id="chart13_div" style="width: 800px; height: 300px;"></div>
									</div>
									<div class="main-search">
										<div id="chart13_div" style="width: 500px; height: 300px;"></div>
									</div>
								</div>
							</div>
						</div>
								
								<!-------   /////////////////////////// chart 2,2 ////////////////////// -->
								
								
								<div class="main-search"></div>

					</div>
				</div>
		
	</div>

		<div class="clear"></div>
		<div class="hrGrey"></div>
		<div class="clear"></div>
		
		<script type="text/javascript" src="https://www.google.com/jsapi"></script>

		<!-------   /////////////////////////// main gnr ////////////////////// -->

		<script type="text/javascript">
		
  google.load('visualization', '1.0', {'packages':['corechart', 'table', 'gauge', 'controls']});
  google.setOnLoadCallback(apiLoaded);
  function apiLoaded() {
	  document.getElementById("allCharts").style.marginLeft="130px";

	//drawChart11();
	//drawChart12();
		
	var currentLevel;
	currentLevel = <?php echo '\'' . $this->location_data[0][name] . '\''; ?>;

<?php  //file_put_contents('c:\wamp\logs\php_debug.log', 'dash3 193 >'.PHP_EOL, FILE_APPEND | LOCK_EX);	ob_start();
	   //var_dump("location_data=", $this->location_data[0],"END");
	   //var_dump("facility_data=",$this->facility_data[0],"END");
	   //$result = ob_get_clean(); file_put_contents('c:\wamp\logs\php_debug.log', $result .PHP_EOL, FILE_APPEND | LOCK_EX); 
?>
		 
	//drawHighchart(currentLevel);
drawChart();
	//drawChart11();
	//drawChart12();
    //generateBarChart();
   
  }

  <!-------   /////////////////////////// script 1,1 ////////////////////// -->

  //TA:17:17: Coverage HW Trained chart
  function drawChart() {

      var chartData = google.visualization.arrayToDataTable([

        [' ', 'Total FP Trained', 'Total LARC Trained', '2015 Target # HWs to be Trained in LARC'],
        <?php
                     foreach($this->tp_data as $key=> $value) {
               echo "['" . $key . "', " . $value['tp_fp'] . ", " . $value['tp_larc'] . ",5500],";
                     }
        ?>                                        
      ]);

      <?php echo  " var title_data = 'Number of HWs trained as of $this->tp_date' " ?>;

      var chartOptions = {
                title: title_data,
                titleTextStyle: { fontSize: 16 },
                vAxis: {format: '#'}, 
                seriesType: "bars",
                series: {2: {type: "line", color: 'red'}},
                chartArea: {width: '50%', left: 80},//new          
      };

     var chart = new google.visualization.ColumnChart(document.getElementById('chart_div'));
      chart.draw(chartData, chartOptions);
    }
  
  function drawChart11() {

      var chart11Data = google.visualization.arrayToDataTable([

['Year', 'FP', 'LARC'],



      ]);
	  
      var chart11Options = {
        title: 'Number of Health Workers Trained',
        titleTextStyle: { fontSize: 15 },
        
      };

      var chart11 = new google.visualization.ColumnChart(document.getElementById('chart11_div'));

      chart11.draw(chart11Data, chart11Options);
    }


  function drawChart13() {
	   Highcharts({
	        title: {
	            text: 'Monthly Average Temperature',
	            x: -20 //center
	        },
	        subtitle: {
	            text: 'Source: WorldClimate.com',
	            x: -20
	        },
	        xAxis: {
	            categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
	                'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
	        },
	        yAxis: {
	            title: {
	                text: 'Temperature (°C)'
	            },
	            plotLines: [{
	                value: 0,
	                width: 1,
	                color: '#808080'
	            }]
	        },
	        tooltip: {
	            valueSuffix: '°C'
	        },
	        legend: {
	            layout: 'vertical',
	            align: 'right',
	            verticalAlign: 'middle',
	            borderWidth: 0
	        },
	        series: [{
	            name: 'Tokyo',
	            data: [7.0, 6.9, 9.5, 14.5, 18.2, 21.5, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6]
	        }, {
	            name: 'New York',
	            data: [-0.2, 0.8, 5.7, 11.3, 17.0, 22.0, 24.8, 24.1, 20.1, 14.1, 8.6, 2.5]
	        }, {
	            name: 'Berlin',
	            data: [-0.9, 0.6, 3.5, 8.4, 13.5, 17.0, 18.6, 17.9, 14.3, 9.0, 3.9, 1.0]
	        }, {
	            name: 'London',
	            data: [3.9, 4.2, 5.7, 8.5, 11.9, 15.2, 17.0, 16.6, 14.2, 10.3, 6.6, 4.8]
	        }]
	    });
  };


 <!-------   /////////////////////////// script 1,2 ////////////////////// -->
  
  function drawChart12() {
	 var data = google.visualization.arrayToDataTable([
	   ['Method', 'LARC', 'Male Condom', 'Female Condom', 'IUD', { role: 'annotation' } ],
	   ['2011', 10, 24, 20, 5, ''],
	   ['2012', 16, 22, 23, 9, ''],
	   ['2013', 28, 19, 29, 13, '']
	 ]);

	 var options = {
		        width: 600,
		        height: 400,
		        legend: { position: 'top', maxLines: 3 },
		        bar: { groupWidth: '75%' },
		        isStacked: true
		      };

      var chart = new google.visualization.BarChart(document.getElementById('chart12_div'));

      chart.draw(data, options);
    }
  


  <!-------   /////////////////////////// 2,1 script gnr  ////////////////////// -->

	function drawHighchart(currentLevel) {

	    Highcharts.data({
	        csv: document.getElementById('latest_consumption_data').innerHTML,
	        itemDelimiter: '\t',
	        parsed: function (columns) {

	            var brands = {},
	                brandsData = [],
	                versions = {},
	                drilldownSeries = [];

	            // Parse percentage strings
	            columns[1] = $.map(columns[1], function (value) {
	                if (value.indexOf('%') === value.length - 1) {
	                    value = parseFloat(value);
	                }
	                return value;
	            });

	            $.each(columns[0], function (i, name) {
	                var brand,
	                    version;

	                if (i > 0) {

	                    // Remove special edition notes
	                    name = name.split(' ');

	                    // Split into brand and version
	                    brand = name[0];
	                    version = name[1];

	                    // Create the main data
	                    if (!brands[brand]) {
	                        brands[brand] = columns[1][i];
	                    } else {
	                        brands[brand] += columns[1][i];
	                    }

	                    // Create the version data
	                    if (version !== null) {
	                        if (!versions[brand]) {
	                            versions[brand] = [];
	                        }
	                        versions[brand].push([version, columns[1][i]]);
	                    }
	                }
	            });

	            $.each(brands, function (name, y) {
	                brandsData.push({
	                    name: name,
	                    y: y,
	                    drilldown: versions[name] ? name : null
	                });
	            });
	            $.each(versions, function (key, value) {
	                drilldownSeries.push({
	                    name: key,
	                    id: key,
	                    data: value
	                });
	            });

	            // Create the chart, column or bar
	            $(document.getElementById('highChart_div')).highcharts({
	                chart: {
	                    type: 'column'
	                },
	                title: {
	                    text: 'Latest Consumption'
	                },
	                xAxis: {
	                    type: 'category'
	                },
	                yAxis: {
	                    title: {
	                        text:  'Total Consumption'
	                    }
	                },
	                legend: {
	                    enabled: false
	                },
	                plotOptions: {
	                    series: {
	                        borderWidth: 0,
	                        dataLabels: {
	                            enabled: true,
	                            format: '{point.y:.0f}'
	                        }
	                    }
	                },

	                tooltip: {
	                    headerFormat: '<span style="font-size:11px">{series.name}</span><br>',
	                    pointFormat: '<span style="color:{point.color}">{point.name}</span>: <b>{point.y:.0f}</b> of total<br/>'
	                },

	                series: [{
	                    name: currentLevel,
	                    colorByPoint: true,
	                    data: brandsData
	                }],
	                drilldown: {
	                    series: drilldownSeries
	                }
	            });
	        }
	    });
	};

  <!-------   /////////////////////////// 2,1 end script ////////////////////// -->


  <!-------   /////////////////////////// 2,2 script ////////////////////// -->

	


  <!-------   /////////////////////////// 2,2 end script ////////////////////// -->
  

  

</script>


<script>
  devsite.github.Link.convertAnchors();
  window.prettyPrint();
</script>	

  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>



</body>

</html>

