<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<style>
#homecontent {
	background: url("images/content-bg.png") repeat-x scroll 0 0 #FAFAFA;
	position: relative;
}

#homecontent-mid {
	background: url("images/bg-stage.png") repeat-y scroll right top #FFFFFF;
	border: 1px solid #BDBCBD;
	min-height: 100%;
	outline: medium none;
	top: -40px;
}

#homebanner {
	background: url("images/bg-stage-shade.png") repeat-x scroll 0 0
		transparent;
	padding-right: 20px;
	position: relative;
}

.rounded {
	border-radius: 10px 10px 10px 10px;
}

.sliderdiv {
	background: none repeat scroll 0 0 FFFFFF;
	float: left;
}

.main-search {
	background: none repeat scroll 0 0 #FFFFFF;
	float: left;
	overflow: hidden;
}

.nav-buttons {
	background: none repeat scroll 0 0 #FFFFFF;
	float: left;
	overflow: hidden;
}
</style>

<link href="//fonts.googleapis.com/css?family=Droid+Sans:400,700"
	rel="stylesheet" type="text/css">

<?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>


      <link rel="stylesheet" type="text/css"
	href="https://google-developers.appspot.---com/_static/f7a896e076/css/screen-docs.css" />
<link rel="stylesheet"
	href="//www.google.com/cse/style/look/default.css" type="text/css" />
<link rel="stylesheet"
	href="//fonts.googleapis.com/css?family=Open+Sans:300,400"
	type="text/css">
<script
	src="https://google-developers.appspot.com/_static/f7a896e076/js/prettify-bundle.js"></script>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
<script id="jqueryui"
	src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js"
	defer async></script>
<script
	src="//www.google.com/jsapi?key=AIzaSyCZfHRnq7tigC-COeQRmoa9Cxr0vbrK6xw"></script>
<!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
<script
	src="https://google-developers.appspot.com/_static/f7a896e076/js/framebox.js"></script>


</head>
<body class="yui-skin-sam">

	<div id="pageHolder">

		<div id="header"><?php require_once('views/scripts/header.phtml');?></div>
		<div id="content">

			<!-------   /////////////////////////// get data ////////////////////// -->

			<div>	
					
<?php
    $idx = 0;
    $tdata = array();
    
	foreach ($this->getins as $getresult){
?>

<?php 
 $tdata[$idx] = array($getresult['col1'], $getresult['col2']);
 $idx = $idx+1;
?>



<?php
	}
?>


</div>

			<!-------   /////////////////////////// make top buttons ////////////////////// -->

			<div class="rightdiv" style="float: right;">
				<?php  require_once('views/scripts/dashboard/top_buttons.phtml');?>
			</div>

			<div class="clear"></div>
			<div class="hrGrey"></div>
			<div class="clear"></div>

			<!-------   /////////////////////////// make left buttons ////////////////////// -->

			<div class="nav-buttons">
				<?php  require_once('views/scripts/dashboard/left_buttons.phtml');?>
			</div>

			<!-------   /////////////////////////// chart ////////////////////// -->


			<body class="docs slim framebox_body">

				<div id="allCharts" class="container">

					<div id="toprow" class="container">

						<div id="homecontent" class="container">
							<div id="homecontent-mid" class="row rounded">
								<div id="homebanner" class="rounded">
									<div class="sliderdiv">

										<div id="dashboard1_div"
											style="border: 1px solid #ccc; margin-top: 1em">
											<p style="padding-left: 1em">
												<strong>1,1</strong>
											</p>
											<table class="columns">
												<tr>
													<td>
														<div id="slider1_div" style="padding-left: 15px"></div>
													</td>
													<td>
														<div id="categoryPicker1_div"></div>
													</td>
												</tr>
												<tr>
													<td>
														<div id="chart1_div" style="padding-top: 15px"></div>
													</td>
													<td>
														<div id="table1_div" style="padding-top: 30px"></div>
													</td>
												</tr>
											</table>
										</div>

									</div>

									<div class="main-search">


										<div id="dashboard2_div"
											style="border: 1px solid #ccc; margin-top: 1em">
											<p style="padding-left: 1em">
												<strong>1,2</strong>
											</p>
											<table class="columns">
												<tr>
													<td>
														<div id="slider2_div" style="padding-left: 15px"></div>
													</td>
													<td>
														<div id="categoryPicker2_div"></div>
													</td>
												</tr>
												<tr>
													<td>
														<div id="chart2_div" style="padding-top: 15px"></div>
													</td>
													<td>
														<div id="table2_div" style="padding-top: 30px"></div>
													</td>
												</tr>
											</table>
										</div>


									</div>
								</div>
							</div>
						</div>

					</div>


					<div class="clear"></div>
					<div class="hrGrey"></div>
					<div class="clear"></div>


					<div id="bottomrow" class="container">


						<div id="homecontent" class="container">
							<div id="homecontent-mid" class="row rounded">
								<div id="homebanner" class="rounded">
									<div class="sliderdiv">
										2,1

										<table align="center">
											<tr valign="top">
												<td style="width: 50%;">
													<div id="map_div" style="width: 400px; height: 300;"></div>
												</td>
												<td style="width: 50%;">
													<div id="table_div"></div>
												</td>
											</tr>
											<tr>
												<td colspan=2>
													<div id="chart_div"
														style="align: center; width: 700px; height: 300px;"></div>
												</td>
											</tr>
										</table>



									</div>

									<div class="main-search">
										2,2

										<div style="float: left">
											<div id="chart22_div"></div>
											<button class="reset"
												onclick="drawRegionsMap();$('#table').html('');">Reset</button>
										</div>
										<div class='state-data'>
											<div id="table22" style="width: 300px; height: 300px;"></div>
										</div>

										<p id="output_string">...</p>

									</div>
								</div>
							</div>
						</div>
					</div>
					
					
					
					
					
				</div>




				<div class="clear"></div>
				<div class="hrGrey"></div>
				<div class="clear"></div>

				<script type="text/javascript" src="https://www.google.com/jsapi"></script>
				<script type="text/javascript">

				<!-------   /////////////////////////// main ////////////////////// -->
				
  google.load('visualization', '1.0', {'packages':['corechart', 'table', 'gauge', 'controls']});
  google.setOnLoadCallback(apiLoaded);
  function apiLoaded() {
	  document.getElementById("allCharts").style.marginLeft="130px";
    drawMainDashboard();
    drawRegionsMap();
    initialize();
  }

  function drawMainDashboard() {
    var dashboard1 = new google.visualization.Dashboard(
        document.getElementById('dashboard1_div'));

    var dashboard2 = new google.visualization.Dashboard(
            document.getElementById('dashboard2_div'));
    
    var slider1 = new google.visualization.ControlWrapper({
      'controlType': 'NumberRangeFilter',
      'containerId': 'slider1_div',
      'options': {
        'filterColumnIndex': 1,
        'minValue': 0,
    	'maxValue': 2000,
        'ui': {
          'labelStacking': 'vertical',
          'label': 'Employees Filter:'
        }
    	
      }
    });
    var categoryPicker1 = new google.visualization.ControlWrapper({
      'controlType': 'CategoryFilter',
      'containerId': 'categoryPicker1_div',
      'options': {
        'filterColumnIndex': 0,
        'ui': {
          'labelStacking': 'vertical',
          'label': 'Partner Selection:',
          'allowTyping': false,
          'allowMultiple': false
        }
      }
    });
    var pie1 = new google.visualization.ChartWrapper({
      'chartType': 'PieChart',
      'containerId': 'chart1_div',
      'options': {
        'width': 300,
        'height': 300,
        'legend': 'none',
        'chartArea': {'left': 15, 'top': 15, 'right': 0, 'bottom': 0},
        'pieSliceText': 'label'
      },
      'view': {'columns': [0, 1]}
    });
    var table1 = new google.visualization.ChartWrapper({
      'chartType': 'Table',
      'containerId': 'table1_div',
      'options': {
      }
    });

    var slider2 = new google.visualization.ControlWrapper({
        'controlType': 'NumberRangeFilter',
        'containerId': 'slider2_div',
        'options': {
          'filterColumnIndex': 1,
          'ui': {
            'labelStacking': 'vertical',
            'label': 'Employees Filter:'
          }
        }
      });
      var categoryPicker2 = new google.visualization.ControlWrapper({
        'controlType': 'CategoryFilter',
        'containerId': 'categoryPicker2_div',
        'options': {
          'filterColumnIndex': 0,
          'ui': {
            'labelStacking': 'vertical',
            'label': 'Partner Selection:',
            'allowTyping': false,
            'allowMultiple': false
          }
        }
      });
      var pie2 = new google.visualization.ChartWrapper({
        'chartType': 'BarChart',
        'containerId': 'chart2_div',
        'options': {
          'width': 300,
          'height': 300,
          'legend': 'none',
          'chartArea': {'left': 15, 'top': 15, 'right': 0, 'bottom': 0}
         
        },
        'view': {'columns': [0, 1]}
      });
      var table2 = new google.visualization.ChartWrapper({
        'chartType': 'Table',
        'containerId': 'table2_div',
        'options': {
        }
      });



	  var idx = 0;
	  var gnrdata1 = new google.visualization.DataTable();
	  gnrdata1.addColumn('string', 'Partner');
	  gnrdata1.addColumn('number', 'Employees');
    
    <?php
    	 foreach ($tdata as $row){
			if($row[1] > 100) {
    ?>
      gnrdata1.addRows(1);
      gnrdata1.setValue(idx, 0, <?php echo '"' . $row[0] . '"' ?>);
      gnrdata1.setValue(idx, 1, <?php echo $row[1] ?>);
      idx = idx+1;
      
    <?php 
			}
		 }  
    ?>

	  idx = 0;
	  var gnrdata2 = new google.visualization.DataTable();
	  gnrdata2.addColumn('string', 'Partner');
	  gnrdata2.addColumn('number', 'Employees');
    
    <?php
    	 foreach ($tdata as $row){
			if($row[1] > 100) {
    ?>
      gnrdata2.addRows(1);
      gnrdata2.setValue(idx, 0, <?php echo '"' . $row[0] . '"' ?>);
      gnrdata2.setValue(idx, 1, <?php echo $row[1] ?>);
      idx = idx+1;
      
    <?php 
			}
		 }  
    ?>

    <!-------   /////////////////////////// draw dashboard ////////////////////// -->
    
    dashboard1.bind([slider1, categoryPicker1], [pie1, table1]);
    dashboard1.draw(gnrdata1);

    <!-------    dashboard2.bind([slider2, categoryPicker2], [pie2, table2]); -->
    dashboard2.bind([slider2], [pie2]);
    dashboard2.draw(gnrdata2);

  }

  <!-------   /////////////////////////// 2,1 script ////////////////////// -->

  google.load('visualization', '1', {'packages': ['table', 'map', 'corechart']});
 

  function initialize() {
    // The URL of the spreadsheet to source data from.  // 'https://spreadsheets.google.com/pub?key=pCQbetd-CptF0r8qmCOlZGg'); 'file:///C:/Users/rossumg/_tmp/ss.xlsx');
    var query = new google.visualization.Query('https://spreadsheets.google.com/pub?key=pCQbetd-CptF0r8qmCOlZGg');
    query.send(draw);
  }

  function draw(response) {
    if (response.isError()) {
      alert('Error in query');
    }

    var ticketsData = response.getDataTable();
    var chart = new google.visualization.ColumnChart(
        document.getElementById('chart_div'));
    //chart.draw(ticketsData, {'isStacked': true, 'legend': 'bottom', 'vAxis': {'title': 'Number of tickets'}});

    var geoData = google.visualization.arrayToDataTable([
      ['Lat', 'Lon', 'Name', 'Action?'],
      [6.2711, 3.2344, 'Lagos, Nigeria', true],
      [9.1032, 7.1050, 'Abuja Nigeria', true],
      [4.4721, 6.5955, 'Port Harcourt Nigeria', true],
      [6.26, 7.29, 'Enugu Nigeria', false],
     ]);

    var geoView = new google.visualization.DataView(geoData);
    geoView.setColumns([0, 1]);

    var table = new google.visualization.Table(document.getElementById('table_div'));
    table.draw(geoData, {showRowNumber: false});

    var map =
        new google.visualization.Map(document.getElementById('map_div'));
    map.draw(geoView, {showTip: true});

    // Set a 'select' event listener for the table.
    // When the table is selected, we set the selection on the map.
    google.visualization.events.addListener(table, 'select',
        function() {
          map.setSelection(table.getSelection());
        });

    // Set a 'select' event listener for the map.
    // When the map is selected, we set the selection on the table.
    google.visualization.events.addListener(map, 'select',
        function() {
          table.setSelection(map.getSelection());
        });
  }


  <!-------   /////////////////////////// 2,1 end script ////////////////////// -->


  <!-------   /////////////////////////// 2,2 script ////////////////////// -->

	<?php  require_once('views/scripts/dashboard/chart1_script.phtml');?>

  <!-------   /////////////////////////// 2,2 end script ////////////////////// -->
  

  

  function drawExample() {
    var exampleDashboard = new google.visualization.Dashboard(
        document.getElementById('example_dashboard_div'));
    var exampleSlider = new google.visualization.ControlWrapper({
      'controlType': 'NumberRangeFilter',
      'containerId': 'example_slider_div',
      'options': {
        'filterColumnLabel': 'Issues',
        'ui': {'labelStacking': 'vertical'}
      }
    });
    var examplePie = new google.visualization.ChartWrapper({
      'chartType': 'PieChart',
      'containerId': 'example_chart_div',
      'options': {
        'width': 600,
        'height': 300,
        'legend': 'right',
        'chartArea': {'left': 0, 'top': 15, 'right': 0, 'bottom': 0},
        'pieSliceText': 'value'
      }
    });
    var exampleData = google.visualization.arrayToDataTable([
      ['Name', 'Issues'],
      ['Michael' , 5],
      ['Elisa', 7],
      ['Robert', 3],
      ['Jon', 2],
      ['Jessica', 6],
      ['Aaron', 1],
      ['Margareth', 8]
     ]);
    exampleDashboard.bind(exampleSlider, examplePie);
    exampleDashboard.draw(exampleData);
  }
</script>


				<script>
      
      devsite.github.Link.convertAnchors();
      
        window.prettyPrint();
			

  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>

</script>

			</body>

</html>

