<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<style>
#homecontent {
	background: url("images/content-bg.png") repeat-x scroll 0 0 #FAFAFA;
	position: relative;
}

#homecontent-mid {
	background: url("images/bg-stage.png") repeat-y scroll right top #FFFFFF;
	min-height: 100%;
	outline: medium none;
	top: -40px;
}

#homebanner {
	background: url("images/bg-stage-shade.png") repeat-x scroll 0 0
		transparent;
	padding-right: 20px;
	position: relative;
}

.rounded {
	border-radius: 10px 10px 10px 10px;
}

.sliderdiv {
	background: none repeat scroll 0 0 FFFFFF;
	float: left;
}

.main-search {
	background: none repeat scroll 0 0 #FFFFFF;
	float: left;
	overflow: hidden;
}

.nav-buttons {
	background: none repeat scroll 0 0 #FFFFFF;
	float: left;
	overflow: hidden;
}

</style>

<link href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700"
	rel="stylesheet" type="text/css">

<?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>


      <link rel="stylesheet" type="text/css"
	href="https://google-developers.appspot.---com/_static/f7a896e076/css/screen-docs.css" />
<link rel="stylesheet"
	href="//www.google.com/cse/style/look/default.css" type="text/css" />
<link rel="stylesheet"
	href="//fonts.googleapis.com/css?family=Open+Sans:300,400"
	type="text/css">
<script
	src="https://google-developers.appspot.com/_static/f7a896e076/js/prettify-bundle.js"></script>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
<script id="jqueryui"
	src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js"
	defer async></script>
<script
	src="//www.google.com/jsapi?key=AIzaSyCZfHRnq7tigC-COeQRmoa9Cxr0vbrK6xw"></script>
<!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
<script
	src="https://google-developers.appspot.com/_static/f7a896e076/js/framebox.js"></script>

</head>
<body class="yui-skin-sam">

	<div id="pageHolder">

		<div id="header"><?php require_once('views/scripts/header.phtml');?></div>
		<div id="content">

			<!-------   /////////////////////////// get data ////////////////////// -->

			<div>

				<?php  //require_once('views/scripts/dashboard/load_data.phtml');?>



			<!-------   /////////////////////////// make top buttons ////////////////////// -->

			<div class="rightdiv" style="float: right;">
				<?php  require_once('views/scripts/dashboard/top_buttons.phtml');?>
					
			</div>
			
			<!-------   /////////////////////////// make left buttons ////////////////////// -->

			<div class="nav-buttons">
				<?php  require_once('views/scripts/dashboard/left_buttons.phtml');?>
				
			</div>
			
			<!-------   /////////////////////////// load scripts ////////////////////// -->
            <div class="nav-buttons">
				<?php require_once('views/scripts/dashboard/displayScripts.phtml');?>
			</div>

			<!-------   /////////////////////////// charts ////////////////////// -->

			<body class="docs slim framebox_body">

				<div id="allCharts" class="container">
				
				    <div id="toprow" class="container">
						<div id="homecontent" class="container">
							<div id="homecontent-mid" class="row rounded">
								<div id="homebanner" class="rounded">
								<div class="sliderdiv">
								    <div class="hrNav"></div>
									<div id="chart11_div" style="width: 800px; height: 300px;"></div>
									</div>
									<div class="main-search">
									    <div class="hrNav"></div>
										<div id="chart12_div" style="width: 800px; height: 300px;"></div>
									</div>
								</div>
							</div>
						</div>			
					</div>
					
					<!-------   /////////////////////////// chart 2,1 ////////////////////// -->
					
					<div id="bottomrow" class="container">
						<div id="homecontent" class="container">
							<div id="homecontent-mid" class="row rounded">
								<div id="homebanner" class="rounded">
								<div class="sliderdiv">
					                <div class="hrNav"></div>
									<div id="chart13_div" style="width: 500px; height: 300px;"></div>
									</div>
									<div class="main-search">
									    <div class="hrNav"></div>									
										<div id="chart14_div" style="width: 500px; height: 300px;"></div>
									</div>
								</div>
							</div>
						</div>
								<!-------   /////////////////////////// chart 2,2 ////////////////////// -->
								<div class="main-search"></div>
					</div>
				</div>
	</div>

		<div class="hrNav"></div>
		<div class="clear"></div>
		
		<script type="text/javascript" src="https://www.google.com/jsapi"></script>

		<!-------   /////////////////////////// main gnr ////////////////////// -->

		<script type="text/javascript">
		
  google.load('visualization', '1.1', {'packages':['corechart', 'table', 'gauge', 'controls']});
  google.load('visualization', '1.1', {'packages':['bar']});
  google.setOnLoadCallback(apiLoaded);
  function apiLoaded() {
	  document.getElementById("allCharts").style.marginLeft="130px";

	drawChart11();
	drawChart12();
	//drawChart13();
	//drawChart14();
		
  }

  <!-------   /////////////////////////// script 1,1 ////////////////////// -->

//TA:17:17 Coverage Over time LARC chart
  function drawChart11() {
	  
      var chart11Data = google.visualization.arrayToDataTable([
['Month', '% trained and providing LARC', '% trained and stocked out LARC', '% trained in LARC'],

<?php
$start_date = '';
$end_date = '';
for($i=0; $i<count($this->larc_coverage); $i++){
    $row = $this->larc_coverage[$i];
    if($i == 0)
        $start_date = $row[month] . " " . $row[year];
    if($i == count($this->larc_coverage)-1)
        $end_date = $row[month] . " " . $row[year];
  	//foreach ($this->larc_coverage as $row){
  	?>
  	[<?php echo  " '$row[month]'," . round($row[tp_percent],2)*100 . "," . round($row[tso_percent],2)*100 . "," . round($row[tt_percent],2)*100 ?>],
  	<?php
  		}
  	?>

]);		

      <?php echo  " var title_data = 'LARC Coverage, " . $start_date . " to " . $end_date ."' " ?>;

      var chart11Options = {
        title: title_data,
        titleTextStyle: { fontSize: 16 },
        vAxis: {format: '#\'%\''},
      };

      var chart11 = new google.visualization.LineChart(document.getElementById('chart11_div'));

      chart11.draw(chart11Data, chart11Options);
    }

//TA:17:17 Coverage Over time FP chart
  function drawChart12() {
	  
      var chart12Data = google.visualization.arrayToDataTable([
['Month', '% trained and providing FP', '% trained and stocked out FP', '% trained in FP'],

<?php
$start_date = '';
	$end_date = '';
	for($i=0; $i<count($this->fp_coverage); $i++){
		$row = $this->fp_coverage[$i];
		if($i == 0)
			$start_date = $row[month] . " " . $row[year];
		if($i == count($this->fp_coverage)-1)
			$end_date = $row[month] . " " . $row[year];
  		//foreach ($this->larc_coverage as $row){
  	?>
  	[<?php echo  " '$row[month]'," . round($row[tp_percent],2)*100 . "," . round($row[tso_percent],2)*100 . "," . round($row[tt_percent],2)*100 ?>],
  	<?php
  		}
  	?>

]);		

      <?php echo  " var title_data = 'FP Coverage, " . $start_date . " to " . $end_date ."' " ?>;

      var chart12Options = {
        title: title_data,
        titleTextStyle: { fontSize: 16 },
        vAxis: {format: '#\'%\''},
      };

      var chart12 = new google.visualization.LineChart(document.getElementById('chart12_div'));

      chart12.draw(chart12Data, chart12Options);
    }
  
 function drawChart13() {

	 var chart13Data = google.visualization.arrayToDataTable([
['State', 'Percentage', { role: 'style' }],
	                                                           
<?php
		foreach ($this->fp_data as $row){
	?>
	['<?php echo str_replace("'",'', str_replace(' ', '', $row[state]))  ?>', <?php echo $row[percentage]; ?>, <?php echo "'$row[color]'"; ?>],
	<?php
		}
	?>

]);

	  var chart13Options = {
		      title: 'Percent of Facilities Providing LARC',
		      titleTextStyle: { fontSize: 15 },
		     
		      hAxis: {title: 'Percentage'},
		      hAxis: {format: '##.##%'},
		      legend: 'none',
		      is3D:true
		};


	  var chart13 = new google.visualization.BarChart(document.getElementById('chart13_div'));
	            
	  chart13.draw(chart13Data, chart13Options);
	}
    

</script>


<script>
  devsite.github.Link.convertAnchors();
  window.prettyPrint();
</script>	

  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>



</body>

</html>

