<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<style>
#homecontent {
	position: relative;
}

#homecontent-mid {
	min-height: 100%;
	outline: medium none;
	top: -40px;
}

#homebanner {
	padding-right: 20px;
	position: relative;
}

.rounded {
	border-radius: 10px 10px 10px 10px; 
}

.sliderdiv {
	float: left;
}

.main-search {
	float: left;
	overflow: hidden;
}

.nav-buttons {
	float: left;
	overflow: hidden;
}


</style>

<link href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700"
	rel="stylesheet" type="text/css">

<?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>


      <link rel="stylesheet" type="text/css"
	href="https://google-developers.appspot.---com/_static/f7a896e076/css/screen-docs.css" />
<link rel="stylesheet"
	href="//www.google.com/cse/style/look/default.css" type="text/css" />
<link rel="stylesheet"
	href="//fonts.googleapis.com/css?family=Open+Sans:300,400"
	type="text/css">
<script
	src="https://google-developers.appspot.com/_static/f7a896e076/js/prettify-bundle.js"></script>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
<script id="jqueryui"
	src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js"
	defer async></script>
<script
	src="//www.google.com/jsapi?key=AIzaSyCZfHRnq7tigC-COeQRmoa9Cxr0vbrK6xw"></script>
<!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
<script
	src="https://google-developers.appspot.com/_static/f7a896e076/js/framebox.js"></script>

</head>
<body class="yui-skin-sam">

	<div id="pageHolder">

		<div id="header"><?php require_once('views/scripts/header.phtml');?></div>
		<div id="content">

			<!-------   /////////////////////////// get data ////////////////////// -->

			<div>
				<?php  //require_once('views/scripts/dashboard/load_data.phtml');?>
			</div>

			<!-------   /////////////////////////// make top buttons ////////////////////// -->

			<div class="rightdiv" style="float: right;">
				<?php //require_once('views/scripts/dashboard/top_buttons.phtml');?>
			</div>
			<div class="hrNav"></div>

			<!-------   /////////////////////////// make left buttons ////////////////////// -->
			<div class="nav-buttons">
				<?php  require_once('views/scripts/dashboard/left_buttons.phtml');?>
			</div>
			<!-------   /////////////////////////// load scripts ////////////////////// -->
            <div class="nav-buttons">
				<?php require_once('views/scripts/dashboard/displayScripts.phtml');?>
			</div>
			
			<!-------   /////////////////////////// charts ////////////////////// -->

			<body class="docs slim framebox_body">

				<div id="allCharts" class="container">
				
				<div class="hrNav"></div>
				<div class="hrNav"></div>
				
				
				    <div id="toprow" class="container">
						<div id="homecontent" class="container">
							<div id="homecontent-mid" class="row rounded">
								<div id="homebanner" class="rounded">
								<div class="sliderdiv">
								    <div class="hrNav"></div>
									<div id="chart11_div" style="width: 1000px; height: 800px;"></div>
									</div>
									<div class="main-search">
									    <div class="hrNav"></div>
										<div id="chart12_div" style="width: 500px; height: 300px;"></div>
									</div>
								</div>
							</div>
						</div>			
					</div>
					
					<!-------   /////////////////////////// chart 2,1 ////////////////////// -->
					
					<div id="bottomrow" class="container">
						<div id="homecontent" class="container">
							<div id="homecontent-mid" class="row rounded">
								<div id="homebanner" class="rounded">
								<div class="sliderdiv">
					                <div class="hrNav"></div>
									<div id="chart13_div" style="width: 1000px; height: 800px;"></div>
									</div>
									<div class="main-search">
									    <div class="hrNav"></div>									
										<div id="chart14_div" style="width: 500px; height: 300px;"></div>
									</div>
								</div>
							</div>
						</div>
								<!-------   /////////////////////////// chart 2,2 ////////////////////// -->
								<div class="main-search"></div>
					</div>
					
				</div>
				
				
	</div>

		<div class="hrNav"></div>
		<div class="clear"></div>
		
		<script type="text/javascript" src="https://www.google.com/jsapi"></script>

		<!-------   /////////////////////////// main gnr ////////////////////// -->

		<script type="text/javascript">
		
  google.load('visualization', '1.1', {'packages':['corechart', 'table', 'gauge', 'controls']});
  google.load('visualization', '1.1', {'packages':['bar']});
  google.setOnLoadCallback(apiLoaded);
  function apiLoaded() {
	  document.getElementById("allCharts").style.marginLeft="130px";

	drawChart11();
	//drawChart12();
	//drawChart13();
	//drawChart14();
		
	var currentLevel;
	currentLevel = <?php echo '\'' . $this->location_data[0][name] . '\''; ?>;

<?php  //file_put_contents('c:\wamp\logs\php_debug.log', 'dash3 193 >'.PHP_EOL, FILE_APPEND | LOCK_EX);	ob_start();
	   //var_dump("latest_consumption_data=", $this->latest_consumption_data,"END");
	   //var_dump("facility_data=",$this->facility_data[0],"END");
	   //$result = ob_get_clean(); file_put_contents('c:\wamp\logs\php_debug.log', $result .PHP_EOL, FILE_APPEND | LOCK_EX); 
?>
		 
  }

  <!-------   /////////////////////////// script 1,1 ////////////////////// -->
  


  function drawChart11() {
	  
      var chart11Data = google.visualization.arrayToDataTable([
['Month', 'Condoms distributed (sachet) - female', 'Condoms distributed (sachet) - male', 'Family Planning Injections', 'Implant', 'IUCD inserted', 'Oral pill cycle (packets)', 'Sterilization Total'],

<?php
  		foreach ($this->average_monthly_consumption_by_geo as $row){
  	?>
  	[<?php echo  " '$row[month]',$row[consumption1],$row[consumption2],$row[consumption3],$row[consumption4],$row[consumption5],$row[consumption6],$row[consumption7] "; ?>],
  	<?php
  		}
  	?>

]);		    

	  <?php echo  " var title_date = 'Commodity Consumption $title->method $this->title_date ' " ?>;

      var chart11Options = {
        title: title_date,
        titleTextStyle: { fontSize: 16 },
        vAxis: {logScale:true},  //TA:17:17 Commodity Consumption All chart
       
      };

      var chart11 = new google.visualization.LineChart(document.getElementById('chart11_div'));

      chart11.draw(chart11Data, chart11Options);
    }

  function drawChart12() {
      var chart12Data = google.visualization.arrayToDataTable([
['', ''],


<?php
  		foreach ($this->consumption_by_geo as $row){
  	?>
  	[<?php echo  " '$row[location]',$row[consumption] "; ?>],
  	<?php
  		}
  	?>

]);		    

	  <?php echo  " var title_date = 'Monthly consumption of $title->method $this->title_date ' " ?>;

      var chart12Options = {
    	      
    		  title: title_date,
    		  titleTextStyle: { fontSize: 16 },
    		  is3D:true,
		      legend: 'none',
    		  
      };

      //var chart12 = new google.charts.Bar(document.getElementById('chart11_div'));
      var chart12 = new google.visualization.ColumnChart(document.getElementById('chart12_div'));

      chart12.draw(chart12Data, chart12Options);
    }

  
  function drawChart13() {
	  
      var chart13Data = google.visualization.arrayToDataTable([
['Month', 'Condoms distributed (sachet) - female', 'Condoms distributed (sachet) - male', 'Family Planning Injections', 'Implant', 'IUCD inserted', 'Oral pill cycle (packets)', 'Sterilization Total'],

<?php
  		foreach ($this->average_monthly_consumption_by_geo as $row){
  	?>
  	[<?php echo  " '$row[month]',$row[consumption1],$row[consumption2],$row[consumption3],$row[consumption4],$row[consumption5],$row[consumption6],$row[consumption7] "; ?>],
  	<?php
  		}
  	?>

]);		    

	  <?php echo  " var title_date = 'Commodity Consumption $title->method $this->title_date ' " ?>;

      var chart13Options = {
        title: title_date,
        titleTextStyle: { fontSize: 16 },
        vAxis: {logScale:true},  //TA:17:17 Commodity Consumption All chart
      };

      var chart13 = new google.visualization.LineChart(document.getElementById('chart13_div'));

      chart13.draw(chart13Data, chart13Options);
    }
  
  function drawChart14() {
	  
      var chart14Data = google.visualization.arrayToDataTable([
['Month', 'Implants', 'Commodities for 7 days'],

<?php
  		foreach ($this->average_monthly_consumption_by_geo as $row){
  	?>
  	[<?php echo  " '$row[location]',$row[consumption] "; ?>],
  	<?php
  		}
  	?>

]);		    

	  <?php echo  " var title_date = 'Consumption of $title->method $this->title_date ' " ?>;
      
      var chart14Options = {
        title: title_data,
        titleTextStyle: { fontSize: 16 },
        vAxis: {format:'#%'},
      };

      var chart14 = new google.visualization.LineChart(document.getElementById('chart14_div'));

      chart14.draw(chart14Data, chart14Options);

    }

  <!-------   /////////////////////////// 2,1 script gnr  ////////////////////// -->

	

  <!-------   /////////////////////////// 2,1 end script ////////////////////// -->


  <!-------   /////////////////////////// 2,2 script ////////////////////// -->

	


  <!-------   /////////////////////////// 2,2 end script ////////////////////// -->
  

  

</script>


<script>
  devsite.github.Link.convertAnchors();
  window.prettyPrint();
</script>	

  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>



</body>

</html>

