<html>
	<head>
		<title><?php echo $this->escape($this->title);?></title>
		<link href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet" type="text/css">
	<?php
	require_once('views/helpers/ScriptContainer.php');
	print ScriptContainer::$instance->renderCSSHead();
	print ScriptContainer::$instance->renderJSHead();	 ?>
	
	
		<script type="text/javascript" charset="utf-8">
			$(document).ready(function() {
				/* Add a click handler to the rows - this could be used as a callback */
				$(".tablegrid tbody").click(function(event) {
					$(oTable.fnSettings().aoData).each(function (){
						$(this.nTr).removeClass('row_selected');
					});
					$(event.target.parentNode).addClass('row_selected');
				});
	
				/* Add a click handler for the delete row */
				$('#delete').click( function() {
					var anSelected = fnGetSelected( oTable );
					oTable.fnDeleteRow( anSelected[0] );
				} );
	
				/* Init the table */
				oTable = $('.tablegrid').dataTable({
					"bJQueryUI": true,
					"sPaginationType": "full_numbers",
					"bSort": false
				});
			} );

			/* Get the rows which are currently selected */
			function fnGetSelected( oTableLocal ){
				var aReturn = new Array();
				var aTrs = oTableLocal.fnGetNodes();
				
				for ( var i=0 ; i<aTrs.length ; i++ ){
					if ( $(aTrs[i]).hasClass('row_selected') ){
						aReturn.push( aTrs[i] );
					}
				}
				return aReturn;
			}
		</script>
	</head>
	
	
	<body  class="yui-skin-sam">
		<div id="pageHolder">
			<div id="header"><?php require_once('views/scripts/preheader.phtml');?></div>
			<div id="content">
			<div id="headerpad">&nbsp;</div>
			<div id="subcontent">
				<div id="contentheader">
					<h2><?php echo t("Welcome to").space.$this->translation['Application Name']; ?></h2><br>
					<p style="float:left;font-size:13px;"><?php echo t("Training System Monitoring and Reporting Tool"); ?></p>
				</div>
				<div class="pad50 clear"></div>

				<div style="width:100%;">
				<table cellpadding="0" cellspacing="0" border="0" class="display tablegrid" id="" style="width:100%">
					<thead>
						<tr>
							<th><?php echo t("Training institution"); ?></th>
							<th width="135"><?php echo t("# of students"); ?></th>
							<th width="135"><?php echo t("# of tutors"); ?></th>
							<th width="180"><?php echo t("Student/Tutor Ratio"); ?></th>
							<th width="120"><?php echo t("# of grads"); ?></th>
							<th width="170"><?php echo t("Early terminations"); ?></th>
						</tr>
					</thead>
					<tbody>
<?php
	foreach ($this->getins as $getresult){
?>
						<tr style="cursor : pointer;" class="GradeA" onclick="location='<?php echo $getresult['link'];?>'">
				   			<td<?php echo ($getresult['type'] == 2 ? " style=\"padding-left : 50px;\"" : "") ?>><?php echo $getresult['col1'];?></td>
							<td class=""><?php echo $getresult['col2'];?></td>
							<td class=""><?php echo $getresult['col3'];?></td>
							<td class=""><?php echo $getresult['col4'];?></td>
							<td class=""><?php echo $getresult['col5'];?></td>
							<td class=""><?php echo $getresult['col6'];?></td>
						</tr>
<?php
	}
?>
					</tbody>
				</table>
				</div>
				<div style="line-height:50px;">&nbsp;</div>

				<div class="rightdiv" style="float:right;">
					<a href="<?php  echo Settings::$COUNTRY_BASE_URL.'/institution/institution'; ?>" class="tsbutton green large"><?php echo t('Institutions'); ?> &raquo;</a>
					<a href="<?php  echo Settings::$COUNTRY_BASE_URL.'/cohort/cohortsearch'; ?>" class="tsbutton green large"><?php echo t('Cohorts'); ?> &raquo;</a>
					<a href="<?php  echo Settings::$COUNTRY_BASE_URL.'/people/people'; ?>" class="tsbutton green large"><?php echo t('People'); ?> &raquo;</a>
					<a href="<?php  echo Settings::$COUNTRY_BASE_URL.'/facility/search'; ?>" class="tsbutton green large"><?php echo t('Facilities'); ?> &raquo;</a>
					<a href="<?php  echo Settings::$COUNTRY_BASE_URL.'/Reportpreservice/studentname'; ?>" class="tsbutton green large"><?php echo t('Reports'); ?> &raquo;</a>
				</div>

			</div>
		</div>
		<div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
		</div>
	</body>
</html>