<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<style>
#homecontent {
	background: url("images/content-bg.png") repeat-x scroll 0 0 #FAFAFA;
	position: relative;
}

#homecontent-mid {
	background: url("images/bg-stage.png") repeat-y scroll right top #FFFFFF;
	border: 1px solid #BDBCBD;
	min-height: 100%;
	outline: medium none;
	top: -40px;
}

#homebanner {
	background: url("images/bg-stage-shade.png") repeat-x scroll 0 0
		transparent;
	padding-right: 20px;
	position: relative;
}

.rounded {
	border-radius: 10px 10px 10px 10px;
}

.sliderdiv {
	background: none repeat scroll 0 0 FFFFFF;
	float: left;
}

.main-search {
	background: none repeat scroll 0 0 #FFFFFF;
	float: left;
	overflow: hidden;
}

.nav-buttons {
	background: none repeat scroll 0 0 #FFFFFF;
	float: left;
	overflow: hidden;
}
</style>

<link href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700"
	rel="stylesheet" type="text/css">

<?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>


      <link rel="stylesheet" type="text/css"
		href="https://google-developers.appspot.---com/_static/f7a896e076/css/screen-docs.css" />
	<link rel="stylesheet"
		href="//www.google.com/cse/style/look/default.css" type="text/css" />
	<link rel="stylesheet"
		href="//fonts.googleapis.com/css?family=Open+Sans:300,400"
		type="text/css">
		<script
			src="https://google-developers.appspot.com/_static/f7a896e076/js/prettify-bundle.js"></script>

		<script
			src="//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
		<script id="jqueryui"
			src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js"
			defer async></script>
		<script
			src="//www.google.com/jsapi?key=AIzaSyCZfHRnq7tigC-COeQRmoa9Cxr0vbrK6xw"></script>
		<!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
		<script
			src="https://google-developers.appspot.com/_static/f7a896e076/js/framebox.js"></script>

</head>
<body class="yui-skin-sam">

	<div id="pageHolder">

		<div id="header"><?php require_once('views/scripts/header.phtml');?></div>
		<div id="content">

			<!-------   /////////////////////////// get data ////////////////////// -->

			<div>	
			
			<script src="http://code.highcharts.com/highcharts.js"></script>
<script src="http://code.highcharts.com/modules/data.js"></script>
<script src="http://code.highcharts.com/modules/drilldown.js"></script>



<!-- Data from www.netmarketshare.com. Select Browsers => Desktop share by version. Download as tsv. -->
<pre id="tsv" style="display:none">Browser Version	Total Market Share
Microsoft Internet Explorer 8.0	26.61%
Microsoft Internet Explorer 9.0	16.96%
Chrome 18.0	8.01%
Chrome 19.0	7.73%
Firefox 12	6.72%
Microsoft Internet Explorer 6.0	6.40%
Firefox 11	4.72%
Microsoft Internet Explorer 7.0	3.55%
Safari 5.1	3.53%
Firefox 13	2.16%
Firefox 3.6	1.87%
Opera 11.x	1.30%
Chrome 17.0	1.13%
Firefox 10	0.90%
Safari 5.0	0.85%
Firefox 9.0	0.65%
Firefox 8.0	0.55%
Firefox 4.0	0.50%
Chrome 16.0	0.45%
Firefox 3.0	0.36%
Firefox 3.5	0.36%
Firefox 6.0	0.32%
Firefox 5.0	0.31%
Firefox 7.0	0.29%
Proprietary or Undetectable	0.29%
Chrome 18.0 - Maxthon Edition	0.26%
Chrome 14.0	0.25%
Chrome 20.0	0.24%
Chrome 15.0	0.18%
Chrome 12.0	0.16%
Opera 12.x	0.15%
Safari 4.0	0.14%
Chrome 13.0	0.13%
Safari 4.1	0.12%
Chrome 11.0	0.10%
Firefox 14	0.10%
Firefox 2.0	0.09%
Chrome 10.0	0.09%
Opera 10.x	0.09%
Microsoft Internet Explorer 8.0 - Tencent Traveler Edition	0.09%</pre>
			
					
<?php
    $idx = 0;
    $tdata = array();
    
	foreach ($this->getins as $getresult){
?>

<?php 
 $tdata[$idx] = array($getresult['col1'], $getresult['col2']);
 $idx = $idx+1;
?>

<?php
	}
?>

</div>

			<!-------   /////////////////////////// make top buttons ////////////////////// -->

			<div class="rightdiv" style="float: right;">
				<?php  require_once('views/scripts/dashboard/top_buttons.phtml');?>
			</div>

			<div class="clear"></div>
			<div class="hrGrey"></div>
			<div class="clear"></div>

			<!-------   /////////////////////////// make left buttons ////////////////////// -->

			<div class="nav-buttons">
				<?php  require_once('views/scripts/dashboard/left_buttons.phtml');?>
			</div>

			<!-------   /////////////////////////// charts ////////////////////// -->


<body class="docs slim framebox_body">

	<div id="allCharts" class="container">

		<div id="toprow" class="container">

			<div id="homecontent" class="container">
				<div id="homecontent-mid" class="row rounded">
					<div id="homebanner" class="rounded">

						<!-------   /////////////////////////// chart 1,1 ////////////////////// -->

						<div class="sliderdiv">

							<div id="dashboard1_div"
								style="border: 1px solid #ccc; margin-top: 1em">
								<p style="padding-left: 1em">
									<strong>1,1</strong>
								</p>
								<table class="columns">
									<tr>
										<td>
											<div id="slider1_div" style="padding-left: 15px"></div>
										</td>
										<td>
											<div id="categoryPicker1_div"></div>
										</td>
									</tr>
									<tr>
										<td>
											<div id="chart1_div" style="padding-top: 15px"></div>
										</td>
										<td>
											<div id="table1_div" style="padding-top: 30px"></div>
										</td>
									</tr>
								</table>
							</div>

						</div>

						<!-------   /////////////////////////// chart 1,2 ////////////////////// -->
						
						<div class="main-search">


							<div id="dashboard2_div"
								style="border: 1px solid #ccc; margin-top: 1em">
								<p style="padding-left: 1em">
									<strong>1,2</strong>
								</p>
								<table class="columns">
									<tr>
										<td>
											<div id="slider2_div" style="padding-left: 15px"></div>
										</td>
										<td>
											<div id="categoryPicker2_div"></div>
										</td>
									</tr>
									<tr>
										<td>
											<div id="chart2_div" style="padding-top: 15px"></div>
										</td>
										<td>
											<div id="table2_div" style="padding-top: 30px"></div>
										</td>
									</tr>
								</table>
							</div>
						</div>
					</div>
				</div>
			</div>

		</div>


		<div class="clear"></div>
		<div class="hrGrey"></div>
		<div class="clear"></div>


		<div id="bottomrow" class="container">


			<div id="homecontent" class="container">
				<div id="homecontent-mid" class="row rounded">
					<div id="homebanner" class="rounded">
					
						<!-------   /////////////////////////// chart 2,1 ////////////////////// -->
						2,1
					
					
					<div id="highChart_div" style="min-width: 210px; height: 300px; margin: 0 auto"></div>
						

						<!-------   /////////////////////////// chart 2,2 ////////////////////// -->
						2,2
						<div class="main-search">
							
							
							

						</div>
					</div>
				</div>
			</div>


		</div>

	</div>




				<div class="clear"></div>
				<div class="hrGrey"></div>
				<div class="clear"></div>

				<script type="text/javascript" src="https://www.google.com/jsapi"></script>

	<!-------   /////////////////////////// main ////////////////////// -->				

				<script type="text/javascript">
  google.load('visualization', '1.0', {'packages':['corechart', 'table', 'gauge', 'controls']});
  google.setOnLoadCallback(apiLoaded);
  function apiLoaded() {
	  document.getElementById("allCharts").style.marginLeft="130px";
    drawMainDashboard();
    drawHighchart();
   
  }

  function drawMainDashboard() {
    var dashboard1 = new google.visualization.Dashboard(
        document.getElementById('dashboard1_div'));

    var dashboard2 = new google.visualization.Dashboard(
            document.getElementById('dashboard2_div'));
    
    var slider1 = new google.visualization.ControlWrapper({
      'controlType': 'NumberRangeFilter',
      'containerId': 'slider1_div',
      'options': {
        'filterColumnIndex': 1,
        'ui': {
          'labelStacking': 'vertical',
          'label': 'Employees Filter:'
        }
      }
    });
    var categoryPicker1 = new google.visualization.ControlWrapper({
      'controlType': 'CategoryFilter',
      'containerId': 'categoryPicker1_div',
      'options': {
        'filterColumnIndex': 0,
        'ui': {
          'labelStacking': 'vertical',
          'label': 'Partner Selection:',
          'allowTyping': false,
          'allowMultiple': false
        }
      }
    });
    var pie1 = new google.visualization.ChartWrapper({
      'chartType': 'PieChart',
      'containerId': 'chart1_div',
      'options': {
        'width': 300,
        'height': 300,
        'legend': 'none',
        'chartArea': {'left': 15, 'top': 15, 'right': 0, 'bottom': 0},
        'pieSliceText': 'label'
      },
      'view': {'columns': [0, 1]}
    });
    var table1 = new google.visualization.ChartWrapper({
      'chartType': 'Table',
      'containerId': 'table1_div',
      'options': {
      }
    });

    var slider2 = new google.visualization.ControlWrapper({
        'controlType': 'NumberRangeFilter',
        'containerId': 'slider2_div',
        'options': {
          'filterColumnIndex': 1,
          'ui': {
            'labelStacking': 'vertical',
            'label': 'Employees Filter:'
          }
        }
      });
      var categoryPicker2 = new google.visualization.ControlWrapper({
        'controlType': 'CategoryFilter',
        'containerId': 'categoryPicker2_div',
        'options': {
          'filterColumnIndex': 0,
          'ui': {
            'labelStacking': 'vertical',
            'label': 'Partner Selection:',
            'allowTyping': false,
            'allowMultiple': false
          }
        }
      });
      var pie2 = new google.visualization.ChartWrapper({
        'chartType': 'BarChart',
        'containerId': 'chart2_div',
        'options': {
          'width': 300,
          'height': 300,
          'legend': 'none',
          'chartArea': {'left': 15, 'top': 15, 'right': 0, 'bottom': 0}
         
        },
        'view': {'columns': [0, 1]}
      });
      var table2 = new google.visualization.ChartWrapper({
        'chartType': 'Table',
        'containerId': 'table2_div',
        'options': {
        }
      });



	  var idx = 0;
	  var gnrdata1 = new google.visualization.DataTable();
	  gnrdata1.addColumn('string', 'Partner');
	  gnrdata1.addColumn('number', 'Employees');
    
    <?php
    	 foreach ($tdata as $row){
			if($row[1] > 100) {
    ?>
      gnrdata1.addRows(1);
      gnrdata1.setValue(idx, 0, <?php echo '"' . $row[0] . '"' ?>);
      gnrdata1.setValue(idx, 1, <?php echo $row[1] ?>);
      idx = idx+1;
      
    <?php 
			}
		 }  
    ?>

	  idx = 0;
	  var gnrdata2 = new google.visualization.DataTable();
	  gnrdata2.addColumn('string', 'Partner');
	  gnrdata2.addColumn('number', 'Employees');
    
    <?php
    	 foreach ($tdata as $row){
			if($row[1] > 100) {
    ?>
      gnrdata2.addRows(1);
      gnrdata2.setValue(idx, 0, <?php echo '"' . $row[0] . '"' ?>);
      gnrdata2.setValue(idx, 1, <?php echo $row[1] ?>);
      idx = idx+1;
      
    <?php 
			}
		 }  
    ?>

    <!-------   /////////////////////////// draw dashboard ////////////////////// -->
    
    dashboard1.bind([slider1, categoryPicker1], [pie1, table1]);
    dashboard1.draw(gnrdata1);

    <!-------    dashboard2.bind([slider2, categoryPicker2], [pie2, table2]); -->
    dashboard2.bind([slider2], [pie2]);
    dashboard2.draw(gnrdata2);

  }

  <!-------   /////////////////////////// 2,1 script ////////////////////// -->

	function drawHighchart() {

	    Highcharts.data({
	        csv: document.getElementById('tsv').innerHTML,
	        itemDelimiter: '\t',
	        parsed: function (columns) {

	            var brands = {},
	                brandsData = [],
	                versions = {},
	                drilldownSeries = [];

	            // Parse percentage strings
	            columns[1] = $.map(columns[1], function (value) {
	                if (value.indexOf('%') === value.length - 1) {
	                    value = parseFloat(value);
	                }
	                return value;
	            });

	            $.each(columns[0], function (i, name) {
	                var brand,
	                    version;

	                if (i > 0) {

	                    // Remove special edition notes
	                    name = name.split(' -')[0];

	                    // Split into brand and version
	                    version = name.match(/([0-9]+[\.0-9x]*)/);
	                    if (version) {
	                        version = version[0];
	                    }
	                    brand = name.replace(version, '');

	                    // Create the main data
	                    if (!brands[brand]) {
	                        brands[brand] = columns[1][i];
	                    } else {
	                        brands[brand] += columns[1][i];
	                    }

	                    // Create the version data
	                    if (version !== null) {
	                        if (!versions[brand]) {
	                            versions[brand] = [];
	                        }
	                        versions[brand].push(['v' + version, columns[1][i]]);
	                    }
	                }

	            });

	            $.each(brands, function (name, y) {
	                brandsData.push({
	                    name: name,
	                    y: y,
	                    drilldown: versions[name] ? name : null
	                });
	            });
	            $.each(versions, function (key, value) {
	                drilldownSeries.push({
	                    name: key,
	                    id: key,
	                    data: value
	                });
	            });

	            // Create the chart
	            // get highChart container and insert into next statement
	            $(document.getElementById('highChart_div')).highcharts({
	                chart: {
	                    type: 'pie'
	                },
	                title: {
	                    text: 'Browser market shares. November, 2013.'
	                },
	             
	                plotOptions: {
	                    series: {
	                        dataLabels: {
	                            enabled: true,
	                            format: '{point.name}: {point.y:.1f}%'
	                        }
	                    }
	                },

	                tooltip: {
	                    headerFormat: '<span style="font-size:11px">{series.name}</span><br>',
	                    pointFormat: '<span style="color:{point.color}">{point.name}</span>: <b>{point.y:.2f}%</b> of total<br/>'
	                },

	                series: [{
	                    name: 'Brands',
	                    colorByPoint: true,
	                    data: brandsData
	                }],
	                drilldown: {
	                    series: drilldownSeries
	                }
	            });
	        }
	    });
	};
  


  <!-------   /////////////////////////// 2,1 end script ////////////////////// -->


  <!-------   /////////////////////////// 2,2 script ////////////////////// -->

	


  <!-------   /////////////////////////// 2,2 end script ////////////////////// -->
  

  

  function drawExample() {
    var exampleDashboard = new google.visualization.Dashboard(
        document.getElementById('example_dashboard_div'));
    var exampleSlider = new google.visualization.ControlWrapper({
      'controlType': 'NumberRangeFilter',
      'containerId': 'example_slider_div',
      'options': {
        'filterColumnLabel': 'Issues',
        'ui': {'labelStacking': 'vertical'}
      }
    });
    var examplePie = new google.visualization.ChartWrapper({
      'chartType': 'PieChart',
      'containerId': 'example_chart_div',
      'options': {
        'width': 600,
        'height': 300,
        'legend': 'right',
        'chartArea': {'left': 0, 'top': 15, 'right': 0, 'bottom': 0},
        'pieSliceText': 'value'
      }
    });
    var exampleData = google.visualization.arrayToDataTable([
      ['Name', 'Issues'],
      ['Michael' , 5],
      ['Elisa', 7],
      ['Robert', 3],
      ['Jon', 2],
      ['Jessica', 6],
      ['Aaron', 1],
      ['Margareth', 8]
     ]);
    exampleDashboard.bind(exampleSlider, examplePie);
    exampleDashboard.draw(exampleData);
  }
</script>


				<script>
      
      devsite.github.Link.convertAnchors();
      
        window.prettyPrint();
			

  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>

</script>

			</body>

</html>

