<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<style>
#homecontent {
	background: url("images/content-bg.png") repeat-x scroll 0 0 #FAFAFA;
	position: relative;
}

#homecontent-mid {
	background: url("images/bg-stage.png") repeat-y scroll right top #FFFFFF;
	border: 1px solid #BDBCBD;
	min-height: 100%;
	outline: medium none;
	top: -40px;
}

#homebanner {
	background: url("images/bg-stage-shade.png") repeat-x scroll 0 0
		transparent;
	padding-right: 20px;
	position: relative;
}

.rounded {
	border-radius: 10px 10px 10px 10px;
}

.sliderdiv {
	background: none repeat scroll 0 0 FFFFFF;
	float: left;
}

.main-search {
	background: none repeat scroll 0 0 #FFFFFF;
	float: left;
	overflow: hidden;
}

.nav-buttons {
	background: none repeat scroll 0 0 #FFFFFF;
	float: left;
	overflow: hidden;
}

</style>

<link href="//fonts.googleapis.com/css?family=Droid+Sans:400,700"
	rel="stylesheet" type="text/css">

<?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>


      <link rel="stylesheet" type="text/css"
	href="https://google-developers.appspot.---com/_static/f7a896e076/css/screen-docs.css" />
<link rel="stylesheet"
	href="//www.google.com/cse/style/look/default.css" type="text/css" />
<link rel="stylesheet"
	href="//fonts.googleapis.com/css?family=Open+Sans:300,400"
	type="text/css">
<script
	src="https://google-developers.appspot.com/_static/f7a896e076/js/prettify-bundle.js"></script>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
<script id="jqueryui"
	src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js"
	defer async></script>
<script
	src="//www.google.com/jsapi?key=AIzaSyCZfHRnq7tigC-COeQRmoa9Cxr0vbrK6xw"></script>
<!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
<script
	src="https://google-developers.appspot.com/_static/f7a896e076/js/framebox.js"></script>

</head>
<body class="yui-skin-sam">

	<div id="pageHolder">

		<div id="header"><?php require_once('views/scripts/header.phtml');?></div>
		<div id="content">

			<!-------   /////////////////////////// get data ////////////////////// -->

			<div>

				<?php  //require_once('views/scripts/dashboard/load_data.phtml');?>



			<!-------   /////////////////////////// make top buttons ////////////////////// -->

			<div class="rightdiv" style="float: right;">
				<?php  require_once('views/scripts/dashboard/top_buttons.phtml');?>
					
			</div>

			<div class="clear"></div>
			<div class="hrGrey"></div>
			<div class="clear"></div>
			


			<!-------   /////////////////////////// make left buttons ////////////////////// -->

			<div class="nav-buttons">
				<?php  require_once('views/scripts/dashboard/left_buttons.phtml');?>
				
			</div>

			<!-------   /////////////////////////// charts ////////////////////// -->
            

			<body class="docs slim framebox_body">

				<div id="allCharts" class="container">
				
				<label><?php echo t('National Contraceptive Prevalence Rate'); ?></label>
			    <input readonly type="text" name="national_contraceptive_prevalence_rate" value="50">
				
				<div id="toprow" class="container">
						<div id="homecontent" class="container">
							<div id="homecontent-mid" class="row rounded">
								<div id="homebanner" class="rounded">
								
								
			                    
								<div class="sliderdiv">
									<div id="chart11_div" style="width: 500px; height: 300px;"></div>
									</div>
									<div class="main-search">
										<div id="chart12_div" style="width: 500px; height: 300px;"></div>
									</div>
								</div>
							</div>
						</div>			
					</div>
								<!-------   /////////////////////////// chart 2,1 ////////////////////// -->
					<div id="bottomrow" class="container">
						<div id="homecontent" class="container">
							<div id="homecontent-mid" class="row rounded">
								<div id="homebanner" class="rounded">
								<div class="sliderdiv">
									<div id="chart13_div" style="width: 500px; height: 300px;"></div>
									
									</div>
									<div class="main-search">
										<div id="chart14_div" style="width: 500px; height: 300px;"></div>
									</div>
								</div>
							</div>
						</div>
								<!-------   /////////////////////////// chart 2,2 ////////////////////// -->
								<div class="main-search"></div>
					</div>
				</div>
	</div>

		<div class="clear"></div>
		<div class="hrGrey"></div>
		<div class="clear"></div>
		
		<script type="text/javascript" src="https://www.google.com/jsapi"></script>

		<!-------   /////////////////////////// main gnr ////////////////////// -->

		<script type="text/javascript">
		
  google.load('visualization', '1.1', {'packages':['corechart', 'table', 'gauge', 'controls']});
  google.load('visualization', '1.1', {'packages':['bar']});
  google.setOnLoadCallback(apiLoaded);
  function apiLoaded() {
	  document.getElementById("allCharts").style.marginLeft="130px";

	drawChart11();
	drawChart12();
	drawChart13();
	drawChart14();
		
	var currentLevel;
	currentLevel = <?php echo '\'' . $this->location_data[0][name] . '\''; ?>;

  }

  <!-------   /////////////////////////// script 1,1 ////////////////////// -->
  


  function drawChart11() {
	  // Create and populate the data table.
	  var chart11Data = google.visualization.arrayToDataTable([


['', ''],

['Female Condoms', 40000],
['Male Condoms', 98000],
['Injectables', 44000],
['Implants', 21000],
['IUDs', 10000],
['Oral Pills', 79000],
['Sterilization', 6000],


]);		    

	  <?php echo  " var title_data = 'Average Monthly Consumption (AMC) by Method as of $this->title_data ' " ?>;
	  
	  var chart11Options = {
			  
			  title: title_data,
			  titleTextStyle: { fontSize: 15 },
		      is3D:true,
		      legend: 'none',
		      
		};

	  var chart11 = new google.visualization.ColumnChart(document.getElementById('chart11_div'));
	  chart11.draw(chart11Data, chart11Options);
	}

  function drawChart12() {
      var chart12Data = google.visualization.arrayToDataTable([
        [' ', '% of Facilities with trained HWs', '% of facilities with (FP/LARC) trained HWS providing (FP/LARC)', '$ of facilities with trained HWs (FP/LARC) that are stocked out of (FP/LARC)'],

    	  [ 'FP', .8,.52,.12 ],
    	  [ 'LARC', .33,.58,.13 ],
    	  	    	
    	  	        
      ]);

      var chart12Options = {
    		  title: 'Integrated Indicators',
    		  titleTextStyle: { fontSize: 15 },
    		  bar: {groupWidth: "80%"},
    		  vAxis: {format: '#%'},
    		  
      };

      //var chart12 = new google.charts.Bar(document.getElementById('chart11_div'));
      var chart12 = new google.visualization.ColumnChart(document.getElementById('chart12_div'));

      chart12.draw(chart12Data, chart12Options);
    }

  function drawChart13() {
	  
      var chart13Data = google.visualization.arrayToDataTable([
['Month', 'FP', 'LARC'],

[ 'April',.21,.52 ],
[ 'May',.23,.60 ],
[ 'June',.30,.65 ],
[ 'July',.35,.67 ],
[ 'August',.38,.70 ],
[ 'September',.40,.73 ],
[ 'October',.44,.74 ],

      ]);

      var chart13Options = {
        title: '% of Facilities Providing FP and LARC Over Time',
        titleTextStyle: { fontSize: 15 },
        vAxis: {format:'#%'},
      };

      var chart13 = new google.visualization.LineChart(document.getElementById('chart13_div'));

      chart13.draw(chart13Data, chart13Options);
    }
  
  function drawChart14() {
	  
      var chart14Data = google.visualization.arrayToDataTable([
['Month', 'Implants', 'Commodities for 7 days'],

[ 'April',.12,.18 ],
[ 'May',.15,.32 ],
[ 'June',.18,.36 ],
[ 'July',.20,.20 ],
[ 'August',.17,.02 ],
[ 'September',.20,.28 ],
[ 'October',.30,.13 ],
      ]);

      <?php echo  " var title_data = 'Stock outs by Method as of $this->title_data ' " ?>;
      var chart14Options = {
        title: title_data,
        titleTextStyle: { fontSize: 15 },
        vAxis: {format:'#%'},
      };

      var chart14 = new google.visualization.LineChart(document.getElementById('chart14_div'));

      chart14.draw(chart14Data, chart14Options);

    }

  <!-------   /////////////////////////// 2,1 script gnr  ////////////////////// -->

	

  <!-------   /////////////////////////// 2,1 end script ////////////////////// -->


  <!-------   /////////////////////////// 2,2 script ////////////////////// -->

	


  <!-------   /////////////////////////// 2,2 end script ////////////////////// -->
  

  

</script>


<script>
  devsite.github.Link.convertAnchors();
  window.prettyPrint();
</script>	

  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>



</body>

</html>

