<div class="hrNav"></div>
<div class="hrNav"></div>
					                   <a	
                    href="<?php  echo Settings::$COUNTRY_BASE_URL.'/index/index'; ?>"
					id=home name=home class="dbbutton dbbutton_leftmenu"><?php tp('Home'); ?></a>
    				<div class="hrNav"></div>
    				
				                       <a	
					id=coverage coverage class="dbbutton dbbutton_leftmenu"><?php tp('Coverage'); ?></a>
					<div class="hrNav"></div>
					
					<p0>
					
					<!-- 
									   <a	
                    href="<?php  echo Settings::$COUNTRY_BASE_URL.'/dashboard/dash5b'; ?>"
					id=btn1a class="dbbutton dbbutton_leftsubmenu"><?php tp('AMC'); ?></a>
    				<div class="hrNav"></div>
    				-->
					                   <a	
                    href="<?php  echo Settings::$COUNTRY_BASE_URL.'/dashboard/dash6a'; ?>"
					id=btn1b class="dbbutton dbbutton_leftsubmenu"><?php tp('HW Trained'); ?></a>
    				<div class="hrNav"></div>
    				                    <a	
                    href="<?php  echo Settings::$COUNTRY_BASE_URL.'/dashboard/dash7'; ?>"
					id=btn2 class="dbbutton dbbutton_leftsubmenu"><?php tp('Fac Trained'); ?></a>
    				<div class="hrNav"></div>
    				    				<a	
                    href="<?php  echo Settings::$COUNTRY_BASE_URL.'/dashboard/dash8'; ?>"
					id=btn3 class="dbbutton dbbutton_leftsubmenu"><?php tp('Fac Providing'); ?></a>
    				<div class="hrNav"></div>
    				    				<a	
                    href="<?php  echo Settings::$COUNTRY_BASE_URL.'/dashboard/dash13'; ?>"
					id=btn4 class="dbbutton dbbutton_leftsubmenu dbbutton_leftsubmenu_large"><?php tp('Fac HW Providing'); ?></a>
    				<div class="hrNav"></div>
    				    				<a	
                    href="<?php  echo Settings::$COUNTRY_BASE_URL.'/dashboard/dash12'; ?>"
					id=btn5a class="dbbutton dbbutton_leftsubmenu"><?php tp('Over Time'); ?></a>
    				<div class="hrNav"></div>
    				
    				</p0>
    				
    				<a
    				
					id=consumption name=consumption class="dbbutton dbbutton_leftmenu"><?php tp('Consumption'); ?></a>
					<div class="hrNav"></div>
					
					<p1>
    				                    <a	
                    href="<?php  echo Settings::$COUNTRY_BASE_URL.'/dashboard/dash996/method/ibHR9NQ0bKL'; ?>"
					id=btn6 class="dbbutton dbbutton_leftsubmenu"><?php tp('Injections'); ?></a>
    				<div class="hrNav"></div>
    				    				<a	
                    href="<?php  echo Settings::$COUNTRY_BASE_URL.'/dashboard/dash996/method/w92UxLIRNTl'; ?>"

					id=btn7 class="dbbutton dbbutton_leftsubmenu dbbutton_leftsubmenu_large"><?php tp('Female Condoms'); ?></a>
    				<div class="hrNav"></div>
    				    				<a	
                    href="<?php  echo Settings::$COUNTRY_BASE_URL.'/dashboard/dash996/method/H8A8xQ9gJ5b'; ?>"
					id=btn8 class="dbbutton dbbutton_leftsubmenu dbbutton_leftsubmenu_large"><?php tp('Male Condoms'); ?></a>
    				<div class="hrNav"></div>
    				    				<a	
                    href="<?php  echo Settings::$COUNTRY_BASE_URL.'/dashboard/dash996/method/DiXDJRmPwfh'; ?>"
					id=btn9 class="dbbutton dbbutton_leftsubmenu"><?php tp('Implants'); ?></a>
    				<div class="hrNav"></div>
    				                    <a	
                    href="<?php  echo Settings::$COUNTRY_BASE_URL.'/dashboard/dash996/method/vDnxlrIQWUo'; ?>"
					id=btn10 class="dbbutton dbbutton_leftsubmenu"><?php tp('Oral Pills'); ?></a>
    				<div class="hrNav"></div>
    				    				<a	
                    href="<?php  echo Settings::$COUNTRY_BASE_URL.'/dashboard/dash996/method/krVqq8Vk5Kw'; ?>"
					id=btn11 class="dbbutton dbbutton_leftsubmenu"><?php tp('Sterilization'); ?></a>
    				<div class="hrNav"></div>
    				                    <a
    				href="<?php  echo Settings::$COUNTRY_BASE_URL.'/dashboard/dash996/method/yJSLjbC9Gnr'; ?>"
					id=btn11a class="dbbutton dbbutton_leftsubmenu"><?php tp('IUCDs'); ?></a>
    				<div class="hrNav"></div>
    				                    <a
    				href="<?php  echo Settings::$COUNTRY_BASE_URL.'/dashboard/dash996all'; ?>"
					id=btn11a class="dbbutton dbbutton_leftsubmenu"><?php tp('All'); ?></a>
    				<div class="hrNav"></div>
    				  
    				</p1>
    				
    				    				<a	
					id=stockout name=stockout class="dbbutton dbbutton_leftmenu"><?php tp('Stock Out'); ?></a>
					<div class="hrNav"></div>
					
					<p2>
					                   <a	
                    href="<?php  echo Settings::$COUNTRY_BASE_URL.'/dashboard/dash15'; ?>"
					id=btn12 class="dbbutton dbbutton_leftsubmenu"><?php tp('HW Stock Out'); ?></a>
    				<div class="hrNav"></div>
    				                    <a	
                    href="<?php  echo Settings::$COUNTRY_BASE_URL.'/dashboard/dash16'; ?>"
					id=btn13 class="dbbutton dbbutton_leftsubmenu dbbutton_leftsubmenu_large"><?php tp('Prov Stock Out'); ?></a>
    				<div class="hrNav"></div>
    				    				<a	
                    href="<?php  echo Settings::$COUNTRY_BASE_URL.'/dashboard/dash14'; ?>"
					id=btn14 class="dbbutton dbbutton_leftsubmenu"><?php tp('Over Time'); ?></a>
    				<div class="hrNav"></div>
    				
    				</p2>
    				
