<?php  //file_put_contents('c:\wamp\logs\php_debug.log', 'left_buttons  >'.PHP_EOL, FILE_APPEND | LOCK_EX);	ob_start();
	   //var_dump('$id=', $this->geo_data[0] ,'END'); 
	   //$result = ob_get_clean(); file_put_contents('c:\wamp\logs\php_debug.log', $result .PHP_EOL, FILE_APPEND | LOCK_EX); 
?>
<script>
function goBack() { window.history.back() }
</script>
               
                <a	
                    href="<?php  echo Settings::$COUNTRY_BASE_URL.'/dashboard/dash9b'; ?>"
					class="dbbutton"><?php tp('Nigeria'); ?></a>
				<div class="hrNav"></div>
				<a	
                    onclick="goBack()"
					class="dbbutton"><?php tp('  Back  '); ?></a>
				<div class="hrNav"></div>
				
				                <a	
                    href="<?php  echo Settings::$COUNTRY_BASE_URL.'/dashboard/dash10'; ?>"
					class="dbbutton"><?php tp('Consumed'); ?></a>
					<div class="hrNav"></div>
				
								<a	
                    href="<?php  echo Settings::$COUNTRY_BASE_URL.'/dashboard/dash5a'; ?>"
					class="dbbutton"><?php tp('AMC'); ?></a>
				<div class="hrNav"></div>
								<a	
                    href="<?php  echo Settings::$COUNTRY_BASE_URL.'/dashboard/dash6'; ?>"
					class="dbbutton"><?php tp('HW Trained'); ?></a>
				<div class="hrNav"></div>
								<a	
                    href="<?php  echo Settings::$COUNTRY_BASE_URL.'/dashboard/dash7'; ?>"
					class="dbbutton"><?php tp('Fac Trained'); ?></a>
				<div class="hrNav"></div>
								<a	
                    href="<?php  echo Settings::$COUNTRY_BASE_URL.'/dashboard/dash8'; ?>"
					class="dbbutton"><?php tp('Providing FP'); ?></a>
				<div class="hrNav"></div>
								<a	
                    href="<?php  echo Settings::$COUNTRY_BASE_URL.'/dashboard/dash9'; ?>"
					class="dbbutton"><?php tp('StockOut'); ?></a>
				<div class="hrNav"></div>
				
				
				<a
					href="<?php  echo Settings::$COUNTRY_BASE_URL.'/dashboard/reports'; ?>"
					class="dbbutton"><?php tp('Reports'); ?></a>
				<div class="hrNav"></div>