<!-- latest consumption data => -->
<pre id="latest_consumption_data" style="display:none">Id Version	Share

<?php
	foreach ($this->latest_consumption_data as $row){
?>
<?php echo str_replace(' ', '', $row[name]); ?> <?php echo str_replace(' ','',$row[child_name]); ?>	<?php echo $row[consumption]; ?>%
<?php
	}
?>

</pre>

<!--  average monthly consumption data is created in the chart script -->



