<!-- location Data => -->
<pre id="chart_data" style="display:none">Id Version	Share

<?php
	foreach ($this->chart_data as $row){
?>
<?php echo str_replace(' ', '', $row[name]); ?> <?php echo str_replace(' ','',$row[child_name]); ?>	<?php echo $row[consumption]; ?>%
<?php
	}
?>

</pre>



<?php  //file_put_contents('c:\wamp\logs\php_debug.log', 'load_data 19 >'.PHP_EOL, FILE_APPEND | LOCK_EX);	ob_start();
       //var_dump("chart_data=", $this->chart_data,"END");
       //var_dump("facility_data=",$this->facility_data,"END");
       //$result = ob_get_clean(); file_put_contents('c:\wamp\logs\php_debug.log', $result .PHP_EOL, FILE_APPEND | LOCK_EX); 
?>


