<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<style>
#homecontent {
	background: url("images/content-bg.png") repeat-x scroll 0 0 #FAFAFA;
	position: relative;
}

#homecontent-mid {
	background: url("images/bg-stage.png") repeat-y scroll right top #FFFFFF;
	border: 1px solid #BDBCBD;
	min-height: 100%;
	outline: medium none;
	top: -40px;
}

#homebanner {
	background: url("images/bg-stage-shade.png") repeat-x scroll 0 0
		transparent;
	padding-right: 20px;
	position: relative;
}

.rounded {
	border-radius: 10px 10px 10px 10px;
}

.sliderdiv {
	background: none repeat scroll 0 0 FFFFFF;
	float: left;
}

.main-search {
	background: none repeat scroll 0 0 #FFFFFF;
	float: left;
	overflow: hidden;
}

.nav-buttons {
	background: none repeat scroll 0 0 #FFFFFF;
	float: left;
	overflow: hidden;
}

</style>

<link href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700"
	rel="stylesheet" type="text/css">

<?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>


      <link rel="stylesheet" type="text/css"
	href="https://google-developers.appspot.---com/_static/f7a896e076/css/screen-docs.css" />
<link rel="stylesheet"
	href="//www.google.com/cse/style/look/default.css" type="text/css" />
<link rel="stylesheet"
	href="//fonts.googleapis.com/css?family=Open+Sans:300,400"
	type="text/css">
<script
	src="https://google-developers.appspot.com/_static/f7a896e076/js/prettify-bundle.js"></script>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.6.1/jquery.min.js"></script>
<script id="jqueryui"
	src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.2/jquery-ui.min.js"
	defer async></script>
<script
	src="//www.google.com/jsapi?key=AIzaSyCZfHRnq7tigC-COeQRmoa9Cxr0vbrK6xw"></script>
<!--[if lt IE 9]>
    <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
<script
	src="https://google-developers.appspot.com/_static/f7a896e076/js/framebox.js"></script>

</head>
<body class="yui-skin-sam">

	<div id="pageHolder">

		<div id="header"><?php require_once('views/scripts/header.phtml');?></div>
		<div id="content">

			<!-------   /////////////////////////// get data ////////////////////// -->

			<div>

				<script src="http://code.highcharts.com/highcharts.js"></script>
				<script src="http://code.highcharts.com/modules/data.js"></script>
				<script src="http://code.highcharts.com/modules/drilldown.js"></script>


<?php 
$col1 = 'Name0'; 
$col2 = '6.0'; 
$col3 = '16.40'; 
$outline = "Name0\tV0\t26.61%";
//echo $line;  <?php echo $this->location_data[5][col2]; ?> 6.0	16.40%
$line = $this->location_data[5][col2] . "\t" . $col2 . "\t" . $col3;
$idx = 5;

?>



<!-- Data from www.netmarketshare.com. Select Browsers => Desktop share by version. Download as tsv.  gnr -->
<pre id="tsv" style="display:none">Location Version	Share

<?php echo $this->location_data[0][col2]; ?> 8.0	26.61%
<?php echo $this->location_data[0][col2]; ?> 9.0	16.96%
<?php echo $this->location_data[1][col2]; ?> 18.0	8.01%
<?php echo $this->location_data[1][col2]; ?> 19.0	7.73%
<?php echo $this->location_data[2][col2]; ?> 12.0	6.72%
<?php echo $this->location_data[2][col2]; ?> 6.0	6.40%
<?php echo $this->location_data[3][col2]; ?> <?php echo $col2; ?>	<?php echo $col3; ?>%
<?php echo $this->location_data[4][col2]; ?> 6.0	6.40%
<?php echo $this->location_data[4][col2]; ?> 6.0	6.40%
<?php echo $this->location_data[5][col2]; ?> <?php echo $col2; ?>	<?php echo $col3; ?>%
</pre>



<?php  file_put_contents('c:\wamp\logs\php_debug.log', 'dash3 137 >'.PHP_EOL, FILE_APPEND | LOCK_EX);	ob_start();
       var_dump("location_data=", $this->location_data,"END");
       var_dump("facility_data=",$this->facility_data,"END");
       $result = ob_get_clean(); file_put_contents('c:\wamp\logs\php_debug.log', $result .PHP_EOL, FILE_APPEND | LOCK_EX); 
?>

</div>

			<!-------   /////////////////////////// make top buttons ////////////////////// -->

			<div class="rightdiv" style="float: right;">
				<?php  require_once('views/scripts/dashboard/top_buttons.phtml');?>
					
			</div>

			<div class="clear"></div>
			<div class="hrGrey"></div>
			<div class="clear"></div>

			<!-------   /////////////////////////// make left buttons ////////////////////// -->

			<div class="nav-buttons">
				<?php  require_once('views/scripts/dashboard/left_buttons.phtml');?>
				
			</div>

			<!-------   /////////////////////////// charts ////////////////////// -->


			<body class="docs slim framebox_body">

				<div id="allCharts" class="container">
					<div id="toprow" class="container">
						<div id="homecontent" class="container">
							<div id="homecontent-mid" class="row rounded">
								<div id="homebanner" class="rounded">
								<div class="sliderdiv">
									<div id="chart11_div" style="width: 500px; height: 300px;"></div>
									</div>
									<div class="main-search">
										<div id="chart12_div" style="width: 500px; height: 300px;"></div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>




				<div class="clear"></div>
				<div class="hrGrey"></div>
				<div class="clear"></div>


				<div id="bottomrow" class="container">


					<div id="homecontent" class="container">
						<div id="homecontent-mid" class="row rounded">
							<div id="homebanner" class="rounded">

								<!-------   /////////////////////////// chart 2,1 ////////////////////// -->
								2,1
								<div id="highChart_div" style="min-width: 310px; height: 400px; max-width: 400px; max-height: 400px; margin: 0 auto" data-highcharts-chart="0"><div class="highcharts-co
								
								
								<!-------   /////////////////////////// chart 2,2 ////////////////////// -->
								2,2
								
								<div class="main-search"></div>

								</div>
							</div>
						</div>
					</div>
				</div>
		</div>


		<div class="clear"></div>
		<div class="hrGrey"></div>
		<div class="clear"></div>

		<script type="text/javascript" src="https://www.google.com/jsapi"></script>

		<!-------   /////////////////////////// main ////////////////////// -->

		<script type="text/javascript">

		<?php  require_once('views/scripts/dashboard/c3.js');?>
		
  google.load('visualization', '1.0', {'packages':['corechart', 'table', 'gauge', 'controls']});
  google.setOnLoadCallback(apiLoaded);
  function apiLoaded() {
	  document.getElementById("allCharts").style.marginLeft="130px";

	//drawChart11();
	//drawChart12();
	drawHighchart();
    //generateBarChart();
   
  }

  <!-------   /////////////////////////// script 1,1 ////////////////////// -->
  
  function drawChart11() {
      var data = google.visualization.arrayToDataTable([
        ['Year', 'Recieved', 'Dispensed'],
        ['2004',  1000,      400],
        ['2005',  1170,      460],
        ['2006',  660,       1120],
        ['2007',  1030,      540]
      ]);

      var options = {
        title: 'Status'
      };

      var chart = new google.visualization.LineChart(document.getElementById('chart11_div'));

      chart.draw(data, options);
    }

 <!-------   /////////////////////////// script 1,2 ////////////////////// -->
  
  function drawChart12() {
	 var data = google.visualization.arrayToDataTable([
	   ['Method', 'LARC', 'Male Condom', 'Female Condom', 'IUD', { role: 'annotation' } ],
	   ['2011', 10, 24, 20, 5, ''],
	   ['2012', 16, 22, 23, 9, ''],
	   ['2013', 28, 19, 29, 13, '']
	 ]);

	 var options = {
		        width: 600,
		        height: 400,
		        legend: { position: 'top', maxLines: 3 },
		        bar: { groupWidth: '75%' },
		        isStacked: true
		      };

      var chart = new google.visualization.BarChart(document.getElementById('chart12_div'));

      chart.draw(data, options);
    }
  


  <!-------   /////////////////////////// 2,1 script gnr  ////////////////////// -->

	function drawHighchart() {

	    Highcharts.data({
	        csv: document.getElementById('tsv').innerHTML,
	        itemDelimiter: '\t',
	        parsed: function (columns) {

	            var brands = {},
	                brandsData = [],
	                versions = {},
	                drilldownSeries = [];

	            // Parse percentage strings
	            columns[1] = $.map(columns[1], function (value) {
	                if (value.indexOf('%') === value.length - 1) {
	                    value = parseFloat(value);
	                }
	                return value;
	            });

	            $.each(columns[0], function (i, name) {
	                var brand,
	                    version;

	                if (i > 0) {

	                    // Remove special edition notes
	                    name = name.split(' -')[0];

	                    // Split into brand and version
	                    version = name.match(/([0-9]+[\.0-9x]*)/);
	                    if (version) {
	                        version = version[0];
	                    }
	                    brand = name.replace(version, '');

	                    // Create the main data
	                    if (!brands[brand]) {
	                        brands[brand] = columns[1][i];
	                    } else {
	                        brands[brand] += columns[1][i];
	                    }

	                    // Create the version data
	                    if (version !== null) {
	                        if (!versions[brand]) {
	                            versions[brand] = [];
	                        }
	                        versions[brand].push(['v' + version, columns[1][i]]);
	                    }
	                }
	            });

	            $.each(brands, function (name, y) {
	                brandsData.push({
	                    name: name,
	                    y: y,
	                    drilldown: versions[name] ? name : null
	                });
	            });
	            $.each(versions, function (key, value) {
	                drilldownSeries.push({
	                    name: key,
	                    id: key,
	                    data: value
	                });
	            });

	            // Create the chart
	            $(document.getElementById('highChart_div')).highcharts({
	                chart: {
	                    type: 'column'
	                },
	                title: {
	                    text: 'Consumption'
	                },
	                xAxis: {
	                    type: 'category'
	                },
	                yAxis: {
	                    title: {
	                        text:  'Total Consumption'
	                    }
	                },
	                legend: {
	                    enabled: false
	                },
	                plotOptions: {
	                    series: {
	                        borderWidth: 0,
	                        dataLabels: {
	                            enabled: true,
	                            format: '{point.y:.1f}%'
	                        }
	                    }
	                },

	                tooltip: {
	                    headerFormat: '<span style="font-size:11px">{series.name}</span><br>',
	                    pointFormat: '<span style="color:{point.color}">{point.name}</span>: <b>{point.y:.2f}%</b> of total<br/>'
	                },

	                series: [{
	                    name: 'Level',
	                    colorByPoint: true,
	                    data: brandsData
	                }],
	                drilldown: {
	                    series: drilldownSeries
	                }
	            });
	        }
	    });
	};

  <!-------   /////////////////////////// 2,1 end script ////////////////////// -->


  <!-------   /////////////////////////// 2,2 script ////////////////////// -->

	


  <!-------   /////////////////////////// 2,2 end script ////////////////////// -->
  

  

</script>


		<script>
      
      devsite.github.Link.convertAnchors();
      
        window.prettyPrint();
			

  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>

</script>

</body>

</html>

