INSERT INTO `acl` (`id`, `acl`) VALUES ('edit_partners', 'edit_partners');
INSERT INTO `acl` (`id`, `acl`) VALUES ('edit_mechanisms', 'edit_mechanisms');
INSERT INTO `acl` (`id`, `acl`) VALUES ('employees_module', 'employees_module');
INSERT INTO `acl` (`id`, `acl`) VALUES ('view_training_location', 'view_training_location');
INSERT INTO `acl` (`id`, `acl`) VALUES ('view_employee', 'view_employee');
INSERT INTO `acl` (`id`, `acl`) VALUES ('view_mechanisms', 'view_mechanisms');
INSERT INTO `acl` (`id`, `acl`) VALUES ('view_partners', 'view_partners');

ALTER TABLE `user_to_acl` MODIFY COLUMN `acl_id` ENUM('ps_view_student_grades','ps_edit_student_grades','ps_view_student','ps_edit_student','in_service','pre_service','employees_module','edit_employee','view_training_location','view_employee','view_mechanisms','view_partners','edit_course','view_course','duplicate_training','approve_trainings','master_approver','edit_people','view_people','edit_training_location','edit_facility','view_facility','view_create_reports','training_organizer_option_all','training_title_option_all','use_offline_app','admin_files','facility_and_person_approver','edit_evaluations','edit_country_options','acl_editor_training_category','acl_editor_people_qualifications','acl_editor_people_responsibility','acl_editor_training_organizer','acl_editor_people_trainer','acl_editor_training_topic','acl_editor_people_titles','acl_editor_training_level','acl_editor_refresher_course','acl_editor_people_trainer_skills','acl_editor_pepfar_category','acl_editor_people_languages','acl_editor_funding','acl_editor_people_affiliations','acl_editor_recommended_topic','acl_editor_nationalcurriculum','acl_editor_people_suffix','acl_editor_method','acl_editor_people_active_trainer','acl_editor_facility_types','acl_editor_ps_classes','acl_editor_facility_sponsors','acl_editor_ps_cadres','acl_editor_ps_degrees','acl_editor_ps_funding','acl_editor_ps_institutions','acl_editor_ps_languages','acl_editor_ps_nationalities','acl_editor_ps_joindropreasons','acl_editor_ps_sponsors','acl_editor_ps_tutortypes','acl_editor_ps_coursetypes','acl_editor_ps_religions','add_edit_users','acl_admin_training','acl_admin_people','acl_admin_facilities','import_training','import_training_location','import_facility','import_person','edit_partners','edit_mechanisms','add_new_facility') NOT NULL DEFAULT 'view_course' ;
INSERT INTO `user_to_acl` (acl_id, user_id, created_by, timestamp_created) select 'employees_module', user_id, created_by, timestamp_created from user_to_acl where acl_id = 'edit_employee';
