<html>
	<head>
		<title><?php echo $this->escape($this->title);?></title>
		<link href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet" type="text/css">

<?php
	require_once('views/helpers/Location.php');
	require_once('views/helpers/ScriptContainer.php');
	print ScriptContainer::$instance->renderCSSHead();
	print ScriptContainer::$instance->renderJSHead();
?>

		<script type="text/javascript" charset="utf-8">
			$(document).ready(function() {
				$( ".calendarbox" ).datepicker({
					changeMonth: true,
					changeYear: true,
					yearRange:'1900:2099'
				});
				/* Add a click handler to the rows - this could be used as a callback */
				$(".tablegrid tbody").click(function(event) {
					$(oTable.fnSettings().aoData).each(function (){
						$(this.nTr).removeClass('row_selected');
					});
					$(event.target.parentNode).addClass('row_selected');
				});

				/* Add a click handler for the delete row */
				$('#delete').click( function() {
					var anSelected = fnGetSelected( oTable );
					oTable.fnDeleteRow( anSelected[0] );
				} );

				/* Init the table */
				oTable = $('.tablegrid').dataTable({
					"bJQueryUI": true,
					"sPaginationType": "full_numbers"
				});
			} );

			/* Get the rows which are currently selected */
			function fnGetSelected( oTableLocal ){
				var aReturn = new Array();
				var aTrs = oTableLocal.fnGetNodes();

				for ( var i=0 ; i<aTrs.length ; i++ ){
					if ( $(aTrs[i]).hasClass('row_selected') ){
						aReturn.push( aTrs[i] );
					}
				}
				return aReturn;
			}
		</script>
	</head>
	<body>
		<div id="pageHolder">
			<div id="header"><?php require_once('views/scripts/preheader.phtml');?></div>
			<div id="content">
				<?php require_once 'views/scripts/status.phtml'; ?>
				<div id="subcontent">

						<div class="historyDiv">

							<a href="#" onclick="doDelete(); return false;"><?php tp('Delete this Person');?></a>
							<script language="JavaScript">
								function doDelete() {
									if(confirm("<?php tp('Are you sure you wish to delete this person?');?>")) {
										window.location = '<?php echo $this->base_url;?>/person/delete/id/<?php echo $this->id;?>';
										return false;
									}
								}
							</script>

						</div>

					<div id="contentheader">
						<h2><?php echo t("Edit/View Tutor's Record"); ?></h2><br>
					</div>
					<form  action="" id="peopleadd" method="post">
						<div class="mainformholder">
							<div class="pad50 clear"></div>
							<input type="hidden" name="id" value="<?php echo $this->escape($this->id);?>">
							<input type="hidden" name="tutorid" value="<?php echo $this->escape($this->tutuotid);?>">

							<p><?php echo t('Personal Information'); ?></p>

		 					<label><?php echo t('Title'); ?></label>
							<select name="title" >
								<option value="0"><?php echo t('Select...'); ?></option>
							<?php foreach ($this->gettitle as $fetchtitle){ ?>
								<option value="<?php echo $fetchtitle[id]; ?>"<?php echo ($this->escape($this->selid) == $fetchtitle[id] ? " selected" : "") ?>><?php echo $fetchtitle[title_phrase]; ?></option>
							<?php } ?>
							</select>

							<label><?php echo t('First name'); ?></label>
							<input type="text" name="firstname" value="<?php echo $this->escape($this->firstname);?>">

							<label><?php echo t('Middle name'); ?></label>
							 <input type="text" name="middlename" value="<?php echo $this->escape($this->middlename);?>">

							<label><?php echo t('Last name'); ?></label>
							<input type="text" name="lastname" value="<?php echo $this->escape($this->lastname);?>">

							<label><?php echo t('School ID'); ?></label>
							<input type="text" name="nationalid" value="<?php echo $this->escape($this->nationalid);?>">

							<label><?php echo t('Nationality'); ?></label>
							<select name="nationality">
								<option value="0"><?php echo t('Select...'); ?></option>
<?php
	foreach ($this->lookupnationalities as $nationality){
?>
								<option value="<?php echo $nationality['id']; ?>"<?php echo $nationality['id'] == $this->escape($this->nationality) ? " selected" : ""; ?>><?php echo $nationality['nationality']; ?></option>
<?php
	}
?>
							</select>

							<label><?php echo t('Gender'); ?></label>
							<select name="gender">
								<option value="na"><?php echo t('Select...'); ?></option>
								<option value="male"<?php echo ($this->escape($this->gender) == "male" ? " selected" : "");?>><?php echo t('Male'); ?></option>
								<option value="female"<?php echo ($this->escape($this->gender) == "female" ? " selected" : "");?>><?php echo t('Female'); ?></option>
							</select>

							<label><?php echo t('Date of birth'); ?></label>
							<input type="text" class="calendarbox" name="dob" id="dob" value="<?php echo $this->escape($this->dob);?>">

							<div class="pad20 clear"></div>
							<p style="float:left;font-size:14px;"><?php echo t('Permanent Address'); ?></p>
							<div class="pad20 clear"></div>

<?php  region_filters_dropdown_ps($this, 'permanent');  ?>

							<label><?php echo t('Address 1'); ?></label>
							<input type="text" name="address1" value="<?php echo $this->escape($this->address1);?>">

							<label><?php echo t('Address 2'); ?></label>
							<input type="text" name="address2" value="<?php echo $this->escape($this->address2);?>" >


							<label><?php echo t('City'); ?></label>
							<input type="text" name="city" value="<?php echo $this->escape($this->city);?>" >

							<label><?php echo t('Postal code / ZIP'); ?></label>
							<input type="text" name="postalcode" value="<?php echo $this->escape($this->postalcode);?>">

							<label><?php echo t('Cellphone'); ?></label>
							<input type="text" name="localcell" value="<?php echo $this->escape($this->cell);?>" >

							<label><?php echo t('Cellphone 2'); ?></label>
							<input type="text" name="localcell2" value="<?php echo $this->escape($this->cell2);?>" >

							<div class="pad20 clear"></div>
							<p style="float:left;font-size:14px;"><?php echo t('Facility Information'); ?></p>
							<div class="pad20 clear"></div>

<?php  region_filters_dropdown_ps($this, 'local');  ?>

							<label>Facility</label>
							<select name="facilityid">
	<?php
		foreach ($this->fetchfacility as $facility){
	?>
								<option value="<?php echo $facility[id];?>"><?php echo $facility[facility_name];?></option>
	<?php
		}
	?>
	<!--						<option value="<?php echo $this->escape($this->facid);?>" selected><?php echo $this->escape($this->facility);?></option>	 -->
							</select>

							<label><?php echo t('Cadre'); ?></label>
							<select name="cadreid">
	<?php
		foreach ($this->getcadre as $cadre){
	?>
								<option value="<?php echo $cadre[id];?>"<?php echo ($this->cadreid == $cadre['id'] ? " selected" : ""); ?>><?php echo $cadre[cadrename];?></option>
	<?php
		}
	?>
							</select>

							<label><?php echo t('Tutor Since'); ?></label>
							<select name="tutorsince">
								<option value="0"><?php echo t('Select...'); ?></option>
<?php
for ($i = date("Y"); $i >= (date("Y") - 100); $i--){
	echo "<option value=\"" . $i . "\"" . ($i == $this->tutorsince ? " selected" : "") . ">" . $i . "</option>\n";
}
?>
							</select>

							<label><?php echo t('Tutor Type'); ?></label>
							<div style="overflow : auto; float : left; width : 250px; height : 100px; border : 1px solid #CCCCCC; border-radius : 3px; margin-left : 25px; -moz-border-radius : 3px; -webkit-border-radius : 3px; border : 1px solid #85B1DE; background-image : url(/html/images/trainsmart-gradient.gif); background-repeat : repeat-x; margin-bottom : 10px;">
<?php
	foreach ($this->lookuptutortypes as $tutortype){
?>
							<div style="height : 20px; overflow : hidden;">
								<input type="checkbox" style="margin : 3px;" name="tutortype[]" id="tutortype[]" value="<?php echo $tutortype['id']; ?>"<?php echo (in_array($tutortype['id'],$this->tutortypes) ? " checked" : "") ?>> <?php echo $tutortype['typename']; ?><br>
							</div>
<?php
	}
?>
							</div>

							<label><?php echo t('Tutor at this Inst. Since'); ?></label>
							<select name="tutortimehere">
								<option value="0"><?php echo t('Select...'); ?></option>
<?php
for ($i = date("Y"); $i >= (date("Y") - 100); $i--){
	echo "<option value=\"" . $i . "\"" . ($i == $this->tutortimehere ? " selected" : "") . ">" . $i . "</option>\n";
}
?>
							</select>

							<label><?php echo t('Degree Institution'); ?></label>
							<input type="text" name="degreeinst" value="<?php echo $this->escape($this->degreeinst);?>">

							<label><?php echo t('Degree'); ?></label>
							<select name="degree" class="comboeditable">
								<option value="0"><?php echo t('Select...'); ?></option>
<?php
	foreach ($this->lookupdegrees as $degree){
?>
								<option value="<?php echo $degree['id']; ?>"<?php echo $degree['id'] == $this->escape($this->degree) ? " selected" : ""; ?>><?php echo $degree['degree']; ?></option>
<?php
	}
?>
							</select>

							<label><?php echo t('Year'); ?></label>
							<input type="text" name="degreeyear" value="<?php echo $this->escape($this->degreeyear);?>">

							<label><?php echo t('Languages Spoken'); ?></label>
							<div style="overflow : auto; float : left; width : 250px; height : 100px; border : 1px solid #CCCCCC; border-radius : 3px; margin-left : 25px; -moz-border-radius : 3px; -webkit-border-radius : 3px; border : 1px solid #85B1DE; background-image : url(/html/images/trainsmart-gradient.gif); background-repeat : repeat-x; margin-bottom : 10px;">
<?php
	foreach ($this->tutorlanguages as $language){
?>
							<div style="height : 20px; overflow : hidden;">
								<input type="checkbox" style="margin : 3px;" name="languagesspoken[]" id="languagesspoken[]" value="<?php echo $language['id']; ?>"<?php echo (in_array($language['id'],$this->knownlanguages) ? " checked" : "") ?>> <?php echo $language['language']; ?><br>
							</div>
<?php
	}
?>

							</div>
						</div>

					<div class="clear pad50"></div>
					<div style="width:100%;">
						<p style=""><?php echo t('Students Advised'); ?></p>
						<table cellpadding="0" cellspacing="0" border="0" class="display tablegrid" id="" style="width:100%">
							<thead>
								<tr>
									<th><?php echo t('Student Id'); ?></th>
									<th><?php echo t('Student Name'); ?></th>
									<th><?php echo t('Year of Graduation'); ?></th>
									<th><?php echo t('Cohort'); ?></th>
								</tr>
							</thead>
							<tbody>
								<?php
									foreach ($this->students as $student){
									?>
									<tr class="GradeA">
										<td><?php echo $student['id'] ?></td>
										<td class=""><?php echo $student['first_name'] . " " . $student['last_name'] ?></td>
										<td class="">-</td>
										<td class="">-</td>
									</tr>
									<?php
								}
								?>
							</tbody>
						</table>
					</div>

					<div class="pad50"></div>
					<div style="width : 100%;">
						<p style=""><?php echo t('Courses Taught'); ?></p>
						<table cellpadding="0" cellspacing="0" border="0" class="display tablegrid" id="" style="width:100%;">
							<thead>
								<tr>
									<th><?php echo t('Course Name'); ?></th>
									<th><?php echo t('Course Type'); ?></th>
									<th><?php echo t('Date'); ?></th>
									<th><?php echo t('Cohort'); ?></th>
								</tr>
							</thead>
							<tbody>
								<?php
									foreach ($this->classes as $class){
									?>
									<tr class="GradeA">
										<td><?php echo $class['classname'] ?></td>
										<td class=""><?php echo $class['coursetype']; ?></td>
										<td class=""><?php echo $class['startdate']; ?> - <?php echo $class['enddate']; ?></td>
										<td class=""><?php echo $class['cohortname']; ?></td>
									</tr>
									<?php
								}
								?>
								<!--
								<tr class="GradeA">
									<td>123</td>
									<td class="">John Doe</td>
									<td class="">M</td>
									<td class="">Institution</td>
								</tr>
								-->
							</tbody>
						</table>
					</div>
					<div class="mainformholder">
							<div class="clear"></div>
							<p><?php echo t('Other'); ?></p>

							<label style="text-align : left;"><?php echo t('Positions held (committees, etc.)'); ?></label>
							<textarea name="position" ><?php echo $this->escape($this->positionsheld);?></textarea>

							<div class="clear"></div><br clear="all"/>

							<label style="text-align : left;"><?php echo t('Comments'); ?></label>
							<textarea name="comments" ><?php echo $this->escape($this->comments);?></textarea>

							<div class="clear"></div><br clear="all"/>

							<div class="rightdiv">
								<div class="pad20"></div>
								<input type="submit" name="update" value="<?php echo t('Update Tutor'); ?> &raquo;" class="tsbutton green large">
							</div>
							<div class="clear"></div>
					</div>
					</form>
							<div class="clear"></div>


					<div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
				</div>
			</div>
		</div>
	</body>
</html>