<html>
	<head>
		<title><?php echo $this->escape($this->title);?></title>
		<link href="http://fonts.googleapis.com/css?family=Droid+Sans:400,700" rel="stylesheet" type="text/css">

<?php
	require_once('views/helpers/Location.php');
	require_once('views/helpers/ScriptContainer.php');
	print ScriptContainer::$instance->renderCSSHead();
	print ScriptContainer::$instance->renderJSHead();
?>

		<script type="text/javascript" charset="utf-8">
			$(document).ready(function() {
				$( ".calendarbox" ).datepicker({
					changeMonth: true,
					changeYear: true,
					yearRange:'1900:2099'
				});
				/* Add a click handler to the rows - this could be used as a callback */
				$(".tablegrid tbody").click(function(event) {
					$(oTable.fnSettings().aoData).each(function (){
						$(this.nTr).removeClass('row_selected');
					});
					$(event.target.parentNode).addClass('row_selected');
				});

				/* Add a click handler for the delete row */
				$('#delete').click( function() {
					var anSelected = fnGetSelected( oTable );
					oTable.fnDeleteRow( anSelected[0] );
				} );

				/* Init the table */
				oTable = $('.tablegrid').dataTable({
					"bJQueryUI": true,
					"sPaginationType": "full_numbers"
				});
			} );

			/* Get the rows which are currently selected */
			function fnGetSelected( oTableLocal ){
				var aReturn = new Array();
				var aTrs = oTableLocal.fnGetNodes();

				for ( var i=0 ; i<aTrs.length ; i++ ){
					if ( $(aTrs[i]).hasClass('row_selected') ){
						aReturn.push( aTrs[i] );
					}
				}
				return aReturn;
			}
		</script>
	</head>
	<body>
		<div id="pageHolder">
			<div id="header"><?php require_once('views/scripts/preheader.phtml');?></div>
			<div id="content">
				<?php require_once 'views/scripts/status.phtml'; ?>
				
				<div id="subcontent">

						

					<div id="contentheader">
						<h2><?php echo t("View Tutor's Record"); ?></h2><br>
					</div>
					<form  action="" id="peopleadd" method="post">
					
					<!-- TA:6: added 8/8/2014 table for better allignment-->
				<table style="width:100%">
				<tr>
				<td>
				
						<div class="mainformholder">
							<div class="pad50 clear"></div>
							<input readonly type="hidden" name="id" value="<?php echo $this->escape($this->id);?>">
							<input readonly type="hidden" name="tutorid" value="<?php echo $this->escape($this->tutuotid);?>">

							
							
							<p><?php echo t('Personal Information'); ?></p>

		 					<label><?php echo t('Title'); ?></label>
							<select name="title" disabled = true >
								<option value="0"><?php echo t('Select...'); ?></option>
							<?php foreach ($this->gettitle as $fetchtitle){ ?>
								<option value="<?php echo $fetchtitle['id']; ?>"<?php echo ($this->escape($this->selid) == $fetchtitle['id'] ? " selected" : "") ?>><?php echo $fetchtitle['title_phrase']; ?></option>
							<?php } ?>
							</select>

							<label><?php echo t('First name'); ?></label>
							<input readonly type="text" name="firstname" value="<?php echo $this->escape($this->firstname);?>">

							<label><?php echo t('Middle name'); ?></label>
							 <input readonly type="text" name="middlename" value="<?php echo $this->escape($this->middlename);?>">

							<label><?php echo t('Last name'); ?></label>
							<input readonly type="text" name="lastname" value="<?php echo $this->escape($this->lastname);?>">

							<label><?php echo t('School ID'); ?></label>
							<input readonly type="text" name="nationalid" value="<?php echo $this->escape($this->nationalid);?>">

							<!-- TA: added 07/22/2014 START -->
							<?php
								if($this->escape($this->label_ps_nationality)){
									echo "<label>" . $this->escape($this->label_ps_nationality) . "</label>";
									echo "<select name='nationality' disabled=true>";
									echo "<option value='0'>" . t('Select...') . "</option>";
									foreach ($this->lookupnationalities as $nationality){
									echo "<option value='" . $nationality['id'] . "' " . ($nationality['id'] == $this->escape($this->nationalityid) ? ' selected' : '') . ">" . $nationality['nationality'] . "</option>";
									}
									echo "</select>";
								}
								?>
							<!-- TA: added 07/22/2014 END -->
							

							<label><?php echo t('Gender'); ?></label>
							<select name="gender" disabled = true>
								<option value="na"><?php echo t('Select...'); ?></option>
								<option value="male"<?php echo ($this->escape($this->gender) == "male" ? " selected" : "");?>><?php echo t('Male'); ?></option>
								<option value="female"<?php echo ($this->escape($this->gender) == "female" ? " selected" : "");?>><?php echo t('Female'); ?></option>
							</select>

							<label><?php echo t('Date of birth'); ?></label>
							<input readonly type="text" class="calendarbox" name="dob" id="dob" value="<?php echo $this->escape($this->dob);?>">
							
							<!-- TA: added 7/22/2014 START -->
							<div class="pad20 clear"></div>
							<?php
								if($this->escape($this->label_marital_status)){
									echo "<label>" . $this->escape($this->label_marital_status) . "</label>";
									echo "<select name='marital_status' id='marital_status' disabled=true>";
									echo "<option value='na'>" . t('Select...') . "</option>";
									echo "<option value='single' " . ($this->escape($this->marital_status) == 'single' ? ' selected' : '') . ">Single</option>";
									echo "<option value='married' " . ($this->escape($this->marital_status) == 'married' ? ' selected' : '') . ">Married</option>";
									echo "<option value='divorced' " . ($this->escape($this->marital_status) == 'divorced' ? ' selected' : '') . ">Divorced</option>";
									echo "<option value='widowed' " . ($this->escape($this->marital_status) == 'widowed' ? ' selected' : '') . ">Widowed</option>";
									echo "</select>";
								}
								if($this->escape($this->label_spouse_name)){
									echo "<label>" . $this->escape($this->label_spouse_name) . "</label>";
									echo "<input readonly type='text' name='spouse_name' id='spouse_name' value='" . $this->escape($this->spouse_name) . "';>";
								}
								
								echo "<div class='pad20 clear'></div>";
		if($this->escape($this->label_ps_permanent_address)){
				echo "<div class='pad20 clear'></div>";
				echo "<p style='float:left;font-size:14px;'>" . $this->escape($this->label_ps_permanent_address) . "</p>";
				echo "<div class='pad20 clear'></div><br>";
				region_filters_dropdown_ps($this, 'permanent');
				echo "<label>" . t('Address 1') . "</label>";
				echo "<input readonly type='text' name='address1' value='" . $this->escape($this->address1) . "'>";
				echo "<label>" . t('Address 2') . "</label>";
				echo "<input readonly type='text' name='address2' value='" . $this->escape($this->address2) . "'>";
				echo"<label>" . t('City') . "</label>";
				echo"<input readonly type='text' name='city' value='" . $this->escape($this->city) . "'>";
				echo"<label>" . $this->escape($this->label_ps_zip_code) . "</label>";
				echo"<input readonly type='text' name='postalcode' value='" . $this->escape($this->postalcode) . "'> ";
				echo "<label>" . t('Cellphone') . "</label>";
				echo "<input readonly type='text' name='localcell' value='" . $this->escape($this->cell) . "'>";
				echo "<label>" . t('Cellphone 2') . "</label>";
				echo "<input readonly type='text' name='localcell2' value='" . $this->escape($this->cell2) . "'>";
}
								?>
								<!-- TA: added 7/22/2014 END -->

							<div class="pad20 clear"></div>
							<p style="float:left;font-size:14px;"><?php echo t('Facility Information'); ?></p>
							<div class="pad20 clear"></div>

<?php  region_filters_dropdown_ps($this, 'local', true);  ?>

              <label><?php echo t('Facility'); ?></label>
              <select id="facilityid" name="facilityid" disabled = true>
                <option value="0"><?php echo t('Select...'); ?></option>
                <?php
                  foreach ($this->facilities as $facility){
                    echo "<option value=\"" . $facility['id'] . "\"" . ($this->facilityid == $facility['id'] ? " selected" : "") . ">" . $facility['facility_name'] . "</option>\n";
                  }
                ?>
              </select>

              <label><?php echo t('Instituion'); ?></label>
              <select id="institutionid" name="institutionid" disabled = true>
                <option value="0"><?php echo t('Select...'); ?></option>
                <?php
                  foreach ($this->institutions as $institution){
                    echo "<option value=\"" . $institution['id'] . "\"" . ($this->institutionid == $institution['id'] ? " selected" : "") . ">" . $institution['institutionname'] . "</option>\n";
                  }
                ?>
              </select>

  
							<label><?php echo t('Tutor Since'); ?></label>
							<select name="tutorsince" disabled = true>
								<option value="0"><?php echo t('Select...'); ?></option>
<?php
for ($i = date("Y"); $i >= (date("Y") - 100); $i--){
	echo "<option value=\"" . $i . "\"" . ($i == $this->tutorsince ? " selected" : "") . ">" . $i . "</option>\n";
}
?>
							</select>

							<label><?php echo t('Tutor Type'); ?></label>
							<div style="overflow : auto; float : left; width : 250px; height : 100px; border : 1px solid #CCCCCC; border-radius : 3px; margin-left : 25px; -moz-border-radius : 3px; -webkit-border-radius : 3px; border : 1px solid #85B1DE; background-image : url(/html/images/trainsmart-gradient.gif); background-repeat : repeat-x; margin-bottom : 10px;">
<?php
	foreach ($this->lookuptutortypes as $tutortype){
?>
							<div style="height : 20px; overflow : hidden;">
								<input type="checkbox" style="margin : 3px;" name="tutortype[]" id="tutortype[]" value="<?php echo $tutortype['id']; ?>"<?php echo (in_array($tutortype['id'],$this->tutortypes) ? " disabled checked" : " disabled") ?>> <?php echo $tutortype['typename']; ?><br>
							</div>
<?php
	}
?>
							</div>
              

							<label><?php echo t('Tutor at this Inst. Since'); ?></label>
							<select name="tutortimehere" disabled = true>
								<option value="0"><?php echo t('Select...'); ?></option>
<?php
for ($i = date("Y"); $i >= (date("Y") - 100); $i--){
	echo "<option value=\"" . $i . "\"" . ($i == $this->tutortimehere ? " selected" : "") . ">" . $i . "</option>\n";
}
?>
							</select>

							<label><?php echo t('Degree Institution'); ?></label>
							<input readonly type="text" name="degreeinst" value="<?php echo $this->escape($this->degreeinst);?>">

							<label><?php echo t('Degree'); ?></label>
							<select name="degree" class="comboeditable" disabled = true>
								<option value="0"><?php echo t('Select...'); ?></option>
<?php
	foreach ($this->lookupdegrees as $degree){
?>
								<option value="<?php echo $degree['id']; ?>"<?php echo $degree['id'] == $this->escape($this->degree) ? " selected" : ""; ?>><?php echo $degree['degree']; ?></option>
<?php
	}
?>
							</select>

							<label><?php echo t('Year'); ?></label>
							<input readonly type="text" name="degreeyear" value="<?php echo $this->escape($this->degreeyear);?>">

							<label><?php echo t('Languages Spoken'); ?></label>
							<div style="overflow : auto; float : left; width : 250px; height : 100px; border : 1px solid #CCCCCC; border-radius : 3px; margin-left : 25px; -moz-border-radius : 3px; -webkit-border-radius : 3px; border : 1px solid #85B1DE; background-image : url(/html/images/trainsmart-gradient.gif); background-repeat : repeat-x; margin-bottom : 10px;">
<?php
	foreach ($this->tutorlanguages as $language){
?>
							<div style="height : 20px; overflow : hidden;">
								<input readonly type="checkbox" style="margin : 3px;" name="languagesspoken[]" id="languagesspoken[]" value="<?php echo $language['id']; ?>"<?php echo (in_array($language['id'],$this->knownlanguages) ? " checked" : "") ?>> <?php echo $language['language']; ?><br>
							</div>
<?php
	}
?>

							</div>
						</div>
						
						<!-- TA:6: added 8/8/2014 START -->
				</td>
				<td style="width:20%" valign='top' align='left'>
				<div class="historyDiv">
						<b>ID</b>&nbsp;<?php echo $this->escape($this->id);?><br>
						<b>Date created</b>&nbsp;<?php echo str_replace(' ','&nbsp;',$this->escape($this->dateCreated));?><br>						
						<b>Created by</b>&nbsp;<?php echo ($this->creator == "N/A" ? t("N/A") : "{$this->creator->first_name} {$this->creator->middle_name} {$this->creator->last_name}") ?><br>
						<b>Date updated</b>&nbsp;<?php echo str_replace(' ','&nbsp;',$this->escape($this->dateModified));?><br>
						<b>Updated by</b>&nbsp;<?php echo ($this->updater == "N/A" ? t("N/A") : "{$this->updater->first_name} {$this->updater->middle_name} {$this->updater->last_name}") ?><br>
						<b>UUID</b>&nbsp;<?php echo $this->escape($this->uuid);?><br>
						<hr>
						<!-- TA:6: added 8/8/2014 END -->
                            <?php if ( $this->hasACL( 'acl_delete_ps_student' )){?> 
							<a href="#" onclick="doDelete(); return false;"><?php tp('Delete this Person');?></a>
							<?php }?>
							<script language="JavaScript">
								function doDelete() {
									if(confirm("<?php tp('Are you sure you wish to delete this person?');?>")) {
										window.location = '<?php echo $this->base_url;?>/person/delete/id/<?php echo $this->id;?>';
										return false;
									}
								}
							</script>

						</div>
				</td>
				</tr>
				</table>

					<div class="clear pad50"></div>
					<div style="width:100%;">
						<p style=""><?php echo t('Students Advised'); ?></p>
						<table cellpadding="0" cellspacing="0" border="0" class="display tablegrid" id="" style="width:100%">
							<thead>
								<tr>
									<th><?php echo t('Student Id'); ?></th>
									<th><?php echo t('Student Name'); ?></th>
									<th><?php echo t('Year of Graduation'); ?></th>
									<th><?php echo t('Cohort'); ?></th>
								</tr>
							</thead>
							<tbody>
								<?php
									foreach ($this->students as $student){
									?>
									<tr class="GradeA">
										<td><?php echo $student['id'] ?></td>
										<td class=""><?php echo $student['first_name'] . " " . $student['last_name'] ?></td>
										<td class="">-</td>
										<td class="">-</td>
									</tr>
									<?php
								}
								?>
							</tbody>
						</table>
					</div>

					<div class="pad50"></div>
					<div style="width : 100%;">
						<p style=""><?php echo t('Courses Taught'); ?></p>
						<table cellpadding="0" cellspacing="0" border="0" class="display tablegrid" id="" style="width:100%;">
							<thead>
								<tr>
									<th><?php echo t('Course Name'); ?></th>
									<th><?php echo t('Course Type'); ?></th>
									<th><?php echo t('Date'); ?></th>
									<th><?php echo t('Cohort'); ?></th>
								</tr>
							</thead>
							<tbody>
								<?php
									foreach ($this->classes as $class){
									?>
									<tr class="GradeA">
										<td><?php echo $class['classname'] ?></td>
										<td class=""><?php echo $class['coursetype']; ?></td>
										<td class=""><?php echo $class['startdate']; ?> - <?php echo $class['enddate']; ?></td>
										<td class=""><?php echo $class['cohortname']; ?></td>
									</tr>
									<?php
								}
								?>
								<!--
								<tr class="GradeA">
									<td>123</td>
									<td class="">John Doe</td>
									<td class="">M</td>
									<td class="">Institution</td>
								</tr>
								-->
							</tbody>
						</table>
					</div>
					<div class="mainformholder">
							<div class="clear"></div>
							<p><?php echo t('Other'); ?></p>

							<label style="text-align : left;"><?php echo t('Positions held (committees, etc.)'); ?></label>
							<textarea disabled = true name="position" ><?php echo $this->escape($this->positionsheld);?></textarea>

							<div class="clear"></div><br clear="all"/>

							<label style="text-align : left;"><?php echo t('Comments'); ?></label>
							<textarea disabled = true name="comments" ><?php echo $this->escape($this->comments);?></textarea>
							
							<!-- TA: added 7/22/2014 START -->
							<div class="clear"></div><br clear="all"/>
							<?php
							if($this->escape($this->label_specialty)){
								echo "<label style='text-align : left;'>" . $this->escape($this->label_specialty) . "</label>";
								echo "<select name='specialty'>";
								echo "<option value='0'>" . t('Select...') . "</option>";
								foreach ($this->getspecialty as $fetchspecialty){
									echo "<option value='" . $fetchspecialty['id'] . "'" . ($this->escape($this->spid) == $fetchspecialty['id'] ? " selected" : "") . ">" . $fetchspecialty['specialty_phrase'] . "</option>";
								}
								echo "</select>";
							}
							if($this->escape($this->label_contract_type)){
								echo "<label style='text-align : left;'>" . $this->escape($this->label_contract_type) . "</label>";
								echo "<select name='contract_type'>";
								echo "<option value='0'>" . t('Select...') . "</option>";
								foreach ($this->getcontracts as $fetchcontract){
									echo "<option value='" . $fetchcontract['id'] . "'" . ($this->escape($this->ctid) == $fetchcontract['id'] ? " selected" : "") . ">" . $fetchcontract['contract_phrase'] . "</option>";
								}
								echo "</select>";
							}
								if($this->escape($this->label_custom_field1)){
									echo "<label style='text-align : left;'>" . $this->escape($this->label_custom_field1) . "</label>";
									echo "<input type='text' name='custom_field1' id='custom_field1' value='" . $this->escape($this->custom_field1) . "';>";
								}
								if($this->escape($this->label_custom_field2)){
									echo "<label style='text-align : left;'>" . $this->escape($this->label_custom_field2) . "</label>";
									echo "<input type='text' name='custom_field2' id='custom_field2' value='" . $this->escape($this->custom_field2) . "';>";
								}
								if($this->escape($this->label_custom_field3)){
									echo "<label style='text-align : left;'>" . $this->escape($this->label_custom_field3) . "</label>";
									echo "<input type='text' name='custom_field3' id='custom_field3' value='" . $this->escape($this->custom_field3) . "';>";
								}
								?>
								<!-- TA: added 7/22/2014 END -->

							<div class="clear"></div><br clear="all"/>

							<div class="rightdiv">
								<div class="pad20"></div>
							</div>
							<div class="clear"></div>
					</div>
					</form>
							<div class="clear"></div>


					<div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
				</div>
				
			</div>
		</div>
	</body>
</html>