<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title><?php echo $this->translation['Application Name'] . " | " . $this->pageTitle; ?></title>
	<?php
	require_once ('views/helpers/Location.php');
	require_once ('views/helpers/ScriptContainer.php');
	require_once ('views/helpers/FormHelper.php');
	print ScriptContainer::$instance->renderCSSHead ();
	print ScriptContainer::$instance->renderJSHead ();
	?>

</head>
<body class="yui-skin-sam">

	<div id="pageHolder">

		<div id="header"><?php require_once('views/scripts/header.phtml');?></div>
		<div id="content">

			<?php require_once 'views/scripts/status.phtml' ?>

			<h1><?php $this->mode == 'add' ? print(t('Add').space.t('Employee')) : tp('Build Funding'); ?></h1>
			
            <form action="" method="post" class="form_employee">

            <?php require_once("views/helpers/DropDown.php");?>
            <fieldset>
            <div id="funwrapper">

                <?php
                    echo DropDown::render('mechanism', t('Mechanism'), $this->mechanism, 'mechanism_phrase', 'id', false, false, true) . "\n";
                    echo DropDown::render('subPartner', t('Subpartner'), $this->subPartner, 'partner', 'id', false, false, true, true, true) . "\n";
                    echo labelAndField($this, t('Funding End Date'), 'date','end_date', '');
                ?>

            </div>
            </fieldset>

				<script type="text/javascript">

					$(document).ready(function () {

						itech_save_confirm_on_leave();
						
						$('.datepicker').each(function () {
							$(this).removeAttr('id').datepicker({ //bugfix, datepicker doesnt work with multiple id="" field, these are cloned so remove id attribute
								changeMonth: true,
								changeYear: true,
								showOn: false,
								dateFormat: "dd/mm/yy"
							})
						});
						$('.calendarbtn').click(openNearestDatePicker);
						
					});
				</script>

				<div class="clear"></div>
				<input type="hidden" name="limit" id="limit" value="1" />
				<input type="submit" class="submitNoArrow" name="go" value="<?php tp('Save');?>" />
			</form>
			<div class="clear"></div>
		</div>
	</body>
</html>
