<?php
//TA:#416.2


ob_start();
require_once('views/scripts/header.phtml');
$header = ob_get_contents();
ob_end_clean();

ob_start();
require_once('views/scripts/nav-admin.phtml');
$nav = ob_get_contents();
ob_end_clean();

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title><?php echo t($this->translation['Application Name']);?> | <?php echo t($this->pageTitle); ?></title>
<?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>
</head>
<body  class="yui-skin-sam">
<div id="pageHolder">
  <div id="header"><?php echo $header; ?></div>
  <div id="content" class="adminDiv">

    <form method="post" name="adminForm"  enctype="multipart/form-data">

    <div id="navAdmin"><?php echo $nav;?></div>

    <div id="contentAdmin">
    <h1><?php echo t($this->pageTitle); ?></h1>
    <div style="font-style:italic;"><?php echo t('Assign Service Delivery Team to Partner'); ?></div>
    <br/>
    
    <?php print $this->multiAssign; ?>


    <div class="clear"></div>
    <br>

    <input type="hidden" name="redirect" value="<?php echo Settings::$COUNTRY_BASE_URL . '/admin/' . $nextUri; ?>">
    <input type="submit" value="<?php echo t('Save & Continue'); ?>" class="submitArrow">
    <input type="submit" value="<?php echo t('Save'); ?>" name="saveonly" class="submitNoArrow" onclick="document.adminForm.redirect.value=''" style="margin-right:1em;">
    </form>


    </div>

    <div class="clear"></div>

	</div>
<div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
</div>

</body>
</html>
