<?php

// template for page that contains an EditTable

// need $pageTitle and $nextUri variables from these includes

ob_start();
require_once('views/scripts/header.phtml');
$header = ob_get_contents();
ob_end_clean();

ob_start();
require_once('views/scripts/nav-admin.phtml');
$nav = ob_get_contents();
ob_end_clean();

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title><?php echo $this->translation['Application Name'];?> | <?php echo $this->pageTitle; ?></title>
	<?php
	require_once('views/helpers/ScriptContainer.php');
	print ScriptContainer::$instance->renderCSSHead();
	print ScriptContainer::$instance->renderJSHead();
	?>
</head>
<body  class="yui-skin-sam">
	<div id="pageHolder">
		<div id="header"><?php echo $header; ?></div>
		<div id="content" class="adminDiv">

			<form method="post" name="adminForm">

			<div id="navAdmin"><?php echo $nav;?></div>

			<div id="contentAdmin">
				<h1><?php echo $this->pageTitle; ?></h1>

			<table class="settings">
				<thead>
					<tr><th>Field</th><th>Display</th><th>Label</th><th>Options</th></tr>
				</thead>
				<tbody>
					<tr><td class="fieldTitle">Employee</td>
					<td></td>
					<td><input type="text" name="label_employee" value="<?php echo $this->label_employee; ?>"></td>
					<td></td></tr>

					<tr><td class="fieldTitle">Employees</td>
					<td></td>
					<td><input type="text" name="label_employees" value="<?php echo $this->label_employees; ?>"></td>
					<td></td></tr>

					<tr><td class="fieldTitle">Employer</td>
					<td></td>
					<td><input type="text" name="label_employer" value="<?php echo $this->label_employer; ?>"></td>
					<td></td></tr>

					<tr><td class="fieldTitle">Employee Code</td>
					<td></td>
					<td><input type="text" name="label_employee_code" value="<?php echo $this->label_employee_code; ?>"></td>
					<td></td></tr>


					<tr><td class="fieldTitle">Local Currency</td>
					<td></td>
					<td><input type="text" name="label_currency" value="<?php echo $this->label_currency; ?>"></td>
					<td></td></tr>

					<tr><td class="fieldTitle">Partner</td>
					<td><input type="checkbox" name="check_partner" <?php if($this->check_partner) echo 'checked'; ?> id="check_partner"></td>
					<td><input type="text" name="label_partner" value="<?php echo $this->label_partner; ?>"></td>
					<td></td></tr>

					<tr><td class="fieldTitle">Sub Partner</td>
					<td><input type="checkbox" name="check_sub_partner" <?php if($this->check_sub_partner) echo 'checked'; ?> id="check_sub_partner"></td>
					<td><input type="text" name="label_sub_partner" value="<?php echo $this->label_sub_partner; ?>"></td>
					<td></td></tr>

					<tr><td class="fieldTitle">Type of Partner</td>
					<td><input type="checkbox" name="check_type" <?php if($this->check_type) echo 'checked'; ?> id="check_type"></td>
					<td><input type="text" name="label_type" value="<?php echo $this->label_type; ?>"></td>
					<td><a href="<?php echo $this->base_url;?>/admin/employee-partner-type" onclick="return submitAdminForm(this);"><?php tp('Add/Edit');?></a></td></tr>

					<tr><td class="fieldTitle">Funder</td>
					<td><input type="checkbox" name="check_funder" <?php if($this->check_funder) echo 'checked'; ?> id="check_funder"></td>
					<td><input type="text" name="label_funder" value="<?php echo $this->label_funder; ?>"></td>
					<td><a href="<?php echo $this->base_url;?>/admin/employee-partner-funding" onclick="return submitAdminForm(this);"><?php tp('Add/Edit');?></a></td></tr>

					<tr><td class="fieldTitle"><?php tp('Employee');?> Base</td>
					<td><input type="checkbox" name="check_base" <?php if($this->check_base) echo 'checked'; ?> id="check_base"></td>
					<td><input type="text" name="label_base" value="<?php echo $this->label_base; ?>"></td>
					<td><a href="<?php echo $this->base_url;?>/admin/employee-base" onclick="return submitAdminForm(this);"><?php tp('Add/Edit');?></a></td></td></tr>

					<tr><td class="fieldTitle">Site Type</td>
					<td><input type="checkbox" name="check_site_type" <?php if($this->check_site_type) echo 'checked'; ?> id="check_site_type"></td>
					<td></td>
					<td><a href="<?php echo $this->base_url;?>/admin/employee-site-type" onclick="return submitAdminForm(this);"><?php tp('Add/Edit');?></a></td></td></tr>

					<tr><td class="fieldTitle">Full Time</td>
					<td><input type="checkbox" name="check_full_time" <?php if($this->check_full_time) echo 'checked'; ?> id="check_full_time"></td>
					<td><input type="text" name="label_full_time" value="<?php echo $this->label_full_time; ?>"></td>
					<td><a href="<?php echo $this->base_url;?>/admin/employee-fulltime" onclick="return submitAdminForm(this);"><?php tp('Add/Edit');?></a></td></td></tr>

					<tr><td class="fieldTitle">Funded hours per week</td>
					<td><input type="checkbox" name="check_funded_hours_per_week" <?php if($this->check_funded_hours_per_week) echo 'checked'; ?> id="check_funded_hours_per_week"></td>
					<td><input type="text" name="label_funded_hours_per_week" value="<?php echo $this->label_funded_hours_per_week; ?>"></td>
					<td></td></tr>

					<tr><td class="fieldTitle">Professional Qualification</td>
					<td></td>
					<td><input type="text" name="label_cadre" value="<?php echo $this->label_cadre; ?>"></td>
					<td><a href="<?php echo $this->base_url;?>/admin/employee-qualification" onclick="return submitAdminForm(this);"><?php tp('Add/Edit');?></a></td></tr>

					<tr><td class="fieldTitle">Staff Category</td>
					<td><input type="checkbox" name="check_staff_category" <?php if($this->check_staff_category) echo 'checked'; ?> id="check_staff_category"></td>
					<td><input type="text" name="label_staff_category" value="<?php echo $this->label_staff_category; ?>"></td>
					<td><a href="<?php echo $this->base_url;?>/admin/employee-category" onclick="return submitAdminForm(this);"><?php tp('Add/Edit');?></a></td></tr>

					<tr><td class="fieldTitle">Registration Number</td>
					<td><input type="checkbox" name="check_registration_number" <?php if($this->check_registration_number) echo 'checked'; ?> id="check_registration_number"></td>
					<td><input type="text" name="label_registration_number" value="<?php echo $this->label_registration_number; ?>"></td>
					<td></td></tr>

					<tr><td class="fieldTitle">Nationality</td>
					<td><input type="checkbox" name="check_nationality" <?php if($this->check_nationality) echo 'checked'; ?> id="check_nationality"></td>
					<td><input type="text" name="label_nationality" value="<?php echo $this->label_nationality; ?>"></td>
					<td><a href="<?php echo $this->base_url;?>/admin/preservice-nationalities" onclick="return submitAdminForm(this);"><?php tp('Add/Edit');?></a></td></tr>

					<tr><td class="fieldTitle">Race</td>
					<td><input type="checkbox" name="check_race" <?php if($this->check_race) echo 'checked'; ?> id="check_race"></td>
					<td><input type="text" name="label_race" value="<?php echo $this->label_race; ?>"></td>
					<td><a href="<?php echo $this->base_url;?>/admin/person-race" onclick="return submitAdminForm(this);"><?php tp('Add/Edit');?></a></td></tr>
					
					<tr><td class="fieldTitle">Date of Birth</td>
					<td><input type="checkbox" name="check_date_of_birth" <?php if($this->check_date_of_birth) echo 'checked'; ?> id="check_date_of_birth"></td>
					<td><input type="text" name="label_date_of_birth" value="<?php echo $this->label_date_of_birth; ?>"></td>
					<td></td></tr>

					<tr><td class="fieldTitle">Disability</td>
					<td><input type="checkbox" name="check_disability" <?php if($this->check_disability) echo 'checked'; ?> id="check_disability"></td>
					<td><input type="text" name="label_disability" value="<?php echo $this->label_disability; ?>"></td>
					<td></td></tr>

					<tr><td class="fieldTitle">Disability Comments</td>
					<td></td>
					<td><input type="text" name="label_disability_comments" value="<?php echo $this->label_disability_comments; ?>"></td>
					<td></td></tr>

					<tr><td class="fieldTitle">Annual Cost</td>
					<td><input type="checkbox" name="check_annual_cost" <?php if($this->check_annual_cost) echo 'checked'; ?> id="check_annual_cost"></td>
					<td><input type="text" name="label_annual_cost" value="<?php echo $this->label_annual_cost; ?>"></td>
					<td></td></tr>

					<tr><td class="fieldTitle">ID/Passport Number </td>
					<td><input type="checkbox" name="check_other_id" <?php if($this->check_other_id) echo 'checked'; ?> id="check_other_id"></td>
					<td><input type="text" name="label_other_id" value="<?php echo $this->label_other_id; ?>"></td>
					<td></td></tr>

					<tr><td class="fieldTitle">Primary Role</td>
					<td><input type="checkbox" name="check_primary_role" <?php if($this->check_primary_role) echo 'checked'; ?> id="check_primary_role"></td>
					<td><input type="text" name="label_primary_role" value="<?php echo $this->label_primary_role; ?>"></td>
					<td><a href="<?php echo $this->base_url;?>/admin/employee-role" onclick="return submitAdminForm(this);"><?php tp('Add/Edit');?></a></td></tr>

					<tr><td class="fieldTitle">Importance</td>
					<td><input type="checkbox" name="check_importance" <?php if($this->check_importance) echo 'checked'; ?> id="check_importance"></td>
					<td><input type="text" name="label_importance" value="<?php echo $this->label_importance; ?>"></td>
					<td><a href="<?php echo $this->base_url;?>/admin/employee-partner-importance" onclick="return submitAdminForm(this);"><?php tp('Add/Edit');?></a></td></tr>

					<tr><td class="fieldTitle">Contract end date</td>
					<td><input type="checkbox" name="check_contract_end_date" <?php if($this->check_contract_end_date) echo 'checked'; ?> id="check_contract_end_date"></td>
					<td></td>
					<td></td></tr>

					<tr><td class="fieldTitle">Agreement end date</td>
					<td><input type="checkbox" name="check_agreement_end_date" <?php if($this->check_agreement_end_date) echo 'checked'; ?> id="check_agreement_end_date"></td>
					<td></td>
					<td></td></tr>

					<tr><td class="fieldTitle">Intended Transition</td>
					<td><input type="checkbox" name="check_intended_transition" <?php if($this->check_intended_transition) echo 'checked'; ?> id="check_intended_transition"></td>
					<td><input type="text" name="label_intended_transition" value="<?php echo $this->label_intended_transition; ?>"></td>
					<td><a href="<?php echo $this->base_url;?>/admin/employee-transition" onclick="return submitAdminForm(this);"><?php tp('Add/Edit');?></a></td></tr>

					<tr><td class="fieldTitle">Transition confirmed</td>
					<td><input type="checkbox" name="check_transition_confirmed" <?php if($this->check_transition_confirmed) echo 'checked'; ?> id="check_transition_confirmed"></td>
					<td></td>
					<td></td></tr>

					<tr><td class="fieldTitle">Actual Transition</td>
					<td><input type="checkbox" name="check_transition_complete" <?php if($this->check_transition_complete) echo 'checked'; ?> id="check_transition_complete"></td>
					<td></td>
					<td></td></tr>

					<tr><td class="fieldTitle">Actual Transition Date</td>
					<td><input type="checkbox" name="check_transition_complete_date" <?php if($this->check_transition_complete_date) echo 'checked'; ?> id="check_transition_complete_date"></td>
					<td></td>
					<td></td></tr>

					<tr><td class="fieldTitle">Incoming partner</td>
					<td><input type="checkbox" name="check_incoming_partner" <?php if($this->check_incoming_partner) echo 'checked'; ?> id="check_incoming_partner"></td>
					<td><input type="text" name="label_incoming_partner" value="<?php echo $this->label_incoming_partner; ?>"></td>
					<td></td></tr>

					<tr><td class="fieldTitle">Relationship</td>
					<td><input type="checkbox" name="check_relationship" <?php if($this->check_relationship) echo 'checked'; ?> id="check_relationship"></td>
					<td><input type="text" name="label_relationship" value="<?php echo $this->label_relationship; ?>"></td>
					<td><a href="<?php echo $this->base_url;?>/admin/employee-relationship" onclick="return submitAdminForm(this);"><?php tp('Add/Edit');?></a></td></tr>

					<tr><td class="fieldTitle">Referral Mechanism</td>
					<td><input type="checkbox" name="check_referral_mechanism" <?php if($this->check_referral_mechanism) echo 'checked'; ?> id="check_referral_mechanism"></td>
					<td><input type="text" name="label_referral_mechanism" value="<?php echo $this->label_referral_mechanism; ?>"></td>
					<td><a href="<?php echo $this->base_url;?>/admin/employee-referral" onclick="return submitAdminForm(this);"><?php tp('Add/Edit');?></a></td></tr>

					<tr><td class="fieldTitle">CHW Supervisor</td>
					<td><input type="checkbox" name="check_chw_supervisor" <?php if($this->check_chw_supervisor) echo 'checked'; ?> id="check_chw_supervisor"></td>
					<td><input type="text" name="label_chw_supervisor" value="<?php echo $this->label_chw_supervisor; ?>"></td>
					<td></td></tr>

					<tr><td class="fieldTitle">Trainings provided</td>
					<td><input type="checkbox" name="check_trainings_provided" <?php if($this->check_trainings_provided) echo 'checked'; ?> id="check_trainings_provided"></td>
					<td><input type="text" name="label_trainings_provided" value="<?php echo $this->label_trainings_provided; ?>"></td>
					<td><a href="<?php echo $this->base_url;?>/admin/employee-training-provided" onclick="return submitAdminForm(this);"><?php tp('Add/Edit');?></a></td></tr>

					<tr><td class="fieldTitle">Courses Completed</td>
					<td><input type="checkbox" name="check_courses_completed" <?php if($this->check_courses_completed) echo 'checked'; ?> id="check_courses_completed"></td>
					<td><input type="text" name="label_courses_completed" value="<?php echo $this->label_courses_completed; ?>"></td>
					<td></td></tr>

					<tr><td class="fieldTitle">Site Name</td>
					<td><input type="checkbox" name="check_site_name" <?php if($this->check_site_name) echo 'checked'; ?> id="check_site_name"></td>
					<td></td>
					<td></td></tr>

					<tr><td class="fieldTitle">Salary</td>
					<td><input type="checkbox" name="check_salary" <?php if($this->check_salary) echo 'checked'; ?> id="check_salary"></td>
					<td><input type="text" name="label_salary" value="<?php echo $this->label_salary; ?>"></td>
					<td></td></tr>

					<tr><td class="fieldTitle">Benefits</td>
					<td><input type="checkbox" name="check_benefits" <?php if($this->check_benefits) echo 'checked'; ?> id="check_benefits"></td>
					<td><input type="text" name="label_benefits" value="<?php echo $this->label_benefits; ?>"></td>
					<td></td></tr>

					<tr><td class="fieldTitle">Additional Expenses</td>
					<td><input type="checkbox" name="check_additional_expenses" <?php if($this->check_additional_expenses) echo 'checked'; ?> id="check_additional_expenses"></td>
					<td><input type="text" name="label_additional_expenses" value="<?php echo $this->label_additional_expenses; ?>"></td>
					<td></td></tr>

					<tr><td class="fieldTitle">Stipend</td>
					<td><input type="checkbox" name="check_stipend" <?php if($this->check_stipend) echo 'checked'; ?> id="check_stipend"></td>
					<td><input type="text" name="label_stipend" value="<?php echo $this->label_stipend; ?>"></td>
					<td></td></tr>
					
					<tr><td class="fieldTitle">Hours per Mechanism</td>
					<td><input type="checkbox" name="check_hours_per_mechanism" <?php if($this->check_hours_per_mechanism) echo 'checked'; ?> id="check_hours_per_mechanism"></td>
					<td><input type="text" name="label_hours_per_mechanism" value="<?php echo $this->label_hours_per_mechanism; ?>"></td>
					<td></td></tr>
					
					<tr><td class="fieldTitle">Annual Cost to Mechanism</td>
					<td><input type="checkbox" name="check_annual_cost_to_mechanism" <?php if($this->check_annual_cost_to_mechanism) echo 'checked'; ?> id="check_annual_cost_to_mechanism"></td>
					<td><input type="text" name="label_annual_cost_to_mechanism" value="<?php echo $this->label_annual_cost_to_mechanism; ?>"></td>
					<td></td></tr>
					
					<tr><td class="fieldTitle">Landing Page Comments</td>
					<td><input type="checkbox" name="check_employee_header" <?php if($this->check_employee_header) echo 'checked'; ?> id="check_employee_header"></td>
					<td><input type="text" name="employee_header" value="<?php echo $this->employee_header; ?>"></td>
					<td></td></tr>
				</tbody>
			</table>

			<input type="hidden" name="redirect" value="<?php echo Settings::$COUNTRY_BASE_URL . '/admin/' . $nextUri; ?>">
			<input type="submit" value="Save" name="saveonly" class="submitNoArrow" onclick="document.adminForm.redirect.value=''" style="margin-right:1em;">
			</form>


			</div>

			<div class="clear"></div>

		</div>
		<div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
	</div>

</body>
</html>