<?php 

// template for page that contains an EditTable

// need $pageTitle and $nextUri variables from these includes
 

ob_start();
require_once('views/scripts/header.phtml');
$header = ob_get_contents();
ob_end_clean(); 

ob_start();
require_once('views/scripts/nav-admin.phtml');
$nav = ob_get_contents();
ob_end_clean(); 

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title><?php echo $this->translation['Application Name'];?> | <?php echo $this->pageTitle; ?></title>
<?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>

	<script type='text/javascript'>
		function submitAdminForm () { return true;} // Added because was missing. Referenced by lots of onlick properties.
	</script>

</head>
<body  class="yui-skin-sam">
<div id="pageHolder">
  <div id="header"><?php echo $header; ?></div>
  <div id="content" class="adminDiv">
    
    <form method="post" name="adminForm" id="adminForm" action="" enctype="multipart/form-data">
    
    <div id="navAdmin"><?php echo $nav;?></div>
    
    <div id="contentAdmin">
    <h1><?php echo $this->pageTitle; ?></h1>
    <br/>
        <div class="fieldInput"><div class="fieldLabel">Website Style:</div>
            <?php echo $this->siteStyleDropdown;?>
        </div>

    <div class="clear"></div>
    <br/>    
    
    <input type="submit" value="<?php tp('Save'); ?>" name="saveonly" class="submitNoArrow" onclick="document.adminForm.redirect.value=''" style="margin-right:1em;" />
    </form>
    
    
    </div>
    
    <div class="clear"></div>
	    
	</div>
<div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
</div>

</body>
</html>