<?php 
// template for page that contains an EditTable
// need $pageTitle and $nextUri variables from these includes
ob_start();
require_once('views/scripts/header.phtml');
$header = ob_get_contents();
ob_end_clean(); 

ob_start();
require_once('views/scripts/nav-admin.phtml');
$nav = ob_get_contents();
ob_end_clean(); 

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title><?php echo $this->translation['Application Name'];?> | <?php echo $this->pageTitle; ?></title>
<?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>
	<script type='text/javascript'>
		function submitAdminForm () { return true;} // Added because was missing. Referenced by lots of onlick properties.
	</script>

</head>
<body  class="yui-skin-sam">
<div id="pageHolder">
  <div id="header"><?php echo $header; ?></div>
  <div id="content" class="adminDiv">

    <div id="navAdmin"><?php echo $nav;?></div>
    
    <div id="contentAdmin">
	    <h1><?php echo t($this->pageTitle); ?></h1>
	    <br/>
	    
	    <?php if(isset($formPrefix)) echo $formPrefix . '<br/><br/>'; ?> 
	    <?php 
	      if(isset($this->checkbox) && is_array($this->checkbox)) { // render checkbox
	        echo '<input type="checkbox" value="1" name="'.$this->checkbox['name'].'" id="'.$this->checkbox['name'].'" '.($this->checkbox['value']?' checked':'').'>';
	        echo '<label for="'.$this->checkbox['name'].'">'.$this->checkbox['label'].'</label>';
	        echo '<br/><br/>';        
	      }
	     ?>
	     
	    <?php echo $this->extraHtml; ?>    
	    <?php echo $this->editTable; ?>
    
		<br/>    

		<div id="personSearchWrapper">
		<?php require_once 'views/scripts/person/_search.phtml'; ?>
		</div>



	<div class="clear"></div>
		<?php if ($this->showMerge) { /* using hidden fields technically I cannot wrap the radio buttons in the data table in this form */ ?>
		<form method="get" name="adminForm" id="adminForm" action="" enctype="multipart/form-data">
		<input type="hidden" name="person_from_id">
		<input type="hidden" name="person_to_id">
		<input type="hidden" name="submitted">
		<input id="mergebutton" type="submit" value="<?php tp('Merge'); ?>" class="submitArrow" />
		</form>
		<?php } ?>
		<div class="clear"></div>
	</div>
  </div>
  <div class="clear"></div>

  <div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>

  <div class="clear"></div>

</div>

<script type="text/javascript">

$(document).ready(function () { // form submit, cannot access checkboxes normally.
	$('#mergebutton').click(function (e) {
		e.preventDefault();
		var f = $('#adminForm');
		f.find('input[name=person_from_id]').val ( $('#people input[group=merge_from]:checked').val() );
		f.find('input[name=person_to_id]').val ( $('#people input[group=merge_to]:checked').val() );
		f.find('input[name=submitted]').val(1);
		f.submit();
	});
});
</script>

</body>
</html>



