<?php

// template for page that contains an EditTable

// need $pageTitle and $nextUri variables from these includes

ob_start();
require_once('views/scripts/header.phtml');
$header = ob_get_contents();
ob_end_clean();

ob_start();
require_once('views/scripts/nav-admin.phtml');
$nav = ob_get_contents();
ob_end_clean();

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title><?php echo t($this->translation['Application Name']);?> | <?php echo t($this->pageTitle); ?></title>
<?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>
</head>
<body  class="yui-skin-sam">
<div id="pageHolder">
  <div id="header"><?php echo $header; ?></div>
  <div id="content" class="adminDiv">

    <form method="post" name="adminForm">

    <div id="navAdmin"><?php echo $nav;?></div>

    <div id="contentAdmin">
    <h1><?php echo t($this->pageTitle); ?></h1>

    <table class="settings">
    <thead>
    <tr><th><?php echo t('Field'); ?></th><th><?php echo t('Display'); ?></th><th><?php echo t('Label'); ?></th><th><?php echo t('Options'); ?></th></tr>
    </thead>
   <tr><td class="fieldTitle"><?php echo t('Is Active'); ?></td>
   	<td><input type="checkbox" name="check_people_active" <?php if($this->check_people_active) echo 'checked'; ?> id="check_people_active"></td>
   	<td><input type="text" name="label_people_active" value="<?php echo $this->label_people_active; ?>"></td>
   	<td></td>
   </tr>
   <tr><td class="fieldTitle"><?php echo t('Title'); ?></td>
   	<td><input type="checkbox" name="check_people_title" <?php if($this->check_people_title) echo 'checked'; ?> id="check_people_title"></td>
   	<td><input type="text" name="label_people_title" value="<?php echo $this->label_people_title; ?>"></td>
   	<td><a href="<?php echo $this->base_url;?>/admin/people-title" onclick="return submitAdminForm(this);"><?php echo t('Add/Edit'); ?></a></td>
   </tr>
  <tr><td class="fieldTitle"><?php echo t('First Name'); ?></td>
  	<td></td>
  	<td><input type="text" name="label_people_first" value="<?php echo $this->label_people_first; ?>"></td>
  	<td></td>
  </tr>
   <tr><td class="fieldTitle"><?php echo t('Middle Name'); ?></td>
  	<td><input type="checkbox" name="check_people_middle" <?php if($this->check_people_middle) echo 'checked'; ?> id="check_people_middle"></td>
  	<td><input type="text" name="label_people_middle" value="<?php echo $this->label_people_middle; ?>"></td>
  	<td><input type="checkbox" name="check_middle_last" <?php if($this->check_middle_last) echo 'checked'; ?> id="check_middle_last"><label for="check_middle_last"><?php echo t('Display Last'); ?></label></td>
  </tr>
 <tr><td class="fieldTitle"><?php echo t('Last Name'); ?></td>
  	<td></td>
  	<td><input type="text" name="label_people_last" value="<?php echo $this->label_people_last; ?>"></td>
  	<td></td>
  </tr>
   <tr><td class="fieldTitle"><?php echo t('Suffix'); ?></td>
   	<td><input type="checkbox" name="check_people_suffix" <?php if($this->check_people_suffix) echo 'checked'; ?> id="check_people_suffix"></td>
   	<td><input type="text" name="label_people_suffix" value="<?php echo $this->label_people_suffix; ?>"></td>
   	<td><a href="<?php echo $this->base_url;?>/admin/people-suffix" onclick="return submitAdminForm(this);"><?php echo t('Add/Edit'); ?></a></td>
   </tr>
   <tr><td class="fieldTitle"><?php echo t('National ID'); ?></td>
   	<td><input type="checkbox" name="check_people_national" <?php if($this->check_people_national) echo 'checked'; ?> id="check_people_national"></td>
   	<td><input type="text" name="label_people_national" value="<?php echo $this->label_people_national; ?>"></td>
   	<td></td>
   </tr>
    <tr><td class="fieldTitle"><?php echo t('File Number'); ?></td>
   	<td> <input type="checkbox" name="check_people_file_num" <?php if($this->check_people_file_num) echo 'checked'; ?> id="check_people_file_num"></td>
   	<td><input type="text" name="label_people_file_num" value="<?php echo $this->label_people_file_num; ?>"></td>
   	<td></td>
   </tr>
   
   <!-- TA:17: 09/10/2014 -->
  <tr><td class="fieldTitle"><?php echo t('Birthdate'); ?></td>
    <td><input type="checkbox" name="check_people_birthdate" <?php if($this->check_people_birthdate) echo 'checked'; ?> id="check_people_birthdate"></td>
   	<td></td>
    <td></td>
  </tr>
  
   <tr><td class="fieldTitle"><?php echo t('Age'); ?></td>
   	<td><input type="checkbox" name="check_people_age" <?php if($this->check_people_age) echo 'checked'; ?> id="check_people_age"></td>
   	<td></td>
   	<td></td>
   </tr>
  
   <tr><td class="fieldTitle"><?php echo t('Gender'); ?></td>
   	<td><input type="checkbox" name="check_people_gender" <?php if($this->check_people_gender) echo 'checked'; ?> id="check_people_gender"></td>
   	<td><input type="text" name="label_people_gender" value="<?php echo $this->label_people_gender; ?>"></td>
   	<td></td>
   </tr>
  <tr><td class="fieldTitle"><?php echo t('Home Address'); ?></td>
   	<td><input type="checkbox" name="check_people_home_address" <?php if($this->check_people_home_address) echo 'checked'; ?> id="check_people_home_address"></td>
   	<td></td>
   	<td></td>
   </tr>
  <tr><td class="fieldTitle"><?php echo t('Address 1'); ?></td>
    <td></td>
    <td><input type="text" name="label_address1" value="<?php echo $this->label_address1; ?>"></td>
    <td></td>
   </tr>
  <tr><td class="fieldTitle"><?php echo t('Address 2'); ?></td>
    <td></td>
    <td><input type="text" name="label_address2" value="<?php echo $this->label_address2; ?>"></td>
    <td></td>
   </tr>

 <tr><td class="fieldTitle"><?php echo t('Home phone'); ?></td>
   	<td><input type="checkbox" name="check_people_home_phone" <?php if($this->check_people_home_phone) echo 'checked'; ?> id="check_people_home_phone"></td>
    <td><input type="text" name="label_home_phone" value="<?php echo $this->label_home_phone; ?>"></td>
   	<td></td>
   </tr>
 <tr><td class="fieldTitle"><?php echo t('Second email'); ?></td>
   	<td><input type="checkbox" name="check_people_second_email" <?php if($this->check_people_second_email) echo 'checked'; ?> id="check_people_second_email"></td>
   	<td></td>
   	<td></td>
   </tr>
 <tr><td class="fieldTitle"><?php echo t('Fax'); ?></td>
   	<td><input type="checkbox" name="check_people_fax" <?php if($this->check_people_fax) echo 'checked'; ?> id="check_people_fax"></td>
   	<td></td>
   	<td></td>
   </tr>
 <tr><td class="fieldTitle"><?php echo t('Qualification'); ?></td>
   	<td></td>
   	<td></td>
   	<td><a href="<?php echo $this->base_url;?>/admin/people-qual" onclick="return submitAdminForm(this);"><?php echo t('Add/Edit'); ?></a></td>
   </tr>



 <tr><td class="fieldTitle"><?php echo t('External Classes'); ?></td>
   	<td><input type="checkbox" name="check_external_classes" <?php if($this->check_external_classes) echo 'checked'; ?> id="check_external_classes"></td>
   	<td></td>
 </tr>



 <tr><td class="fieldTitle"><?php echo t('M&E Responsibility'); ?></td>
   	<td><input type="checkbox" name="check_responsibility_me" <?php if($this->check_responsibility_me) echo 'checked'; ?> id="check_responsibility_me"></td>
   	<td><input type="text" name="label_responsibility_me" value="<?php echo $this->label_responsibility_me; ?>"></td>
   	<!--<td><a href="<?php echo $this->base_url;?>/admin/people-meresponsibility" onclick="return submitAdminForm(this);"><?php echo t('Add/Edit'); ?></a></td>-->
   	<td></td>
 </tr>

 
 
 <tr><td class="fieldTitle"><?php echo t('Primary Responsibility'); ?></td>
   	<td><input type="checkbox" name="check_primary_responsibility" <?php if($this->check_primary_responsibility) echo 'checked'; ?> id="check_attend_reason"></td>
   	<td><input type="text" name="label_primary_responsibility" value="<?php echo $this->label_primary_responsibility; ?>"></td>
   	<td><a href="<?php echo $this->base_url;?>/admin/people-primaryresp" onclick="return submitAdminForm(this);"><?php echo t('Add/Edit'); ?></a></td>
 </tr>

 
 
 <tr><td class="fieldTitle"><?php echo t('Secondary Responsibility'); ?></td>
   	<td><input type="checkbox" name="check_secondary_responsibility" <?php if($this->check_secondary_responsibility) echo 'checked'; ?> id="check_attend_reason"></td>
   	<td><input type="text" name="label_secondary_responsibility" value="<?php echo $this->label_secondary_responsibility; ?>"></td>
   	<td><a href="<?php echo $this->base_url;?>/admin/people-secondaryresp" onclick="return submitAdminForm(this);"><?php echo t('Add/Edit'); ?></a></td>
 </tr>
 
 
 
 <tr><td class="fieldTitle"><?php echo t('Reason Attending'); ?></td>
   	<td><input type="checkbox" name="check_attend_reason" <?php if($this->check_attend_reason) echo 'checked'; ?> id="check_attend_reason"></td>
   	<td><input type="text" name="label_attend_reason" value="<?php echo $this->label_attend_reason; ?>"></td>
   	<td><a href="<?php echo $this->base_url;?>/admin/people-attendreason" onclick="return submitAdminForm(this);"><?php echo t('Add/Edit'); ?></a></td>
 </tr>
 
 <tr><td class="fieldTitle"><?php echo t('Highest Education Level'); ?></td>
   	<td><input type="checkbox" name="check_highest_ed_level" <?php if($this->check_highest_ed_level) echo 'checked'; ?> id="check_highest_ed_level"></td>
   	<td><input type="text" name="label_highest_ed_level" value="<?php echo $this->label_highest_ed_level; ?>"></td>
   	<td><a href="<?php echo $this->base_url;?>/admin/people-highestedulevel" onclick="return submitAdminForm(this);"><?php echo t('Add/Edit'); ?></a></td>
 </tr>

 <tr><td class="fieldTitle"><?php echo t('Comments'); ?></td>
 <!-- TA:17: 09/09/2014 -->
    <td><input type="checkbox" name="check_people_comments" <?php if($this->check_people_comments) echo 'checked'; ?> id="check_people_comments"></td>
    <td><input type="text" name="label_comments" value="<?php echo $this->label_comments; ?>"></td>
    <td></td>
 </tr>
   
 <tr><td class="fieldTitle"><?php echo t('Recommended topics'); ?></td>
   	<td></td>
   	<td></td>
   	<td><a href="<?php echo $this->base_url;?>/admin/training-recommend" onclick="return submitAdminForm(this);"><?php echo t('Add/Edit'); ?></a></td>
   </tr>
 <tr><td class="fieldTitle"><?php echo t('Responsibility'); ?></td>
   	<td></td>
   	<td></td>
   	<td><a href="<?php echo $this->base_url;?>/admin/people-primaryresp" onclick="return submitAdminForm(this);"><?php echo t('Add/Edit'); ?></a></td>
   </tr>

 <tr><td class="fieldTitle"><?php echo t('Custom field'); ?> 1</td>
    <td><input type="checkbox" name="check_people_custom3" <?php if($this->check_people_custom3) echo 'checked'; ?> id="check_people_custom3"></td>
    <td><input type="text" name="label_people_custom3" value="<?php echo $this->label_people_custom3; ?>"></td>
    <td></td>
 </tr>
 <tr><td class="fieldTitle"><?php echo t('Custom field'); ?> 2</td>
    <td><input type="checkbox" name="check_people_custom4" <?php if($this->check_people_custom4) echo 'checked'; ?> id="check_people_custom4"></td>
    <td><input type="text" name="label_people_custom4" value="<?php echo $this->label_people_custom4; ?>"></td>
    <td></td>
 </tr>
 <tr><td class="fieldTitle"><?php echo t('Custom field'); ?> 3</td>
    <td><input type="checkbox" name="check_people_custom5" <?php if($this->check_people_custom5) echo 'checked'; ?> id="check_people_custom5"></td>
    <td><input type="text" name="label_people_custom5" value="<?php echo $this->label_people_custom5; ?>"></td>
    <td></td>
  <tr><td class="fieldTitle"><?php echo t('Custom field'); ?> 4</td>
   	<td><input type="checkbox" name="check_people_custom1" <?php if($this->check_people_custom1) echo 'checked'; ?> id="check_people_custom1"></td>
   	<td><input type="text" name="label_people_custom1" value="<?php echo $this->label_people_custom1; ?>"></td>
   	<td></td>
 </tr>
 <tr><td class="fieldTitle"><?php echo t('Custom field'); ?> 5</td>
   	<td><input type="checkbox" name="check_people_custom2" <?php if($this->check_people_custom2) echo 'checked'; ?> id="check_people_custom2"></td>
   	<td><input type="text" name="label_people_custom2" value="<?php echo $this->label_people_custom2; ?>"></td>
   	<td></td>
 </tr>
 <tr><td class="fieldTitle"><?php echo t('Active trainer'); ?></td>
   	<td></td>
   	<td></td>
   	<td><a href="<?php echo $this->base_url;?>/admin/people-active-trainer" onclick="return submitAdminForm(this);"><?php echo t('Add/Edit'); ?></a></td>
   </tr>
 <tr><td class="fieldTitle"><?php echo t('Trainer Types'); ?></td>
   	<td></td>
   	<td></td>
   	<td><a href="<?php echo $this->base_url;?>/admin/people-types" onclick="return submitAdminForm(this);"><?php echo t('Add/Edit'); ?></a></td>
   </tr>
<tr><td class="fieldTitle"><?php echo t('Trainer skills'); ?></td>
   	<td></td>
   	<td></td>
   	<td><a href="<?php echo $this->base_url;?>/admin/people-skills" onclick="return submitAdminForm(this);"><?php echo t('Add/Edit'); ?></a></td>
   </tr>
<tr><td class="fieldTitle"><?php echo t('Languages'); ?></td>
   	<td></td>
   	<td></td>
   	<td><a href="<?php echo $this->base_url;?>/admin/people-languages" onclick="return submitAdminForm(this);"><?php echo t('Add/Edit'); ?></a></td>
   </tr>
<tr><td class="fieldTitle"><?php echo t('Affiliations'); ?></td>
   	<td><input type="checkbox" name="check_trainer_affiliations" <?php if($this->check_trainer_affiliations) echo 'checked'; ?> id="check_trainer_affiliations"></td>
   	<td></td>
   	<td><a href="<?php echo $this->base_url;?>/admin/people-affiliations" onclick="return submitAdminForm(this);"><?php echo t('Add/Edit'); ?></a></td>
   </tr>
 <tr><td class="fieldTitle"><?php echo t('People Approval'); ?></td>
    <td></td>
    <td></td>
    <td><input type="checkbox" name="check_approval_mod" <?php if($this->check_approval_mod) echo 'checked'; ?> id="check_approval_mod"><label for="check_approval_mod"><?php echo t('Enabled'); ?></label></td>
  </tr>
  
  <!-- TA:17: 09/09/2014 -->
  <tr><td class="fieldTitle"><?php echo t('Facilitator Information'); ?></td>
    <td><input type="checkbox" name="check_people_facilitator" <?php if($this->check_people_facilitator) echo 'checked'; ?> id="check_people_facilitator"></td>
   	<td></td>
    <td></td>
  </tr>
  
  <!-- TA:#331.1 -->
  <tr><td class="fieldTitle"><?php echo t('People Education'); ?></td>
    <td></td>
    <td></td>
    <td><input type="checkbox" name="check_education_mod" <?php if($this->check_education_mod) echo 'checked'; ?> id="check_education_mod"><label for="check_education_mod"><?php echo t('Enabled'); ?></label></td>
  </tr>
  
  <!-- TA:#331.1 -->
  <tr><td class="fieldTitle"><?php echo t('Education History'); ?></td>
   	<td></td>
   	<td><input type="text" name="label_education_history" value="<?php echo $this->label_education_history; ?>"></td>
   	<td></td>
 </tr>
 
  <!-- TA:#331.1 -->
  <tr><td class="fieldTitle"><?php echo t('Type of Education'); ?></td>
   	<td></td>
   	<td><input type="text" name="label_type_of_education" value="<?php echo $this->label_type_of_education; ?>"></td>
   	<td><a href="<?php echo $this->base_url;?>/admin/people-educationtype" onclick="return submitAdminForm(this);"><?php echo t('Add/Edit'); ?></a></td>
 </tr>
 
 <!-- TA:#331.1 -->
  <tr><td class="fieldTitle"><?php echo t('Official School Name'); ?></td>
   	<td></td>
   	<td><input type="text" name="label_official_school_name" value="<?php echo $this->label_official_school_name; ?>"></td>
   	<td><a href="<?php echo $this->base_url;?>/admin/people-schoolname" onclick="return submitAdminForm(this);"><?php echo t('Add/Edit'); ?></a></td>
 </tr>
 
 <!-- TA:#331.1 -->
  <tr><td class="fieldTitle"><?php echo t('Education Country'); ?></td>
   	<td></td>
   	<td><input type="text" name="label_education_country" value="<?php echo $this->label_education_country; ?>"></td>
   	<td><a href="<?php echo $this->base_url;?>/admin/people-educationcountry" onclick="return submitAdminForm(this);"><?php echo t('Add/Edit'); ?></a></td>
 </tr>
 
 <!-- TA:#331.1 -->
  <tr><td class="fieldTitle"><?php echo t('Year of Graduation/Completion'); ?></td>
   	<td></td>
   	<td><input type="text" name="label_year_graduation" value="<?php echo $this->label_year_graduation; ?>"></td>
   	<td></td>
 </tr>
 
 <!-- TA:#331.2 -->
  <tr><td class="fieldTitle"><?php echo t('Participants Attestation'); ?></td>
    <td></td>
    <td></td>
    <td><input type="checkbox" name="check_attestation_mod" <?php if($this->check_attestation_mod) echo 'checked'; ?> id="check_attestation_mod"><label for="check_attestation_mod"><?php echo t('Enabled'); ?></label></td>
  </tr>
  
  <!-- TA:#331.2 -->
  <tr><td class="fieldTitle"><?php echo t('Attestation Progress'); ?></td>
   	<td></td>
   	<td><input type="text" name="label_attestation_progress" value="<?php echo $this->label_attestation_progress; ?>"></td>
   	<td></td>
 </tr>
 
  <!-- TA:#331.2 -->
  <tr><td class="fieldTitle"><?php echo t('Attestation Category'); ?></td>
   	<td></td>
   	<td><input type="text" name="label_attestation_category" value="<?php echo $this->label_attestation_category; ?>"></td>
   	<td><a href="<?php echo $this->base_url;?>/admin/people-attestationcategory" onclick="return submitAdminForm(this);"><?php echo t('Add/Edit'); ?></a></td>
 </tr>
 
 <!-- TA:#331.2 -->
  <tr><td class="fieldTitle"><?php echo t('Attestation Level'); ?></td>
   	<td></td>
   	<td><input type="text" name="label_attestation_level" value="<?php echo $this->label_attestation_level; ?>"></td>
   	<td><a href="<?php echo $this->base_url;?>/admin/people-attestationlevel" onclick="return submitAdminForm(this);"><?php echo t('Add/Edit'); ?></a></td>
 </tr>
 
 <!-- TA:#331.2 -->
  <tr><td class="fieldTitle"><?php echo t('Attestation Year'); ?></td>
   	<td></td>
   	<td><input type="text" name="label_attestation_year" value="<?php echo $this->label_attestation_year; ?>"></td>
   	<td></td>
 </tr>

</table>

    <input type="hidden" name="redirect" value="<?php echo Settings::$COUNTRY_BASE_URL . '/admin/' . $nextUri; ?>">
    <input type="submit" value="<?php echo t('Save'); ?>" name="saveonly" class="submitNoArrow" onclick="document.adminForm.redirect.value=''" style="margin-right:1em;">
    </form>


    </div>

    <div class="clear"></div>

	</div>
<div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
</div>

</body>
</html>