<?php 

// template for page that contains an EditTable

// need $pageTitle and $nextUri variables from these includes
  
ob_start();
require_once('views/scripts/header.phtml');
$header = ob_get_contents();
ob_end_clean(); 

ob_start();
require_once('views/scripts/nav-admin.phtml');
$nav = ob_get_contents();
ob_end_clean(); 

?>
<!DOCTYPE html>
<html>
	<head>
		<title><?php echo $this->translation['Application Name'];?> | <?php echo $this->pageTitle; ?></title>
<?php
	require_once('views/helpers/ScriptContainer.php');
	print ScriptContainer::$instance->renderCSSHead();
	print ScriptContainer::$instance->renderJSHead();
?>

		<style>
			fieldset input[type=text], fieldset select { margin-bottom:12px; width:95%; padding: .4em; }
			fieldset { padding:0; border:0; margin-top:25px; text-align : left; font-size : .9em }
			h1 { font-size: 1.2em; margin: .6em 0; }
			.ui-dialog .ui-state-error { padding: .3em; }
			.validateTips { border: 1px solid transparent; padding: 0.3em; }
		</style>
		<script>
			$(function() {
				$( "#dialog-form" ).dialog({
					autoOpen: false,
					width: 350,
					modal: true,
					buttons: {
                        Delete: function() {
                            if (confirm('Are you sure you want to delete record id ' + $("#currentid").val() + '?')) {
                                $("#data_action").val("delete");
                                $(this).dialog("close");
                                document.getElementById("dialogform").submit();
                            }
                        },
						"Save": function() {

							if ($("#currentid").val() == 0){
								$("#data_action").val("addnew");
							} else {
								$("#data_action").val("update");
							}

                            var title = $("#title").val(), external_id = $("#external_id").val(), custom_1 = $("#custom_1").val();

                            if ((title.indexOf('\'') >= 0) || (title.indexOf('\"') >= 0)) {
                                alert('Text must not contain quote characters');
                                $("#title").focus();
							} else if ((external_id.indexOf('\'') >= 0) || (external_id.indexOf('\"') >= 0)) {
                                alert('Text must not contain quote characters');
                                $("#external_id").focus();
                            } else if ((custom_1.indexOf('\'') >= 0) || (custom_1.indexOf('\"') >= 0)) {
                                alert('Text must not contain quote characters');
                                $("#custom_1").focus();
                            } else {
								$( this ).dialog( "close" );
								document.getElementById("dialogform").submit();
							}
						},
						Cancel: function() {
							$( this ).dialog( "close" );
						}
					}
				});
		
				$( "#addmodule" )
					.button()
					.click(function() {
						$('#dialog-form').dialog('option', 'title', 'Add Class Module');
						$("#currentid").val("0");

						$("#external_id").val("");
						$("#title").val("");
						$("#lookup_coursetype_id").val("");
						$("#custom_1").val("");

						$( "#dialog-form" ).dialog( "open" );
					});
			});

            function edititem(d){

				$('#dialog-form').dialog('option', 'title', 'Update Class Module');

                $("#currentid").val(d['id']);
                $("#external_id").val(d['external_id']);
                $("#title").val(d['title']);
                $("#lookup_coursetype_id").val(d['lookup_coursetype_id']);
                $("#custom_1").val(d['custom_1']);

				$( "#dialog-form" ).dialog( "open" );
			}
		</script>

		<script type="text/javascript" charset="utf-8">
			$(document).ready(function() {
				$( ".calendarbox" ).datepicker({
					changeMonth: true,
					changeYear: true
				});
				/* Add a click handler to the rows - this could be used as a callback */
				$(".tablegrid tbody").click(function(event) {
					$(oTable.fnSettings().aoData).each(function (){
						$(this.nTr).removeClass('row_selected');
					});
					$(event.target.parentNode).addClass('row_selected');
				});
	 
				/* Add a click handler for the delete row */
				$('#delete').click( function() {
					var anSelected = fnGetSelected( oTable );
					oTable.fnDeleteRow( anSelected[0] );
				} );
	 
				/* Init the table */
				oTable = $('.tablegrid').dataTable({
					"bJQueryUI": true,
					"sPaginationType": "full_numbers"
				});
				$("#peopleadd").validate();

			} );

			/* Get the rows which are currently selected */
			function fnGetSelected( oTableLocal ){
				var aReturn = new Array();
				var aTrs = oTableLocal.fnGetNodes();
				 
				for ( var i=0 ; i<aTrs.length ; i++ ){
					if ( $(aTrs[i]).hasClass('row_selected') ){
						aReturn.push( aTrs[i] );
					}
				}
				return aReturn;
			}
			
		</script>
	</head>
	<body  class="yui-skin-sam">
<div id="dialog-form" title="Add/Update Class Module">
	<p class="validateTips">All form fields are required.</p>

	<form id="dialogform" method="post">
		<fieldset>
			<label for="external_id"><?php echo t('Module Number');?></label>
			<input type="text" name="external_id" id="external_id" class="text ui-widget-content ui-corner-all" />

            <label for="title"><?php echo t('Module Name');?></label>
            <input type="text" name="title" id="title" class="text ui-widget-content ui-corner-all" />

            <label for="lookup_coursetype_id"><?php echo t('Course Type');?></label>
            <select type="text" name="lookup_coursetype_id" id="lookup_coursetype_id" class="text ui-widget-content ui-corner-all">
                <?php
                foreach ($this->coursetypes as $ct){
                    echo "<option value=\"" . $ct['id'] . "\">" . $ct['coursetype'] . "</option>\n";
                }
                ?>
            </select>

            <label for="custom_1"><?php echo t('ps class modules custom 1');?></label>
            <input type="text" name="custom_1" id="custom_1" class="text ui-widget-content ui-corner-all" />

		</fieldset>
		<input type="hidden" name="currentid" id="currentid" value="0" class="text ui-widget-content ui-corner-all" />
        <input type="hidden" name="data_action" id="data_action" value="0" class="text ui-widget-content ui-corner-all" />
	</form>
</div>
		<div id="pageHolder">
			<div id="header"><?php echo $header; ?></div>
			<div id="content" class="adminDiv">
				<div id="navAdmin"><?php echo $nav;?></div>
				<div id="contentAdmin" style="width : 900px;">
					<div id="contentheader">
						<h2><?php echo $this->header; ?></h2>
					</div>
	
					<div class="pad20"></div>
					<div style="width :100%;">
						<table cellpadding="0" cellspacing="0" border="0" class="display tablegrid" id="" style="width:100%">
							<thead>
								<tr>
									<th><?php echo t('ID'); ?></th>
									<th><?php echo t('Module Number'); ?></th>
                                    <th><?php echo t('Module Name'); ?></th>
                                    <th><?php echo t('Course Type'); ?></th>
                                    <th><?php echo t('ps class modules custom 1'); ?></th>
								</tr>
							</thead>
							<tbody>
					
<?php
	foreach ($this->modules as $mod){
?>
                                <tr class="GradeA" style="cursor : pointer;" onclick='edititem(<?php echo json_encode($mod); ?>);'>
                                    <td><?php echo $mod['id']; ?></td>
                                    <td><?php echo $mod['external_id']; ?></td>
                                    <td><?php echo $mod['title']; ?></td>
                                    <td><?php echo $this->coursetypes[$mod['lookup_coursetype_id']]['coursetype']; ?></td>
                                    <td><?php echo $mod['custom_1']; ?></td>
								</tr>
<?php
	}
?>
							</tbody>
						</table>
						<div style="text-align : right;">
							<br>
							<input type="button" name="addmodule" id="addmodule" value="Add Class Module" class="tsbutton green large">
						</div>
					</div>
				</div>
				<div class="clear"></div>
				<div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
			</div>
		</div>
	</body>
</html>