<?php 
ob_start();
require_once('views/scripts/header.phtml');
$header = ob_get_contents();
ob_end_clean(); 
ob_start();
require_once('views/scripts/nav-admin.phtml');
$nav = ob_get_contents();
ob_end_clean(); 
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">

	<head>
		<title><?php echo t($this->translation['Application Name']);?> | <?php echo t($this->pageTitle); ?></title>
<?php
	require_once('views/helpers/ScriptContainer.php');
	print ScriptContainer::$instance->renderCSSHead();
	print ScriptContainer::$instance->renderJSHead();
?>
<style>
			input.text { margin-bottom:12px; width:95%; padding: .4em; }
			fieldset { padding:0; border:0; margin-top:25px; text-align : left; font-size : .9em }
			h1 { font-size: 1.2em; margin: .6em 0; }
			.ui-dialog .ui-state-error { padding: .3em; }
			.validateTips { border: 1px solid transparent; padding: 0.3em; }
</style>

<script>

$(document).ready(function() {
	//class table
	$(".tablegrid_class tbody").click(function(event) {
		$(oTable_class.fnSettings().aoData).each(function (){
			$(this.nTr).removeClass('row_selected');
		});
		$(event.target.parentNode).addClass('row_selected');
	});

	$('#delete').click( function() {
		var anSelected = fnGetSelected( oTable_class );
		oTable_class.fnDeleteRow( anSelected[0] );
	} );

	oTable_class = $('.tablegrid_class').dataTable({
		"bJQueryUI": true,
		"sPaginationType": "full_numbers"
	});

	//Clinical table
	$(".tablegrid_clinical tbody").click(function(event) {
		$(oTable_clinical.fnSettings().aoData).each(function (){
			$(this.nTr).removeClass('row_selected');
		});
		$(event.target.parentNode).addClass('row_selected');
	});

	$('#delete').click( function() {
		var anSelected = fnGetSelected( oTable_clinical );
		oTable_clinical.fnDeleteRow( anSelected[0] );
	} );

	oTable_clinical = $('.tablegrid_clinical').dataTable({
		"bJQueryUI": true,
		"sPaginationType": "full_numbers"
	});

	// Licensing table
	$(".tablegrid_licensing tbody").click(function(event) {
		$(oTable_licensing.fnSettings().aoData).each(function (){
			$(this.nTr).removeClass('row_selected');
		});
		$(event.target.parentNode).addClass('row_selected');
	});

	$('#delete').click( function() {
		var anSelected = fnGetSelected( oTable_licensing );
		oTable_licensing.fnDeleteRow( anSelected[0] );
	} );

	oTable_licensing = $('.tablegrid_licensing').dataTable({
		"bJQueryUI": true,
		"sPaginationType": "full_numbers"
	});

} );

			$(function() {
				$( "#dialog-form-class" ).dialog({
					autoOpen: false,
					height: 210,
					width: 350,
					modal: true,
					buttons: {
						"<?php echo t('Save') ?>": function() {
							$("#grade_description_type").val("class");
							$("#grade_description_name").val($("#grade_description_name_class").val());
							var $rows = $(".tablegrid_class tbody tr");
				            for (var i = 0; i < $rows.length; i++) {
				            	if($($rows[i]).children().first().text() == $("#grade_description_name").val()){
					            	alert("Item exists already.");
					            	return false;
				            	}
				            }
							$( this ).dialog( "close" );
							document.getElementById("adminform").submit();
						},
						"<?php echo t('Cancel') ?>": function() {
							$( this ).dialog( "close" );
						}
					}
				});
				$( "#add-grade-description-class" ).button().click(function() {
						$('#dialog-form-class').dialog('option', 'title', 'Add class grade description');
						$( "#dialog-form-class" ).dialog( "open" );
						$("#grade_description_name_class").val("");
						$("#action").val("addnew");
					});

			});

			$(function() {
				$( "#dialog-form-clinical" ).dialog({
					autoOpen: false,
					height: 210,
					width: 350,
					modal: true,
					buttons: {
						"<?php echo t('Save') ?>": function() {
							$("#grade_description_type").val("clinical");
							$("#grade_description_name").val($("#grade_description_name_clinical").val());
							var $rows = $(".tablegrid_clinical tbody tr");
				            for (var i = 0; i < $rows.length; i++) {
				            	if($($rows[i]).children().first().text() == $("#grade_description_name").val()){
					            	alert("Item exists already.");
					            	return false;
				            	}
				            }
							$( this ).dialog( "close" );
							document.getElementById("adminform").submit();
						},
						"<?php echo t('Cancel') ?>": function() {
							$( this ).dialog( "close" );
						}
					}
				});
				$( "#add-grade-description-clinical" ).button().click(function() {
						$('#dialog-form-clinical').dialog('option', 'title', 'Add clinical grade description');
						$( "#dialog-form-clinical" ).dialog( "open" );
						$("#grade_description_name_clinical").val("");
						$("#action").val("addnew");
					});

			});

			$(function() {
				$( "#dialog-form-licensing" ).dialog({
					autoOpen: false,
					height: 210,
					width: 350,
					modal: true,
					buttons: {
						"<?php echo t('Save') ?>": function() {
							$("#grade_description_type").val("licensing");
							$("#grade_description_name").val($("#grade_description_name_licensing").val());
							var $rows = $(".tablegrid_licensing tbody tr");
				            for (var i = 0; i < $rows.length; i++) {
				            	if($($rows[i]).children().first().text() == $("#grade_description_name").val()){
					            	alert("Item exists already.");
					            	return false;
				            	}
				            }
							$( this ).dialog( "close" );
							document.getElementById("adminform").submit();
						},
						"<?php echo t('Cancel') ?>": function() {
							$( this ).dialog( "close" );
						}
					}
				});
				$( "#add-grade-description-licensing" ).button().click(function() {
						$('#dialog-form-licensing').dialog('option', 'title', 'Add licensing grade description');
						$( "#dialog-form-licensing" ).dialog( "open" );
						$("#grade_description_name_licensing").val("");
						$("#action").val("addnew");
					});

			});

			function deleteitem(id, name){
				if(confirm("Do you want to delete '" + name + "' description?")){
				    $("#id").val(id);
				    $("#action").val("delete");
				    document.getElementById("adminform").submit();
				}
			}

			function edititem(form, name, id,itxt){
				$('#' + form).dialog('option', 'title', '<?php echo t('Update grade description') ?>');
				$("#id").val(id);
				$("#" + name).val(itxt);
				$("#action").val("edit");
				$( "#" + form ).dialog( "open" );
			}

		</script>
	</head>
	
	<body  class="yui-skin-sam">

<div id="dialog-form-class" title="Update class grade description">
	<form method="post">
		<fieldset>
			<label for="name"><?php echo t('Grade description')?></label>
			<input type="text" name="grade_description_name_class" id="grade_description_name_class" class="text ui-widget-content ui-corner-all" />
		</fieldset>
	</form>
</div>

<div id="dialog-form-clinical" title="Update clinical grade description">
	<form method="post">
		<fieldset>
			<label for="name"><?php echo t('Grade description')?></label>
			<input type="text" name="grade_description_name_clinical" id="grade_description_name_clinical" class="text ui-widget-content ui-corner-all" />
		</fieldset>
	</form>
</div>

<div id="dialog-form-licensing" title="Update licensing grade description">
	<form method="post">
		<fieldset>
			<label for="name"><?php echo t('Grade description')?></label>
			<input type="text" name="grade_description_name_licensing" id="grade_description_name_licensing" class="text ui-widget-content ui-corner-all" />
		</fieldset>
	</form>
</div>

<div id="pageHolder">
    <div id="header"><?php echo $header; ?></div>
	<div id="content" class="adminDiv">
				<div id="navAdmin"><?php echo $nav;?></div>
				
<div id="contentAdmin" style="width : 900px;">
				
<!-- Class table -->	
<div id="contentheader"><h2>Class grade description</h2></div><br>
<div style="width :100%;">
<table cellpadding="0" cellspacing="0" border="0" class="display tablegrid_class" id="" style="width:100%">
	<thead>
		<tr>
		 <th><?php echo t('Grade description');?></th>
		<th width=100px><?php echo t('Action');?></th>
		</tr>
	</thead>
	<tbody>
<?php
$i = 0;
	foreach ($this->lookup as $lookup){
	    if($lookup['grade_description_type'] === 'class'){
?>
<tr>
	<td class=""><?php echo $lookup['grade_description_name']; ?></td>
	<td>
	<a href="javascript:edititem('dialog-form-class','grade_description_name_class','<?php echo $lookup['id']; ?>','<?php echo $lookup['grade_description_name']; ?>');">Edit</a> 
	<a href="javascript:deleteitem('<?php echo $lookup['id']; ?>','<?php echo $lookup['grade_description_name']; ?>');">Delete</a></td>
</tr>
<?php
$i = $i+1;
	    }
	}
?>
	</tbody>
</table><br>
<div style="text-align : right;">
	<input type="submit" name="add-grade-description-class" id="add-grade-description-class" value="<?php echo t('Add class grade description');?>" class="tsbutton green large">
</div>
</div>
<br><br>

<!-- Clinical table -->
<div id="contentheader"><h2>Clinical grade description</h2><br></div>
<div style="width :100%;">
<table cellpadding="0" cellspacing="0" border="0" class="display tablegrid_clinical" id="" style="width:100%">
							<thead>
								<tr>
									<th><?php echo t('Grade description');?></th>
									<th width=100px><?php echo t('Action');?></th>
								</tr>
							</thead>
							<tbody>
<?php
$i = 0;
	foreach ($this->lookup as $lookup){
	    if($lookup['grade_description_type'] === 'clinical'){
?>
<tr>
	<td class=""><?php echo $lookup['grade_description_name']; ?></td>
	<td>
	<a href="javascript:edititem('dialog-form-clinical','grade_description_name_clinical','<?php echo $lookup['id']; ?>','<?php echo $lookup['grade_description_name']; ?>');">Edit</a> 
	<a href="javascript:deleteitem('<?php echo $lookup['id']; ?>', '<?php echo $lookup['grade_description_name']; ?>');">Delete</a></td>
</tr>
<?php
$i = $i+1;
	    }
	}
?>
							</tbody>
						</table><br>
<div style="text-align : right;">
	<input type="submit" name="add-grade-description-clinical" id="add-grade-description-clinical" value="<?php echo t('Add clinical grade description');?>" class="tsbutton green large">
</div>
</div>
<br><br>

<!-- licensing table -->	
<div id="contentheader"><h2>Licensing grade description</h2></div><br>
<div style="width :100%;">
<table cellpadding="0" cellspacing="0" border="0" class="display tablegrid_licensing" id="" style="width:100%">
	<thead>
		<tr>
		 <th><?php echo t('Grade description');?></th>
		<th width=100px><?php echo t('Action');?></th>
		</tr>
	</thead>
	<tbody>
<?php
$i = 0;
	foreach ($this->lookup as $lookup){
	    if($lookup['grade_description_type'] === 'licensing'){
?>
<tr>
	<td class=""><?php echo $lookup['grade_description_name']; ?></td>
	<td>
	<a href="javascript:edititem('dialog-form-licensing','grade_description_name_licensing','<?php echo $lookup['id']; ?>','<?php echo $lookup['grade_description_name']; ?>');">Edit</a> 
	<a href="javascript:deleteitem('<?php echo $lookup['id']; ?>','<?php echo $lookup['grade_description_name']; ?>');">Delete</a></td>
</tr>
<?php
$i = $i+1;
	    }
	}
?>
	</tbody>
</table><br>
<div style="text-align : right;">
	<input type="submit" name="add-grade-description-licensing" id="add-grade-description-licensing" value="<?php echo t('Add licensing grade description');?>" class="tsbutton green large">
</div>
</div>
<br><br>

</div>

<form action="" id="adminform" method="post" class="formvalidate">
    <input type="hidden" name="action" id="action" value="">
    <input type="hidden" name="grade_description_name" id="grade_description_name" value="">
    <input type="hidden" name="grade_description_type" id="grade_description_type" value="">
    <input type="hidden" name="id" id="id" value="">
</form>


<div class="clear"></div>
<div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
</div>
</div>
		
	</body>
</html>