<?php 

// template for page that contains an EditTable

// need $pageTitle and $nextUri variables from these includes
  
ob_start();
require_once('views/scripts/header.phtml');
$header = ob_get_contents();
ob_end_clean(); 

ob_start();
require_once('views/scripts/nav-admin.phtml');
$nav = ob_get_contents();
ob_end_clean(); 

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<title><?php echo $this->translation['Application Name'];?> | <?php echo $pageTitle; ?></title>
<?php
	require_once('views/helpers/ScriptContainer.php');
	print ScriptContainer::$instance->renderCSSHead();
	print ScriptContainer::$instance->renderJSHead();
?>

		<style>
			fieldset input[type=text], fieldset select { margin-bottom:12px; width:95%; padding: .4em; }
			fieldset { padding:0; border:0; margin-top:25px; text-align : left; font-size : .9em }
			h1 { font-size: 1.2em; margin: .6em 0; }
			.ui-dialog .ui-state-error { padding: .3em; }
			.validateTips { border: 1px solid transparent; padding: 0.3em; }
		</style>
		<script>
			$(function() {
			});

		</script>

		<script type="text/javascript" charset="utf-8">
		</script>
	</head>
	<body  class="yui-skin-sam">
		<div id="pageHolder">
			<div id="header"><?php echo $header; ?></div>
			<div id="content" class="adminDiv">
				<div id="navAdmin"><?php echo $nav;?></div>
				<div id="contentAdmin" style="width : 900px;">
					<div id="contentheader">
						<h2><?php echo $this->header; ?></h2>
					</div>
	
					<form  action="" id="peopleadd" method="post">
						<div class="mainformholder">
							<div class="pad50 clear"></div>
								<div class="pad20"></div>
								<div style="width :100%;">
<?php
	foreach ($this->allfields as $field){
		$caption = $field;
		if (substr($caption, 0, 3) == "ps "){
			$caption = substr($caption, 3);
		}
		$caption = ucwords(strtolower(trim($caption)));

		$value = "";
		foreach ($this->fieldvalues as $fieldvalue){
			if ($fieldvalue['key_phrase'] == $field){
				$value = $fieldvalue['phrase'];
			}
		}
		echo "<label>" . $caption . "<span style=\"font-size : 10px;\"></span></label>\n";
		echo "<input type=\"text\" name=\"fields[" . $field . "]\" name=\"fields[" . $field . "]\" value=\"" . $value . "\">\n";
	}

#		var_dump($this->fieldvalues);
#		var_dump($this->allfields);
?>
								</div>
								<div class="rightdiv">
									<div class="pad20"></div>
									<input type="submit" name="update" value="Update Labels &raquo;" class="tsbutton green large">
								</div>
							<div class="clear"></div>
					</div>
					<input type="hidden" name="action" id="action" value="savelabels">
					</form>
					<div class="clear"></div>
				</div>
				<div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
				<div class="clear"></div>
			</div>
		</div>
	</body>
</html>