<?php 
ob_start();
require_once('views/scripts/header.phtml');
$header = ob_get_contents();
ob_end_clean(); 
ob_start();
require_once('views/scripts/nav-admin.phtml');
$nav = ob_get_contents();
ob_end_clean(); 
?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">

	<head>
		<title><?php echo t($this->translation['Application Name']);?> | <?php echo t($this->pageTitle); ?></title>
<?php
	require_once('views/helpers/ScriptContainer.php');
	print ScriptContainer::$instance->renderCSSHead();
	print ScriptContainer::$instance->renderJSHead();

?>
		<style>
			input.text { margin-bottom:12px; width:95%; padding: .4em; }
			fieldset { padding:0; border:0; margin-top:25px; text-align : left; font-size : .9em }
			h1 { font-size: 1.2em; margin: .6em 0; }
			.ui-dialog .ui-state-error { padding: .3em; }
			.validateTips { border: 1px solid transparent; padding: 0.3em; }
		</style>

		<script>
		
			$(function() {
				$( "#dialog-form" ).dialog({
					autoOpen: false,
					height: 250,
					width: 350,
					modal: true,
					buttons: {
						"<?php echo t('Save') ?>": function() {
							$("#degree_institution").val($("#title").val());
							$("#id").val($("#currentid").val());
							if ($("#currentid").val() == 0){
								$("#action").val("addnew");
							} else {
								$("#action").val("update");
							}
							$( this ).dialog( "close" );
							document.getElementById("adminform").submit();
						},
						"<?php echo t('Cancel') ?>": function() {
							$( this ).dialog( "close" );
						}
					},
					close: function() {}
				});
				$( "#update" )
					.button()
					.click(function() {
						$('#dialog-form').dialog('option', 'title', 'Add degree institution');
						$("#currentid").val("0");
						$("#title").val("");
						$( "#dialog-form" ).dialog( "open" );
					});
			});

			function edititem(iid,itxt){
				$('#dialog-form').dialog('option', 'title', '<?php echo t("Update degree institution")?>');
				$("#currentid").val(iid);
				$("#title").val(itxt);
				$( "#dialog-form" ).dialog( "open" );

			}

			function deleteitem(sel_row, iid){
				oTable.fnDeleteRow( sel_row );
				$("#currentid").val(iid);
				$("#id").val($("#currentid").val());
				if ($("#currentid").val() != 0){
					$("#action").val("delete");
				}
				document.getElementById("adminform").submit();
			}

		</script>

		<script type="text/javascript" charset="utf-8">

			$(document).ready(function() {
				$( ".calendarbox" ).datepicker({
					changeMonth: true,
					changeYear: true
				});

				/* Add a click handler to the rows - this could be used as a callback */

				$(".tablegrid tbody").click(function(event) {
					$(oTable.fnSettings().aoData).each(function (){
						$(this.nTr).removeClass('row_selected');
					});
					$(event.target.parentNode).addClass('row_selected');
				});

	 
				$('#delete').click( function() {
					var anSelected = fnGetSelected( oTable );
					oTable.fnDeleteRow( anSelected[0] );
				} );

				oTable = $('.tablegrid').dataTable({
					"bJQueryUI": true,
					"sPaginationType": "full_numbers"
				});
				$("#peopleadd").validate();
			} );


			function fnGetSelected( oTableLocal ){
				var aReturn = new Array();
				var aTrs = oTableLocal.fnGetNodes();
				for ( var i=0 ; i<aTrs.length ; i++ ){
					if ( $(aTrs[i]).hasClass('row_selected') ){
						aReturn.push( aTrs[i] );
					}
				}
				return aReturn;
			}

		</script>

	</head>

	<body  class="yui-skin-sam">

<div id="dialog-form" title="Update degree institution">
	<form method="post">
		<fieldset>
			<label for="name"><?php echo t('Degree institution')?></label>
			<input type="text" name="title" id="title" class="text ui-widget-content ui-corner-all" />
		</fieldset>
		<input type="hidden" name="currentid" id="currentid" class="text ui-widget-content ui-corner-all" />
	</form>
</div>

		<div id="pageHolder">
			<div id="header"><?php echo $header; ?></div>
			<div id="content" class="adminDiv">
				<div id="navAdmin"><?php echo $nav;?></div>
				<div id="contentAdmin" style="width : 900px;">
					<div id="contentheader">
						<h2><?php echo $this->header; ?></h2>
					</div>
					<div class="pad20"></div>
					<div style="width :100%;">
						<table cellpadding="0" cellspacing="0" border="0" class="display tablegrid" id="" style="width:100%">
							<thead>
								<tr>
									<th><?php echo t('ID');?></th>
									<th><?php echo t('Title');?></th>
									<th width=100px><?php echo t('Action');?></th>
								</tr>
							</thead>
							<tbody>

<?php
$i = 0;
	foreach ($this->lookup as $lookup){
?>
<tr>
<td><?php echo $lookup['id']; ?></td>
<td class=""><?php echo $lookup['degree_institution']; ?></td>
<td><a href="javascript:edititem('<?php echo $lookup['id']; ?>','<?php echo ($lookup['degree_institution']); ?>');">Edit</a>
<?php if(!$lookup['used']){?>
<a href="javascript:deleteitem('<?php echo $i; ?>','<?php echo $lookup['id']; ?>');">Delete</a>
<?php }?>
</td>
</tr>
<?php
$i = $i+1;
	}
?>
							</tbody>
						</table>
<div style="text-align : right;">
							<br>
							<input type="submit" name="update" id="update" value="<?php echo t('Add degree institution');?>" class="tsbutton green large">
						</div>
					</div>

<form action="" id="adminform" method="post" class="formvalidate">
<input type="hidden" name="action" id="action" value="addnew">
<input type="hidden" name="degree_institution" id="degree_institution" value="">
<input type="hidden" name="id" id="id" value="0">
</form>
				</div>
				<div class="clear"></div>
				<div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
			</div>
		</div>
	</body>
</html>