<?php

// template for page that contains an EditTable

// need $pageTitle and $nextUri variables from these includes

ob_start();
require_once('views/scripts/header.phtml');
$header = ob_get_contents();
ob_end_clean();

ob_start();
require_once('views/scripts/nav-admin.phtml');
$nav = ob_get_contents();
ob_end_clean();

?>
<!DOCTYPE html>
<html>
<head>
	<title><?php echo $this->translation['Application Name'];?> | <?php echo t($this->pageTitle); ?></title>
	<?php
	require_once('views/helpers/ScriptContainer.php');
	print ScriptContainer::$instance->renderCSSHead();
	print ScriptContainer::$instance->renderJSHead();
	?>

	<style>
		fieldset input[type=text], fieldset select { margin-bottom:12px; width:95%; padding: .4em; }
		fieldset { padding:0; border:0; margin-top:25px; text-align : left; font-size : .9em }
		h1 { font-size: 1.2em; margin: .6em 0; }
		.ui-dialog .ui-state-error { padding: .3em; }
		.validateTips { border: 1px solid transparent; padding: 0.3em; }
	</style>
	<script>
		$(function() {
			$( "#dialog-form" ).dialog({
				autoOpen: false,
				width: 350,
				modal: true,
				buttons: {
				    "<?php echo t('Delete'); ?>": function() {
                        if (confirm("Are you sure you want to delete this class?\n\nThis will remove it from the cohort and delete associated student grades."))
                        {
                            $("#_id").val($("#currentid").val());
                            $("#_action").val("delete");
                            document.getElementById('adminform').submit();
                        }
                    },
					"<?php echo t('Save') ?>": function() {
						$("#_classname").val($("#classname").val());
						$("#_startdate").val($("#startdate").val());
						$("#_enddate").val($("#enddate").val());
						$("#_instructorid").val($("#instructorid").val());
						$("#_coursetypeid").val($("#coursetypeid").val());
						$("#_coursetopic").val($("#coursetopic").val());

						$("#_class_modules_id").val($("#class_modules_id").val());
						$("#_custom_1").val($("#custom_1").val());
						$("#_credits").val($("#credits").val());
						$("#_custom_2").val($("#custom_2").val());

						$("#_id").val($("#currentid").val());
						if ($("#currentid").val() == 0){
							$("#_action").val("addnew");
						} else {
							$("#_action").val("update");
						}

 						if ($("#startdate").val() == ""){
 							alert ('Please enter a start date');
 							$("#startdate").focus();
 						} else if ($("#enddate").val() == ""){
 							alert ('Please enter an end date');
 							$("#enddate").focus();
 						} else if (Date.parse($("#enddate").val()) <= Date.parse($("#startdate").val())){
							alert ('<?php //echo t('The end date cannot be before the start date')?>');
 							$("#enddate").focus();
 						} else {
 							$( this ).dialog( "close" );
 							document.getElementById("adminform").submit();
 						}
					},
					"<?php echo t('Cancel') ?>": function() {
						$( this ).dialog( "close" );
					}
				},
				close: function() {

				}
			});

			$( "#update" )
				.button()
				.click(function() {
					$('#dialog-form').dialog('option', 'title', '<?php echo t('Add class')?>');
					$("#currentid").val("0");

					$("#classname").val("");
					$("#startdate").val("");
					$("#enddate").val("");
					$("#coursetopic").val("");

					$( "#dialog-form" ).dialog( "open" );
				});
		});

		function edititem(d){

			$('#dialog-form').dialog('option', 'title', '<?php echo t('Update class')?>');
			$("#currentid").val(d['id']);

			$("#classname").val(d['classname']);
			$("#startdate").val(d['startdate']);
			$("#enddate").val(d['enddate']);
			$("#instructorid").val(d['instructorid']);
			$("#coursetypeid").val(d['coursetypeid']);
			$("#coursetopic").val(d['coursetopic']);

			$("#class_modules_id").val(d['class_modules_id']);
			$("#custom_1").val(d['custom_1']);
			$("#credits").val(d['maxcredits']);
			$("#custom_2").val(d['custom_2']);

			$( "#dialog-form" ).dialog( "open" );
		}
	</script>

	<script type="text/javascript" charset="utf-8">
		$(document).ready(function() {
			$( ".calendarbox" ).datepicker({
				changeMonth: true,
				changeYear: true
			});
			/* Add a click handler to the rows - this could be used as a callback */
			$(".tablegrid tbody").click(function(event) {
				$(oTable.fnSettings().aoData).each(function (){
					$(this.nTr).removeClass('row_selected');
				});
				$(event.target.parentNode).addClass('row_selected');
			});

			/* Add a click handler for the delete row */
			$('#delete').click( function() {
				var anSelected = fnGetSelected( oTable );
				oTable.fnDeleteRow( anSelected[0] );
			} );

			/* Init the table */
			oTable = $('.tablegrid').dataTable({
				"bJQueryUI": true,
                "iDisplayLength": 25,
				"sPaginationType": "full_numbers"
			});
			$("#peopleadd").validate();

		} );

		/* Get the rows which are currently selected */
		function fnGetSelected( oTableLocal ){
			var aReturn = new Array();
			var aTrs = oTableLocal.fnGetNodes();

			for ( var i=0 ; i<aTrs.length ; i++ ){
				if ( $(aTrs[i]).hasClass('row_selected') ){
					aReturn.push( aTrs[i] );
				}
			}
			return aReturn;
		}

	</script>
</head>
<body  class="yui-skin-sam">
<div id="dialog-form" title="Update class">
	<form method="post">
		<fieldset>
			<label for="classname"><?php echo t('Class name');?></label>
			<input type="text" name="classname" id="classname" class="text ui-widget-content ui-corner-all" />
			<label for="coursetypeid"><?php echo t('Course Name');?></label>

            <?php
            echo $this->formSelect('coursetypeid', '', array('id' => 'coursetypeid', 'class' => "text ui-widget-content ui-corner-all"), $this->coursetypes);
            ?>
			<label for="coursetopic"><?php echo t('Topic');?></label>
			<input type="text" name="coursetopic" id="coursetopic" class="text ui-widget-content ui-corner-all" />
			<label for="startdate"><?php echo t('Start date');?></label>
			<input type="text" name="startdate" id="startdate" class="calendarbox text ui-widget-content ui-corner-all" />
			<label for="enddate"><?php echo t('End date');?></label>
			<input type="text" name="enddate" id="enddate" class="calendarbox text ui-widget-content ui-corner-all" />
			<label for="instructorid"><?php echo t('Instructor');?></label>
            <?php
            echo $this->formSelect('instructorid', '', array('id' => 'instructorid', 'class' => "text ui-widget-content ui-corner-all"), $this->tutors);
            ?>
			<?php if ($this->setting['site_style'] == 'skillsmart') { ?>
				<label for="class_modules_id">Module</label>
				<select name="class_modules_id" id="class_modules_id" class="text ui-widget-content ui-corner-all">
					<?php
					foreach ($this->modules as $module){
						echo "<option value=\"" . $module['id'] . "\">" . $module['external_id'] . " - " . $module['title'] . "</option>\n";
					}
					?>
				</select>
				<label for="custom_1">Short Name</label>
				<input type="text" name="custom_1" id="custom_1" class="text ui-widget-content ui-corner_all" />
				<label for="credits">Credits</label>
				<input type="text" name="credits" id="credits" class="text ui-widget-content ui-corner_all" />
				<label for="custom_2">Weight</label>
				<input type="text" name="custom_2" id="custom_2" class="text ui-widget-content ui-corner_all" />
			<?php } ?>

		</fieldset>
		<input type="hidden" name="currentid" id="currentid" class="text ui-widget-content ui-corner-all" />
	</form>
</div>

<div id="pageHolder">
	<div id="header"><?php echo $header; ?></div>
	<div id="content" class="adminDiv">
		<div id="navAdmin"><?php echo $nav;?></div>
		<div id="contentAdmin" style="width : 900px;">
			<div id="contentheader">
				<h2><?php echo $this->header; ?></h2>
			</div>

			<div class="pad20"></div>
			<div style="width :100%;">
				<table cellpadding="0" cellspacing="0" border="0" class="display tablegrid" id="" style="width:100%">
					<thead>
					<tr>
						<th><?php echo t('ID');?></th>
						<th><?php echo t('Title');?></th>
						<th>Course Type</th>
						<th>Course Topic</th>
						<th>Start Date</th>
						<th>End Date</th>
						<th>Instructor</th>
						<?php if ($this->setting['site_style'] == 'skillsmart') { ?>
							<th>Module</th>
							<th>Short Name</th>
							<th>Credits</th>
							<th>Weight</th>
						<?php }  ?>
					</tr>
					</thead>
					<tbody>

					<?php
					foreach ($this->lookup as $lookup){
						?>
						<tr class="GradeA" style="cursor : pointer;" onclick='edititem(<?php echo json_encode($lookup, JSON_HEX_QUOT|JSON_HEX_APOS); ?>);'>

							<td><?php echo $lookup['id']; ?></td>
							<td><?php echo $lookup['classname']; ?></td>
							<td><?php echo $lookup['coursetype']; ?></td>
							<td><?php echo addslashes($lookup['coursetopic']); ?></td>
							<td><?php echo $lookup['startdate']; ?></td>
                            <td><?php echo $lookup['enddate']; ?></td>
							<td><?php echo trim($lookup['instructor']) != ',' ? $lookup['instructor'] : ''; ?></td>
							<?php if ($this->setting['site_style'] == 'skillsmart') { ?>
								<td><?php echo $this->modules[$lookup['class_modules_id']]['title'] ?></td>
								<td><?php echo $lookup['custom_1'] ?></td>
								<td><?php echo $lookup['maxcredits'] ?></td>
								<td><?php echo $lookup['custom_2'] ?></td>
							<?php } ?>
						</tr>
					<?php
					}
					?>
					</tbody>
				</table>
				<div style="text-align : right;">
					<br>
					<input type="submit" name="update" id="update" value="<?php echo t('Add class');?>" class="tsbutton green large">
				</div>
			</div>

			<form action="" id="adminform" method="post" class="formvalidate">
				<input type="hidden" name="_action" id="_action" value="addnew" />
				<input type="hidden" name="_classname" id="_classname" value="" />
				<input type="hidden" name="_startdate" id="_startdate" value="" />
				<input type="hidden" name="_enddate" id="_enddate" value="" />
				<input type="hidden" name="_instructorid" id="_instructorid" value="" />
				<input type="hidden" name="_coursetypeid" id="_coursetypeid" value="" />
				<input type="hidden" name="_coursetopic" id="_coursetopic" value="" />
				<input type="hidden" name="_id" id="_id" value="0" />
				<input type="hidden" name="_class_modules_id" id="_class_modules_id" value="" />
				<input type="hidden" name="_custom_1" id="_custom_1" value="" />
				<input type="hidden" name="_credits" id="_credits" value="" />
				<input type="hidden" name="_custom_2" id="_custom_2" value="" />
			</form>

		</div>
		<div class="clear"></div>
		<div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
	</div>
</div>
</body>
</html>