<?php 

if ($this->showcomp){
	$caption = "competency question";
} else {
	$caption = "competency";
}

// template for page that contains an EditTable

// need $pageTitle and $nextUri variables from these includes
  
ob_start();
require_once('views/scripts/header.phtml');
$header = ob_get_contents();
ob_end_clean(); 

ob_start();
require_once('views/scripts/nav-admin.phtml');
$nav = ob_get_contents();
ob_end_clean(); 

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<title><?php echo $this->translation['Application Name'];?> | <?php echo $pageTitle; ?></title>
<?php
	require_once('views/helpers/ScriptContainer.php');
	print ScriptContainer::$instance->renderCSSHead();
	print ScriptContainer::$instance->renderJSHead();
?>

		<style>
			input.text { margin-bottom:12px; width:95%; padding: .4em; }
			fieldset { padding:0; border:0; margin-top:25px; text-align : left; font-size : .9em }
			h1 { font-size: 1.2em; margin: .6em 0; }
			.ui-dialog .ui-state-error { padding: .3em; }
			.validateTips { border: 1px solid transparent; padding: 0.3em; }
		</style>
		<script>
<?php
	if ($this->showcomp){
		// VIEWING DETAILS FOR QUESTIONS ON COMPETENCY
?>
			$(function() {
				$( "#dialog-form-detail" ).dialog({
					autoOpen: false,
					height: 350,
					width: 350,
					modal: true,
					buttons: {
						"Save": function() {
							$("#_fieldtoupdatedetail").val($("#titledetail").val());
							$("#_iddetail").val($("#currentiddetail").val());
							$("#_orderdetail").val($("#orderdetail").val());
							$("#_qtypedetail").val($("#typedetail").val());
							if ($("#currentiddetail").val() == 0){
								$("#_actiondetail").val("addnew");
							} else {
								$("#_actiondetail").val("update");
							}
							$( this ).dialog( "close" );
							document.getElementById("adminformdetail").submit();
						},
						Cancel: function() {
							$( this ).dialog( "close" );
						}
					},
					close: function() {
						//allFields.val( "" ).removeClass( "ui-state-error" );
					}
				});
		
				$( "#update" )
					.button()
					.click(function() {
						$('#dialog-form-detail').dialog('option', 'title', 'Add <?php echo $caption ?>');
						$("#currentiddetail").val("0");
						$("#titledetail").val("");
						$("#orderdetail").val("<?php echo(count($this->questions) + 1) ?>");
						$("#typedetail").val('questionmulti');

						$( "#dialog-form-detail" ).dialog( "open" );
					});

				$( "#updatequalification" )
					.button()
					.click(function() {
						$('#qualform').submit();
					});

			});

			function edititemdetail(iid,itxt,iorder,itp){
				$('#dialog-form-detail').dialog('option', 'title', 'Update <?php echo $caption ?>');
				$("#currentiddetail").val(iid);
				$("#titledetail").val(itxt);
				$("#orderdetail").val(iorder);
				$("#typedetail").val(itp);
				$( "#dialog-form-detail" ).dialog( "open" );
			}
<?php
	} else {
		// VIEWING COMPETENCY LISTINGS
?>
			$(function() {
				$( "#dialog-form" ).dialog({
					autoOpen: false,
					height: 250,
					width: 350,
					modal: true,
					buttons: {
						"Save": function() {
							$("#_fieldtoupdate").val($("#title").val());
							$("#_id").val($("#currentid").val());
							if ($("#currentid").val() == 0){
								$("#_action").val("addnew");
							} else {
								$("#_action").val("update");
							}
							$( this ).dialog( "close" );
							document.getElementById("adminform").submit();
						},
						Cancel: function() {
							$( this ).dialog( "close" );
						}
					},
					close: function() {
						//allFields.val( "" ).removeClass( "ui-state-error" );
					}
				});
		
				$( "#update" )
					.button()
					.click(function() {
						$('#dialog-form').dialog('option', 'title', 'Add <?php echo $caption ?>');
						$("#currentid").val("0");
						$("#title").val("");
						$( "#dialog-form" ).dialog( "open" );
					});

			});

			function edititem(iid,itxt){
				$('#dialog-form').dialog('option', 'title', 'Update <?php echo $caption ?>');
				$("#currentid").val(iid);
				$("#title").val(itxt);
				$( "#dialog-form" ).dialog( "open" );
			}

<?php
	}
?>


		</script>

		<script type="text/javascript" charset="utf-8">
			$(document).ready(function() {
				$( ".calendarbox" ).datepicker({
					changeMonth: true,
					changeYear: true
				});
				/* Add a click handler to the rows - this could be used as a callback */
				$(".tablegrid tbody").click(function(event) {
					$(oTable.fnSettings().aoData).each(function (){
						$(this.nTr).removeClass('row_selected');
					});
					$(event.target.parentNode).addClass('row_selected');
				});
	 
				/* Add a click handler for the delete row */
				$('#delete').click( function() {
					var anSelected = fnGetSelected( oTable );
					oTable.fnDeleteRow( anSelected[0] );
				} );
	 
				/* Init the table */
				oTable = $('.tablegrid').dataTable({
					"bJQueryUI": true,
<?php
	if ($this->showcomp){
		echo "					\"bPaginate\": false,\n";
		echo "					\"bSort\": false,\n";
	} else {
		echo "					\"sPaginationType\": \"full_numbers\",\n";
	}
?>
				});
				$("#peopleadd").validate();



			} );

			/* Get the rows which are currently selected */
			function fnGetSelected( oTableLocal ){
				var aReturn = new Array();
				var aTrs = oTableLocal.fnGetNodes();
				 
				for ( var i=0 ; i<aTrs.length ; i++ ){
					if ( $(aTrs[i]).hasClass('row_selected') ){
						aReturn.push( aTrs[i] );
					}
				}
				return aReturn;
			}
			
		</script>
	</head>
	<body  class="yui-skin-sam">

<?php
	if ($this->showcomp){
?>
<div id="dialog-form-detail" title="Update <?php echo $caption ?>">
	<p class="validateTips">All form fields are required.</p>

	<form method="post">
		<fieldset>
			<label for="name"><?php echo strtoupper($caption) ?></label>
			<input type="text" name="titledetail" id="titledetail" class="text ui-widget-content ui-corner-all" /><br>

			<label for="name">Field order</label>
			<select name="orderdetail" id="orderdetail" class="text ui-widget-content ui-corner-all" style="display : block; width : 100%; padding : .4em;" />
<?php
	for ($i = 0; $i <= count($this->questions); $i++){
		echo "<option value=\"" . ($i + 1) . "\">Position " . ($i + 1) . "</option>\n";
	}
?>
			</select>

			<label for="name">Field type</label>
			<select name="typedetail" id="typedetail" class="text ui-widget-content ui-corner-all" style="display : block; width : 100%; padding : .4em;" />
				<option value="text">Text header</option>
				<option value="questionmulti">Question, A-E options</option>
				<option value="questionyesno">Question, yes/no options</option>
				<option value="questiontext">Question, textbox</option>
			</select>
		</fieldset>
		<input type="hidden" name="currentiddetail" id="currentiddetail" class="text ui-widget-content ui-corner-all" />
	</form>
</div>
		<div id="pageHolder">
			<div id="header"><?php echo $header; ?></div>
			<div id="content" class="adminDiv">
				<div id="navAdmin"><?php echo $nav;?></div>
				<div id="contentAdmin" style="width : 900px;">
					<div id="contentheader">
						<h2><?php echo $this->header; ?></h2>
					</div>
	
					<div class="pad20"></div>
					<div style="width :100%;">
						<table cellpadding="0" cellspacing="0" border="0" class="display tablegrid" id="" style="width:100%">
							<thead>
								<tr>
									<th style="width : 70px;">Order</th>
									<th style="width : 80px;">Type</th>
									<th>Title</th>
									<th style="width : 120px;">Options</th>
								</tr>
							</thead>
							<tbody>
					
<?php
	foreach ($this->questions as $lookup){
?>
								<tr class="GradeA" style="cursor : pointer;">
									<td class=""><?php echo $lookup['itemorder']; ?></td>
<?php
	$tp = "";
	switch ($lookup['itemtype']){
		case "text":
			$tp = "Header";
		break;
		case "questionyesno":
			$tp = "Yes/no";
		break;
		case "questiontext":
			$tp = "Textbox";
		break;
		default:
			$tp = "A-E";
		break;
	}
?>
									<td class=""><?php echo $tp; ?></td>
									<td class=""><?php echo $lookup['question']; ?></td>
									<td class="" style="text-align : right;"><input style="padding : 6px;" type="button" value="Edit" onclick="edititemdetail('<?php echo $lookup['id']; ?>','<?php echo (addslashes($lookup['question'])); ?>','<?php echo($lookup['itemorder']); ?>','<?php echo($lookup['itemtype']); ?>');" /></td>
								</tr>
<?php
	}
?>
							</tbody>
						</table>
						<div style="text-align : right;">
							<br>
							<input type="submit" name="update" id="update" value="Add <?php echo $caption ?>" class="tsbutton green large">
						</div>
						
					</div>
					<div style="margin-top : 50px;">
						<h2>Link to qualification</h2>
						<form method="post" name="qualform" id="qualform">
							<input type="hidden" name="actionqual" id="actionqual" value="1">
							<input type="hidden" name="compid" id="compid" value="<?php echo($this->compid); ?>">

						<table cellpadding="0" cellspacing="0" border="0" class="display tablegrid" id="" style="width:100%">
							<thead>
								<tr>
									<th style="width : 50px;">Link</th>
									<th>Qualification group</th>
								</tr>
							</thead>
							<tbody>

<?php
	foreach ($this->quals as $group){
		echo "<tr><td><input type=\"checkbox\" id=\"qual[]\" name=\"qual[]\" value=\"" . $group['id'] . "\"" . (in_array($group['id'],$this->currentlinks) ? " checked" : "") . "></td><td>" . $group['label'] . "</td></tr>\n";
	}
#	var_dump ($this->quals);
?>
							</tbody>
						</table>
						<div style="float : left; width : 45%; height : 60px;">
							<br>
							<input type="button" name="" id="" value="Back" class="tsbutton green large" onclick="location='/admin/skillsmart-competency'">
						</div>
						<div style="text-align : right; float : right; width : 50%; height : 60px;">
							<br>
							<input type="submit" name="updatequalification" id="updatequalification" value="Update links" class="tsbutton green large">
						</div>
						</form>
					</div>


<form action="" id="adminformdetail" method="post" class="formvalidate">
<input type="hidden" name="_actiondetail" id="_actiondetail" value="addnew">
<input type="hidden" name="_iddetail" id="_iddetail" value="0">
<input type="hidden" name="_fieldtoupdatedetail" id="_fieldtoupdatedetail" value="">
<input type="hidden" name="_orderdetail" id="_orderdetail" value="0">
<input type="hidden" name="_qtypedetail" id="_qtypedetail" value="questionmulti">
</form>

				</div>
				<div class="clear"></div>
				<div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
			</div>
		</div>
<?php
	} else {
?>
<div id="dialog-form" title="Update <?php echo $caption ?>">
	<p class="validateTips">All form fields are required.</p>

	<form method="post">
		<fieldset>
			<label for="name"><?php echo strtoupper($caption) ?></label>
			<input type="text" name="title" id="title" class="text ui-widget-content ui-corner-all" />
		</fieldset>
		<input type="hidden" name="currentid" id="currentid" class="text ui-widget-content ui-corner-all" />
	</form>
</div>

		<div id="pageHolder">
			<div id="header"><?php echo $header; ?></div>
			<div id="content" class="adminDiv">
				<div id="navAdmin"><?php echo $nav;?></div>
				<div id="contentAdmin" style="width : 900px;">
					<div id="contentheader">
						<h2><?php echo $this->header; ?></h2>
					</div>
	
					<div class="pad20"></div>
					<div style="width :100%;">
							<table cellpadding="0" cellspacing="0" border="0" class="display tablegrid" id="" style="width:100%">
								<thead>
									<tr>
										<th>Competency</th>
										<th style="width : 250px;">Options</th>
									</tr>
								</thead>
								<tbody>
					
<?php
	foreach ($this->lookup as $lookup){
?>
									<tr class="GradeA" style="cursor : pointer;">
										<td class=""><?php echo $lookup['label']; ?></td>
										<td class="" style="text-align : right;"><input style="padding : 6px;" type="button" value="Edit name" onclick="edititem('<?php echo $lookup['id']; ?>','<?php echo (addslashes($lookup['label'])); ?>');" /> <input style="padding : 6px;" type="button" value="Add/edit questions" onclick="location='/admin/skillsmart-competency/comp/<?php echo($lookup['id']); ?>'" /></td>
									</tr>
<?php
	}
?>
								</tbody>
							</table>
							<div style="text-align : right;">
								<br>
								<input type="submit" name="update" id="update" value="Add <?php echo $caption ?>" class="tsbutton green large">
							</div>
					</div>


<form action="" id="adminform" method="post" class="formvalidate">
<input type="hidden" name="_action" id="_action" value="addnew">
<input type="hidden" name="_fieldtoupdate" id="_fieldtoupdate" value="">
<input type="hidden" name="_id" id="_id" value="0">
</form>

				</div>
				<div class="clear"></div>
				<div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
			</div>
		</div>
<?php
	}
?>
	</body>
</html>