<?php 

// template for page that contains an EditTable

// need $pageTitle and $nextUri variables from these includes
  
ob_start();
require_once('views/scripts/header.phtml');
$header = ob_get_contents();
ob_end_clean(); 

ob_start();
require_once('views/scripts/nav-admin.phtml');
$nav = ob_get_contents();
ob_end_clean(); 

?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title><?php echo t($this->translation['Application Name']);?> | <?php echo t($this->pageTitle); ?></title>
<?php
require_once('views/helpers/ScriptContainer.php');
print ScriptContainer::$instance->renderCSSHead();
print ScriptContainer::$instance->renderJSHead();
?>
</head>
<body  class="yui-skin-sam">
<div id="pageHolder">
  <div id="header"><?php echo $header; ?></div>
  <div id="content" class="adminDiv">
    
    <div id="navAdmin"><?php echo $nav;?></div>
    
    <div id="contentAdmin">
    <h1><?php echo t($this->pageTitle); ?></h1>
    <?php require_once('views/scripts/user/_add_form.phtml');?>
    </div>
    
     <div class="clear"></div>
	    

<div id="footer"><?php require_once('views/scripts/footer.phtml');?></div>
</div>   </div>
    


</body>
</html>